### PR TITLE
3.0.0 alpha.14.4.0

### PR DESCRIPTION
**Pull request by lauriejim**
GitHub diff: https://github.com/strapi/strapi/compare/v3.0.0-alpha.14.3...v3.0.0-alpha.14.4.0
Migration guide: https://github.com/strapi/strapi/wiki/migration-guide-alpha.14.3-to-alpha.14.4

### CODE REVIEW

**Comment by asharamseervi** [comment]
Might you had forgotten to merge this PR before tagging version !!

**Comment by lauriejim** [comment]
It's here https://github.com/strapi/strapi/releases/tag/v3.0.0-alpha.14.4.0

**Comment by lauriejim** [comment]
In fact `v3.0.0-alpha.14.4.0` === `v3.0.0-alpha.14.4`

**Comment by asharamseervi** [comment]
I want to know, why this version not still merged to master? Any specific reason to release this version with branch? Might I'm missing something, here for learning.

**Pull request merged**
