### PR TITLE
Add the Content Type display control option

### PR DESCRIPTION
**Pull request by cyp3rius**
#### Description of what you did:
Extend the Content Type format function and Model options definition `isManaged` to allow hide / show specified Content Types on purpose.

This modification came as a part of plugin development work.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@Aurelsicoko

**Comment by cyp3rius** [comment]
@Aurelsicoko I will be really glad if you can review and give feedback for this PR. Small, but I think quite handy feature :)

**Comment by alexandrebodin** [comment]
Hello @cyp3rius. The isDisplayed variable is only meant for internal use. Using the same var as a config param will prevent us from using it as an internal option. We should consider another way of doing this that will not make use of internal code.

**Comment by cyp3rius** [comment]
@alexandrebodin I assume you're referring to `isContentTypeDisplayed` function. Happy to change variable to something else like `showInSidebar` or `managedContentType`. Maybe other suggestion?

**Comment by cyp3rius** [comment]
@alexandrebodin @Aurelsicoko code has been reworked, newly introduced parameter `isManaged` both for config and filtering content types in the `<LeftMenu />`.

**Comment by alexandrebodin** [comment]
Hey @cyp3rius thanks for the update. Just wondering if the Admin&Permission feature in 3.1.0 would be enough for this though. That would avoid adding config options

**Comment by cyp3rius** [comment]
@alexandrebodin indeed it's possible to change the visibility via Admin&Permission, just updated & checked this. Otherwise, `isManaged` is mostly for the plugin models, that shouldn't be accessible anyway and here is see the usage.

As Is see in the Admin&Permission, such model is still visible under Collection Types. Will modify the filtering there to exclude such models also.

Do you think it's going to be acceptable or it's agains the concepts you want to follow as a founders?

**Comment by cyp3rius** [comment]
Changes applied.

Zrzut ekranu 2020-07-24 o 10 07 31

**Comment by cyp3rius** [comment]
@alexandrebodin Updates done and build passed after updating to recent master.

**Comment by alexandrebodin** [comment]
Hi @cyp3rius FYI for a feature we are working on we are going to be reviewing the options for this. We will probably change this to something else :)

**Comment by cyp3rius** [comment]
@derrickmehaffy @alexandrebodin I've update the PR to the latest Strapi. Is this going to be somehow proceeded in the future? :)

**Comment by alexandrebodin** [comment]
Hi @cyp3rius, This PR implies changes in both the server & the admin UI. This kind of changes can't be merged into the app without going throught a RFC process. I'll keep it open but will ask you to go over https://github.com/strapi/rfcs add open an RFC :)

**Comment by cyp3rius** [comment]
Done @alexandrebodin -> strapi/rfcs#22

**Comment by alexandrebodin** [comment]
Hello I'm going to close this PR as you can control this now with the options we added in the referenced PR.

```json
 {
  "pluginOptions": {
    "content-manager": {
      "visible": false
    },
    "content-type-builder": {
      "visible": false
    }
  }
}
```

**Comment by cyp3rius** [comment]
Thanks @alexandrebodin, it will help a lot and we can revert the change in the fork soon :)

**Pull request closed without merging**
