### PR TITLE
Update documentation of the section plugin Google Cloud Storage

### PR DESCRIPTION
**Pull request by Lith**
Hello,

Some people are writing issue about misunderstood in the `google cloud storage` section for the deployment with Google App Engine.
In order to avoid further mistake, I prefer than the documentation provide a redirection to the full documentation of the plugin.

Thanks,

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
While I do like gutting this out, @lauriejim we need to clarify if we are going to be directly linking community plugins in the official documentation.

(Or at the very least we should probably make a notice that this plugin is not developed by Strapi)

**Comment by Lith** [comment]
Hi @derrickmehaffy , thanks for your fast reply.

I've wrote from the beginning on the documentation of the plugin,  it's a "Non-Official" Google Cloud Storage Provider for Strapi Upload. 
But I can add additional information in order to inform it's not managed by Strapi Team.

The main problem for now, it's some user send me help request for Google App Engine and how to use the plugin with deprecated information.

Thanks :)

**Comment by derrickmehaffy** [comment]
Ah yeah perfect, I hadn't reviewed the other part of that documentation. I am certainly not apposed to having community packages in the docs. :)

**Comment by lisongx** [comment]
@Lith 
thanks for doing this! was literally trying to find the non-existing button for 20 minutes until I go to the documentation for the plugin.

**Comment by Lith** [comment]
Hi, I've fixed conflict and rebase to latest master commit.

**Comment by Lith** [comment]
Travis  are failing with MySQL. Does it possible to check and approve this PR ?
Thanks :)

**Comment by derrickmehaffy** [comment]
> Travis are failing with MySQL. Does it possible to check and approve this PR ?
> Thanks :)

You can ignore that, since you are modifying the docs. It has to do with the knex pooling....

**Comment by lauriejim** [comment]
Hello @Lith can you please also apply this update in the `v3.x` documentation?

**Comment by Lith** [comment]
Hi @lauriejim !
I've apply modification on v3.x documentation
Let me know if something wrong :)
Thanks <3

**Pull request merged**
