### PR TITLE
Setup official GitHub Dependabot

### PR DESCRIPTION
**Pull request by abdonrd**
#### Description of what you did:

Setup official GitHub Dependabot.

https://docs.github.com/en/github/administering-a-repository/about-github-dependabot-version-updates

> GitHub Dependabot takes the effort out of maintaining your dependencies. You can use it to ensure that your repository automatically keeps up with the latest releases of the packages and applications it depends on.

Then you will have a new tab `Dependabot` in the [`Insights > Dependency graph`](https://github.com/strapi/strapi/network/dependencies) here:

https://github.com/strapi/strapi/network/updates

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @abdonrd nice initiative ! Can you make sure we force exact versions ? maybe adding a .npmrc to the repo too :)

**Comment by abdonrd** [comment]
@alexandrebodin ok! I can add it the `.npmrc` with:

```
save-exact=true
```

But why the exact versions intead of using the `^` to get the last patches?

**Comment by derrickmehaffy** [comment]
> @alexandrebodin ok! I can add it the `.npmrc` with:
> 
> ```
> save-exact=true
> ```
> 
> But why the exact versions intead of using the `^` to get the last patches?

Because of the Strapi packages, you shouldn't mix and match versions and NPM can get a little strange sometimes when it resolves

**Comment by derrickmehaffy** [comment]
@alexandrebodin was there a reason for the closure?

**Comment by alexandrebodin** [comment]
Nope it got closed because I deleted the target branch. switching target

**Comment by abdonrd** [comment]
Reopened here! https://github.com/strapi/strapi/pull/7103

**Pull request closed without merging**
