### PR TITLE
Remove Node 14 tests as it goes EOL

### PR DESCRIPTION
**Pull request by derrickmehaffy**
### What does it do?

Removes the tests for Node 14 as it goes EOL at the end of the month.

### Why is it needed?

Node 14 goes EOL at the end of the month: https://endoflife.date/nodejs

image

### How to test it?

N/A

### Related issue(s)/PR(s)

N/A

### CODE REVIEW

**Comment by alexandrebodin** [comment]
We should be adding node 20 now that it's released. I'm not sure we will have any breaking changes. Can you try that please ?

**Comment by derrickmehaffy** [comment]
> We should be adding node 20 now that it's released. I'm not sure we will have any breaking changes. Can you try that please ?

Technically node 20 doesn't go LTS until October should we really start testing it this early?

**Comment by alexandrebodin** [comment]
If it is active we can add it as soon as we want If we are not using any breaking change there isn't a good reason to delay support

**Comment by Marc-Roig** [comment]
we could update the documentation if we drop support of node 14 https://docs.strapi.io/dev-docs/installation/cli/#preparing-the-installation!

**Comment by alexandrebodin** [comment]
I think we can update the doc in // as node 14 is already EOL.

**Comment by joshuaellis** [comment]
We need to remove the required checks for `unit_back (node:14)` before this can be merged as well :)

**Review by joshuaellis — DISMISSED** [review]

**Comment by innerdvations** [comment]
This is updating tests but [not the actual supported versions](https://github.com/strapi/strapi/pull/16557). But do we want to do that now?

**Review by innerdvations — CHANGES_REQUESTED** [review]
Need to update `.github/workflows/skipped_tests.yml` too

**Comment by innerdvations** [comment]
I've merged this into the much bigger [Node 14 -> 20 PR](https://github.com/strapi/strapi/pull/16557), should we close this one until that's ready?

**Pull request closed without merging**
