### PR TITLE
add fallback targetAttribute for content type builder

### PR DESCRIPTION
**Pull request by Boegie19**
### What does it do?

Add fallback when targetAttribute is not set

### Why is it needed?

So you can use it with the same content as from the content type builder without it breaking relations

### CODE REVIEW

**Comment by innerdvations** [comment]
Can you give an example of when this might happen? I'm not sure I understand why this is needed.

**Comment by Boegie19** [comment]
plugin devs using it.

This is basically just a quality of life improvement.

since if you where to update an exisiting file I would not set target.

**Comment by Boegie19** [comment]
Why is CodeFactor  being mean?

**Comment by innerdvations** [comment]
I'll see about getting this PR merged this week, it seem simple enough, I just need to make sure it can't break something.

> Why is CodeFactor being mean?

Yeah, I think there's actually something wrong with it. I'll ask @alexandrebodin to look into it, and in the meantime I'll see if we can just fix any of them.

**Comment by Boegie19** [comment]
@innerdvations I think I should re order it to 

> It seems like this could introduce undesired behavior; if there's no targetAttribute, we should unset the relation, right?
> 
> Can you give a concrete example? Or provide some tests showing the different cases?

If I get the file it would not have a targetAttribute I want it to fall back on inversedBy or mappedBy if they already exist in the file and not break it. only of all 3 do not exist it should delete the relationship since else you will get an error since your side still has the inversedBy or mappedBy. note this is only happen if plugins call the service with an existing content type schema (aka I want it to hanndle schemas witout me having to set targetAttribute for all relations witout removing the other side of the relation)

**Comment by innerdvations** [comment]
So if I'm understanding the issue: right now if we have an attribute with oldTarget has an inversedBy, and newTarget has an inversedBy, nothing has changed, but we are considering it changed and unsetting it. Is that right?

**Comment by Boegie19** [comment]
Correct that was atleast the case when I wrote the PR. still this only happens in using the service in secondary plugins since the builder always sets targetAttribute

**Comment by alexandrebodin** [comment]
Hey, I'm gonna go ahead and close this. Best option imo is to make that targetAttributerequired in the function so programmatic usage will need it instead of allow too many loose options

**Pull request closed without merging**
