### PR TITLE
Update koa2-ratelimit to latest version

### PR DESCRIPTION
**Pull request by derrickmehaffy**
#### Description of what you did:

`npm audit` is throwing some vulnerabilities coming from `koa2-ratelimit` package. Testing updating to the latest version `0.9.0`

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [ ] MongoDB
- [x] MySQL
- [x] Postgres
- [x] SQLite

### CODE REVIEW

**Comment by alexandrebodin** [comment]
@derrickmehaffy have you tried it ?

**Comment by derrickmehaffy** [comment]
Doing it now, and also submitting the PR to let Travis do it's thing also

**Comment by derrickmehaffy** [comment]
https://travis-ci.org/strapi/strapi/builds/556857089?utm_source=github_status&utm_medium=notification
:stuck_out_tongue_closed_eyes:

**Comment by derrickmehaffy** [comment]
@alexandrebodin Manual testing of MySQL, SQLite, and Postgres it works fine. Waiting for Travis to confirm mongo.

**Pull request merged**
