### PR TITLE
feat(users-permissions): Add Crossid provider

### PR DESCRIPTION
**Pull request by asaf**
Authenticate via crossid.io provider

https://github.com/strapi/strapi/pull/11407

Related to issue https://github.com/strapi/strapi/issues/11305 and
PRs  https://github.com/strapi/strapi/pull/11407  https://github.com/strapi/strapi/pull/11306

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Just so we don't have a repeat of v3 PRs.... @petersg83 / @alexandrebodin any update here (assuming we fix the sessions middleware first).

**Comment by petersg83** [comment]
I cannot signup an account on crossid. I'm waiting for a response from their intercom.
Can you signup on your side?
I tried in December, it seemed a DNS issue. I tried today and it was a 404 response.

**Comment by derrickmehaffy** [comment]
> I cannot signup an account on crossid. I'm waiting for a response from their intercom. Can you signup on your side? I tried in December, it seemed a DNS issue. I tried today and it was a 404 response.

Gotcha, yeah once we get the session middleware issue resolved I can take a shot myself. Just wanted to poke in on some of the old PRs and make sure they weren't forgotten about :)

**Comment by alexandrebodin** [comment]
Hello @asaf, I will close this PR for inactivity. Feel free to ping us so we can reopen once/if you can work on it again.

**Pull request closed without merging**
