### PR TITLE
Validating the components on creation and direct schema edits 

### PR DESCRIPTION
**Pull request by iifawzi**
### What does it do?
Hi, this PR is resolving https://github.com/strapi/strapi/pull/14557#issuecomment-1283535907. 

Describe the technical changes you did.
1- Components will be validated on both the creation and when the schema is edited manually. 
2- Attributes will be checked for uniqueness, following up on #14012 (https://github.com/strapi/strapi/pull/14557#issuecomment-1281074801)

### Why is it needed?
it's how it is supposed to be working in the first place, components need to be validated.

### CODE REVIEW

**Comment by Marc-Roig** [comment]
LGTM! 💯 

@petersg83 What do you think? During the review of https://github.com/strapi/strapi/pull/14557, @iifawzi  discovered the component's domain validation was not being used anywhere. With this, it should be working now 🚀

**Review by Marc-Roig — APPROVED** [review]

**Comment by iifawzi** [comment]
why there's a lot of linting issues? it seems not to be related to the PR itself, right?

**Comment by Marc-Roig** [comment]
>why there's a lot of linting issues? it seems not to be related to the PR itself, right?
oh, ok, it seems like they are all warnings and there two failing tests related to the pr, I will take a look.

Yep, we changed the eslint rules a while ago and we have some eslint warnings showing up in all PRs. 😓

**Comment by alexandrebodin** [comment]
HI, I'm going to close this PR as we refactored the code in v4 & even more in v5. Feel free to check v5 out and see if this PR is applicable there. Thank you for your contribution  🙌

**Pull request closed without merging**
