### PR TITLE
Make internal strapi peerDependencies ranges and bump minimums

### LINKED ISSUE #17619: @strapi/data-transfer@4.12.1" has incorrect peer dependency "@strapi/strapi@4.11.5"
yarn info  @strapi/data-transfer@4.12.1 peerDependencies

yarn info v1.22.19
{
  '@strapi/strapi': '4.11.5'
}

### LINKED ISSUE #17792: `@strapi/data-transfer@4.12.6` has incorrect peer dependency `@strapi/strapi@4.12.4`
### Required System information

- Node.js version: v18.17.0
- NPM version: v9.6.7 
- PNPM version: v8.6.10
- Rush version: v5.94.1,
- Strapi version: v4.12.6
- Database: Postgres
- Operating system: MacOS Ventura 13.0
- Is your project Javascript or Typescript: JS

### Describe the bug

`@strapi/data-transfer@4.12.6` has incorrect peer dependency `@strapi/strapi@4.12.4` that blocks the upgrading on the `@strapi/strapi@4.12.6` version due to failing on `peerDependencies`

### Steps to reproduce the behavior

1. Set up Strapi v4.12.6 project using rush.js monorepo or simply in `strict-peer-dependency` mode.
2. Run `rush install` command or install the dependencies using the package manager directly.
3. Get the following error:
```
ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

../../cms/strapi
└─┬ @strapi/strapi 4.12.6
  └─┬ @strapi/admin 4.12.6
    └─┬ @strapi/data-transfer 4.12.6
      └── ✕ unmet peer @strapi/strapi@4.12.4: found 4.12.6

hint: If you don't want pnpm to fail on peer dependency issues, add "strict-peer-dependencies=false" to an .npmrc file at the root of your project.
```

### Expected behavior

There should be no error with peerDependencies, on the installation phase.

### Screenshots
Issue Image

### Related Issues
- [@strapi/data-transfer@4.12.1" has incorrect peer dependency "@strapi/strapi@4.11.5" #17619](https://github.com/strapi/strapi/issues/17619)

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

Set all peerDependiencies to use a range with the minimum versions of 4.12.4 / 1.9.0 (design system)

It looks like we're using peerDependencies as a way to get around circular references and to import code from other modules without listing them as actual dependencies. If that's the case (not sure, I don't have all the context here) we should be using fixed version numbers, but if we do that we have to be very careful to manually update them during a release, since they are not updated with `lerna publish`, and it would lead to a lot of human error.

I don't like either solution, but for now this PR should at least help remove any redundant or incorrect version packages and prevent any issues like we saw last week with [a peerDep in data-transfer](https://github.com/strapi/strapi/issues/17619)

### Why is it needed?

If we keep fixed version numbers, it may lead to that version being kept around in node_modules and a project's yarn.lock. And it will have to be updated manually with every release, since the publish script doesn't update peerDeps. So it's safest to keep them as a ranges.

We should, however, investigate if there's a better way to accomplish what we're doing with peerDeps.

### How to test it?

Everything should just work. We don't depend on lower versions, so bumping the minimum shouldn't do anything except potentially clean out unused packages from a project's node_modules.

I would appreciate if someone could do some additional QA or investigation, though, in case I'm missing something here.

### Related issue(s)/PR(s)

Fixes  #17619 (technically that is already fixed because someone updated the version number, but since it was left as an exact version, the issue would very likely reappear in the future)

Fixes #17792

### CODE REVIEW

**Comment by Marc-Roig** [comment]
Do you know if it  could be possible to make the `lerna publish` update peerDependencies too?

**Comment by innerdvations** [comment]
> Do you know if it could be possible to make the `lerna publish` update peerDependencies too?

They [actually removed it](https://github.com/lerna/lerna/issues/1018), because in general peerDependencies should be a wide range that doesn't change. As I understand it, talking to @Convly , we are bending the meaning of what peerDependencies are supposed to be for to solve a technical problem -- being able to import files from that module without listing it as a dependency. This is a band-aid for now, the real solution is to move any shared code to its own package and drop the peerDependencies.

**Comment by joshuaellis** [comment]
> being able to import files from that module without listing it as a dependency.

I don't think that applies everywhere, and maybe i've misunderstood so I apologise if you already know this but typically if you list it as a peer dep it should still be a devDep, just not production i.e. because you need a single type from somewhere...

**Comment by innerdvations** [comment]
> I don't think that applies everywhere, and maybe i've misunderstood so I apologise if you already know this but typically if you list it as a peer dep it should still be a devDep, just not production i.e. because you need a single type from somewhere...

That's another reason I'm confused. Most of our @strapi peerDeps do not include a matching devDep. I only know about one specific case, in data-transfer, where it's used to grab some actual code (not just types), but in that case we do actually have it listed as a devDep.

I will discuss with @alexandrebodin next week. This PR is primarily to add the ^ that is missing a couple places so that when we next release we don't accidentally include a fixed version that is wrong again.

**Comment by joshuaellis** [comment]
>That's another reason I'm confused. Most of our https://github.com/strapi peerDeps do not include a matching devDep. I only have context for one specific case, in data-transfer, where it's used to grab some actual code (not just types), but in that case we do actually have it listed as a devDep.

We added this to the FE TS eslint config because the issues you're describing can cause huge problems in pnpm etc. because we work in a workspace where "everything" is accessible but in reality, it's not... https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md#importno-extraneous-dependencies

**Comment by joshuaellis** [comment]
> If we keep fixed version numbers, it may lead to that version being kept around in node_modules and a project's yarn.lock. And it will have to be updated manually with every release, since the publish script doesn't update peerDeps. So it's safest to keep them as a ranges.

Do we plan to update them again? Because `semver` see's updating a peerDep as a breaking change. So i guess the bottom line is, how come we're moving them all up to `4.13.0`? 🤔 it seems like we should actually perhaps step back and draw up the diagram of deps and correctly address the "funnel" no?

**Comment by innerdvations** [comment]
Ok, closing this in favor of a one liner that just fixes the data-transfer version. We can look at the bigger issue later.

**Comment by joshuaellis** [comment]
Definitely maybe we can discuss it in a v5 sync so we have a unified approach going forward 🏃🏼‍♀️

**Pull request closed without merging**
