### PR TITLE
Add Audit Logs feature

### PR DESCRIPTION
**Pull request by Feranchz**
### What does it do?

Add the Audit Logs feature to Strapi, PR authors: @madhurisandbhor @remidej @markkaylor @Feranchz 

### How to test it?

* Be sure to have a valid EE license active
* Start your Strapi application
* Go to `Settings -> Audit Logs`, you will see a list with a log of events, you should see also the details of each event in a specific modal if you click the details icon at the right
* You can create events doing general actions such as create/edit/delete content-types, users, media, roles and others...

### CODE REVIEW

**Comment by Boegie19** [comment]
Question this was recorded for https://github.com/strapi/strapi/pull/15363 by derrick on my request since it is hard to explain without visuals https://www.loom.com/share/b175f2b9ce5a4e41a0d36793a3a4682e would this not be a issue for audit logs?

**Comment by yanniskadiri** [comment]
Interesting take, it won't be part of the MVP we will release this week but it could be a good addition in the future.
We would have to explore a bit further though because this is also an issue that could be solved when we add a content history feature for the entries.

**Review by markkaylor — APPROVED** [review]
🎈

**Review by remidej — COMMENTED** [review]
When looking at it with Fabien we found some things things I think we should change. Please don't merge just yet

**Review by remidej — DISMISSED** [review]

**Review by remidej — APPROVED** [review]

**Review by remidej — DISMISSED** [review]

**Review by remidej — APPROVED** [review]

**Review by markkaylor — APPROVED** [review]

**Comment by msoler75** [comment]
I updated to the last strapi version, did yarn install, yarn build, and yarn develop.

But that menu item don't appear in Settings -> Audit Logs

Settings - Application - Google Chrome_2

```
"dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.1.2",
    "@strapi/plugin-i18n": "4.6.0",
    "@strapi/plugin-users-permissions": "4.6.0",
    "@strapi/strapi": "4.6.0",
    "mysql": "2.18.1",
    "strapi-google-auth": "^0.1.2"
  },
```

**Comment by yanniskadiri** [comment]
@msoler75 do you have a Strapi enterprise license? 

The audit logs feature is only accessible in the Strapi enterprise edition.

**Comment by jpcmf** [comment]
This is a nice feature, but I encountered some issues when updating to the latest version of Strapi. Some foreign keys from 'strapi_audit_logs' and 'strapi_audit_logs_user_links' were missing in my production database. I dropped these tables and then ran the Strapi build again to recreate them. The foreign keys were successfully created, but now I'm receiving an error when attempting to access the Audit Logs.

image

Any tips to fix? Thank you.

**Pull request merged**
