### PR TITLE
Adding missing dependencies for Yarn PnP support

### LINKED ISSUE #12452: Unable to build Strapi with Yarn berry
### Describe the bug

You can't install Strapi with yarn berry.

### Steps to reproduce the behavior

1. `yarn create strapi-app my-project --quickstart`
2.

```bash
cd my-project
rm -rf .cache yarn.lock
yarn set version berry
yarn install
yarn build
```

### Expected behavior

Strapi should success to build with yarn berry.

### System

- Node.js version: v14.17.1
- NPM version: 8.4.1
- Strapi version: 4.0.7
- Database: SQLite
- Operating system: MacOS M1

### Additional context
When I tried to `yarn build`, it throws an error
```
Error: @strapi/admin tried to access object-assign, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: object-assign
Required by: @strapi/admin@npm:4.0.7
```

I declared required packages into `.yarnrc.yml` until every `it isn't declared in its dependencies` error disappeared
```yml
yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@strapi/admin@*":
    dependencies:
      object-assign: "*"
      whatwg-fetch: "*"
      react-is: "*"
  "@strapi/babel-plugin-switch-ee-ce@*":
    dependencies:
      "@babel/template": "*"
      "reselect": "*"
      "resolve": "*"
```

And this new error appeared.
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'lodash/merge' in '/Users/username/Develop/strapi-serverless/.cache/admin/src'
```

### LINKED ISSUE #12505: Yarn PnP warns about undeclared dependencies in @strapi/admin
### Describe the bug

When running `develop` using yarn in PnP mode, it immediately exits with an error or throws multiple warnings in `loose` mode. The warnings are:

```
(node:37369) [MODULE_NOT_FOUND] Error: node-fetch tried to access encoding (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
(node:37369) [MODULE_NOT_FOUND] Error: debug tried to access supports-color (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
(node:37369) [MODULE_NOT_FOUND] Error: @strapi/admin tried to access object-assign, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:37369) [MODULE_NOT_FOUND] Error: @strapi/admin tried to access whatwg-fetch, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:37369) [MODULE_NOT_FOUND] Error: @strapi/admin tried to access react-is, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

Additionally it throws the following error, which does not seem to have any visible consequences (I'm guessing it is supposed to open the browser?):

```
Error: spawn ENOTDIR
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at open (/home/aram/yarn-pnp/.yarn/cache/open-npm-8.2.1-f135ffeb36-fcde005918.zip/node_modules/open/index.js:205:34)
    at async Strapi.openAdmin (/home/aram/yarn-pnp/.yarn/unplugged/@strapi-strapi-npm-4.0.7-629da0ab63/node_modules/@strapi/strapi/lib/Strapi.js:208:7)
```

### Steps to reproduce the behavior

1. Create a new strapi-app using `yarn create strapi-app`
2. Create a .yarnrc.yml file wih `pnpMode: loose`
3. Run `yarn install`
4. Run `yarn develop`

### Expected behavior

All dependencies should be listed as dependencies and not throw warnings or errors .

### System

- Node.js version: v16.13.0
- NPM version: `yarn` v3.1.1
- Strapi version: 4.0.7
- Operating system: Ubuntu 21.10

### LINKED ISSUE #12837: TypeError: Cannot read properties of undefined in Content-Type Builder and Uploads pages
## Bug report
Hello,

I've an issue in the "Content-Type Build" page with the error `Cannot read properties of undefined (reading 'startSection')`
and the "uploads" page (under the content-type build) with the error `Cannot read properties of undefined (reading 'allPermissions')`

### Describe the bug
 When I'm going on the url `127.0.0.1/admin/plugins/content-type-builder` i get a blank page (here black because of my browser dark mode) with this error in the console
 
(c.f Screen 1)

Also the same problem but with another property in the uploads pages (`127.0.0.1/admin/plugins/upload`)

(c.f Screen 2)

I tried with version 4.0.5, 4.1.0, 4.1.1, 4.1.2 & 4.1.3
Each time I removed the package-lock.json, removed the `build` and `.cache` folders, and then start the server and I always have the same problem on the both pages.

### Steps to reproduce the behavior

1. Go to admin panel
2. Click on Content-Type Builder
4. See blank page & error
5. Go to admin panel index by refreshing or opening a new tab
6. Click on "Media library"
7. See blank page & error

### Expected behavior

Accessing both content type builder and media library page without errors in console and blank page.

### Screenshots

Screen 1 : image
Screen 2: image

### System

- Node.js version: v14.19.0
- NPM version: v14.19.0
- Strapi version: Tested on 4.0.5, 4.1.0, 4.1.1, 4.1.2 & 4.1.3
- Database: Mysql 8.0.28
- Operating system: Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-171-generic x86_64)

### Additional context

The problem appears after I got for an unknown reason a deletion of the content of the strapi folder, after reverting it with git, the problem was here.

### PR DESCRIPTION
**Pull request by kibblerz**
### What does it do?

Adds package dependencies explicitly to allow compatibility with Yarn PnP. With these edits, PnP will be able to function with strapi. With these edits, Yarn PnP will be able to run without fallback mode or setting pnpMode to loose.

For npm to work with this, strapi-icons needs to be updated to request @strapi/design-system 1.1.1

It requires adding a significant amount of dependencies to the root project, due to the admin being ran from .cache/. Not sure if there's a better way to handle this

This also seemed to fix issue #12837 for me. 

### Why is it needed?

PnP fails to work with strapi due to undefined dependencies

### How to test it?
Copy the dependencies from package.json (At the root of the Repo") into the dependencies for your Strapi Application. Depending on your configuration, you may need to add additional packages to your project due to how the admin panel is built.

Run "yarn set versions stable"
Disable Fallback mode, pnpMode, and nodeLinker options from .yarnrc.yml
Run "yarn install & yarn build"

### Related issue(s)/PR(s)

Resolves #12505
Resolves #12452
Resolves #12837

### CODE REVIEW

**Comment by kibblerz** [comment]
Why did the check fail? I can't seem to see the error

**Comment by kibblerz** [comment]
Just cleaned this up so that few imports are needed on the project. I also added some logic to differentiate between whether pnpapi is being used. I did have to bypass an eslint rule as require('pnpapi') is used to test whether PNP is enabled.

**Comment by MrChrisRodriguez** [comment]
@kibblerz take a look at https://github.com/strapi/strapi/pull/12678 -- is your PR including a more robust set of dependencies?

@soupette reviewed the other PR (pending for a few months now) and @alexandrebodin added it to the release schedule. Any feedback on these changes? I know quite a few people are *really* looking forward to a PnP fix.

**Comment by kibblerz** [comment]
@MrChrisRodriguez Yes, this PR would be a more robust set of dependencies then what #12678 adds. 

#12678 may allow PnP to work with Fallback mode and loose mode enabled, but this PR should allow PnP to work without enabling fallback or loose mode. All dependencies should now be defined, so this should allow for near full integration with PnP. Zero Installs still won't work as esbuild and sharp have build scripts that need to run.

**Comment by kibblerz** [comment]
Why is the security/snyk test failing? I can't see the details for it.

**Comment by MrChrisRodriguez** [comment]
@kibblerz [here's a heads-up](https://github.com/strapi/strapi/pull/12678#issuecomment-1165508902) that Strapi may be working on this problem next week. Hopefully, @gu-stav will review your PR as part of that initiative.

**Comment by gu-stav** [comment]
@kibblerz @MrChrisRodriguez We recently discussed this topic and will open a PR on Monday, to hopefully fix all missing dependencies in our packages. 🚀 As part of this effort we will re-check your PR.

**Comment by gu-stav** [comment]
@kibblerz @MrChrisRodriguez I'm going to close this PR now. Thanks a lot for your work. @fdel-car will come up with a more complete PR very soon, which will fix all the issues you have mentioned, but also remove some unneeded dependencies.

I'll keep you updated once it is there and ask for your feedback!

**Comment by Imshubh69** [comment]
> @kibblerz @MrChrisRodriguez I'm going to close this PR now. Thanks a lot for your work. @fdel-car will come up with a more complete PR very soon, which will fix all the issues you have mentioned, but also remove some unneeded dependencies.
> 
> I'll keep you updated once it is there and ask for your feedback!

finally it's happening

**Comment by SalahAdDin** [comment]
> > @kibblerz @MrChrisRodriguez I'm going to close this PR now. Thanks a lot for your work. @fdel-car will come up with a more complete PR very soon, which will fix all the issues you have mentioned, but also remove some unneeded dependencies.
> > I'll keep you updated once it is there and ask for your feedback!
> 
> finally it's happening

Well, nope, it is not happening yet.

**Pull request closed without merging**
