### PR TITLE
Allow relations to be selected as repeatable main field in settings

### PR DESCRIPTION
**Pull request by hamilton-b**
### What does it do?

Makes a repeatable show the title of a nested relation when a default title is not available

### Why is it needed?

No title is currently shown when a relation is the only property in a repeatable. I found this discussion and seems to be desired in v4 - https://forum.strapi.io/t/using-a-relationships-entry-title-as-a-repeatable-components-entry-title/6186

Before - see blank title on repeatable as I cannot select it as a main field:
before

With change, it will now use the title of the relation and allow relations to be used as main fields
after

This allows an array to be created with relations to be ordered, while now showing them in a user friendly manner

### How to test it?

1. Create a component with a `oneToOne` relation to a collection
2. Add a repeatable to a content type with the component
3. In settings, select your relation as the main field to display
4. In content manager, add and remove relations to the content type and see the title now showing

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by hamilton-b** [comment]
@soupette - I have modified the implementation slightly from the PR previously closed. It is now more generic and allows the relation to be selected in settings. Previous PR: https://github.com/strapi/strapi/pull/12650

**Comment by vsychov** [comment]
It's very nice feature, that improve strapi UI, hope this will be merged or implemented in another way soon. Related topic on forum - https://forum.strapi.io/t/using-a-relationships-entry-title-as-a-repeatable-components-entry-title/6186

**Comment by joshuaellis** [comment]
I'm not sure this PR is entirely relevant given the release of `4.5.0` wdyt @gu-stav & @hamilton-b

**Comment by gu-stav** [comment]
@joshuaellis It is still very relevant.

**Comment by gu-stav** [comment]
Closing this PR, because the code is outdated and wouldn't work any longer. We have added the issue to the internal board and will discuss how we could achieve this at some point.

**Pull request closed without merging**
