### PR TITLE
fix: load strapi before watch

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

- Load strapi before watch to avoid installing vite middleware too early

### Why is it needed?

Fix https://github.com/strapi/strapi/issues/21846

### How to test it?

- See that runing yarn develop works exactly the same with vite & webpack
- check the cors headers in the issue are work for both yarn develop & yarn start

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by innerdvations** [comment]
This seems like the right thing to do in general, but it didn't exactly work for me to solve the issue.


My cors middleware:
```
 {
    name: 'strapi::cors',
    config: {
      headers: [
        'Origin',
        'Accept',
        'Content-Type',
        'Authorization',
        'X-Frame-Options',
        'X-Forwarded-For',
        'Access-Control-Allow-Credentials',
        'Access-Control-Allow-Origin',
      ],
      credentials: true,
      keepHeaderOnError: true,
      origin: [
        // Local API
        'http://localhost:1337',
        'http://localhost:1338',

        // Local Frontend
        'http://localhost:3000',
        'http://localhost:5173',
      ],
    },
  },
```

On `develop` I get access-control-origin as an empty line
```
"

"
```

With this PR I get access-control origin as `"*"`

**Comment by derrickmehaffy** [comment]
Localhost won't set the origin header so it returning * on localhost is normal. The origin header only is sent on actual domains or cross site requests

**Comment by alexandrebodin** [comment]
You have to manually set the origin to test this. In Strapi this won't do anything because it's the same domain

example 
Screenshot 2024-10-22 at 06 29 20

**Comment by innerdvations** [comment]
Ahhh, ok, I thought it was always set. I will try again with that in mind later!

**Pull request merged**
