### PR TITLE
Fixed static http protocol within Auth.js (provider)

### LINKED ISSUE #1861: Facebook provider is broken: wrong request_uri
**Informations**
- **Node.js version**: v9.11.2
- **npm version**:5.6.0
- **Strapi version**: 3.0.0-alpha-14
- **Database**: MySQL
- **Operating system**: Ubuntu 16.04

**What is the current behavior?**

request_uri for the facebook provider is generated with http. http uris are rejected by facebook (except localhost uris for dev)

**Steps to reproduce the problem**

Setup facebook provider and send GET <host>/connect/facebook

**What is the expected behavior?**

request_uri is accepted by facebook.

**Suggested solutions**

Use a configurable protocol instead of an hard coded one in `plugins/users-permissions/controllers/Auth.js` in the following lines:

```
_.defaultsDeep(grantConfig, {
      server: {
        protocol: 'http',
        host: `${strapi.config.currentEnvironment.server.host}:${strapi.config.currentEnvironment.server.port}`
      }
});
```

I tried just hard coding https so that facebook accepts the request_uri, but it will trigger another error down the line in the `plugins/users-permissions/services/Providers.js`. More specifically in the following lines:

```
const users = await strapi.query('user', 'users-permissions').find({
          where: {
            email: profile.email
          }
});
```

It will throw an object as error that is caught and passed to the reject function. The error object is empty so I have no idea for what might be the cause.

### PR DESCRIPTION
**Pull request by steadweb**
My PR is a Bug fix #1861

Main update on the *Plugin: users-permissions*

This aids configuring the host and protocol for said provider, it's most likely that the port won't be specified and `https` _must_ be used, in _production_. This assumes the config sets `protocol` to `https`. I'm happy to set a sane default if necessary.

Issue: https://github.com/strapi/strapi/issues/1861

### CODE REVIEW

**Comment by lauriejim** [comment]
Can you link the issue you fix please.

**Comment by steadweb** [comment]
> Can you link the issue you fix please.

https://github.com/strapi/strapi/issues/1861

**Comment by lauriejim** [comment]
@derrickmehaffy Can you take a look please.

**Comment by derrickmehaffy** [comment]
@lauriejim yeah I'll take a look tonight when I get home

**Comment by lauriejim** [comment]
Agree with @derrickmehaffy .

We will work on this PR https://github.com/strapi/strapi/pull/2110.

Anyway, thank you @steadweb for the job you did!

**Pull request closed without merging**
