### PR TITLE
Fix SQL query where oneWay relationship is null

### PR DESCRIPTION
**Pull request by Aurelsicoko**
**My PR is a:**
- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #issueNumber
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

**Main update on the:**
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

**Manual testing done on the follow databases:**
- [ ] Not applicable
- [ ] MongoDB
- [x] MySQL
- [ ] Postgres

**Description:**

I fixed the SQL query that allows retrieving multiple entries through GraphQL, there was a bug when a oneWay relationship was null.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/issues/2396

**Comment by greatwitenorth** [comment]
I'm still seeing NULL on deep nested relations:

screenshot 2019-01-28 16 08 36

**Comment by lauriejim** [comment]
@greatwitenorth What is the version of strapi you use to test it ?
`alpha.21` or the mono repo ?

**Comment by greatwitenorth** [comment]
This is alpha 21 with the specific changes done from this pull request.

**Comment by lauriejim** [comment]
Yes please. And make sur you apply update of this PR.

**Comment by greatwitenorth** [comment]
After updating to Alpha 21 and applying the patches in this update I'm now seeing empty result sets for ALL nested relations when I know for certain there's related data:

**Deeply nested data:**
screenshot 2019-01-31 15 13 54


**Nested data:**
screenshot 2019-01-31 15 16 46

**Comment by lauriejim** [comment]
Can you give us models you use (to have the relation type and test it on our side)

**Comment by greatwitenorth** [comment]
You can ignore my issue, after updating to alpha 22 everything seems to be working correctly now.

**Pull request merged**
