### PR TITLE
Use cache action to cache node_modules

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by joshuaellis** [comment]
Do we know that that's the correct cache path?

From previous places i've had to get the cache directory, but then i've normally done this on ubuntu (and the example below uses v2).

CleanShot 2022-11-23 at 17 22 49@2x

**Comment by alexandrebodin** [comment]
> Do we know that that's the correct cache path?
> 
> From previous places i've had to get the cache directory, but then i've normally done this on ubuntu (and the example below uses v2).
> 
> CleanShot 2022-11-23 at 17 22 49@2x

Your screenshot is for caching yarn cache. Here I'm caching the node_modules directly as we have full control over the node version and can create the cache key based on it.

**Comment by alexandrebodin** [comment]
> Do we know that that's the correct cache path?
> 
> From previous places i've had to get the cache directory, but then i've normally done this on ubuntu (and the example below uses v2).
> 
> CleanShot 2022-11-23 at 17 22 49@2x

Your screenshot is for caching yarn cache. Here I'm caching the node_modules directly as we have full control over the node version and can create the cache key based on it.

**Comment by joshuaellis** [comment]
aha makes sense! 😄 thanks for explaining the diff!

**Review by joshuaellis — APPROVED** [review]

**Review by Convly — APPROVED** [review]

**Review by derrickmehaffy — APPROVED** [review]
Lgtm

**Pull request merged**
