### PR TITLE
Relations: Fix backend and frontend communication papercut issues

### PR DESCRIPTION
**Pull request by gu-stav**
### What does it do?

Now that the back and frontend are working together this PR fixes a few papercut issues that occured during testing.

### CODE REVIEW

**Review by ronronscelestes — COMMENTED** [review]
Nice fixes thank you!

I don't know if you intended to fix those issues with this PR but in case:
- Save is still not working
- When adding a relation, first time you re-enter the search the relation is still there and can be added again, you have to defocus and re-enter once again to see it removed/omitted 

https://user-images.githubusercontent.com/71838159/188873463-714cbd7e-038c-4189-ad46-792c0892e8cb.mov

**Comment by gu-stav** [comment]
@ronronscelestes Pierres PR is still open and not merged: https://github.com/strapi/strapi/pull/14327 and yes there are many errors everywhere, but this is a good foundation to bring the FE in line with the specs.

**Comment by derrickmehaffy** [comment]
Just out of curiosity, do we have a list of the paper cuts fixed just in case they match up with any open issues? 

(Thank you though, I love seeing paper cut fix PRs)

**Comment by gu-stav** [comment]
@derrickmehaffy These are all last-minute fixes on the feature branch moving relations into the main view. We will have a QA session tomorrow and had the chance to see the backend and frontend working together for the first time today ...

**Comment by derrickmehaffy** [comment]
Ahhhh okay, feature paper cuts got it. Sorry been a long week 😅

**Pull request merged**
