### PR TITLE
tests(perf): explore happy-dom (highly wip)

### PR DESCRIPTION
**Pull request by belgattitude**
**caution** Highly WIP and I'm not sure I would do this, but it might be a good case to help the upstream https://github.com/capricorn86/happy-dom to fill gaps and bring more supported features.

Part of ci performance explorations.

- #16694 
- #16638 
- #16709 
- #16693 
- #16581

## Install 

```
yarn install
yarn build --projects=@strapi/admin-test-utils,@strapi/helper-plugin --skip-nx-cache
cd packages/core/admin

# Works
yarn test:front --coverage false --env=@happy-dom/jest-environment

```

## Benchmarks.

The test suite won't run with the latest version of happy-dom. I'll comment failing issues. Not sure about speed but I would say between 5-20% speedup. Not sure it's worth it due to happy-dom parity (cost/benefit). Will try to reach the author.

What works right now

```bash
yarn test:front --coverage false \
        --testPathPattern "admin/src/utils/*" \
        --env=@happy-dom/jest-environment

# compared to

yarn test:front --coverage false \
        --testPathPattern "admin/src/utils/*" \
        --env=jsdom
```

Not enough passing tests to measure

### CODE REVIEW

**Comment by belgattitude** [comment]
Happy dom upstream issue

- [ ] https://github.com/capricorn86/happy-dom/issues/921

```bash
yarn install
yarn build --projects=@strapi/admin-test-utils,@strapi/helper-plugin --skip-nx-cache
```

```bash
cd packages/core/admin
yarn test:front --coverage false --testPathPattern admin/src/components --env @happy-dom/jest-environment
```

```
   TypeError: Cannot read properties of undefined (reading 'matches')

      12 |
      13 | const getDefaultTheme = () => {
    > 14 |   const browserTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
```

**Comment by belgattitude** [comment]
Happy dom upstream issue


```bash
yarn install
yarn build --projects=@strapi/admin-test-utils,@strapi/helper-plugin --skip-nx-cache
```

```bash
cd packages/core/admin
yarn test:front --coverage false --testPathPattern admin/src/pages --env @happy-dom/jest-environment
```


image

**Comment by belgattitude** [comment]
@capricorn86 Would you be interested to collaborate on this attempt ? 

I'm not working for strapi, but got a recent interest in whatever helps to reduce what would help reduce carbon emission. Very naive but I need to start somewhere, before sharing more (a website with recipes or something)

Strapi seemed to me a very good start, cause I'm impressed by what they're doing.

If you're interesed let me know

**Comment by gu-stav** [comment]
@belgattitude Thank you again so much for investing all your time into our tooling :) I will be honest with you here: unless this would bring a significant speed improvement (which I doubt), I think I'd like to stick to the default jest setup. The system is already complex (and brittle) enough and I would prefer to stick to the default jsdom setup for now.

While it is a novel goal to optimize for carbon emissions looking at the high-level setup will help to not micro-optimize steps, but improve the situation as a whole. You have already had a tremendous impact for us, which I appreciate a lot.

**Comment by belgattitude** [comment]
Makes sense

**Pull request closed without merging**
