### PR TITLE
Media lib/provider settings

### PR DESCRIPTION
**Pull request by alexandrebodin**
This PR moves the upload provider config to a file. 

Right now you need to edit the config in the extensions folder `./extensions/upload/config/settings.json`. (doc is updated in the PR)

### CODE REVIEW

**Comment by YeomansIII** [comment]
Is it no longer possible to set provider configurations on a per-environment basis?

**Comment by abdonrd** [comment]
I have the same doubt.

**Comment by alexandrebodin** [comment]
Hi, In a next release you will be able to do it in a better way (https://github.com/strapi/strapi/pull/5747#pullrequestreview-393770635), but right now you can use two methods:

- Dynamic configuration as  in the [documentation](https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#dynamic-configurations)
- Use some js to choose the config depending on the env :) 

`./extensions/plugins/upload/config/settings.js`
```js

if (!process.env.NODE_ENV || process.env.NODE_ENV === 'development') {
  module.exports = {
 //   provider: 'local',
   // providerOptions: {
     //....
    },
  };
} else if (process.env.NODE_ENV === 'production') {
  module.exports = {
//    provider: 'cloudinary',
    // providerOptions: {
    //   cloud_name: 'cloud-name',
    //   api_key: 'api-key',
    //   api_secret: 'api-secret',
    // },
  };
}

```

**Comment by abdonrd** [comment]
Thanks @alexandrebodin !

I just updated to auto-load the default local config:

```javascript
if (!process.env.NODE_ENV || process.env.NODE_ENV === 'development') {
  module.exports = require('strapi-plugin-upload/config/config.json');
} else if (process.env.NODE_ENV === 'production') {
  module.exports = {
    provider: 'cloudinary',
    providerOptions: {
      // ...
    }
  };
}
```

**Comment by alexandrebodin** [comment]
@abdonrd You can just return an empty object instead it will get merged ;)

**Comment by abdonrd** [comment]
@alexandrebodin oh, perfect! I didn't know that, thanks!

**Pull request merged**
