### PR TITLE
Moved sentry middleware

### PR DESCRIPTION
**Pull request by Froelund**
In order to catch errors from the other middlewares, it is important to have sentry middleware loaded in the beginning.
If let's say `responseTime` middleware would throw an error, sentry would not be able to pick it up if it's not loaded before.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@alexandrebodin should this be against the master branch?

**Comment by alexandrebodin** [comment]
Hi Yes please reopen against master please

**Comment by alexandrebodin** [comment]
Hey @Froelund can you verify the DCO check please :)

**Comment by Froelund** [comment]
I see why you recommended creating a new pull-request against master :)
https://github.com/strapi/strapi/pull/6430

**Pull request closed without merging**
