### PR TITLE
move logic of cron enable check

### PR DESCRIPTION
**Pull request by Cpaczek**
### What does it do?

Moves the config check to the add function of the `add()` function to prevent bypassing enabled flag

### Why is it needed?

If the user doesn't explicitly set the cron.enabled to true it shouldn't be allowed to add cron jobs.

### How to test it?

strapi --quickstart

try and create a cron job without enabling it in the config. (should fail)

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/15588

### CODE REVIEW

**Comment by petersg83** [comment]
@Cpaczek @Bassel17 It has to be check but I think it is an intended behavior. The logic is that the user can disable its own `cron` tasks but not the others, if a plugin uses `cron`, it's its responsability to provide a config that impact this own `cron` logic.

**Comment by Cpaczek** [comment]
> @Cpaczek @Bassel17 It has to be check but I think it is an intended behavior. The logic is that the user can disable its own `cron` tasks but not the others, if a plugin uses `cron`, it's its responsability to provide a config that impact this own `cron` logic.

I see how that makes sense but not having a way for the user to disable cron jobs entirely could be more problematic. There are a few different approaches on how to prevent race conditions for horizontally scaled strapi apps with cron. One options would be to use a table-locking system but that would require changes to Strapi to get working. Another way would be only only have 1 instance of Strapi running the cron jobs. Obviously, this wouldn't allow horizontal performance for action contained within cron jobs but it's a good start. But for these latter options not being able to disable cron jobs globally would cause a problem for plugins that don't deal with the race condition. 

I personally think its fine to merge this PR or not merge it both approaches make sense however I think the cron system should be reworked to prevent race conditions.

**Comment by petersg83** [comment]
You're right, there is a discussion to have about how to handle horizontal scale. Maybe a general issue about that can be opened as I think not only `cron` would be involved in the thinking (the license check for instance). What do you think of closing the current issue and opening a new one?

**Comment by Cpaczek** [comment]
Ya i'll close this and open a new issue

**Pull request closed without merging**
