### PR TITLE
Feature/asset table for media library

### PR DESCRIPTION
**Pull request by Krito1997**
### What does it do?
In media library page, we added a feature that allows users to take a quick look at all assets as a list.
Users can press a button to switch between card view and list view. The list view shows all actions which can be performed in one/two clicks. Additionally, it shows all asset related information which helps get a quick overview

### Why is it needed?
It saves users time by providing a quick overview of each asset.

### How to test it?
- Click on Show Asset List to see the list
- Freely interact which each asset in the list 
- Switch back to card view by clicking on the Show Asset Card
Screen Shot 2022-06-02 at 1 15 23 PM

### Design document:
https://docs.google.com/document/d/1CQkRTItfi7DMvEbKkMrG7JYU-3Vji5zcuJIMWqXhRvw/edit?usp=sharing

### Related issue(s)/PR(s)

This is a new feature.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
This would be really awesome!

**Comment by maevalienard** [comment]
Hi 👋 This is a very very cool feature, thank you! Would you be up to do a few UI/UX changes so we could make the best out of your PR? :D 

- I was thinking that if it's technically feasible, allowing the bulk select in the list view would be awesome since we have the bulk checkbox next to the sort by buttons?
- Maybe that would be interesting to reduce the button size, such as something like this, what do you think? (screenshoted from Slack - I could help with a design though 🙂 )
Capture d’écran 2022-06-07 à 11 54 28
- To follow UI guidelines, I think that would be awesome if the padding left and right could fit the alignments of the buttons above: 
Listview-ML

**Comment by gu-stav** [comment]
@maevalienard I think we need to talk about this PR first (during the next user issues & pr review), but this heavily interfers with the upcoming folders feature and can not be merged in it's current state. I've invited you to this meeting.

That being said: @Krito1997 thanks for opening the PR. We really appreciate the work and will discuss it on the 28th of June and get back to you.

**Comment by gu-stav** [comment]
@Krito1997 Thanks again for opening the PR and the work already. We discussed the PR and would like to move forward with it. @maevalienard will provide you with some design on how to include folders (see https://github.com/strapi/strapi/pull/13499).

The table layout will also need to be done for the modal in the content-manager (when you pick an asset from the media library).

Would you still be available to work on these things? I will try to do my best to help and guide you whereever needed.

**Comment by Isha2209** [comment]
Hie👋! Here's the finalized design 😄
Grid view
List view with folders

**Pull request closed without merging**
