### PR TITLE
Remove files that no longer need to be changed

### PR DESCRIPTION
**Pull request by abdonrd**
### What does it do?

Remove files that no longer need to be changed

### Why is it needed?

No longer need to be changed

### CODE REVIEW

**Comment by abdonrd** [comment]
@derrickmehaffy I'm not sure if the branch should be `documentation` or `master`.

**Comment by derrickmehaffy** [comment]
@abdonrd documentation :) Just going to set the frontend team to review and make sure we aren't missing anything.

**Review by soupette — DISMISSED** [review]
LGTM

**Comment by soupette** [comment]
@abdonrd thanks a lot for your PR can you make sure the DCO checks so we can merge it?

**Comment by abdonrd** [comment]
@soupette done!

**Review by soupette — APPROVED** [review]
LGTM

**Review by HichamELBSI — APPROVED** [review]
LGTM

**Comment by abdonrd** [comment]
@derrickmehaffy when it goes lives? I don't know if it deploys every time the branch changes, you do it manually or what.

**Comment by derrickmehaffy** [comment]
Right now its manual, ill be pushing in a few minutes.

But here soon when we move to the new documentation repo it will be automatic on a cron (likely daily still TBD)

**Comment by abdonrd** [comment]
Got it, thanks @derrickmehaffy!

I have also created a new PR with the intention of making it easier to create new providers. #8741

**Pull request merged**
