### PR TITLE
chore(helper-plugin)!: move useStrapiApp and remove Library / CustomFields

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* moves `StrapiApp` feature to admin
* removes `CustomFields` feature and merges it into `useStrapiApp`
* removes `Library` feature and merges it into `useStrapiApp`

### CODE REVIEW

**Review by Marc-Roig — APPROVED** [review]

**Comment by jhoward1994** [comment]
I'm seeing this error when navigating to the CTB

```
chunk-U4SGKR5B.js?v=ef04e799:3530 React Router caught the following error during render TypeError: Cannot read properties of undefined (reading 'customFields')
    at get (CustomFields.ts:179:17)
    at FormModal (FormModal.tsx:105:23)
    at renderWithHooks (chunk-UXQHBU75.js?v=ef04e799:12171:26)
    at mountIndeterminateComponent (chunk-UXQHBU75.js?v=ef04e799:14921:21)
    at beginWork (chunk-UXQHBU75.js?v=ef04e799:15902:22)
    at beginWork$1 (chunk-UXQHBU75.js?v=ef04e799:19749:22)
    at performUnitOfWork (chunk-UXQHBU75.js?v=ef04e799:19194:20)
    at workLoopSync (chunk-UXQHBU75.js?v=ef04e799:19133:13)
    at renderRootSync (chunk-UXQHBU75.js?v=ef04e799:19112:15)
    at recoverFromConcurrentError (chunk-UXQHBU75.js?v=ef04e799:18732:28) {componentStack: '\n    at FormModal (http://localhost:1337/@fs/Users…pi/vite/deps/chunk-U4SGKR5B.js?v=ef04e799:4463:5)'}

```

**Comment by jhoward1994** [comment]
And also this sporadically when navigating around the CM

```
chunk-4BIPJWK7.js?v=644af2f8:3530 React Router caught the following error during render Error: A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.
    at throwException (chunk-SAG4Y7ZM.js?v=644af2f8:14217:43)
    at handleError (chunk-SAG4Y7ZM.js?v=644af2f8:19030:15)
    at renderRootSync (chunk-SAG4Y7ZM.js?v=644af2f8:19115:15)
    at recoverFromConcurrentError (chunk-SAG4Y7ZM.js?v=644af2f8:18732:28)
    at performSyncWorkOnRoot (chunk-SAG4Y7ZM.js?v=644af2f8:18875:28)
    at flushSyncCallbacks (chunk-SAG4Y7ZM.js?v=644af2f8:9135:30)
    at chunk-SAG4Y7ZM.js?v=644af2f8:18623:21 {componentStack: '\n    at Lazy\n    at CollectionTypePages (http://lo…pi/vite/deps/chunk-4BIPJWK7.js?v=644af2f8:4463:5)'}

```

I think the source is vite

**Comment by joshuaellis** [comment]
> I'm seeing this error when navigating to the CTB
> 
> ```
> chunk-U4SGKR5B.js?v=ef04e799:3530 React Router caught the following error during render TypeError: Cannot read properties of undefined (reading 'customFields')
>     at get (CustomFields.ts:179:17)
>     at FormModal (FormModal.tsx:105:23)
>     at renderWithHooks (chunk-UXQHBU75.js?v=ef04e799:12171:26)
>     at mountIndeterminateComponent (chunk-UXQHBU75.js?v=ef04e799:14921:21)
>     at beginWork (chunk-UXQHBU75.js?v=ef04e799:15902:22)
>     at beginWork$1 (chunk-UXQHBU75.js?v=ef04e799:19749:22)
>     at performUnitOfWork (chunk-UXQHBU75.js?v=ef04e799:19194:20)
>     at workLoopSync (chunk-UXQHBU75.js?v=ef04e799:19133:13)
>     at renderRootSync (chunk-UXQHBU75.js?v=ef04e799:19112:15)
>     at recoverFromConcurrentError (chunk-UXQHBU75.js?v=ef04e799:18732:28) {componentStack: '\n    at FormModal (http://localhost:1337/@fs/Users…pi/vite/deps/chunk-U4SGKR5B.js?v=ef04e799:4463:5)'}
> ```

I think i fixed this now, I found the issue with ✨ _lexical scoping_ ✨

**Comment by joshuaellis** [comment]
> And also this sporadically when navigating around the CM

And this, i removed a suspense boundary that I should not have

**Review by jhoward1994 — APPROVED** [review]
Do you know if we have these things tracked anywhere?

- CTB save button remains enabled after save
- CTB requires page reload to see recent changes made to content types (fields added etc)

**Comment by joshuaellis** [comment]
> Do you know if we have these things tracked anywhere?
> 
> * CTB save button remains enabled after save
> * CTB requires page reload to see recent changes made to content types (fields added etc)

https://github.com/strapi/strapi/pull/19811 Bassel is on it, it's in the DX board

**Pull request merged**
