### PR TITLE
Fix regex validation

### LINKED ISSUE #9236: Uncaught TypeError: Cannot delete property 'regex' of #<Object>
### Describe the bug

Getting error ```Uncaught TypeError: Cannot delete property 'regex' of #<Object>```, when trying to create or to save collection type item containing text field with regex validation.

### Steps to reproduce the behavior

1. Create collection type ```test```
2. Create field rgba_regex, set regex validation rule to ```rgba\(\d{1,3},\s?\d{1,3},\s?\d{1,3},\s?[0-1]\.\d+\)```, save it.
3. Open Test collection and try to create an item.

### Screenshots

image
image

### System

- Strapi version: v3.4.5
- Database: Mongo
- Operating system: Windows

### Additional context

Issue is happening in ```strapi-plugin-content-manager\admin\src\containers\EditViewDataManagerProvider\utils\schema.js``` in function ```createYupSchemaAttribute```. Because ```validations``` argument that is an object is read-only. We can do clone of it and then freely manipulate with it.

### PR DESCRIPTION
**Pull request by soupette**
Signed-off-by: soupette <cyril.lpz@gmail.com>

### What does it do?

This PR fixes #9236

### CODE REVIEW

**Review by shtelzerartem — APPROVED** [review]
Cool, checked, it works

**Review by lundgren2 — APPROVED** [review]

**Review by mfrachet — APPROVED** [review]
Regexp are definitely not my biggest strength, but it works on my end 😊

**Review by HichamELBSI — APPROVED** [review]
LGTM

**Comment by derrickmehaffy** [comment]
This pull request has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/regex-error-typeerror-cannot-delete-property-regex-of-object/2519/3

**Comment by dalbitresb12** [comment]
@derrickmehaffy Has this fix been released in v3.4.6? It isn't listed in the [changelog](https://github.com/strapi/strapi/releases/tag/v3.4.6).

**Comment by dappiu** [comment]
@dalbitresb12 I had the same question, I checked and I can confirm that -even if not listed- it's indeed present in v3.4.6

**Comment by dalbitresb12** [comment]
Thank you, @dappiu! I believe this one should also be added to the changelog. Friendly ping to @alexandrebodin since he was the one who posted the release?

**Comment by alexandrebodin** [comment]
Hi, th label wern't addd to the PR so it didn't get a changlog lin :) will add it manually thanks for th notice !

**Pull request merged**
