### PR TITLE
Add facts when running setup

### PR DESCRIPTION
**Pull request by soupette**
This PR does not improve the framework but after making a lot of setup I thought it might be great to learn some stuffs 🤓🤓....

Maybe we can merge it only if we get some votes from the community?

### CODE REVIEW

**Comment by lauriejim** [comment]
I will approve this PR when more than **50** 👍 will be added to your PR  😈

**Comment by derrickmehaffy** [comment]
What is the goal of this PR?

**Comment by Aurelsicoko** [comment]
Learn things during the setup and build time

**Comment by franciscop** [comment]
-1, seems to only add noise, specially on the Slack group where the author (who is also the main maintainer) is asking for votes 😬

**Comment by Aurelsicoko** [comment]
@franciscop It only adds facts for people who are cloning the GitHub repository. It doesn't appear when you're building the administration panel or running any commands in your project. Don't worry, I'm watching over the entire project to avoid noise and useless things! This feature only targets maintainers.

**Comment by soupette** [comment]
Furthermore it will be displayed only if your run `npm run setup:facts` `npm run setup:build:facts` and theses commands aren't referenced in the documentation

**Comment by franciscop** [comment]
Sure, no problem. But then why asking at all in unrelated places? Unless it is some kind of _growth hacking_ to get more users interested in the project (which I'd totally understand, just curious).

**Comment by alexleone** [comment]
I would be a fan if the facts where facts about the framework. If they are completely random, there is not a whole lot of value. If the strapi team wants to write custom facts then it may be a good idea, but seems like just a lot of work for not much value.

**Pull request closed without merging**
