### PR TITLE
fix: Discord Auth not assigning username correctly

### PR DESCRIPTION
**Pull request by gitstart**
#### [Fixes/issue](https://github.com/strapi/strapi/issues/17067)
Removes the discriminator from the username when creating a new user using Discord as the provider.
### Why is it needed?
Discord removed the discriminator, so now the username does not contain the number tag in them but strapi still stores that.
This PR updates the username based on the new naming rules.

#### Recreation:
1. Run the Project in the main branch
2. Navigate to [Settings/Providers](http://localhost:4000/admin/settings/users-permissions/providers)
3. Click on the edit button for Discord, and enable it, to get credentials:
a. Navigate to [Discord Developer Console](https://discord.com/developers/applications)
b. Create an app and you will be able to get  CLIENT_ID and CLIENT_SECRET from OAuth2/General
c. Add this [URL](http://localhost:1337/api/connect/discord/callback) to Redirects and save it: `http://localhost:1337/api/connect/discord/callback`
4. To Generate the URL to test it you can  follow [this guide](https://discord.com/developers/docs/getting-started#step-1-creating-an-app) remember to select `Identify` and `email` for permission before generating the URL
5. After you generate the URL, open it in a new browser tab, and Login with your discord, in the result you can see that the user_name contains #0
 
#### Fix:
1. Checkout to this branch fix/discord-username and run the project
2. Navigate to [Content Manager](http://localhost:1337/admin/content-manager)] then User and delete the user created in the Recreation step
3. Open The generated link in step 4 again and you will see the username no longer contains `#0`

### Demo
https://www.loom.com/share/6c28f247a3544bff89ffc53752d065d4

### CODE REVIEW

**Review by Convly — COMMENTED** [review]
Hey, thanks for the very detailed issue report & fix, it's very appreciated!

Regarding the fix, I've stumbled upon [this article](https://support-dev.discord.com/hc/en-us/articles/13667755828631#h_01GYA87X9QZ19H2X6PJ3M35ZDH) from Discord. It seems like the `#0` discriminator is a temporary solution to allow bots & apps to adapt over time.

> During migration, usernames will appear in payloads with a #0 discriminator at the end. Make sure to account for this temporary discriminator when updating your code.

I think your fix is great, but I would maybe add a `TODO` comment explaining why we're doing this special `#0` check (for instance, we can link the article I've shared)

Also from the article:

> If your code references usernames instead of IDs, we recommend updating this approach for a smoother transition.

I don't think this is relevant in our case as we don't really care about the user ID. We only want the displayed username.

**Comment by mallowsc** [comment]
Hi @Convly!

Thanks for reviewing this issue.  The Discord (user) ID may not be necessary for this fix but long term with Strapi integration, I think it would be a good idea to include.  If needed, I can include some of this outside of the fix.

Here are 2 examples: 
If the user changes their email address but the username stays the same, Strapi will create a new user potentially creating duplicates and causing data to be inaccurate or maybe other unforeseen things.
A user can also change their username ever so often but keep the email the same.  Depending on how the front end is configured, there is the potential for the username shown to be inaccurate.

Adding the Discord ID will allow Strapi (if implemented) to update any and all values for the user record needed.   It also adds additional benefit for Discord Bot Developers (such as myself).  Hope this helps.

**Comment by Convly** [comment]
Thanks for the detailed answer!

While I do agree with you that the discord user ID makes more sense than the email to target individual accounts. Strapi only accepts the email as a discriminator to find unique users.

Handling discord IDs as a way to differentiate users means that we would need to create additional logic & add columns to the user table, just for Discord.

Maybe there is a way to generalize that, but I'm not sure about what we could come up with that don't break current implementation

**Comment by mallowsc** [comment]
> Thanks for the detailed answer!
> 
> While I do agree with you that the discord user ID makes more sense than the email to target individual accounts. Strapi only accepts the email as a discriminator to find unique users.
> 
> Handling discord IDs as a way to differentiate users means that we would need to create additional logic & add columns to the user table, just for Discord.
> 
> Maybe there is a way to generalize that, but I'm not sure about what we could come up with that don't break current implementation

Other than a database migration script to add the column to the user table, I agree.

**Comment by ahzia** [comment]
@Convly I have added the article as a TODO comment.
is there anything else I should update?
CC: @mallowsc

**Pull request closed without merging**
