### PR TITLE
adds styling to drag icon to support dark mode

### LINKED ISSUE #15141: Drag icon in repeatable component not visible in dark mode
### Required System information

- Node.js version: 16.18.0
- NPM version: 8.19.2
- Strapi version: 4.5.3
- Database: Not Relevant
- Operating system: Windows 11

### Describe the bug

In the dark mode, the *Drag* icon is not visible, adding repeatable components.

### Steps to reproduce the behavior

 1.   Create a content-type with a repeatable component
 2.   Add items and observe.
 
### Expected behavior
Icon's color should change according to the mode. For Example - In light mode it has dark color.
That same color is being used here.

### Screenshots

On hover - 

Drag Icon - On Hover

Without hover - 

Drag Icon - Without hover

### PR DESCRIPTION
**Pull request by BhuvaneshPatil**
- Refer to the issue you are closing in the PR description: Fix #15141 

### What does it do?

adds styling for drag icon for better visibility in dark mode.

### CODE REVIEW

**Comment by BhuvaneshPatil** [comment]
Hi @joshuaellis , sorry for the clutter apparently my email wasn't mentioned in the git config.
I hope CLA issue won't be there.

**Comment by joshuaellis** [comment]
@BhuvaneshPatil think you'll need to update the snapshots to get the tests to pass 😄

**Comment by BhuvaneshPatil** [comment]
> @BhuvaneshPatil think you'll need to update the snapshots to get the tests to pass 😄

@joshuaellis , can you help me with writing snapshot test, I can't find where these tests has to be written.

**Comment by joshuaellis** [comment]
You don't write snapshot tests. They're automatic, see this document for `jest` – https://jestjs.io/docs/snapshot-testing#updating-snapshots

**Comment by ronronscelestes** [comment]
hi @BhuvaneshPatil 
at the root (not admin, not getstarted) of your project you should be able to run `yarn test:front -u`

image

try to `yarn setup` at the root of the project before if you still encounter an issue

**Comment by joshuaellis** [comment]
These tests are still failing. We'll be releasing #15119 on 25th Jan so I'm going to close this PR as that PR has a fix for this. Thanks for your work :)

**Pull request closed without merging**
