### PR TITLE
Fix remove single item by "remove all selected"

### PR DESCRIPTION
**Pull request by nobodywithbody**
My PR is a:

🐛 Bug fix

Main update on the:

Framework

step to reproduce bug:
* use postgresql as database
* select one item of type
* click on "1 entry selectedDelete all"
* Postgresql error for not correct query build

explanation:

If selected one item `isNumeric` return `true` on `[someId]` and then generated not correct query for db, because search `in` need `list`.

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello @nobodywithbody why did you delete this PR ?

**Comment by nobodywithbody** [comment]
This bug reproduced only in my project. In new generated project this bug not occur. This changes solved bug, but i guess basic problem in my code.

**Comment by lauriejim** [comment]
Okay, thank you @nobodywithbody.

**Comment by nobodywithbody** [comment]
I can repeat this bug on new project!)

Knex version >= 0.14.5 (ideal is the latest version)

In `plugins/content-manager/config/queries/bookshelf.js:12` added `where` to query.
Before 0.14.5 knex generate correct sql in both version - argument as number or argument is array of number.
After 0.14.4 knex generate this sql `SELECT * FROM table WHERE id IN 5` if  where is not array.

Changes on this PR fixed this bug because where always include array type in `IN` expression.

**Comment by lauriejim** [comment]
Hello @nobodywithbody . Can you check if it's already not fix on master please.
Make a `setup:build` with strapi master branch. And I think it's already fixed.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.

**Pull request closed without merging**
