### PR TITLE
Update digitalocean-one-click.md

### PR DESCRIPTION
**Pull request by kenara**
Warn user to set up initial admin, otherwise anyone who knows the machine IP can do it!

### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Review by derrickmehaffy — APPROVED** [review]
Lgtm

**Review by derrickmehaffy — CHANGES_REQUESTED** [review]
Ah actually can you please update the v3 docs, not the v3 beta docs

**Comment by kenara** [comment]
Done

Nov 16, 2020, 13:02 by notifications@github.com:

**Comment by derrickmehaffy** [comment]
Closing in favor of https://github.com/strapi/strapi/pull/8660

**Pull request closed without merging**
