### PR TITLE
Migrate to higher performance bcrypt implement

### PR DESCRIPTION
**Pull request by Brooooooklyn**
[@node-rs/bcrypt](https://www.npmjs.com/package/@node-rs/bcrypt) is `4~8x` faster than `bcryptjs`.

And compare to [node bcrypt](https://www.npmjs.com/package/bcrypt), `@node-rs/bcrypt` has no `postinstall` download scripts nor `node-gyp`.

Benchmark:

- [@node-rs/bcrypt](https://www.npmjs.com/package/@node-rs/bcrypt)
- [node bcrypt](https://www.npmjs.com/package/bcrypt)
- [bcryptjs](https://www.npmjs.com/package/bcryptjs)

```
@node-rs/bcrypt x 70.38 ops/sec ±1.40% (32 runs sampled)
node bcrypt x 63.88 ops/sec ±0.95% (30 runs sampled)
bcryptjs x 12.23 ops/sec ±4.90% (10 runs sampled)
Async hash round 10 bench suite: Fastest is @node-rs/bcrypt
@node-rs/bcrypt x 16.55 ops/sec ±2.33% (11 runs sampled)
node bcrypt x 14.62 ops/sec ±1.48% (11 runs sampled)
bcryptjs x 3.12 ops/sec ±1.60% (6 runs sampled)
Async hash round 12 bench suite: Fastest is @node-rs/bcrypt
@node-rs/bcrypt x 3.65 ops/sec ±5.08% (6 runs sampled)
node bcrypt x 3.50 ops/sec ±2.14% (6 runs sampled)
bcryptjs x 0.84 ops/sec ±12.31% (5 runs sampled)
Async hash round 14 bench suite: Fastest is @node-rs/bcrypt
@node-rs/bcrypt x 18.78 ops/sec ±0.86% (12 runs sampled)
node bcrypt x 16.28 ops/sec ±3.55% (11 runs sampled)
bcryptjs x 3.70 ops/sec ±2.64% (6 runs sampled)
Async verify bench suite: Fastest is @node-rs/bcrypt
```

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hello, Thank you for this PR but we are going to stick with the current library we are using. Performance only is not enough to make us switch to a new library that concerns security :) 

Closing this for now

**Comment by derrickmehaffy** [comment]
Yeah I'll have to agree here, the new package listed is far too new to be considered secure.

**Comment by Brooooooklyn** [comment]
> Performance only is not enough to make us switch to a new library that concerns security :)

`@node-rs/bcrypt` is based on [bcrypt](https://crates.io/crates/bcrypt), which is wildly used in Rust ecosystem (`205k` downloads) and 0 line `unsafe` codes. I believe it is safer and faster than `c` implementation.

BTW, `@node-rs/bcrypt@1.0.0` now support `apple silicon, android aarch64, linux aarch64, linux armv7, linux musl` prebuild binaries, and I believe it will make it easier to install and use.

**Comment by Brooooooklyn** [comment]
Hey all, `parse-server` has introduced `@node-rs/bcrypt` more than half a year ago, and zero securely issue reported, would you reconsider to introduce `@node-rs/bcrypt` in `strapi`?

Pull request which introduced `@node-rs/bcrypt` into `parser-server`:  https://github.com/parse-community/parse-server/pull/6794

@alexandrebodin

**Pull request closed without merging**
