### PR TITLE
Add & update Czech translation

### PR DESCRIPTION
**Pull request by choutkamartin**
Hello, I did a few tweaks in the Czech language of the admin interface. I'm going to do the same with plugins in the upcoming days/weeks. Also, do we still need to use "Kai Doe" ([#8738](https://github.com/strapi/strapi/pull/8738)) instead of using some local names (for example Jiří Novák)? I'm asking because, for example, the Slovak language uses localized names.

The PR is work in progress.

### What does it do?

Changes and adds Czech language strings.

### Why is it needed?

The admin interface is not fully translated when the Czech language is selected.

### How to test it?

Doesn't need to be tested.

### Related issue(s)/PR(s)

None

### CODE REVIEW

**Comment by hondem** [comment]
This is really needed 🙏  Can we push this somehow please?

**Comment by choutkamartin** [comment]
> This is really needed 🙏 Can we push this somehow please?

I don't have much time lately, as I'm dealing with other projects and going on vacation in 4 days, but I can assure you that I will finish this PR at the end of this month. 🙂

**Comment by hondem** [comment]
Can I contribute somehow?

**Comment by choutkamartin** [comment]
> Can I contribute somehow?

Yeah. I think it would be best to keep all Czech translations in this PR. You can fork my Strapi repo, make some changes in the `update-czech-language` branch, commit them and make a pull request to my repo. After we merge the pull request, your changes will show there. I still haven't translated some of the plugins, so you can translate them. Also, you can proofread some of the strings I've already translated. 🙂

**Comment by derrickmehaffy** [comment]
Hi 👋  
We now have released the `v4`. As of now, the `v3` is in maintenance mode for 6 months. We will only be fixing critical and security issues on v3 from now on. 
I will go ahead and close this PR. Thank you for contributing to Strapi 🔥

**Comment by hondem** [comment]
Nice job there! Tips for people, who still have to use this PR and merge it into the project. You can basically use `patch-package` (https://www.npmjs.com/package/patch-package) and create quick patch for your dependencies. One additional thing to do is that you have to export newly created translations in `translations/index.js`. So if your translation doesn't exist (the file wasn't there before), you have to export it.

**Pull request closed without merging**
