### PR TITLE
Fix: Remove @strapi/babel-plugin-switch-ee-ce again

### PR DESCRIPTION
**Pull request by gu-stav**
### What does it do?

Removes the `@strapi/babel-plugin-switch-ee-ce` package again. 

### Why is it needed?

It had been removed first in https://github.com/strapi/strapi/pull/17206, but was accidentally re-introduced in https://github.com/strapi/strapi/commit/7bdef3d27843c78666c85f30dc2f1bcf4d6b805e#diff-0c24787bb61753b049782d9abba3055411f9d2c558941fa96712bd74239e297b

### Related issue(s)/PR(s)

- https://github.com/strapi/strapi/pull/17350

### CODE REVIEW

**Comment by gu-stav** [comment]
@Marc-Roig Do you think this needs to go into the 4.11.6 release branch?

**Comment by Marc-Roig** [comment]
@gu-stav sure, @Convly  as you are doing the release this week, do you mind if we cherry pick this change into the release branch?

**Comment by gu-stav** [comment]
@Marc-Roig Are you asking me or @Convly? 🙈

**Comment by Marc-Roig** [comment]
@gu-stav @Convly  !

**Comment by Convly** [comment]
Since it might be required for the release anyway, let's go

**Pull request merged**
