### PR TITLE
[Data transfer] Allow trailing slash from admin url in remote transfer

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

Strips a single trailing slash, if present, from the admin url path provided by the user for a remote transfer

### Why is it needed?

Some users may enter a URL such as `http://localhost/admin` and others may enter `http://localhost/admin/` and both are valid admin url paths

Entering more than a single slash is indicative of an error however, and could lead to unexpected behavior if we allowed it.

### How to test it?

Run a transfer (push and pull) with a URL that contains a trailing slash, and that does not contain a trailing slash

### CODE REVIEW

**Review by Convly — COMMENTED** [review]
LGTM
Just for readability and maintenance, could you just extract the logic to a function we could export from the DTS Strapi providers' utils?
Smth like
```ts
const trimTrailingSlash = str => replace(/\/$/, '');
```

**Review by christiancp100 — APPROVED** [review]
LGTM! 🍝

**Comment by innerdvations** [comment]
> Silly question but why add this as far as src/utils/provider instead of just putting it in the remote strapi provider utils (since it only applies to them) `packages/core/data-transfer/src/strapi/providers/utils.ts`

It was just to make it available at a slightly higher level in case anything else wanted to re-use it, but I don't have a strong preference either way so I just moved it to the Strapi providers utils.

**Review by Convly — DISMISSED** [review]
LGTM, waiting for the tests to pass

**Comment by innerdvations** [comment]
> LGTM, waiting for the tests to pass

Oh no, they failed. I'll take a look and let you know when it's fixed.

**Pull request merged**
