### PR TITLE
Update ES translations

### PR DESCRIPTION
**Pull request by maturano**
My PR is a:

💅 Enhancement

Main update on the:
Admin

- Fix minor errors and improve translation done with #1566 after review it in context.
- Add missing translations reported on #1621 

Improvement area:
Normalize the tone. There are impersonal and personal styles mixed. I'm on use a personal-friendly style. This is, Instead of "Configure sus opciones" (impersonal - formal - third person), prefer "Configura tus opciones" (personal - friendly - first person).

### CODE REVIEW

**Comment by maturano** [comment]
@akkys77 Can you take a look? 👀  What do you thing?

**Comment by akkys77** [comment]
Hi Alberto,
Regarding your Tone comment, I chose the formal tone in Spanish because that's the choice that was made for French. 
In French, Strapi is using formal style `Vous` that corresponds to Formal style `Usted` in Spanish. 
So I totally agree with your point: Normalise the tone, I am just wondering whether we should normalise to formal or informal.
Do you know who can weigh in on this ?
If having informal tone in Spanish is OK, then your corrections and addition of missing keys are definite improvements.

**Comment by maturano** [comment]
> In French, Strapi is using formal style Vous that corresponds to Formal style Usted in Spanish.

😮 I didn't know that. 🤔 ... I think the informal way is better for the UX, but let align with the original style. I'll do the changes...

**Comment by maturano** [comment]
Done!. Rebased and squashed...

**Comment by lauriejim** [comment]
Will need @Aurelsicoko mindset about the style to use in any languages.

**Comment by Aurelsicoko** [comment]
I confirm we're using the formal tone. Thank you so much for this PR!

LGTM 👍

**Pull request merged**
