### PR TITLE
Add config options for AutoOpen by default

### PR DESCRIPTION
**Pull request by derrickmehaffy**
My PR is a:
💅 Enhancement

Main update on the:
Framework

Added the config options for the autoOpen option to the server.js configs by default on generation to make it easier to find and change.

Personally I think it should be disabled by default on development, on most environments it does not refresh the current tab and instead opens up a new one. Very frustrating when you are trying to add models using the content-type builder or directly editing files while the server is running. Every time it auto-restarts it opens a new tab.

@Aurelsicoko thoughts on this? If you agree we can disable it by default I'll push the change.

### CODE REVIEW

**Comment by Aurelsicoko** [comment]
@derrickmehaffy We should only auto-open the administration when the command `strapi start` is done manually. If we are in the case of an auto-reload, we should not auto-open the dashboard.

It will reduce the frustration. If it's not enough, we should only auto-open for the first start.

**Comment by derrickmehaffy** [comment]
I'm thinking @Aurelsicoko maybe some kind of trigger on the strapi start command like `strapi start -autoopen`

**Comment by Aurelsicoko** [comment]
It makes the command line more complex for a little feature. I still want the newcomers to run `strapi start`, then we handle the logic to only auto-open on the first start. IMO, it should be an option disabled by default if you're not using a Macintosh and only triggered when the user is running the `strapi start` command, not during an auto-reload...

What do you think about that?

**Comment by derrickmehaffy** [comment]
(As for adding something like this, I feel it might be a bit above my head. I can try and figure it out)

If there is a way to for sure make sure it doesn't open a new tab and only refreshes great, but yeah I see the benefit of this. Coming from a light php background I'm used to refreshing the page. Previous experience working with nodejs I don't know why the AdminUI doesn't auto-refresh anyway :confused:

**Comment by lauriejim** [comment]
Hello @derrickmehaffy, I will merge your PR.
Can you open an issue about the optimisation of the windows focus please.

**Pull request merged**
