### PR TITLE
Fix date and datetime required validations issue

### LINKED ISSUE #7186: Entries can't be saved when boolean field is set as required
**Describe the bug**
Whenever I edit an entry where the collection has a boolean field with `required: true`, I can't save the entry.
I get the error message "This field is required", I try to toggle it with no success. Then if I change the boolean field to `required: false` it works.

Note: I didn't change the model and it worked before migrating

**Steps to reproduce the behavior**

1. Go to a collection list view
2. Click on any entries to edit the data
3. Edit a field
4. Try to save
5. You get an error that the boolean field is a required field, even though it is selected

**Expected behavior**
The entry is supposed to be saved because the boolean field was already selected when attempted to save the entry.

**Screenshots**
image

**System**
- Node.js version: v12.13.1
- NPM version: 6.14.6
- Strapi version: 3.1.1
- Database: Postgresql 12.3
- Operating system: Linux

### PR DESCRIPTION
**Pull request by soupette**
Signed-off-by: soupette <cyril.lpz@gmail.com>

#### Description of what you did:
This PR fixes the required validation issue when updating a entry that has a required date field.

- Fixes #7186 
- Fixes #7183

### CODE REVIEW

**Comment by ralphsomeday** [comment]
> LGTM. @ralphsomeday does that fix your issues ?

@alexandrebodin this should fix it :)! thanks. I guess you will be releasing it in 3.1.2, right?

**Comment by pjamieson** [comment]
Just updated to 3.1.2. Issue with required boolean values remains as described above.

**Comment by alexandrebodin** [comment]
@pjamieson did you rebuild your admin ?

**Comment by pjamieson** [comment]
Yes. I have both re-installed with yarn and rebuilt Strapi with yarn develop. (And I see the same issue in a production build.)

Originally, I was running 3.0.5, and did not have this issue with the required boolean values. The problem started when I updated to 3.1.1, and remains after updating to 3.1.2.

When I initially try to save an update, the boolean values  (I have 3 required boolean values in this case) are flagged as required in the UI, even though they were previously set and have not been touched. Toggling them makes the warning in the Admin UI go away, but saving still does not work, and validation errors still appear in the Chrome Dev Tools.

FYI, in one case (with v3.1.1) a required decimal value (for a price) appeared to exhibit the same problem even though it already had a previously entered valid entry of 0.00. I have not dug into that one, as I have been focused on the booleans.

Thanks for looking into this.

Patrick Jamieson

**Pull request merged**
