### PR TITLE
fix: Update env.example

### PR DESCRIPTION
**Pull request by xiaotiandada**
### What does it do?

Modify the example environment variable.

### Why is it needed?

Because .env.example and .env are inconsistent

### How to test it?

Initialize the project

### Related issue(s)/PR(s)

No.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
This example isn't complete either :thinking:

**Comment by xiaotiandada** [comment]
> 

Incomplete refers to `.env.example`? 🤔

**Review by christiancp100 — APPROVED** [review]

**Comment by Convly** [comment]
@xiaotiandada could you sign the CLA so that we can move forward with this, please? :eyes:

**Comment by xiaotiandada** [comment]
> @xiaotiandada could you sign the CLA so that we can move forward with this, please? 👀

emmmmm........ ok, let me see how to deal with it

**Comment by xiaotiandada** [comment]
> [CLA assistant check](https://cla.strapi.io/strapi/strapi?pullRequest=16570) All committers have signed the CLA.

Signing the CLA for the first time, seems to be done.  @Convly

**Pull request merged**
