### PR TITLE
Hide content type

### PR DESCRIPTION
**Pull request by vibhor-mungee**
This PR closes: [#3678](https://github.com/strapi/strapi/issues/3678)

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [x] Admin
- [ ] Documentation
- [ ] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [x] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
I'm not entirely sure if they will merge this into base code, in the past @Aurelsicoko has stated they don't want display level stuff in the model settings themselves (as much as many people disagree with that, myself included).

Either way thank you for the PR, I can at least use it as a reference for those who do want to hide stuff, they may just need to apply it to their own projects.

**Comment by soupette** [comment]
I will need @alexandrebodin and @Aurelsicoko approval on this one. IMO hiding and displaying content types from the menu is a settings that should not be set in the content type's settings file.

**Comment by derrickmehaffy** [comment]
> I will need @alexandrebodin and @Aurelsicoko approval on this one. IMO hiding and displaying content types from the menu is a settings that should not be set in the content type's settings file.

We shall have to agree to disagree on that 😝 I can see the benefit of hiding a model that should never be interacted with directly in code to prevent someone from "enabling" it while in production and breaking stuff like automated history models or whatever. There are man use-cases where this would be nice to have.

**Comment by vibhor-mungee** [comment]
> > I will need @alexandrebodin and @Aurelsicoko approval on this one. IMO hiding and displaying content types from the menu is a settings that should not be set in the content type's settings file.
> 
> We shall have to agree to disagree on that 😝 I can see the benefit of hiding a model that should never be interacted with directly in code to prevent someone from "enabling" it while in production and breaking stuff like automated history models or whatever. There are many use-cases where this would be nice to have.

I agree, my use case was pretty straight forward- hiding the content-types created for many-to-many relationships. Will never use it from admin dashboard.

**Comment by alexandrebodin** [comment]
Hi, @vibhor-mungee Sorry but I'm not willing to add that to the repo right now. You can just do it as en extension like you just did in your project for no. 

The reason is simply to avoid adding configurations for every single usecase users have. This just increase complexity exponentially.

This might be done with programmatic api instead in the future or sth. Be not a priority right now tbh.

Hope you understand the reason behing us not closing the issue and hope I will see more PRs from you ;) Make sure to open issues before making PR to avoid this happenning to you :D

**Pull request closed without merging**
