### PR TITLE
OpenID Connect login provider

### PR DESCRIPTION
**Pull request by lapphan**
#### Description:
Add example for adding a new provider with OpenID Connect using Keycloak.

#### My PR is a:
- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix #issueNumber
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:
- [ ] Admin
- [x] Documentation
- [ ] Framework
- [ ] Plugin

#### Manual testing done on the following databases:
- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [x] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello! I close this PR because we just put an example to add a new providers.
If we start to add all providers in the documentation it's not possible.
Please can you provide a PR to add it in the plugin `users-permissions` please.

**Comment by lauriejim** [comment]
In any case - thank you for your work!

**Comment by MatheusRV** [comment]
Hello, sorry for this. But why not move forward adding keycloak as one login provider. Is there a technical debit behind this? Could someone explains?

**Comment by derrickmehaffy** [comment]
> Hello, sorry for this. But why not move forward adding keycloak as one login provider. Is there a technical debit behind this? Could someone explains?

We did start accepting new providers a little while ago, you are welcome to open a new PR however it won't be merged until after the documentation change freeze.

**Comment by mrabusalah** [comment]
any updates ?

**Pull request closed without merging**
