### PR TITLE
Update "upgrade major" rules

### PR DESCRIPTION
**Pull request by Convly**
### What does it do?

Refines the logic for calculating version ranges for `major` version upgrades:
- Update the major range from `<= next_major.0.0` to `<= next_major` , which translates to `< next_next_major.0.0-0`
- Include more intuitive comments to clarify the purpose and behavior of each range calculation.

### Why is it needed?

Targets the latest `minor.patch` when doing a `major` upgrade instead of targeting the first `patch` of the next `major`.
This helps mitigate migration issues from early versions of new majors.

### How to test it?

1. Run the updated unit tests in `range.test.ts`.
2. Verify that the new ranges (`<=2` instead of `<=2.0.0`) are generated correctly in different scenarios.

**or**

Test migrating a `v4` application on latest `minor` to the latest `v5` patch (`5.0.4` at the time of writing this)

### CODE REVIEW

**Comment by Convly** [comment]
@butcherZ oops, yes this was an issue addressed in https://github.com/strapi/strapi/pull/21751, I've merged it in this branch. If you do another experimental, this should be fixed :slightly_smiling_face:

**Review by butcherZ — APPROVED** [review]
LGTM! tested with `0.0.0-experimental.76999222c105ee5da1bc2540e3b5e5f57747300c`  well done :D

**Comment by Convly** [comment]
Related doc PR: https://github.com/strapi/documentation/pull/2259

**Review by innerdvations — APPROVED** [review]
LGTM, tested and works great!

**Review by Marc-Roig — APPROVED** [review]
GREAT, this fixes a couple of open issues

**Pull request merged**
