### PR TITLE
[Unit testing doc] add runtime fix

### PR DESCRIPTION
**Pull request by Antoine-lb**
#### Description of what you did:
I just changed the `note` for a `tip` because is not showing in the docs. 
More info about the modification at https://github.com/strapi/strapi/discussions/7549

### CODE REVIEW

**Review by derrickmehaffy — APPROVED** [review]
English structure looks good, can't comment about the content as I'm not super familiar with unit testing

**Comment by derrickmehaffy** [comment]
@Antoine-lb Sorry the late merge, can you quickly review the conflicts and resolve them and I can merge this in.

**Comment by alexandrebodin** [comment]
Hi @Antoine-lb there are some conflicts on this PR. Can you fix them so we can merge it ?

**Comment by Antoine-lb** [comment]
now is ready, sorry for the delay

**Pull request merged**
