### PR TITLE
3.0.0-alpha.12.7

### PR DESCRIPTION
**Pull request by lauriejim**
Migration guide: https://github.com/strapi/strapi/wiki/migration-guide-alpha.12.6-to-alpha.12.7

Changelog: https://github.com/strapi/strapi/releases/tag/3.0.0-alpha.12.7

### CODE REVIEW

**Comment by mnlbox** [comment]
@lauriejim Changelog URL is broken.

**Comment by lauriejim** [comment]
@mnlbox It's updated. Thank you for the report.

**Comment by mnlbox** [comment]
@lauriejim your welcome. With this migration guide my extra permission gone. (I added some new role but after migrate to 12.7 my extra role is lost)
I think we need copy some file to new `plugin` folder right?

**Comment by lauriejim** [comment]
If you did some plugin customization, absolutely yes

**Comment by mnlbox** [comment]
So please provide some docs about this. I can't find where is new role stored to backup or re add after upgrade Strapi version. :thinking:

**Pull request merged**
