### PR TITLE
fix(content-manager): pass field to CustomField input to have backward compatibility

### PR DESCRIPTION
**Pull request by Feranchz**
### What does it do?

Pass field values to CustomField Input so we can have backward compatibility and don't introduce a breaking change.

### How to test it?

Use a Custom Field without using `useField`, instead use `value` and `onChange` that you should receive as param in your Input CustomField 

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/20915

### CODE REVIEW

**Review by remidej — COMMENTED** [review]
Could you update the color picker custom field to use this? This way our example custom fields would match the docs, and we can test this PR more easily

**Comment by Feranchz** [comment]
> Could you update the color picker custom field to use this? This way our example custom fields would match the docs, and we can test this PR more easily

@remidej Color Picker custom field is using `useField` currently, which I think is what we want users to do, and keep this as a backward, right? 🤔

**Comment by remidej** [comment]
@Feranchz It's a question of point of view IMO: which is the recommended approach? both are fine, but I tend to prefer putting the props approach as the recommended one because:
- if you build a plugin like this, it works with v4 and v5, while using useField breaks v4
- it's the method the docs currently show, so no need to change them
- there's a lot of info that's available in the props and not the hook (name, required, hint, label, labelAction, etc.). So I like getting my data from 1 place instead of an arbitrary mix of props and useField

What do you think?

**Comment by Feranchz** [comment]
> @Feranchz It's a question of point of view IMO: which is the recommended approach? both are fine, but I tend to prefer putting the props approach as the recommended one because:
> 
> * if you build a plugin like this, it works with v4 and v5, while using useField breaks v4
> * it's the method the docs currently show, so no need to change them
> * there's a lot of info that's available in the props and not the hook (name, required, hint, label, labelAction, etc.). So I like getting my data from 1 place instead of an arbitrary mix of props and useField
> 
> What do you think?

@remidej I agree with all you mentioned. So I change the current ColorPickerInput

**Comment by remidej** [comment]
@Feranchz looks like there's a TS issue

**Review by remidej — APPROVED** [review]
🎯

**Pull request merged**
