### PR TITLE
Improve graphql perf

### PR DESCRIPTION
**Pull request by alexandrebodin**
#### Description of what you did:

Might Fix https://github.com/strapi/strapi/issues/4080 it needs testing by @JelmerV-WFC

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [x] MongoDB
- [x] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by JelmerV-WFC** [comment]
Will test it, thanks @alexandrebodin!

**Comment by JelmerV-WFC** [comment]
I don't think it's improving much at my side, at first sight. But it can be my connection that's the issue right now (on 4G in a train ;-)).

**Comment by JelmerV-WFC** [comment]
@alexandrebodin is it possible that after this merging this pull request the relations are not returned anymore?

**Comment by alexandrebodin** [comment]
@JelmerV-WFC yes the PR is only working for SQL a the moment if you are using mongo I need to do some updates. Will keep you updated

**Comment by JelmerV-WFC** [comment]
> @JelmerV-WFC yes the PR is only working for SQL a the moment if you are using mongo I need to do some updates. Will keep you updated

Okay! Thanks!

**Comment by alexandrebodin** [comment]
@JelmerV-WFC Can you test this again ?

**Comment by JelmerV-WFC** [comment]
@alexandrebodin it did improve the performance for what I can see. @derrickmehaffy did you had the time to test it?

**Comment by derrickmehaffy** [comment]
Not yet @JelmerV-WFC I'll be doing it tonight when I get to work.

**Comment by JelmerV-WFC** [comment]
I also can confirm that this fixes the performance issues with Mongoose!

**Comment by devyourcar** [comment]
@alexandrebodin thanks so much for this!

**Comment by mbistuer** [comment]
@alexandrebodin  
hello, it works worse for me than before with giant loading times that if I have custom queries with bookself they worked better with the other version
Mysql
`return strapi.models['account']
        .query(qb =>
          qb
            .leftJoin('accounts_categories__categories_accounts', function() {
              this.on(
                'accounts.id',
                '=',
                'accounts_categories__categories_accounts.account_id'
              );
            })
            .leftJoin('categories', function() {
              this.on(
                'categories.id',
                '=',
                'accounts_categories__categories_accounts.category_id'
              );
            })
            .leftJoin('categories_users__users_categories', function() {
              this.on(
                'categories.id',
                '=',
                'categories_users__users_categories.category_id'
              );
            })
            .leftJoin('users-permissions_user', function() {
              this.on(
                'categories_users__users_categories.user_id',
                '=',
                'users-permissions_user.id'
              );
            })
            .where(function() {
              this.where('users-permissions_user.id', '=', id);
            })
            .where(function() {
              this.where('accounts.type', '=', params.type);
            })
            .orderBy('name')
        )
        .fetchAll();`


Captura de pantalla 2019-10-08 a las 20 35 01

**Pull request merged**
