### PR TITLE
scoped provider packages doc

### PR DESCRIPTION
**Pull request by tudorilisoi**
Signed-off-by: Tudor Ilisoi <tudorilisoi@yahoo.com>

#### Description of what you did:

Updated the docs to include aliasing scoped packages as email providers

### CODE REVIEW

**Comment by tudorilisoi** [comment]
@derrickmehaffy Done

**Comment by derrickmehaffy** [comment]
@alexandrebodin we will need to merge the master into the doc branch since the release of 3.0.4 and it should clean up this PR

**Comment by tudorilisoi** [comment]
I opened another PR, I hope this last one is better
https://github.com/strapi/strapi/pull/6753

**Comment by derrickmehaffy** [comment]
Will do thank you, closing this one

**Pull request closed without merging**
