### PR TITLE
Fix/required fields UI

### PR DESCRIPTION
**Pull request by ronronscelestes**
## What

Indicate required fields in following forms:
- API Tokens
- Profile page
- Webhooks
- Users create / edit

+ Fix uid field UI when it is required #11809

## Snapshots

Screenshot 2022-01-05 at 12 13 35

Screenshot 2022-01-05 at 12 13 56

Screenshot 2022-01-05 at 12 14 24

Screenshot 2022-01-05 at 12 14 38

Screenshot 2022-01-05 at 12 14 59

## UID required

Screenshot 2022-01-05 at 13 36 19

### CODE REVIEW

**Review by HichamELBSI — APPROVED** [review]
LGTM

**Comment by abdonrd** [comment]
This doesn't fix the UIDs, right? https://github.com/strapi/strapi/issues/11809

**Comment by ronronscelestes** [comment]
> This doesn't fix the UIDs, right? #11809

Hi, thank you for highlighting this issue!
I think I found a solution for the uid situation if you want to check it out!

**Comment by abdonrd** [comment]
Thanks @ronronscelestes, it works!

**Review by soupette — APPROVED** [review]

**Comment by abdonrd** [comment]
@ronronscelestes sorry for the late warning, but I think the same thing happens with "Rich text" fields.

**Comment by ronronscelestes** [comment]
> @ronronscelestes sorry for the late warning, but I think the same thing happens with "Rich text" fields.

@abdonrd Oh sorry I saw that too late, you're right! I'll create a new PR to handle it :)

**Comment by abdonrd** [comment]
@rockmandash I see one more 🙈

The `Text` when you select the `Long text` type.

**Comment by abdonrd** [comment]
@rockmandash I see one more!

The User password:
Screenshot 2022-01-11 at 14 23 07

**Comment by ronronscelestes** [comment]
Thank you @abdonrd! 
I'll fix those 2 and try every type of fields with the required mode, hoping to catch them all 😅

**Pull request merged**
