### PR TITLE
Update Docs to Vuepress

### PR DESCRIPTION
**Pull request by MartinMuzatko**
My PR is an:

💅 Enhancement

Main update on the:

Documentation

image

So this is a major overhaul of the documentation. 
The reason to introduce a server-side-rendered but javascript enabled documentation is to easily implement documentation modules such as API generator. See #1758.

**You will get the following features:**
- Development and deployment should be a lot more comfortable (I wrote a little blogpost about the benefits compared to regular content management here: https://happy-css.com/articles/from-processwire-to-vuepress-why-i-gave-up-my-shiny-wysiwyg-for-a-static-site-generator/)
- Hot Module Replacement - you can add content during development and stay at the same page/scroll height
- Vue Components - dynamic explanations are easier to build than gifs with animations.

**Building the project:**
``` sh
cd docs
npm i
# Development
npm run dev
# localhost:8080
# Alternatively:
npm i -g vuepress
vuepress dev
```

**Todos left:**
- [x] check docs for style
- [x] check if sidebar is ok (for both versions)
- [x] replace blockquotes with info containers (https://vuepress.vuejs.org/guide/markdown.html#custom-containers)
- [x] add correct metadata and favicon

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Main 3.x.x page is a little off:
image

I think using the larger badges might be needed

**Comment by derrickmehaffy** [comment]
Requests menu has a duplicate:

image

**Comment by lauriejim** [comment]
@MartinMuzatko It work like a charm ! Great job!

Did you know if it's possible to render it with `/documentation` prefix ?
To have `/documentation/3.x.x` instead of `/3.x.x`

**Comment by MartinMuzatko** [comment]
Yep that  is a setting in the  `.vuepress/config.js`. The `base` property should do that :)

**Comment by MartinMuzatko** [comment]
I am not sure if it is a good idea to commit the `dist` folder. We need to add this to .gitignore

**Comment by lauriejim** [comment]
Yes you are right @MartinMuzatko! It's a mistake.
We have to add it in the `.gitignore`.

When you think you can finish the last point `add correct metadata and favicon` ?
I can't wait to merge your PR and publish this new version of the doc in our website.

**Comment by MartinMuzatko** [comment]
will do today :)

**Pull request merged**
