### PR TITLE
Add uuid attribute translations and uuid icon for content builder

### LINKED ISSUE #4340: uuid treated as a relation in backoffice entity configuration
**Describe the bug**
When using uuid as a primary key, it is treated as a relation instead of a simple property (uuid). Icon for uuid doesn't exist as well.

**Screenshots**
Screenshot 2019-10-23 at 16 33 27

**System**
- Node.js version: 12.1.0
- NPM version:
- Strapi version: 3.0.0-beta.17.3
- Database: postgres
- Operating system: MacOS

### PR DESCRIPTION
**Pull request by mhelmetag**
#### Description of what you did:

I added translations for the UUID attribute for the content type builder and a placeholder icon (should be replaced in by whatever svg y'all want) so that the missing icon and placeholder translation string can go away.

Fixes #4340 

Before:
Screen Shot 2019-10-30 at 1 46 25 AM

After*:
Screen Shot 2019-11-01 at 10 57 35 AM

\* Using a placeholder icon for Uuid.

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [x] SQLite

### CODE REVIEW

**Comment by mhelmetag** [comment]
@Aurelsicoko, @lauriejim mentioned you could suggest an icon for uuid? If you could, I could replace the placeholder one I used (copied from the string icon).

Thanks!

**Comment by lauriejim** [comment]
Hello @mhelmetag !
Thank you for your PR.
Just waiting for the right icon and then we are OK.
@Aurelsicoko will send it to you today.

**Comment by Aurelsicoko** [comment]
I have a question: did you follow the RFC (see https://github.com/strapi/rfcs/pull/3) to implement the UUID type?

Here how the icon should look like: 
key_icon

> We move the icons in our components library Buffet.js. @soupette might give you more insights how to use it.

Here the SVG file for the key icon: https://cloudup.com/c9cf9sbWcRN

**Comment by mhelmetag** [comment]
@Aurelsicoko , I didn't add the UUID type myself so I can't comment on whether or not the steps in the RFC were followed. It looks like it's not fully implemented as @derrickmehaffy said "UUID support isn't entirely there yet" in #4340 .

This PR is just to add the translation string and icon since they are missing when viewing a UUID field in the content builder.

I can try helping finish the UUID implementation in a further PR?

**Comment by mhelmetag** [comment]
I update the icon with the one supplied. Should be in the "After" screenshot now.

**Comment by derrickmehaffy** [comment]
Yeah there is a lot that would need to be done to support UUID properly

**Comment by Aurelsicoko** [comment]
It seems complicated to add the type and the icon in the Content-Type Builder if the type and feature are not there...

**Comment by mhelmetag** [comment]
Users can still use the UUID feature (regardless of it being fully implemented) so I still think it's important to have correct icons and strings.

**Comment by derrickmehaffy** [comment]
I agree @mhelmetag the main issue is it not being propo implemented on MySQL although I think it works on PostgreSQL

**Comment by lauriejim** [comment]
I agree with that.
The topic of this PR is not to add the support of UUID on the Content-Type Builder.
It's to don't break the Content Manager UI when you manually add UUID (and that is something that is possible and explained into the documentation)

**Comment by mhelmetag** [comment]
Woo! Thanks!

**Pull request merged**
