### PR TITLE
Features/dark mode

### PR DESCRIPTION
**Pull request by vincentbpro**
### What does it do?

- Adds a setting in the user profile page that allows users to apply the theme they want
- The theme defaults to the browser theme (light/dark)

### CODE REVIEW

**Comment by sargreal** [comment]
I found an issue with custom themes (and also the dark theme here) and the WYSIWGY editor:

The WYSIWGY editor does not use the color from the theme but "white", this is defined in the following code:

https://github.com/strapi/strapi/blob/634bbc15205bd668bada30b8cba71e344c72b73f/packages/core/admin/admin/src/content-manager/components/Wysiwyg/EditorStylesContainer.js#L161

Similar to the changes in https://github.com/strapi/design-system/commit/44b415045c8d0474ba3973bbaa56a46f9283dffb I would suggest to set the background to inherit there right?

**Comment by vincentbpro** [comment]
Good catch @sargreal thanks!

**Review by MarionLemaire — APPROVED** [review]
Tested on Getstarted using 1 SuperAdmin user and 5 invited users having different roles : 
- functional features are OK, nothing broken
- every role has access to the switch and the right to pick up theme
- choice of theme is independent between users on the same project
- choice of theme is saved after logout
- global useability is OK
>> OK with reservations on UI issues to fix for next version (though nothing blocking or strongly impacting the user experience) + DM on in-app market place still not tested on functional / design QA

**Comment by alexandrebodin** [comment]
Merging dark mode in `releases/4.2.0`

**Pull request merged**
