### PR TITLE
fix: The list view settings popover is not scrollable

### LINKED ISSUE #21572: The list view settings popover is not scrollable
### Steps to reproduce
- Go to the list view of a content-type with many different fields
- Click on the settings of the list view
- See the long popover and the inability to scroll

### Expected behavior

You should be able to scroll

### Screenshots

Image

### PR DESCRIPTION
**Pull request by dkochetkov**
I limited the maximum height and added the ability to scroll content inside the block.

### What does it do?

Describe the technical changes you did.
Added <code>maxHeight={'240px'}</code> and <code>overflow={'scroll'}</code> properties for parent <code>Flex</code> component in <code>ViewSettingsMenu</code>.

### Why is it needed?

Scrolling of the content becomes possible when the block is filled with a large amount of content.

### How to test it?

- Go to the list view of a content-type with many different fields
- Click on the settings of the list view
- See the long popover and the ability to scroll

### Related issue(s)/PR(s)

Closes #21572

### CODE REVIEW

**Comment by hanpaine** [comment]
Hey @dkochetkov thanks for another contribution! We'll take a look soon 🙏 happy Hacktoberfest 🎃

**Comment by PrathameshGujar08** [comment]
I was thinking of working on the issue. Is it already solved? If so please respond here so.

**Comment by dkochetkov** [comment]
> I was thinking of working on the issue. Is it already solved? If so please respond here so.

Yes, it is solved the same way as in version 4: the height of the container is limited and scrolling inside it is added.

If there is a more elegant solution, it will be fine.

**Review by simotae14 — APPROVED** [review]
Thanks a lot @dkochetkov for the contribution,
The code looks ok and I tested it and it works (also is the same height as in v4), well done 💪🏽 
I am gonna approve your PR, Congrats 🏅

**Pull request merged**
