### PR TITLE
chore: fix strip-hash

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

fix the regexp for stripping the hash on the size comparison action

### Why is it needed?

the matching is wrong so it's considering every single file to be removed or added, instead of comparing accurately

### How to test it?

it's CI, I'm not sure if it will affect this PR or only work after it's merged

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Review by alexandrebodin — APPROVED** [review]
I think there was a discussion to remove it entirely. but nice if it's at least fixed.

**Comment by innerdvations** [comment]
Yeah, I thought this might allow us to keep it if anyone finds it useful, but removing it altogether would work too. As long as we stop getting giant lists of a hundred files every PR 😆

**Review by remidej — APPROVED** [review]
I'm all for keeping it if it stops spamming PRs 😁

**Comment by innerdvations** [comment]
Ok, let's hope my regexp is right, won't know for sure until the next front-end PR 😆

**Pull request merged**
