### PR TITLE
fix: v5 migration with wrong enum values

### LINKED ISSUE #21583: Strapi 5 migration, unable to create index because it already exists
### Required System information

- Node.js version: v20
- NPM version: latest that comes with 20
- Strapi version: 5.0.2
- Database: Strapi Cloud
- Operating system: Strapi Cloud
- Is your project Javascript or Typescript: JS

### Describe the bug

When migrating the application from Strapi 4 to Strapi 5 and deploying on cloud, in some cases the following error will happen causing the migration to fail and automatic rollback to last known good config also fails (requires restoring a database backup)

```
2024-10-03T15:58:29.932875243Z [2024-10-03 15:58:29.929] [34mdebug[39m: ⛔️ Server wasn't able to start properly.
2024-10-03T15:58:29.941316973Z [2024-10-03 15:58:29.937] [31merror[39m: create index "admin_permissions_role_links_fk" on "public"."admin_permissions_role_links" ("permission_id") - relation "admin_permissions_role_links_fk" already exists
2024-10-03T15:58:29.941346537Z error: create index "admin_permissions_role_links_fk" on "public"."admin_permissions_role_links" ("permission_id") - relation "admin_permissions_role_links_fk" already exists
2024-10-03T15:58:29.941352103Z     at Parser.parseErrorMessage (/home/app/node_modules/pg-protocol/dist/parser.js:283:98)
2024-10-03T15:58:29.941356317Z     at Parser.handlePacket (/home/app/node_modules/pg-protocol/dist/parser.js:122:29)
2024-10-03T15:58:29.941361474Z     at Parser.parse (/home/app/node_modules/pg-protocol/dist/parser.js:35:38)
2024-10-03T15:58:29.941365559Z     at TLSSocket.<anonymous> (/home/app/node_modules/pg-protocol/dist/index.js:11:42)
2024-10-03T15:58:29.941370996Z     at TLSSocket.emit (node:events:519:28)
2024-10-03T15:58:29.941375536Z     at TLSSocket.emit (node:domain:488:12)
2024-10-03T15:58:29.941380295Z     at addChunk (node:internal/streams/readable:559:12)
2024-10-03T15:58:29.941385786Z     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
2024-10-03T15:58:29.941390026Z     at Readable.push (node:internal/streams/readable:390:5)
2024-10-03T15:58:29.941394158Z     at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)
```

### Steps to reproduce the behavior

Unknown steps to reproduce at this time

### Expected behavior

Migration shouldn't fail and schema inspection shouldn't try to create indexes that already exist or fail gracefully

### Screenshots

N/A

### Code snippets

N/A

### Additional context

Related TID: 8413 and 8397

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?

As described in https://github.com/strapi/strapi/issues/21583#issuecomment-2393242982 , trying to migrate from v4 with invalid enum values (e.g. an enum that allows red,green, blue but the stored value is "yellow") resulted in the `discard-draft` migration crashing, and so preventing the migration to happen.

example error:
```
MigrationError: Migration core::5.0.0-discard-drafts (up) failed: Original error: theme must be one of the following values: dark, light, yellow,    
       at /Users/marcroig/Documents/strapi/strapi/node_modules/umzug/lib/umzug.js:169:27    
```

We concluded that any badly formated data in v4 should be also preserved in v5 during the migration (as long as app works and data is modifiable). So the `discard-draft` migration will run without any data validation (enums, max, min, required, ...)

### Why is it needed?
So users can migrate even if there is "invalid" data.

### How to test it?

- Start with Strapi 4
- create a content type with d&p disabled
- add  an enum field
- add invalid data for that enum field in the database, for example your enum allows red, green, and blue, but you have a value in your database of yellow
- migrate to Strapi 5
- migration should not fail

### Related issue(s)/PR(s)
 
fixes #21583

### CODE REVIEW

**Comment by Marc-Roig** [comment]
Experimental release: `0.0.0-experimental.fd55b75e545ef2b5c16b5f49a04e0db294663d8d`

**Review by Convly — APPROVED** [review]
Fix the issue on my side using the reproduction steps from https://github.com/strapi/strapi/issues/21583#issuecomment-2393242982

**Comment by MarionLemaire** [comment]
Test report using the experimental : 

Migration from 4.25.13 to V5 experimental worked well.
My data were saved :

- Dog without i18n and without D&P
- Owner with i18n and with D&P
- Relations between Dog & Owner in Draft status 

BUT :
Relation between Dog & Owner has disappeared when my Owner was Published

Already discussed with @Marc-Roig who is already working on this separately :)

**Comment by innerdvations** [comment]
> Test report using the experimental :
> 
> Migration from 4.25.13 to V5 experimental worked well. My data were saved :
> 
> * Dog without i18n and without D&P
> * Owner with i18n and with D&P
> * Relations between Dog & Owner in Draft status
> 
> BUT : Relation between Dog & Owner has disappeared when my Owner was Published
> 
> Already discussed with @Marc-Roig who is already working on this separately :)

So that is a separate issue that already exists in v5?

**Review by innerdvations — APPROVED** [review]
Works for me!

**Comment by Marc-Roig** [comment]
> > Test report using the experimental :
> > Migration from 4.25.13 to V5 experimental worked well. My data were saved :
> > 
> > * Dog without i18n and without D&P
> > * Owner with i18n and with D&P
> > * Relations between Dog & Owner in Draft status
> > 
> > BUT : Relation between Dog & Owner has disappeared when my Owner was Published
> > Already discussed with @Marc-Roig who is already working on this separately :)
> 
> So that is a separate issue that already exists in v5?

Yes! we are going to create an issue

**Pull request merged**
