### PR TITLE
Update admin UI: Inputs/index.js

### PR DESCRIPTION
**Pull request by secretlifeof**
#### Description of what you did:
Corrected formatting on relational Field. There was a double formatting className="col-6" on the parent and this child. Removed className="col-6" on this.
I have never done a pull request to any kind of open-source project. Please tell me if I did not do this correctly.

Screenshot 2020-02-18 at 13 50 57
Screenshot 2020-02-18 at 13 51 10

There is also a Bug with a z-index, but I don´t know how to correct this. Adding "zIndex: 1" or "zIndex: 1000" to the SelectWrapper component fixes some formatting but screws up others.

Screenshot 2020-02-18 at 13 53 19

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [x] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by HichamELBSI** [comment]
Hello @secretlifeof, thank you for this PR. You just need to sign-off your commit to check the DCO.

**Comment by secretlifeof** [comment]
@HichamELBSI I was a bit confused how to do it. So now there are many commits. Even if I did the sign-off on the last commit, there is still an error saying sign-off is missing. What can I do?

**Comment by lauriejim** [comment]
Hi @secretlifeof did you check this https://github.com/strapi/strapi/pull/5261/checks?check_run_id=455031486 ?

**Comment by secretlifeof** [comment]
Hi @lauriejim 
Yes, but only with the latest commit. The next time I will do a PR I will know how to contribute correctly. Is there a way to fix this, or should we close this and open another PR?

**Comment by soupette** [comment]
@secretlifeof thanks for taking the time to contribute however, I am closing your PR as it as already been fixed.

**Pull request closed without merging**
