### PR TITLE
[audit logs] Add JSON component to modal

### PR DESCRIPTION
**Pull request by markkaylor**
### What does it do?

Adds the new JSON component from the design system in the audit logs modal

### Why is it needed?

To visualize the payload

### How to test it?

- Go to the audit logs page and open the modal, you should see the JSON component, make sure it matches the designs

### CODE REVIEW

**Review by remidej — COMMENTED** [review]
The code changes look good, I'll come back to test it a bit later (my local git is a mess right now 😅)

Also, do you think it's okay to merge it before we release the json component (even in alpha)?  it means the feature branch will crash for people who don't have the yarn link, but I don't know if it's problematic

**Comment by markkaylor** [comment]
I don't think we should merge it until we have some sort of DS release that contains the component, that's why I added the don't merge flag.

**Comment by markkaylor** [comment]
@remidej I added the experimental release to this PR so it should be easier to test now and I think we could merge this if approved and potentially use it for the beta. wdyt?

**Review by remidej — APPROVED** [review]
image

**Pull request merged**
