### PR TITLE
[ADMIN] Misleading back link in header on Content Manager & Content-Type Builder page

### PR DESCRIPTION
**Pull request by nitinmadelyn**
### What does it do?

- I've added a condition to show back link only if there's state passed to useLocation object on Content-Type Builder page.
- Passed state to useLocation object when someone click on `Edit the model` button from Collection Type edit page(right panel)
- On Content Manager page when someone click on the Content Type from the List. I've set the location info to localStorage named `back-link`. Which will be use to navigate back to List page with exact search & paging info.

### Why is it needed?

- When we initially navigate to Content Manager & Content-Type Builder page then Back link is always there and clicking on it does nothing. (unnecessary displayed).
- Also when we navigate to different Collection Type from the nav list then it also doesn't preserved the history. It simply going to the first Collection Type from the list.
- In Content Manager it doesn't keep the history of the search & paging info when we press Back link from the Collection Type edit page.

**Previous Behaviour:**

https://github.com/strapi/strapi/assets/40918526/329900d9-3fa1-442b-827e-976457a2c7a7

**After Update:**

https://github.com/strapi/strapi/assets/40918526/56b6a370-7fb0-4086-bd12-a46fc3bc2d96

### How to test it?

- Login to admin and follow the steps as per the last video above. Also you can play around Back link from both Content Manager & Content-Type Builder page.

### Related issue(s)/PR(s)

No existing issue for this PR. This PR is in progress, If you accept this change then I will update the tests & documentations if needed.

### CODE REVIEW

**Comment by nitinmadelyn** [comment]
@Boegie19 @Convly @joshuaellis Can this be reviewed? 
Updated test cases too.

**Comment by joshuaellis** [comment]
> @Boegie19 @Convly @joshuaellis Can someone please review this? Updated tests also.

We have an internal review process, it'll be reviewed within due time, i imagine the UI changes will need to be validated by product as well.

**Comment by nitinmadelyn** [comment]
> > @Boegie19 @Convly @joshuaellis Can someone please review this? Updated tests also.
> 
> We have an internal review process, it'll be reviewed within due time, i imagine the UI changes will need to be validated by product as well.

@joshuaellis thank you for the consideration of this PR. And sorry I wasn't fully aware of the internal review process. I will keep this in mind.

**Comment by nitinmadelyn** [comment]
This fix also work with filters, see in demo below:

https://github.com/strapi/strapi/assets/40918526/6cf88f0d-2596-4910-a7b8-7fc1572722ff

**Comment by joshuaellis** [comment]
Sorry for the late reply and radio silence we've been busy across many topics. I think realistically we need to analyse our approach on this and create it easily reproducible across the app and consistent so we're going to take this in house instead. I do appreciate the work you've done on this – thank you 😄

**Pull request closed without merging**
