### PR TITLE
Fix context issue in custom GraphQL query and mutation

### LINKED ISSUE #5531: Cannot access ctx.state.user in custom GraphQL resolver
**Describe the bug**
I cannot access `ctx.state.user` in custom GraphQL resolver. It happened after I migrate from `3.0.0-beta.18.7` to `3.0.0-beta.19.3` in my project.
I've also tried it in `examples/getstarted` of cloned repository, it's same.

**Steps to reproduce the behavior**
I will try to explain with https://github.com/strapi/strapi/tree/master/examples/getstarted project.
1. Create `address/config/schema.graphql`
```js
module.exports = {
  definition: `
  `,
  query: `
    testing: String
  `,
  mutation: `
  `,
  resolver: {
    Query: {
      testing: {
        resolverOf: 'application::address.address.find',
        resolver: (obj, options, { context }) => {
          console.log('context.state.user', context.state.user);

          return 'testing';
        },
      },
    },
  },
};
```
2. Create an user and get token with login mutation.
```js
mutation Login {
  login(input: {identifier: "test", password: "test1234"}) {
    jwt
    user {
      id
      username
      email
      confirmed
      blocked
    }
  }
}
```
3. Give the user `address.find` permission and run the test query.
```js
query testing {
  testing
}
```
4. Check the terminal.
```js
context.state.user undefined
```

**Expected behavior**
I should have had access to the `ctx.state.user` object.

**System**
- Node.js version:  node v12.14.1
- NPM version: 6.13.4
- YARN version: 1.12.1
- Strapi version: 3.0.0-beta.19.3 
- Database: SQLite
- Operating system: MacOS

**Additional context**
It's `context.state` object I printed out in resolver.
```js
context.state {
  session: Session {
    _sessCtx: ContextSession {
      ctx: [Object],
      app: [Object],
      opts: [Object],
      store: undefined,
      session: [Circular]
    },
    _ctx: {
      request: [Object],
      response: [Object],
      app: [Object],
      originalUrl: '/graphql',
      req: '<original node req>',
      res: '<original node res>',
      socket: '<original node socket>'
    },
    isNew: true
  },
  i18n: I18n {
    devMode: true,
    directory: '/Users/chisus/Develop/strapi-test/strapi/examples/getstarted/config/locales',
    locales: {
      cs_cz: [Object],
      en_us: [Object],
      es_es: [Object],
      fr_fr: [Object],
      it_it: [Object],
      ja_jp: [Object],
      ru_ru: [Object],
      tr_tr: [Object],
      vi_vn: [Object]
    },
    defaultLocale: 'en_us',
    modes: [ 'query', 'subdomain', 'cookie', 'header', 'url', 'tld' ],
    cookieName: 'locale',
    extension: '.json',
    locale: 'en_us',
    whitelist: [ 'Query', 'Subdomain', 'Cookie', 'Header', 'Url', 'TLD' ],
    request: { method: 'POST', url: '/graphql', header: [Object] }
  },
  __: [Function: bound __],
  __n: [Function: bound __n],
  getLocale: [Function: bound getLocale],
  isPreferredLocale: [Function: bound isPreferredLocale]
}
```

### PR DESCRIPTION
**Pull request by iicdii**
#### Description of what you did:
Fix #5531 issue. Make `policiesMiddleware` works in custom resolvers too.

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi, Can you please fix the DCO check.

**Comment by alexandrebodin** [comment]
@iicdii The tests are breaking with your changes.

**Comment by iicdii** [comment]
@alexandrebodin I'll check the code.

**Comment by derrickmehaffy** [comment]
Tests look to be passing now good catch @iicdii

**Comment by iicdii** [comment]
@alexandrebodin 
This is the clue I've found why test fails.
```js
// packages/strapi-plugin-users-permissions/test/graphql.test.e2e.js`

test('createUser is authorized for admins', async () => {
  const res = await authReq({
    url: '/graphql',
    method: 'POST',
    body: {
      query: /* GraphQL */ `
        mutation {
          createUser(
            input: {
              data: {
                username: "test"
                email: "test@strapi.io"
                password: "test"
              }
            }
          ) {
            user {
              id
              username
            }
          }
        }
      `,
    },
  });

  expect(res.statusCode).toBe(201);
  expect(res.body).toMatchObject({
    data: {
      createUser: {
        user: {
          id: expect.anything(),
          username: 'test',
        },
      },
    },
  });

  data.user = res.body.data.createUser.user;
});
```

`res.statusCode` is `200` when I `graphqlContext.context = ctx` so test fails.
Otherwise it's `201`  when I `graphqlContext.context.state = ctx.state` so test passes.
It seems to need more digging the code, honestly I don't get the concept difference between `graphqlContext` and `ctx`.

**Comment by alexandrebodin** [comment]
ctx is the context of the koa app and graphqlContext is the context inside of graphql. 

When we receive a graphql query it calls koa middleware hence the need to passe the ctx to them. We just clone it to avoid pbl when running multiple queries at once.

if you look at the createUser mutation you will see it calls a controller with the context and inside of this you have a ctx.created() call. this is supposed to do ctx.status = 201 and ctx.body = data

But this is not copied back to the koa context. Which in my opinion isn't a big deal. 

I think we should set graphqlContext.context =. ctx and just change the test to check for a 200 status. In graphql other status don't really make sense anyway.

**Comment by iicdii** [comment]
Thank you for detailed explanation. I made PR again.

**Comment by alexandrebodin** [comment]
Thanks you for this PR 💯

**Pull request merged**
