### PR TITLE
Move from deprecated packages to graphql-scalars to handle scalar types

### PR DESCRIPTION
**Pull request by Convly**
### What does it do?

Move from deprecated packages (graphql-iso-date, graphql-long) to graphql-scalars to handle scalar types

### Why is it needed?

Remove dependencies to unmaintained packages

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/pull/13769

### CODE REVIEW

**Comment by fdel-car** [comment]
So glad to see that, thanks JS, no more invalid peer dependencies warning as well 👍

**Review by alexandrebodin — APPROVED** [review]
LGTM. Just need a yarn lock update before merging :)

**Comment by Convly** [comment]
@alexandrebodin it should already bé updated 🤔

**Comment by derrickmehaffy** [comment]
That's a lot of cleaning of the yarn.lock lol

**Review by alexandrebodin — DISMISSED** [review]
LGTM :)

**Review by alexandrebodin — APPROVED** [review]

**Comment by exreplay** [comment]
I upgraded to 4.3.3 and getting the following error message `Missing type JSONObject, did you forget to import a type to the root query?`.

I tracked it down to this PR and found that a scalar for `JSONObject` is missing. When i add the missing scalar, everything works again. This is how my file looks now.

https://github.com/strapi/strapi/blob/master/packages/plugins/graphql/server/services/internals/scalars/index.js

```js
'use strict';

const { GraphQLDateTime, GraphQLLong, GraphQLJSON, GraphQLJSONObject } = require('graphql-scalars');
const { GraphQLUpload } = require('graphql-upload');
const { asNexusMethod } = require('nexus');

const TimeScalar = require('./time');
const GraphQLDate = require('./date');

module.exports = () => ({
  JSON: asNexusMethod(GraphQLJSON, 'json'),
  JSONObject: asNexusMethod(GraphQLJSONObject, 'json'),
  DateTime: asNexusMethod(GraphQLDateTime, 'dateTime'),
  Time: asNexusMethod(TimeScalar, 'time'),
  Date: asNexusMethod(GraphQLDate, 'date'),
  Long: asNexusMethod(GraphQLLong, 'long'),
  Upload: asNexusMethod(GraphQLUpload, 'upload'),
});

```

**Comment by alexandrebodin** [comment]
@exreplay Are you using custom Graphql resovlers ?

**Comment by exreplay** [comment]
@alexandrebodin I am indeed having a custom graphql resolver, which i was not aware of anymore, where i used `JSONObject` instead of `JSON`. Changed it and now it works. Thank you for your quick response!

**Pull request merged**
