### PR TITLE
Optimize database foreign keys references - PostgreSQL

### PR DESCRIPTION
**Pull request by meherchandan**
…gn key references

### What does it do?

Describe the technical changes you did.
Optimize the "getForeignKeys" when synchronizing with the database for postgres db.
### Why is it needed?

Describe the issue you are solving.
On existing database, knex timeout error is coming when adding a new component. The PR is simplifying the complex(costly) database queries to remove the timeout error.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request
https://github.com/strapi/strapi/issues/11860

### CODE REVIEW

**Comment by meherchandan** [comment]
Fix for mysql, the fix is already added on https://github.com/strapi/strapi/pull/12843. For sqlite, I think the issue doesn't exist as the query already looks optimized `FOREIGN_KEY_LIST: 'pragma foreign_key_list(??)',`.

**Review by derrickmehaffy — APPROVED** [review]
Much like the MySQL PR it looks good to me but we do need @alexandrebodin to take a look here. Automated tests already passed fine so good there.

**Review by alexandrebodin — APPROVED** [review]
LGTM. THank you for those contributions 👍

**Review by shrmaky — COMMENTED** [review]
Great work @meherchandan

**Pull request merged**
