### PR TITLE
Make select autocomplete case insensitive

### PR DESCRIPTION
**Pull request by WalkingPizza**
### What does it do?

Solves #13888.

### Why is it needed?
The select component's autocomplete feature is currently case sensitive, meaning some results may not show up in the list if the casing does not match exactly.

### How to test it?

Create some entries with titles in different casing (eg. title case vs lowercase) and try scrolling to the bottom of the list.
Notice how the component also shows entries with titles in different casing, whereas the component in the current Strapi release doesn't.

### Related issue(s)/PR(s)

#13888.

### CODE REVIEW

**Comment by Sija** [comment]
Anything holds this back from merging?

**Comment by chrift** [comment]
@alexandrebodin @WalkingPizza @gu-stav Hey guys do you know if we are able to get a date on when this will be merged/released?

**Comment by gu-stav** [comment]
@petersg83 Do you think we can merge this until the refactored relations are released (the refactoring will include this fix)?

**Comment by petersg83** [comment]
@gu-stav Yes totally :)

**Review by petersg83 — APPROVED** [review]
LGTM :)

**Pull request merged**
