### PR TITLE
Add Italian translation

### PR DESCRIPTION
**Pull request by alewin**
My PR is a:
💅 Enhancement 

Main update on the:
Admin
Plugin

Italian language:

- [x] content-manager
- [x] content-type-builder
- [x] admin
- [x] email
- [x] settings-manager
- [x] users-permissions
- [x] upload

### CODE REVIEW

**Comment by lauriejim** [comment]
Yeah it' so nice 🇮🇹 !! Let me time to review your PR  ;)

**Comment by lauriejim** [comment]
@alewin sometimes you have `it.json` folder with `it.json` file inside `translations/it.json/it.json`. Can you fix translation file path please `translations/it.json`.

Bad path: 
- `packages/strapi-plugin-content-manager/admin/src/translations/it.json/it.json`
- ` packages/strapi-plugin-content-type-builder/admin/src/translations/it.json/it.json`
- `packages/strapi-plugin-settings-manager/admin/src/translations/it.json/it.json`
- `packages/strapi-plugin-upload/admin/src/translations/it.json/it.json`

**Comment by alewin** [comment]
@lauriejim oh sorry.. tomorrow i'll fix it! 👍

**Comment by lauriejim** [comment]
@alewin Top !

**Comment by lauriejim** [comment]
@alewin I have notice `users-permissions` plugin is missing.
If you have time to translate it we will appreciate it ;D

**Comment by alewin** [comment]
Sure, tomorrow I'll do it! 👍

**Comment by lauriejim** [comment]
Thank you @alewin  !

**Pull request merged**
