### PR TITLE
Fix problems related to filtering

### LINKED ISSUE #2396: GraphQL issue with Bookshelf, operator undefined is not permitted
**Informations**
- **Node.js version**: v10
- **npm version**: v6
- **Strapi version**: v15
- **Database**: MariaDB 10.2
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**

When trying to query nested data in GraphQL that may contain some NULL data, the following error is thrown:

```
{
  "errors": [
    {
      "message": "The operator \"undefined\" is not permitted",
      "locations": [
        {
          "line": 19,
          "column": 5
        }
      ],
      "path": [
        "gssites",
        0,
        "activeGroups"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: The operator \"undefined\" is not permitted",
            "    at Formatter.operator (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/formatter.js:187:13)",
            "    at QueryCompiler_MySQL.whereBasic (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/query/compiler.js:554:100)",
            "    at QueryCompiler_MySQL.where (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/query/compiler.js:350:32)",
            "    at /nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/query/compiler.js:127:31",
            "    at Array.map (<anonymous>)",
            "    at QueryCompiler_MySQL.select (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/query/compiler.js:126:33)",
            "    at QueryCompiler_MySQL.toSQL (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/query/compiler.js:74:27)",
            "    at Builder.toSQL (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/query/builder.js:70:44)",
            "    at /nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/runner.js:39:32",
            "    at runCallback (timers.js:705:18)",
            "    at tryOnImmediate (timers.js:676:5)",
            "From previous event:",
            "    at Runner.run (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/runner.js:34:31)",
            "    at Builder.Target.then (/nixstorage/Github/capi/CAPIv2-Strapi/node_modules/knex/lib/interface.js:20:43)"
          ]
        }
      }
    },
```

**Steps to reproduce the problem**

You can see my example query using my Development Strapi Server:

Query: https://github.com/canonn-science/CAPIv2-Strapi/blob/development/seed_files/GraphQL-Examples.MD

Development Server: https://api.canonn.tech:2083/graphql

There are cases within my data where a `GS Site` may not have the following relational data aka NULL data:

`activeGroups` or `activeObelisks` removing those entries from my query results in a positive response with no major errors, however adding in those nested query options will result in the error above.

You are also welcome to clone my project and run it locally, to seed your MySQL database you can use the following seed file: https://github.com/canonn-science/CAPIv2-Strapi/blob/development/seed_files/SQL/example-development-20181128.sql

Default user created is:
```
user: canonntest
pass: canonntest
```

**What is the expected behavior?**

GraphQL should provide the NULL response on missing data.

**Suggested solutions**

There seems to have been a change between 14.5 and 15 that caused this error, it seems related to an improper knex query that is being passed for relational data that doesn't exist.

@kamalbennani Not sure if you were working on the query part of the GraphQL plugin?

### LINKED ISSUE #2397: The GraphQL sort desc doesn't work
**Informations**
- **Node.js version**: v10.0.0
- **npm version**: v6.0.0
- **Strapi version**: v3.0.0-alpha.15
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

The GraphQL sort desc doesn't work

**Steps to reproduce the problem**

After upgrading from `v3.0.0-alpha.14.5` to `v3.0.0-alpha.15`, this query doesn't work:

```javascript
{
  seasons {
    slug
    editions {
      slug
      matchdays(sort: "date:desc") {
        slug
        date
      }
    }
  }
}
```

Error:

```
"message": "Unkown order value: \"desc\", available values are: ASC, DESC",
```

And after update to:

```javascript
{
  seasons {
    slug
    editions {
      slug
      matchdays(sort: "date:DESC") {
        slug
        date
      }
    }
  }
}
```

The error is:

```
"message": "Unkown field: \"date\"",
```

But if I remove the `(sort: "date:DESC")`, it works:

```javascript
{
  seasons {
    slug
    editions {
      slug
      matchdays {
        slug
        date
      }
    }
  }
}
```

**What is the expected behavior?**

Working :)

### LINKED ISSUE #2408: GraphQL - Cannot read property 'isMongoId' of undefined
**Informations**
- **Node.js version**: v10.13.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.15
- **Database**: Mongo
- **Operating system**: OSX
**What is the current behavior?**
in a Many to Many relation GraphQl on latest strapi throws:
> "Cannot read property 'isMongoId' of undefined"
> "at valueToId (/Users/admin/Downloads/kon-strapi/node_modules/strapi-hook-mongoose/lib/utils/index.js:60:19)"
> 

**Steps to reproduce the problem**
Create two Collections and a many to many field, add a couple a values and query with graphql:
```graphql
{
  categories {
    name
    Product{
      Name
    }
  }
}
```

**What is the expected behavior?**
To return the results.
In 14.5 it was working fine but now it is not.

**Suggested solutions**
Couldn't find any. Seems relevant to issue [#1683](https://github.com/strapi/strapi/issues/1683#issue-346752826)

### LINKED ISSUE #2413: _start and _limit filter not working
**Informations**
- **Node.js version**: v10
- **NPM version**: 6.4.1
- **Strapi version**: v3.0.0-alpha.15
- **Database**: MongoDB 4.0.4
- **Operating system**:  macOS Mojave

**What is the current behavior?**

`GET /blogs` => i have 10 items returned
`GET /blogs?_start=3&_limit=3` => empty result

**Steps to reproduce the problem**

Create a simple standard API, create many instances

**What is the expected behavior?**

Pagination should just work, like previous alpha

**Suggested solutions**

Search for the bug and fix it!

### LINKED ISSUE #2417: Can't sort on createdAt field
**Informations**
- **Node.js version**:  v11.2.0
- **NPM version**:  6.4.1
- **Strapi version**:3.0.0-alpha.14.5
- **Database**: mongo
- **Operating system**: ubuntu

**What is the current behavior?**
I get >ERROR Error: "GraphQL error: Unkown field: "createdAt""

I'm using Angular 7 for front-end

**Steps to reproduce the problem**
dependencies for graphql queries, that I'm using in angular:
    apollo-angular
    graphql-tag

my query:

> 
```
{
        reports( sort: "createdAt:DESC", limit: 20, start: ${page * 20}) {
          _id
          title
          short
          image{
            url
          }
          creator {
            username
          }
          createdAt
          categories{
            name
          }
        }
      }
```

I'm using strapi in production. 

**What is the expected behavior?**
Getting data object

**Suggested solutions**
?

### LINKED ISSUE #2420: Images attribute duplicate entries in response
**Informations**
- **Node.js version**: v10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.15
- **Database**: MongoDB 
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**
I am receiving duplicate entries for each item when queried via GraphQL

**Steps to reproduce the problem**
Created new content type:
screenshot from 2018-12-02 14-48-03

Made a GraphQL request as follows:
screenshot from 2018-12-02 14-46-30

Duplicate records in response, despite MongoDB showing 4 distinct records:
screenshot from 2018-12-02 14-47-21

**What is the expected behavior?**
4 items in response. Received 16. Each Carouselslide is returned 4 times in the response.

**Suggested solutions**
I am not sure why this is happening. I apologise if I am doing something wrong. :)

### PR DESCRIPTION
**Pull request by kamalbennani**
My PR is a:
- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #2397 fix #2396 fix #2413 fix #2408 fix #2413 fix #2417 fix #2420
- [x] 💅 Enhancement
- [ ] 🚀 New feature

Main update on the:
- [ ] Admin
- [ ] Documentation
- [x] Framework
- [x] Plugin

The main purpose of this PR is to fix all the problems related to nested filtering introduced in the v3.0.0-alpha.15.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@lauriejim @kamalbennani Me and my team both tested this fix and it is working as a charm. No more null errors.

**Comment by kamalbennani** [comment]
I'll rework all the commits once I finish dealing with all the problems

**Comment by lauriejim** [comment]
I can't use the content manager

```
0|strapi start  | ReferenceError: mergeStages is not defined
0|strapi start  |     at Function.find (/home/ubuntu/strapi/packages/strapi-plugin-content-manager/config/queries/mongoose.js:10:29)
```

**Comment by kamalbennani** [comment]
@lauriejim Could you give it a try again :pray:

**Comment by lauriejim** [comment]
This issue still happen https://github.com/strapi/strapi/issues/2408

**Comment by kamalbennani** [comment]
@lauriejim I've just generated a Mongoose project and I didn't faced this problem, could you give me steps to reproduce it

**Comment by kamalbennani** [comment]
@lauriejim what about the other issues? are they fixed or you're not able to start a project?

**Comment by lauriejim** [comment]
@kamalbennani Are you on Slack ? Will be easier to talk.

**Comment by lauriejim** [comment]
But others issues you link looks good.

**Comment by kamalbennani** [comment]
Emm weird, I'll take a look into it soon

**Comment by lauriejim** [comment]
When I populate with Mongoose on GraphQL

```
{articles {
  title
  tags {
    name
  }
}}
```

I get all tags available in the response and not only tags linked to my article

**Comment by lauriejim** [comment]
Same request with Bookshelf trigger an error.

**Comment by derrickmehaffy** [comment]
@kamalbennani Just noticed on using this PR on my test server that the adminUI pages don't seem to be working properly. I'll pm you on slack for login details so you can take a look

**Comment by derrickmehaffy** [comment]
for clarification on my previous comment, the adminUI doesn't seem to be taking into account the page number and will only show the first 10 results (changing the amount per page doesn't change anything, for instance if I select 100, it will only show the first 100 no matter the page number selected)

I spoke with @kamalbennani about this via slack and he is taking a look.

**Comment by Aurelsicoko** [comment]
@lauriejim Can this PR be closed since we revert the changes made by @kamalbennani?

**Comment by mamartins** [comment]
on alpha.16 using graphQl I'm facing the current issues:
- no more than 100 items returned, even when limit is set to +100 
start and limit return nonsense results. For eg, for the same +100 items collection start 40 returns 10 items, 50 returns 3 items (collection has 103 items)

**Comment by derrickmehaffy** [comment]
@mamartins That's due to the security limit, see this PR (It's in release v16): https://github.com/strapi/strapi/pull/2400

**Comment by mamartins** [comment]
> @mamartins That's due to the security limit, see this PR (It's in release v16): #2400

Didn't found that on documentation. I found the limit under ` plugins/graphql/services/Query.js ` 
Also, start and limit are urgent bugs.

**Pull request closed without merging**
