### PR TITLE
Pluralize routes

### LINKED ISSUE #504: REST routes with plural resource names
Node.js version: 8.9.0
npm version: 5.5.1
Strapi version: 3.0.0-alpha.8.3
Operating system: Windows 7 (Enterprise)

Hi, if my understanding of REST is correct (and based on how other frameworks have implemented it eg. Laravel, Rails etc.)
Shouldn't all REST methods operate on a plural form of the resource? For example, you'd GET all posts via `/posts` and not `/post` and DELETE a specific post via `/posts/:id` etc.?

image

Thanks.

### PR DESCRIPTION
**Pull request by pierreburgy**
My PR is a:

💅 Enhancement

Main update on the:

Documentation
Framework

 - Pluralize routes in generated APIs and plugins.
 - Update documentation accordingly.

Fix #504

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Ooooo boy this is gonna break some stuff :stuck_out_tongue:

**Comment by Aurelsicoko** [comment]
Yes, we need to test everything because maybe there are hardcoded URLs in the dashboard...

**Comment by derrickmehaffy** [comment]
Related issue: https://github.com/strapi/strapi/issues/504

**Comment by lauriejim** [comment]
Working on it - https://github.com/strapi/strapi-sdk-javascript/pull/28

**Pull request merged**
