### PR TITLE
feat: add priority to middlewares

### PR DESCRIPTION
**Pull request by Marc-Roig**
Run doc service middlewares with a priority, the higher the number the earlier it will be executed.

```ts
strapi.documents(ARTICLE_UID).use(
  'findMany',
  (ctx, next) => { },
  // Runs last
  { priority: strapi.documents.middlewares.priority.LAST }
);

strapi.documents(ARTICLE_UID).use(
  'findMany',
  (ctx, next) => {},
  // Runs first
  { priority: strapi.documents.middlewares.priority.FIRST }
);
```

### CODE REVIEW

**Comment by Marc-Roig** [comment]
@innerdvations  I have added a basic implementation of the middleware priority we discussed.
My goal is to make this work, and make it clean later.

What's now called middlewareManager will probably be completely refactored .

**Comment by derrickmehaffy** [comment]
This is interesting 🤔 will normal global and route middlewares be able to have a priority set?

**Comment by Marc-Roig** [comment]
@derrickmehaffy at the moment this will only be possible in document service middlewares. We are still unsure about the naming , we were between middlewares and lifecycles, and middlewares fit more the current api definition.

We are exploring this option for the document service now, if it's something we like and then we can discuss also moving thiss to other places!

**Comment by derrickmehaffy** [comment]
Nice sounds good, just saw the PR name and got excited (I love Koa middlewares 💕)

**Pull request merged**
