### PR TITLE
Front/upgrade buffetjs rc

### PR DESCRIPTION
**Pull request by soupette**
#### Description of what you did:
This PR upgrades the version of Buffet.js

### CODE REVIEW

**Comment by MattieBelt** [comment]
@soupette looks to me like the `main.chunk.js` will double its size. Not sure if this will be addressed any soon, but their has been some discussion regarding the 6mb+ size #7439. (It's fine by me :wink:)

**Comment by soupette** [comment]
@MattieBelt I will take a look at it then!

**Comment by soupette** [comment]
@MattieBelt I have tested with the example app from the monorepo and I have compared the build from this PR and the one from master using the [Webpack Bundle Analyzer plugin](https://www.npmjs.com/package/webpack-bundle-analyzer), I have changed the dev config so it builds in `production` mode and from what I have seen the build is slightly smaller. 

**New Buffet config**:
Screenshot 2020-09-15 at 09 26 15

**Old Buffet config**:
Screenshot 2020-09-15 at 09 26 23


If you could detail me the steps you did to find such difference between the builds I would love to investigate more.

**Comment by soupette** [comment]
I am closing this PR in favour of #7900

**Pull request closed without merging**
