### PR TITLE
fix: Added correct object for plugin loading

### PR DESCRIPTION
**Pull request by roelbeerens**
### What does it do?

Set the correct uid for a plugin. 

### Why is it needed?

It used to output `undefined` in the `strapi` object for all the plugin uid's

### How to test it?

Log the content types for the plugins and verify the uid is correctly set now, instead of something like `plugin::users-permissions.undefined`. It should be `plugin::users-permissions.user`

### Related issue(s)/PR(s)

-

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi, thanks for this PR but was this creating a bug somewhere? I think this code is actually not necessary @petersg83 can you check this ?

**Comment by roelbeerens** [comment]
Hi! Nah, eventually it did not cause a bug. I thought it was related to extending the user-permissions plugin services, but as it turned out, I was just using the wrong setup for that. I did however open the PR, as it seemed the undefined should be something else. As of now it doesn't seem to break something, but maybe it will in the future.

**Comment by petersg83** [comment]
Thank you @roelbeerens! it was not meant to be like that indeed.
It seems the code is not used anymore, it was probably for V3 compatibility while coding V4.
Could you delete the whole `formatContentTypes` function?

**Comment by roelbeerens** [comment]
> Thank you @roelbeerens! it was not meant to be like that indeed.
> 
> It seems the code is not used anymore, it was probably for V3 compatibility while coding V4.
> 
> Could you delete the whole `formatContentTypes` function?

Sure! I'll look into it tomorrow and change up the PR. I'll try to verify if it doesn't break anything. Thanks for looking into it!

**Comment by roelbeerens** [comment]
The `formatContentTypes` function appears to have no function anymore in Strapi. I've deleted it to clean up the loader.

**Review by petersg83 — APPROVED** [review]
LGTM ! Thank you and sorry for the delay :)

**Pull request merged**
