### PR TITLE
WIP: Validate email top level domain

### LINKED ISSUE #6475: Domain name validation
Describe the bug
At the time of registration, email has not been validated correctly `http://localhost:1337/admin/auth/register`

Expected behavior
An email should be valid in all aspect like

- should check valid domain, well-formed and valid mailbox

Screenshots
invalid email1:
s1

invalid email2:
s2

invalid in the dashboard:
dashboard

System

Node.js version:v12.6.0
NPM version:6.9.0
Strapi version: 3.0.1
Database:mongodb
Operating system:Ubuntu 18.04

### PR DESCRIPTION
**Pull request by DJ-Icebear**
Fixes #6475 
#### Description of what you did:

This will add top-level domain validation of email inputs, checking the TLD-part of the email against a local registry of accepted TLDs (as defined by the IANA in: https://data.iana.org/TLD/tlds-alpha-by-domain.txt)
Also some tests.

This is my first contributing PR so let me know if I missed something!

### CODE REVIEW

**Comment by petersg83** [comment]
Hi ! Thanks for your contribution :)
Can you please use a third-party library to list the accepted TLDs? It would be better for maintenance purpose :)
I've seen this one : https://github.com/peerigon/parse-domain Not sure if it is the best one but it looks good

**Review by petersg83 — CHANGES_REQUESTED** [review]
Hi ! Thanks for your contribution :)
Can you please use a third-party library to list the accepted TLDs? It would be better for maintenance purpose :)
I've seen this one : https://github.com/peerigon/parse-domain Not sure if it is the best one but it looks good

**Comment by alexandrebodin** [comment]
Hi @DJ-Icebear any update on this ?

**Comment by alexandrebodin** [comment]
Hi, I'm going to close this PR for inactivity. Feel free to ping me so I reopen it if you eventually can work on it again :)

**Pull request closed without merging**
