### PR TITLE
[v4]: Fix the typo of query key from 'providers' to 'get-providers'

### PR DESCRIPTION
**Pull request by smoothdvd**
### What does it do?

Fix the typo of query key from 'providers' to 'get-providers'

### Why is it needed?

The modified state of the provider does not take effect immediately after submission.

### How to test it?

Go to setting page of users-permissions' providers, edit any of the provider.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/18069

### CODE REVIEW

**Comment by smoothdvd** [comment]
This issue exist in V4 and V5 latest version

**Comment by alexandrebodin** [comment]
Hi, we juste fixed it in v5 but can you udpate your PR against develop so we can fix this in v4 too 🙏

**Comment by smoothdvd** [comment]
OK

**Review by alexandrebodin — APPROVED** [review]

**Comment by alexandrebodin** [comment]
Thank you @smoothdvd !

**Pull request merged**
