### PR TITLE
fix(type): export JSONObject

### PR DESCRIPTION
**Pull request by jhoward1994**
### What does it do?

I was seeing a build error in the CTB, I think exporting this JSON interface fixes it

### CODE REVIEW

**Comment by Marc-Roig** [comment]
@jhoward1994 which error were you seeing?

**Review by innerdvations — APPROVED** [review]
Not sure why it would be needed but also doesn't seem like it would harm anything and would be useful to have available.

**Comment by jhoward1994** [comment]
image

**Review by joshuaellis — APPROVED** [review]
If it builds it works – dangers of diverging branches here.

**Comment by remidej** [comment]
I confirm this is useful, I had the error mentioned :)

**Review by remidej — APPROVED** [review]

**Review by Convly — APPROVED** [review]

**Review by innerdvations — APPROVED** [review]

**Comment by remidej** [comment]
Merging this as it's blocking CI on several content studio PRs

**Pull request merged**
