### PR TITLE
Fix/5439

### LINKED ISSUE #5439: Cannot use 'in' operator to search for 'excludeEmptyString' in url must be a valid URL
**Describe the bug**
After upgrading strapi to 3.0.0-beta.19 / 3.0.0-beta.19.2 i get an error (output shown below). I basically followed this guideline: https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.18-to-beta.19.html

```
[2020-03-05T19:28:54.191Z] debug ⛔️ Server wasn't able to start properly.
[2020-03-05T19:28:54.194Z] error TypeError: Cannot use 'in' operator to search for 'excludeEmptyString' in url must be a valid URL
    at StringSchema.matches (/Users/gjorgekarakabakov/Development/my-project/node_modules/strapi-utils/node_modules/yup/lib/string.js:107:51)
    at Object.<anonymous> (/Users/gjorgekarakabakov/Development/my-project/node_modules/strapi-admin/controllers/Webhooks.js:21:8)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at loadFiles (/Users/gjorgekarakabakov/Development/my-project/node_modules/strapi/lib/load/load-files.js:35:17)
    at async Promise.all (index 0)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gjorgekarakabakov/.npm/_logs/2020-03-05T19_28_54_211Z-debug.log
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-strapi-app
Arguments: my-project --quickstart
Directory: /Users/gjorgekarakabakov/Development
Output:

```

**Steps to reproduce the behavior**
1. Follow migration guideline on https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.18-to-beta.19.html and update all dependencies to 3.0.0-beta.19.2.
2. Remove `/node_modules`, `/build`, `/.cache` and run `yarn install`
3. Run `yarn develop` (tried running `yarn build` just in case, no luck)

**Expected behavior**
Should build and run the server without errors.

**System**
- Node.js version: 13.10.1 (tried with older version as well)
- NPM version: 6.13.7
- Strapi version: 3.0.0-beta.19.2
- Database: SQLite
- Operating system: MacOS / Windows

**Additional context**
This issue wasn't happening on 3.0.0-beta.18.4. Also tried to create new strapi app with `yarn create strapi-app my-app` but the same error ocurred.

### PR DESCRIPTION
**Pull request by MattieBelt**
- [x] yarn test:unit
 - [x] yarn test:front

#### Description of what you did:

Fixes #5439

### CODE REVIEW

**Comment by dngrhm** [comment]
👍 works for me! Thanks for the PR!

**Comment by MattieBelt** [comment]
It does fix the problem for now, but it's not a good fix, because `webhooks.url` may not be an empty string.

I'm not sure on which (empty) string the webhookValidator crashes on startup.

**Comment by MattieBelt** [comment]
https://github.com/jquense/yup/issues/798

**Comment by MattieBelt** [comment]
The problem, really lies with yup 0.28.2

**Comment by gorgekara** [comment]
If the problem lies in new `yup` version maybe set a fix one that works - ex.: `0.27.0`?

**Pull request merged**
