### PR TITLE
Upgrade Sentry version (both for plugin and internal) to latest

### LINKED ISSUE #12702: Sentry integration is not working with Strapi 4
### Describe the bug
Strapi is not reporting any errors to the sentry. tried triggering errors by sending invalid graphql request and Rest API call in both cases it's not reporting errors to sentry.

### Steps to reproduce the behavior

1. Enable graphql plugin
2. Install latest sentry plugin (one compatible with sentry 4)
3. Configure sentry plugin in config/plugin.js as shown in step below 

```javascript
// path: ./config/plugins.js

module.exports = {
  //
  graphql: {
    config: {
      endpoint: "/graphql",
      shadowCRUD: true,
      playgroundAlways: true,
      depthLimit: 7,
      amountLimit: 100,
      apolloServer: {
        tracing: false,
      },
    },
  },
  sentry: {
    enabled: true,
    config: {
      dsn: "https://xxxxxxxxxxxxxxxxxxx@xxxxxxx.ingest.sentry.io/xxxxxxx",
      sendMetadata: true,
    },
  },
};

```
5. Create A collection
6. Add Data
7. Call graphql API / Rest API with invalid parameters 
8. It will return error response 
9. Error wont be logged in sentry

### Expected behavior

The error should be reported to the sentry and should be visible in the sentry dashboard.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version:  v16.13.1
- NPM version: 8.1.2
- Strapi version: 4.0.3
- Database: postgres / sqlite
- Operating system: mac / linux

### PR DESCRIPTION
**Pull request by derrickmehaffy**
Signed-off-by: Derrick Mehaffy <derrickmehaffy@gmail.com>

fixes #12702

### CODE REVIEW

**Review by remidej — APPROVED** [review]
Tested locally, it works well 👌

**Comment by derrickmehaffy** [comment]
> Tested locally, it works well ok_hand

The only thing I'm worried about is internally we had a very old version (6.3.0) so I'm hoping there was no breaking changes I missed that would stop sending sentry events to us.

**Comment by gu-stav** [comment]
@derrickmehaffy From my experience sentry is very stable and expresses its changes in semver versions, so I'm not worried too much.

**Comment by SujayPrabhu96** [comment]
Folks, when can we expect this on production ?

**Comment by derrickmehaffy** [comment]
@remidej approved so gonna merge this for the next release.

**Pull request merged**
