### PR TITLE
Relations & Dynamic Zones reordering

### LINKED ISSUE #14908: Reordering Relations in Dynamic Zone cause blank screen
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.5.0
- Database: mysql v8
- Operating system: macOs 12.5

### Describe the bug

When a Relation component is used in a Dynamic Zone, reordering the Relation component will lead to a blank screen with following error:

```
TypeError: i is not iterable
```

### Steps to reproduce the behavior

1. create Relation component
2. create a Dynamic Zone which use that Relation component, and also any other component type
3. in Content Manager, reorder the added Relation component among other components in the same Dynamic Zone

### Expected behavior

Reordering a Relation component in Dynamic Zone won't lead to a blank screen

### Screenshots

Screenshot 2022-11-17 at 4 25 30 PM

### Code snippets

suggest to change this line — https://github.com/strapi/strapi/blob/b169f6fe33253d3b6875131fc56454b786ef119e/packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js#L140

from

```
        set(draftState, initialDataPath, uniqBy([...value, ...initialDataRelations], 'id'));
```

```
        set(draftState, initialDataPath, uniqBy([...value, ...(initialDataRelations || [])], 'id'));
```

So it wont spreading an undefined `initialDataRelations` (which its index in dynamic zone is changed) when reordering the Relation component

### LINKED ISSUE #15141: Drag icon in repeatable component not visible in dark mode
### Required System information

- Node.js version: 16.18.0
- NPM version: 8.19.2
- Strapi version: 4.5.3
- Database: Not Relevant
- Operating system: Windows 11

### Describe the bug

In the dark mode, the *Drag* icon is not visible, adding repeatable components.

### Steps to reproduce the behavior

 1.   Create a content-type with a repeatable component
 2.   Add items and observe.
 
### Expected behavior
Icon's color should change according to the mode. For Example - In light mode it has dark color.
That same color is being used here.

### Screenshots

On hover - 

Drag Icon - On Hover

Without hover - 

Drag Icon - Without hover

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* Adds relations re-ordering (BE & FE)
* Adds dynamic zones re-ordering (drag and drop FE only)

### Related Issues
* resolves #15141
* resolves #14908

### CODE REVIEW

**Review by Marc-Roig — APPROVED** [review]

**Comment by Boegie19** [comment]
Just a quick question is this able to be disabled since lets say I have 99999 relationships to 1 entity what would be the performance hit and would I be able disabled so you don't get the hit at all if you don't need reordering of relationships

**Comment by joshuaellis** [comment]
> Just a quick question is this able to be disabled since lets say I have 99999 relationships to 1 entity what would be the performance hit and would I be able disabled so you don't get the hit at all if you don't need reordering of relationships

IMO this is too granular a step for permissions. This then becomes permissions on actions per field type which raises a lot more questions re. dynamic zones should you be able to not reorder them etc?

**Comment by Boegie19** [comment]
> IMO this is too granular a step for permissions. This then becomes permissions on actions per field type which raises a lot more questions re. dynamic zones should you be able to not reorder them etc?

@joshuaellis Still not being able to disable reodering to not get the reodering hit when somone moves the top to bottom or other way around and the hit is more then 30 seconds is to my opinion not exactable since that means that my whole aplication for anyone is not accasible for 30 seconds witout scaling if it is not more

**Comment by joshuaellis** [comment]
> > IMO this is too granular a step for permissions. This then becomes permissions on actions per field type which raises a lot more questions re. dynamic zones should you be able to not reorder them etc?
> 
> @joshuaellis Still not being able to disable reodering to not get the reodering hit when somone moves the top to bottom or other way around and the hit is more then 30 seconds is to my opinion not exactable since that means that my whole aplication for anyone is not accasible for 30 seconds witout scaling if it is not more

We're at a difference in opinion. If you want to see this feature considered, then I would suggest you add it on Canny – https://strapi.canny.io/

**Comment by Boegie19** [comment]
@joshuaellis Me and @Cpaczek just did a test if we have 10000 relationships and we reoder the 1000 relationship to 9999 then it takes 43000 for strapi since you give us the last added relationships in the view reordering any of them even by 1 has this impact So that means that any enterprise customer needs this disabled on there large relationships and we don't even have to click load more once also deleting 1 with 10000 relationships and you delete the 10000 relationship It takes 85 seconds to do so  of the relationships has the same issue aka this would make strapi unusable for enterprise customers with large amount of relationships. Also I will write it out under the following issue with replication steps https://github.com/strapi/strapi/issues/15539 and explain it more

**Comment by joshuaellis** [comment]
> @joshuaellis Me and @Cpaczek just did a test if we have 10000 relationships and we reoder the 1000 relationship to 9999 then it takes 43000 for strapi since you give us the last added relationships in the view reordering any of them even by 1 has this impact So that means that any enterprise customer needs this disabled on there large relationships and we don't even have to click load more once also deleting 1 with 10000 relationships and you delete the 10000 relationship It takes 85 seconds to do so of the relationships has the same issue aka this would make strapi unusable for enterprise customers with large amount of relationships. Also I will write it out under the following issue with replication steps #15539 and explain it more

We've discussed it internally this morning and to address your concerns above we're going to explore refining the FE payload & also investigate into #15539.

RE disabling the ability to re-order, like I said before if you want to see this included you should open a feature request.

**Pull request merged**
