### PR TITLE
[Blocks] Fix content not updating when switching locales

### PR DESCRIPTION
**Pull request by remidej**
### Why is it needed?

There were 2 bugs related to i18n and blocks:

- switching locales did not update the content in the admin
- "fill in from locale" did not work

Both were due to the fact that the Slate component is uncontrolled (see https://github.com/ianstormtaylor/slate/issues/4612). So it was not aware that the value was being updated somewhere else by Redux.

### What does it do?

Since we can't use Slate as a controlled component, my workaround is to count the total updates to `value`, vs the `value` updates that were triggered by Slate. When they're different, it means the `value` was updated from Redux (e.g. when switching locales). In this case it forces a rerender of the Slate component, which will now use the latest `value` version.

I extracted the logic to a custom hook because I didn't want this hack to be in the way of the rest of the component. It also made it easier to document it (comments) since everything related is in 1 place.

### How to test it?

Use a content type that has localization enabled (and at least 2 locales) and a blocks attribute.

Save content in 1 locale, switch to the other. Use "fill in from locale". Switch back and forth between locales. The content you see in the editor should always be in sync with the active locale, without needing to refresh.

### CODE REVIEW

**Comment by joshuaellis** [comment]
So, while I don't think Remi's solution is wrong – I do worry it's quite complicated for what it is, maybe it has to be that way but it would be good to know if we think something like:

```ts
key={JSON.stringify({ initialValue, path })}
```

Would be simpler and work more effectively? Path could just be the content-type & id? i'm not sure of that bit yet. I looked at how Sanity do it and because they have push events with Observables, it's overkill for us. However, this is how payload does it and lets be honest, that one line is simpler – but maybe it's not good enough? not sure.

**Comment by remidej** [comment]
@joshuaellis the reason I didn't go for that approach is that it re-renders the editor on every update, instead of only re-rendering it when the value was updated outside of Slate. It's particularly visible in our case because we lose and regain the focus style on every keypress

https://github.com/strapi/strapi/assets/8087692/31ab8afc-2fc8-40ce-af3d-abf503bff950

**Comment by joshuaellis** [comment]
> @joshuaellis the reason I didn't go for that approach is that it re-renders the editor on every update, instead of only re-rendering it when the value was updated outside of Slate. It's particularly visible in our case because we lose and regain the focus style on every keypress
> 
>  Screen.Recording.2023-10-06.at.09.42.38.mov

damn, what are we passing as the initial value? the value from redux? 🤔 which i guess wouldn't update slate anyway...?

**Comment by remidej** [comment]
@joshuaellis the screen recording I sent was using this, `value` being the one from redux:

```jsx
<Slate
  editor={editor}
  initialValue={value || [{ type: 'paragraph', children: [{ type: 'text', text: '' }] }]}
  onChange={handleSlateChange}
  key={JSON.stringify(value)}
>
```

**Comment by joshuaellis** [comment]
What about just using the content-type & id? Locale's have their own entity ID right? 🤔

**Comment by remidej** [comment]
@joshuaellis I think that would solve switching locales, but probably not the "fill in from another locale" feature

**Comment by joshuaellis** [comment]
> @joshuaellis I think that would solve switching locales, but probably not the "fill in from another locale" feature

ahhhh yes. Okay let's go with your way – can you add a reference to the issue in the comments and maybe just also add why we do this over using the value as a key or the content-type & id – all the reasons you've walked me through already – this just helps people understand why we've done it the way we've done it and some things to test against should they try and change it which hopefully one day we will be able too 🤞🏼

**Comment by remidej** [comment]
@joshuaellis I added more comments 👍

**Review by joshuaellis — APPROVED** [review]
✨

**Review by markkaylor — APPROVED** [review]
Works for me. Tested locally. I was also hoping there would be a simpler work around. I'm not too keen on keeping counters in sync but, hey, it's working!

Tried a few variations of the ideas mentioned here with the time I had, but no luck. Let's move forward with this 👍

**Pull request merged**
