### PR TITLE
Only allow registeration with specific fields

### PR DESCRIPTION
**Pull request by alexandrebodin**
Signed-off-by: Alexandre Bodin <bodin.alex@gmail.com>

### CODE REVIEW

**Comment by jackyang1984** [comment]
But now can't pass value to custom field, in backend can add custom field also. In fact, many business use case need pass value to custom field, i think the feature is unresonable.

**Comment by mmorainville** [comment]
Hi,

As stated by @jackyang1984 , this can breaks things. I have a use-case in my application where I generate accounts for "anonymous users" (you can create an account just by giving up a name). We generate a random password and a random mail the user doesn't need to care about. See it like a throwable, temporary account.
To do that I passed from the front-end the `confirmed` property to true because I want it that way.

Is there now a way to still mark the user as confirmed from the frontend without making a custom hook?

If not, I think I may have to go back to 20.1 for my use case.

Regards,
M.

**Comment by alexandrebodin** [comment]
You can always customize the code of the user-permission plugin to implement the logic you want :) Or create a custom route for your specific usecase

**Comment by mmorainville** [comment]
Hi @alexandrebodin,

Yes of course, but my point is that it's clearly a breaking change (though minor) and I don't exactly see the reason why, as there is nothing really wrong in passing the confirmed property if it's available (especially if the user confirmation is disabled in the admin panel).

The customization possibilities of Strapi are really great (good job on that!) but more customization means more work at every update (to ensure that everything still works as expected). The less we have to customized stuffs, the better, otherwise we wouldn't use Strapi.

Maybe at least we could check if the user care or not about email confirmation by checking the configuration before cherry picking params?

Something like (in pseudo-code):

```
if (Strapi.configuration.isEmailConfirmationEnabled) {
    const params = {
      ..._.pick(ctx.request.body, ['username', 'email', 'password']),
      provider: 'local',
    };
} else {
    const params = _.assign(ctx.request.body, {});
}
```

If you're interested I could try and make and PR, otherwise I'll just custom the code as you suggested.
(But that doesn't solve @jackyang1984 point, where one want to send custom parameters with email confirmation enabled :/.)

**Comment by alexandrebodin** [comment]
Hi, 

If you disable the email confirmation the registration set the `confirmed` flag to `true` automatically I don't think you need to do anything :)

For the other issue indeed we should omit certain properties instead of picking them. 

We should be omitting the confirmed and resterPasswordToken as it shouldn't be something a user can set when calling the register API.

If you want to automate user creation you might want look into using the POST /users API that is an admin API :)

**Comment by mmorainville** [comment]
`If you disable the email confirmation the registration set the confirmed flag to true automatically I don't think you need to do anything :)`

Oh great! I admit I didn't try that and set the `confirmed` right away. This should solve my issue for now then! Thanks!

`For the other issue indeed we should omit certain properties instead of picking them.`
Sounds like a better option indeed! :)

**Comment by alexandrebodin** [comment]
If you are up for a PR it would be awesome 👍

**Comment by frosato-dev** [comment]
I'm not sure why test is failing but I've already opened a PR that should fix the problem: https://github.com/strapi/strapi/pull/6124

@alexandrebodin can you help me with the failing test ?

**Comment by jackyang1984** [comment]
@alexandrebodin   I choose strapi as it's very light and customize, i know strapi only allow registration with "username, email, password" for security, but we will lose the customize feature, as the same time, registration is the portal for other functionalities, some use case really need it. I think change the codes
`_.pick(ctx.request.body, ['username', 'email', 'password'])` to `_.omit(ctx.request.body, ['resetPasswordToken', 'confirmed', 'blocked', 'role'])`
then we have security and  customize.

**Comment by hkovacs** [comment]
> Hi,
> 
> If you disable the email confirmation the registration set the `confirmed` flag to `true` automatically I don't think you need to do anything :)
> 
> For the other issue indeed we should omit certain properties instead of picking them.
> 
> We should be omitting the confirmed and resterPasswordToken as it shouldn't be something a user can set when calling the register API.
> 
> If you want to automate user creation you might want look into using the POST /users API that is an admin API :)

does this mean that developers need to send an api `POST` to register, and then with the returned user id send an api `POST` to users? can you provide a link to the docs that has information on this?

Thank you!

**Pull request merged**
