### PR TITLE
feat: add en-US and en-GB localization (allowing use of respective date formats)

### PR DESCRIPTION
**Pull request by Christian-Schwarz2003**
### What does it do?

- I added a localization for en-GB and en-US,
- It allows the use of DD/MM/YYYY date format (by using en-GB)
### Why is it needed?

This is useful to people who use the DD/MM/YYYY system on a daily basis and mistakenly switch month and day around

### How to test it?

- Add "en-GB" and "en-US" to the locales in the admin panel config
- View any entry that has a date format

yarn test:front

### Related issue(s)/PR(s)

- https://github.com/strapi/strapi/issues/12216 / https://feedback.strapi.io/customization/p/option-to-change-the-date-format-in-the-admin-dashboard

### CODE REVIEW

**Comment by Christian-Schwarz2003** [comment]
Just wondering if there is anything more i have to do, before it can be reviewed

**Comment by Christian-Schwarz2003** [comment]
the workflows keep getting this error:

```
Error: Command failed: git diff --name-only --no-renames --relative "origin/main" "29cd85b41c5c977acef9ab563a7a9cf6f7fbf952"
fatal: ambiguous argument 'origin/main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

```
while running nx affected

**Comment by Christian-Schwarz2003** [comment]
Is there any way I can speed up/fast track the reviewing process?
I feel this would benefit many users who use the english UI outside the US

**Comment by alexandrebodin** [comment]
Hi @Christian-Schwarz2003 Strapi is under change feeze while we were preparing v5. It is now out and you can resubmit your PR on `develop` to get it into v5. 

We are only accepting v4 cirtical or security issue fixes as it moves to maintenance. 

Let me know if you need anby guidance 🙌

**Comment by Christian-Schwarz2003** [comment]
Im developing on windows and git is throwing the following error when in try to checkout the latest commit 
`error: invalid path 'packages/core/review-workflows/admin/src/routes/settings/:id.tsx'`

i think it is due to the colon, because you cant use that in windows file names.
I'll try to do it in  a vm but i rarely work with linux, so thats gonna be fun.

**Pull request closed without merging**
