### PR TITLE
Temporary fix for GraphQL variables not being loaded

### LINKED ISSUE #3537: GraphQL nested filter using variable not giving correct results
**Describe the bug**
GraphQL queries using a variable in a nested filter are giving do not apply the filter, where adding the string directly in the query gives the correct result

**Steps to reproduce the behavior**
1. Query a content types relationship with variable in a nested filter
2. Compare the results to the same query entering the string directly in the filter

**Expected behavior**
The results given should be the same

**Screenshots**
Correct result using string
Screenshot_2019-06-27 Playground - http localhost 1337 graphql(1)
Incorrect result using variable (post id:1 is returned although its PostCategories are empty
Screenshot_2019-06-27 Playground - http localhost 1337 graphql

**System**
- Node.js version: 10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.7
- Database: MariaDB 10.1.40
- Operating system: Ubuntu

**Additional context**
Model settings.json for above example attached below
Postcategory.settings.json
```json
{
  "connection": "default",
  "collectionName": "postcategory",
  "info": {
    "name": "postcategory",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "slug": {
      "type": "string"
    },
    "posts": {
      "collection": "post",
      "dominant": true,
      "via": "postcategories"
    }
  }
}
```

Post.settings.json
```json
{
  "connection": "default",
  "collectionName": "post",
  "info": {
    "name": "post",
    "description": ""
  },
  "options": {
    "timestamps": [
      "created_at",
      "updated_at"
    ]
  },
  "attributes": {
    "slug": {
      "unique": true,
      "required": true,
      "type": "string"
    },
    "featuredImage": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": true
    },
    "content": {
      "type": "text"
    },
    "postcategories": {
      "collection": "postcategory",
      "via": "posts"
    },
       ......
  }
}`

### PR DESCRIPTION
**Pull request by derrickmehaffy**
#### Description of what you did:

Fix for variables in GraphQL with latest version, hard coded to 14.3.1 version instead of allowing npm/yarn to install the latest.

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #3537
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by alexandrebodin** [comment]
@derrickmehaffy Can you point to the change in grahpql v14.4.0 that breaks ?

**Comment by derrickmehaffy** [comment]
@alexandrebodin wasn't me that found it but @lith. I can confirm though that downgrading solved the issue as I tested myself.

**Comment by alexandrebodin** [comment]
@derrickmehaffy I'll wait for @Lith to give us some more context. It might just need some fix in strapi itself. I haven't seen any breaking change in the graphql changelog that could explain what's happening.

**Comment by alexandrebodin** [comment]
I'm closing this as there is an explanation about it. i'll give more context in the issue

**Pull request closed without merging**
