### PR TITLE
Fix Update user does not update component attribute

### LINKED ISSUE #11832: [v4] GraphQL Mutation doesn't update component's booleans
### Describe the bug

In Strapi v4.0.0 I have added a component User -> Flags to store various booleans flags related to user. The component configuration is as follows (just 1 field for simplicity):
```
{
  "collectionName": "components_user_flags",
  "info": {
    "displayName": "flags",
    "icon": "adjust"
  },
  "options": {},
  "attributes": {
    "welcomeCompleted": {
      "type": "boolean",
      "default": false
    }
  }
}
```

Linked with user as:
```
"flags": {
      "type": "component",
      "repeatable": false,
      "component": "user.flags"
    }
```

All configuration/linking was done via Strapi Admin.

I can access this component via GraphQL query and see it properly in Strapi Admin - all good here.

However, upon sending mutation to update this component in a following simple form (tested both via React with Apollo Client and `http://localhost:1337/graphql`), I'm getting successful response without any errors, however flag still stays false.
```
mutation updateUser {
  updateUsersPermissionsUser(id: "3", data: { flags: { id: "1", welcomeCompleted: true } }) {
    data {
      id
      attributes {
        flags {
          id
          welcomeCompleted
        }
      }
    }
  }
}
```

```
{
  "data": {
    "updateUsersPermissionsUser": {
      "data": {
        "id": "3",
        "attributes": {
          "flags": {
            "id": "1",
            "welcomeCompleted": false
          }
        }
      }
    }
  }
}
```

If I update the flag manually in Admin panel, the new value is saved, but seems that this is not working via GraphQL? Or maybe I'm doing something wrong?

### Steps to reproduce the behavior

1. Add not repeatable component to user collection (from users-permissions) with boolean field
2. Try to update field in this component via GraphQL
3. The field is not being updated

### Expected behavior

The field in the component (inside collection) to be properly updated.

### System

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version: v4
- Database: postgres
- Operating system: macOS

### PR DESCRIPTION
**Pull request by iicdii**
Signed-off-by: harimkims <harimkims@gmail.com>

### What does it do?

- Replace old update query used in v3 with new `entityService` in v4
- Add e2e test for GraphQL update user mutation

### Why is it needed?

To be compatible with v4 params

### How to test it?

1. Create component
2. Add component field in User in Content-type builder. (single component)
3. Go to page for Create or Update user
4. Input any data into component field
5. Send GraphQL mutation in http://localhost:1337/graphql
```gql
mutation updateUser {
  updateUsersPermissionsUser(id: "3", data: { comp: { id: "1", name: "update test" } }) {
    data {
      id
      attributes {
        comp {
          id
          name
        }
      }
    }
  }
}
```
6. Check if field is updated in result

### Related issue(s)/PR(s)

Closes #11832

### CODE REVIEW

**Comment by iicdii** [comment]
```js
yarn run v1.22.17
$ next lint --dir __tests__
info  - Loaded env from /Users/chisus/Develop/bbsworld/web-view/.env.local

./__tests__/faq.test.js
296:14  Error: Avoid using container methods. Prefer using the methods from Testing Library, such as "getByRole()"  testing-library/no-container
296:24  Error: Avoid direct Node access. Prefer using the methods from Testing Library.  testing-library/no-node-access
301:14  Error: Avoid using container methods. Prefer using the methods from Testing Library, such as "getByRole()"  testing-library/no-container
301:24  Error: Avoid direct Node access. Prefer using the methods from Testing Library.  testing-library/no-node-access

./__tests__/notice.test.js
245:11  Error: Prefer `findByTestId` query over using `waitFor` + `getByTestId`  testing-library/prefer-find-by
348:14  Error: Avoid using container methods. Prefer using the methods from Testing Library, such as "getByRole()"  testing-library/no-container
348:24  Error: Avoid direct Node access. Prefer using the methods from Testing Library.  testing-library/no-node-access
353:14  Error: Avoid using container methods. Prefer using the methods from Testing Library, such as "getByRole()"  testing-library/no-container
353:24  Error: Avoid direct Node access. Prefer using the methods from Testing Library.  testing-library/no-node-access

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

notice쪽이랑 함께 eslint 에러 fix 부탁드려요~

**Review by Convly — COMMENTED** [review]
LGTM, waiting for the tests to pass

**Review by Convly — DISMISSED** [review]

**Comment by iicdii** [comment]
I just found unnecessary `console.log` I will remove it now 😅

**Review by Convly — APPROVED** [review]
Nice catch, waiting for the tests again and then merging.

**Comment by devjiro76** [comment]
I tested this fix.
and I found with this fix, I can't update user information.

url: /api/users/1
method: put
body: {"username": "haha"}

this request makes an error.

```
Error: Undefined attribute level operator id
    at processAttributeWhere (/Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/database/lib/query/helpers/where.js:82:13)
    at processWhere (/Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/database/lib/query/helpers/where.js:176:36)
    at /Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/database/lib/query/helpers/where.js:104:29
    at Array.map (<anonymous>)
    at Object.processWhere (/Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/database/lib/query/helpers/where.js:104:18)
    at Object.processState (/Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/database/lib/query/query-builder.js:234:29)
    at Object.getKnexQuery (/Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/database/lib/query/query-builder.js:271:12)
    at Object.execute (/Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/database/lib/query/query-builder.js:352:25)
    at Object.findOne (/Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/database/lib/entity-manager.js:121:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.update (/Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/strapi/lib/services/entity-service/index.js:197:28)
    at async Object.<anonymous> (/Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/strapi/lib/services/entity-service/index.js:67:20)
    at async Object.update (/Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/plugin-users-permissions/server/controllers/user.js:127:18)
    at async returnBodyMiddleware (/Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /Users/devjiro76/Documents/Workspace/nenekin/strapi/node_modules/@strapi/strapi/lib/middlewares/body.js:24:7
```

**Pull request merged**
