### PR TITLE
Add "made by strapi" badge to official marketplace plugins

### PR DESCRIPTION
**Pull request by remidej**
### What does it do?

- Adds "made by strapi" badge to official plugins on the marketplace
- Replaces the previous "verified" logo by the one used on the current Figma designs

### CODE REVIEW

**Review by markkaylor — COMMENTED** [review]
Here you've added two new icons. For the "Made by Strapi" I guess it does make sense to use an `svg` for a small icon, but I still wonder if we could just use `strapi_logo_menu.png`

For the "Verified Badge", my reasoning for using `CheckCircle` vs the icon in the figma file was that the `CheckCircle` icon is part of the design system. I think we (and the designs) should respect the design system as closely as possible. 

Mainly I'm just wondering if we should be adding these icons here or to [Strapi icons](https://github.com/strapi/design-system/tree/main/packages/strapi-icons)? 🤔

**Comment by remidej** [comment]
For the made by Strapi icon, I think it's better to use the image coming straight from Figma. It has the benefit of being an SVG, and it has a different border radius that I'd prefer not to set manually.

I understand your points regarding the verified badge however. I think it comes down to whether we prefer consistency with the design system, or consistency with the Strapi Market branding. I think we should ask Raff to make this decision

**Comment by markkaylor** [comment]
Yeah I noticed the border radius, and that's actually part of the reason I asked the question. Now we are introducing a new version of the logo that is not consistent with the other Strapi logos in the app. Not sure that is a good thing, but I'm also not sure what the best move is! Adding the `svg` does seem to make sense but now I am questioning that border radius, should it be consistent with the other logos? @rgesulfo

**Comment by remidej** [comment]
I personally don't think it's problematic because it serves a different purpose: it's not a strapi logo, it's a "made by strapi" badge. Also it's much smaller, and being this small I think it would look too square if the radius wasn't adjusted

**Review by markkaylor — APPROVED** [review]
Looks good to me. We can merge this I think and address these questions about the icons later.

**Comment by rgesulfo** [comment]
Thanks for bringing this up @markkaylor. As @remidej mentioned, the border radius can vary based on the size of its container. Can't wait to see the badge live! :D

**Pull request merged**
