### PR TITLE
Improve <Ico> component for handle click if specified

### LINKED ISSUE #1257: Cannot click 'pencil' icon in Content Manager
**Informations**
- **Node.js version**:
9.0.0
- **npm version**:
6.0.1
- **Strapi version**:
3.0.0-alpha.12.2
- **Database**:
MongoDB v3.6.5
- **Operating system**:
Mac OS X Sierra
**What is the current behavior?**
Nothing happens when I click the icon ( I can however click anywhere else on the line )

**Steps to reproduce the problem**
Click the pencil icon.

**What is the expected behavior?**
To edit the entry (just as when clicking anywhere on the line).

**Suggested solutions**
Well, erhm ... how about making it work as expected!?

### PR DESCRIPTION
**Pull request by johannpinson**
My PR is a:
🐛 Bug fix

Main update on the:
Admin

Fix #1257

### CODE REVIEW

**Comment by soupette** [comment]
Hi @johannpinson, thanks for your contribution. However, I don't really see the improvement since if there is no `onClick` handler provided the `Ico` component will use the `defaultProps` `onClick` which is a function.
In this case I would say that an improvement will be the following :

```js
import { isFunction } from 'lodash';


const handleClick = (e, onClick) => {
  e.preventDefault();
  e.stopPropagation();

  if (isFunction(onClick)) {
    onClick(e);
  }
};

// Then we need to change the `propTypes` to allow booleans

Ico.propTypes = {
  onClick: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.bool,
  ]),
};

**Comment by johannpinson** [comment]
Hey @soupette 

In fact, the problem is about the `e.stopPropagation()`, which results a bug from the issue #1257.
And whatever the `defaultProps`, the `IcoContainer` also provide one:

https://github.com/strapi/strapi/blob/bb514d48ce8550f68a4a36b8e8fb7fccd076d4ef/packages/strapi-helper-plugin/lib/src/components/IcoContainer/index.js#L20-L22

Since the default value will still be an empty function, force the stop of event propagation can be a problem if a parent element also have a `onClick` handler (as exception for the `delete` button)
<br>
It's why I group all the code inside the `if` statement, to disable any overridden behavior.
(and i don't use the `isFunction` because it can be a `boolean`).
Actually, the PR just not cover the case if the developer set the props to the boolean `true`.

Feel free to contact me via Slack if necessary.

PS: well seen for the default props, I thought I changed it with my commit.

**Comment by BroTrue** [comment]
Hi guys. Do I need to create 'strapi-helper-plugin' to fix that bug with pencil?

**Comment by soupette** [comment]
@johannpinson thanks for clarifying, in this case I agree with your PR if you can update the `proptypes` to reflect what we discussed above.

@BroTrue you don't need to create the `strapi-helper-plugin` package it's [here](https://github.com/strapi/strapi/tree/master/packages/strapi-helper-plugin).

**Comment by johannpinson** [comment]
@soupette I already made the update after my previous comment 😉

**Pull request merged**
