### PR TITLE
fix: grammar 

### PR DESCRIPTION
**Pull request by sammychinedu2ky**
Signed-off-by: Alexandre Bodin <bodin.alex@gmail.com>
Signed-off-by: Samson Amaugo <sammychinedu2ky@gmail.com>

fix:corrected grammar

### CODE REVIEW

**Comment by petersg83** [comment]
Hi :) It says `Files changed 0`. Am I missing something?

**Comment by sammychinedu2ky** [comment]
I'm sorry I actually corrected something locally but seems I made a mistake by  reversing it before pushing

**Comment by derrickmehaffy** [comment]
@sammychinedu2ky be sure that if you are marking documentation grammar fixes you set the PR target as `documentation` not `master`

**Comment by alexandrebodin** [comment]
The PR doesn't contain any changes. Closing :) Feel free to reopen a new one with the changes :)

**Pull request closed without merging**
