### PR TITLE
Update "Adding a new Provider" section

### PR DESCRIPTION
**Pull request by fiblan**
PopUpForm has been removed in 43ee492fcbf02170e7421a3b473660d49e7da0a2, but the documentation still refers to it. This PR remove any reference.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@soupette or @HichamELBSI can you two please verify the change and ensure we aren't missing anything required to add a new provider?

**Comment by soupette** [comment]
> @soupette or @HichamELBSI can you two please verify the change and ensure we aren't missing anything required to add a new provider?

Well in some cases a provider might need a dedicated form, so some configuration might be required in this [file](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/admin/src/containers/Providers/utils/forms.js) and also [this statement](https://github.com/strapi/strapi/blob/583488fb4dd84d6708951a1d6e34ed4bdd191ae5/packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js#L91-L101) here might need to be updated in order to retrieve the correct form. To be honest I am not sure how to write the documentation so if you have some guidance I'll be happy to help.

**Comment by derrickmehaffy** [comment]
In the case of those providers, it's most likely we will need an RFC anyway or at least a review from the design team to make sure.

@fiblan if you are comfortable with writing instructions like that in the docs please feel free else we will skip that. Eventually the plan is to get rid of grant altogether (to move to passport) so these docs are only temporary.

**Review by derrickmehaffy — APPROVED** [review]
Changes look good to me, without the new additions, pending author response if they wish to add them else we will merge as is.

**Comment by derrickmehaffy** [comment]
Change no longer required as the docs were updated in another PR

**Pull request closed without merging**
