### PR TITLE
Update DE translations

### PR DESCRIPTION
**Pull request by forethoughtde**
#### Description of what you did:
Added some missing translations for built-in admin panel for German language.

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [x] Admin
- [ ] Documentation
- [ ] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by forethoughtde** [comment]
I have updated it as you have requested it.

**Comment by veitbjarsch** [comment]
👍

**Comment by lauriejim** [comment]
Thank you for this update. Your changes are now visible 👍

I checked the same file but the [`en` version](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/translations/en.json).
And I noticed translations are placed after `"app.utils.delete": "Delete",` line.
And here you added all `HomePage[...]` keys. But there is some missing keys If I follow the `en` file.
```
  "HomePage.helmet.title": "Homepage",
  "HomePage.welcome.congrats": "Congrats!",
  "HomePage.welcome.congrats.content": "You are logged as the first administrator. To discover the powerful features provided by Strapi,",
  "HomePage.welcome.congrats.content.bold": "we recommend you to create your first Content-Type.",
  "HomePage.community": "Join the Community",
  "HomePage.roadmap": "See our roadmap",
  "HomePage.greetings": "Hi {name}!",
```
Can you please add other `HomePage` missing translation pelase.

**Comment by alexandrebodin** [comment]
@forethoughtde still a bit more work to do. Do you think you will be able to do it ?

**Comment by forethoughtde** [comment]
I can do this. I will do it in this weekend. @alexandrebodin

**Comment by lauriejim** [comment]
Thank you @forethoughtde ! Waiting for your updates.
I really appreciate your contribution.

**Comment by lauriejim** [comment]
@forethoughtde In your last commit you replaced all translation by the `en` values...

**Comment by forethoughtde** [comment]
@lauriejim Sorry. I do not understand what you mean?

**Pull request merged**
