### PR TITLE
Strapi support srv uri

### LINKED ISSUE #432: MongoDB cluster connection
can i use https://cloud.mongodb.com as DB ?

### PR DESCRIPTION
**Pull request by sundaycrafts**
My PR is a:

🚀 New feature

Main update on the:

Framework

By #1743, Strapi had become accept “new” command +srv URI but the generated project still not supports it actually. This pull request is for it becomes support +srv URI!

This pull request may be looked has lot of changes but it because of beautify code and shallow nest. Please review it by ignoring white space🙏

resolve #432

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello @sundaycrafts, thank you for this PR.

I would love have one PR for the fix (easy to review) and one for code clean.

Will try to work on your PR soon as possible.

**Comment by sundaycrafts** [comment]
Hi @lauriejim. I made sense!
I'm sorry to make you suffer to review in this pull request…
I will make it separately for next time!

Thank you for your review.

**Comment by lauriejim** [comment]
@sundaycrafts Please can you open an other issue with just your +srv support (Too hard to read what is feature update and what is beautify)
I will review that first before review some beautify code on this PR.
Thank you.

**Comment by sundaycrafts** [comment]
@lauriejim Sure! Thank you for your review.
I will revert some lines doesn't depend on this pull request.
Then I open another pull request.

**Comment by lauriejim** [comment]
When we create a new app, you set `srv` as a `string` instead of a `boolean` type.
Can you did an update about that in the `strapi-generate-new`

And handle it like [this code](https://github.com/strapi/strapi/pull/1831/files#diff-43153381da5552c728ec8acf21724e86R75) for [this code](https://github.com/strapi/strapi/pull/1831/files#diff-43153381da5552c728ec8acf21724e86R57)

**Comment by sundaycrafts** [comment]
Ok, I did it!
I feel so good for Monorepo design 👍

**Comment by lauriejim** [comment]
`(It will be ignored if you enable +srv)` is also displayed when we create an application with **Postgres**. I think we have to display it only for Mongo.

**Comment by sundaycrafts** [comment]
Oh, it's my mistake. Thank you!
I fixed it!

**Comment by gianniskarmas** [comment]
How exactly does the database.json has to look with "srv": true?
It doesn't seem to work for me with atlas.
Keep creating new projects just to find the correct format but it is so unstable... sometimes the connection is successful but when I strapi start the project it doesn't start with error:
[2018-09-14T12:59:50.182Z] debug ⛔️ Server wasn't able to start properly.
[2018-09-14T12:59:50.183Z] error Make sure your MongoDB database is running...

**Comment by sundaycrafts** [comment]
Hi @gianniskarmas .
- Have you registered your global IP address into cluster whitelist?
- Can you access the DB from [Compass](https://www.mongodb.com/products/compass)?
- Does that user have read/write permission of that DB?

**Comment by gianniskarmas** [comment]
Hi @sundaycrafts.
1. Yes
2. Never use compass but it works perfectly well through 3T Studio, Cli etc.
3. Yes,
4. Yes, Gbit - 4ms ping to Europe.
It seems like there is a caching happening within mongoose or the hook.
I can make it work using uri alone but trying to implement this latest srv parameter.
Can someone suggest the best way to debug strapi in general as to locate the problem?

**Comment by sundaycrafts** [comment]
@gianniskarmas Ok, I make sense!
Please try to set breakpoint or console.log() and check `error.message` on [there]( https://github.com/strapi/strapi/blob/master/packages/strapi-hook-mongoose/lib/index.js#L94).

**Comment by pierreburgy** [comment]
@sundaycrafts do you really need `dbName` in `connectionOptions` (https://github.com/strapi/strapi/pull/1831/files#diff-43153381da5552c728ec8acf21724e86R77)?

This is what breaks the Heroku deploy (https://github.com/strapi/strapi/issues/2136) so it would be great to remove it.

**Comment by sundaycrafts** [comment]
@pierreburgy Hi! My answer is Yes. I think you can't connect URL having `+srv` without `dbName`. Could you try it yourself if you have time?

> Specifies which database to connect to and overrides any database specified in the connection string. If you're using the mongodb+srv syntax to connect to MongoDB Atlas, you should use dbName to specify the database because you currently cannot in the connection string.

https://mongoosejs.com/docs/connections.html

**Pull request merged**
