### PR TITLE
Update Strapi-Bookshelf to properly store long float values

### PR DESCRIPTION
**Pull request by derrickmehaffy**
My PR is a:

🐛 Bug fix

Main update on the:

Plugin

Update MySQL float data type from `float` to `double` to properly store large float values.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Fix for https://github.com/strapi/strapi/issues/1148

**Comment by lauriejim** [comment]
@derrickmehaffy Can you check if it also work with Postgres please.

**Comment by derrickmehaffy** [comment]
@lauriejim have never used Prostgres before but I'll give it a shot

**Comment by derrickmehaffy** [comment]
@lauriejim PR updated and tested with Postgres and MySQL

**Pull request merged**
