### PR TITLE
[V4] Fix 500 on create/update with empty body

### LINKED ISSUE #11489: [v4] Sending malformed POST payload in REST yeilds a 500 error
### Describe the bug

if you send an improper POST body payload it will throw a 500 error

### Steps to reproduce the behavior

1. Create a collection type with Draft & Published enabled
2. Set permissions and/or create a user and auth
3. Send a POST request with keys inside an object (without a data object)

### Expected behavior

Should return a 400 Bad Request error, not a 500

### Screenshots

image
image
image

### Code snippets

Bad Payload:
```json
{
    "string": "test",
    "stringRequired": "test"
}
```

Good Payload:
```json
{
    "data": {
        "string": "test",
        "stringRequired": "test"
    }
}
```

### System

- Node.js version: v14.17.5
- NPM version: v6.14.14
- Strapi version: 4.0.0-beta.11
- Database: SQLite
- Operating system:  Linux Mint 20.2

### Additional context

N/A

### PR DESCRIPTION
**Pull request by Convly**
### What does it do?

Fix 500 on create/update with empty body & throw a ValidationError instead

### Why is it needed?

The server should invalidate the request instead of throwing a 500

Fix #11489

### CODE REVIEW

**Comment by Convly** [comment]
@alexandrebodin I wasn't sure whether to put the checks in the core API's services or controllers.
Let me know your opinion on the matter :slightly_smiling_face:

**Review by Elhebert — APPROVED** [review]

**Comment by Elhebert** [comment]
Might be better to put the validation in the controller as it's the first point on entry 🤔 But other than that LGTM.

**Comment by Convly** [comment]
> Might be better to put the validation in the controller as it's the first point on entry thinking But other than that LGTM.

Yeah, that's what I initially thought, but I couldn't remember if it can be an issue with the files or not (a scenario where you need to have `files` defined & you don't really care about `data`) :thinking:

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
Should this be verified in the entity validator in entity service ?

I think the error messages are misleading. As we are in the services we should only be speaking about data.
to finish I would verify the request as a data object in the controllers and not in the service

**Review by alexandrebodin — APPROVED** [review]

**Pull request merged**
