### PR TITLE
Chore: Update styled-components to 5.3.6

### PR DESCRIPTION
**Pull request by gu-stav**
### What does it do?

Updates `styled-components` from 5.3.3 to 5.3.6.

### Why is it needed?

Keep dependencies up-to-date.

### CODE REVIEW

**Review by jhoward1994 — DISMISSED** [review]

**Comment by joshuaellis** [comment]
do you know why snyk keeps failing? 🤔

**Comment by gu-stav** [comment]
I don't have access to the report. @derrickmehaffy do you?

**Comment by derrickmehaffy** [comment]
> I don't have access to the report. @derrickmehaffy do you?

No I don't either, I think only Alex does honestly. If you pull the branch and do a `yarn audit` you should be able to see whatever it's catching.

**Comment by gu-stav** [comment]
🤔 Yarn audit prints a log of high-sev issues but none that is related to this PR ...

**Comment by gu-stav** [comment]
Found the problem: 

- https://github.com/styled-components/styled-components/issues/3879
- https://security.snyk.io/package/npm/styled-components/5.3.6

According to the library-maintainers nothing we should worry about. Alternative would be to wait for the v6 release.

**Comment by joshuaellis** [comment]
We'd need an admin to merge this in that case because `snyk` is failing. The follow up would be would it fail on every other PR? If so, can't merge it because it would slow everyone down 🐌

**Comment by gu-stav** [comment]
Yes that is true unfortunately. Let's close this then and wait for v6.

**Pull request closed without merging**
