### PR TITLE
Update PL translations

### PR DESCRIPTION
**Pull request by mleko**
My PR is a:

💅 Enhancement

PR for https://github.com/strapi/strapi/issues/1624

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello @mleko Thank you for your PR.

It's possible for you to compile all your translations update in just one PR please.

**Comment by mleko** [comment]
@lauriejim Sure, done that

**Comment by lauriejim** [comment]
There is still PL translations missing if you want https://github.com/strapi/strapi/issues/1624

**Comment by mleko** [comment]
Hi I am aware I skipped some keys. I wasn't sure how to translate them in a way they would be "natural". But I will try to get back to them.

**Pull request merged**
