### PR TITLE
refactor(plugins/graphql): improve the codebase

### PR DESCRIPTION
**Pull request by YassinEldeeb**
Good morning, Strapi Team! Yassin from [The Guild](https://the-guild.dev/) is here 👋🏼

Let us introduce ourselves first, we’re a unique group of open-source developers who authored and are maintaining most of the leading Open Source GraphQL tools that are used on daily bases like [GraphQL Code Generator](https://github.com/dotansimha/graphql-code-generator), [GraphQL Mesh](https://github.com/Urigo/graphql-mesh), [GraphQL Yoga](https://github.com/dotansimha/graphql-yoga), [GraphQL Tools](https://github.com/ardatan/graphql-tools), [GraphQL Scalars](https://github.com/Urigo/graphql-scalars) and many many others(check out our website). 

We build these tools because we needed them and we thought they were lacking in the industry from our various experiences. 

Every once in a while we pick a really cool open source project that we really admire (that’s mostly related to GraphQL) and Strapi’s GraphQL plugin has caught our attention, we forked the repo and introduced our tools into your graphql plugin codebase to better improve maintainability, performance, extensibility, and also offer to maintain it if that’s something you’d be up to. 

We’ve changed a lot of things but just as a suggestion. Let’s have a conversation on things you may want to merge and things you wanna discard.

### JS → Typescript

We were really surprised at first to know that Strapi was written fully in 100% JS and we’re convinced that this’s certainly because of important design decisions that we’re not aware of at least at the core level of Strapi.

But from what we’ve noticed in the GraphQL plugin, it seems like it’s an independent package that could possibly take another route without breaking any of the design decisions that are in place and could really take advantage of typescript’s type-safety features in catching bugs early and being more confident/productive about the code we’re writing. That being said, we’ve rewritten the entire plugin source code to Typescript and we’re very curious about your take on it because we’ve seen JSDoc which means that you’re concerned about type safety too but there’re probably some details we’re missing.

### Normal Imports instead of using the `getService(’…’)`

Since we’ve migrated to Typescript, this was a roadblock for type-safety because there was no guarantee about what we were importing being actually available and also the imported item comes back with `any` type which is inconvenient when we’ve services typed. That also eliminates the weird exports everywhere that were wrapped by a function that returns another function when invoked(which was the work done by the `getService(…)` function.

Untitled

### Apollo Server → GraphQL Yoga 2.0

We see that Yoga takes better approaches than Apollo Server which can be illustrated in the following points:

**Architecture**

One of the main advantages of [GraphQL Yoga 3.0](https://graphql-yoga.com/) is its architecture. In the same way that TypeScript aims to stay aligned with ECMAScript, GraphQL Yoga 3.0 is based on several official and recognized specs:

[GraphQL-spec](https://spec.graphql.org/October2021/), [GraphQL-over-HTTP](https://github.com/graphql/graphql-over-http): guarantees your GraphQL API to work with all existing GraphQL clients (Apollo, Relay, URQL, and more).

[GraphQL-Multipart-Request](https://github.com/jaydenseric/graphql-multipart-request-spec): enables great file upload support.

[W3C Fetch API](https://fetch.spec.whatwg.org/) : we embrace the future of Node.js and provide the same developer experience on all platforms.

Together with the fact that it separates completely HTTP handling from GraphQL, which means that we don’t need to handle starting/shutting down the server as we just need a Yoga instance alongside a Koa middleware to handle graphql requests in strapi’s use case

**Ecosystem**

GraphQL Yoga 3.0 is built on top of [Envelop Plugins.](https://github.com/parse-community/parse-server/issues/envelop.dev)

That means you can use the whole [plugin ecosystem of Envelop](https://www.envelop.dev/plugins), including rate limiting, caching, Auth, tracing and monitoring, and basically any feature GraphQL servers in production need.

**Real time and future-spec features**

GraphQL Yoga 3.0, has up to date, fully typed GraphQL Subscriptions implementation.

In addition to that, we added the ability to use GraphQL Live Queries, which has the potential to make Parse's own live queries more ergonomic for developers.

Also, you get of course the official GraphiQL 2.0 out of the box (which is back to being maintained by many GraphQL Foundation companies).

Untitled 1

**Performance**

GraphQL Yoga 3.0 has significantly less latency and a much higher requests rate.

You can find the actual numbers on this [3rd party benchmark](https://github.com/graphql-crystal/benchmarks/runs/6175900826?check_suite_focus=true)

Untitled 2

**Less memory footprint**

Regarding memory footprint, we don’t run official benchmarks specifically for that. However, according to our high-scale clients running across all the environments I’ve mentioned above, the costs of maintaining servers are lower after migrating.

If you have specific scenarios or benchmarks we can use, please let me know and we'll add that to our CI as well.

**Fewer dependencies**

I would check both the number of dependencies and the overall bundle size when evaluating library dependencies. Because Bundle Size matters when you are running your servers in certain environments (because of cold starts).

You can find the comparison for bundle sizes and the number of dependencies below:
[https://bundlephobia.com/package/apollo-server@3.6.7](https://bundlephobia.com/package/apollo-server@3.6.7)
[https://bundlephobia.com/package/@graphql-yoga/node@2.3.0](https://bundlephobia.com/package/@graphql-yoga/node@2.3.0)

Untitled 3

**Compatibility with advanced usages from an apollo/client?**

GraphQL Yoga 3.0 supports any feature of Apollo Client, Relay, Urql, react-query and any GraphQL client out there.

**Compatibility with Apollo Federation?**

GraphQL Yoga 3.0 not only officially supports the Federation spec as a subgraph, but also can act as the Apollo Gateway server.
With GraphQL Yoga 3.0 you can use Apollo Federation together with all 
the plugins of Envelop, so you can benefit from both ecosystems:
[https://www.graphql-yoga.com/docs/features/apollo-federation](https://www.graphql-yoga.com/docs/features/apollo-federation)

**GraphQL Playground for backward compatibility?**

We know how annoying it can be to force every single Strapi user to use GraphiQL 2.0, even though we think it’s better. GraphQL Playground is still gonna be the default browser IDE and GraphiQL can be enabled through this option:

```jsx
// config/plugins.js
module.exports = () => ({
  graphql: {
    enabled: true,
    config: {
			...,
      browserIDE: 'graphiql',
    },
  },
```

You can find more information about the comparison here: [https://the-guild.dev/graphql/yoga-server/docs/comparison](https://the-guild.dev/graphql/yoga-server/docs/comparison)

### Nexus → Pothos GraphQL

So, [Pothos](https://pothos-graphql.dev/) is also a code-first GraphQL schema library.

The main differences between Nexus and Pothos are that Pothos has a very powerful plugin system, its typesafety DX is amazing, has no code generation, and most importantly, it is very actively maintained and in a much better shape than Nexus.

## Note

This's still a work in progress, so unexpected behaviors, some failing tests, and some unorganized code are currently expected. but no worries we plan to polish it as best as we can!

## Summary

We love open source projects and want to do the best we can to support them.

All the suggestions above are just suggestions.

We could turn each one of them into separate PRs and go all the way like we’ve already done in our branch.

We would love to offer you a shared Slack channel with The Guild (for free of course).

You can ask any question you have there about GraphQL, even if you would choose to not take any of our suggestions 🙂

Also, we would love to hear any improvements the community wants to do on the GraphQL API and help with that.

Thank you for the wonderful system you’ve built and for making it open source! ❤️

### CODE REVIEW

**Comment by joshuaellis** [comment]
<3

**Comment by iCarossio** [comment]
🤩

**Comment by alexandrebodin** [comment]
Hi @YassinEldeeb  thank you for making such a big contribution. Sadly as you can see this is not something we are capable of accepting (breaking changes) or reviewing as is. We would need this to be split in smaller steps and 1st validated through and RFC process :) 

Happy to discuss how we could move forward with it. Be aware though that we will probably do big refactoring in the upcoming months so I wouldn't want you to work on something if we change a lot anyway.

**Comment by Urigo** [comment]
@alexandrebodin we would love to split it into smaller changes and RFCs.

The description in this PR is many RFCs together, can you just go through the description and let us know which RFCs you would like us to open, where and how and we'll go ahead and open them

Good luck with the big refactoring and just let us know when you are ready.

In the meantime if you want to open a shared Slack channel for @the-guild-org and Strapi so we can answer any questions related to GraphQL in general, let me know and I'll send over an invite for the Strapi team!

**Comment by alexandrebodin** [comment]
Hi @YassinEldeeb  I'm going to close this PR as we are moving toward v5. A lot of the proposal are interesting and we might implement some of them there. If you are interested in participating let us know 💯

**Comment by Urigo** [comment]
Hi @alexandrebodin and thank you for looking and reviewing the proposals.
We would love to help and participate in helping!
What would be the best way?
Should we schedule a meeting? Maybe a shared Slack channel with @the-guild-org?

**Comment by alexandrebodin** [comment]
A bit early to say for now. As soon as we have something to share I'll ping you here to see how we can provide guidance :)

**Pull request closed without merging**
