### PR TITLE
remove react-select from RW & ban with ESlint

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* Bans importing react-select from the helper-plugin
* Converts the review-workflow usage to DS components

### Why is it needed?

* We don't need RS

### Related issue(s)/PR(s)

* part of CONTENT-813

### CODE REVIEW

**Comment by jhoward1994** [comment]
Looks good, I'm seeing a couple of bugs in the RW settings page though

- If you remove the value the call to .toUpperCase fails
- The select initially appears to offer all options but you can't seem to select them, it defaults back to the value that is typed

I think it would make sense if the combobox wasn't type-able or clearable as we only have a set of color options. wdyt?


https://github.com/strapi/strapi/assets/48524071/1955f5ba-1e7c-443a-b8ae-1867e63efa87

**Comment by joshuaellis** [comment]
> I think it would make sense if the combobox wasn't type-able or clearable as we only have a set of color options. wdyt?

I'd agree to be honest, we don't support custom options and we allow `typeahead` so does it have any value – might wanna check with @maevalienard ?

**Comment by maevalienard** [comment]
Works for me!

**Comment by joshuaellis** [comment]
@jhoward1994 made those changes 👍🏼

**Comment by jhoward1994** [comment]
Hmmm for me the stage test is still broken and unable to assert that the value is blue. Is it working for you? @joshuaellis

**Comment by joshuaellis** [comment]
No it's not, it's weird cause it knows the default value but it won't assign it - I'm looking into it 😊

**Comment by joshuaellis** [comment]
> No it's not, it's weird cause it knows the default value but it won't assign it - I'm looking into it 😊

found it, really dumb mistake.

**Review by jhoward1994 — APPROVED** [review]

**Pull request merged**
