### PR TITLE
add strapi  helm chart 

### PR DESCRIPTION
**Pull request by geekette86**
#### Description of what you did:
Add helm chart of strapi to the strapi base repo

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
I'm not sure I understand the goal of this PR?

**Comment by geekette86** [comment]
I added helm chart, it means this will make it easy for every one who want
to deploy strapi on kunernetes

**Comment by derrickmehaffy** [comment]
@geekette86 I'm not sure that is something that should be in the mono-repo as it's not used for projects but is maintaining all the core source code for Strapi packages. This might better be something directed at https://github.com/strapi/community-content

**Comment by geekette86** [comment]
okay great

**Comment by derrickmehaffy** [comment]
Marking as closed as this PR shouldn't be in the mono-repo

**Comment by stevek-pro** [comment]
Why don't you want to officially suppport a mature and well maintained helm chart officially as it is done by myriads of similar projects?

**Comment by derrickmehaffy** [comment]
> Why don't you want to officially suppport a mature and well maintained helm chart officially as it is done by myriads of similar projects?

Because this 8s a monorepo of many different packages deployed to npm by lerna. We already have a helm chart plugin developed by our community.

**Pull request closed without merging**
