### PR TITLE
fix(ctb): Refactor data-fetching to use react-query

### PR DESCRIPTION
**Pull request by gu-stav**
### What does it do?

Refactors the data-fetching logic in the CTB data manager provider to use react-query. It also makes `formatAPIError` a stable reference.

### Why is it needed?

Fixes a bug outlined in https://github.com/strapi/strapi/issues/17812. It seems that now we aren't unmounting pages as often anymore, which leads to stable references and therefore stale data.

### How to test it?

- Create / Delete / Update content-types (single + multiple)
- Create / Delete / Update components (new + existing categories)

### Related issue(s)/PR(s)

- Fixes https://github.com/strapi/strapi/issues/17812

### CODE REVIEW

**Comment by markkaylor** [comment]
Create and update look good on collection types and single types but I have a weird behavior on delete (although it does seem to delete):


https://github.com/strapi/strapi/assets/26598053/b1775a92-69d5-4f7b-8f33-2036b56ccc62

For components it doesn't look like I'm able to edit the component after creating it. Delete also has a strange behavior a bit different from content types. Also it doesn't look like the category is being added to the component.


https://github.com/strapi/strapi/assets/26598053/77d07d79-a760-4e62-bd10-0cbb39e2b423

**Comment by gu-stav** [comment]
Moving this PR back into draft, as there are two issues left which I don't fully understand yet and which are hard to debug: https://strapihq.slack.com/archives/C010V90JYN4/p1693294711228739

To not block the upcoming release we will revert the initial refactoring instead.

**Comment by alexandrebodin** [comment]
Hey do we keep this or will it be addressed during v5 ?

**Comment by gu-stav** [comment]
> Hey do we keep this or will it be addressed during v5 ?

The problem needs to addressed before we can move to react-router@6 so I'd leave it open for now.

**Pull request closed without merging**
