### PR TITLE
Fix broken MongoDB information links

### PR DESCRIPTION
**Pull request by derrickmehaffy**
### What does it do?

Updated links to forum thread about MongoDB

### Why is it needed?

Links did not include the trailing thread ID so when the thread name changed the links became broken

### How to test it?

N/A

### Related issue(s)/PR(s)

N/A

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
This pull request has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/mongodb-compatibility-delayed-on-v4/4549/111

**Review by soupette — APPROVED** [review]
LGTM

**Comment by alexandrebodin** [comment]
There is already this PR https://github.com/strapi/strapi/pull/10506 @derrickmehaffy

**Comment by alexandrebodin** [comment]
Closing as I merged the initial PR

**Pull request closed without merging**
