### PR TITLE
hide move button in Media Library

### PR DESCRIPTION
**Pull request by nitinmadelyn**
### What does it do?

In Media Library, while selecting the Assets/Folders there are two action buttons `Delete` & `Move`. When we try to perform move action then on the Move Element popup we might get an error if we try to move an items to the same root Folder. See screenshot below:

Screenshot 2023-07-10 at 12 20 31 PM

### Why is it needed?

In order to prevent above error I've hide the move button in the case where move action can't be performed. Here are some cases when move button is not needed. All cases are within the root folder of the Media Library.

1. When we try to move an Assets where there's no Folder.
2. When we try to move Folder to another Folder, but we only have 1 Folder. 
3. When we try to move all Folders + all Assets.

### How to test it?

- Login to admin.
- Go to Media Library.
- Try all above cases mentioned above.

### Related issue(s)/PR(s)

No related issue for this PR.

### CODE REVIEW

**Review by joshuaellis — CHANGES_REQUESTED** [review]
I'm not sure about this solution, the code feels very messy for what it is, also I don't agree with hiding buttons when you can't do actions imo we should just disable it.

**Comment by nitinmadelyn** [comment]
@joshuaellis that sounds like a good one, hiding the button will make some confusion for the users. I'll be happy to make the button disabled instead of hiding them. Please do let me know your final decision.

**Comment by joshuaellis** [comment]
> we should just disable it.

**Comment by alexandrebodin** [comment]
> [!IMPORTANT] 
> With the release of Strapi 5, we have lifted the code freeze. To ensure we can effectively review and assist with contributions, we are now only accepting PRs targeting version 5 (the develop branch).<br/> 
> As your PR targets version 4, it has been automatically closed. However, we would greatly appreciate it if you could update your contribution to align with version 5 and resubmit!

**Pull request closed without merging**
