### PR TITLE
Ignore build folders in admin & plugins

### PR DESCRIPTION
**Pull request by abdonrd**
From **1375 files** to **739 files** to stage in the initial commit. 🎉 
And I can't find the `analytics` plugin to do the same.

Also:
* Remove some unused `.npmignore` inside `admin` folders.
* Ignore `strapi-plugin-users-permissions/config/actions.json`.
* Standar `.gitignore` across plugins.

### CODE REVIEW

**Comment by abdonrd** [comment]
Applying these changes to a work in progress project...

screen shot 2018-02-27 at 10 14 47

**Comment by lauriejim** [comment]
Look really really nice ! I have to try it for `npm publish`. If every thing I want still published.

**Comment by abdonrd** [comment]
Related to this... If I have all the `build` folders ignored. When I want to create them, how should I do? For example, when a friend clones the repository the first time.

I have tried with:

```
npm install
npm run setup
```

But it only generates the admin build, and not the plugins build.

**Comment by abdonrd** [comment]
I just read in a Slack message:

```
npm run setup --plugins
```

**Comment by abdonrd** [comment]
We should add the `plugins/users-permissions/config/actions.json`, right?
It is an automatically generated file.

**Comment by Aurelsicoko** [comment]
We should definitely add it to the ignored files!

**Comment by abdonrd** [comment]
@Aurelsicoko done! 😄

**Comment by abdonrd** [comment]
@lauriejim @Aurelsicoko something more to be able to merge this PR?

**Comment by lauriejim** [comment]
@abdonrd I have to test it with our deployment process cause these files are critical for publishing on npm.
Test is take many times and I'm actually working on wysiwig with @soupette . 
I will try it before the end of the week.

**Comment by abdonrd** [comment]
Ok, thanks! 👏

**Comment by lauriejim** [comment]
Hey @abdonrd today I took time to test your code and that confirm my doubts.

Your update remove admin build folders on npm. Where there is a gitignore, npm use it as npmignore file so it's ignore admin build in `strapi-admin/admin` for example.
So you have to create empty npmignore file where you have a gitignore to not omit build.

We have to send it on npm to not make the entire build when someone install strapi.

To be sure your code work as expected I use this process to test https://blog.strapi.io/testing-npm-package-before-releasing-it-using-verdaccio-and-ngrok/ (without ngrock in first time)

Publish process of Strapi:
1. run `npm run setup` to be sure the local setup is ok
2. update `package.json` version to `11.2` and run `npm run clean` (to apply the new version to all packages)
3. run `TAG=alpha npm run release`
4. Then install the strapi version you just publish `npm i strapi@alpha -g` and test `strapi -v` is `alpha.11.2`
5. Play with the admin and each plugins to be sure all build works fine.

**Comment by abdonrd** [comment]
@lauriejim thanks for the feedback! 👏 

> We have to send it on npm to not make the entire build when someone install strapi.

Why send the build to npm? I thought that run the build after the installation was the best option.

**Comment by lauriejim** [comment]
If we don't send build, we have to did it on npm installation and it's not really cool to run npm install strapi and wait a long time for the build.

That is why. The experience is more fluent if we send build on npm.

**Comment by abdonrd** [comment]
@lauriejim so you also recommend that we keep the builds in git? 😕

**Comment by lauriejim** [comment]
Nop, but as you said in your issue, you have to rebuild admins after a git pull.
Have to discuss with @Aurelsicoko about this point.

**Comment by abdonrd** [comment]
@lauriejim I will wait for the https://github.com/strapi/strapi/issues/798 discussion.

**Comment by Aurelsicoko** [comment]
I added my contribution to the discussion. It's a very sensitive part for us. We need to take our time.

**Comment by Aurelsicoko** [comment]
@abdonrd What's the state of this PR? We found an agreement in this issue https://github.com/strapi/strapi/issues/798. We don't have enough time to make the changes shortly.

**Comment by abdonrd** [comment]
We can close it, and create new PRs for:

- https://github.com/strapi/strapi/issues/822
- https://github.com/strapi/strapi/issues/824
- https://github.com/strapi/strapi/issues/823

**Pull request closed without merging**
