### PR TITLE
Feature/graphql disable plugins

### PR DESCRIPTION
**Pull request by pimsomeday**
### What does it do?

It adds an option to the Graphql Plugin settings to disable specified plugins and extensions from being added to the generated graphql-schema.

### Why is it needed?

This way we can prevent collisions if we want to stitch the graphql-schemas from multiple Strapi instances. 

For example, in Hasura we would like to stitch two graphql-schemas (both from Strapi instances). This will return a not unique error because both Strapi instances will add by default the typeDefs and resolvers defined in the Users Permissions- and Upload plugin.

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hello. For now this change is not going to be under consideration yet. 

Since you are using schema stitching, Have you considered using schema merger or transforms to remove duplicates when you are building your stitch with graphql-tools ?

**Comment by pimsomeday** [comment]
@alexandrebodin We are using [Hasura](https://hasura.io/) and unfortunately we don't have control on how the schemas are stitched. 

Do you have any other solutions in mind to have more control over the schema? Right now the users-permissions and upload plugins are causing collisions.. (and there is no way to turn them off or hide them from being loaded in the schema)

**Comment by alexandrebodin** [comment]
Hi @pimsomeday without investigating and testing the first idea that comes to mind would be to create a custom graphql route on one of the instances that will do the stitching with graphql-tools so you can then use hasura on top of it. does that make sense ?

**Comment by pimsomeday** [comment]
@alexandrebodin I got your point, but then we have to create an extra layer in our infra: [strapi instances] => [schema stitcher] => [hasura] (which is a bit redundant). In the meanwhile I created [a PR](https://github.com/strapi/strapi/pull/9010) to be able to override all the resolvers (and not only the ones from the shadowCRUD). It's a less aggressive approach then disabling the whole plugin ;) but this way I can prevent collisions as well. I hope you guys like it!

**Comment by alexandrebodin** [comment]
going to close this one in favor of https://github.com/strapi/strapi/pull/9131 :) Thank you for contributing 💯

**Pull request closed without merging**
