### PR TITLE
Use actual hash instead of randomly generated string

### PR DESCRIPTION
**Pull request by jskorepa**
My PR is a:

💅 Enhancement

Main update on the:

Plugin

Hash field in upload plugin was not actual hash but instead was randomly generated string. I replaced it with sha256 digest which is then encoded as base64 because it is shorter that hex. And I use different more URL-friendly character set for the encoding.

### CODE REVIEW

**Comment by Aurelsicoko** [comment]
@jskorepa What happens if I upload twice the same file? There is nothing random in your niceHash() method. I tested it and it generates the same hash... You should add something which is random. That's why we choose UUID before it generates a unique hash and there is no way to have a collision.

**Comment by jskorepa** [comment]
@Aurelsicoko That's partially the point. If someone uploads same file it is stored only once.

But that is not use case I was aiming for. I have a script which feeds data into strapi. This script needs efficient way to know if file in strapi is the same as it has locally - I wanted to achieve this using the hash but found out that it is not actually a hash. So for this use case I am fine with generating random filename for example with the UUID.

So I can modify my pull request to generate random filename and save hash to the database, but I thought that file deduplication is nice side-effect. But as I think about it - the delete button in administration deletes the file as well as the record in database, so if two files have same filename one deletes the other.

I will send modified pull request which will save with random filename (using uuid), but provide stable hash in the API.

**Comment by jskorepa** [comment]
@Aurelsicoko Not it behaves same as previously but also has new field name sha256 which contains the hash.

**Comment by jskorepa** [comment]
To clarify: by previously I mean before any changes I made

**Comment by Aurelsicoko** [comment]
Yes, you're right it has a nice side-effect 🙈 

LGTM, thank you for the PR 👍

**Pull request merged**
