### PR TITLE
Fix for UPPERCASE / camelCase names

### PR DESCRIPTION
**Pull request by EpicUsaMan**
#### Description:

Fix for UPPERCASE / camelCase names in "model" or "collection" field when generate documentation

#### My PR is a:
- [ ] 💥 Breaking change
- [x] 🐛 Bug fix 
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:
- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [x] SQLite

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello @EpicUsaMan !

Can you give us the way to reproduce the issue you fix please.

**Comment by EpicUsaMan** [comment]
@lauriejim 
Pre conditions:
1. Installed documentation plugin
2. Two api exists

STR:
1. Create model in firstApi like `featureKey`
2. Create second model in secondApi like `feature`
3. Add relation between feature and featureKey (one-way) (feature -> featureKey)
4. Run strapi via strapi start

**Comment by derrickmehaffy** [comment]
@EpicUsaMan case model names aren't supported https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#model--field-naming-schemes

**Comment by EpicUsaMan** [comment]
@derrickmehaffy Okay, but some steps to support it can be implemented, based on description from your link :)

So I implement it.
Maybe merge it like enchancement, not as.bug fix?

**Comment by derrickmehaffy** [comment]
@EpicUsaMan they do plan to support it in the future, but I have a feeling that this patch may break some peoples projects who have used work arounds.

**Comment by EpicUsaMan** [comment]
@derrickmehaffy  any plugin update breaks workaround in updated plugin ;)

**Comment by soupette** [comment]
Well for the moment we don't support camelCase api so I'd say it's ok for me...

**Pull request merged**
