### PR TITLE
Add nvm config file

### PR DESCRIPTION
**Pull request by thelovekesh**
### What does it do?

Add config file for [NVM](https://github.com/nvm-sh/nvm/).

### Why is it needed?

- Having a `.nvmrc` file makes it helpful to dictate which node version is currently used for project development.

### How to test it?

- In the project root dir run `nvm install && nvm use`. 
- Check your node version by running `node -v`.
- Your current node version should be the same as defined in `.nvmrc` file.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Review by derrickmehaffy — APPROVED** [review]
Lgtm

**Review by gu-stav — COMMENTED** [review]
@thelovekesh Could you explain a little more which problem this solves for you? Honestly, I don't think we need this at the moment - it is documented which versions are supported and it is actually beneficial I'd say if several developers are running different versions of node.

**Comment by derrickmehaffy** [comment]
@gu-stav they had opened an issue about this a few days ago that closed as the issue was opened only to ask if they could submit a PR: https://github.com/strapi/strapi/issues/14520

**Review by joshuaellis — APPROVED** [review]
IMO this is helpful for local development because you can just run `nvm use`

Makes onboarding easier for contributors 😄

**Comment by gu-stav** [comment]
@joshuaellis I think it is healthy if we all run different versions of node - Strapi supports a range of versions and therefore features should be tested in different environments. I'm afraid defining one version will lead to less diversity in versions used, but if you all think merging this is ok, I won't object.

**Comment by joshuaellis** [comment]
> @joshuaellis I think it is healthy if we all run different versions of node - Strapi supports a range of versions and therefore features should be tested in different environments. I'm afraid defining one version will lead to less diversity in versions used, but if you all think merging this is ok, I won't object.

I think if we didn't have such a complex matrix of test suites i'd agree, but i have faith in the CI 👍🏼

**Pull request merged**
