### PR TITLE
feat: add en-US and en-GB localization (allowing use of respective date formats)

### PR DESCRIPTION
**Pull request by Christian-Schwarz2003**
### What does it do?

- I added a localization for en-GB and en-US,
- It allows the use of DD/MM/YYYY date format (by using en-GB)
### Why is it needed?

This is useful to people who use the DD/MM/YYYY system on a daily basis and mistakenly switch month and day around

### How to test it?

- Add "en-GB" and "en-US" to the locales in the admin panel config
- View any entry that has a date format

yarn test:front

### Related issue(s)/PR(s)

- https://github.com/strapi/strapi/issues/12216 / https://feedback.strapi.io/customization/p/option-to-change-the-date-format-in-the-admin-dashboard
- old v4 PR: https://github.com/strapi/strapi/pull/20563

### CODE REVIEW

**Review by alexandrebodin — COMMENTED** [review]
Hi @Christian-Schwarz2003  I'm not sure I see any diff between the "en" and "en-US" ?

I'm gonna give it a try but I wonder if we can find a way to avoid all the repetion by have "overrides" instead 🤔

**Comment by Christian-Schwarz2003** [comment]
Hi @alexandrebodin, you're right there is no difference, I thought some people could be confused if there was just en and en-GB. If you want me to I can just remove en-US.
Overrides would be nice though.
Also would be nice if there was a explicit time format override.

**Comment by alexandrebodin** [comment]
Hey @Christian-Schwarz2003  I found a nice approach to avoid the extra copy pasting. I wanted to push but your repo doesn't accept it. Could you give me the right access please 🙏

**Comment by alexandrebodin** [comment]
Ok I did a wrong command Let me reopen a PR 🤦  sorry about that

**Comment by alexandrebodin** [comment]
Here is the new PR. I kept your commits so we can be co-authors 🙇 

Thank you!

**Comment by matumartin14** [comment]
Any updates on this?

**Pull request closed without merging**
