### PR TITLE
Fix relations for shortened contentTypes

### LINKED ISSUE #20886: Really long content-types with relations throw error on finding relational linking table
## Bug report

### Required System information

- Node.js version: v20
- NPM version: v10
- Strapi version: 5.0.0-rc.7
- Database: SQLite
- Operating system: Linux Mint 21.3
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When creating two content-types with really long names and then trying to create a relational link between them an error is thrown when Strapi tries to find the middle joining table

### Steps to reproduce the behavior

1. Create a content-type using the name `this-is-a-really-really-really-long-content-type-name`
2. Create another content-type using the name `this-is-a-really-really-long-relational-content-type-name`
3. Add a manyToMany relationship to the first one, pointing at the second one
4. See error:

```
⠧ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                                                                                                     │
│   SqliteError: create index `this_is_a_really_rea8ed46_this_is_a_really_rea553cd_ofk` on `this_is_a_really_rea8ed46_this_is_a_really_reae3630_lnk` (`this_is_a_really_really_long_relational_contene070a_ord`) - no such column:    │
│   this_is_a_really_really_long_relational_contene070a_ord                                                                                                                                                                           │
│   at Database.prepare (/mnt/storage/Development/testlongnames/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)                                                                                                             │
│   at Client_BetterSQLite3._query (/mnt/storage/Development/testlongnames/node_modules/knex/lib/dialects/better-sqlite3/index.js:35:34)                                                                                              │
│   at executeQuery (/mnt/storage/Development/testlongnames/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)                                                                                                      │
│   at Client_BetterSQLite3.query (/mnt/storage/Development/testlongnames/node_modules/knex/lib/client.js:154:12)                                                                                                                     │
│   at /mnt/storage/Development/testlongnames/node_modules/knex/lib/execution/transaction.js:371:24                                                                                                                                   │
│   at new Promise (<anonymous>)                                                                                                                                                                                                      │
│   at trxClient.query (/mnt/storage/Development/testlongnames/node_modules/knex/lib/execution/transaction.js:366:12)                                                                                                                 │
│   at Runner.query (/mnt/storage/Development/testlongnames/node_modules/knex/lib/execution/runner.js:141:36)                                                                                                                         │
│   at Runner.queryArray (/mnt/storage/Development/testlongnames/node_modules/knex/lib/execution/runner.js:235:21)                                                                                                                    │
│   at Runner.queryArray (/mnt/storage/Development/testlongnames/node_modules/knex/lib/execution/runner.js:287:31)                                                                                                                    │
│                                                                                                                                                                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Done in 93.17s.
```

### Expected behavior

It should be able to find and construct the middle joining table name 

### Screenshots

![image](https://github.com/user-attachments/assets/7c105c28-431c-4da4-82b6-1afceacd034c)


### Code snippets

Content-Type 1 schema:

```json
{
  "kind": "collectionType",
  "collectionName": "this_is_a_really_really_really_long_content_type_names",
  "info": {
    "singularName": "this-is-a-really-really-really-long-content-type-name",
    "pluralName": "this-is-a-really-really-really-long-content-type-names",
    "displayName": "this is a really really really long content type name",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "test": {
      "type": "string"
    },
    "this_is_a_really_really_long_relational_content_type_names": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::this-is-a-really-really-long-relational-content-type-name.this-is-a-really-really-long-relational-content-type-name",
      "inversedBy": "this_is_a_really_really_really_long_content_type_names"
    }
  }
}
```

Content-Type 2 schema:

```json
{
  "kind": "collectionType",
  "collectionName": "this_is_a_really_really_long_relational_content_type_names",
  "info": {
    "singularName": "this-is-a-really-really-long-relational-content-type-name",
    "pluralName": "this-is-a-really-really-long-relational-content-type-names",
    "displayName": "this is a really really long relational content-type name"
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "test": {
      "type": "string"
    },
    "this_is_a_really_really_really_long_content_type_names": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::this-is-a-really-really-really-long-content-type-name.this-is-a-really-really-really-long-content-type-name",
      "mappedBy": "this_is_a_really_really_long_relational_content_type_names"
    }
  }
}
```

### Additional context

n/a

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?

- Adds column to orderColumn attributes that are shortened already to prevent us from attempting to shorten again

### Why is it needed?

- Many-to-Many and Many-to-one relations are broken for contentTypes that need to be shortened 
- orderColumn is being shortened twice

### How to test it?

- create a collectionName with more than 55 characters, and try to create a many-to-many relation with another contentType or Many-to-one, it should work successfully with no errors
- you can follow the related issue for reproduction and confirming the fix 

### Related issue(s)/PR(s)

DX-1500

improves #20886 but there is still an issue with migrations causing the relational data to be lost

### CODE REVIEW

**Comment by innerdvations** [comment]
When I start with a v4 database (`develop`) with long table and attribute names (for example, in sqlite) and switch to this PR, the migration loses the relation data. Can you see if we need to fix something in the migration too?

**Comment by Bassel17** [comment]
> When I start with a v4 database (`develop`) with long table and attribute names (for example, in sqlite) and switch to this PR, the migration loses the relation data. Can you see if we need to fix something in the migration too?

yep looked into this, seems to be a separate issue, we'd face the same with any contenttype that didn't have draft and publish enabled in v4 and going to v5, needs to be fixed but probably in a separate PR

**Comment by innerdvations** [comment]
Adding `don't merge` for now because this does fix the bug, but seems to change the situation from a "v4->v5 migration aborting", to "v4->v5 migration succeeding with data loss"

**Comment by Bassel17** [comment]
Found this issue #20948 during the QA on this PR
Turned out to be unrelated and exists on `v5/main`

**Pull request merged**
