### PR TITLE
fix: missing documentation custom setting

### PR DESCRIPTION
**Pull request by kayac-chang**
### What does it do?

There's a [settings section](https://docs.strapi.io/developer-docs/latest/plugins/documentation.html#settings), 
but doesn't implemented in source code.

### Why is it needed?

Custom settings should existed based on official website documentation.

### How to test it?

```sh
yarn strapi install documentation
echo '{ "hello": "world" }' > src/extensions/documentation/config/settings.json
yarn develop
```

### Related issue(s)/PR(s)
Related to [#12046](https://github.com/strapi/strapi/issues/12046).

### CODE REVIEW

**Review by cbleek — COMMENTED** [review]
works for me

**Comment by cbleek** [comment]
If no config file exists, an empty file is created. This makes the server fail to start. I had to write `{}` into the empty file to make the server starting again.

```
[2022-01-03 13:36:49.976] error: /home/strapi/backend/src/extensions/documentation/config/settings.json: Unexpected end of JSON input
SyntaxError: /home/strapi/backend/src/extensions/documentation/config/settings.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object._readFile (/home/strapi/backend/node_modules/jsonfile/index.js:25:16)
    at async Object.generateFullDoc (/home/strapi/backend/node_modules/@strapi/plugin-documentation/server/services/documentation.js:145:30)
    at async Object.module.exports [as bootstrap] (/home/strapi/backend/node_modules/@strapi/plugin-documentation/server/bootstrap.js:52:3)
    at async Object.bootstrap (/home/strapi/backend/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:7)
    at async Object.bootstrap (/home/strapi/backend/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:9)
    at async Strapi.runLifecyclesFunctions (/home/strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:463:5)
    at async Strapi.bootstrap (/home/strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:401:5)
    at async Strapi.load (/home/strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:410:5)
    at async Strapi.start (/home/strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:161:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kayac-chang** [comment]
> If no config file exists, an empty file is created. This makes the server fail to start. I had to write `{}` into the empty file to make the server starting again.
> 
> ```
> [2022-01-03 13:36:49.976] error: /home/strapi/backend/src/extensions/documentation/config/settings.json: Unexpected end of JSON input
> SyntaxError: /home/strapi/backend/src/extensions/documentation/config/settings.json: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at Object._readFile (/home/strapi/backend/node_modules/jsonfile/index.js:25:16)
>     at async Object.generateFullDoc (/home/strapi/backend/node_modules/@strapi/plugin-documentation/server/services/documentation.js:145:30)
>     at async Object.module.exports [as bootstrap] (/home/strapi/backend/node_modules/@strapi/plugin-documentation/server/bootstrap.js:52:3)
>     at async Object.bootstrap (/home/strapi/backend/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:7)
>     at async Object.bootstrap (/home/strapi/backend/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:9)
>     at async Strapi.runLifecyclesFunctions (/home/strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:463:5)
>     at async Strapi.bootstrap (/home/strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:401:5)
>     at async Strapi.load (/home/strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:410:5)
>     at async Strapi.start (/home/strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:161:9)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

Hello, should we create an empty file with `{}`?
or if we don't have custom config then just using default one. Thank you

**Comment by kayac-chang** [comment]
> I've replaced my node_modules/@strapi/plugin-documentation/server/services/documentation.js and now I get:
> 
> ```
> strapi@strapi:~/backend$ yarn dev
> yarn run v1.22.11
> $ strapi develop
> [2022-01-04 08:40:05.679] debug: ⛔️ Server wasn't able to start properly.
> [2022-01-04 08:40:05.680] error: Cannot access 'path' before initialization
> ReferenceError: Cannot access 'path' before initialization
>     at Object.generateFullDoc (/home/strapi/backend/node_modules/@strapi/plugin-documentation/server/services/documentation.js:119:28)
>     at Object.module.exports [as bootstrap] (/home/strapi/backend/node_modules/@strapi/plugin-documentation/server/bootstrap.js:55:6)
>     at async Object.bootstrap (/home/strapi/backend/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:7)
>     at async Object.bootstrap (/home/strapi/backend/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:9)
>     at async Strapi.runLifecyclesFunctions (/home/strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:463:5)
>     at async Strapi.bootstrap (/home/strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:401:5)
>     at async Strapi.load (/home/strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:410:5)
>     at async Strapi.start (/home/strapi/backend/node_modules/@strapi/strapi/lib/Strapi.js:161:9)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

That's because naming conflict, already fixed that, thank you.

**Comment by stafyniaksacha** [comment]
LGTM

**Comment by markkaylor** [comment]
Hi @kayac-chang ,

Thanks for your contribution. Everything looks good I just think you might be doing the merge a littler early. Some fields are set on the default settings after the merge so the custom settings aren’t taken into account, for example a custom `servers` array would be overridden with:

```javascript
_.set(settings, 'servers', [
  {
    url: `${serverUrl}${apiPath}`,
    description: 'Development server',
  },
]);
```

I think you could do something like this:

```javascript
const defaultSettings = _.cloneDeep(defaultConfig)
      
const serverUrl = getAbsoluteServerUrl(strapi.config);
const apiPath = strapi.config.get('api.rest.prefix');

_.set(defaultSettings, 'servers', [
  {
    url: `${serverUrl}${apiPath}`,
    description: 'Development server',
  },
]);

_.set(defaultSettings, ['info', 'x-generation-date'], new Date().toISOString());
_.set(defaultSettings, ['info', 'version'], version);

const customSettings = (await fs.pathExists(customConfigPath))
        ? await fs.readJson(customConfigPath)
        : {};
const settings = _.merge(defaultSettings, customSettings)
```

**Review by markkaylor — CHANGES_REQUESTED** [review]
Hi @kayac-chang ,

Thanks for your contribution. Everything looks good I just think you might be doing the merge a littler early. Some fields are set on the default settings after the merge so the custom settings aren’t taken into account, for example a custom `servers` array would be overridden with:

```javascript
_.set(settings, 'servers', [
  {
    url: `${serverUrl}${apiPath}`,
    description: 'Development server',
  },
]);
```

I think you could do something like this:

```javascript
const defaultSettings = _.cloneDeep(defaultConfig)
      
const serverUrl = getAbsoluteServerUrl(strapi.config);
const apiPath = strapi.config.get('api.rest.prefix');

_.set(defaultSettings, 'servers', [
  {
    url: `${serverUrl}${apiPath}`,
    description: 'Development server',
  },
]);

_.set(defaultSettings, ['info', 'x-generation-date'], new Date().toISOString());
_.set(defaultSettings, ['info', 'version'], version);

const customSettings = (await fs.pathExists(customConfigPath))
        ? await fs.readJson(customConfigPath)
        : {};
const settings = _.merge(defaultSettings, customSettings)
```

**Comment by alexandrebodin** [comment]
Hi @kayac-chang :) Just making sure it's in your inbox :)

**Pull request closed without merging**
