### PR TITLE
Fix/required field

### LINKED ISSUE #12198: [v4] Changes of required field in Content-Type Builder doesn't show in Content Manager
### Describe the bug

Changes of required field in Content-Type Builder doesn't show in Content Manager. 

### Steps to reproduce the behavior

1. Create collection type, for example, Category
2. Create text field "Subtitle" - not required.
3. Save the collection.
4. Create some entries of Category.
5. Come back to collection type and change field "subtitle" from "not required" to "required".
6. Open the page of creating new entry of Category
7. Observe the bug: the field of subtitle is not required

### Expected behavior

Changing the option from "not required" to "required" is saved.

It's repeatable problem with any content type in admin.

### Screenshots

Content-Type Builder: field is required

Content Manager: field is not required - the bug

### System

- Node.js version: 14.17.5
- NPM version: 6
- Strapi version: 4.0.4
- Database: SQLite
- Operating system: MacOS

### PR DESCRIPTION
**Pull request by ronronscelestes**
## What

- Bump DS to add required UI for:
  - ToggleInput
  - CarouselInput
  - Textarea
- Integrated required UI for the ones above + InputJSON

Thanks to @abdonrd and teinett (didn't manage to create the tag 🥲) for spotting those issues
Closes #12198

### CODE REVIEW

**Review by HichamELBSI — DISMISSED** [review]
LGTM

**Review by HichamELBSI — APPROVED** [review]
LGTM

**Review by HichamELBSI — APPROVED** [review]

**Comment by derrickmehaffy** [comment]
Don't forget to delete the merged branches :)

**Comment by ronronscelestes** [comment]
indeed sorry 🤦‍♀️

**Comment by derrickmehaffy** [comment]
> indeed sorry woman_facepalming

It's okay :) just helps keeps things clean. Usually the one who merges should delete. :wink:

**Comment by abdonrd** [comment]
> Don't forget to delete the merged branches :)

@derrickmehaffy You can automatically delete head branches from here:

https://github.com/strapi/strapi/settings#merge-button-settings

Screenshot 2022-02-01 at 23 55 34

**Comment by derrickmehaffy** [comment]
> > Don't forget to delete the merged branches :)
> 
> @derrickmehaffy You can automatically delete head branches from here:
> 
> https://github.com/strapi/strapi/settings#merge-button-settings
> 
> Screenshot 2022-02-01 at 23 55 34

I know, not sure why we won't have that enabled :see_no_evil:

**Pull request merged**
