### PR TITLE
Handle user not found error in email confirmation

### PR DESCRIPTION
**Pull request by WalkingPizza**
### What does it do?

Checks that a user exists before verifying whether it is confirmed or blocked in the `sendEmailConfirmation` method.

### Why is it needed?

Server throws an Internal Server Error with no details about why the error was thrown.

### Related issue(s)/PR(s)

#12344

### CODE REVIEW

**Comment by Mehrdad8800** [comment]
WalkingPizza:fix/up-email-confirmation-user-not-found

**Comment by alexandrebodin** [comment]
Hi, Instead of saying a user was not found I'm wondering if we should instead send a 200 response saying we will send an email if the user is found to avoid leaking if a user exists or not

**Comment by WalkingPizza** [comment]
> Hi, Instead of saying a user was not found I'm wondering if we should instead send a 200 response saying we will send an email if the user is found to avoid leaking if a user exists or not

This sounds much better than my initial approach.

Since the response/error formats in the U&P plugins are not very _standard_, I was wondering what exactly we should return.

I think since the objective is not leaking any information regarding the existence of the user, it might be smart to return something similar to the object that's being returned when the request is successful, hence something like `{ email: params.email, sent: true }`.

Do you think that'd work?

**Comment by alexandrebodin** [comment]
I like that idea to have a consistent format 👍

**Review by alexandrebodin — APPROVED** [review]

**Pull request merged**
