### PR TITLE
[v4] fix(plugin generator): support valid package names for pluginId

### PR DESCRIPTION
**Pull request by ComfortablyCoding**
### What does it do?

Updates the current replace regex to support both scoped package and old strapi plugin names.

### Why is it needed?

 Currently the generated plugins only support packages that are scoped under the strapi org. Most plugin developers are not creating any plugins under the strapi org (for obvious reasons) making it something every plugin developer needs to update.

### How to test it?

- Generate a plugin with a valid npm name
- Enable the plugin in config/plugins.js
- Start strapi
- Navigate to the plugin list section
- Observe that only the actual plugin name remains in the plugin list

Alternatively I have created some sample test at the following link: https://regexr.com/6dce9, unsure of how long it lasts.

### Related issue(s)/PR(s)

N/A

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
likely related to https://github.com/strapi/strapi/pull/11743

@strapi/backend I assume we won't accept this option either since it's intended we only allow loading `@strapi/*` with the shorthand?

**Comment by alexandrebodin** [comment]
This one could be accepted actually as it's just annoying when using the generators for a plugin.

**Review by markkaylor — APPROVED** [review]
Looks good to me!

**Comment by alexandrebodin** [comment]
@ComfortablyCoding Do you mind amending your code and pushing it again so github can run the checks?

**Comment by ComfortablyCoding** [comment]
Hi @alexandrebodin ,

Can you clarify what you mean by amending my code? When I attempt to amend the commit and repush it is adding a merge commit on top of the change commit. Is their some other way to do this? Not sure if its ok to pollute the commit history like that.

**Comment by derrickmehaffy** [comment]
> Hi @alexandrebodin ,
> 
> Can you clarify what you mean by amending my code? When I attempt to amend the commit and repush it is adding a merge commit on top of the change commit. Is their some other way to do this? Not sure if its ok to pollute the commit history like that.

Easiest way is to merge our master branch into yours again. Don't worry about the commit history since we squash merge

**Comment by ComfortablyCoding** [comment]
@derrickmehaffy , thanks. Merge completed and pushed.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy , thanks. Merge completed and pushed.

thank you, tests are running now :)

**Pull request merged**
