### PR TITLE
Showing local time in admin panel content manager

### LINKED ISSUE #2811: Date type fields (on Admin panel) are inconsistent with database's
### Informations
- **Node.js version**: 10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.22
- **Database**: PostgreSQL 10
- **Operating system**: Windows 10

**What is the current behavior?**
* Admin panel (11h slower, maybe it's displayed in UTC format):
  image

* Database GUI:
  image

> P.S. Here is Melbourne (AEDT, UTC+11)

**Suggested solutions**
Admin panel should respect the original data, or allow to set a default timezone.

### PR DESCRIPTION
**Pull request by derrickmehaffy**
#### Description of what you did:

Related PR: https://github.com/strapi/strapi/pull/3022

Thank you to @fattomhk for the initial PR, changes were made to reflect the Beta versions

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #2811 #2663
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [ ] MongoDB
- [x] MySQL
- [x] Postgres
- [x] SQLite

### CODE REVIEW

**Comment by soupette** [comment]
@derrickmehaffy I have tested your PR and it works with bookshelf however with mongoose it seems that the time is not working...
Here are some screenshots

**Created Entry**
Screenshot 2019-07-03 at 13 36 17


**Saved Entry**
Screenshot 2019-07-03 at 13 36 33

**Comment by derrickmehaffy** [comment]
@soupette figures lol, I admit this isn't my code.

**Comment by fattomhk** [comment]
@soupette  The format of "YYYY-MM-DD HH:mm:ss" should be fine to mongoose. Is the saved date correct in mongodb? 

ISODate

**Comment by derrickmehaffy** [comment]
> @soupette The format of "YYYY-MM-DD HH:mm:ss" should be fine to mongoose. Is the saved date correctly in mongodb?
> 
> ISODate

@soupette did you get an error while saving or is it just the format?

**Comment by soupette** [comment]
@derrickmehaffy, according to @alexandrebodin we will just send the stringified moment object and the backend will take care of the rest... We are planning to fix this issue with the upcoming new featutre.

**Comment by derrickmehaffy** [comment]
But you are still planning to add the code to convert from backend utc to user local time right?

**Comment by soupette** [comment]
Dates have been fixed in #3664 so I think it's better to wait for the PR to be merged since this one doesn't work with Mongo

**Comment by derrickmehaffy** [comment]
Closing as fixed in develop branch

**Comment by vlad320** [comment]
@derrickmehaffy Hello. Is this fix expected in version 16? 
I am confused that in "Manual testing done on the following databases" MongoDB is not specified. 
I am observing this problem now on version 15. MongoDB will remain without correction?


I display the incorrect display date after saving until I correct through the model by shifting the saved date.

**Pull request closed without merging**
