### PR TITLE
Nested zones

### PR DESCRIPTION
**Pull request by kibblerz**
### What does it do?

This PR enables the ability to use nested dynamic zones inside of components. 

### Why is it needed?

For complex layouts, and to make an easy editing experience for non technical users. This opens up significant possibilities in what can be achieved with content manager.

### How to test it?

Add a dynamic zone to your component via the component json file. Currently I have been unable to get the content builder to allow adding the zones (Maybe someone else can do that?). From my tests, all functionality is left in tact and the code change is minimal. 

Previous concerns I read about regarding this was how it could lead to a cramped UI. If that's still the major concern, I can adjust this PR so that nested zones show up in a popup Modal Window.

### CODE REVIEW

**Comment by gu-stav** [comment]
Thank you for opening this PR and your work! 🚀 We need to discuss the implications of this PR as a team first. I'll try to get back to you as soon as possible.

Could you in the meantime try to fix the failing tests please? 🙏🏼

**Comment by kibblerz** [comment]
@gu-stav Will do. I do have a plugin I'm currently building out that leverages these nested zones to create a page builder for react apps. It uses components and serialized them into MDX, which can then be parsed by a frontend like https://github.com/hashicorp/next-mdx-remote

So far it works quite well, I plan on publishing it if this is merged. I do believe it'll give quite an edge in the CMS space and make strapi a viable competitor to Wordpress. Not sure I've seen a headless CMS adequately implement a page builder so I think it'll be quite the hit.

**Comment by yanniskadiri** [comment]
Hey @kibblerz, we discussed this PR with the team and we'd like to wait before moving forward with it because we already removed the limit on nested components recently and we'd like to see what the impact is (especially on the UI). It might also help to solve your problem by the way ([here is the related PR](https://github.com/strapi/strapi/pull/13331)). Let me know.

For now, I will close this PR but we can reopen it later.

**Comment by kibblerz** [comment]
Can we consider implementing this again? The changes I implemented are rather basic, and after substantial testing, I have found no issues with them. 

You can already add a dynamic zone to a component (via editing the component configuration directly), but it breaks the admin. This PR would prevent the admin from being broken by it.  

We could avoid allowing dynamic zones to be added via content type builder if we want to limit the impact, so that it's only allowed when explicitly defined in the config.

**Comment by gu-stav** [comment]
@kibblerz would you have some time to talk to me about the issue on discord?

**Comment by kibblerz** [comment]
Sure, when would be a good time for you?

**Comment by ryanwspears** [comment]
Any update on this? A client of my company wants to have online courses on their site and a component=>repeatable dynamic zone=>component choice would be the most efficient content flow for them.

**Comment by derrickmehaffy** [comment]
Locking this as it relates to https://feedback.strapi.io/customization/p/dynamic-zone-in-components please keep votes, comments, etc there.

**Pull request closed without merging**
