### PR TITLE
GraphQL Subscriptions

### PR DESCRIPTION
**Pull request by fakedob**
Hello fellow strapi friends. I have finally found a moment to catch up with all the changes being made lately and was able to once again implement my GraphQL Subscription #3165 logic into the strapi graphql plugin core.
It has been really tough, since I am using strapi for more than two years now and whenever I had the time to migrate everything that I have in production, I had to start all over again, because a lot has already changed, but anyway.. Here it is - my fully featured subscriptions logic on top of the graphql strapi plugin.

This PR includes an extension to the ShadowCRUD, so that everything regarding the subscriptions gets generated into the schema automatically.
Basically, all subscription methods are attached to the lifecycle triggers of the models. As soon as they are enabled in the model configuration. For example, inside `/extentions/users-permissions/models/User.js` you can enable any of the events, by simply declaring it like:

`module.exports = {
  lifecycles: {
    beforeFind(params, populate){
      console.log('beforeFind')
    },
    afterFind(results, params, populate){
      console.log('afterFind')
    }
}`

Currently, all lifecycle triggers are available to use.
Every method, when being called, checks the corresponding access policy, matched with the hook as described [here](https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks)
Basically, if you enable (for example) update permissions to your content type, you will be able to subscribe to beforeUpdate[ContentType] and afterUpdate[ContentType] etc. Otherwise you will get a forbidden message.

Also, you have to supply a token to the connection params like so:
`connectionParams.authToken = '[your_token]'`
or
`Authorization = 'Bearer [your_token]'`

If you are testing with the playground, simply add
`{
  "Authorization": "Bearer [your_token]"
}` into the headers sections and replace the placeholder with the valid token you may have.

If you are using the Redis plugin (you have a config enabled), then the plugin will now get the messages distributed trough all your instances.

It is possible to use the WebSocket for queries and mutations, this is how I use strapi actually, but keep in mind that there are some more things to consider if you want to use it like that. You have to handle the login procedures and update the socket reference when logging in/out, since the connection stays open all the time, the token is being checked only once, when the connection is getting initialised.
You have to implement a way to handle your error messages and locales. 

So I hope you like it and have a great time while using it ✌️🥳

### CODE REVIEW

**Comment by fakedob** [comment]
Forgot to mention, if you want to add a custom subscription, create a schema.graphql.js file inside your component/config folder and use this sample code

```
module.exports = {
  subscription: `
    onCustomSubscription(channel: String): String
  `,
  resolver: {
    Subscription: {
      onCustomSubscription: {
        //Resolver is used to get access policy. Failing to provide one, will end with 401 Forbiden
        resolverOf: 'plugins::users-permissions.user.me',
        subscribe: async (obj, options, { context } ) => {

          let count = 0;

          setInterval(() => {
            strapi.graphql.pubsub.publish(options.channel, {
              onCustomSubscription: `Count: ${count}`
            });

            count ++;
          }, 1000);
          
          return await strapi.graphql.pubsub.asyncIterator(options.channel)
        }
      }
    }
  }
};
```

**Comment by derrickmehaffy** [comment]
So some small opinions here:

- I don't believe we should be using the Redis-hook package (as it hasn't been updated or reviewed in ages)
- Currently this implementation won't support Redis Clusters or HA Sentinel clusters (since it's only looking for a single host)
- I believe it would be better to directly pass-off the ioredis settings to the GraphQL config file and thus be able to be configured in the `config/plugins.js` similar to what is being done on the [community redis cache middleware](https://github.com/patrixr/strapi-middleware-cache) such as something similar documented here: https://github.com/patrixr/strapi-middleware-cache#example where you pass the object straight to the ioredis package thus allowing for much more customized configurations.

**Comment by derrickmehaffy** [comment]
Alternative to points 1 and 2, we also rework the Redis hook into a proper connector and take in the points from number 3 and make redis a "1st class citizen" again to be used by other plugins and middleware properly which I outlined here: https://github.com/strapi/strapi/discussions/3866

**Comment by alishshrestha** [comment]
how to implement where clause in afterCreate

**Comment by AdelShokry** [comment]
@fakedob 
when the collection Name camel case like userDetails subscription not work
how can i fix that

**Comment by derrickmehaffy** [comment]
Please keep comments on this PR about the PR and not help with using it. Thank you! :smiley:

**Comment by alexandrebodin** [comment]
Hi @fakedob Before reviewing this there are a lot of things to consider like derrick mentionned.

I think we should move to a discussion and a RFC to move forward with this.

**Review by vasilGerginski — APPROVED** [review]
Works on my machine

**Comment by derrickmehaffy** [comment]
I'm going to mark this as closed unless @fakedob can pick this back up and make the requested changes. If someone else wants to take over this PR please feel free.

**Comment by RizanPSTU** [comment]
How to use it? I am not able to run the graphql subscription :(. Can anyone help me?

**Comment by darron1217** [comment]
I'm planning to test this feature next week.
I hope more people are interested in this feature.

**Comment by AdelShokry** [comment]
> I'm planning to test this feature next week.
> I hope more people are interested in this feature.

very interested
I tried before, but I got no results

**Comment by SalahAdDin** [comment]
> I'm planning to test this feature next week.
> I hope more people are interested in this feature.

How can we test this?

**Comment by derrickmehaffy** [comment]
This PR is very old and was never merged due to other requirements that haven't been met/added. Strapi currently doesn't support Subscriptions.

**Comment by flaki** [comment]
If anyone wants to play around with this PR, I do have a version that works.

**Fair warning: this is unsupported, undocumented, and may very well eat your laundry. Don't use this in production.**

With that out of the way, you can replace the built-in `strapi-plugin-graphql` to get subscription endpoints by using this: https://github.com/flaki/strapi-plugin-graphql

It is pretty much just the plugin good fakedob started above, updated to 3.6.0.

**Comment by SalahAdDin** [comment]
> If anyone wants to play around with this PR, I do have a version that works.
> 
> **Fair warning: this is unsupported, undocumented, and may very well eat your laundry. Don't use this in production.**
> 
> With that out of the way, you can replace the built-in `strapi-plugin-graphql` to get subscription endpoints by using this: https://github.com/flaki/strapi-plugin-graphql
> 
> It is pretty much just the plugin good fakedob started above, updated to 3.6.0.

any plan to make a new pull request?

**Comment by flaki** [comment]
I'm not planning to clean this up (and it *does* very much need clean up).
This patched plugin is meant to be a stopgap solution for one of our projects that we already have plans to move away from the Strapi/GraphQL-based realtime management into its own separate component.

That said, I'll be keeping the patched plugin up to date until we do so and you are welcome to use it (again, without any warranties, see above).

If it would make sense and the Strapi team is not already working Subscriptions support for e.g. 4.0 (@derrickmehaffy?) and someone wants to do the work of cleaning the code up and seeing this through to be RFC-d and merged, you are welcome to do so.

**Comment by derrickmehaffy** [comment]
> If it would make sense and the Strapi team is not already working Subscriptions support for e.g. 4.0 (@derrickmehaffy?) and someone wants to do the work of cleaning the code up and seeing this through to be RFC-d and merged, you are welcome to do so.

@flaki not in the initial release of v4 but the changes being made to GraphQL certainly are moving in the direction of eventually adding it.

**Pull request closed without merging**
