### PR TITLE
Fixing issue #11044

### PR DESCRIPTION
**Pull request by Eventyret**
### What does it do?

Describe the technical changes you did.
Bumped version of `mongoose` in `packages/strapi-connector-mongoose/package.json` to `5.13.7` fixing #11044
Bumped also a version of `strapi-connector-mongoose` by patch `3.6.9`

### Why is it needed?

Fixing #11044 [Prototype Pollution Vuln](https://snyk.io/vuln/SNYK-JS-MONGOOSE-1086688)

### Related issue(s)/PR(s)

#11044

### CODE REVIEW

**Comment by aksdevac** [comment]
Hi @Eventyret, this does not update version in yarn lock file: https://github.com/strapi/strapi/blob/master/yarn.lock#L13853, like some dependabot PR(s).

**Comment by Eventyret** [comment]
I'll get that updated

**Comment by Eventyret** [comment]
@aksdevac  i think we need to get the `strapi-connector-mongoose` published again then to make `yarn` and package-lock` get updated?

**Comment by aksdevac** [comment]
Hi @Eventyret it seems it also updated **sharp** dependency in lock file. may be because after this [commit](https://github.com/strapi/strapi/commit/d018999fe1d2e7bd038d502d26f0cf07f578115b#diff-8c57b68bff7febb43001a4cd7a666a63ba0ad6db47e933df071bd8efbcb97392) lock file was not updated.
I think @alexandrebodin can give more information about correct way for dependency update.

**Comment by kasonde** [comment]
Hi @Eventyret as we are currently in the middle of a PR freeze, I'll close this PR here. The engineering team will be able to see though however and if they feel it's something they can incorporate, they will proceed to reopen, review and merge the fix.

**Pull request closed without merging**
