### PR TITLE
CM: Replace custom State and Badge components with Status

### PR DESCRIPTION
**Pull request by gu-stav**
### What does it do?

- Replaces the custom `State` component in the CM list view with a default component `Status` from the design-system.

| Before | After |
|-|-|
| Screenshot 2022-11-03 at 15 36 58 | Screenshot 2022-11-03 at 15 36 46 |

- Replaces `Badge` with `Status` in `RelationItem`

| Before | After |
|-|-|
| Screenshot 2022-11-03 at 15 37 32 | Screenshot 2022-11-03 at 15 37 59 |

### Why is it needed?

To keep the styling consistent across the app.

#### Todo

- [x] Wait for the [design-system 1.26 release](https://github.com/strapi/strapi/pull/14773)

### Related issue(s)/PR(s)

- https://github.com/strapi/design-system/pull/747
- https://github.com/strapi/design-system/pull/734
- https://github.com/strapi/strapi/pull/14773

### CODE REVIEW

**Review by joshuaellis — APPROVED** [review]
This resolves a Jira ticket right?

**Comment by gu-stav** [comment]
@joshuaellis https://strapi-inc.atlassian.net/browse/CONTENT-651 and implements some prep work for D&P v2 too, which isn't part of a ticket yet. What's better than creating a ticket? Making sure we never have to create one :p

**Comment by joshuaellis** [comment]
pre-cognative tickets

**Review by maevalienard — APPROVED** [review]
This makes me really happy 😂 Looks good to me, thank you very much!

**Pull request merged**
