### PR TITLE
Changed plugin description: more helpful text

### PR DESCRIPTION
**Pull request by cwray-tech**
#### Description of what you did:
The marketplace area in the cms shows this text, so I thought this would be a little more helpful than the default text. I updated it.

### CODE REVIEW

**Comment by MattieBelt** [comment]
Nice, what about the other plugins (eg. `email`, `graphql`, `upload`) and some providers? :wink:

**Comment by cwray-tech** [comment]
@MattieBelt YES working on it. most of the others have a decent description. (:

**Comment by cwray-tech** [comment]
@MattieBelt  should I put that into this same pull request?

**Comment by MattieBelt** [comment]
Yes that's fine, `email` and `upload` also have `This is the description of the plugin.` as description.

**Comment by alexandrebodin** [comment]
Hi, this PR contains conflicts since the latest release. Do you mind updating it ?

**Comment by cwray-tech** [comment]
Hey Alexandre,
Absolutely! I will try to do that today if I get the chance.

________________________________

**Comment by cwray-tech** [comment]
@alexandrebodin I'm sorry this is taking me forever. I had deleted my fork & branch of this. Is there a way for me to fix this conflicts easily?

**Comment by alexandrebodin** [comment]
Hi, I don't see another method than the classic update of your branch and pulling the upstream master into your branch so you can fix the conflicts :/

**Comment by alexandrebodin** [comment]
Otherwise you can open a new PR but we are going to make a new release soon and change the versions again so maybe wait a bit for this :)

**Comment by cwray-tech** [comment]
Haha ok I may wait and just open a new PR. You know when that new version will hit?

Chris Wray
Software Dev
https://chriswray.dev
________________________________

**Comment by cwray-tech** [comment]
Closed as I opened another pr with these changes and an updated branch.

**Pull request closed without merging**
