### PR TITLE
Add Hindi translation

### PR DESCRIPTION
**Pull request by AnjaliMahawar**
### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by AnjaliMahawar** [comment]
Hy 
i am Anjali Mahawar from india . i am submitting a PR for hindi Translation .i have made file that  is hi.json which is translated in hindi. 
i request you to kindly accept my PR.
jai hind

**Comment by derrickmehaffy** [comment]
We have 3 different pull requests opened in the past few days all targeting adding Hindi translations. Can you three agree on which one we should take a look at?
Also just curious was there some kind of workshop that was going on? (Love seeing people battle over PRs lol)

- https://github.com/strapi/strapi/pull/13468
- https://github.com/strapi/strapi/pull/13467
- https://github.com/strapi/strapi/pull/13466

**Comment by anildalar** [comment]
@derrickmehaffy Yes Derrick, I am the instructor of these workshop classes on git collaboration. I am teaching my students about how to submit PR to open source repository. PR#13467 is ok and can be merged.
I personally like Strapi very much. I had used Strapi in a recent Singapore based company Latitude pay to build a Merchant Directory system. It was a great experience for me to able to incorporate Strapi as CMS. 
 If want to see live workshop classes visit https://youtube.com/c/OKLABSGURU
https://youtu.be/tE7STQUPjRU

**Comment by anildalar** [comment]
@derrickmehaffy Can i work on Strapi as fullTime. ?

**Comment by ronronscelestes** [comment]
hi!
thank you for this nice contribution 😊
I think tests should be updated - the problem seems to come from `languageNativeNames.js`, would it be possible for you to fix it?

**Comment by AnjaliMahawar** [comment]
Ok i will try .

**Comment by AnjaliMahawar** [comment]
hi @ronronscelestes
 I fixed the problem.

**Comment by ronronscelestes** [comment]
> hi @ronronscelestes I fixed the problem.

hi @AnjaliMahawar, thanks again 😊 I'll merge it after the tests check!

**Review by ronronscelestes — APPROVED** [review]
LGTM, thank you 💃

**Pull request merged**
