### PR TITLE
fix: fix boot issue when removing i18n from an app

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?

Fix boot error when i18n is not installed
image

### CODE REVIEW

**Review by alexandrebodin — APPROVED** [review]
code lgtm

**Review by simotae14 — APPROVED** [review]
it looks good to me, thanks Mark, I need just to test it

**Comment by simotae14** [comment]
It works perfectly, thanks @Marc-Roig

**Review by Feranchz — APPROVED** [review]
Thanks for taking care of this so fast Marc!

**Pull request merged**
