### PR TITLE
Change strapi icons color in dashboard

### PR DESCRIPTION
**Pull request by simotae14**
### What does it do?

Change the Strapi svg colors in the Dashboard

### Why is it needed?

Because we have a bug in the dashboard, the icons for the blog and careers links seem to be broken.

### How to test it?

Run your Strapi application and open the admin panel. after logging in and navigating to your dashboard, you should see the issue.
Schermata 2022-11-30 alle 16 00 05
Schermata 2022-11-30 alle 15 59 59

now resolved
Schermata 2022-11-30 alle 16 00 05
Schermata 2022-11-30 alle 15 59 59

### Related issue(s)/PR(s)

Fix [#793](https://github.com/strapi/design-system/issues/793)

### CODE REVIEW

**Review by joshuaellis — COMMENTED** [review]
Why are we doing any of these amends in here? Surely the icon from the lib should be correct to begin with? 

Cc @gu-stav / @ronronscelestes / @maevalienard

**Comment by simotae14** [comment]
Ok, I understand your point, let's wait their opinion, we can change directly the svg in the DS

**Comment by maevalienard** [comment]
I honestly don't know why the SVG is not the right one. 

The fix provided is fine to me if it can avoid future potential regression like the one we currently have. I trust your opinion about what is best though, and happy to provide assets if necessary :)

**Comment by simotae14** [comment]
The SVG is correct, maybe we need to find a better way to change the icons' theme color, I think we can open a ticket on it and try to find a better way, because I think it is bigger than just fixing the colors like I did for the Strapi Icon and I suppose there are different icons involved inside the Strapi repo, then my suggestion is to provide this temporal fix in the meantime and close the bug and then discuss a proper way to handle these situations preventing possible regressions when we change the svg for example

**Review by gu-stav — APPROVED** [review]
I'd say this is a valid for for now, but it shows that we should start working on the SVG theming API which has been discussed in a FE sync.

During an [internal slack discussion](https://strapihq.slack.com/archives/C030FUN0GGP/p1669974471147949) it became evident, the color reset comes from [`BaseButton`](https://github.com/strapi/design-system/blob/main/packages/strapi-design-system/src/BaseButton/BaseButton.js#L17-L22). 

@simotae14 Could you create an issue for the SVG theming API in the design-system repo? 🙏🏼

**Review by Bassel17 — APPROVED** [review]

**Comment by simotae14** [comment]
Yes, sorry I was on holiday...sure I can create an issue in the DS, thanks @gu-stav

**Pull request merged**
