### PR TITLE
Fix unable to filter users, add e2e test

### LINKED ISSUE #11789: Filtering on any field for Users in Users-Permissions yields a 500 error
### Describe the bug

When running an `$eq` filter on any field from users-permissions => user model yields the following error:

```
[2021-12-03 13:10:44.546] error: Undefined attribute level operator email
Error: Undefined attribute level operator email
    at processAttributeWhere (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/helpers/where.js:82:13)
    at processWhere (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/helpers/where.js:142:45)
    at /mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/helpers/where.js:104:29
    at Array.map (<anonymous>)
    at Object.processWhere (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/helpers/where.js:104:18)
    at Object.processState (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/query-builder.js:234:29)
    at Object.getKnexQuery (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/query-builder.js:271:12)
    at Object.execute (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/query/query-builder.js:352:25)
    at Object.findMany (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/database/lib/entity-manager.js:134:10)
    at async Object.find (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/plugin-users-permissions/server/controllers/user.js:137:19)
    at async returnBodyMiddleware (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async serve (/mnt/Storage/Development/testPopDocs/node_modules/koa-static/index.js:59:5)
    at async returnBodyMiddleware (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/mnt/Storage/Development/testPopDocs/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /mnt/Storage/Development/testPopDocs/node_modules/@strapi/strapi/lib/middlewares/body.js:24:7
```

### Steps to reproduce the behavior

1. Create a user in Users-Permissions
2. Enable public find permission
3. Try to filter for `username`, `email`, or `role`

### Expected behavior

Should Filter :)

### Screenshots

image

image

### Code snippets

qs structure:

```js
const qs = require('qs');
const query = qs.stringify({
  filters: {
    username: {
      $eq: 'test'
    },
  },
}, {
  encodeValuesOnly: true,
});

await request(`/api/users?${query}`);
// GET /api/users?filters[username][$eq]=test
```

### System

- Node.js version: v14.18.1
- NPM version: v6.14.15
- Strapi version: 4.0.0
- Database: SQLite
- Operating system: Linux Mint 20.2

### Additional context

N/A

### PR DESCRIPTION
**Pull request by iicdii**
### What does it do?

1. It replaces `strapi.query` with `strapi.entityService`.
2. It adds e2e test for `read` - with filter, without filter.

### Why is it needed?

For using filter on `User`.
Current code does not covert `ctx.query` to proper params for Strapi query engine.
So I replace it with `strapi.entityService` just like collection-types have, so that it converts to proper params.

### How to test it?

1. Create user
2. Send GET request with any filter

### Related issue(s)/PR(s)

Closes #11789

### CODE REVIEW

**Comment by alexandrebodin** [comment]
I'm not sure this is something we want to move forward with as it only changes the find but doesn't change the findOne etc. 

This API is not like the autogenerated ones by design and only supports filters passed at the root level of the query. 
You are not supposed to be able to pass down sorting or limit for example. 

I agree it would be better to make it consistent but we have some security concerns to take into account first.

**Comment by iicdii** [comment]
What about
```js
strapi.db.query('plugin::users-permissions.user').findMany({ where, populate });
```
then?
I assume that the old `strapi.query` has a problem.

**Comment by alexandrebodin** [comment]
Hum not sure what you are suggesting here can you share a more complete snippet ?

**Comment by iicdii** [comment]
the original code used `strapi.query`, but in v4 it's documented that you need to use `strapi.db.query`
so I suggest

```js
  fetchAll(params, populate) {
    return strapi.db.query('plugin::users-permissions.user').findMany({ where: params, populate });
  },
```

instead of

```js
  fetchAll(params, populate) {
    return strapi.query('plugin::users-permissions.user').findMany({ where: params, populate });
  },
```

**Comment by alexandrebodin** [comment]
> 

Ho I see, strapi.query still exist for compatibility reasons so that wouldn't be a big deal anyway as it's internal code of the plugin :)

**Comment by iicdii** [comment]
I just revert to the original code and just pass `ctx.query.filter` instead of `ctx.query`. I think it's simple and no side effect about security or compatibility issues, etc :)

**Comment by alexandrebodin** [comment]
Thanks for the update. I think that's a good quick fix before we move to entityService.

**Review by alexandrebodin — APPROVED** [review]

**Pull request merged**
