### PR TITLE
Fix so you can choose multiple domains for the cors

### PR DESCRIPTION
**Pull request by gianca970226**
⚠️ Fix so you can choose multiple domains for the cors 

My PR is a:
- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #issueNumber
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

Main update on the:
- [ ] Admin
- [ ] Documentation
- [x] Framework
- [ ] Plugin

The problem was that my Strapi needs to be seen from several GUI clients, e.g. client1.com and client2.com, in the cors for security could not leave the wildcard *, then, I went to admin gui of strapi, and add the two domains, but I did not work, I only took the first so separated by commas "," then I consulted about KOA js and discovered that for multiple domains had to make a function and review the origin of the request in a list that is the one I make a split with "," of the configuration of the midlewars of cors.

⚠️ https://github.com/strapi/strapi/issues/2245
⚠️ https://github.com/strapi/strapi/issues/1766
⚠️ https://github.com/strapi/strapi/issues/2406

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello @gianca970226! Thank you for this PR.

Can you fix travis errors (the lint look have issues) and can you write a comment about what do this PR please.

**Comment by gianca970226** [comment]
but i have this error At least 1 approving review is required by reviewers with write access

**Comment by derrickmehaffy** [comment]
@gianca970226 you need to review the logs from the travisCI build and fix them, Just push to your branch and travisCI will retest automatically.

Your build is failing currently. Until the errors are fixed this PR cannot be merged.

**Comment by lauriejim** [comment]
@gianca970226 Can you please update your PR comment and add a short description of what you PR is doing.

The travis test fail because of `snyk` and we fixed it (just have to pull master to fix it on your branch)

**Comment by gianca970226** [comment]
@lauriejim Ready mofique the comment

**Comment by lauriejim** [comment]
I think we have to trim the array values.

In your case `app1.strapi.io,app2.strapi.io` will work but `app1.strapi.io, app2.strapi.io` will not work I think.

**Comment by gianca970226** [comment]
@lauriejim ready add regex split

**Pull request merged**
