### PR TITLE
Integrate AWS SES provider into nodemailer provider

### PR DESCRIPTION
**Pull request by iicdii**
### What does it do?

- Replaced [node-ses](https://github.com/aheckmann/node-ses) library with [nodemailer](https://github.com/nodemailer/nodemailer). [node-ses](https://github.com/aheckmann/node-ses) has not been maintained for long time - **last published at Oct 2020, 198 star**. On the other side, [nodemailer](https://github.com/nodemailer/nodemailer) is more popular, well-maintained library - **last published at Nov 2021, 14.4k star**.
- Updated README.md
- Added extra jsDoc in `index.js`
- Throws proper error

### Why is it needed?

- To replace old, unmaintained library.
- Make more use cases like **sending email with `attachment`**, **obtaining `messageId` of email**, **including `inReplyTo` parameter for threading** to be possible.

### How to test it?

1. Set configuration in `config/plugins.js` following `README.md` guide.
2. Settings > EMAIL PLUGIN - Settings > Click **Test Email**

### Related issue(s)/PR(s)

It also fixes problem in #10151.

### CODE REVIEW

**Review by derrickmehaffy — APPROVED** [review]
LGTM

**Comment by alexandrebodin** [comment]
Sadly this is PR is a breaking change and we cannot accept it. I would recommend we create a new provider for example and deprecate the current one to avoid breaking changes.

**Comment by iicdii** [comment]
Can I create new provider `@strapi/provider-email-amazon-ses-nodemailer` for example and just add a deprecate message in old provider? Or is there anything else that I need to do programmatically?

**Comment by alexandrebodin** [comment]
We will have to add a deprecation warning on npm once we make a new release if we want to deprecate the old one. 

However, I'm wondering since nodemailer supports a few transports. It would be even better to just have a provider-email-nodemailer, that could support any of the supportes transports without having to install a new strapi provider each time 🤔

**Comment by iicdii** [comment]
> However, I'm wondering since nodemailer supports a few transports. It would be even better to just have a provider-email-nodemailer, that could support any of the supportes transports without having to install a new strapi provider each time 🤔

I agree. We can extend `providerOption` to existing `email-nodemailer` provider for developers to use different transports (and deprecate this ses provider). Shall I start working that way?

**Comment by alexandrebodin** [comment]
Sounds good as long as we can extend without breaking changes it seems like a good solution

**Comment by alexandrebodin** [comment]
Going to close this PR in favor of the upcoming changes

**Pull request closed without merging**
