### PR TITLE
Sidebar injection zone

### PR DESCRIPTION
**Pull request by Boegie19**
### What does it do?

Add a new injection zones on the side menu

### Why is it needed?

So that plugins can inject stuff into the side menus

For example the plugin that I am currently work on that would allow you to instance with multiple different strapi instances.

### How to test it?

try to inject something into the side menu

### CODE REVIEW

**Comment by joshuaellis** [comment]
We'll need to discuss internally before continuing with this.

**Comment by Boegie19** [comment]
Understandable

**Comment by joshuaellis** [comment]
Yeah, I'd actually rather do a more API based approach with a lot more freedom, IMO I think it creates a more predictable app as opposed to plug-in developers just hooking into a black box.

I'll still bring this up tomorrow.

**Comment by Boegie19** [comment]
> Yeah, I'd actually rather do a more API based approach with a lot more freedom, IMO I think it creates a more predictable app as opposed to plug-in developers just hooking into a black box.
> 
> I'll still bring this up tomorrow.

I think we need to have both and tell plugins devs to when ever possible use the more API based approach but keep the injection zones and have at least 1 per page for when you want to do more custom stuff. what would not be posible in the API based approach.

for example for my thing I need a dropdown inside of the admin view

**Comment by Boegie19** [comment]
@joshuaellis Any updates on this and let me give it an other try to fix the damm failing linting

**Pull request closed without merging**
