### PR TITLE
Support adding custom locales for admin UI

### PR DESCRIPTION
**Pull request by DarkSuniuM**
### What does it do?

Allows developer to extend `packages/core/admin/admin/src/translations/languageNativeNames.js` using `languageNativeNames` key admin config (`src/admin/app.js`)

### Why is it needed?

Without this, extending translations for custom languages doesn't work.

### How to test it?

Modify `examples/getstarted/src/admin/app.js` and put the following:
```js
export default {
  config: {
    locales: ['fa'],
    languageNativeNames: {
      fa: 'فارسی',
    },
    translations: {
      fa: { 'Settings.profile.form.section.experience.interfaceLanguage': 'زبان رابط کاربری' },
    },
  },
  bootstrap() {},
};
```

Run the following command: `yarn workspace getstarted develop --watch-admin`

Open http://localhost:8000/admin/me in your browser, Set Interface Langauge to "فارسی", and Save.

The "Interface Language" title should change to "زبان رابط کاربری" which is defined in `examples/getstarted/src/admin/app.js`

### CODE REVIEW

**Comment by shestakov-vladyslav** [comment]
Good thing

**Comment by DarkSuniuM** [comment]
> Good thing

This PR had some issues which I'll fix later

**Comment by pimpelsang** [comment]
So what happened to it?

**Comment by EmanuilGerganov** [comment]
How to add a new language to Strapi admin panel?

**Comment by AleksiupasSameSystem** [comment]
How to add a new language to Strapi admin panel?

**Pull request closed without merging**
