### PR TITLE
fix: invalid path separator

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?
Copy of https://github.com/strapi/strapi/pull/20680 on the v4 branch (develop)

Adds support for cross-platform handling of separators (win32 and posix) when parsing file paths.

### Related issue(s)/PR(s)

fixes https://github.com/strapi/strapi/issues/20730

### CODE REVIEW

**Review by Convly — APPROVED** [review]
The code LGTM, I won't have access to a Windows machine in the coming week, so let's create an experimental release and see how it works on users' machines.

**Comment by Marc-Roig** [comment]
Experimental release: `0.0.0-experimental.1773982cafe8a6dd5c5d0551ba2cac334854d42f`

@derrickmehaffy do you know of someone with windows who can test the experimental?

**Comment by Convly** [comment]
Note: Keep in mind we need to test with an actual Win shell.WSL and in some instances PowerShell handles forward slashes and won't have the original error anyway (hence why it took time to reproduce)

**Comment by alexandrebodin** [comment]
I can't test on windows but code lgtm

**Comment by Marc-Roig** [comment]
going to merge this morning, and will test with @MarionLemaire today on windows

**Comment by MarionLemaire** [comment]
Tested on Windows with 4.25.4 : 
image
Component is created without making the app crash :)

(previously on 4.25.3, we had this error : )
image

**Comment by derrickmehaffy** [comment]
Sorry I didn't get a chance to test, got backlogged with tickets. Thank you @MarionLemaire 😊

**Pull request merged**
