### PR TITLE
chore: allow graphql get request with authentication

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Allows get request. I couldn't find any reason to keep the old code arround.

### CODE REVIEW

**Comment by innerdvations** [comment]
Fixes/implements #18979 and #14601

**Review by innerdvations — APPROVED** [review]
LGTM, tested that auth still works with GET. Any idea why this was added originally? I remember adding those comments a while back but was afraid to remove the actual code in v4

**Comment by alexandrebodin** [comment]
> LGTM, tested that auth still works with GET. Any idea why this was added originally? I remember adding those comments a while back but was afraid to remove the actual code in v4

I think someone missunderstood strapi.auth.anthenticate & strapi.auth.verify

**Comment by innerdvations** [comment]
We may want to accept https://github.com/strapi/strapi/pull/19168 as well for v4

**Pull request merged**
