### PR TITLE
fix query-builder distinct issue with one-to-many and many-to-many relations

### PR DESCRIPTION
**Pull request by Zoha**
### What does it do?

fixes distinct issues with orderBy in one-to-many and many-to-many relations when we our orderBy creates a join on query
fixes: #13153

### reproduce the issue 

1. on an example project, create two (or more) address entity 
2. then create a category and assign created addresses to it 
3. try to get categories by sorting by a column of addresses for example `/categories?sort=addresses.slug:ASC`
4. you will see that we got two (or more) categories but we just had one ( we'll have duplicates for each address item )

### Why is it needed?

currently, we have an abvious bug in relations query building and its results 
we don't need `order by` columns distinction 
we will  always have a `target.id` select on our entity so all the returned data will be distinct since our id is unique we don't need to distinguish it by relations, distinction by id + relation fields always return duplicate data since all the rows unwinded by the result

summary : 
for relations ordering, we are generating something like this
`select distinct `t2`.`created_at`, `t0`.* from ...` ⛔ 
but we need to distinct by target table to prevent duplicate data 
`select distinct  `t0`.* from ...` 👍 

### How to test it?

1. on an example project, create two (or more) address entity 
2. then create a category and assign created addresses to it 
3. try to get categories by sorting by a column of addresses for example `/categories?sort=addresses.slug:ASC`
4. you will see that we just have one item, not two 👍 

### Related issue(s)/PR(s)

related to #13153

### CODE REVIEW

**Comment by kibblerz** [comment]
Can this get merged? It's affecting a project of ours.

**Comment by kibblerz** [comment]
Any update on the status for this?

**Comment by derrickmehaffy** [comment]
> Any update on the status for this?

No status update yet but I'll try and get someone to review it. In the meantime you can apply it using patch-package to your project

**Comment by alexandrebodin** [comment]
Hi, We merged a few things recently addressing the distinct issues. Does that issue still exist the the latest version ?

**Comment by kibblerz** [comment]
Is there an ETA on this? It's holding back a project of ours currently.

**Comment by alexandrebodin** [comment]
@kibblerz As said in the previous message. We fixed already the DISTINCT issue but we are not 100% sure it fixed this one. 

Have you tried the latest Strapi versions?

**Comment by Zoha** [comment]
@alexandrebodin I tested an no its still hapenning 
let me know if you want to consider this pr 
image

**Comment by alexandrebodin** [comment]
The main problem I'm seeing is that you removed the code that we used to manage a condition for postgres distinct documented here https://www.postgresql.org/docs/9.0/sql-select.html#SQL-DISTINCT that requires the leftmost orderby to appear in the distinct. 

We need to figure this out for all DBs :)

**Comment by Convly** [comment]
Hey I'm closing this for inactivity but don't hesitate to put a comment to reopen it :slightly_smiling_face:

**Pull request closed without merging**
