### PR TITLE
Typescript support - Added config option to allow loading additional file types.

### PR DESCRIPTION
**Pull request by ascension**
**Description of what you did:**
Based on the discussion in #6550 I implemented:
Added a new config option loader.extensions to allow core api to load additional files.
Added a new example project that uses Typescript.

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @ascension thank you for this PR. I'm going to close the other one so we have only one to work on :)

**Comment by ashbrener** [comment]
> Hi @ascension thank you for this PR. I'm going to close the other one so we have only one to work on :)

Hi @alexandrebodin , if this commit solves the file extension issue only, surely #6550 is still relevant ?

**Comment by alexandrebodin** [comment]
HI @ashbrener. I thought you were inactive & wouldn't update your PR so I wanted @ascension to merge all the work into one PR so we could move forward with this :)
You both have examples projects & changes to the same files. If you are willing to update your PR once we have reviewed this one then I can reopen but you will only need to add the typings from your PR back if I'm not mistaken

**Comment by alexandrebodin** [comment]
what @ascension @ashbrener do you think about this ?

**Comment by ashbrener** [comment]
Am happy to apply the type declarations and project generator files once @ascension has completed the file type loaders.

Q: What is the view on running TypeScript compilation as per discussion in #6550 ?  Is this something the developer would have to "hack" manually using ts-node etc, or are you going to expose it as an option in the CLI ?

**Comment by ascension** [comment]
> Am happy to apply the type declarations and project generator files once @ascension has completed the file type loaders.
> 
> Q: What is the view on running TypeScript compilation as per discussion in #6550 ? Is this something the developer would have to "hack" manually using ts-node etc, or are you going to expose it as an option in the CLI ?

@ashbrener Currently I have this setup to allow people to register a `bootstrap` function in the sever config to allow something like this: `require('ts-node').register();`. I know there are some might performance implications with this method. 

In order to support native typescript compilation without introducing typescript dependancies to strapi, we would need a plugin api exposed that would allow `strapi/lib/commands` to be swapped out with ones that support typescript.

**Comment by ashbrener** [comment]
Hi @alexandrebodin what is the status here?

**Comment by amitav13** [comment]
As someone who's primarily worked on strongly typed languages, I think this and #6550 are the two PRs that I've followed the closest, probably ever. Would have contributed to this myself if I had the know-how. 

Any way I can help push this ahead? @ascension @alexandrebodin ?

**Comment by ascension** [comment]
I opened a new PR with some updates here https://github.com/strapi/strapi/pull/10614

**Comment by ascension** [comment]
Closing this PR as I have opened a new one with some updates here:
https://github.com/strapi/strapi/pull/10614

**Pull request closed without merging**
