### PR TITLE
Add session option to Strapi query for Mongo Multi-Document transaction

### PR DESCRIPTION
**Pull request by iicdii**
#### Description of what you did:
1) I added optional object as the last parameter of the Strapi Query, so that you can pass extra values inside Strapi query.
```js
// As-is
strapi.query('post').create({ title: 'test' });
strapi.query('post').find({ title: 'test' }, []);

// To-be
strapi.query('post').create({ title: 'test' }, {});
strapi.query('post').find({ title: 'test' }, [], {});
```
2) I made sure to use the **session** value for all mongoose operations, which is necessary for Mongo Multi-Document transaction.
It does not affect to previous operations though, because all mongoose operations has "session" option and calling session(null) removes the session from the query. I set the default value for session to null.

#### Example of usage:
```js
const input = [{ title: 'test1' }, { title: 'test2' }, { title: 'test3' }];

const session = await strapi.query('post').model.startSession();
session.startTransaction();
try {
  for (let data of input) {
    await strapi.query('post').create(data, { session });
  }

  await session.commitTransaction();
  session.endSession();
} catch (e) {
  await session.abortTransaction();
  session.endSession();
  throw e;
}
```

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi, Your PR is quite outdated would you mind updating it ?

**Comment by iicdii** [comment]
@alexandrebodin No Problem. I will make PR soon.

**Comment by alexandrebodin** [comment]
Hey @iicdii Your PR contains changes it should contain. You will need to fix this so we can review first :)

**Comment by iicdii** [comment]
Have been struggled with some git history issues.. 😓 I excluded unnecessary changes and hope it work

**Comment by alexandrebodin** [comment]
Hi ! your PR is still not passing the test :/ You would mind recreating a fresh new PR without one unique sign-off commit ?

**Comment by iicdii** [comment]
Ok I will close this and make new one.

**Pull request closed without merging**
