### PR TITLE
Save uploaded files' path info and use it in the delete operation

### LINKED ISSUE #7770: strapi-provider-upload-aws-s3 with custom path, original not deleted
**Describe the bug**
New issue as requested in #6931.
I'm uploading images on AWS S3 using the plugin strapi-provider-upload-aws-s3 with custom paths. When deleting the image, the original file on a custom path is not deleted.

**Steps to reproduce the behavior**

1. Upload an image with a custom path. This will create original and thumbnail at a minimum.
2. Delete image.
3. Thumbnail is deleted, original is still around.

**Expected behavior**
Deletion of all formats including original.

**Additional context**
Related to #7742 perhaps?

**System**
- Node.js version: 13.7
- NPM version: 6.13.6
- Strapi version: 3.1.4
- Database: pg
- Operating system: osx

### PR DESCRIPTION
**Pull request by ktunador**
### What does it do?

It saves the path information included in an upload request as provider metadata. This allows the AWS-S3 provider to use this information in other operations like deleting uploaded files.

### Why is it needed?

Currently, the provider doesn't save this information, and the upload plugin doesn't have a column, "path," to hold this data. Without this information, the delete operation could not be able to remove the uploaded files from the bucket. [PR 8408](https://github.com/strapi/strapi/pull/8408) tries to solve the issue by adding the column. However, the solution should target the provider, not the plugin, because the path info and the issue are specific to the provider.

### Related issue(s)/PR(s)

Fix #7770

### CODE REVIEW

**Comment by ktunador** [comment]
Hi @derrickmehaffy, 
Could you check this PR to see if I've been doing something wrong so that it hasn't been reviewed for a month.

Thanks,

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy,
> Could you check this PR to see if I've been doing something wrong so that it hasn't been reviewed for a month.
> 
> Thanks,

Sorry we are pretty far behind on PR reviews as the team is focused on the v4 development. I'll poke the team to see how it's going on the PR reviews.

**Comment by jordankittle** [comment]
Hi everyone, I just wanted to express my interest in this fix.   Any files deleted from media library are remaining on our S3 storage. Thank you.

**Review by angelbanderasudg — CHANGES_REQUESTED** [review]
Hi, I Am suggesting changes in the delete function, because if someone tries to delete a previous file, this file will not have  provider metadata, and it will gave a null exception. I suggest this: 
`` `const path = file.provider_metadata && file.provider_metadata.path ? `{file.provider_metadata.path}/` : '';` ``

**Comment by angelbanderasudg** [comment]
> Hi everyone, I just wanted to express my interest in this fix. Any files deleted from media library are remaining on our S3 storage. Thank you.

Hi, you could create a local provider using the same code of this provider and apply the changes of this fix, and the one that I suggest, until they publish this fix

**Comment by ktunador** [comment]
> Hi, I Am suggesting changes in the delete function, because if someone tries to delete a previous file, this file will not have provider metadata, and it will gave a null exception. I suggest this:
> `` `const path = file.provider_metadata && file.provider_metadata.path ? `{file.provider_metadata.path}/` : '';` ``

Hi,
Sorry for the late response. 
''''provider_metada'''' field isn't specific to this plugin. It was added to File model [2 years ago ](https://github.com/strapi/strapi/commit/0ab5a8a40746b0f8179860600b96b3aac12dda89) so I believe if the strapi installation isn't more than 2 years old; '''provider_metadata''' field should always be available in the file record.

Did you get the exception in your system?

**Comment by angelbanderasudg** [comment]
> > Hi, I Am suggesting changes in the delete function, because if someone tries to delete a previous file, this file will not have provider metadata, and it will gave a null exception. I suggest this:
> > `` `const path = file.provider_metadata && file.provider_metadata.path ? `{file.provider_metadata.path}/` : '';` ``
> 
> Hi,
> Sorry for the late response.
> ''''provider_metada'''' field isn't specific to this plugin. It was added to File model [2 years ago ](https://github.com/strapi/strapi/commit/0ab5a8a40746b0f8179860600b96b3aac12dda89) so I believe if the strapi installation isn't more than 2 years old; '''provider_metadata''' field should always be available in the file record.
> 
> Did you get the exception in your system?

Hi, yes, well I was using AWS as a provider and I get the problem that if I save the files to a specific folder and not the root folder, and then I delete them, in the bucked of AWS only the thumbnails get deleted. So I find this PR and I tested it, it give me the exception with the files that I already had on the bucked, for that I suggest the comprobation that I did and its working.
Yeah it seems like its added, but if the provider don't save that data it would be null. (I use mongoose, I don't now if this is diferrent in another databases)

**Comment by BrOrlandi** [comment]
I'm also interested in this fix.

**Comment by ktunador** [comment]
Hey @alexandrebodin, 
Is there any chance of merging this request? If not, could you provide us another solution for the issue, please?

Cheers

**Comment by BrOrlandi** [comment]
> Hey @alexandrebodin,
> Is there any chance of merging this request? If not, could you provide us another solution for the issue, please?
> 
> Cheers

@ktunador We solve this by sending the `path` to the delete function like this:

```js
const fileToDelete = await strapi.plugins.upload.services.upload.fetch(query);
    if (fileToDelete) {
      if (fileToDelete.formats && fileToDelete.formats.thumbnail) {
        fileToDelete.path = fileToDelete.formats.thumbnail.path;
      }
      await strapi.plugins.upload.services.upload.remove(fileToDelete);
    }
```

Hope it helps

**Comment by derrickmehaffy** [comment]
Hi 👋  
We now have released the `v4`. As of now, the `v3` is in maintenance mode for 6 months. We will only be fixing critical and security issues on v3 from now on. 
I will go ahead and close this PR. Thank you for contributing to Strapi 🔥

**Comment by LyovaYesayan** [comment]
In v4 this issue exists

**Comment by LyovaYesayan** [comment]
> > Hey @alexandrebodin,
> > Is there any chance of merging this request? If not, could you provide us another solution for the issue, please?
> > Cheers
> 
> @ktunador We solve this by sending the `path` to the delete function like this:
> 
> ```js
> const fileToDelete = await strapi.plugins.upload.services.upload.fetch(query);
>     if (fileToDelete) {
>       if (fileToDelete.formats && fileToDelete.formats.thumbnail) {
>         fileToDelete.path = fileToDelete.formats.thumbnail.path;
>       }
>       await strapi.plugins.upload.services.upload.remove(fileToDelete);
>     }
> ```
> 
> Hope it helps

The case is that media is not only image, it can be pdf/audio file, etc.. and these kind of files don't have thumbnail or any other format like small or large. this doesn't fix that case

**Comment by LyovaYesayan** [comment]
I wonder if strapi community hasn't fixed this issue, as it is known issue from 2020

**Pull request closed without merging**
