### PR TITLE
Prevent override `where` clause for `findOne`, `update`, `delete` met…

### PR DESCRIPTION
**Pull request by R-iskey**
### What does it do?

Currently `findOne`, `update`, `delete` just ignore the `filters` property from params, and find the entity with id.

### Why is it needed?

Gave an ability to use corresponding methods more flexible

### How to test it?

To order to test it, just use  one of corresponding methods  from `strapi.entityService`

### Related issue(s)/PR(s)

Fixes: https://github.com/strapi/strapi/issues/13693

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi. 

Can you explain the use case that requires this?

**Comment by alexandrebodin** [comment]
> @alexandrebodin this was one that even Richard and I think should exist since findOne only allows finding by ID and not say a UID field like slug. To do it now, you have to find any and grab the first index from the response which feels hacky (even though it's generating a similar SQL query.
> 
> This could be much more helpful later on if/when we decide to create core actions though or allow plugins to create actions, say something that automatically creates `/findByX` routes on all content types with a UID (or several) fields.


Ok if that's the usecase then there are two things: 

- Allowing findOne to find per unique field
- Adding a findFirst to find the 1st matching entity and this removing the id from the function entirely

Right now this PR keeps the entityId so it won't solve the use case you shared

**Comment by derrickmehaffy** [comment]
There are additional use-cases that opting not to just perform actions based on ids like say deleting records older than x date or updating records (think bulk update but without knowing id) though I suppose we do have the bulk actions from the DB engine that could account for those but bulk doesn't exist in the entityService.

**Comment by alexandrebodin** [comment]
> There are additional use-cases that opting not to just perform actions based on ids like say deleting records older than x date or updating records (think bulk update but without knowing id) though I suppose we do have the bulk actions from the DB engine that could account for those but bulk doesn't exist in the entityService.

The examples you mention indeed are not targeting one entity so there shouldn't be part of a single update or delete. the PR only adds filters on top of id, but it says required, so it's not addressing any of the use cases you mentioned where you want to do sth on multiple things by matching without id.

**Comment by alexandrebodin** [comment]
Hi based on the discussion here I'm going to close this PR for now. Feel free to ping me if you want to discuss this again

**Pull request closed without merging**
