### PR TITLE
fix: get condigured field for admin_users collection for relation field.

### PR DESCRIPTION
**Pull request by sumaiya2908**
### What does it do?

For the issue that the user was not able to see/select while creating/editing a new entry, the field of the related collection:

I have added a case for checking the read permission of the collection user(admin).   If the user has permission, we can see the corresponding field values, or else the id field is displayed.
 
I have configured the view to firstname for the relation field and am able to see the respective field.

image

### Why is it needed?

I have configured the view to firstname for the relation field. But I am able to see the ID field for the collection while creating an enrty.

image

This was because while sanitizing the field, we were not checking for the user(admin) collection. So the condition would return id by default.

image

### How to test it?

- Add a field that is related to the User (from admin) to any content type
- Configure the view for this content type
- Attempt to create an item
- The Relation Fieldcorrect input only shows the ID of the user
- The record is shown correctly in the content manager

### Related issue(s)/PR(s)

Modified the code of the PR -  #17702

closes - #18072

### CODE REVIEW

**Comment by Feranchz** [comment]
For me the code looks good, I tried it locally and its working fine but I would like to have the @Marc-Roig opinion because this PR is in top of his work.

@sumaiya2908 can you please sign the CLA?

**Comment by sumaiya2908** [comment]
> @sumaiya2908 can you please sign the CLA?

Hey @Feranchz , I have already signed the CLA.

image

**Comment by sumaiya2908** [comment]
any update on this?

**Comment by lordvcs** [comment]
Any update on this?
 I am facing the same issue too.

**Comment by santhoshmaderi** [comment]
Hi

I am having the same issue how can I fix this issue? 

Regards
Santhosh Kumar

**Comment by innerdvations** [comment]
Hello, thanks for your PR! Could you please target the `develop` branch instead of `main`? Thanks!

**Comment by alexandrebodin** [comment]
> [!IMPORTANT] 
> With the release of Strapi 5, we have lifted the code freeze. To ensure we can effectively review and assist with contributions, we are now only accepting PRs targeting version 5 (the develop branch).<br/> 
> As your PR targets version 4, it has been automatically closed. However, we would greatly appreciate it if you could update your contribution to align with version 5 and resubmit!

**Pull request closed without merging**
