### PR TITLE
[V4] Add support to have multiple Strapi instances in same database using table prefix

### PR DESCRIPTION
**Pull request by jakobsjoqvist**
### What does it do?

Add support to have multiple Strapi instances use the same table by making use of table prefixes.

- `examples/getstarted/config/database.js`
Lets user specify table prefix to use for the particular instance.
- `packages/core/database/lib/dialects/[sqlite|mysql|postgres]/schema-inspector.js`
Update `LIST_TABLE` SQL-query to only return the tables associated with the particular Strapi instance (i.e. only return tables that have the prefix).
- `packages/core/database/lib/index.js`
Add field `tablePrefix` to database class and pass it to `createMetadata` to make all tables to be created gets the correct prefix.
- `packages/core/database/lib/metadata/index.js`
Prepend prefix to table name.
- `packages/core/database/lib/migrations/index.js` and `packages/core/database/lib/migrations/storage.js`
Add table prefix to migration table.
- `packages/core/database/lib/schema/diff.js`
Extend checks that are used to determine whether a table has a reserved name or not to handle table prefixes.
- `packages/core/database/lib/schema/storage.js`
Add prefix support for the `strapi_database_schema`-table.
- `packages/core/database/lib/utils/table-prefix.js`
Function to validate and create the table prefix. 

### Why is it needed?

This PR solves the problem of using the same database for multiple Strapi instances. Typically some hosting providers have database limits and by using prefixes the same database can be reused for multiple purposes (e.g. multiple Strapi instances).

### How to test it?

Configure two Strapi-instances to use different table prefixes but make them communicate to the same database. In the case of SQLite, you create a `data.db` file and then set the same path for both instances in `examples/getstarted/config/database.js`. The same applies for MySQL and Postgres.

The easiest way to create the two instances is to simply duplicate the examples/getstarted folder and make sure to use different server port (`config/server.js`) as well as a different database prefix in `config/database.js`.

### Related issue(s)/PR(s)

fixes: #5080 
Related PR: #11491 (Was closed when the `releases/v4` branch was deleted)

### State of PR
This PR is ready to be merged.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Triggering tests

**Comment by alexandrebodin** [comment]
Hi, 

I think we can allow table prefix for convenience when using strapi and mixing it with custom tables but I don't support the idea to have multiple apps in one DB. This goes against a lot of good practices. I will always recommend you split the DBs in the database server you use instead (security, backups, performance, human errors...)

**Comment by alexandrebodin** [comment]
Hi, @jakobsjoqvist I think this PR seems quite alright, It is going to need some documentation too. I'm pinging @pwizla to help you out on this :) 

Maybe I would change the config format to match what exists (it will require a change in the config to merge objects correctly it's just doing an assign at the moment)

```js
module.exports = ({ env }) => ({
  connection: {
   ...
  },
  settings: {
    tablePrefix: 'xxx'
  }
});
```
does that sounds good ?

**Comment by derrickmehaffy** [comment]
@jakobsjoqvist you mind resolving the conflicts?

**Comment by jakobsjoqvist** [comment]
> @jakobsjoqvist you mind resolving the conflicts?

Hi, currently I'm quite busy but I might have some time during the coming weeks. Do you want me to only resolve the conflicts or change the config format as well?

**Comment by alexandrebodin** [comment]
> > @jakobsjoqvist you mind resolving the conflicts?
> 
> Hi, currently I'm quite busy at the moment but I might have some time during the coming week(s). Do you want me to only resolve the conflicts or change the config format as well?

That would be great yes :)

**Comment by jakobsjoqvist** [comment]
Hi!

I have now resolved the conflicts and I think I have updated the config object as per your request. Please have a look and let me know how we proceed further :)

**Comment by alexandrebodin** [comment]
hey @jakobsjoqvist  I had a look and things seem to be almost ready. We merged some PRs to improve performance that created some conflicts with your branch. Do you think you could update it accordingly ?

**Comment by jakobsjoqvist** [comment]
> hey @jakobsjoqvist I had a look and things seem to be almost ready. We merged some PRs to improve performance that created some conflicts with your branch. Do you think you could update it accordingly ?

Hi! I checked the conflict and it seems to be unrelated to my changes so I think I would suggest that you fix the conflict in `packages/core/database/lib/dialects/postgresql/schema-inspector.js`

**Comment by alexandrebodin** [comment]
> > hey @jakobsjoqvist I had a look and things seem to be almost ready. We merged some PRs to improve performance that created some conflicts with your branch. Do you think you could update it accordingly ?
> 
> Hi! I checked the conflict and it seems to be unrelated to my changes so I think I would suggest that you fix the conflict in `packages/core/database/lib/dialects/postgresql/schema-inspector.js`

actually it's caused by the refactor you did and create a function that changed the indentation :) If you don't have time I'll try to do it later

**Comment by alexandrebodin** [comment]
Hi @jakobsjoqvist  I just pushed the conflict fix. However I tried the PR and instantly go an error with a prefix and an sqlite table (with an already existing project) Let me know if you have time to investigate or I'll finish the work here :)

**Comment by jakobsjoqvist** [comment]
> Hi @jakobsjoqvist I just pushed the conflict fix. However I tried the PR and instantly go an error with a prefix and an sqlite table (with an already existing project) Let me know if you have time to investigate or I'll finish the work here :)

Sorry for my late reply. I will go on vacation in ~3 weeks so until then I will be quite busy but I will try to take a look at it :) If you need to merge it sooner I think it would be awesome if you could take a look from your end :)

**Comment by alexandrebodin** [comment]
Hi :) I'll close this PR for now as I won't be able to take over. If you want to continue or someone wants to finish the work start  simply ping me :)

**Comment by JakeElder** [comment]
Hi this would be a great feature. Did this ever make it in to the codebase?

**Comment by derrickmehaffy** [comment]
> Hi this would be a great feature. Did this ever make it in to the codebase?

No, no one else opted to take over the development

**Pull request closed without merging**
