### PR TITLE
Update sharp module to 0.26.0

### PR DESCRIPTION
**Pull request by darron1217**
Related Issue https://github.com/lovell/sharp/issues/2352

I've faced an issue when building electron app with strapi.

Updating version of sharp solved the problem.

Please check and hope be merged soon.

### CODE REVIEW

**Comment by MattieBelt** [comment]
@derrickmehaffy, they have [updated](https://github.com/lovell/sharp/blob/master/docs/changelog.md) their `libvips` version. #7409 might me related.

**Review by alexandrebodin — APPROVED** [review]
LGTM

**Comment by alexandrebodin** [comment]
Thanks for the upgrade !

**Comment by peteretelej** [comment]
sharp `0.26.0` requires Node 10.16.0+ https://github.com/lovell/sharp/compare/v0.25.4...v0.26.0#diff-04c6e90faac2675aa89e2176d2eec7d8R19

strapi README may need updating to reflect the new Node version requirement https://github.com/strapi/strapi#-requirements

**Pull request merged**
