### PR TITLE
Removed redundant callback argument

### PR DESCRIPTION
**Pull request by dacre-denny**
The `cb` argument is not used in the `send` method and was therefore removed. Ready for merge.

### CODE REVIEW

**Comment by alexandrebodin** [comment]
This callback should also be removed from the email.send service in the email plugin :)

**Comment by dacre-denny** [comment]
> This callback should also be removed from the email.send service in the email plugin :)

Just had a look and as you mentioned, it does appear to be redundant as well :)
https://github.com/strapi/strapi/pull/5466

**Comment by alexandrebodin** [comment]
@dacre-denny Can you please make your changes in one single PR :)

**Comment by dacre-denny** [comment]
@alexandrebodin sorry for the delay - found a few more redundant `cb`, so I've zapped those as well :)

**Comment by alexandrebodin** [comment]
@dacre-denny great :) can you fix the DCO check so your PR is mergeable ;)

**Comment by alexandrebodin** [comment]
@dacre-denny waiting on the DCO check to pass before merging.

**Pull request merged**
