### PR TITLE
feat: do not send status relations

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?

Do not send any status on relations if draft and publish is disabled on the **target** content type.

### CODE REVIEW

**Comment by joshuaellis** [comment]
Is status optional on the contract?

**Comment by jhoward1994** [comment]
Not in the response https://github.com/strapi/strapi/blob/4482266959526daf0608d1cde70eab7843c78806/packages/core/content-manager/shared/contracts/relations.ts#L9-L10

I think we should change that

**Comment by Marc-Roig** [comment]
missed you rcomment! just added the change in the contract

**Comment by joshuaellis** [comment]
I've added the FE parts but i can't see relations

https://github.com/strapi/strapi/assets/37798644/fd7afd84-85fe-4845-8a9e-6d531260d53e

**Comment by joshuaellis** [comment]
Does this need something else before we can merge? i.e. to solve the above issue i shared?

**Comment by joshuaellis** [comment]
wrong button.

**Comment by Marc-Roig** [comment]
edit, I can handle it :) it's just a line of code 🫡

**Review by joshuaellis — APPROVED** [review]

**Pull request merged**
