### PR TITLE
Update logger.js

### PR DESCRIPTION
**Pull request by Froelund**
Added environment variables to configure strapi logger.
`STRAPI_LOG_LEVEL`
`STRAPI_LOG_TIMESTAMP`
`STRAPI_LOG_PRETTY_PRINT`
`STRAPI_LOG_FORCE_COLOR`

### CODE REVIEW

**Comment by Froelund** [comment]
I need to change the value of `prettyPrint`. I'm deploying my api to Heroku, and using LogDNA for log analysis, that doesn't handle newlines.

**Comment by lauriejim** [comment]
LGTM but want a review from @Aurelsicoko 

Can you also write documentation about that. https://strapi.io/documentation/advanced/logging.html

**Comment by Aurelsicoko** [comment]
@Froelund Really great work! Thank you for this contribution 👍 

However, the documentation is still missing...

**Comment by Froelund** [comment]
Thanks for the review @lauriejim and @Aurelsicoko . I will update the documentation.

**Comment by Froelund** [comment]
I've split up the documentation/code in what relates to the global logger, and what is the request logger middleware.
I think we have a "todo", to create a logger factory, which enables us to move the global logger configuration into json files as everything else. The problem is, that the logging configuration has to be ready when the logger is required by Strapi as it's currently designed.

**Pull request merged**
