### PR TITLE
Update upload.md

### PR DESCRIPTION
**Pull request by drewmarshburn**
Added location of upload middleware configuration to the doc.

See modjke's comment on #7035.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
This change looks to be made on the wrong docs, can you please modify the v3 docs and not the v3-beta?

**Comment by drewmarshburn** [comment]
@derrickmehaffy Done, thanks

**Review by derrickmehaffy — APPROVED** [review]
LGTM

**Comment by derrickmehaffy** [comment]
@drewmarshburn Sorry for the late merge, can you resolve the conflicts and sign the new CLA? Thank you!

**Comment by alexandrebodin** [comment]
Hi @drewmarshburn your PR contains some conflicts :) can you update it ?

**Comment by derrickmehaffy** [comment]
Closing as manually synced to the new docs repo

**Pull request closed without merging**
