### PR TITLE
Update docs to include MySQL docker-compose.yaml

### PR DESCRIPTION
**Pull request by adamrhunter**
#### Description of what you did:
Adds a MySQL tab to the list of docker-compose yaml files in the "Installation using Docker" section of the docs.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
You have tested this option right? Curious to know if it works even with the changes to the MySQL password auth. Also could you also include one for MariaDB as well (it's a drop in replacement for MySQL that is entirely open source)

**Comment by adamrhunter** [comment]
> You have tested this option right? Curious to know if it works even with the changes to the MySQL password auth. Also could you also include one for MariaDB as well (it's a drop in replacement for MySQL that is entirely open source)

@derrickmehaffy  - Yes, indeed. It has been tested; I'm using this configuration for my local docker testing.  Ok, yeah, we can create an example config for MariaDB

**Comment by derrickmehaffy** [comment]
> > You have tested this option right? Curious to know if it works even with the changes to the MySQL password auth. Also could you also include one for MariaDB as well (it's a drop in replacement for MySQL that is entirely open source)
> 
> @derrickmehaffy - Yes, indeed. It has been tested; I'm using this configuration for my local docker testing. Ok, yeah, we can create an example config for MariaDB

Awesome, glad to hear it, I know on a normal MySQL install you have to manually specify `mysql_native_password` :+1:

**Review by derrickmehaffy — APPROVED** [review]
LGTM pending a review from @alexandrebodin just to confirm

**Comment by adamrhunter** [comment]
> > > You have tested this option right? Curious to know if it works even with the changes to the MySQL password auth. Also could you also include one for MariaDB as well (it's a drop in replacement for MySQL that is entirely open source)
> > 
> > 
> > @derrickmehaffy - Yes, indeed. It has been tested; I'm using this configuration for my local docker testing. Ok, yeah, we can create an example config for MariaDB
> 
> Awesome, glad to hear it, I know on a normal MySQL install you have to manually specify `mysql_native_password` 👍

@derrickmehaffy  - Ok, I've added MariaDB yml example to the commit.  I also bumped the MySQL docker version to latest (8 at time of writing) and forced the legacy authentication plugin via the command param.  I tested (fresh install and create content via admin ui) both on my local docker server.

**Comment by derrickmehaffy** [comment]
@adamrhunter Awesome, thank you!

**Pull request merged**
