### PR TITLE
fix: the disabled components don’t look like they are disabled inside content history

### PR DESCRIPTION
**Pull request by sg1asgard**
### What does it do?
I have fixed a component cosmetic issue where inside the Content History page it was showing as not disabled.
Eventually I chose to pass props at the level of the component and remove the styled component all together.
The <Flex> component supports passing down the current color prop. Also the <PlusCircle> icon supports pasing down props such as width and height.

### Why is it needed?
The disabled components don’t look like they are disabled. It makes it hard to understand that the fields in Content History are not editable.

### How to test it?
Steps to reproduce:
- Go to an entry with a component
- Click on the 3 dots
- Click on Content History (you will need a paid license)
- The Components should appear as disabled (grey text instead of blue).

### Related issue(s)/PR(s)
https://github.com/strapi/strapi/issues/20796

### CODE REVIEW

**Comment by markkaylor** [comment]
Hey @sg1asgard, thanks for the PR. Couple small things. 
- Could you sign the [contributor CLA](https://github.com/strapi/strapi/pull/22172#issuecomment-2478533800)
- A bit confused by the branch / PR name which seems to be referencing a different topic related to review workflows
- The commit lint isn't happy because you need to respect [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary). See [contrib docs](https://github.com/strapi/strapi/blob/develop/CONTRIBUTING.md#type). You can also include a domain ie `fix(history): apply disabled styles to strapi components`
- Your what does it do section is fine but feel free to provide more details here if you want for example: "I chose to leverage currentColor already on svgs to apply the correct colors..."
- Your how to test should show the happy path that proves you fixed the issue. For example: Go to the history page and components should appear as disabled (grey text instead of blue)

**Comment by markkaylor** [comment]
@remidej @simotae14 I worked closely with George on this yesterday so I would prefer you two gave it a review. We will squash and merge the commits here after approval and George will respect the convention on his next PR.

**Review by simotae14 — DISMISSED** [review]
The code looks great, well done...I need to test your solution

**Comment by lucasboilly** [comment]
@sg1asgard I just tested the branch and it looks much better!

There's things I would like to change, but that's my bad because I didn't give enough explanations [here](https://github.com/strapi/strapi/issues/20796).
- The background color should be `Neutral150`
- The border color should be `Neutral200`
- The icon color should be `Neutral500`
- The text color should be `Neutral600` (for accessibility)

The idea is to make it look like the other disabled fields 👍

**Comment by sg1asgard** [comment]
> The code looks great, well done...I need to test your solution

Much appreciated. Mark helped with good explanations and examples.

**Comment by sg1asgard** [comment]
> @sg1asgard I just tested the branch and it looks much better!
> 
> There's things I would like to change, but that's my bad because I didn't give enough explanations [here](https://github.com/strapi/strapi/issues/20796).
> 
> * The background color should be `Neutral150`
> * The border color should be `Neutral200`
> * The icon color should be `Neutral500`
> * The text color should be `Neutral600` (for accessibility)
> 
> The idea is to make it look like the other disabled fields 👍

@markkaylor @simotae14 What should I do? Go on and update the branch then update current PR? What's the right way I need to proceed forward?

**Comment by simotae14** [comment]
Hey @sg1asgard you just need to do the changes in your local branch, commit your changes, and push them again in your remote branch

**Review by remidej — APPROVED** [review]
looks good to me! but I'll let @lucasboilly confirm it matches his designs

**Comment by sg1asgard** [comment]
> Hey @sg1asgard you just need to do the changes in your local branch, commit your changes, and push them again in your remote branch

All done and pushed into the branch.

**Comment by lucasboilly** [comment]
@remidej I just had a call with @sg1asgard and I could check the design, that's all good 👍

Happy we could finally solve the issue, I think it was really confusing for users. Well done!

**Comment by remidej** [comment]
@sg1asgard do you have the permissions to Squash & Merge?

**Comment by markkaylor** [comment]
Thanks everyone I'll squash and merge!

**Comment by sg1asgard** [comment]
@markkaylor It seems all went well?

**Pull request merged**
