### PR TITLE
 Support for GeoJSON Content Type 

### PR DESCRIPTION
**Pull request by arogyakoirala**
My PR is a:
- [x] 🚀 New feature

Main update on the:
- [x] Admin
- [x] Plugin

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Background

**Context**
I have been working over the last few days with the strapi code-base add support for geographical data types (GeoJSON, to be more precise). I was pleased to see that strapi already had support for JSON, so I repurposed the code for `InputJSON` and `InputJSONWithErrors` components to create the GeoJSON content-type. To do so, I've followed the instructions posted on [this issue](https://github.com/strapi/strapi/issues/483#issuecomment-358971985) 

 **Why a separate GeoJSON content-type? (A real world use-case)**
Our organization primarily works with local governments in Nepal to build official portals that help them connect with their citizens. In doing so, some offices have realized a need to include a feature that allows them to visualize all of capital-projects for the fiscal year. See image below:

image

We want government officials to be able to upload geographic information on their own. Due to their limited technical knowledge, we found that the best way to get this done is by providing them with a user-interface to draw out the project.

I've gone ahead and created a component to facilitate the same. 

### Steps taken:

**Steps to display new input in the content type builder**

- To display my new field I have added it it in the `/plugins/content-type-builder/admin/src/containers/Form/forms.json`file.

- I've also populated the corresponding translations in the `/plugins/content-type-builder/admin/src/translations` folder. However, since I don't know language other than English, I've used english everywhere.

- I added another `switch-case` statement inside  `strapi/plugins/strapi-hook-mongoose/lib/utils/index.js` file for my new content-type (geojson), simply copy pasting the one for json. The plugin didn't run until I did that.

- I have also added images for my new content type in the `AttributeRow` and `AttributeCard` components.

- I was thus able to display my new attribute in the plugin (this might have an impact on the plugin's component)

**Using my new type in the content manager**

- I had to add a few new packages npm packages `(mapbox gl-js, @mapbox/mapbox-gl-js-draw, @mapbox/geojson-extent etc.)` and css files, I did not know how to add CSS files so i directly used the index.html file in  the `admin/admin/src/index.html` I know this is not optimal, what are my options?

  - When adding `@mapbox/mapbox-gl-js-draw` I ran into issues as I rebuilt the  `content-manager` plugin. So for my present purpose, I have served the CDN through my public directory `/public`, I’m aware this is not the best way to do things. Looking forward to your inputs here too.

- I also had to update the `containers/saga.js` and update the following line :
`const cleanedData = (attrType === 'json' || attrType==='geojson') ? record[current] : cleanData(record[current], 'value', 'id');`

- In the content manager plugin I modified the `Edit` container and its children in order to display my new field type.

- I created the `InpuGJSON` and `InputGJSONWithErrors` component and served them through the `Edit` component as suggested. 

### How it looks
image

### Features:
The GeoJSON input component allows a user to:
- Upload a `.geojson` file.
- Preview and modify uploaded `.geojson` in the browser.
- Draw custom points, lines and polygons (multiple points, lines and polygons also allowed) directly through the tool.
- Search for a place using a search box (using `mapbox-generic-geocoder` with OSM Nominatim), and zoom in to the location.

### Questions/Comments:
- What is the right way to use CDNs for JS and CSS in strapi? Im not sure if i followed standard practices for the same.
- Currently I've used [Maptiler Cloud](https://cloud.maptiler.com/) for hosting my vector tiles. This service allows upto 100000 free views in a month. If needed I can set up a map tile server for the same.
- I'm looking forward to someone from strapi going through my code and pointing out blunders, mistakes so that I can work on the same. I've submitted a pull request to facilitate the same. 

Best,
Arogya Koirala
[Kathmandu Living Labs](www.kathmandulivinglabs.org)

### CODE REVIEW

**Comment by soupette** [comment]
Hi @arogyakoirala thanks for you contribution it's really impressive!

I have tested it and I have noticed a few minor bugs:
- I'm unable to delete a created line or tile
- There are some propTypes errors in the console (string instead of object).

Do you want me to take a look?

Thanks a lot!

**Comment by arogyakoirala** [comment]
> Hi @arogyakoirala thanks for you contribution it's really impressive!
> 
> I have tested it and I have noticed a few minor bugs:
> 
>     * I'm unable to delete a created line or tile

Thanks for pointing this out. I've fixed this issue in my latest commit. In this process, I've also remove unwanted `codemirror` code from the InputGJSON Component.
 
>     * There are some propTypes errors in the console (string instead of object).

Where was this exactly? I wasn't able to find it. Maybe you can point me to where you see this?

> 
> Do you want me to take a look?

> Thanks a lot!

**Comment by lauriejim** [comment]
Hello! I will take time to review your PR this week.

**Comment by lauriejim** [comment]
Hello @arogyakoirala ! Thank you for this PR.

I just tried and I'm not able to finish a selection.
For a line and for a zone.
I'm also not able to use the search bar.

**Comment by arogyakoirala** [comment]
Hi @lauriejim, the issue around non-closing lines and zones should be fixed now. Also, regarding tiles, I've also added an ayttribution to the map and now changed the map source to OpenStreetMap Mapnik raster tiles, which are free forever. 

test

Let me know if there's anything else.

**Comment by buithuyen** [comment]
How about this PR you guys. This will be released in the next time?

**Comment by Aurelsicoko** [comment]
We can keep this PR open but we won't merge it to the core. It should be an external plugin. The only thing we will support is a simpler Map field where you can ping a location.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko @lauriejim if this should be moved to a plugin, is there any reason to keep this open?

**Comment by arogyakoirala** [comment]
That's cool, looking forward to the beta version. How do we make plugins? Will take a look at that, and try to build on this whenever I can. @Aurelsicoko

**Comment by lauriejim** [comment]
@arogyakoirala We will share with you how to do it when the development and the documentation will be done for the new architecture.

**Comment by lauriejim** [comment]
I close this issue since we will not merge it like that.
Will have to be adapted to the the architecture in an other PR.

Will let you know when it will be ready.
Thank you for your interest into Strapi

**Comment by Aurelsicoko** [comment]
Thank you @arogyakoirala for the good work! You helped us to understand the complexity behind this field and how we need to think about it for future implementation 👍

**Comment by sebaestel** [comment]
What is the status of this feature?

**Comment by derrickmehaffy** [comment]
It has not been added @sebaestel

**Pull request closed without merging**
