### PR TITLE
Revert "chore(deps): bump graphql-upload to 15.0.2"

### LINKED ISSUE #19114: Graphql Version Confict in 4.16.x
### Required System information

- Node.js version: v18.18.2
- NPM version:9.8.1
- Strapi version:4.16.2
- Database:sqlite
- Operating system:mac
- Is your project Javascript or Typescript:TS

### Describe the bug

After upgrading from 4.15 I got an error message after starting strapi

```
 Error: Cannot use GraphQLScalarType "Time" from another module or realm.                                      │
│                                                                                                                 │
│   Ensure that there is only one instance of "graphql" in the node_modules                                       │
│   directory. If different versions of "graphql" are the dependencies of other                                   │
│   relied on modules, use "resolutions" to ensure only one version is installed. 
```

### Steps to reproduce the behavior

1. Update to 4.16.2 having plugin-graphql installed

### Expected behavior

Strapi should start up as normal

### Additional context

My assumption is that 4.16.2 uses
```
    "graphql": "^15.5.1",
    "graphql-upload": "15.0.2",
```

Though graphql-upload 15.0.2 has a peer dependency on graphql 16.3.0.

Therefor graphql is installed two times.

### PR DESCRIPTION
**Pull request by Bassel17**
Reverts strapi/strapi#18811

This change was a breaking change for V4 users, we will revert it back 
and re-introduce this with the V5 version.

fixes #19114

### CODE REVIEW

**Review by derrickmehaffy — APPROVED** [review]
Lgtm ty

**Review by innerdvations — APPROVED** [review]
LGTM

As a side note, we are investigating if there's another way to patch this in v4 that doesn't involve breaking changes.

**Comment by derrickmehaffy** [comment]
> LGTM
> 
> As a side note, we are investigating if there's another way to patch this in v4 that doesn't involve breaking changes.

Good luck on that one if we want to stick to using this package, I tried in the past before but since the maintainer opted to switch to ESM only it kinda hurt anyone not using ESM

**Comment by derrickmehaffy** [comment]
FYI I ran some tests just to confirm that the issue in graphql-upload doesn't impact us.

If a malicious payload like the one mentioned for dicer is used we actually handle it properly and throw a 413 error code. I pumped about 200 requests per second at a very small instance and never managed to DDoS the application since the error gets caught by the koa-body parser and that's what throws the 413 error.

Basically any attempt to actually DDoS the application through an oversized payload should be handled.

**Comment by macnibblet** [comment]
@derrickmehaffy That doesn't help for those of us with compliance requirements tho, as all the scanners are going to flag out the graphql-upload dependency as a vulnerability Gitlab is flagging it as a critical issue, and the CVE scoring is a 9.8

So while in practise there is no issue, there is still an issue :'(

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy That doesn't help for those of us with compliance requirements tho, as all the scanners are going to flag out the graphql-upload dependency as a vulnerability Gitlab is flagging it as a critical issue, and the CVE scoring is a 9.8
> 
> So while in practise there is no issue, there is still an issue :'( 

Anything that solely relies on just CVE reports is a flawed system. We also have compliance but every system should have exceptions. Eg in our case SOC2 and we've made an exception for it.

It's extremely easy to submit false (and sometimes malicious) CVE reports and get them accept.

**Pull request merged**
