### PR TITLE
Full dependencies upgrade of strapi-generate-new

### PR DESCRIPTION
**Pull request by gustawdaniel**
#### Description of what you did:

Minor changes

| package         |   old   | new     |
|-----------------|:-------:|---------|
| @sentry/node    |  ^5.7.1 | ^5.24.2 |
| lodash          | 4.17.19 | 4.17.20 |
| node-machine-id | ^1.1.10 | ^1.1.12 |

Major changes

| package         |   old   | new     |
|-----------------|:-------:|---------|
| chalk           |  ^2.4.2 | ^4.1.0  |
| inquirer        | ^6.3.1  | ^7.3.3  |
| node-fetch      | ^1.7.3  | ^2.6.1  |
| ora             | ^3.4.0  | ^5.1.0  |
| uuid            | ^3.3.2  | ^8.3.0  |

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Will wait to see if TravisCI throws any errors, but there may be some issues jumping a ton of packages up so many versions without reviewing each one's changelogs. ;)

**Comment by gustawdaniel** [comment]
There are breaking changes in pino, because of update from 4 to 6 throws errors on:

```
  ● Test suite failed to run                                                                                                                                                                                 
                                                                                                                                                                                                             
    TypeError: pino.pretty is not a function                                                                                                                                                                 
                                                                                                                                                                                                             
      36 | };                                                                                                                                                                                                
      37 |                                                                                                                                                                                                   
    > 38 | const pretty = pino.pretty({                                                                                                                                                                      
         |                     ^                                                                                                                                                                             
      39 |   formatter: (logs, options) => {                                                                                                                                                                 
      40 |     return `${options.asColoredText(                                                                                                                                                              
      41 |       { level: 10 },                                                                                                                                                                              
                                                                                                                                                                                                             
      at Object.<anonymous> (packages/strapi-utils/lib/logger.js:38:21)                                                                                                                                      
      at Object.<anonymous> (packages/strapi-utils/lib/index.js:12:16)                                                                                                                                       
      at Object.<anonymous> (packages/strapi-plugin-upload/services/Upload.js:14:24)                                                                                                                         
      at Object.<anonymous> (packages/strapi-plugin-upload/services/__tests__/upload.test.js:1:23)        
```

connected issue:

> https://github.com/pinojs/hapi-pino/issues/61

so I did not change the version of pino. Anyway, you have one of the greatest contribution guide that I have ever seen.

**Comment by derrickmehaffy** [comment]
> so I did not change the version of pino. Anyway, you have one of the greatest contribution guide that I have ever seen.

I'm sure @alexandrebodin will be happy to see that feedback, thank you :hugs:

**Comment by alexandrebodin** [comment]
Hey, thanks for this PR, that's a bit hard for us to test all version bumps at once tbh. Would you mind making a PR with minor and patches version bumps first and another one with the major bumps ? the major needs a review of changelogs before we can approve :)

**Comment by gustawdaniel** [comment]
Can I simply attach documentation about breaking changes in the description of this pull request? Collecting all required docs would be simpler for me. I can do a review too if this package is not fully documented, probably at the end of this week.

**Comment by alexandrebodin** [comment]
sure if you feel it is easier for you that way :)

**Comment by alexandrebodin** [comment]
Hi, sorry but I'm going to have to close this PR as we can't validate this easily. We will keep the upgrades on our side to avoid any unwanted breaking changes :)

**Pull request closed without merging**
