### PR TITLE
Chore/fix iso locales

### PR DESCRIPTION
**Pull request by ivanThePleasant**
### What does it do?

Removes duplicate ISO locales 

### Why is it needed?

Duplicate ISO locales break UI of some elements

### How to test it?

Run the `getstarted` app. Watch the video below. The issue in the video should be gone.

https://www.loom.com/share/5c4a5d5683414bbab559c16ecb7a6ef8

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/14752

### CODE REVIEW

**Review by Convly — COMMENTED** [review]
I don't understand how duplicates made their way into the file. That's quite concerning :thinking: 
Would you mind adding a quick unit test that reads the locales file & make sure there are no duplicates in it? This way, we prevent the same issue from happening in the future. WDYT?

**Comment by ivanThePleasant** [comment]
@Convly good point! Done! 😊

**Review by Convly — APPROVED** [review]
LGTM

Might be worth it for Derrick to validate the issue has been fixed in his exact scenario.

**Review by derrickmehaffy — APPROVED** [review]
Lgtm

**Pull request merged**
