### PR TITLE
feat: add mapping property support for documentation plugin's open api generated docs

### PR DESCRIPTION
**Pull request by schimini**
### What does it do?

When the documentation plugin calls cleanSchemaAttributes to convert types between attributes and openapi data types it parses dynamic zones into an array of `anyOf` components (references to openapi schemas). 
The new implementation also generates the proper discriminator property [see openapi docs](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/) and mapping. We use the `__component` property to discriminate and the mapping grabs all compoonent names and maps them to the schemas already generated.

### Why is it needed?

Dynamic zones are reflected in the openapi docs generated as a anyOf using the list of possible components. For this to be more useful according the openapi spec we can use a discriminator to let the docs know what property is responsible for the discrimination and the mapping between the property values and schemas.

### How to test it?

Run any strap instance with a content type that has a dynamic zone. It should be generated with proper discriminator.
Taking examples from the get started example app: 

```
"dynamic_relations": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "#/components/schemas/BasicRelationComponent"
          },
          {
            "$ref": "#/components/schemas/BasicSimpleComponent"
          }
        ]
      },
      "discriminator": {
        "propertyName": "__component",
        "mapping": {
          "basic.relation": "#/components/schemas/BasicRelationComponent",
          "basic.simple": "#/components/schemas/BasicSimpleComponent"
        }
      }
    },
    
    
"dynamiczone": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "#/components/schemas/BasicSimpleComponent"
          },
          {
            "$ref": "#/components/schemas/BlogTestComoComponent"
          },
          {
            "$ref": "#/components/schemas/DefaultClosingperiodComponent"
          }
        ]
      },
      "discriminator": {
        "propertyName": "__component",
        "mapping": {
          "basic.simple": "#/components/schemas/BasicSimpleComponent",
          "blog.test-como": "#/components/schemas/BlogTestComoComponent",
          "default.closingperiod": "#/components/schemas/DefaultClosingperiodComponent"
        }
      }
    },
```

### CODE REVIEW

**Comment by schimini** [comment]
@oiorain Hi! 

Is there something I can do that can speed up the process / increase the likelihood of this being merged? ( adding tests, providing additional info etc ) 

Thanks :)

**Comment by jhoward1994** [comment]
Hi @schimini this looks good thank you!

The only thing I would do is lift `${pascalCase(component)}Component` out to be a constant, around line 141

**Review by jhoward1994 — APPROVED** [review]

**Comment by schimini** [comment]
> Hi @schimini this looks good thank you!
> 
> The only thing I would do is lift `${pascalCase(component)}Component` out to be a constant, around line 141

H, thanks for the review! I actually did something different that I feel might be useful. Just extracted the behaviour of this "name conversion". Let me know if it makes sense. If not I'll revert it. 

Also I'm thinking of doing a follow PR to resolve the proper value for `__component`, turning this: 
```  
"BasicSimpleComponent": {
  "type": "object",
  "properties": {
    "id": {
      "type": "number"
    },
    "__component": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "test": {
      "type": "string"
    }
  }
},
```

into this:

```  
"BasicSimpleComponent": {
  "type": "object",
  "properties": {
    "id": {
      "type": "number"
    },
    "__component": {
      "type": "string",
      "enum": ["basic.simple"]
    },
    "name": {
      "type": "string"
    },
    "test": {
      "type": "string"
    }
  }
},
```

This should make a log of code generation tools happy, but let me know if it should be a different PR, included in this one, or discarded. 
Thanks!

**Review by jhoward1994 — APPROVED** [review]

**Comment by jhoward1994** [comment]
Could you please fix the linting errors by running ` yarn dlx prettier --write packages/plugins/documentation/server/src/services/helpers/utils/clean-schema-attributes.ts` ?

I dont seem to have access to push here directly

**Comment by schimini** [comment]
@jhoward1994 I ran yarn lint thinking it would take care of all formatting stuff. bad assumption on my end. Just ran prettier:clean on it. ty

**Comment by schimini** [comment]
Oh I messed up. Not just file linting. I assumed everything would be squashed so I didn't care too much about commit message formatting. Should I rebase / amend the bad ones? 

Sorry

**Comment by jhoward1994** [comment]
Ah I see, no worries yeah if you could that should make the ci pass 

The format should be something like "[chore | fix | feat](affected_package_name): message"

**Comment by schimini** [comment]
🤦‍♂️ Sorry about all of this, didn't want to force push anything . ( I also didn't want to close the close the PR and open another one but GitHub didn't allow me to use the same one)

Here is the new one, passing both lint and commitlint: https://github.com/strapi/strapi/pull/21752 
@jhoward1994 won't happen again!

**Pull request closed without merging**
