### PR TITLE
Persian translation

### PR DESCRIPTION
**Pull request by Arsh1a**
**What does it do?**

Adds Persian translation to strapi-admin.

**How to test it?**
None

**Related issue(s)/PR(s)**
None

### CODE REVIEW

**Comment by ghonchesefidi** [comment]
Thanks for your contribution @Arsh1a . I hope it gets approved soon. I reviewed some of your phrases and they seams all correct in Persian.
Actually, I was going to translate it myself today!
@lauriejim  Can you please review and confirm?

**Comment by ghonchesefidi** [comment]
@Arsh1a I think you forgot to import the translation file to packages/strapi-admin/admin/src/translations/index.js
[Here is an example](https://github.com/strapi/strapi/pull/10345/files) how you can do it.

**Review by ghonchesefidi — CHANGES_REQUESTED** [review]
@Arsh1a I think you forgot to import the translation file to packages/strapi-admin/admin/src/translations/index.js
Here is an example of how you can do it.

**Comment by Arsh1a** [comment]
> @Arsh1a I think you forgot to import the translation file to packages/strapi-admin/admin/src/translations/index.js
> [Here is an example](https://github.com/strapi/strapi/pull/10345/files) of how you can do it.

I forgot to commit the index.js. Fixed now.

@lauriejim Can you please review? Would like to use the translation on my projects and continue translating plugins. I may work on RTLing the admin panel.

**Comment by derrickmehaffy** [comment]
Hi 👋  
We now have released the `v4`. As of now, the `v3` is in maintenance mode for 6 months. We will only be fixing critical and security issues on v3 from now on. 
I will go ahead and close this PR. Thank you for contributing to Strapi 🔥

**Pull request closed without merging**
