### PR TITLE
Update LeftMenuFooter style

### LINKED ISSUE #992: Language selector not visible
latest strapi

**Informations**

**What is the current behavior?**
When browser is german, the admin of strapi is automatically german (Even if specifically defined in the config to be english). The usual dropdown language selector is not visible in this case. There is no way to switch the language

**Steps to reproduce the problem**

**What is the expected behavior?**
The language dropdown should be visible.

**Suggested solutions**
I changed the chrome language settings to english, than the select field for languages appeared. Possibly something with the autodetect

----

- [x] I'm sure that this issue hasn't already been referenced

### PR DESCRIPTION
**Pull request by XcrossD**
I could not reproduce, but this should fix #992. Not accounting for the padding on each side which causes the footer to go out of bounds should be the problem here.

### CODE REVIEW

**Comment by soupette** [comment]
Hi @XcrossD I tried your solution but it doesn't solve #992.

Hi suggest the following modifications :

**Path -** `packages/strapi-admin/admin/src/components/LeftMenuFooter/index.js`

```js
function LeftMenuFooter({ version }) { // eslint-disable-line react/prefer-stateless-function
  return (
    <div className={styles.leftMenuFooter}>
      <div>
        <FormattedMessage {...messages.poweredBy} />
        <a href="https://strapi.io" target="_blank">v{version}</a>
      </div>
      <LocaleToggle />
    </div>
  );
}
```

Then in the `styles.scss` file

```
// Import
@import "../../styles/variables/variables";

.leftMenuFooter { /* stylelint-disable */
  position: absolute;
  width: 100%;
  bottom: 0;
  height: 3rem;
  
  // New properties
  display: flex;
  justify-content: space-between;

  padding-left: 15px;
  padding-right: 15px;
  line-height: 3rem;
  font-family: 'Lato';
  background-color: rgba(255, 255, 255, .02);
  font-size: 1rem;
  font-weight: 400;
  letter-spacing: 0.05rem;
  vertical-align: middle;
  color: $strapi-gray-light;

  a {
    color: #0097f7;
  }

  select{
    outline: none;
  }
}
```

**Comment by Aurelsicoko** [comment]
I'll certainly make some changes and move the flag in the header instead of the menu. It will be more visible and will avoid this issue.

screen shot 2018-04-23 at 18 11 26

**Comment by XcrossD** [comment]
So is there anything I could do here? If you're moving the flag to the top right corner I don't see the point of adding a commit for the suggestions made by @soupette. Sorry, I didn't help much.

**Comment by soupette** [comment]
@XcrossD do you mind updating your PR or do you want me to take care of it?

**Comment by XcrossD** [comment]
@soupette PR added. I was busy producing some debug information for some other issues.

**Pull request merged**
