### PR TITLE
Upgrade dependency version

### PR DESCRIPTION
**Pull request by filipesmedeiros**
#### Description of what you did:

Just updated the dependency in `package.json` for `strapi-plugin-graphql` from 4.17.11 to 4.17.12

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
I think you mixed two PRs together :thinking:

**Comment by filipesmedeiros** [comment]
@derrickmehaffy Oh damn, I didn't even know that was possible. Let me fix this!

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Oh damn, I didn't even know that was possible. Let me fix this!

Generally best to re-base instead of merging :wink:

**Comment by filipesmedeiros** [comment]
Not the prettiest PR, but should be good to go

**Comment by derrickmehaffy** [comment]
Pretty don't matter @filipesmedeiros thanks for the PR :)

**Comment by filipesmedeiros** [comment]
Ah while I have you, what's the workflow to deploying this new `package.json` to the npm package? As in, can I help, and if not, when can I run `npm upgrade` or something?

**Comment by derrickmehaffy** [comment]
> Ah while I have you, what's the workflow to deploying this new `package.json` to the npm package? As in, can I help, and if not, when can I run `npm upgrade` or something?

It will need to be merged in and released to a version. In the short term you can hack your own project package.json and forcefully resolve a new version.

https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

(I have no idea about npm directly as most of the maintainers and contributors like myself all use yarn)

**Comment by filipesmedeiros** [comment]
Btw, partially closes #6042

**Comment by filipesmedeiros** [comment]
Fo sho. I think I can get it done today! Do you want me to check other easy-to-fix warnings about deprecations and stuff?

**Comment by filipesmedeiros** [comment]
Correct me if I'm wrong, but aren't all the other lodash dependencies correct? I don't see any warnings, my `yarn audit` only tells me about this plugin.

**Comment by alexandrebodin** [comment]
You are right, the other have the carret sign first. We are lacking consistency there...  If you want to take a try at upgrading minor dependencies please go ahead :D

**Comment by filipesmedeiros** [comment]
Yeah I can try that, and also update this to instead of locking X.X.12, putting the carret sign on this one as well. Sounds good?

**Comment by filipesmedeiros** [comment]
Oh and by the way, Strapi (the root of the Yarn workspace) has a lot of missing peer dependencies. Should those be added to the workspace? Or left for each individual package?

**Comment by derrickmehaffy** [comment]
> Oh and by the way, Strapi (the root of the Yarn workspace) has a lot of missing peer dependencies. Should those be added to the workspace? Or left for each individual package?

This is something I see come in slack often, most of which relates to the Admin.

**Pull request merged**
