### PR TITLE
Fix relation detection OneToManyMorph for OneToMany

### PR DESCRIPTION
**Pull request by lauriejim**

### CODE REVIEW

**Comment by kamalbennani** [comment]
Thanks @lauriejim for the fix. But I'm little be curious how this thing works before. I mean is there a way to implement unit test for this utility functions ?

**Comment by lauriejim** [comment]
Hi @kamalbennani this issue is, we loop on each models witch have a specific `via` key. And if two models have a relation with the same model and the same via key, the relation detection fail.

**Comment by victorlambert** [comment]
Hey @lauriejim, thanks for fixing this issue.
I was wondering if the `via` property was required on oneToMany relations like this one, on `Article.settings.json` : 
`//Path — ./api/user/models/User.settings.json.
{
  "attributes": {
    "articles": {
      "collection": "article",
      "via": "author"
    }
  }
}
//Path — ./api/article/models/Article.settings.json.
{
  "attributes": {
    "author": {
      "model": "user",
      "via": "articles"
    }
  }
}`
This is how we got this issue, and this is how the model is generated from the admin ui.
In the docs, there is no `via` property to demonstrate the oneToMany relations.

**Comment by Aurelsicoko** [comment]
@victorlambert The `via` attribute is only required in the `many` side. In your case, in the `User.settings.json` model.

**Pull request merged**
