### PR TITLE
Fix connection issue with Heroku Postgres

### LINKED ISSUE #2522: Connecting to Heroku PostgreSQL
**Informations**
- **Node.js version**:  v10.14.2
- **NPM version**: 6.4.1
- **Strapi version**:  3.0.0-alpha.17
- **Database**: PostgreSQL
- **Operating system**: Windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Can not connect to heroku PostgreSQL

**Steps to reproduce the problem**
Running the following command in the terminal:

`strapi new Test --dbclient=postgres --dbhost=herokuHost --dbport=5432 --dbname=herokuDbName --dbusername=herokuUsername --dbpassword=herokuPassword --dbssl=false --dbauth=herokuDbName
`

Error returned: 

`Start creating your Strapi application. It might take a minute, please take a coffee`
`Lets configurate the connection to your database:`
`Database determined by CLI args: postgres`
`Testing database connection...`
`Database connection has failed! Make sure your "herokuDbName" database exist.`

**What is the expected behavior?**

Connection is created successfully 

**Suggested solutions**

...

### PR DESCRIPTION
**Pull request by mohamead**
My PR is a:
- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #2522 
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

Main update on the:
- [ ] Admin
- [ ] Documentation
- [x] Framework
- [ ] Plugin

Updated `strapi new` command to ask for enabling SSL regardless of database-type. This is done because remote connection to Heroku Postgres is requiring SSL to be enabled ref -> https://devcenter.heroku.com/articles/connecting-to-heroku-postgres-databases-from-outside-of-heroku#ssl

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello @mohamead! Thank you for the details to make it work with Heroku PG database.
But actually if you change `options` to `settings` it will break where `options.ssl` it used.
Because it used somewhere in the code (in this case to handle ssl connection for mongodb databases)

So to make it work correctly you will have to update `strapi-hook-knex` 
`_.get(connection.settings, 'ssl') || false,` => `_.get(connection.options, 'ssl') || false,`

**Comment by mohamead** [comment]
@lauriejim thank you for the feedback. Unfortunately the modification mentioned did not resolve the issue https://github.com/strapi/strapi/issues/2522. It is still failing with the same error..

Can we consider updating `before.js` in `strapi-generate-new` from
`scope.database.options.ssl = _.toString(answers.ssl) === 'true';` =>
`scope.database.settings.ssl = scope.database.options.ssl = _.toString(answers.ssl) === 'true';`

The change seems to work in windows, and not breaking where `options.ssl` is used..

**Comment by lauriejim** [comment]
OKay dac!

**Comment by mohamead** [comment]
Likewise!

**Pull request closed without merging**
