### PR TITLE
chore(e2e): store test traces for failed tests as GH action artifacts

### PR DESCRIPTION
**Pull request by gu-stav**
### What does it do?

- Stores traces for failed e2e tests
- Uploads traces as GH Action artifact

### Why is it needed?

I am pretty lost why https://github.com/strapi/strapi/pull/18065 keeps failing and hope traces give me some hints.

### CODE REVIEW

**Comment by innerdvations** [comment]
Do you know how much impact this will have re: storage on github? I recall when I tried adding it before there was some discussion for the amount of data it would produce.

**Comment by gu-stav** [comment]
> Do you know how much impact this will have re: storage on github? I recall when I tried adding it before there was some discussion for the amount of data it would produce.

I don't, but I would argue we need a way to retrieve these traces. If the action works properly they are only recorded for failed tests. One trace on my machine is about ~300kB.

If storage is a concern, I'll add `retention-days: 1`. 👍🏼

**Comment by innerdvations** [comment]
Sounds good to me, we can see the impact and then increase the retention to be longer if it isn't an issue.

**Comment by joshuaellis** [comment]
I originally turned this off because if a trace happens during a test suite the entire server resets itself thinking there's a file change – i don't know why and i didn't know how to stop it, it seemed like we had a blocklist instead of an allowlist somewhere...

**Comment by gu-stav** [comment]
> I originally turned this off because if a trace happens during a test suite the entire server resets itself thinking there's a file change – i don't know why and i didn't know how to stop it, it seemed like we had a blocklist instead of an allowlist somewhere... So to be clear, we should ensure this doesn't happen anymore cause _everything_ will fall apart if one test fails 🥲

Thanks for these insights. I'll brake a test and run the whole suite to see what happens, because locally it seemed fine.

Do you think this could have something to do with the concurrency? If so I think we could remove it entirely, because running 3 instances in parallel already crashes my machine completely and I believe over time we will have much more than 3 🙈

**Comment by joshuaellis** [comment]
> > I originally turned this off because if a trace happens during a test suite the entire server resets itself thinking there's a file change – i don't know why and i didn't know how to stop it, it seemed like we had a blocklist instead of an allowlist somewhere... So to be clear, we should ensure this doesn't happen anymore cause _everything_ will fall apart if one test fails 🥲
> 
> Thanks for these insights. I'll brake a test and run the whole suite to see what happens, because locally it seemed fine.
> 
> Do you think this could have something to do with the concurrency? If so I think we could remove it entirely, because running 3 instances in parallel already crashes my machine completely and I believe over time we will have much more than 3 🙈

no i think it's to do with the file watcher the server has 👀

**Comment by gu-stav** [comment]
Oh I see what you mean @joshuaellis: not playwright restarts, but Strapi itself. I have reported that as an issue https://github.com/strapi/strapi/issues/18196 and will limit the traces for the CI for now, which is stopping anyways after the first failed test, so this should be fine.

**Review by joshuaellis — APPROVED** [review]

**Pull request merged**
