### PR TITLE
Virtual model fields

### PR DESCRIPTION
**Pull request by Tomaszal**
#### Description of what you did:

Basically I've wanted to implement exactly what @wysher was trying to document in #6433. However from what I could tell there was no way to have an attribute field that doesn't generate a column in the database. So to achieve that I implemented a "virtual" field attribute. When it's set to true the database will not try to create a column for it.

Master branch also for some reason didn't have the lifecycles working correctly so I had to quickly fix that to make this work. I've added an example in the address model of the getstarted example.

I'm not sure if this is the ideal implementation, but it's the only way I could think of. Also this currently only works with bookshelf. I don't have any experience with mongoose so it's better if someone else does it if they deem this a good addition.

Overall I think this is very useful. Doesn't add too much to API functionality, however it was really needed for me for the admin panel. Since before this it's only possible to display the actual fields in the database, which is often not what you want.

### CODE REVIEW

**Comment by wysher** [comment]
We discussed it with @alexandrebodin few weeks ago and AFAIR we agreed that strapi should not have special case for virtual fields.

Also we changed `Virtual` to `Composed` fields to remove this confusion.
But I'm not sure what strapi team have to say about this. @alexandrebodin any comments?

**Comment by Tomaszal** [comment]
I saw the discussion about changing the name to `Composite` fields. However I think in this case `Virtual` makes more sense, since it's not saving anything to the database.

Why were you against having virtual fields though? Since to me this seems like the most straightforward way to have custom dynamic fields in the admin panel.

**Comment by Tomaszal** [comment]
Ah right, sorry, that makes more sense now. Fixed it.

**Comment by alexandrebodin** [comment]
Hi, As is we cannot move forward with this PR

It will required to support mongoose and needs to be discussed in a RFC first. Please start by work on an RFC over in http://github.com/strapi/rfcs.


I'm closing this for the time being ;)

**Pull request closed without merging**
