### PR TITLE
adds caching option for strapi-provider-upload-local (#6645)

### PR DESCRIPTION
**Pull request by alexkainzinger**
### What does it do?

adds caching (http-headers, lru-cache if needed) option for strapi-provider-upload-local.

### Why is it needed?

Currently uploaded images are loaded from the local provider over-and-over again without any caching options. This adds support for it. Especially useful is the "ETag" in that case, which would save a lot of bandwidth.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/6645 + my own need of caching support for uploaded files

### CODE REVIEW

**Comment by dneckel** [comment]
Exactly what I was looking for!
+1 for getting this merged rather sooner than later

**Comment by dneckel** [comment]
@derrickmehaffy Is there any way to get this reviewed?
I tested it and it worked great for me also nice documentation :)
Thank you in advance!

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Is there any way to get this reviewed?
> I tested it and it worked great for me also nice documentation :)
> Thank you in advance!

I'll need the @strapi/maintainers to review it first since it's modifying a core package, I only review the documentation side of things.

**Comment by alexandrebodin** [comment]
Hi,

I think this is something that should stay in userland if possible. You could do a middleware that would overload the default behavior.

**Comment by iksent** [comment]
This PR adds an option to enable caching, so the default behavior (no caching) won't be changed, is not it?

**Comment by alexkainzinger** [comment]
That also was my intention. 

I used https://github.com/strapi/strapi/issues/6645#issuecomment-645217698 as an approach, but quickly found out that with `koaStatic()` there are too little options for caching. This would make it hard to  stay in userland and use `koaStaticCache()` which resolves the exact issue.

But if there is no chance of getting it merged this way, I will have to readdress this 👍 thx

**Comment by dneckel** [comment]
I used the middleware overload approach now but to me it seems like this is something that should not be as "difficult" to figure out. I am a big fan of doing stuff via config files I guess but I also see the problem when there are so many different upload providers.
I think a guide in the documentation describing the middleware overload for this case would be great for developers who get started with Strapi.

**Comment by 17forever** [comment]
You saved me!

**Comment by derrickmehaffy** [comment]
@alexandrebodin is the final decider, but if this absolutely needs to go in userland we can look at adding that to the documentation. 

We are a docs change freeze for the moment though.

**Comment by alexandrebodin** [comment]
Hi, a quick word to clarify a point. I'll come back to it with a fresh eye after the end of year :) 

When I say userland I didn't mean every developer should do it on its own :) 
I meant creating a npm package like `strapi-middleware-upload-plugin-cache`  of some sort that will add the caching behavior on top of the upload plugin. 

The idea is to keep the modularity  as different caching approaches can be implemented and it would be really easy to just npm install the one you need / want.

**Comment by derrickmehaffy** [comment]
> Hi, a quick word to clarify a point. I'll come back to it with a fresh eye after the end of year :)
> 
> When I say userland I didn't mean every developer should do it on its own :)
> I meant creating a npm package like `strapi-middleware-upload-plugin-cache` of some sort that will add the caching behavior on top of the upload plugin.
> 
> The idea is to keep the modularity as different caching approaches can be implemented and it would be really easy to just npm install the one you need / want.

That makes more sense to me @alexandrebodin I believed you meant it needed to be done via extensions, but a custom middleware makes a lot more sense.

**Comment by alexkainzinger** [comment]
@alexandrebodin ahh that clarifies a lot! ^^  Hopefully I got some time at the beginning of next year so I can re-do it as you stated by creating a ``middleware-plugin``. 

@derrickmehaffy thanks for re-addressing this PR 👍

**Comment by derrickmehaffy** [comment]
> @alexandrebodin ahh that clarifies a lot! ^^  Hopefully I got some time at the beginning of next year so I can re-do it as you stated by creating a ``middleware-plugin``. 
> 
> @derrickmehaffy thanks for re-addressing this PR 👍 

Thanks :)

Going to mark this closed, when you get time if you plan to build the Middleware feel free to submit it on our [awesome-strapi](https://github.com/strapi/awesome-strapi) repo!

**Comment by alexkainzinger** [comment]
Really wanted to finish this, so I quickly created a plugin which is now available as [``strapi-middleware-upload-plugin-cache``](https://github.com/alexkainzinger/strapi-middleware-upload-plugin-cache).
Basically same idea and code, packet into one configurable middleware 👍

**Pull request closed without merging**
