### PR TITLE
Adding documentation for M1 users

### PR DESCRIPTION
**Pull request by mfrachet**
### What does it do?

- Provides information to M1 users on how to fix sharp troubles when setting the project up.
- Incrementing a title number (there was two "5")

### Why is it needed?

M1 users may not be able to run the project in dev mode without that.

### Related issue(s)/PR(s)

Not in this repository but in the sharp's one: https://github.com/lovell/sharp/issues/2460

### Env

Tested on Node v12.20.1 / yarn 1.22.10

### CODE REVIEW

**Review by soupette — APPROVED** [review]
LGTM

**Review by derrickmehaffy — APPROVED** [review]
English looks good to me, can't validate content without hardware to test.

**Comment by mfrachet** [comment]
@derrickmehaffy how can I help you in that scenario? Do you need a pairing session (well, now that I've run the fix, not sure how to get back 😓 ) ?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy how can I help you in that scenario? Do you need a pairing session (well, now that I've run the fix, not sure how to get back  ) ?

It's alright :) since we have two in the team that can validate the fix, I'm not needed to validate. We might want to have a couple people in the community test as well. I'm posting a link to this PR on the resources I've seen within the community to confirm.

**Comment by derrickmehaffy** [comment]
This pull request has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/apple-silicon-m1-chip/1565/3

**Pull request merged**
