### PR TITLE
Create CTs, middlewares, policies folders during plugin generation

### PR DESCRIPTION
**Pull request by sunnysonx**
### What does it do?

1) Added the following folders (and default index.js empty export file) when generating a plugin by using CLI Generator:
- `/src/plugins/{pluginName}/server/content-types`
- `/src/plugins/{pluginName}/server/middlewares`
- `/src/plugins/{pluginName}/server/policies`

2) Imported them in strapi-server.js

### Why is it needed?

When you create a plugin through CLI, by default it will contain/generate all directories, except `content-types/middlewares/policies`. There are also not imported in the strapi-server.js.

This is kinda confusing because when you create a new `content-type/middleware/policy` inside the plugin it is not imported and these do not have index.js files.

### CODE REVIEW

**Comment by zettabyte918** [comment]
Plugins can't have content Type on default

**Comment by derrickmehaffy** [comment]
> Plugins can't have content Type on default

What?

**Comment by sunnysonx** [comment]
> Plugins can't have content Type on default

It just creates export files that are needed for future content type creation.

**Comment by zettabyte918** [comment]
> > Plugins can't have content Type on default
> 
> What?

I mean manually i add models in my plugins

**Review by Elhebert — APPROVED** [review]
Thanks for the PR 👌

LGTM 👍

**Pull request merged**
