### PR TITLE
feat(users-permissions): Add Auth0 provider

### LINKED ISSUE #403: How to integrate with auth0?
Hi, we have a client who is using auth0 as their user system service. 
Can strapi integrate with [Auth0](https://auth0.com)?

### PR DESCRIPTION
**Pull request by Heziode**
### What does it do?

This PR add the support of Auth0 provider.

### Why is it needed?

Some people (me included) wants to use Auth0 with Strapi.

### Related issue(s)/PR(s)

This will definitely close #403

### CODE REVIEW

**Review by derrickmehaffy — DISMISSED** [review]
Docs look good to me, please do create a PR to https://github.com/strapi/strapi-examples

Specifically for the: https://github.com/strapi/strapi-examples/tree/master/login-react

**Comment by Heziode** [comment]
Ok,

I do that tomorrow.

**Comment by derrickmehaffy** [comment]
> Ok,
> 
> I do that tomorrow.

No rush :)

**Comment by Heziode** [comment]
@derrickmehaffy PR created on `strapi-examples`: strapi/strapi-examples/pull/171

However, the Strapi doc seems outdated according to the `strapi/strapi-examples/login-react`. Indeed, "The redirect URL to your front-end app" is not nedeed anymore. And the link `http://localhost:1337/admin/plugins/users-permissions/providers` should be `http://localhost:1337/admin/settings/users-permissions/providers`.

I have do my doc according to the others providers tab, but they all need to be updated to be consistent (and to work with `strapi-examples`).

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy PR created on `strapi-examples`: [strapi/strapi-examples/pull/171](https://github.com/strapi/strapi-examples/pull/171)
> 
> However, the Strapi doc seems outdated according to the `strapi/strapi-examples/login-react`. Indeed, "The redirect URL to your front-end app" is not nedeed anymore. And the link `http://localhost:1337/admin/plugins/users-permissions/providers` should be `http://localhost:1337/admin/settings/users-permissions/providers`.
> 
> I have do my doc according to the others providers tab, but they all need to be updated to be consistent (and to work with `strapi-examples`).

Ah yes you are right, when we changed the U&P path in v3.1.5, can you by chance tweak that in the docs within this PR also? Easier to handle it all at once ;)

**Review by derrickmehaffy — APPROVED** [review]
Doc changes look good, ty

**Comment by Heziode** [comment]
No news about code reviewer ?

**Comment by derrickmehaffy** [comment]
@Heziode no review news yet, we are actually going through some internal discussion about building out our review process right now. They will take a look once they have some time :)

**Review by Jp-watcher — APPROVED** [review]

**Comment by Rowanto** [comment]
Any chance this is going to be merged in next 1-2 weeks?

**Comment by Rowanto** [comment]
Is this still planned to be merged?

**Comment by alexandrebodin** [comment]
hi @Heziode the documentation has been move to the https://github.com/strapi/documentation repo :) can you create a PR there with the doc content. I'll review the PR asap

**Review by alexandrebodin — COMMENTED** [review]
Waiting for the doc & conflict fix  to be merged but tested it and works well 👍

**Comment by Heziode** [comment]
👋
It' noted, I'm on it. I'll get back to you in the weekend.

**Comment by Heziode** [comment]
@alexandrebodin is done.

Conflict solved.
PR on doc: https://github.com/strapi/documentation/pull/81

**Comment by alexandrebodin** [comment]
Hey @Heziode your PR now contains 400+ commits :) I think there was a small issue in the update process ;) Let me know when ready ;)

**Comment by Heziode** [comment]
I often get stuck in resolving conflicts process...
It should be good now.

**Review by alexandrebodin — APPROVED** [review]

**Comment by alexandrebodin** [comment]
Thank you for this contribution @Heziode 💯

**Comment by derrickmehaffy** [comment]
This pull request has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/new-release-strapi-v3-4-5/2446/1

**Pull request merged**
