### PR TITLE
Fix sanity check for @casl/ability upgrade #12232

### PR DESCRIPTION
**Pull request by denik1981**
### What does it do?
- Works on solving issue #12232. 
- Normalizes the codebase for the BREAKING CHANGES introduced in v5.1.0 of @casl/ability 

### Why is it needed?
- npm v8 installations are not working because of @casl/ability v4 that does not support it and makes strapi fail on the installation.

Describe the issue you are solving.

### How to test it?

- Unit and e2e tests were all passed to check for the changes made in this PR. 

To assert for a green light on an npm v8 installation (#12232) I used "verdaccio" to mimic a public npm registry locally so I can have a registry to publish forth and pull back. After that I went with the standard worflow on how to create a strapi app but with npm (--use-npm flag). 

The steps I used:
- `npm i -g verdaccio` 
- `npm i -g npm` - install npm@latest
- `verdaccio` - opens the registry and starts listening at http://localhost:4873
- `npm set registry http://localhost:4873`  ​
- `cd path/to/root/of/strapi/monorepo/`
- `lerna publish --force-publish --no-git-tag-version --no-push` - publishes strapi to verdaccio
- `cd ..` 
- `npx create-strapi-app my-strapi-app --quickstart --use-npm` - install strapi using npm pulling from verdaccio 
 `App is instaling ...`
 
Remember to put your npm registry back to npm when finished
 
### Related issue(s)/PR(s)

#12232

### Aditional Info

There are three commits that merge into one: 
- "HEAD~2" has all the code changes for the source files.
- "HEAD^" has comments related to the modifications in "HEAD~2".
- "HEAD" wipes out all the comments introduced in "HEAD^" and leaves an exact copy of "HEAD~2". 

### RFC
A ci test could be added to run on a relaxed schedule to test against package managers as well. Currently, tests are running against node versions and databases but package managers are a source of problems as well.

### CODE REVIEW

**Comment by denik1981** [comment]
#12265 I have just submitted a PR with the needed changes.

**Comment by cschuller** [comment]
+1 Very good idea to use "verdaccio" for an integration test!

**Comment by derrickmehaffy** [comment]
> Can someone, with access to the security logs, help me know what's the reason that the last step failed or/and what can I do to fix it? With no information, I feel unknowledgeable of where to look.

It's fine, they have passed now

**Comment by denik1981** [comment]
No worries. It fixed along.

**Comment by alexandrebodin** [comment]
Really appreciate this !

If I remember correctly the latest casl version add a breaking change on conditions which was breaking our custom conditions feature.

By any chance have you tried to use the custom conditions in your code to validate we can still create some and we still have the same operators as the ones we document ? @Convly  can you take a look at this?

**Comment by denik1981** [comment]
@alexandrebodin Yes, I deeply check the conditions in your code before committing this.

What happens here is that CASL changed the signature of an important utility function that is consumed by the sanity checks of Strapi. Specifically, it adds a new positional argument called `fields from`.

**BEFORE**
```
const permittedFields = permittedFieldsOf(ability, actionOverride, subject,);
```

**AFTER**
```
const permittedFields = permittedFieldsOf(ability, actionOverride, subject, {
        fieldsFrom: rule => rule.fields || [],
      });       
```

If you follow the docs of the BREAKING CHANGE you will see that this was made because CASL was returning an empty array when the permissions were set to "all" fields. And for that reason, the later conditions in place of the strapi code are checking for this to address that missing feature. [`isEmpty(peremitedFields)`]

 ```
 const shouldIncludeAllFields = isEmpty(permittedFields) && !hasAtLeastOneRegistered;
 ``` 
 
CASL is not giving you any way to return all the fields for that entity so what it is doing here is returning what it already knows from the fields defined on its rules but keeps returning "undefined" when the permissions are set to "all". 

The proposal from CASL BREAKING CHANGE docs is that when you are querying for "all" permissions, the return value will be `undefined || [...allFields]` BUT all fields is something that needs to be calculated by the user beforehand. Thus what CASL suggests the user do beforehand is what Strapi is already doing on the latter. 

The problem to traverse the entity before calling this permittedFields CASL utility function to extract all the fields is that the logic already in place is much more complicated than that and does much more. So to say it will be more costly and will require a full refactor of the sanity code. You can review that on the code.

So to normalize CASL BREAKING CHANGES with the previous version and prevent a costly refactor the best way to do it will be to keep returning an empty array when the permissions are set to "all" fields. The code proposed in this PR is EQUIVALENT to how CASL was working before and **imho** is the best way to address this quickly based on that the main issue here is that NPM 8 users are not being able to install strapi because CASL needs an upgrade due that npm 8 is a non-supported PM engine.

**Review by Convly — APPROVED** [review]
Hi, thanks for the detailed report and analysis, I've tested the code and it looks like it works as intended (also tested with custom conditions).

Thanks for your commitment, LGTM :tada:

**Comment by Convly** [comment]
_(could you resolve the conflict on the `yarn.lock` before we can merge though :sweat_smile: )_

**Comment by denik1981** [comment]
> _(could you resolve the conflict on the `yarn.lock` before we can merge though sweat_smile )_

Yes, done.

**Comment by alexandrebodin** [comment]
Love that kind of explanation. Kudos! 👍

**Review by Convly — APPROVED** [review]

**Pull request merged**
