### PR TITLE
fix: resolve internal plugins from the strapi pkg

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Tentative fix for https://github.com/strapi/strapi/issues/20298

### How to test it?

Create a new app with the experiemental linked below

### Related issue(s)/PR(s)

Closes https://github.com/strapi/strapi/issues/20298

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Prerelease job: https://github.com/strapi/strapi/actions/runs/10091469460

**Review by innerdvations — COMMENTED** [review]
I haven't been able to recreate the actual bug in a real world situation, so let's wait to see what the results are from users reporting it before merging.

Code looks good. I don't like the implicit/circular dependency that this leaves in place, so I'll still keep a task open to later restructure how the plugin loading is handled.

**Comment by alexandrebodin** [comment]
> I haven't been able to recreate the actual bug in a real world situation, so let's wait to see what the results are from users reporting it before merging.
> 
> Code looks good. I don't like the implicit/circular dependency that this leaves in place, so I'll still keep a task open to later restructure how the plugin loading is handled.

Yeah I have this as v6 refactorings happy to give you the details

**Review by innerdvations — APPROVED** [review]
Anyway, LGTM!

**Pull request merged**
