### PR TITLE
feat(document-service): document id to id

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?

Our original approach on the doc service was to switch the `documentId` attribute coming from db to be renamed to `id`.
That change added unnecessary complexity on our side, but also on the user side, as they would internally have apis with different syntax:

```ts
const entry = strapi.db.query(uid).findOne(1);
// -> { id: 1, documentId: 'doc-id', ...}

strapi.documents(uid).update(entry.documentId, {...})
// -> {id: 'doc-id'}  <- This switch can be confusing
```

While from the api perspective it was clean to have a single id, there will be cases when the user relies on db queries, and doing so and having the id switch was confusing.

This approach keeps the syntax the same as the DB layer, so things like this are possible:
```ts
const category = strapi.db.query('category').findOne(1);
// -> { id: 1, documentId: 'category-doc-id', ...}


strapi.documents('article').update('article-doc-id', {
	data: { 
	    category: category // Can properly connect relations without any syntax switch
	}
})
// -> { id: 1, documentId: 'article-doc-id', category: { id: 1, documentId: 'category-doc-id' }
```

The Content API will only expose the documentId and not the entry id, but the document service will expose both.

### CODE REVIEW

**Comment by Marc-Roig** [comment]
We can keep this as the main PR of this change, I will be working on fixing all the doc id references in the backend side

**Comment by joshuaellis** [comment]
We should figure out here what we want to do with `id` and `documentId` in the list view. Currently, we display the `id` still, we can't show `documentId` because it's not on the schema which  to be honest i don't see the value in either. IMHO I think showing the `id` now is wrong because we don't _really_ want people to use them.

So:

* Should we be omitting this from the content-type configuration?
* Do we need a migration to be added for this?

**Comment by Marc-Roig** [comment]
@joshuaellis good point, I am going to add a ticket to do this, will check but I believe we hardcode the id into the configuration, so I don't think it will require a migration.
And also wonder what happens if a user will be able to not display any column in the list view if we do this.

**Comment by joshuaellis** [comment]
> And also wonder what happens if a user will be able to not display any column in the list view if we do this.

The UI breaks cause im bad at my job 🙃

**Pull request merged**
