### PR TITLE
feat: register admin routes like any other plugin

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?

Change how admin routes are defined.

Before:

```js
module.exports = [
  {
    method: 'GET',
    path: '/providers',
    handler: 'authentication.getProviders',
	...
  },
]
```

Now: 
```js
module.exports = {
	type: 'admin' // We will be able to create content-api routes like this
	routes: [
	  {
	    method: 'GET',
	    path: '/providers',
	    handler: 'authentication.getProviders',
		...
	  },
	]
}
```

### Why is it needed?

This way EE features can declare content-api routes. 

Some thoughts:
- We assumed any route defined in admin would be for the admin plugin
- EE is still in the admin folder, which makes things a bit complicated
	-  Until we move the EE folder somewhere else, this can be a good tradeoff.
- This syntax is the same as for any other plugin.

### CODE REVIEW

**Comment by joshuaellis** [comment]
Should DTS use this? It would fix the circular dep.

**Comment by Marc-Roig** [comment]
@joshuaellis Is this a package json dependency you mean?
I think this would not fix it if it's about that, this only defines the list of endpoints a package exposes.

**Review by alexandrebodin — APPROVED** [review]
⚠️ I  Only read the code and did not run QA on it. 

Makes sense to do this regardless of EE anyway as we build features in Strapi. Package name would probably need to be challenged. 

That being said we could consider the feature requiring this should be internal plugins to decouple them from the admin code.

**Comment by Marc-Roig** [comment]
> I Only read the code and did not run QA on it.
We will make sure to QA everything here , thank you for the review! 

> That being said we could consider the feature requiring this should be internal plugins to decouple them from the admin code.
100%, and because of that I think the EE folder should live outside Admin, being a different repo, different package, or just separate plugins that can be flagged as EE.

**Comment by Marc-Roig** [comment]
@joshuaellis @innerdvations I think that is already possible

https://github.com/strapi/strapi/blob/main/packages/core/admin/server/routes/transfer.js

Is anything preventing these routes being defined inside `@data-transfer`? I see the data-transfer pakcage does not have the common /admin /server folders.

**Comment by alexandrebodin** [comment]
> 

Data transfer isn't a plugin (nor implemented as such) but it could be a good way to architecture it as if it was like we do for email & upload to remove the circular dep 👍

**Comment by joshuaellis** [comment]
Ping @Convly @marcoautiero might be one to look at addressing in future iterations of DTS?

**Comment by Convly** [comment]
Hey, the current design for @strapi/data-transfer is that it's a library exposing an API to build transfer processes, the routes defined in the admin are admin-related features and don't belong in the DTS package (which is unaware of Strapi).
Happy to discuss more about the package design if you want :slightly_smiling_face:

**Comment by joshuaellis** [comment]
> which is unaware of Strapi

I'd disagree with this considering you import `@strapi/strapi` and directly tap into the entity service? I do think we need to solve this circular dependency have you guys talked about it at all? 🤔

**Comment by Convly** [comment]
> I'd disagree with this considering you import `@strapi/strapi` and directly tap into the entity service? I do think we need to solve this circular dependency have you guys talked about it at all?

Yeah, I hesitated before saying this because it's not 100% true. I should have said the core transfer API doesn't know about Strapi, only some data providers' implementation knows about Strapi logic. Hence the dependency. In a perfect world data source and destination would be hosted in provider packages and used by the core transfer API to run transfer.

**Comment by Convly** [comment]
More context: The DTS APIs are used by the admin, CLI, and can also be used independently, that's another reason why it's a library and not a plugin.
To summarize, the DTS package provides the utils to build transfer processes & transfer features in other places (admin, CLI, server, etc...)
What's annoying is that we're also providing default source/destination providers in the same package (that can rely on other dependencies)

**Comment by alexandrebodin** [comment]
> More context: The DTS APIs are used by the admin, CLI, and can also be used independently, that's another reason why it's a library and not a plugin. To summarize, the DTS package provides the utils to build transfer processes & transfer features in other places (admin, CLI, server, etc...) What's annoying is that we're also providing default source/destination providers in the same package (that can rely on other dependencies)

It would be fairly easy to argue the default providers don't have their place in the core data-transfer package but rather the cli commands that is actually really using them

**Comment by Convly** [comment]
> > More context: The DTS APIs are used by the admin, CLI, and can also be used independently, that's another reason why it's a library and not a plugin. To summarize, the DTS package provides the utils to build transfer processes & transfer features in other places (admin, CLI, server, etc...) What's annoying is that we're also providing default source/destination providers in the same package (that can rely on other dependencies)
> 
> It would be fairly easy to argue the default providers don't have their place in the core data-transfer package but rather the cli commands that is actually really using them

While I agree with moving the providers out of the DTS package, they need to be used by both strapi/core & strapi/admin

**Comment by Boegie19** [comment]
Would it not be better to add them to packages/providers and basically handle it the same as any other provider
then add hooks everywhere you need it and make sure the provider calls into the hooks

**Comment by alexandrebodin** [comment]
> > > More context: The DTS APIs are used by the admin, CLI, and can also be used independently, that's another reason why it's a library and not a plugin. To summarize, the DTS package provides the utils to build transfer processes & transfer features in other places (admin, CLI, server, etc...) What's annoying is that we're also providing default source/destination providers in the same package (that can rely on other dependencies)
> > 
> > 
> > It would be fairly easy to argue the default providers don't have their place in the core data-transfer package but rather the cli commands that is actually really using them
> 
> While I agree with moving the providers out of the DTS package, they need to be used by both strapi/core & strapi/admin. Moving them next to the CLI would not allow that, right? 🤔

If they are needed in both places then we must extract them to a deits providers package (I would start by one for all "common" providers for now)

**Comment by Convly** [comment]
> > > > More context: The DTS APIs are used by the admin, CLI, and can also be used independently, that's another reason why it's a library and not a plugin. To summarize, the DTS package provides the utils to build transfer processes & transfer features in other places (admin, CLI, server, etc...) What's annoying is that we're also providing default source/destination providers in the same package (that can rely on other dependencies)
> > > 
> > > 
> > > It would be fairly easy to argue the default providers don't have their place in the core data-transfer package but rather the cli commands that is actually really using them
> > 
> > 
> > While I agree with moving the providers out of the DTS package, they need to be used by both strapi/core & strapi/admin. Moving them next to the CLI would not allow that, right? thinking
> 
> If they are needed in both places then we must extract them to a deits providers package (I would start by one for all "common" providers for now)

LGTM :slightly_smiling_face:

**Pull request merged**
