### PR TITLE
Add UK translation

### PR DESCRIPTION
**Pull request by avhust**
Full Ukrainian translation for en.json

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello! Thank you for this contribution!
I would like to notice 2 things.

- Can you please also fill plugin's UK translations.
- Can you check the DCO when you are committing.

Thank you.

**Comment by lauriejim** [comment]
Hello @avhust !

Any news about my last comment?
I will have to close this PR if it's not covered.

**Comment by avhust** [comment]
> Hello @avhust !
> 
> Any news about my last comment?
> I will have to close this PR if it's not covered.

Hello @lauriejim !

Soory, I have no time right now. I'm going to complete translation in May.

**Comment by lauriejim** [comment]
Hello @avhust !
Good to know, thank you for this detail.

**Comment by lauriejim** [comment]
Additional comment, can you make sure to pass the DCO please. 

https://github.com/strapi/strapi/pull/5545/checks?check_run_id=519361398

**Comment by alxnkt** [comment]
Hello @avhust!
I would like to notice, that just adding `uk.json` file does not do the trick. You also have to edit `index.js` file in the same folder.
```javascript
...
import en from './en.json';
...
import ua from './ua.json';

const trads = {
  ...
  en,
  ...
  ua
};
```
Besides, it is better to name your file `ua.json` instead of `uk.json`. This is because strapi automatically substitutes link to country flag from `cloudflare` (see the picture). So you will get pretty Ukrainian flag.
ua

**Comment by alexandrebodin** [comment]
Closing for inactivity. Feel free to reopen with applied changes :D !

**Pull request closed without merging**
