### PR TITLE
enhancement: Add Wolof and Xhosa languages

### PR DESCRIPTION
**Pull request by tgb20**
### What does it do?

Adds support for the Wolof and Xhosa languages in the @strapi/i18n package.

### Why is it needed?

We have a client that needs these languages added. This PR was made once for v4 and was approved but then got closed with the transition to v5.

### CODE REVIEW

**Comment by tgb20** [comment]
Is there anything else I need to do for this?

**Comment by lucasboilly** [comment]
Hi @tgb20, thanks a lot for your contribution :) 

I just discovered your PR, it would be really cool to add these languages indeed! I'm sharing it to the team right now so it can be reviewed ASAP 👍

**Review by remidej — APPROVED** [review]
thanks!

**Comment by remidej** [comment]
the CI seems to be stuck, I'll try closing and reopening to get it to move along

**Pull request merged**
