### PR TITLE
Compound indexes

### LINKED ISSUE #2006: Primary Key and Compound keys in Content Type Editor
**What is the expected behavior?**

It would be great if we had some facilities for determining Primary Key or Compound keys of a Content Type in Content Type Editor.
I see that we don't have such options even programmaticaly in model setting:
https://strapi.io/documentation/3.x.x/guides/models.html

### PR DESCRIPTION
**Pull request by sajjad-shirazy**
#### Description:
A database index allows a query to efficiently retrieve data from a database. Indexes are consist of one or more keys. Strapi had single key indexes but not compound keys so far.

Fixes #2006 

#### My PR is a:
- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix #issueNumber
- [ ] 💅 Enhancement
- [x] 🚀 New feature

#### Main update on the:
- [ ] Admin
- [x] Documentation
- [x] Framework
- [ ] Plugin

#### Manual testing done on the following databases:
- [ ] Not applicable
- [x] MongoDB
- [x] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@sajjad-shirazy Can you please convert the knex raw queries into the proper knexjs functions? https://knexjs.org/#Schema-index

Also with the addition of SQLite this PR will need to be modified a bit and tested to make sure SQLite works as well.

**Comment by lauriejim** [comment]
Hello! 
Thank you for your PR, this topic is interesting.
We will plan a review on the way we execute bookshelf database query to manipulate the database.
This PR will be updated at this time.

**Comment by dgtllion** [comment]
is there a way how to create compound index with mongoose in strapi? Cant find any documentation. See only single index.

**Comment by alexandrebodin** [comment]
As we are going to bring a lot of changes to the database layer during the next year we are not going to add this as a core feature. you can still add your indexes yourself on start with the database functions files as described in https://strapi.io/documentation/3.0.0-beta.x/configurations/configurations.html#bookshelf-mongoose

We will keep this as a feature request and see if it can go in the roadmap at a future time

**Comment by jonathanmach** [comment]
Any updates on compound keys?

**Pull request closed without merging**
