### PR TITLE
feat: expose /swagger.json

### PR DESCRIPTION
**Pull request by tomsaleeba**
This PR is ready to be merged.

### What does it do?

Add controller and routes to expose the endpoints:
  - /swagger.json (the latest spec)
  - /openapi.json (the latest spec)
  - /vN.N.N/swagger.json
  - /vN.N.N/openapi.json

### Why is it needed?

Users of a Strapi API may want to use a code generator to create a client for their language of choice. To do this, they need the OpenAPI spec document. Currently the document is only served up *inside* the index.html for the swagger UI.

I can see that you have [a comment](https://github.com/strapi/strapi/blame/dcd5254e6011835e197d369f4fa5e14baa7fe583/packages/strapi-plugin-documentation/controllers/Documentation.js#L39) saying exposing the spec is a security concern. This solution still requires permission to be granted to roles before it can be exposed, which means it won't make a newly created project any less secure than currently. It seems that the [users-permissions](https://github.com/strapi/strapi/blob/dcd5254e6011835e197d369f4fa5e14baa7fe583/packages/strapi-plugin-documentation/config/functions/bootstrap.js#L6) plugin is a required dependency, which means the auth system will always be present to protect the spec if it needs to be kept private.

### Related issue(s)/PR(s)

None.

CC @tokmakoff

### CODE REVIEW

**Review by derrickmehaffy — DISMISSED** [review]
Docs look good and I'm in favor of this change. Something to keep in mind that our filtering system does not comply with the OpenAPI spec so any automated client generator will have problems with that.

**Comment by tomsaleeba** [comment]
Thanks @derrickmehaffy. I haven't tried to use a code generator yet but thank you for the warning it might not be happy.

Also, do I need to send a separate PR with changes to the `documentation` branch? Or is that automatically updated with my changes to the README?

**Comment by derrickmehaffy** [comment]
Nope when building out a feature you can keep the docs in the same PR

**Comment by derrickmehaffy** [comment]
> Nope when building out a feature you can keep the docs in the same PR

Just a heads up this has changed since the PR was first opened, we are quite behind on PR reviews and merges but documentation has been moved to a new repo: https://github.com/strapi/documentation

**Comment by tomsaleeba** [comment]
I've created a PR for the other repo: https://github.com/strapi/documentation/pull/85

**Comment by tomsaleeba** [comment]
Whoops, accidentally deleted the branch, which closed the PR. Re-opening.

**Comment by derrickmehaffy** [comment]
Hi 👋  
We now have released the `v4`. As of now, the `v3` is in maintenance mode for 6 months. We will only be fixing critical and security issues on v3 from now on. 
I will go ahead and close this PR. Thank you for contributing to Strapi 🔥

**Comment by martijn10kb** [comment]
@derrickmehaffy Cool, but can you fix it in v4 then? Thank you!

**Pull request closed without merging**
