### PR TITLE
GET /users/me returns same data as auth user

### PR DESCRIPTION
**Pull request by bglidwell**
### What does it do?

GET /users/me was returning just what was saved on the user state rather than the user object itself. 

Updated /users/me controller to return the sanitized user object from the state.user.id instead, which now matches the user object schema that is returned when performing auth initially

### Why is it needed?

Allows frontend developers to refresh things like role changes and extended properties in the user collection type. 
The /users/me should be the same object schema that is returned when performing auth to avoid losing information when attempting to refresh or display the user. 

### TODO

It would be nice if the graphql me resolver was updated as well, but this was a little outside my expertise since the type would need to pull from the Users type in /strapi-plugin-users-permissions/config/schema.graphql.js. Perhaps someone can make that change. 

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Review by Convly — COMMENTED** [review]
Hi, thanks for your contribution!

Tell me if I missed something, but it appears the call you're doing to the `user.fetch` method is a duplicate of the call made to fetch the authenticated user thanks to the jwt token (and the user id) in the permissions policy.
https://github.com/strapi/strapi/blob/1e65de6c7abb1a565fee5605f61097d177dba98b/packages/strapi-plugin-users-permissions/config/policies/permissions.js#L21-L24

FYI `fetchAuthenticatedUser` and your `user.fetch` call are doing the same query underneath.

https://github.com/strapi/strapi/blob/1e65de6c7abb1a565fee5605f61097d177dba98b/packages/strapi-plugin-users-permissions/services/User.js#L67-L69

https://github.com/strapi/strapi/blob/1e65de6c7abb1a565fee5605f61097d177dba98b/packages/strapi-plugin-users-permissions/services/User.js#L75-L77

Also, I tried and failed to reproduce your issue with non-up-to-date data returned from `/users/me`. If you have an example showcasing this behaviour, feel free to open an issue so we can look into it.

Thanks!

**Comment by bglidwell** [comment]
@Convly Thanks for your comments. The issue was not getting out of date information but instead not getting extended data resolved on the user collection. I have several relationships and fields added to the users collection type on my strapi version, and when I log in, that data is correctly returned to me in the auth response. However, the ctx.state.user object that is returned form /users/me did not contain these resolved relationships. 

As an example, I fired up a fresh copy of strapi on Docker, added a new text field to users called test, and setup a relationship to another collection called profile in a one-to-one
image
image

When I successfully post to /auth/local, I correctly receive the following back
```
{
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjEwMTE0MzYxLCJleHAiOjE2MTI3MDYzNjF9.c2spyEkGc1OTmk2y9QeNLmnI0ZdfpyLy_iNEo29jjFs",
    "user": {
        "id": 1,
        "username": "testUser",
        "email": "sintex@gmail.com",
        "provider": "local",
        "confirmed": true,
        "blocked": false,
        "role": {
            "id": 1,
            "name": "Authenticated",
            "description": "Default role given to authenticated user.",
            "type": "authenticated"
        },
        "Test": "test",
        "profile": {
            "id": 1,
            "DisplayName": "Test",
            "Age": 123,
            "user": 1,
            "published_at": null,
            "created_at": "2021-01-08T13:59:08.380Z",
            "updated_at": "2021-01-08T13:59:08.395Z"
        },
        "created_at": "2021-01-08T13:56:17.333Z",
        "updated_at": "2021-01-08T13:59:08.386Z"
    }
}
```

However, when I hit /users/me with that bearer token, I receive only
```
{
    "id": 1,
    "username": "testUser",
    "email": "sintex@gmail.com",
    "provider": "local",
    "confirmed": true,
    "blocked": false,
    "role": {
        "id": 1,
        "name": "Authenticated",
        "description": "Default role given to authenticated user.",
        "type": "authenticated"
    },
    "Test": "test",
    "profile": 1,
    "created_at": "2021-01-08T13:56:17.333Z",
    "updated_at": "2021-01-08T13:59:08.386Z"
}
```

Notice the lack of the resolved relationship. The field shows up, but not the extra resolves. Part of the appeal of a /users/me endpoint for me would be to refresh the user object I'm keeping in state on my frontend application, which means I really would prefer to get the same "user" object schema back from both requests. 

I can only presume this is due to the explicit "role" in the relationships list on fetchAuthenticatedUser? Perhaps when this is left null as in auth user.fetch and my /users/me example, the behavior is to resolve all relationships one level deep?
https://github.com/strapi/strapi/blob/1e65de6c7abb1a565fee5605f61097d177dba98b/packages/strapi-plugin-users-permissions/services/User.js#L75-L77

**Comment by Convly** [comment]
> but instead not getting extended data resolved on the user collection

Oh, I see, I've misinterpreted your first explanation, my bad.

> Perhaps when this is left null as in auth user.fetch and my /users/me example, the behavior is to resolve all relationships one level deep?

This is exactly the behaviour of the populate option :slightly_smiling_face: 

> However, the ctx.state.user object that is returned form /users/me did not contain these resolved relationships

> Notice the lack of the resolved relationship. The field shows up, but not the extra resolves. Part of the appeal of a /users/me endpoint for me would be to refresh the user object I'm keeping in state on my frontend application, which means I really would prefer to get the same "user" object schema back from both requests.

Back in time, we were returning the whole user + its relationship (1st level). However, some users pointed out that for complex architecture, returning the user alongside all its relations was not ideal.
(I agree that the `login` & `GET /me` routes should return the same information, but I'm more for the login route to copy the behaviour of the `GET /me`)

In summary, whether we send the relationships or not, some users will have cases where they'll want the other behaviour. So as long as we don't support the populate specification directly in the query params, we'll have to make a choice.

As a workaround, what you could do is either make a call to `/users/:id` (which does the auto-populate) or extend the controller to update this specific route and its behaviour with your own implementation. Something like the following should work:

`/extensions/users-permissions/controllers/User.js`
```javascript
'use strict';

const { sanitizeEntity } = require('strapi-utils');

const sanitizeUser = user =>
  sanitizeEntity(user, {
    model: strapi.query('user', 'users-permissions').model,
  });

module.exports = {
  async me(ctx) {
    const user = ctx.state.user;

    if (!user) {
      return ctx.badRequest(null, [{ messages: [{ id: 'No authorization header was found' }] }]);
    }

    const { id } = user;
    const data = await strapi.plugins['users-permissions'].services.user.fetch({ id });

    ctx.body = sanitizeUser(data);
  },
};

```

**Comment by bglidwell** [comment]
@Convly Thanks for the input. I understand and agree with the assessment to match the two returns to the one with the least data. Would you like me to update this PR to reflect that change and match /auth/local return to the /users/me shape? That may be a breaking change for some that are expecting that info from /auth/local is all. 

I have already overridden the users controller to return my extended information, and I will eagerly await the query option. I love that Strapi core can be overridden, but I do like to keep it temporary and to a minimum where possible.

**Comment by Convly** [comment]
> Would you like me to update this PR to reflect that change and match /auth/local return to the /users/me shape?

That would be very nice, thank you. However, we'll have to wait for the v4 to merge it since it's indeed a breaking change.

**Comment by NooBiToo** [comment]
@bglidwell , @Convly 
Hello!
i use
```javascript
'use strict';

module.exports = {
  fetchAuthenticatedUser(id) {
    return strapi.query('user', 'users-permissions').findOne({ id }, ['role', 'fav_game', 'articles', 'avatar']);
  },
}
```
But, the **articles** field has a **images** field, and with this output, I do not receive the **images** field from the **articles**.
I see only fields that are not nested

**Comment by derrickmehaffy** [comment]
Hi 👋  
We now have released the `v4`. As of now, the `v3` is in maintenance mode for 6 months. We will only be fixing critical and security issues on v3 from now on. 
I will go ahead and close this PR. Thank you for contributing to Strapi 🔥

**Pull request closed without merging**
