### PR TITLE
Adding ESM possibility for Upload Providers

### PR DESCRIPTION
**Pull request by DasRed**
Adding the possibility to import ESM provider Plugins and not only common js

### What does it do?

The Upload plugin allows some different providers. These providers will be loaded with `require()`. That's okay, but only allows providers, which have a CommonJS interface. This change detects, if the required file is an ESM file and imports that file with `import()`. 
The result is, that both interface are now allowed for importing (CommonJS and ESM).

### Why is it needed?

NodeJS supports ESM natively and not only CommonJS. In my opinion, ESM is the future. And we (Zeppelin) implement an own upload provider, which is based on ESM.

### How to test it?

Setup strapi. Configure a ESM Upload provider. 

### Related issue(s)/PR(s)

no related issues

### CODE REVIEW

**Comment by DasRed** [comment]
> @DasRed please don't forget to fill out the complete description of the PR! :)

done @joshuaellis

**Comment by Marc-Roig** [comment]
Hello @DasRed , sorry for the delay. We have been exploring this proposal and we reached to a conclusion:

- We know ESM is the way to go, still at this point in time backend side of Strapi works with commonjs. Allowing ESM syntax only in here would mean we also need to allow it elsewhere in the codebase. And as today this is something that needs to be discussed more in depth, specially with @alexandrebodin.
- Until we move to ESM in the codebase, we regret to inform you that we cannot allow this change.  Would it be possible for your provider to work with cjs? We hope you understand our decision and look forward to hearing back from you.

**Comment by joshuaellis** [comment]
Just to add, if you're working with TS or a bundler, this is relatively easy for you to do (typically).

**Comment by Marc-Roig** [comment]
As this is not possible at the moment, I am closing the issue now. Still we will wait for a response to see if there is any alternative for your use case.

**Pull request closed without merging**
