### PR TITLE
Merge mongoose connection options 

### LINKED ISSUE #9962: sslCA in strapi-connector-mongoose
### Describe the bug

The sslCA is not being taken into account in the mongodb connection options

### Steps to reproduce the behavior

1. Set env vars filepath in sslCA: "DB_SSL_CA=../../foo.pem"
2. Go to and config env vars options.sslCA = [fs.readFileSync(DB_SSL_CA, "utf8")] in 'config/database.js'
3. npm start
4. See error: "Error connecting to the Mongo database. unable to verify the first certificate"

### Expected behavior

This must connect to the databases in replicaset mode taking into account the ssl and sslCA options.

### Screenshots

Error:
image

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12
- NPM version: 6.14.11
- Strapi version: 3.5.4
- Database: Mongodb - IBM Hyper protect
- Operating system: Ubuntu 20.04

### Additional context

Solution:

The sslCA property needs to be added in the strapi-connector-mongoose options as follows:
image

And with that the fault is corrected:
image

### PR DESCRIPTION
**Pull request by chris-schra**
The current parsing of mongoose options is still confusing so this rather is a Hotfix and we should have a closer look at the logic (eg username could be set in connection URI, strapi config and elsewhere).

Fixes #9962

### CODE REVIEW

**Comment by vkDreamInCode** [comment]
Is this MR going to be merged? Im personally stuck because of sslCA not working

**Comment by chris-makaio** [comment]
I don't think so :( 
we're currently using a patch via patch-package

**Comment by EnkeyCaps** [comment]
Hi chris,

Im not sure what you mean with patch via patch-package.
Is that patch-package a solution to this problem? And if so how do I use that?

**Comment by derrickmehaffy** [comment]
Hi 👋  
We now have released the `v4`. As of now, the `v3` is in maintenance mode for 6 months. We will only be fixing critical and security issues on v3 from now on. 
I will go ahead and close this PR. Thank you for contributing to Strapi 🔥

**Pull request closed without merging**
