### PR TITLE
Fix custom mutation returning null and not executing policies

### LINKED ISSUE #1887: The policies are not executed in my GraphQL custom schema
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 6.4.0
- **Strapi version**: 3.0.0-alpha.14
- **Database**: mongo:4.0.1
- **Operating system**: OSX 10.13.6

**What is the current behavior?**
The policies are not executed in my graphql custom schema

**Steps to reproduce the problem**
This is my schema.graphql into api/contacts/config/
```js
module.exports = {
  definition: `
    type Contacts {
      count: Int!
      rows: [Contact]!
    }
  `,
  query: `
    _contacts(sort: String, limit: Int, start: Int, where: JSON): Contacts
  `,
  resolver: {
    Query: {
      _contacts: {
        description: `Contacts`,
        policy: ['plugins.users-permissions.isAuthenticated'],  // <-------
        resolver: async (obj, options, ctx) => {
          let params = {
            _limit: options.limit ? options.limit : 10,
            _sort: options.sort ? options.sort : '',
            _start: options.start ? options.start : 0
          }

          if ( options.where ) {
            params = Object.assign(params, { ...options.where })
          }

          const rows = await strapi.services.contact.fetchAll(params);
          const count = await strapi.services.contact.count(params);
          return { count, rows };
        }
      }
    }
  }
};
```

**What is the expected behavior?**
The policy executed

**Suggested solutions**

### PR DESCRIPTION
**Pull request by nikosolihin**
#### Description:
**The fix address the following issues:**
- Custom mutation resolvers defined as string will return null ([screenshot](https://github.com/strapi/strapi/issues/2766#issuecomment-463129085))
- Policies defined for custom resolvers won't execute 

**Steps to reproduce:** 
1. In `schema.graphql` add a custom resolver:
```
resolver: {
    Mutation: {
      upsertPost: {
        policies: ['global.isLoggedIn'],
        resolver: 'Post.createOrUpdate'
      }
    }
  }
```
2. Add the controller action returning a sample data according to your schema
3. `strapi generate:policy isLoggedIn`
4. Execute the mutation

#### My PR is a:
- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #1887 #2766
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:
- [ ] Not applicable
- [x] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @nikosolihin, would you mind updating your branch if the PR is still active ?

**Comment by WeFlyCheap** [comment]
@alexandrebodin I can confirm that this PR fixes the issues with custom mutations and policies. If necessary I can make a new PR with the updated branch.

**Comment by derrickmehaffy** [comment]
@WeFlyCheap please do and link this PR in yours and we can mark this as closed

**Comment by derrickmehaffy** [comment]
closing in favor of https://github.com/strapi/strapi/pull/3735

**Pull request closed without merging**
