### PR TITLE
Update polish translations

### PR DESCRIPTION
**Pull request by luklus**
Sort and update polish translations

### CODE REVIEW

**Comment by soupette** [comment]
@luklus Thanks a lot for your contribution!

Can you make sure to pass the DCO checks so we can merge your PR?

**Comment by soupette** [comment]
@wysher I'll let you validate the PR then. Once we have your approval and the DCO checks we will merge the PR.

**Comment by luklus** [comment]
@wysher dzięki za uwagi, poprawione

**Comment by wysher** [comment]
@soupette LGTM!

@luklus one last thing - You need to signoff commits. Here's how to signoff for current PR: https://github.com/strapi/strapi/pull/6366/checks

**Comment by alexandrebodin** [comment]
Hi @luklus when trying to fix the DCO check your rebase totally broke your branch :) If you don't mind reopening one with a single commit this would be great. Going to close this one in the meantime !

**Pull request closed without merging**
