### PR TITLE
added missing locales to i18n plugin ( Wolof and Xhosa languages)

### PR DESCRIPTION
**Pull request by cupofnestor**
### What does it do?

Added additional locales for Wolof and Xhosa languages to the i18n plugin

### Why is it needed?

Our client requires i18n features in these languages.

### CODE REVIEW

**Comment by jhoward1994** [comment]
Hi @cupofnestor, thanks for this!

Could you please update the related snapshot as per https://github.com/strapi/strapi/commit/cfa980ba5ab966ef3911a4f194afbeb444460840 so that our tests pass ? 🙏🏻

**Review by jhoward1994 — CHANGES_REQUESTED** [review]
See above comment

**Comment by cupofnestor** [comment]
Do I need to manually edit the `server/services/__tests__/iso-locales.test.js` file, or is this generated by some process?

**Comment by jhoward1994** [comment]
Running `yarn test:unit packages/plugins/i18n/server/services -u` should update the snapshot for you

**Comment by cupofnestor** [comment]
Thanks, hopefully this does it.

**Review by jhoward1994 — APPROVED** [review]

**Comment by Nathalie590** [comment]
Running yarn test:unit packages/plugins/i18n/server/services [-](https://mlinjectors.com/zaxius-domain/)u should update the snapshot for you.

**Comment by tgb20** [comment]
Is there any news on when this might be added?

**Comment by innerdvations** [comment]
Hello, thanks for your PR! Could you please target the `develop` branch instead of `main`? Thanks!

**Comment by cupofnestor** [comment]
done

**Comment by alexandrebodin** [comment]
> [!IMPORTANT] 
> With the release of Strapi 5, we have lifted the code freeze. To ensure we can effectively review and assist with contributions, we are now only accepting PRs targeting version 5 (the develop branch).<br/> 
> As your PR targets version 4, it has been automatically closed. However, we would greatly appreciate it if you could update your contribution to align with version 5 and resubmit!

**Pull request closed without merging**
