### PR TITLE
Update Landing page social links

### LINKED ISSUE #10758: [Request] Change Logos and links
## Feature request

Change of design and links on the homepage of Strapi's environment.
image

### Summary

- Replace the Slack logo with the Discord logo
- Add the [discord link](https://discord.com/invite/WFrDyNzNDU)
- Replace the Medium logo by Strapi Logo with "Blog" as the name.
- Replace with the [strapi blog link](https://strapi.io/blog)
- Replace the Reddit logo by the Strapi Logo with "Hiring" as the name.
- Replace Reddit link with our [careers page](https://strapi.io/careers)
- 

### Why is it needed?
Keep promoting Strapi's content on Strapi's ecosystem.
Direct Reddit potential questions to the forum or the discord

Thank you

### PR DESCRIPTION
**Pull request by derrickmehaffy**
Signed-off-by: Derrick Mehaffy <derrickmehaffy@gmail.com>

### What does it do?

- Replaces Slack with Discord
- Replaces Medium with Blog
- Replaces Academy with Careers

### Why is it needed?

- We don't have a community slack anymore
- We no longer push content to medium
- Academy is being put in limbo

### How to test it?

Standard testing of admin PRs

### Related issue(s)/PR(s)

fixes #10758

image

image

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@Melanie12 we still have a very active community on Reddit (and a few team members as mods there, myself included).
I also changed Hiring to Careers, let me know if this works for you.

**Comment by soupette** [comment]
LGTM

**Comment by Melanie12** [comment]
@derrickmehaffy No problem. I thought Reddit was a distraction from the forum.
Thank you for your help.

@KevinCudennec do you think we need to create new logos for career or blog? So it's less repetitive.

**Review by Melanie12 — APPROVED** [review]
All good for me.
I guess we can change the logos later when we have an idea of the design.

**Pull request merged**
