### PR TITLE
Add Te Reo Māori locale

### PR DESCRIPTION
**Pull request by chris-turner-datacom**
### What does it do?

Adds Te Reo Māori as a locale

### Why is it needed?

Te Reo Māori was missing previously and is widely needed in New Zealand

### How to test it?
Check if the locale is present in the locales dropdown when creating a localization.

### Related issue(s)/PR(s)

#14319

### CODE REVIEW

**Review by ronronscelestes — COMMENTED** [review]
hi @chris-turner-datacom, thank you for this addition 😊
from the documentation we use for ISO-locales ([here](https://iso639-3.sil.org/code_tables/639/data/all?title=&field_iso639_cd_st_mmbrshp_639_1_tid=All&name_3=Maori&field_iso639_element_scope_tid=All&field_iso639_language_type_tid=All&items_per_page=200) and [here](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)) I found that `mi` code has `Maori` and not `Te Reo Māori` as name/description
usually we try to follow those documentations, wdyt? 🙂

**Comment by chris-turner-datacom** [comment]
> 

hi @ronronscelestes , I consulted with a few Maori people I work with and all of them felt that the ISO definition is not culturally correct. Te Reo Māori is the language. Maori is the people. I've also checked a number of websites and the majority of them also use Te Reo Māori as the label for switching language so I think in this instance, we would be better to go with Te Reo Māori. :-) Cool - will look at the backend snaphots!

**Comment by ronronscelestes** [comment]
> > 
> 
> hi @ronronscelestes , I consulted with a few Maori people I work with and all of them felt that the ISO definition is not culturally correct. Te Reo Māori is the language. Maori is the people. I've also checked a number of websites and the majority of them also use Te Reo Māori as the label for switching language so I think in this instance, we would be better to go with Te Reo Māori. :-) Cool - will look at the backend snaphots!

thank you for this explanation, really interesting, Te Reo Māori it is then 😊

**Review by ronronscelestes — COMMENTED** [review]
hi @chris-turner-datacom, I think tests snapshots are not updated yet, I launched the tests but they'll probably fail 👀
could you please update them by using `yarn test:unit -u` command at the root of the strapi repo locally and then commit the snapshot change? 
let me know if you need any help 🙂

**Comment by chris-turner-datacom** [comment]
> yarn test:unit -u

Hey @ronronscelestes , So I've tried doing exactly that and it successfully runs 1 test suite containing 7 tests but i'm not seeing anything in git that needs pushing. What am I missing? That seems like not a lot of tests for an application the size of strapi!

**Comment by ronronscelestes** [comment]
> > yarn test:unit -u
> 
> Hey @ronronscelestes , So I've tried doing exactly that and it successfully runs 1 test suite containing 7 tests but i'm not seeing anything in git that needs pushing. What am I missing? That seems like not a lot of tests for an application the size of strapi!

mmh indeed there should be more than 7 tests 👀
are you launching the command at the root of strapi (not inside packages nor getstarted)?
if I launch `yarn test:unit` with your branch I get this:
image

**Comment by ronronscelestes** [comment]
let me know if you need anything @chris-turner-datacom - I could try to push the snapshots update if you want to 🙂

**Comment by chris-turner-datacom** [comment]
@ronronscelestes Interestingly, I also can't successfully run the yarn setup script. I get the following: 
image
It might be quickest and easiest if you are able to push those snapshots if you don't mind!

**Comment by chris-turner-datacom** [comment]
> 

Yep - from the root:
image
 It seems to be picking up a test file inside the github actions check-pr-status folder rather than the main set of tests.

**Comment by ronronscelestes** [comment]
that's really curious 👀
I pushed a commit with the snapshot update 🙂

**Review by ronronscelestes — APPROVED** [review]
LGTM 💃

**Pull request merged**
