### PR TITLE
Typescript support - Added config option to allow loading additional file types.

### PR DESCRIPTION
**Pull request by ascension**
#### Description of what you did:
Based on the discussion in #6550 I implemented:
Added a new config option `loader.extensions` to allow core api to load additional files.
Added a new example project that uses Typescript.
Updated config docs to include `loader.extensions`

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi, I see a lot of unwanted commits in your branch history :) Would you mind cleaning it up so the diff only contains your changes ;)

**Comment by alexandrebodin** [comment]
Hey, sorry but your PR history is still not clean :/

**Comment by alexandrebodin** [comment]
Hi @ascension still seeing a weird history here :)

**Comment by ascension** [comment]
> Hi @ascension still seeing a weird history here :)

@alexandrebodin I will try to get this cleaned up this week

**Comment by derrickmehaffy** [comment]
This pull request has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/strapi-integration-with-other-typescript-aplications-in-a-monorepo/1104/2

**Comment by sapkra** [comment]
@ascension Any update?

**Comment by ascension** [comment]
> @ascension Any update?

@sapkra Open a new PR #9076

**Pull request closed without merging**
