### PR TITLE
Some minor doc improvements on english level

### PR DESCRIPTION
**Pull request by denislutz**
Hey Guys, I did some minor improvements to english sentences. Please accept.

**Important**: at the beginning of the model section, I added a note to point new devs to start with the admin interface, this seems simple but not obvious. This helped me a lot at the beginning, since the admin interface is asserting many things right away.

**Question**: since the model and controller generators do not work and wont be fixed soon, as you said yourself, how about we clean up the doc just to be with generate:api?

### CODE REVIEW

**Comment by Freakspot** [comment]
Despite fixing many mistakes, you also introduced a couple of new ones :stuck_out_tongue: 

1. "intedependent" -> independent
2. "maintable" -> maintainable
3. "convinient" -> convenient

Those should probably be fixed before merging. Additionally, I still see a couple of other mistakes in the docs which should be fixed later but apart from that your commit should help cleaning up the docs.

**Comment by denislutz** [comment]
@Freakspot thanks for pointing out the mistakes, I just pushed a fix.

**Comment by lauriejim** [comment]
Thank you @denislutz  and @Freakspot for your participation 👍

**Comment by denislutz** [comment]
@Aurelsicoko the logging change will come in a separate PR, this one was only about the docs.

**Pull request merged**
