### PR TITLE
chore(i18n): Adding Hungarian translation for admin core

### PR DESCRIPTION
**Pull request by popovicsandras**
### What does it do?

Adding Hungarian translation texts for Admin Core features, which were missing from Strapi 4.20.0.

1. Started from [this PR](https://github.com/strapi/strapi/pull/16904), I've rebased it, while paying attention to keep the commit history, giving the credits for @KristofKekesi for his work.
2. On top of his work, I've added all the missing translation keys, while reordering the keys to have the same order that the en.json translation file has.

### Why is it needed?

Hungarian translation for Admin Core features was partial.

### How to test it?

Run the application using Hungarian language.

### Related issue(s)/PR(s)

https://feedback.strapi.io/feature-requests/p/i18n-hungarian-translation

### CODE REVIEW

**Comment by popovicsandras** [comment]
@innerdvations, @alexandrebodin Sorry for the direct tagging, I've seen your names in another community created PRs.
Can you please point me to someone who I can bother with these 2 (this and https://github.com/strapi/strapi/pull/19522 ) **only translation related PRs** (no code change at all)?
I keep rebasing them to be uptodate and I just would like to know how much time usually it takes to be merged, whether I should keep them rebased or not.

Cheers,
Andras

**Comment by popovicsandras** [comment]
@derrickmehaffy, Sorry for the direct tagging, I'm pretty sure you are busy with another PRs, but I've seen your name in another community created PRs.
I keep rebasing these 2 PRs for 2 weeks now (this and https://github.com/strapi/strapi/pull/19522) without any feedback from Strapi's side, can someone please tell me whether it makes sense for me to keep it updated? It didn't get any feedback or change request,  nor a label or something (to postpone, etc...)
Do you consider it a meaningful contribution? Saying no is completely fine for me, I just would like to know whether it is worth my effort to keep this branch uptodate.

Kind regs,
Andras

**Comment by alexandrebodin** [comment]
> [!IMPORTANT] 
> With the release of Strapi 5, we have lifted the code freeze. To ensure we can effectively review and assist with contributions, we are now only accepting PRs targeting version 5 (the develop branch).<br/> 
> As your PR is targeting some of the most recent v4 version, We we would greatly appreciate it if you could update your contribution to align with version 5 and resubmit!

**Comment by alexandrebodin** [comment]
Following up on https://github.com/strapi/strapi/pull/19522 I'm sadly force to close this for now. 

Again if this can be publicly avaialble on a repo the community will be able to use it. I hope you will be able to do that and suggest it on strapi-awesome repo that is maintained by some community members 🙏

**Pull request closed without merging**
