### PR TITLE
[fixing #6089] No need to check for platform and replace backslash

### PR DESCRIPTION
**Pull request by alexdevmotion**
Fixing #6089

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hello @alexdevmotion thank you for the fix, 

-  can you please make your PR on top of master and not develop. 
- you will need to sign-off your commit so we can merge your PR.

**Comment by alexdevmotion** [comment]
Done, should be fine now. Let me know if there's anything else I need to change.

**Comment by alexandrebodin** [comment]
Hey @alexdevmotion sorry but the DCO check is still not happy. I recommend you do an interactive rebase  squash all your commits into one signed off commit

**Comment by alexdevmotion** [comment]
Finally done, sorry for the delay, I wasn't familiar with the sign-off process, now I understand it, so thanks for that.

**Comment by alexandrebodin** [comment]
Hey @alexdevmotion, sorry again :) From what I am seeing; because you started your PR from develop your PR contains code already merged in develop. Can you please reopen a PR from master to master with only your code.

**Comment by alexdevmotion** [comment]
will do that ASAP

**Comment by alexandrebodin** [comment]
Hi @alexdevmotion any updat eon this ?

**Comment by alexandrebodin** [comment]
Hey, closing in favor of https://github.com/strapi/strapi/pull/6546 :)

**Pull request closed without merging**
