### PR TITLE
Check that model and model.privateAttributes is not undefined

### PR DESCRIPTION
**Pull request by csandven**
### What does it do?

Solves an issue where the database maybe out of sync with strapi and the model is undefined when modifying and object.
```
error TypeError: Cannot read property 'includes' of undefined
```

### Why is it needed?

This error gives an error in the admin view. The editing is still working, but not in a nice way.

### CODE REVIEW

**Review by alexandrebodin — APPROVED** [review]
LGTM. Thansk for the improvement

**Comment by alexandrebodin** [comment]
@csandven Can you please sign the CLA so we can merge ;)

**Comment by csandven** [comment]
> @csandven Can you please sign the CLA so we can merge ;)

I did, but it seems to just be loading. What can I do here?

**Comment by alexandrebodin** [comment]
@csandven you will need to wait a few seconds it is quite slow

**Review by alexandrebodin — APPROVED** [review]
LGTM, Thank you :)

**Pull request merged**
