### PR TITLE
Fix create-strapi-app for commander 8.2.0

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

Updates the create-strapi-app command to work with commander v8.2.0 (it was previously written using commander v6.1.0)

### Why is it needed?

There was a breaking change between commander 6.x -> 7.x that caused the options flags to not be passed through

### How to test it?

Run `create-strapi-app --quickstart testProjName` and it should now generate a quickstart app without prompting for input

### Related issue(s)/PR(s)

Issue: https://github.com/strapi/strapi/issues/15056

Original PR that introduced the error: https://github.com/strapi/strapi/pull/15043

### CODE REVIEW

**Comment by innerdvations** [comment]
Just noticed we also need to fix `create-strapi-starter`, working on that now.

**Review by Convly — APPROVED** [review]
Tested create-strapi-app and looks fine to me, thanks!

EDIT: Waiting for create-strapi-starter :eyes:

**Comment by innerdvations** [comment]
> > > Just noticed we also need to fix `create-strapi-starter`, working on that now.
> > 
> > 
> > Actually, `create-strapi-starter` seems to work the same as before, the issues I noticed (options present in the code that aren't displayed or used by the command) have always existed. I'll take a look at that later.
> 
> If we need to expand or improve the documentation, just loop me in and I will take care of it.

I don't have anything specific to say, but if you google "create-strapi-starter" you basically get a blog post, and can also find the Strapi starters page which actually uses "create strapi-app" (app, and without the dash) but doesn't outline any of the options.

Essentially, it feels like "create-strapi-starter" was announced in a blog post but is otherwise undocumented (unless it's buried somewhere searches can't find)

**Comment by StrapiShaun** [comment]
> > > > Just noticed we also need to fix `create-strapi-starter`, working on that now.
> > > 
> > > 
> > > Actually, `create-strapi-starter` seems to work the same as before, the issues I noticed (options present in the code that aren't displayed or used by the command) have always existed. I'll take a look at that later.
> > 
> > 
> > If we need to expand or improve the documentation, just loop me in and I will take care of it.
> 
> I don't have anything specific to say, but if you google "create-strapi-starter" you basically get a blog post, and can also find the Strapi starters page which actually uses "create strapi-app" (app, and without the dash) but doesn't outline any of the options.
> 
> Essentially, it feels like "create-strapi-starter" was announced in a blog post but is otherwise undocumented (unless it's buried somewhere searches can't find).
> 
> Personally, I'm not sure if more documentation is the path. To me it makes more sense to deprecate it and combine it with create-strapi-app unless there's a specific reason to maintain two commands.

OK I understand it better now. Regardless if it exists as a separate command or as a series of options it should be in the CLI documentation. I will add it to our backlog with a note that we need to sync with DX on the decision.

**Pull request merged**
