### PR TITLE
Fix big integer support on GraphQL

### LINKED ISSUE #3084: GraphQL doesn't support bigintegers by default
**Informations**
- **Node.js version**: v10
- **NPM version**: v6
- **Strapi version**: Alpha 25.2
- **Database**: MySQL
- **Operating system**: Ubuntu 18.04
- **(Optional) Link to your Project**: https://github.com/canonn-science/CAPIv2-Strapi

**What is the current behavior?**

Attempting to pull a big integer value from graphql with a value larger than a 32-bit integer results in the following error: 

`"message": "Int cannot represent non 32-bit signed integer value: 1316130638171"`

**Steps to reproduce the problem**

Create a model with the big integer field type, add some data with larger integer values than a 32-bit integer

**What is the expected behavior?**

It should display the values 😛 

**Suggested solutions**

I recommend either a custom scalar type in graphQL or adding the following: https://github.com/chadlieberman/graphql-type-long

Example of a custom scalar type via apollo: https://www.apollographql.com/docs/graphql-tools/scalars#Own-GraphQLScalarType-instance

**References**

https://github.com/graphql/graphql-spec/issues/73

### PR DESCRIPTION
**Pull request by derrickmehaffy**
#### Description:

Fix support for big integer values on GraphQL using the following module: https://www.npmjs.com/package/graphql-type-long

#### My PR is a:
- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #3084 
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:
- [ ] Not applicable
- [x] MongoDB
- [x] MySQL
- [x] Postgres
- [x] SQLite

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Looks good to me. 

Can you had some tests ?

**Comment by derrickmehaffy** [comment]
> Looks good to me.
> 
> Can you had some tests ?

I'll give it my best shot after I test manually

**Comment by derrickmehaffy** [comment]
Looks good so far on MySQL: 
image

**Comment by derrickmehaffy** [comment]
@alexandrebodin Ready for review

**Comment by Aurelsicoko** [comment]
LGTM, not sure about the tests though... (cc @alexandrebodin)

**Comment by derrickmehaffy** [comment]
> LGTM, not sure about the tests though... (cc @alexandrebodin)

I hate writing tests @Aurelsicoko :rofl:

**Pull request merged**
