### PR TITLE
fix: configure the view button missing for components

### LINKED ISSUE #21993: Configure The View Button missing for components
- Node.js version: v18.19.0
- NPM version: 10.2.3
- Strapi version: 5.1.1
- Database: Mysql 8+
- Operating system: Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Go to a component - there is no "Configure The View" button. This button is there for collections, and it used to be there in strap 4.x. The feature still works, you can navigate to the view, ie: admin/content-manager/components/el.button/configurations/edit and save the configuration. Be nice if the button was there tho:)

### PR DESCRIPTION
**Pull request by Rishith-S**
fix #21993

### What does it do?

it enables to configure the layout/view for the components in the content-type builder

### Why is it needed?

The feature to edit the layout or view is available but the button to access the configure the view feature was not visible in the UI

### How to test it?

1. Go to content-type builder as super admin
2. Select any component from the components section
3. Click on configure the view button
Now you change the layout structure of components

Screenshot 2024-11-08 at 3 43 14 PM

### CODE REVIEW

**Comment by hanpaine** [comment]
Hey @Rishith-S thanks for your contribution - I believe this is actually an enhancement PR as configure the view got moved into the ⚙️ menu in the CM in Strapi 5 (see #20460). I'll leave it with @yanniskadiri to decide next steps 😄

**Comment by Rishith-S** [comment]
> Hey @Rishith-S thanks for your contribution - I believe this is actually an enhancement PR as configure the view got moved into the ⚙️ menu in the CM in Strapi 5 (see #20460). I'll leave it with @yanniskadiri to decide next steps 😄

Thank you @hanpaine 😄

**Comment by yanniskadiri** [comment]
Thanks for your contribution @Rishith-S!

I don't know if there was a reason why it was removed. Do you know @lucasboilly?

Currently you can set the component's layout if it's used in a content-type from this content-type "Configure the view" page (see the screen recording) but not from the component page in the content-type-builder. This PR adds this capability (and it was originally there in v4).

https://github.com/user-attachments/assets/349dabd6-9c83-4c3f-ad85-5147440f4874

**Comment by yanniskadiri** [comment]
Then let's go! I'll ask the team to review it - thanks again for your contribution @Rishith-S :)

**Pull request merged**
