### PR TITLE
fix: reload ctb after save

### LINKED ISSUE #19378: Content-Type builder not refreshing state after restart/saving content-type
### Required System information

- Node.js version: 20
- NPM version: 10
- Strapi version: 4.19.0
- Database: SQLite
- Operating system: Linux Mint 21.3
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When creating a new component, after saving, the CTB believes the content-type doesn't exist still and you can't navigate off of the page or re-save the content-type without a warning or error.

### Steps to reproduce the behavior

1. Spin up a new project
2. Create a component "Button" with the category as "Default
3. Add a text field called "Label"
4. Save
5. Wait for server restart
6. Try to navigate off of the content-type builder page or to another content-type
7. See warning that you need to save the content type or it'll be lost
8. Try to save again
9. See error

### Expected behavior

CTB should refresh content-type state after the server restarts so that it knows the new content-type/compo exists

### Screenshots

image
image
image
image

### Code snippets

N/A

### Additional context

Reported by @pierreburgy in internal Slack, reproduced by me

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?

- forces ctb to reload after save

### Why is it needed?

- After saving components in the ctb, state is not refreshing unless the page is reloaded manually

### How to test it?

- create or update a contentType it should work properly

### Related issue(s)/PR(s)

fix #19378

### CODE REVIEW

**Review by joshuaellis — CHANGES_REQUESTED** [review]
Is there no other way to refetch our data? this feels quite inconsistent with our current behaviours across the app 🤔

**Comment by joshuaellis** [comment]
Could we recall this `getData` like we do here – https://github.com/strapi/strapi/blob/87b1535d0e2e4c4200f38b61c180a03146f4beca/packages/core/content-type-builder/admin/src/components/DataManagerProvider/DataManagerProvider.tsx#L152

after the submission was sucessful?

**Comment by Bassel17** [comment]
> Could we recall this `getData` like we do here –
> 
> https://github.com/strapi/strapi/blob/87b1535d0e2e4c4200f38b61c180a03146f4beca/packages/core/content-type-builder/admin/src/components/DataManagerProvider/DataManagerProvider.tsx#L152
> 
> after the submission was sucessful?

we could, doesn't help on it's on, but it was a missing piece in the puzzle, this solution should be better now

**Review by innerdvations — APPROVED** [review]
Front end is not my forté but lgtm. QAd it and works for me now

**Review by joshuaellis — APPROVED** [review]
I've not had time to QA but the code approach is fine, when we move to redux-toolkit all this noise will dissapear and we can be happy. Nice work Bassel ⭐

**Pull request merged**
