### PR TITLE
fix: edit role

### LINKED ISSUE #21942: TypeError: Cannot read properties of undefined (reading 'type')     at @strapi/plugin-users-permissions/server/services/users-permissions.js:115:39
### Required System information

- Node.js version: 20.16.0
- NPM version: 10.8.1
- Strapi version: 4.25.13
- Database: PostgreSQL
- Operating system:macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When attempting to edit a role in the Strapi admin panel, the following error occurs:

`TypeError: Cannot read properties of undefined (reading 'type')`  
At: `@strapi/plugin-users-permissions/server/services/users-permissions.js:115:39`

### Steps to reproduce the behavior

1. Go to 'Roles & Permissions' in the Strapi admin panel.
2. Click on a role to edit.
3. The error is displayed, still can edit the role tho, after a bit the table appears with warning internal server error.

### Expected behavior

The table appears without any error

### PR DESCRIPTION
**Pull request by kasyap1234**
### What does it do?
fixes the editing role issue mentioned in the issue #21942 

Describe the technical changes you did.
The root cause is that the code assumes all controller actions have a type symbol property, but some actions may not have this property defined.To fix this, the code should be modified to handle cases where the type symbol is undefined

### Why is it needed?
This would prevent the /TypeError while maintaining the functionalify of content API actions. 

Describe the issue you are solving.
fixes #21942 

Provide information about the environment and the path to verify the behaviour.
the file is mentioned in the issue itself .

### CODE REVIEW

**Comment by oiorain** [comment]
Hi!
thank you for your contribution.
Could you provide a description for your PR please?

**Comment by kasyap1234** [comment]
@oiorain could you please review the PR or assign someone to review the PR whenever possible .

**Comment by jhoward1994** [comment]
Hi, thanks for the PR. I'm afraid I'm not able to reproduce this when editing user and permissions roles at e.g. `http://localhost:1337/admin/settings/users-permissions/roles/1`

Are you able to double check this on `develop` and provide more specific recreation instructions?

**Comment by kasyap1234** [comment]
@jhoward1994  it has been more than 2 weeks since the push so please give me some time so that I can verify once again and get back to you .

**Comment by hanpaine** [comment]
Closing this PR as testing from other community members did not resolve the issue and it appears there is clarity on why the Issue was occurring in the first place now 🙏

**Pull request closed without merging**
