### PR TITLE
release: 4.17.0

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* release 4.17.0
* Includes total typescript conversion of the CTB / i18n & Admin
* Includes partial typescript conversion of the CM
* Blocks: add drag and drop block reordering
* Blocks: add expanded mode
* Blocks: add markdown snippets
* Blocks: simplify link edition popover
* Blocks: add forced line break support (shift+enter)
* Blocks: press enter twice to break out of a code block
* Blocks: fix pressing enter and delete while images are selected

### How to test it?

* experimental – 0.0.0-experimental.68e91e14ec0acd8a8dd9d5bc02f8106c6aee6599
* Because this release contains a lot of conversions we expect any of the converted domains could be effected by unexpected changes. It's therefore recommended to test those domains.

### CODE REVIEW

**Comment by iparidhi** [comment]
Hello, a few small issues I encountered while testing the experimental (so far) @joshuaellis 
1. UI overlap 
Screenshot 2024-01-04 at 11 15 18 AM
2. I tested EE license and Review workflows and it's working fine, except I need to click on 'Save' twice when changing the mapping of CT to a Review workflow https://www.loom.com/share/26dd60bb40de40d2a1c2f5a0d6701466

**Review by MarionLemaire — COMMENTED** [review]
With my SuperAdmin profile, trying to create a new user (both Editor and Author roles), I get a warning error message and no URL to share is created, but when I try again to create the same user, I have a warning message displaying this email address is already used.
See the Loom video [here.](https://www.loom.com/share/81635b4d1348491f8a110bd46bfdb15a?sid=64b8bbca-4257-4ea4-a466-e62b40af75a2
)

**Comment by derrickmehaffy** [comment]
> With my SuperAdmin profile, trying to create a new user (both Editor and Author roles), I get a warning error message and no URL to share is created, but when I try again to create the same user, I have a warning message displaying this email address is already used.
> See the Loom video [here.](https://www.loom.com/share/81635b4d1348491f8a110bd46bfdb15a?sid=64b8bbca-4257-4ea4-a466-e62b40af75a2
> )

You need to set the connect with SSO to false as you are basically creating a user with no password under the assumption they will login using an SSO provider.

**Comment by lucasboilly** [comment]
Hey @joshuaellis , I noticed 2 things:

1. In the link edition popover, the link's placeholder is the URL of Strapi's website, but it should simply be "Paste link".

CleanShot 2024-01-08 at 10 31 18@2x

2. The icons are missing in the checkboxes, but maybe it's a DS issue?

CleanShot 2024-01-08 at 10 06 39@2x

**Comment by joshuaellis** [comment]
Latest experimental – 0.0.0-experimental.f7b9b47085e387e97f990d8695971b51d7f7149a

**Pull request merged**
