### PR TITLE
Fix validation of Date and Time field types for Mongoose connector #5777

### LINKED ISSUE #5777: Be able to set null for date input
**Describe the bug**
I want to clear the date that was set on a field

**Steps to reproduce the behavior**
1. Create a type with a date field that is not required
2. Create an instance of the type with a value in the date field and save it
3. Edit the instance and clear the date field
4. It cannot be cleared
5. Make a GraphQL request to clear the field
6. The request errors

**Expected behavior**
You can clear the field in the UI
The GraphQL mutation works

**Code snippets**
```
mutation UnsetDate($id: ID!) {
  updateYourType(input:{
    where:{
      id: $id
    },
    data: {
      date_field: null
    }
  }) {
    your_type { 
      id
      date_field
    }
  }
}
```

This returns `"message": "Expected type Date, found \"\"; Date cannot represent an invalid date-string ."`

**System**
- Node.js version: 13.7
- Yarn version: 1.22
- Strapi version: 3b19.5
- Database: Mongo 4.2.5
- Operating system: Arch Linux 4.19-97

**Additional context**

### PR DESCRIPTION
**Pull request by richardgrey**
Signed-off-by: richardgrey richie.grey@gmail.com

#### Description of what you did:

This PR fixes #5777 

This changes will allow setting an empty value (null, undefined) for fields of type Date/Time through the API.

In the admin panel, it's still not possible to clear the value of Date or Time fields. It is on buffet/core DatePicker component and has related [feature request](https://github.com/strapi/buffet/issues/97) to be able to clear the value of such inputs.

### CODE REVIEW

**Comment by richardgrey** [comment]
Guys, not sure about the coding style. Kindly let me know if it needs to be changed.

**Comment by darron1217** [comment]
Is there anyone who can confirm this PR?
This is not a big change.

**Comment by darron1217** [comment]
And also we should handle `dateField_null: false` case.

**Review by alexandrebodin — APPROVED** [review]
LGTM, thansk for this fix 💯

**Pull request merged**
