### PR TITLE
Update engines configuration

### PR DESCRIPTION
**Pull request by abdonrd**
#### Description of what you did:

Update engines configuration to make it compatible with Google Cloud.
Because right now, it shows this error:

```
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: The 'package.json' configuration file must specify a supported nodejs10 version that is compatible with the runtime specified in the deployment. Please pin your application to a compatible major version of the runtime via the 'engines.node' property. Supported 'engines.node' values for the runtime 'nodejs10' are: [10.x.x, 10.X.X, 10.x, 10.X, 10.*.*, 10.*, ~10, ~10.0, ~10.0.0, 10, ^10, ^10.0, ^10.0.0, >=10, >=10.0, >=10.0.0, >10.0, >10.0.0, >=1, >=1.0, >=1.0.0, >1, >1.0, >1.0.0, >=2, >=2.0, >=2.0.0, >2, >2.0, >2.0.0, >=3, >=3.0, >=3.0.0, >3, >3.0, >3.0.0, >=4, >=4.0, >=4.0.0, >4, >4.0, >4.0.0, >=5, >=5.0, >=5.0.0, >5, >5.0, >5.0.0, >=6, >=6.0, >=6.0.0, >6, >6.0, >6.0.0, >=7, >=7.0, >=7.0.0, >7, >7.0, >7.0.0, >=8, >=8.0, >=8.0.0, >8, >8.0, >8.0.0, >=9, >=9.0, >=9.0.0, >9, >9.0, >9.0.0].
```

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [x] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Why only in this pacakge ?

**Comment by abdonrd** [comment]
I update this because it is the root `package.json`, the file used to deploy.

**Comment by alexandrebodin** [comment]
> I update this because it is the root `package.json`, the file used to deploy.

Ok make sense. If you don't mind refactoring them all so it is the same ;)

**Comment by abdonrd** [comment]
For sure! All updated now! Also the [documentation plugin](https://github.com/strapi/strapi/pull/3617/commits/231757acb6606c633da9dbd02d33ca45605e34cd).

**Pull request merged**
