### PR TITLE
Update languageNativeNames.ts add O'zbekcha

### PR DESCRIPTION
**Pull request by Shohzod-Abdusamatov-7777777**
I have updated the languageNativeNames.ts file to include the Uzbek language with the key 'uz' and the value 'O'zbekcha'. This modification ensures that the native name for Uzbek is displayed correctly in the language selection options within the Strapi admin panel.

### CODE REVIEW

**Comment by oiorain** [comment]
Hi @Shohzod-Abdusamatov-7777777 
Thanks for your contribution!
Could you fill in the description of your PR, please?

**Comment by Shohzod-Abdusamatov-7777777** [comment]
> Hi @Shohzod-Abdusamatov-7777777 Thanks for your contribution! Could you fill in the description of your PR, please?

Hi! Sure, I'll update the PR description shortly. Thanks for the reminder!

**Review by Shohzod-Abdusamatov-7777777 — COMMENTED** [review]
add uz to languageNativeNames

**Comment by Shohzod-Abdusamatov-7777777** [comment]
@oiorain can we move this comment to the version 4  because I am using this version for  my project

**Comment by mad-zephyr** [comment]
Sorry, for bother you. I would ask you to add in your PR one more language with key "ro" and value "Română". For correct  displayng Romanian langauge. 

 "ro":"Română"

**Review by simotae14 — DISMISSED** [review]
Hello @Shohzod-Abdusamatov-7777777 
Thanks a lot for your contribution, really appreciated!
I am gonna approve it 💪🏽 

Thanks again

**Comment by simotae14** [comment]
@Shohzod-Abdusamatov-7777777 if you can add also the romanian language we can merge both the new languages, thanks

**Review by Shohzod-Abdusamatov-7777777 — COMMENTED** [review]
add Română for languageNativeNames.ts

**Comment by Shohzod-Abdusamatov-7777777** [comment]
> @Shohzod-Abdusamatov-7777777 if you can add also the romanian language we can merge both the new languages, thanks

@simotae14

**Review by simotae14 — APPROVED** [review]
good job 💪🏽

**Comment by simotae14** [comment]
Hey, you have a lint error (probably the missing space between the : and the string `'Română'`), Can you please run `yarn lint:fix` and `yarn pretttier:write` to fix the issue?

**Review by Shohzod-Abdusamatov-7777777 — COMMENTED** [review]
fix eslint

**Review by simotae14 — APPROVED** [review]
🏅

**Comment by simotae14** [comment]
This one is for v5, if you want to do the same for v4 you need to create a PR with base branch `strapi:v4`...let me know if you need more infos how to do it, thank you

**Comment by Shohzod-Abdusamatov-7777777** [comment]
> This one is for v5, if you want to do the same for v4 you need to create a PR with base branch `strapi:v4`...let me know if you need more infos how to do it, thank you

@simotae14 
Yes, I do need it. Could you explain how to do it? Thank you!

**Comment by Shohzod-Abdusamatov-7777777** [comment]
Hello! @simotae14  Thank you for your guidance. I appreciate your offer to assist. If you could help me with starting from the v4 branch, I would be very grateful.

**Comment by simotae14** [comment]
Hey, here you can find your code added in v4 https://github.com/strapi/strapi/pull/22073 👍🏽

**Comment by Shohzod-Abdusamatov-7777777** [comment]
> Hey, here you can find your code added in v4 #22073 👍🏽

Thank you👍🏽

**Pull request merged**
