### PR TITLE
Cron type fix

### PR DESCRIPTION
**Pull request by Boegie19**
### What does it do?

fixes types for cron job

also the lint is failing because of a ts-ignore this is needed because of the type bring wrong I open a PR to fix that https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68941 

The above PR was aproved so the TS-ignroes can now be gone
### Why is it needed?

so cron jobs can be used properly in ts

### How to test it?

test out the with `{ start: startTime, end: endTime, rule: '*/1 * * * * *' }` and `{hour: 14, minute: 30, dayOfWeek: 0}`

### Related issue(s)/PR(s)

fixes https://github.com/strapi/strapi/issues/19710

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Hey @Boegie19 can you rebase this from develop rather than main to clean up some of the dirty commits.

**Comment by Boegie19** [comment]
Will do so tomorow

**Review by alexandrebodin — APPROVED** [review]
LGTM, can you update your PR plz

**Comment by alexandrebodin** [comment]
Thanks for the contribution @Boegie19 💯

**Pull request merged**
