### PR TITLE
added english for norway

### PR DESCRIPTION
**Pull request by JonathanHallen1991**
### What does it do?

Adds a locale for english in Norway. Something we need to be able use Strapi.

### Why is it needed?

We are having an issue when implementing the different locales in our app. All markets we have needs to have their own english version and there is not option for Norway.

### How to test it?

Go in to locales and se if it shows up

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Hey @JonathanHallen1991 can you please sign our CLA, it's required before we can merge any PR.

**Review by derrickmehaffy — APPROVED** [review]
lgtm

**Comment by derrickmehaffy** [comment]
Hey @JonathanHallen1991 can you fix the broken test please?

**Comment by JonathanHallen1991** [comment]
Could not find how to regenerate the snapshot based on the new config file. What do i need to do in order to fix that? @derrickmehaffy

**Review by derrickmehaffy — APPROVED** [review]
Lgtm

**Comment by JonathanHallen1991** [comment]
Can we merge this today?

**Comment by derrickmehaffy** [comment]
Have to wait on a review from the engineers, but it won't be released right away most likely in a week or so as we have the pending v4.15.5 release being worked on before we release anything else merged into main.

**Pull request merged**
