### PR TITLE
Make type of id configurable

### PR DESCRIPTION
**Pull request by kuongknight**
My PR is a: New feature

Main update on the: Framework

Add option idAttributeType to options of model defined config => we can custom type of primary key! 
Add supported uuid type for all attributes

Tested with postgresql and mysql

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@kuongknight Is this Model defined or globally defined?

**Comment by derrickmehaffy** [comment]
related issue: https://github.com/strapi/strapi/issues/1202

**Comment by kuongknight** [comment]
it is Model defined

**Comment by derrickmehaffy** [comment]
@kuongknight Sir you are amazing, thank you.

**Comment by derrickmehaffy** [comment]
Note that some extra testing may need to be done with MySQL as the `varchar(255)` doesn't look quite right.

**Comment by kuongknight** [comment]
varchar(36) is ok?

**Comment by derrickmehaffy** [comment]
@kuongknight that sounds about right, I believe the default Mongo UUID is also 36. A 255 UUID is just a tad large :wink: 

Have you tested this on MySQL yet?

**Comment by derrickmehaffy** [comment]
Per [RFC 4122](https://tools.ietf.org/html/rfc4122#section-3) a UUID is 32 Hex digits + 4 Dashes

**Comment by lauriejim** [comment]
@kuongknight Thank you for this PR.
Can you just update your PR description to add some context of what this PR is doing.

**Comment by kuongknight** [comment]
I updated description

**Comment by Aurelsicoko** [comment]
@kuongknight Can you update the documentation?

**Comment by dj-hedgehog** [comment]
@Aurelsicoko Does it suffice?

**Pull request merged**
