### PR TITLE
feat (content-manager): Use Documents in Single Types controllers

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?

Uses https://github.com/strapi/strapi/pull/18941 work and refactors the single-type controllers to use documents instead of entries.

## What still doesn't work

- Bulk actions (publish, unpublish, delete)
- Relations ( we still need to work some parts on the document service)\
- Publish documents with unique fields (fields are not unique across every entry but across the entire document at the moment).
- Publish/Unpublish many locales at once
- I overlooked permissions, and sanitization.

### Why is it needed?

Describe the issue you are solving.

## 🧪  Test Endpoints
(Should also work for single types)

<details>
<summary><h3>Find Homepage</h3></summary>

`GET  /content-manager/single-types/api::homepage.homepage`

```ts
type QueryParams = {
	locale: string
	status: 'draft' | 'published'
}
```

</details>

<details>
<summary><h3>Create a draft Homepage</h3></summary>

`PUT /content-manager/single-types/api::homepage.homepage`

```ts
type Body = {
	locale: string
} & Document
```

</details>

<details>
<summary><h3>Update a draft Homepage</h3></summary>

`PUT /content-manager/single-types/api::homepage.homepage`

```ts
type Body = {
	locale: string // If the provided locale does not exist, but the document id does, it will create the locale
} & Document
```

</details>

<details>
<summary><h3>Publish a draft Homepage</h3></summary>

`POST /content-manager/single-types/api::homepage.homepage/actions/publish`

⚠️  Publishing many locales at the same time is still not supported
```ts
type Body = {
	locale: string
} 
```

</details>

<details>
<summary><h3>Unpublish a Homepage</h3></summary>

`POST /content-manager/single-types/api::homepage.homepage/actions/unpbulish`

⚠️  Unpublishing many locales at the same time is still not supported

```ts
type Body = {
	locale: string
} 
```

</details>

<details>
<summary><h3>Delete a Homepage</h3></summary>

`DELETE /content-manager/single-types/api::homepage.homepage`

```ts
type Body = {
	locale?: string // if not provided, it will delete the entire document
} 
```

</details>

### CODE REVIEW

**Comment by jhoward1994** [comment]
It seems like when I try to create a single type entry `documentExists` is coming back as true and it is trying to do an update at 

https://github.com/strapi/strapi/blob/83ee8e15ffa1e8755f79a10cd00d12742cef2b07/packages/core/content-manager/server/src/controllers/single-types.ts#L108

**Comment by Marc-Roig** [comment]
@jhoward1994 will check! Thank you

**Comment by Marc-Roig** [comment]
@jhoward1994  it does work for me when there are no locales available for the single type. Could you check thats the case for you?

**Comment by jhoward1994** [comment]
For me when coming from an old version of strapi with a single type with no document ID the update doesn't work from this branch.

It looks like it is because it tries to use the documents number ID field rather than the string doc ID in the document service here

https://github.com/strapi/strapi/blob/d4d47227a6519c49dc53bf408fba273da49e1ba0/packages/core/strapi/src/services/document-service/index.ts#L151

resulting in the existing entry not being found

**Comment by Marc-Roig** [comment]
@jhoward1994 sorry missed this comment.
Ineed, we will need proper migrations so this does not happen. At the moment existing data will have empty document ids, and that is something I can not think of how to solve.

**Comment by Marc-Roig** [comment]
I will merge this in the meantime

**Pull request merged**
