### PR TITLE
Add upload provider Google storage

### PR DESCRIPTION
**Pull request by danielmahon**
My PR is a:

🚀 New feature

Main update on the:

Upload Plugin

# strapi-upload-google-storage

Google Cloud Storage provider for the strapi upload plugin.
Will upload to `https://storage.googleapis.com/[bucket-name]/[hash]/[slugified-file-name].[ext]`
Original filename is restored when downloaded.

## Authentication Setup

1.  Follow the instructions at https://cloud.google.com/docs/authentication/getting-started to create a service account key with at least the `Storage Admin` role.
2.  Download the resulting JSON file containing your key.
3.  Copy the entire file contents into the `Service Account JSON` field under "Upload - Settings" in the Strapi admin.
4.  Enter a storage bucket to use or create.

The provider will parse the JSON for the required credentials.

### CODE REVIEW

**Comment by danielmahon** [comment]
I'm not sure if this is the "correct" place to add this provider or if it should just remain a standalone package. Let me know, thanks!

**Comment by derrickmehaffy** [comment]
@danielmahon Yup you should be doing it correctly, new providers should be their own standalone package as you have done, nice work :smile:

**Comment by danielmahon** [comment]
Looks like the provider's max file size isnt passed to the `koa-body` parser, so currently we need to manually update `request.json` in our respective environment and add the formidable config like so:
```
"formidable": {
  "maxFileSize": 1048576000 // defaults to 200MB
}
```

**Comment by danielmahon** [comment]
Destination path will now be:
`https://storage.googleapis.com/[bucket-name]/[hash]/[slugified-file-name].[ext]`

**Comment by lauriejim** [comment]
Please host your provider on your own GitHub repo, publish it on NPM.
Be sure to complete your maintainer information to let us able to contact you if needed.
Will contact you when we will update the marketplace to add provider section.

**Pull request closed without merging**
