### PR TITLE
Allow JSON stringify to pretty print the config dump via config

### PR DESCRIPTION
**Pull request by piersroberts**
### What does it do?

Currently, a config dump produces a big ugly JSON one-liner which is near impossible to diff. The change in this PR allows the JSON stringify to pretty up the dump over multiple lines allowing for dumps to be easily diffed.

To take advantage of this feature a `commands.js` config file that looks like this;

```
module.exports = {
  configDump: { prettyIndent: 2 },
};
```

and then running `strapi configuration:dump -f sync/core.json` will produce a core.json file with an indentation of 2 chars

If this config file is not present no changes to the current operation will be noticed. This is a non-breaking change.

### Why is it needed?

We were having lots of problems of developers pushing config dumps that would conflict with the json blob in git

### Related issue(s)/PR(s)

n/a

### CODE REVIEW

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
Can you add a command option instead of load a config file ? this can already be handled with command piping => using jq for example

**Comment by piersroberts** [comment]
@alexandrebodin no problem, that's in now. We're desperately trying to avoid dependencies on things like jq so having the ability to do this with a command switch will help us a lot.

**Review by alexandrebodin — APPROVED** [review]
LGTM :)

**Comment by andrewspode** [comment]
I tried adding a commands.js file into /config and it did nothing. I can't find reference to commands.js in the documentation.

I looked the diff of the PR and it mentions instead using "--pretty" for the dump. This isn't mentioned above, nor in the documentation. I tried that and it worked. 

However, the "value" property is in itself serialized JSON and the large part of what you want to see in a diff. Is there a way this could be updated to prettify this property too?

**Comment by alexandrebodin** [comment]
Hi @andrewspode

I don't understand what you are trying to do with command.js :) if you can give me more details :)

For the value property I agree with you. the thing is the data is itself json so we need to escape it to dump it. prettifying it would mean the output would not be json output and won't be restorable. 

I think you are better of creating a small script that will take the output and parse it if you need to do some diffing and simply pipe the output to this script. `strapi config:dump | node my-pretty-script.js`

Hope this helps !

**Comment by andrewspode** [comment]
> Hi @andrewspode
> 
> I don't understand what you are trying to do with command.js :) if you can give me more details :)
> 
> For the value property I agree with you. the thing is the data is itself json so we need to escape it to dump it. prettifying it would mean the output would not be json output and won't be restorable.
> 
> I think you are better of creating a small script that will take the output and parse it if you need to do some diffing and simply pipe the output to this script. `strapi config:dump | node my-pretty-script.js`
> 
> Hope this helps !

Hi @alexandrebodin!

This PR is linked on the changelog for Strapi mentioning this feature and if you scroll to the very top of the page, it suggests adding a commands.js as a way of using it. So my first question/concern is that I couldn't get that to work and there is documentation of any other use of a commands.js file either, so I'm confused there.

I found that it's actually --pretty as a parameter on the dump to get this to work, which is not documented. @MattieBelt agreed that yes this should be documented - so I'm going to do a PR for that but it would be good to have clarify on the commands.js.

Regarding the serialized JSON - what I didn't take into account is that JSON doesn't support multi-line strings so any formatting of this serialized JSON would break the parser. I guess my only question about that, is why it needs to be serialized in the first place as it's only ever storing JSON. If that could be changed, then this prettier becomes 1000x more useful.

**Pull request merged**
