### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by buraksakalli**
#### Description of what you did:

Digital Ocean One Click Deploy steps included some mistakes. I fixed it

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@lauriejim are we still updating the beta docs or is it still in the plan to remove them entirely? These bugs have already been fixed on the latest docs

**Comment by lauriejim** [comment]
If the fix is correct we have no reason to reject it.
The important thing is to check if it's fixed in the stable version.

**Comment by derrickmehaffy** [comment]
@lauriejim the send-mail most certainly is: https://strapi.io/documentation/v3.x/guides/send-email.html#apply-our-changes, as is the digitalocean one-click: https://strapi.io/documentation/v3.x/installation/digitalocean-one-click.html#controlling-the-strapi-service-and-viewing-logs

But since the one-click is no longer offered on the beta I'm not sure if it's worth updating if we just plan to remove those docs.

**Comment by derrickmehaffy** [comment]
I'm going to close this as the one-click no longer applies to the beta.

**Pull request closed without merging**
