### PR TITLE
release: main to develop

### PR DESCRIPTION
**Pull request by Marc-Roig**

### CODE REVIEW

**Review by Convly — APPROVED** [review]

**Review by innerdvations — APPROVED** [review]
I didn't realize we could safely do this from github 😆

**Comment by Marc-Roig** [comment]
@Convly @innerdvations do you know if we did this merge main->develop before? there seems to be some diffs that are not from the release (and prettier is failing too)

**Comment by innerdvations** [comment]
There seems to be a `prettier` issue though 🤔 we might want to fix that before merging to develop

**Comment by Marc-Roig** [comment]
I plan to fix those issues during the day, but I wonder if I messed up something during the merge

**Comment by innerdvations** [comment]
As far as I know we've never merged it this way, only manually. I'm a bit worried about that "Update Branch" button on github getting pushed.

**Pull request merged**
