### PR TITLE
Users Permissions: preserve icon column width, centered icons

### PR DESCRIPTION
**Pull request by veitbjarsch**
#### Description of what you did:

This PR improves the icon column in the user permission table (f.e. email templates). Before FA icons were trimmed on smaller screen resolutions. 
Before:
Screenshot 2019-09-30 at 15 38 47
After:
Screenshot 2019-09-30 at 15 39 33

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [x] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
I think @virginieky is in the process of removing the scss stuff.

**Comment by veitbjarsch** [comment]
I just reverted the changes of the linter to make it more clear what I'm suggesting.

**Comment by soupette** [comment]
@veitbjarsch do you mind changing the base branch of your PR to make it against `develop` we have migrated the plugin to styled-components so your changes won't be reflected.

Thanks a lot

**Comment by veitbjarsch** [comment]
I changed the base branch. Is this everything I need to do?

**Pull request closed without merging**
