### PR TITLE
Improved editing of dynmaic zones by adding toggle for visiblility and 

### PR DESCRIPTION
**Pull request by web-mi**
strapi_dz_improvement

### What does it do?

- Moved dynamic zone CTAs into single bar so every new added CTA will be positioned without the need of absolute positioning
- Added expand function to dynamic zone components by just showing the upper part of compontent for easier idenfication
- Added expand all function to dynamic zones
- Changed move up and move down to single function with offset to reduce nearly duplicated code
- Added move to top and move to bottom button for dynamic zones

### Why is it needed?

1. Editing a content type with many elements in a dynamic zone is currenlty very confusing.
By just showing the first parts of a compontent you could see the top sorted elements first which ist mostly a label or something else which should be enough to identify the compontent you want to edit.

2. Improving moving elements in dynamic zones because new elements could only be added at the end of the zone. So an action with "move to top" will speed up editing dynamic zones.

3. Every single action button for a dynamic zone component is set absolute. To add a new cta you will always need to repositioning every single element.

### How to test it?

Create a content type with a dynamic zone.

_Expand elements:_
Add elements to the dynamic zone and each element will show an eye to toggle the visibility. The dynamic zone itself will have an eye too for toggling all elements at once.  
Default is always showing all components.

_Move elements:_
Add more than 2 items and every item, should have an "move to top" and/or "move to bottom" button.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

Currently i can't find any issue about this function so its just an improvement of editing dynamic zones.
The nearest issue i found was #7941 so i have added the "move to top" and "move to bottom" too.

### CODE REVIEW

**Comment by soupette** [comment]
Thank you for your contribution we will review your PR soon

**Comment by web-mi** [comment]
@LilyLauben i have attached a zip file.
Maybe you could use it by unpacking the code of the zip file inside /extensions directory.
Haven't tried it with the latest release but i think it should work.
[PR_9865.zip](https://github.com/strapi/strapi/files/7369099/PR_9865.zip)

**Comment by web-mi** [comment]
@urbandale could you try this one and give some feedback if it works.
I just made a blind merge because i have currently no time to try everything and nothing is happening in this pr since 6 months so it does not make sense for me to try everything. ;-
[PR_9865.zip](https://github.com/strapi/strapi/files/7382848/PR_9865.zip)
)

**Comment by derrickmehaffy** [comment]
Hi 👋  
We now have released the `v4`. As of now, the `v3` is in maintenance mode for 6 months. We will only be fixing critical and security issues on v3 from now on. 
I will go ahead and close this PR. Thank you for contributing to Strapi 🔥

**Comment by LilyLauben** [comment]
@derrickmehaffy this is a feature we've requested repeatedly and there's been no word for when such an essential, and also pretty straightforward quality of life change will be merged into strapi. Our team is likely going to stop from upgrading to v4 to continue to take advantage of these changes, because they're so critical for our content managers.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy this is a feature we've requested repeatedly and there's been no word for when such an essential, and also pretty straightforward quality of life change will be merged into strapi. Our team is likely going to stop from upgrading to v4 to continue to take advantage of this PR's changes, because they're so critical for our content managers.

I don't disagree at all, All I'm saying is a new PR would need to be made for the Strapi v4 :) 

We are happy to get pull requests, we just had a lot on our plate and didn't get a chance to review before work on v4 started. We are still working on our community contributions for new features.

**Comment by derrickmehaffy** [comment]
@web-mi if you are interested in talking about this with us please let me know :)

**Comment by web-mi** [comment]
https://github.com/strapi/strapi/pull/9898#issuecomment-998282773

**Pull request closed without merging**
