### PR TITLE
Add a config option to disable thumbnail generation

### PR DESCRIPTION
**Pull request by carlosdubus**
### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by Marc-Roig** [comment]
Hello ! :) Thank you for your contribution.

What is your usecase to disable thubmnail generation? For performance reasons, I think the admin panel should have access to these thubmnails.

**Comment by Marc-Roig** [comment]
As stated, for performance reasons we want the thubmnail to be generated always. For now I am closing the issue.

If you could please provide your use case of why you want this enhancement, I will reopen the issue to continue the conversation :)

**Comment by ngotrongphuc** [comment]
> As stated, for performance reasons we want the thubmnail to be generated always. For now I am closing the issue.
> 
> If you could please provide your use case of why you want this enhancement, I will reopen the issue to continue the conversation :)

Hi, I think I have a good reason for that. Since I host my media on S3, I'm really concerned about storage usage - I don't want to have any duplication at all. If I needed image scaling, I could just use a service that allows scaling via URL params like ImageKit. Moreover, my frontend uses Next.js which can scale images on the server-side, so performance isn't a problem for me. It would be great if Strapi would allow me to disable thumbnail generation completely.

**Comment by ngotrongphuc** [comment]
I found a way to disable thumbnail generation in Strapi v5. Simply add this file at ./src/extensions/upload/strapi-server.ts - it overrides the generateThumbnail method of the Upload plugin. Now thumbnails in the media library will use the original image URL as a fallback.
```ts
export default (plugin) => {
  // Override upload plugin to disable thumbnail generation
  plugin.services['image-manipulation'].generateThumbnail = () => {}
  return plugin
}
```

**Pull request closed without merging**
