### PR TITLE
optional deterministic api-token generation

### PR DESCRIPTION
**Pull request by ProfXponent**
### What does it do?

This PR adds functionality to create deterministic api tokens.

### Why is it needed?

This is necessary in many architectures where keys need to be shared at build time prior to deployment.

This is currently not possible because api tokens are generated randomly, so even during the app bootstrap step it is not possible to create a deterministic token that can be shared to dependent services in advance.

This leads to serious issues in orchestrated environments that rely on CI / CD where strapi becomes a single point of manual deployment and potentially causes application downtime on deploy or secondary deployments post key generation in production.

### How to test it?

```javascript
const apiToken = await strapi.admin.services['api-token'].create({
  name: 'My API Token',
  description: 'This is a test API token v1.',
  type: 'full-access', // Or 'read-only', depending on the level of access you need.
  accessKey: 'b23fb4aaaba2276b1aa057cefa12e01b9ef112bb1039deb0942f317737b4f1e253c7fe716658984448b4c00ebfbb47071ba2234f6a08ff9a94e2b03914ce1e0a',
  permissions: [
              // Define specific permissions here if needed.
  ],
})

console.log(apiToken)
```

This should result in a static key generation that can be done during development, checked into secret management, and deterministically recreated in production assuming you used the same salt.

### CODE REVIEW

**Comment by ProfXponent** [comment]
@innerdvations appreciate you self-assigning this.

If possible I would like to start a discussion on the viability of this PR and likelihood it will make it upstream.

My team and I are currently of the opinion that we will monkey-patch it while waiting for it to make it into release, but if that seems like it will not be the case we are going to need to fork and manage a parallel version, which is not ideal to say the least.

From what I can tell it is failing some TS checks and listing, which I am happy to update if you can provide a style guide.

If the issues are more fundamental / ideological let me know so that my team and I can plan accordingly.

**Comment by innerdvations** [comment]
I think this will be fine generally, but I need to determine that there aren't additional security implications.

However, we have a freeze on Strapi 4 (the `develop` branch) for this kind of PR right now, so it would have to wait for Strapi 5.

For your own usage, since you need it soon, I don't think you need to fork or monkey-patch it. It should be possible to create them programmatically (in bootstrap, plugin, custom api endpoint, etc) if you use the query service to create your own tokens, and you will only need to copy/paste your own versions of the `hash` and `create` methods from the api token service file, or if you can use the `update` method directly, which does appear to allow updating them.

**Comment by ProfXponent** [comment]
@innerdvations ok interesting, so you are suggesting creating the key with the appropriate permissions in bootstrap and the updating the value for accessKey post creation with the predefined hash value?

**Comment by ngfgrant** [comment]
I would just like to add that we have a very similar use case - i.e. the ability to pass in a desired API access token (via env vars) and programatically save that access key.

@ProfXponent where did you get to with this? 

At the moment it looks like we are looking at creating the access key programatically during bootstrapping and then update the value using the service API as suggested by @innerdvations. Ideally, we'd prefer to avoid these sorts of gymnastics.

Another option would be a new API `createWithAccessKey(...)` @innerdvations would that still be caught in a feature freeze for v5 or could I put a patch in for that?

**Comment by ProfXponent** [comment]
> I would just like to add that we have a very similar use case - i.e. the ability to pass in a desired API access token (via env vars) and programatically save that access key.
> 
> @ProfXponent where did you get to with this?
> 
> At the moment it looks like we are looking at creating the access key programatically during bootstrapping and then update the value using the service API as suggested by @innerdvations. Ideally, we'd prefer to avoid these sorts of gymnastics.
> 
> Another option would be a new API `createWithAccessKey(...)` @innerdvations would that still be caught in a feature freeze for v5 or could I put a patch in for that?

I ended up generating the key locally via a script and then apply it directly via a migration.

Here is the script

```javascript
const crypto = require('crypto');
const { Buffer } = require('buffer');

// Function to validate if the input is a valid Base64-encoded string
function isValidBase64(s) {
    return s.match(/^[A-Za-z0-9+/]+={0,2}$/) && s.length % 4 === 0;
}

function getApiTokenSalt() {
    const args = process.argv;
    const salt = args[2];

    if (salt && typeof salt === 'string' && isValidBase64(salt)) {
        const decodedBytes = Buffer.from(salt, 'base64');
        const hexString = decodedBytes.toString('hex');
        
        // Ensure the decoded byte length is exactly 16 bytes (32 hex digits)
        if (hexString.length === 32) {
            return salt;
        }
    }
    
    console.error('Error: A valid salt is required. The salt must be a valid Base64-encoded 128-bit (32 hex characters) string, with appropriate padding.');
    process.exit(1); // Exit the script with an error code
}

// taken from strapi token gen function
// https://github.com/strapi/strapi/blob/cb00a1799402728de4ecec6d52a815e33fcedaf3/packages/core/admin/server/src/services/api-token.ts#L167
function createApiToken() {
    return crypto.randomBytes(128).toString('hex');
}

// taken from strapi hash function
// https://github.com/strapi/strapi/blob/cb00a1799402728de4ecec6d52a815e33fcedaf3/packages/core/admin/server/src/services/api-token.ts#L143
function hashApiToken(accessKey, salt) {
    return crypto
        .createHmac('sha512', salt)
        .update(accessKey)
        .digest('hex');
};

function main() {
    const salt = getApiTokenSalt();
    const apiToken = createApiToken();
    const apiTokenHash = hashApiToken(apiToken, salt);
    console.log('API TOKEN SALT:', salt);
    console.log('API TOKEN:', apiToken);
    console.log('API TOKEN HASH (persist to db):', apiTokenHash);
}

main();
```

I call it with the salt for the intended environment the token will be used in

```node
npm run create-api-token cxxxATAwexxxk/SpEq+rbg==
```

Here is a Postgres procedure to update the record that you can call from a migration file

```sql
-- Procedure: proc_strapi_update_api_token
-- Purpose: Updates specific fields of an API token identified by its name in the strapi_api_tokens table,
--          but only if the provided values differ from the existing ones. It raises an exception if no 
--          token with the given name exists, and issues a notice if the data is unchanged.
-- Parameters:
--   p_name (VARCHAR): The name of the API token to update. This acts as the unique identifier.
--   p_description (VARCHAR): The new description to set for the API token.
--   p_type (VARCHAR): The new type to set for the API token.
--   p_access_key (VARCHAR): The new access key to set for the API token.
--   p_expires_at (TIMESTAMP): The new expiration timestamp to set for the API token.
--   p_lifespan (BIGINT): The new lifespan (in days or another unit) to set for the API token.
CREATE OR REPLACE PROCEDURE proc_strapi_update_api_token(
	p_name character varying(255),
    p_description character varying(255),
    p_type character varying(255),
    p_access_key character varying(255),
    p_expires_at timestamp(6) without time zone,
    p_lifespan BIGINT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_count INT; -- Variable to store the count of records that match the given name.
BEGIN
    -- First, check if a record with the specified name exists in the table.
    SELECT COUNT(*)
    INTO v_count
    FROM public.strapi_api_tokens
    WHERE name = p_name;

    -- If no records are found, raise an exception to halt the procedure and inform the caller.
    IF v_count = 0 THEN
        RAISE EXCEPTION 'No API token found with name %', p_name;
    END IF;

    -- Update the API token if it exists and any of the provided values differ from the current values.
    UPDATE public.strapi_api_tokens
    SET description = p_description, 
        type = p_type, 
        access_key = p_access_key,
        expires_at = p_expires_at, 
        lifespan = p_lifespan,
        updated_at = NOW()::timestamp without time zone
    WHERE name = p_name
    AND (description IS DISTINCT FROM p_description OR
         type IS DISTINCT FROM p_type OR
         access_key IS DISTINCT FROM p_access_key OR
         expires_at IS DISTINCT FROM p_expires_at OR
         lifespan IS DISTINCT FROM p_lifespan);

    -- After attempting the update, check if any rows were actually changed.
    IF NOT FOUND THEN
        -- If no rows were updated, issue a notice indicating that no changes were necessary.
        RAISE NOTICE 'No changes were made for the API token with name %, as the data provided matches existing values.', p_name;
    END IF;
END;
$$;
```

And here is an example of it being used


```sql
-- Calling the procedure proc_strapi_update_api_token to update an existing API token in the database.
-- The procedure updates the token only if the new values differ from the existing ones in the specified fields.
CALL proc_strapi_update_api_token(
    p_name := 'DEFAULT_CMS_API_TOKEN',     -- The name of the API token. This is a unique identifier for the API token.
    p_description := '',                   -- The new description for the API token. Here, it's set to an empty string, indicating no description.
    p_type := 'custom',                    -- The type of the API token. 'Custom' implies a specific kind of access or usage not covered by standard types.
    p_access_key := '9ca9fa43b13dc965ead228a06025ba82ffcaa3a12a37f6756b8b37ceabe04aa79b1f203bd19757f1e1e0df035e13db4708028b13e63b73621c379e4594a69bbe', -- The new access key for the API token. Typically, this should be a securely generated hash.
    p_expires_at := NULL,                           -- The expiration date for the API token. Setting this to NULL means the token does not expire.
    p_lifespan := NULL                              -- The lifespan of the API token. NULL indicates that there is no set lifespan, and the token remains valid indefinitely.
);
```

I do something similar with strapi internal configs and check them into version control as yaml files that are migrated on deploy.

As a team we decided to move away from strapi soon over issues like this in favor of a simpler internal solution for our content management needs.

**Comment by alexandrebodin** [comment]
> [!IMPORTANT] 
> With the release of Strapi 5, we have lifted the code freeze. To ensure we can effectively review and assist with contributions, we are now only accepting PRs targeting version 5 (the develop branch).<br/> 
> As your PR is targeting some of the most recent v4 version, We we would greatly appreciate it if you could update your contribution to align with version 5 and resubmit!

**Comment by innerdvations** [comment]
Closing this, but if anyone would like to create a version targeting v5, it would be fine to allow the create method to accept an accessKey to use, since we already do that for the update

**Pull request closed without merging**
