### PR TITLE
Batching and caching requests using DataLoader for GraphQL

### LINKED ISSUE #2228: Use facebook/dataloader to improve GraphQL performance
**What is the expected behavior?**

The current graphql plugin redundantly fetches data from mongodb and suffers from n+1 problem, which is very common for un-optimized graphql resolvers implementations. Example: 

```graphql 
query { 
  posts { 
    title 
    bins {
       title
    }
  } 
}
```

And the mongodb log:

image

Notice that different posts may have same bins, which have already been fetched in earlier `find`s for the first `post`, but is being stupidly refetched again and again for the later `post`s.

The common solutoin for this issue is to use https://github.com/facebook/dataloader

### PR DESCRIPTION
**Pull request by Aurelsicoko**
My PR is a:
- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix #issueNumber
- [x] 💅 Enhancement
- [ ] 🚀 New feature

Main update on the:
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

I've implemented the DataLoader library on our GraphQL plugin. It reduces drastically the numbers of requests. 

For example, this query was generating **16 SQL or Mongo requests**.
```js
{
  users {
    email
    products (where: { name: "Product 1" }) {
      name
      users (limit: 1) {
        email
      }
    }
  }
}
```

Thanks to this PR, **it only generates 4 SQL or Mongo requests**. The **response time is reduced by 400%** as well. It was only tested with 3 users and 3 products in the database. If you've hundreds or thousands of entries in the database, the gain will be crazy.

Close #2228

### CODE REVIEW

**Comment by kamwing** [comment]
@Aurelsicoko 

is there any new progress?

**Comment by Aurelsicoko** [comment]
I was on holidays during the last two weeks. I'll continue my work next week to merge it for the next release 💪

**Comment by kamwing** [comment]
Happy holidays :) @Aurelsicoko

**Comment by Aurelsicoko** [comment]
This PR has been pulled on the #2380. We can close it and the work done here will be merged.

**Pull request closed without merging**
