### PR TITLE
Add collapse option to dynamic zone 

### PR DESCRIPTION
**Pull request by louieheaton**
### What does it do?

- Adds an options to the Dynamic Zone to have a collapse by default option

### Why is it needed?

- Lots of content inside of components and lots of components inside a dynamic zone makes it difficult to add/move components. Many discussions been raised about this

https://github.com/strapi/strapi/issues/16737
https://forum.strapi.io/t/strapi-v4-dynamic-zono-components-to-be-closed-by-default/25661
https://github.com/strapi/strapi/issues/15655

### How to test it?

- Add a dynamic zone to a content type
- Go into Advanced Settings
- Select the new option for Collapsed by Default
- Add a component field
- Create a new entry
- Add a couple of the new components
- Save the page
- Refresh and confirm that the items are collapsed by default

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

https://github.com/strapi/strapi/issues/16737
https://github.com/strapi/strapi/issues/15655

### CODE REVIEW

**Comment by dimitrisganotis** [comment]
Any updates on this request?

**Comment by alexandrebodin** [comment]
> [!IMPORTANT] 
> With the release of Strapi 5, we have lifted the code freeze. To ensure we can effectively review and assist with contributions, we are now only accepting PRs targeting version 5 (the develop branch).<br/> 
> As your PR is targeting some of the most recent v4 version, We we would greatly appreciate it if you could update your contribution to align with version 5 and resubmit!

**Comment by remidej** [comment]
Hello, thanks for the PR, but as we've moved our development efforts to the newer Strapi 5 version, we'll only accept PRs on v4 if it's bug fixes.

Would you be interested in re-opening a PR on top of Strapi 5 (develop branch)?

And ping @lucasboilly to check if the UX would work for us

**Comment by louieheaton** [comment]
Looks like this is rectified in v5 - dynamic menus already are closed by default

**Comment by xenobytezero** [comment]
+1, is there a way to have these open by default?

**Pull request closed without merging**
