### PR TITLE
chore: update quickstart behavior to disable example app

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Changing the default behavior for the example app

cc @pwizla can you update the cli doc to say the example app will not be included with the quickstart ?

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Pre-release `0.0.0-experimental.f6c00790e260ea5a9b6b86abac5fea02b05d569c`

**Comment by alexandrebodin** [comment]
> Not caused by this PR, but I just noticed that when I used --quickstart, we do not create a `.gitignore`, so node_modules are being included when we initialize git. Do you want to quickly fix that here, or should we create a separate PR for it?

I'll add the gitignore in the template here

**Review by innerdvations — APPROVED** [review]
LGTM! We just need to check it with an experimental tomorrow to be sure

**Comment by alexandrebodin** [comment]
New experimental `0.0.0-experimental.626cf5324f21d318dee435c11cb3e08bb4c414b7`

**Pull request merged**
