### PR TITLE
Fix command not mounting the routes correctly

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Fixes https://github.com/strapi/strapi/issues/17390

### Why is it needed?

To fix a bug

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Review by derrickmehaffy — APPROVED** [review]
Tested manually (via node_modules patch)

image

**Comment by derrickmehaffy** [comment]
Patch File for those that need it: 
[patches.zip](https://github.com/strapi/strapi/files/12111991/patches.zip)

**Review by innerdvations — APPROVED** [review]
Tested and works for me

**Review by Convly — APPROVED** [review]
That might be the most reviewed PR, but... Tested and works on my side.

**Pull request merged**
