### PR TITLE
Fix several security vulns on v3

### PR DESCRIPTION
**Pull request by derrickmehaffy**
## What this PR does

Updates the following dependencies to fix security warnings:

- [immer](https://www.npmjs.com/package/immer): v8.0.1 to v9.0.16
- [git-url-parse](https://www.npmjs.com/package/git-url-parse): v11.4.4 to v13.1.0
- [koa-passport](https://www.npmjs.com/package/koa-passport): v4.1.4 to v5.0.0
- [moment](https://www.npmjs.com/package/moment): v2.29.1 to v2.29.4
- [mongoose](https://www.npmjs.com/package/mongoose): v5.10.8 to v5.13.15
- [sanitize-html](https://www.npmjs.com/package/sanitize-html): v2.3.3 to v2.7.2
- [swagger-ui-dist](https://www.npmjs.com/package/swagger-ui-dist): v3.47.1 to v4.15.1
- [sharp](https://www.npmjs.com/package/sharp): v0.29.0 to v0.31.1
- [koa2-ratelimit](https://www.npmjs.com/package/koa2-ratelimit): v0.9.0 to v1.1.2
- [package-json](https://www.npmjs.com/package/package-json): v6.5.0 to v7.0.0 (this may not fix all the vulns but we can't upgrade further as they have gone full ESM-only)

Does the following other misc things:

- Removes node 12 from tests since it's EOL
- Disables a few eslint rules that don't matter in the short term

Decreased total vulnernabilities from a `yarn audit` from ~400 down to 74; see below for vulns we will not be patching in v3.

## Special notes

We will need to document in the next release that we will not be able to provide security updates on the following packages as they require too much refactoring:

- [package-json](https://www.npmjs.com/package/package-json): Converted to ESM only, breaking changes
- [mailgun-js](https://www.npmjs.com/package/mailgun-js): Package no longer maintained, replacement has far too many breaking changes to backport updates in v4
- [node-fetch](https://www.npmjs.com/package/node-fetch): Only used in limited places in the code-base that bad actors cannot interact with
- [ejs](https://www.npmjs.com/package/ejs): Package (strapi-hook-ejs) isn't used and isn't recommened for usage
- [pkgcloud](https://www.npmjs.com/package/pkgcloud): Only used by the rackspace provider which we have cut all support on for both v3 and v4
- [webpack-dev-server](https://www.npmjs.com/package/webpack-dev-server): Far too many breaking changes, this is only used on local development and has no impact on production applications
- [apollo-server-koa](https://www.npmjs.com/package/apollo-server-koa): Several breaking changes that require massive refactoring, will not backport fixes as it would require far too much time
- [graphql-upload](https://www.npmjs.com/package/graphql-upload): Converted to ESM only, breaking changes
- [sqlite3](https://www.npmjs.com/package/sqlite3): Maintainer has changed hands, requires far too much refactoring for an issue that only occurs when you compile the binary manually, doesn't impact production applications
- [lerna](https://www.npmjs.com/package/lerna): Used for repo-only tooling, does not impact end-users at all 

Also we should add a reminder to the release notes that security support will end on Dec 31st 2022

### CODE REVIEW

**Comment by alexandrebodin** [comment]
That's a lot of major upgrade. Let's see how the tests behave

**Comment by derrickmehaffy** [comment]
@alexandrebodin do you want me to try and fix these lint issues?

**Comment by alexandrebodin** [comment]
@derrickmehaffy I tried checking out v3.6.10 and didn't get that error. 
It's probably coming from an eslitn udpate done by yarn autmatically because the version isn't strict in the pkg json. either you fix the code (which should be straight forward for most of the issues apparently or you can revert the eslint version upgrades done by yarn)

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I tried checking out v3.6.10 and didn't get that error. 
> It's probably coming from an eslitn udpate done by yarn autmatically because the version isn't strict in the pkg json. either you fix the code (which should be straight forward for most of the issues apparently or you can revert the eslint version upgrades done by yarn)
> 

I'll just try fixing the eslint stuff it's fine

**Comment by gu-stav** [comment]
@derrickmehaffy The tests should run again with abfa85672ac7e688dc4f06bb4a1b60e988dc96d9. I had to update the jest setup to match the one from v4 (which is the proper one), because otherwise, we'd have to add typescript as a hard dependency.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy The tests should run again with abfa85672ac7e688dc4f06bb4a1b60e988dc96d9. I had to update the jest setup to match the one from v4 (which is the proper one, because @swc/jest is the documented setup for these transforms), because we'd have to add typescript as a hard dependency otherwise.

Thank you. 🙏

**Comment by derrickmehaffy** [comment]
Alright I have no idea why the hell node is running out of memory here.

**Comment by derrickmehaffy** [comment]
@alexandrebodin is currently working on a parallel PR to see if he can work around some of the upgrade errors I was getting: https://github.com/strapi/strapi/pull/14914

**Comment by derrickmehaffy** [comment]
Closing in favor of https://github.com/strapi/strapi/pull/14914

**Pull request closed without merging**
