### PR TITLE
Add lodash to package.json to avoid version problem

### PR DESCRIPTION
**Pull request by TheWebsDoor**

### CODE REVIEW

**Comment by lauriejim** [comment]
Hi @TheWebsDoor where in your code you use lodash and the version is not correct ?

**Comment by TheWebsDoor** [comment]
Hi @lauriejim, in your `strapi-plugin-upload/services/Upload.js`, the method bufferize uses `_.isBuffer` or in content-manager or in strapi-mongoose, you use` _.differenceWith` and I think that there are some more that don't exist in the default installed version on Strapi (which for us is the version **3.10.1**).
The problem is that lodash is installed by default from another package and the version used by this package is the **3.10.1**... 
If you use lodash in your code, I think that you have to put it as a dependency for your project and not get it from another dependency package.

**Comment by lauriejim** [comment]
Here is the lodash dependency of Strapi https://github.com/strapi/strapi/blob/master/packages/strapi/package.json#L52

**Comment by TheWebsDoor** [comment]
Good catch thanks

**Pull request merged**
