### PR TITLE
fix: always return an object if data is falsey

### LINKED ISSUE #15751: Blank pages in admin media libraray after upgrade to 4.6.0
### Required System information

Node.js version: 18.9.1
NPM version: 8.19.1
Strapi version: 4.5.6
Database: MySQL
Operating system: Ubuntu 64 Bit

### Describe the bug
After upgraded Strapi from 4.5.6 to 4.6.0, we can't access the "Media Library" page (http://my-host/admin/plugins/upload).
When we trace the browser calls, we see that the call https://my-host/upload/configuration returns a null data.

If we pass the sorting in the url, the page is displayed (ex : /admin/plugins/upload?sort=createdAt:DESC&page=1&pageSize=10), the page is displayed.

Moreover, if we try to modify an existing image, we have a similar error

### Screenshots
image

image

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* always returns an `object` for `data`

### Why is it needed?

* we assume we're always going to get an `object` so we don't do `?` checks

### How to test it?

* automated testing!

### Related issue(s)/PR(s)

* resolves #15751
* resolves CONTENT-1070

### CODE REVIEW

**Comment by joshuaellis** [comment]
Hey @Marc-Roig & @jhoward1994 is it normal for `strapi.store({ type: 'plugin', name: 'upload', key: 'view_configuration' }).get()` to return a `null` value? Just wanted to see if this is BE mistake and the FE can rely on getting default values all the time or we do need to include this check?

**Comment by jhoward1994** [comment]
> Hey @Marc-Roig & @jhoward1994 is it normal for `strapi.store({ type: 'plugin', name: 'upload', key: 'view_configuration' }).get()` to return a `null` value? Just wanted to see if this is BE mistake and the FE can rely on getting default values all the time or we do need to include this check?

To me this is strange behaviour, `strapi.store({ type: 'plugin', name: 'upload', key: 'view_configuration' }).get()` should return the view configuration of the upload plugin. Which has been present in the app since v4.5.5 - see https://github.com/strapi/strapi/pull/14700

The issue mentions that the bug happened when updating from v4.5.6 - v4.6.0, I'm struggling to see how `view_configuration` could return null following this upgrade 🤔

I think it is worth making this fix but I don't think it's the root issue. @Marc-Roig wdyt?

**Comment by gu-stav** [comment]
Should me merge this as an emergency fix and create a follow-up issue in Jira to find and address the root cause?

**Comment by Marc-Roig** [comment]
> I think it is worth making this fix but I don't think it's the root issue. @Marc-Roig wdyt?

I agree, if the problem is the store returns a null value, is because it's not created in the DB, and it's something we should fix.
Nevertheless I agree with gustav too, we should merge this as a temporary fix until we find a solution.

Would you mind creating an exploration ticket for this @jhoward1994 ?

**Comment by joshuaellis** [comment]
Great, if someone can review/approve we can get this merged :)

**Review by gu-stav — APPROVED** [review]

**Pull request merged**
