### PR TITLE
feat(dts): support models and contentTypes

### PR DESCRIPTION
**Pull request by markkaylor**
### What does it do?

- Includes strapi models alongside contentTypes to delete any entries belonging to models included in the DTS import

### Why is it needed?

- e2e tests are currently using DTS to reset the database. History is a new feature using models over contentTypes. The data is not being reset since currently DTS does not take models into consideration.

### How to test it?

- Create a model using the models API
- Export data using DTS
- Make changes to add entries to the model's table
- Import data and see that the model data was reset

The easiest way to test is maybe on this branch: https://github.com/strapi/strapi/pull/19525 where the patch is in place as well. The history-versions model is used in the data import for each test.

co-authored by @Convly

### CODE REVIEW

**Comment by innerdvations** [comment]
Thank you so much Mark for handling this!

Looks like there are failing unit tests. Could you update them to also include a check for this specific case (handling both models and contentTypes) ?

**Review by christiancp100 — APPROVED** [review]

**Comment by markkaylor** [comment]
@innerdvations @Convly I updated the tests to check models are considered in the `include` array if you have a second to give that a once over :)

**Review by innerdvations — APPROVED** [review]
Code LGTM! Did you try this out with a regular project import/export/transfer to make sure it still works ok and clears what it should (or doesn't clear what it shouldn't)?

**Comment by markkaylor** [comment]
I had only tested it in my e2e PR. I tried testing it this morning but I keep getting an error on import. I have the same on v5/main though so not sure it is related to these changes here.
Screenshot 2024-02-27 at 09 28 20

any ideas @innerdvations

**Comment by christiancp100** [comment]
> ~I had only tested it in my e2e PR. I tried testing it this morning but I keep getting an error on import. I have the same on v5/main though so not sure it is related to these changes here.~ Screenshot 2024-02-27 at 09 28 20
> 
> ~any ideas @innerdvations?~
> 
> nvm found the issue

Maybe Finally we've got someone at strapi who's able to reproduce this error 😂

**Comment by markkaylor** [comment]
> > ~I had only tested it in my e2e PR. I tried testing it this morning but I keep getting an error on import. I have the same on v5/main though so not sure it is related to these changes here.~ Screenshot 2024-02-27 at 09 28 20
> > ~any ideas @innerdvations?~
> > nvm found the issue
> 
> Maybe Finally we've got someone at strapi who's able to reproduce this error 😂

I think this one had something to do with components pointing to entries that didn't exists anymore 🤷 when I deleted the components it was fine.

**Comment by markkaylor** [comment]
I'm having another issue where the import works (I see everything in the database), but whens starting the Strapi app it's like I don't have permissions to see anything, the app looks empty, going to the content manager just throws an error. Still investigating but would be great if someone else could QA this PR as well to confirm this issue 🙏

**Comment by markkaylor** [comment]
Updates:
- Use strapi.get('models').get() instead of strapi.db.metadata 

How to test
- Create a model with the following code snippet in examples/getstarted register:

'use strict';

const historyVersion = {
  uid: 'plugin::content-manager.history-version',
  tableName: 'strapi_history_versions',
  singularName: 'history-version',
  attributes: {
    id: {
      type: 'increments',
    },
    name: {
      type: 'string',
    },
  },
};

module.exports = {
  /**
   * An asynchronous register function that runs before
   * your application is initialized.
   *
   * This gives you an opportunity to extend code.
   */
  register({ strapi }) {
    strapi.get('models').add(historyVersion);
  },
- In a db explore add an entry to the history-versions table
- Run the export
- Run the import
- The entry added to the history-versions table should no longer be there
- Otherwise the import should have behaved as normal and the CMS should function as expected

**Comment by innerdvations** [comment]
A bunch of failing things related to releases which I assume isn't caused by this :(

**Comment by markkaylor** [comment]
> A bunch of failing things related to releases which I assume isn't caused by this :(
> 
> Other than that, looks good. Can you try merging in v5/main if whatever problem is fixed there and see if the tests pass now?

This branch is up to date with v5/main. I feel confident the changes here didn't introduce the issues with the failing test. I will look on the v5/main branch to see what's up.

**Review by Convly — APPROVED** [review]
Tested and works well. Not 100% fan of what we've done here, but let's improve it later

**Pull request merged**
