### PR TITLE
Respect "Size optimization" setting on image resize

### PR DESCRIPTION
**Pull request by krestaino**
### What does it do?

When "Responsive friendly upload" is enabled, the resized images are using default quality options (80) even with "Size optimization" disabled. This PR just checks whether "Size optimization" is enabled or not during the resizing process.

### Why is it needed?

Resized images are compressed even with "Size optimization" disabled.

### How to test it?

1. Enable "Responsive friendly upload" and disable "Size optimization", upload an image and check the quality and file size of the resized images.
2. Pull this PR and do the same test, you'll notice the resized images are larger in file size and of better quality.
3. Disable "Size optimization" and test again. You'll see the resized images are compressed again.

### CODE REVIEW

**Comment by krestaino** [comment]
I just pushed a new commit which allows you to configure options per format in `config/plugins.js`. For example:

```
module.exports = () => ({
  upload: {
    config: {
      formats: {
        jpeg: {
          chromaSubsampling: '4:4:4',
          quality: 95
        },
        png: {
          compressionLevel: 9,
          progressive: true
        }
      }
    }
  }
});
```

**Comment by krestaino** [comment]
Is there anything I can do to help get this merged in?

**Comment by krestaino** [comment]
I've added documentation.

https://github.com/strapi/documentation/pull/1768

**Comment by alexandrebodin** [comment]
Hi @krestaino, the way the processing works is that the original image is 1st optimized and then that optimized image is resized for each responsive formats using the default optimization config to avoid loosing too much information as it is done on top of an already optimized image. 

We did this to avoid to reduce processing a bit but it's open for discussion. 

Considering how old this PR is I'm going to close it as we made some changes already and are about to release v5 RC. Feel free to check it out and see if it's worth applying this PR to it. Thank you for your contribution !

**Pull request closed without merging**
