### PR TITLE
update to sharp 0.28 for cpu arm (m1)

### PR DESCRIPTION
**Pull request by mehdiraized**
https://github.com/strapi/strapi/issues/9121

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@mehdiraized thank you, please don't forget to sign the CLA as it's a requirement to merge after we review.

**Comment by mehdiraized** [comment]
> @mehdiraized thank you, please don't forget to sign the CLA as it's a requirement to merge after we review.

what is CLA ?

**Comment by mehdiraized** [comment]
> @mehdiraized thank you, please don't forget to sign the CLA as it's a requirement to merge after we review.

Thanks, it worked

**Comment by derrickmehaffy** [comment]
I've manually given this PR to our engineering team to validate, we have a handful of M1 based macs on the team so we will confirm. Thanks!

**Comment by alexandrebodin** [comment]
Closing as we merged a dependabot PR doing this update in master already :)

**Comment by derrickmehaffy** [comment]
Related dependabot PR: https://github.com/strapi/strapi/pull/9927

**Pull request closed without merging**
