### PR TITLE
Add new LinkedIn opendid provider

### PR DESCRIPTION
**Pull request by lswartsenburg**
This PR is based on https://github.com/strapi/strapi/pull/15216

This PR is a retry of https://github.com/strapi/strapi/pull/19610 with an updated  commit email

### What does it do?

This PR adds support for the new LinkedIn OpenID Authentication (https://www.linkedin.com/developers/news/featured-updates/openid-connect-authentication)

### Why is it needed?

All new LinkedIn apps are now forced to use the new OpenID standard and will therefore have to use this provider.

### How to test it?

image

### Related issue(s)/PR(s)
- https://github.com/strapi/strapi/pull/15216
- https://forum.strapi.io/t/linkedin-provider-sign-in-issue/35841/2
- https://github.com/strapi/strapi/issues/19641

### CODE REVIEW

**Comment by lswartsenburg** [comment]
@derrickmehaffy Can you take a look at this PR? I fixed the author email issue you flagged in https://github.com/strapi/strapi/pull/19610 with this new PR

**Comment by Melak12** [comment]
Thanks @lswartsenburg  for this PR. I need also this to be merged.

**Comment by lswartsenburg** [comment]
@derrickmehaffy What is the best way to get this merged?

**Comment by martin-kolarov** [comment]
+1 this is very much needed

**Comment by lswartsenburg** [comment]
@innerdvations Do you think we can proceed with merging this?

**Comment by pos1234** [comment]
What is the progress of this pr when is it going to be merged?

**Comment by alexandrebodin** [comment]
Hello, I have tried this PR and cannot make it work, it is missing the scope in the config & after manually changing those it just won't work.

We have a working PR https://github.com/strapi/strapi/pull/20625 so I'll close this one

**Comment by lswartsenburg** [comment]
@alexandrebodin lookedat your PR. It's backward incompatible with people not openid, so it will break a lot of setups

**Pull request closed without merging**
