### PR TITLE
datetime must conform with openapi spec

### LINKED ISSUE #7149: Incorrect datetime type generated in the Documentation plugin
**Description**
When generating swagger documentation using strapi-plugin-documentation, we see that for data type "Datetime" swagger documentation generated is also "datetime". This instead according to [OpenAPI](https://swagger.io/specification/#oas-document) standards should be "date-time"

**Steps to reproduce the behavior**

1. Using content-type buider create new data type with a datetime field
2. Build strapi with  strapi-plugin-documentation configured

**Expected behavior**
Should generate swagger documentation with `date-time`

**Screenshots**
image
image

**System**

- Strapi version: 3.0.0
- strapi-plugin-documentation version: 3.0.0

### PR DESCRIPTION
**Pull request by littleski**
## Added a special case for handling datetime type
should fix #7149

Should be ok since there is no test existing in this plugin. Let me know if i need to do something else.
Cf https://swagger.io/specification/ -> Data Types

## Changed default structure for requestBody,
as it was breaking most codegen with the following error:
`codegenModel is null. Default to UNKNOWN_BASE_TYPE`
see https://swagger.io/specification/#pathItemObject
It's now working much better.

Sorry, i just discovered strapi this morning, and this got me frustrated.

### CODE REVIEW

**Comment by littleski** [comment]
Added a second commit as i had another small error. I basically really want to be able to use codegen on the doc generated by strapi to generate sdk for all the apps interacting with the backend.

**Review by petersg83 — CHANGES_REQUESTED** [review]
Hi :) 
Thanks for your contribution !
From what I see the format attribute was never set and you have set it for the `datetime` type. Can you also do it for `date` and `password` please?
I suggest making the function `getFormat` that would work like the function `getType`.

**Comment by alexandrebodin** [comment]
Closing for inactivity. Feel free to reopen if you can eventually pick it up ;)

**Comment by henrych4** [comment]
Mind if I pick it and continue the work?

**Comment by littleski** [comment]
Feel free. I won't have time any time soon.

Le mar. 13 oct. 2020 à 17:18, Alexandre BODIN <notifications@github.com> a
écrit :

**Pull request closed without merging**
