### PR TITLE
Add support to upload cloudinary file to specific folder with path variable

### PR DESCRIPTION
**Pull request by angelbanderasudg**
### What does it do?

This makes possible to upload files to a specific folder for the upload-cloudinary provider, like the aws-s3 provider, taking the path variable as the folder

### Why is it needed?

By using it, you can organize your files on cloudinary

### How to test it?

Just set your cloudinary details for the plugin, open the /upload endpoint and send a request with the "files" and "path" variable

### Related issue(s)/PR(s)

---

### CODE REVIEW

**Comment by SalahAdDin** [comment]
> ### What does it do?
> 
> This makes possible to upload files to a specific folder for the upload-cloudinary provider, like the aws-s3 provider, taking the path variable as the folder
> ### Why is it needed?
> 
> By using it, you can organize your files on cloudinary
> ### How to test it?
> 
> Just set your cloudinary details for the plugin, open the /upload endpoint and send a request with the "files" and "path" variable
> ### Related issue(s)/PR(s)

Is it all? Just these few lines?

What are we waiting for @derrickmehaffy ?

**Comment by SalahAdDin** [comment]
> ### What does it do?
> 
> This makes it possible to upload files to a specific folder for the upload-cloudinary provider, like the aws-s3 provider, taking the path variable as the folder
> ### Why is it needed?
> 
> By using it, you can organize your files on cloudinary
> ### How to test it?
> 
> Just set your cloudinary details for the plugin, open the /upload endpoint and send a request with the "files" and "path" variable
> ### Related issue(s)/PR(s)

Is it all? Just these few lines?

@angelbanderasudg Can you add documentation for this? 

Also, what about setting the main default folder for it? Let's say, we have more projects connected to the same Cloudinary "bucket", so we want to set all media related to project A in projectA folder(all the Strapi folder within), and the media from project B in projectB, etc.

It would like to add a prefix for the file path with the name of the project(from an environment variable, for instance, or from another **Strapi** setting), and following by the folder path, which is already a property for any media content.

What do you think about this @derrickmehaffy and **Strapi** staff?

**Comment by diegovfeder** [comment]
Any updates here? Looking forward to this.

**Comment by Marc-Roig** [comment]
This looks good to me, could you fix the merge conflicts?
Also the branch should not be named master, but should follow the

**Comment by Marc-Roig** [comment]
Fixed the conflicts :) Everything works on my side, I will merge when tests pass

**Review by Marc-Roig — APPROVED** [review]

**Comment by SalahAdDin** [comment]
> ### What does it do?
> 
> This makes possible to upload files to a specific folder for the upload-cloudinary provider, like the aws-s3 provider, taking the path variable as the folder
> ### Why is it needed?
> 
> By using it, you can organize your files on cloudinary
> ### How to test it?
> 
> Just set your cloudinary details for the plugin, open the /upload endpoint and send a request with the "files" and "path" variable
> ### Related issue(s)/PR(s)

Can you document this?

**Comment by Marc-Roig** [comment]
@SalahAdDin For some reason I missed completely your message on this thread.

About the documentation, I am looking for a way we could document providers. https://docs.strapi.io/developer-docs/latest/plugins/upload.html#examples Right now, in the docs, we only mention the user to look up the provider configuration. 

But we should have a way to document this, I will take a look.

> Also, what about setting the main default folder for it? Let's say, we have more projects connected to the same Cloudinary "bucket", so we want to set all media related to project A in projectA folder(all the Strapi folder within), and the media from project B in projectB, etc.

> It would like to add a prefix for the file path with the name of the project(from an environment variable, for instance, or from another Strapi setting), and following by the folder path, which is already a property for any media content.

That is a good idea, but maybe it could fit in another PR so we can have a discussion for it. would you be open to work on it? :)

**Pull request merged**
