### PR TITLE
docs: fix 404 in PR template

### PR DESCRIPTION
**Pull request by roschaefer**
### What does it do?

Fix a 404 in this very pull request template

### Why is it needed?

Link is broken

### Related issue(s)/PR(s)

discovered this in #8459

### CODE REVIEW

**Comment by roschaefer** [comment]
@strapi learned about the `--sign-off` feature just now: https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for

It's quite a pain that you cannot update the docs through GitHub Web UI and send a PR which passes the checks. :confused:

**Comment by derrickmehaffy** [comment]
The link provided in the PR template appears to work for me? 

image

**Comment by roschaefer** [comment]
@derrickmehaffy yes, you have the fixed URL in the address bar.

The broken link (which this PR is fixing) is: https://github.com/strapi/strapi/blob/docs/contribguide/CONTRIBUTING.md

**Review by derrickmehaffy — APPROVED** [review]
Yup your right, I completely missed that, thank you :)

**Pull request merged**
