### PR TITLE
Fix search select

### PR DESCRIPTION
**Pull request by soupette**

### CODE REVIEW

**Comment by Aurelsicoko** [comment]
It's not working as expected, there are many errors when we are searching a value in the select.

```bash
[2018-04-20T08:45:12.939Z] error Cast to ObjectId failed for value "[object Object]" at path "_id" for model "Tag"
[2018-04-20T08:45:12.939Z] debug GET /content-manager/explorer/tag/[object%20Object]?source=content-manager&name_contains=couc (3 ms)
```

**Comment by soupette** [comment]
@Aurelsicoko could you provide the steps to reproduce because it's working on my side

**Comment by Aurelsicoko** [comment]
@soupette Done(in private), I'm waiting for the changes 🙈

**Comment by oeddyo** [comment]
Hi, 

we are wondering when this would be released? If there's no plan, is there any way we can use this patch before release? Our editors are frustrating with this 20 limit issue :/

Thanks!

**Comment by XcrossD** [comment]
I'm also hoping that this gets released soon (currently on alpha.12.0.1). IMO not being able to select what you want to link in the relation defeats the purpose of setting up relations. Not to mention that data easily go over 20 entries in quite a lot of applications.

**Comment by soupette** [comment]
@XcrossD a lazy load has been added, the search now works also

**Pull request merged**
