### PR TITLE
fixed issue 5266

### LINKED ISSUE #5266: When adding new content, select field was incorrectly wrapped
**Describe the bug**
When adding new content, select field was incorrectly wrapped.

image

image

The select field is very short, and drop down options are all broken.

image

Dropdown came from dynamic zone with relations child.

image

**Steps to reproduce the behavior**
1. Setup a new new component (eg. Pricing). Include a Relations field in this component, relating to any content type (eg. Currency)
2. Update an existing content type (eg. Products) and add a new dynamic zone (Pricing). Add the newly created component to the dynamic zone.
3. Go to your existing content type and create new entry

**Expected behavior**
The select box should be wrapped properly like this:

Screen Shot 2020-02-19 at 5 39 01 AM

**System**
- Node.js version: v13.8.0
- NPM version: 6.13.6
- Strapi version: Strapi v3.0.0-beta.18.7
- Database: MongoDB 4.2.3 Enterprise (Atlas)
- Operating system: macOS Catalina 10.15.2

### PR DESCRIPTION
**Pull request by kubuntux**
#### Description of what you did:

Fix  #5266

### CODE REVIEW

**Comment by kubuntux** [comment]
I just did it, hope it will be merged. Thanks!

**Comment by lauriejim** [comment]
Yeah thank you for reporting the issue and fixing it
Really appreciate it!

**Comment by alexandrebodin** [comment]
@kubuntux Can you reset your yarn file ? it shouldn't change in your PR :)

**Comment by alexandrebodin** [comment]
Will just wait for @kubuntux to update the PR ;)

**Comment by kubuntux** [comment]
Ok done. :)

**Comment by kubuntux** [comment]
Sorry guys, I am really having a hard time passing DCO. This is my first time contributing using Git. So please bear with me.

**Comment by alexandrebodin** [comment]
@kubuntux I would recommend you create a new PR with only one commit ;) this will be easier to pass DCO :)

**Comment by kubuntux** [comment]
Ok thanks. Done.

#5346

**Pull request closed without merging**
