### PR TITLE
[WIP] Fix providers url to use proxy url

### PR DESCRIPTION
**Pull request by derrickmehaffy**
My PR is a:
🐛 Bug fix

Main update on the:
Plugin

The providers were hard coded to use http:// and the Strapi running IP/Port. If you used a proxy such as Nginx providers like facebook and discord will fail in production use (in many cases they work using localhost on development)

This PR is still in a work in progress as I don't know how to fix the grantConfig here:

```
    _.defaultsDeep(grantConfig, {
      server: {
        protocol: 'http',
        host: `${strapi.config.url}`
      }
    });
```

Due to it being hard coded for http

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@lauriejim or @Aurelsicoko when you get a moment can you take a look at this. I'm not sure how best to handle this as `strapi.config.url` already includes the protocol in it, IE `https://domain.com:443`

**Comment by derrickmehaffy** [comment]
As it stands currently if a user is using a proxy like Nginx/Apache for SSL they cannot use providers like Facebook or discord which -ONLY- allow connections over https in production. Realistically the grant protocol should be flipped based on if the proxy SSL flag is set and the `strapi.config.url` should be broken down into `https` & `://` & `domain.com` & `:` & `443`

Especially if you are using ports 80 and 443 there is no reason to include them.

**Comment by derrickmehaffy** [comment]
Related Error: https://github.com/strapi/strapi/issues/1861

**Comment by jrodriguesimg** [comment]
I tried just hard coding https so that facebook accepts the request_uri, but it will trigger another error down the line in the plugins/users-permissions/services/Providers.js. More specifically in the following lines:

```
const users = await strapi.query('user', 'users-permissions').find({
          where: {
            email: profile.email
          }
});
```

It will throw an object as error that is caught and passed to the reject function. The error object is empty so I have no idea for what might be the cause.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko @lauriejim when you get some time I could really use your help / thoughts on this.

**Comment by Aurelsicoko** [comment]
We could add a new option in the `./config/environments/**/server.json` file called `protocol`?

```json
{
  "protocol": "http",
  "host": "127.0.0.1",
  "port": 1337,
  "autoReload": {
    "enabled": true
  },
  "cron": {
    "enabled": false
  }
}
```

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I added a boolean toggle in my Proxy PR: https://github.com/strapi/strapi/pull/1813 that should be able to be used here.

If you are developing locally and using localhost then there is no need to add in another protocol option. And if you are using Strapi in production you are almost always going to be using some kind of proxy (Bad bad bad to run something like strapi as a root user, thus you can't use any port below 1024 on a linux system)

**Comment by lauriejim** [comment]
@derrickmehaffy so you can try something like that

```js
_.defaultsDeep(grantConfig, {
    server: {
        protocol: `http${(strapi.config.proxy.enabled && strapi.config.proxy.ssl) ? 's' : ''}`,
        host: `${strapi.config.url}`
    }
});
```

Based on the PR you link. Just test if proxy is enabled and if ssl is true, in this case use `https`

**Comment by derrickmehaffy** [comment]
@lauriejim that is what I was looking for, I'll take a look at this in a few hours.

**Comment by derrickmehaffy** [comment]
@lauriejim I can't quite figure out how to get this to work. PM me on Slack when you get in and have some free time please.

Current error is this:
```
TypeError: Cannot read property 'proxy' of undefined
    at connect (/opt/strapi/packages/strapi-plugin-users-permissions/controllers/Auth.js:153:110)
```

**Comment by lauriejim** [comment]
In your condition you not place proxy in the correct place.

**Comment by lauriejim** [comment]
Can you test and tell me if it work for you. What need to be done before merging this PR @derrickmehaffy ?

**Comment by derrickmehaffy** [comment]
Worked with Jim via slack, we fixed redirect problem as it was related to conflicting `login-react` example and strapi but all providers are now giving the following error:

`error=grant: missing session or misconfigured provider`

**Comment by derrickmehaffy** [comment]
Closing due to https://github.com/strapi/strapi/pull/2110 taking over

**Pull request closed without merging**
