### PR TITLE
Replace standard error message with descriptive message

### LINKED ISSUE #6598: Have clear error messages in tooltip
**Describe the bug**
While saving a new collection type, I faced an error. Let the user know about the error description in the tooltip provided

**Steps to reproduce the behavior**

1. Create a new collection type
2. Create a UID field of MaxLength greater than 500
3. Save the collection type
4. See error tooltip without any clue of what happened in background, 

As a dev, I thought it was an issue with my mongo atlas cluster, When checked the network logs, the concise error message indicating the root cause but was not shown in the tooltip

{"error":{"contentType.attributes.productId.maxLength":["contentType.attributes.productId.maxLength must be less than or equal to 256"]}}

**Expected behavior**
Let the user know in the tooltip mentioned about the error description rather than just letting user see a message "An error occoured"

**Screenshots**
image

**System**

- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version:  "strapi": "3.0.1"
- Database: mongo-atlas
- Operating system: osx mojave

### PR DESCRIPTION
**Pull request by diogotcorreia**
Closes #6598 

#### Description of what you did:

Added a new util method to `strapi-helper-plugin` that parses the error from a Strapi REST request and checks if there's any descriptive error message and uses that on the error notification. Otherwise, the default error message is used.

I've gone through most instances of `strapi.notification.error('notification.error');`, and I've replaced the ones that:
1. Are related to user input (e.g. POST and PUT requests)
2. Seem to have custom controllers/services that throw error messages depending on user input

Please tell me if there's something I've missed, I'll happily change it in this PR as well.

(some code borrowed from #7737)

### CODE REVIEW

**Comment by soupette** [comment]
@diogotcorreia can you fix the merge conflicts so we can review your PR?

Thanks a lot.

**Comment by diogotcorreia** [comment]
@soupette Done! 😄

**Comment by soupette** [comment]
Hello @diogotcorreia!

First of all, thanks a lot for your contribution! I have tested your PR, more specifically in the webhooks page in which I have change the schema so the `name` and the `url` fields are not required ones so I can submit a falsy form. Unfortunately your changes break the app as the error format is not the same as the one in the content manager for instance.

Until, we improve the error format in order to have a consistent one in the entire one we must write specific code in order to display the errors properly, in this way, I am going to close your PR. 

Please, feel free to open other PRs because improvements are more than welcomed!

**Comment by diogotcorreia** [comment]
@soupette 
What if I remove the code from the endpoints that don't use that same error format?
It'd still fix issue #6598, which was what I was going for.

**Comment by soupette** [comment]
@diogotcorreia sure you can move your displayErrors utils into the content type builder and use it only there, this way I could merge your PR.

Thanks a lot!

**Pull request closed without merging**
