### PR TITLE
[WIP] Fix multi lines in content type description

### PR DESCRIPTION
**Pull request by entwicklerfr**
My PR is a: 🐛 Bug fix

Main update on the: Admin

When a user is creating a new Content Type through The Admin/Content Type Builder he can set a description in a text area. If he sets a multilines text
1. No saving is possible. an error message is displayed "request.error.model.read"
2. If strapi is restarted it doesn't work due to an "SyntaxError: ~/api/MyHappyModel/models/MyHappyModel.settings.json: Unexpected token in JSON at position 152" exception.

The fix consists of updating two files in the strapi-plugin-content-manager

- ContentTypeBuilder.js
- helpers.js

In both create and update model methods, description is currently parsed to replace newline by space because the description has to be displayed as label in the Admin page (linkedIn Profile abtract behaviour).  The replacement is managed by an helper function.

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello @entwicklerfr ! Thank you for your PR.

With your code, when I insert a new line in the description, I save, then when I try to see my description I lost the multi lines.

The job to do it to not loose it.

**Comment by entwicklerfr** [comment]
@lauriejim , 

Thx for the feedbak. I misinterpreted the need.
I'll dive in code this week-end.
I'll let you know.

**Comment by entwicklerfr** [comment]
Hi @lauriejim,

I have had to open a new PR **#2159** instead of this one because of a mistake I made on my original forked repo.

I close this one.

**Comment by lauriejim** [comment]
Why you don't update your code ? Don't need to create a new PR each time.
We loose comments and feedback...

**Comment by entwicklerfr** [comment]
Hello,

I know it and I'm so sorry.
I simply crashed my ubuntu VM without possible recovery and, in the same time, removed my forked github strapi repository. 
So I recreated all my environments from scratch. 
I will have more caution next time.

**Pull request closed without merging**
