### PR TITLE
[Fix/i18n] Single type deletion and locale nav

### PR DESCRIPTION
**Pull request by jhoward1994**
### What does it do?

Fix https://github.com/strapi/strapi/issues/21294
Fix https://github.com/strapi/strapi/issues/21296

### Why is it needed?

- Fix for locale deletion in single types (for single types we should not require a documentId to proceed with the deletion as the CM url doesn't contain one)
- Fix to disable CM navigation to a locale you don't have permission for (you need the `canCreate` permission if the locale doesnt exist yet & `canRead` if it does)

DX-1612
DX-1613

### CODE REVIEW

**Comment by innerdvations** [comment]
LGTM! Can you add an e2e test for it?

**Comment by jhoward1994** [comment]
I have to go now but will add this test next https://github.com/strapi/strapi/blob/6819dcbd7ca367f785b9f33786b3190eec1c21dc/tests/e2e/tests/i18n/editview.spec.ts#L306-L308

**Comment by hanpaine** [comment]
QAed by @butcherZ ✅

**Review by innerdvations — APPROVED** [review]
LGTM!

**Pull request merged**
