### PR TITLE
feature: accept user-defined logger from opts

### PR DESCRIPTION
**Pull request by pixeleet**
I propose that Strapi accepts a custom logger implementation from outside, mainly for the reason that I'd like to define my own transports and controls for pino instead of the hardcoded behaviour from `strapi-utils`

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @pixeleet I like the idea but as @derrickmehaffy said we are going to need some documentation to be added :) Would you be willing to add it ?

**Comment by pixeleet** [comment]
Yeah, I'll take some time this weekend to make the PR. 
Should I just add a quick `logging.md` to `guides` for it?

**Comment by alexandrebodin** [comment]
Hi @pixeleet I would add it in the concepts @derrickmehaffy what do you think ?

**Comment by derrickmehaffy** [comment]
Yeah a deep dive in concepts might be best

**Comment by lauriejim** [comment]
@derrickmehaffy @alexandrebodin What about here - https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-start
There is some ENV documentation for the start.

**Comment by pixeleet** [comment]
The code part is done but the guide I wrote is absolute gibberish 😅 

Would you guys care to weigh in?

# Logging

## STRAPI_LOG environment variables and defaults

STRAPI_LOG_LEVEL=debug
STRAPI_LOG_TIMESTAMP=false
STRAPI_LOG_FORCE_COLOR=true
STRAPI_LOG_PRETTY_PRINT=true

## Production setup

STRAPI_LOG_LEVEL=info
STRAPI_LOG_PRETTY_PRINT=false

This will force `pino` the logger that `Strapi` uses under the hood, to push out JSON instead of pretty printed messages that can be collected and processed.

## Levels

> fatal, error, warn, info, debug, trace

Levels define what `level` the log message carries. Consider using `strapi.log` instead of `console.log` called with the appropriate level.

For example:
```js
module.exports = {
  find: async (ctx) => {
    const { name } = ctx.params.query
    if (!name) {
      strapi.log.error("Invalid query provided!")
      ctx.send(404)
    }
    strapi.log.debug({ name }, 'Looking for pet based on name')
    const pets = await strapi.query('pets').find({ name })
    strapi.log.info({ name, pets }, 'Found pets for query')
    ctx.send(pets)
  }
}
```

Given the `STRAPI_LOG_LEVEL=info` environment var you'd only see the last message.
While using default settings all messages will be pretty printed into the console.

## Child loggers

It's often useful to create a new logger, with some added information.
Creating a child logger is as easy as:
```js
const strapi.log.child({ customProp: 'customVal' })
```

## Bring your own logger

When creating a strapi instance you're free to provide your own logger implementation.
In case you'd like to configure transports, or other facilities for pino, here's how you can do that.

For more options check the pino [documentation](https://getpino.io/#/)

```js
const Strapi = require('strapi')
const pino = require('pino')
const logger = pino({ level: 'info' ... })
const strapi = Strapi({ logger })
strapi.start()
```

::: tip
When providing a logger implementation, make sure it is compatible with `pino`.
The best idea is to just use `pino` :)
:::

**Comment by derrickmehaffy** [comment]
I like the idea, when this was first purposed I also brought it up with some of the community provides to add the option to disable logging (though it was done via the middleware/plugin config files) I think it's good to decrease the logging in production as I myself when scaling in production, especially during rolling updates/restarts will end up spamming my remote log server with a bunch of unnecessary info.

**Comment by alexandrebodin** [comment]
Hi @pixeleet going to close this for inactivity :) Let us know if you eventaully can make the changes so we reopen the PR

**Comment by pixeleet** [comment]
Closing to submit a new more pristine PR with updated guide and examples.

**Pull request closed without merging**
