### PR TITLE
Trim spaces from string values on insert and update

### PR DESCRIPTION
**Pull request by websocket98765**
Fixes https://github.com/strapi/strapi/issues/3983 for Bookshelf.

#### Description of what you did:

Updates Bookshelf's to trim leading and trailing blank spaces from any string-type values during insert and update.

Confirmed working with Strapi beta16.6 and Sqlite.

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [x] SQLite

### CODE REVIEW

**Comment by veitbjarsch** [comment]
May create a function out of it to respect the DRY principle.

**Comment by alexandrebodin** [comment]
Hi @websocket98765, this kind of behaviour isn't something that should be put in the database layer. This will make it impossible to have heading or trailling space intentionnaly. If we want to make sure the inputs are trimmed it should be done on an other layer.

**Comment by derrickmehaffy** [comment]
Preferably at a validation layer that could be changed with something like regex

**Comment by alexandrebodin** [comment]
> Preferably at a validation layer that could be changed with something like regex

Yes we could just do it in the front-end in case you want to put some spaces on purpose when calling the api. I don't see the usecase but I don't see why we should prevent it anyway

**Comment by alexandrebodin** [comment]
I'm closing this PR as discussed above.  Feel free to open a new PR to make the update in the front-end

**Comment by websocket98765** [comment]
I've now created middleware which trims all string submissions on the server. This will better suit my needs than client side trimming because I won't have to remember to check that strings are trimmed on all client inputs and it enforces the desired consistency for all string inputs on Strapi.

**Pull request closed without merging**
