### PR TITLE
Add DateTime support for GraphQL plugin

### PR DESCRIPTION
**Pull request by johannpinson**
My PR is a:
💥 Breaking change

Main update on the:
Plugin

To improve the date field for GraphQL, this PR introduce the concept of DateTime scalar instead of String type.
It use the npm package [graphql-type-datetime](https://www.npmjs.com/package/graphql-type-datetime) (developed specially for the occasion 👍 )

### CODE REVIEW

**Comment by johannpinson** [comment]
capture d ecran 2018-06-19 a 10 56 21

This is a preview of the field "rendering".
`createdAt` and `updatedAt` have the new format, and the field `releaseWW` the old one.
(with the PR, all date field will have the ISO format, this screenshot is just to show the difference)

**Comment by derrickmehaffy** [comment]
Nice job @johanbaath

**Comment by kamalbennani** [comment]
Your package is not correctly configured, here is what needs to be changed:
1- Correctly separate between devDependencies and dependencies (Please move moment and Graphql to dependencies)
2- Point your main file to `lib/index.js` rather than `./index.js`, another solution is to build to the root folder.
I have a small question BTW, how did you check that it's working? did you use `npm link` for that?

**Comment by johannpinson** [comment]
@kamalbennani 
Thanks for the report, I push the update.

For testing, I made it manually, directly with the `npm install` (what is happening during the `strapi install graphql`) with a new project, and also with a existing project to be sure that the update will works.
After, the build process and npm organization is copied exactly on the `graphql-type-json` which is working well.

**Comment by Aurelsicoko** [comment]
@johannpinson How these changes support the different date format? Currently, we can have `date`, `time`, `datetime`, `timestamp` in our models (see https://strapi.io/documentation/guides/models.html#define-the-attributes).

**Comment by johannpinson** [comment]
@Aurelsicoko Ouch, well seen...
I just test it with the default datetime available from the content type builder, I test it right now!

**Comment by johannpinson** [comment]
is related with https://github.com/strapi/strapi/pull/1437

**Comment by Aurelsicoko** [comment]
Awesome! I posted a comment in the other PR

**Comment by johannpinson** [comment]
@Aurelsicoko 
FYI: I didn't add the `time` detection for the format because it a type which we need to talk about.
Actually, time/date/datetime/timestamp are (or were) all considered as a `datetime` (TIMESTAMP for SQL / ISODate for Mongo).
If MySQL or PostgreSQL can separate the date and the time, it's not possible with Mongo.

Two options:
1. remove the `time` and `date` because they can be use separately
2. keep the 4 formats and add specific behavior in the admin when it's a SQL database

**Comment by lauriejim** [comment]
@johannpinson @Aurelsicoko I think we have to chose option 2.
It let us handle more cases.

**Comment by lauriejim** [comment]
I would like to merge https://github.com/strapi/strapi/pull/1439 before this one.
Have a clear choice about date types.

**Comment by johannpinson** [comment]
@lauriejim 
PR updated about what we talk => manage the actual four type around `date`.

**Comment by lauriejim** [comment]
I remove this PR from the next release because or the other PR related to Date format.

**Comment by johannpinson** [comment]
@lauriejim 
In fact, this PR is related with the other one (in the mind), but not depend in the code 😉

**Comment by jp-gouigoux** [comment]
Hello. I am using Strapi v3.0.0-alpha.25.2, and after many attempts with different formats, I am still stuck with using dates in the GraphQL plugin. When using the Playground, I try sending the following :

mutation {
  createAnimal(input: {
    data: {
      nom : "Bidouille",
      naissance : "2000-02-16T00:00:00.000Z"
    }
  }) {animal {nom naissance}}
}

This results in :

"message": "Expected type DateTime, found \"2000-02-16T00:00:00.000Z\"; value is not defined",

I have tried some other formats, like "2000-01-16" or "2000 02 16". I even tried a structure as I have seen in some documentation, with the following :

      naissance : {
        value : "2000-02-16T00:00:00.000Z"
      }

Still no success. I have created the Content Type using Strapi GUI, and the proposed "Date" format. I have no problem in adding an entry with a date from the Strapi GUI. I tried catching the network frames there and using the same data (from formdata) and using it into GraphQL Playground, but again to no success.

Thanks in advance for any help !

**Comment by derrickmehaffy** [comment]
@jp-gouigoux If you are on a bookshelf DB (SQLite, Postgres, or MySQL) you need to send the format like `YYYY-MM-DD HH:MM:SS`

**Comment by jp-gouigoux** [comment]
Thanks for helping ! I still have the same error message with this format. I am using a MongoDB backend, as proposed in the Docker Compose I have used to run Strapi ; maybe this is the cause of the problem and another format is needed, but I cannot find it, nor get any documented working example...

**Comment by fouss** [comment]
@jp-gouigoux I have the same problem, did you find a solution ?

**Comment by jp-gouigoux** [comment]
@fouss Nope... And I have stopped trying, after many different attempts. Maybe @derrickmehaffy would have another proposal in the case of MongoDB ?

**Pull request merged**
