### PR TITLE
Support Node 15 and 16

### PR DESCRIPTION
**Pull request by dzcpy**
### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hello, this PR is missing a valid description explaining it's goal. THis change is not going to make strapi support node 16. Closing until more details are provided

**Comment by dzcpy** [comment]
Currently strapi cli does not support either node 15 or 16. So is there any alternatives without using nvm?

**Comment by alexandrebodin** [comment]
Strapi doesn't support node 16 right now so you need to use node 14 which is the current lts. We plan to support node 16 once it is in LTS which will be  the 2021-10-26 :)

**Comment by derrickmehaffy** [comment]
https://nodejs.org/en/about/releases/

image

We never support "Odd" versions of node as they do not go into an LTS and are development builds only. The versions of node we support are listed in our documentation: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment.html#general-guidelines

image

**Pull request closed without merging**
