### PR TITLE
Adding support for more Date, Time, Datetime, and Timestamp options

### LINKED ISSUE #2497: Split the frontend date picker into 3 new types; date, datetime, and time
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Using the following react frontend parts I think we can easily split the current date field option into these three:

- date (2018/12/30) => https://www.npmjs.com/package/react-date-picker
- datetime (2018/12/30 01:02:03) => https://www.npmjs.com/package/react-datetime-picker
- time (01:02:03) => https://www.npmjs.com/package/react-time-picker

This FR falls in line with the current focus on bookshelf date functions: https://github.com/strapi/strapi/issues/2495

### PR DESCRIPTION
**Pull request by derrickmehaffy**
Adding the following options (at the moment only backend support):

- Date
- Time
- Datetime
- Timestamp (with automated values for create / update)

What is done so far:

- [x] Adding all options to Mongoose
- [x] Adding all options to Bookshelf
- [ ] Testing Bookshelf DBs
- [ ] ~~Testing Mongo~~ Not needed as mongo doesn't support time only
- [ ] ~~Add options to AdminUI~~ Out of PR scope until beta PR is merged

#### My PR is a:
- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #2497
- [ ] 💅 Enhancement
- [x] 🚀 New feature

#### Main update on the:
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:
- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@soupette Can I get your thoughts on adding these to the AdminUI?

I was thinking something along the lines of how the Integer/Decimal/Float type is setup with a selection of different types. Also I will likely need help working on the adminUI part of this, I can make an attempt (and plan to) but there is a good chance my skills aren't quite high enough in react to finish that part of it.

**Comment by lauriejim** [comment]
@soupette is super busy actually. 
I will try to point him this point during a planning tasks meeting.

**Comment by derrickmehaffy** [comment]
@lauriejim I spoke with him on the slack a few days ago. Backend support should be possible but frontend support will likely come in the beta since he is replacing the date picker.

I made him aware of this PR. In the mean time we can test the backend to make sure it works okay

**Comment by lauriejim** [comment]
Since we will not work on the front ent stuff in this PR, doesn't it still in WIP status ?

**Comment by derrickmehaffy** [comment]
@lauriejim the backend parts need to be tested, for now we can forgo the frontend until the beta stuff is ready

**Comment by derrickmehaffy** [comment]
Closing as all of this is subject to change in the beta

**Comment by iRoachie** [comment]
Any update on this?

**Comment by lauriejim** [comment]
Hi! Not on the pipe right now. And I can't give you a date.

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/issues/2497

@soupette is in the process of adding the buffetjs.io stuff once that's added it won't take much to add in the backend support (most of it is already there just isn't used)

**Pull request closed without merging**
