### PR TITLE
fix #15862 (core upload): add missing FR translations

### LINKED ISSUE #15862: Missing fr translations
### Required System information

- Node.js version: v16.18.0
- NPM version: 8.19.2
- Strapi version: 4.6.1
- Database: MySQL
- Operating system: Linux (Ubuntu)

### Describe the bug

I don't know if there is a better place for that kind of remarks but I'm seeing missing translations in the French version of Strapi, go to admin and them:

In media library, upper buttons are not translated:
image

In media library, Folders and Assets sub titles:
image

In content, relation field is not translated:
image

### Expected behavior

Those texts should be in French.

### Additional context

I would be happy to help translate if there is a way to do it, please let me know.

### PR DESCRIPTION
**Pull request by edlefebvre**
### What does it do?
Add missing FR translations for media library

### Why is it needed?

Strapi French version is missing 62 translations.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/15862

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @edlefebvre sadly out CLA bot is detecting that you commited with 2 different emails and isn't happy about it :) Could you update your branch so we can review/approve it ? thanks!

**Comment by edlefebvre** [comment]
@alexandrebodin should I close this PR and make a second one? I don't know how to fix the problem of the two emails here (one doesn't exist anymore). Thanks

**Comment by alexandrebodin** [comment]
You can either rewrite the git history or rebase it into one commit  that might be simpler :)

**Comment by edlefebvre** [comment]
@alexandrebodin sorry I can't seem to make it work, I made a new PR : https://github.com/strapi/strapi/pull/16156

**Pull request closed without merging**
