### PR TITLE
Allow empty objects in validator

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

Removes the empty object query validator

### Why is it needed?

Empty objects are not valid inputs, but by not allowing them it makes user queries much more complex to write. For example, if you see the issue https://github.com/strapi/strapi/issues/17995 

NOTE: This is an issue where we're caught between a rock and a hard place. 
On one side, it is easier for users to catch bugs and security issues if invalid parameters throw an error. 
On the other, in cases like this it requires their queries to be written dynamically with much more complexity.
I think this PR is the right balance, because it will still throw errors when something completely invalid is sent, but if nothing is sent at all, it should still be easy for the user to catch their mistake even without an error.

### How to test it?

Test both graphql and the rest API. Empty objects in parameters are now permitted, even though they are filtered out.

### Related issue(s)/PR(s)

Alternate option to https://github.com/strapi/strapi/pull/18168

Fixes https://github.com/strapi/strapi/issues/17995

### CODE REVIEW

**Review by Convly — COMMENTED** [review]
It could be nice to have also a REST API test. Do you think you could add it here?
(otherwise, LGTM as discussed internally)

**Comment by innerdvations** [comment]
Yeah, absolutely. If this is the approach we want to go with, I will add several more tests before merging

**Review by Bassel17 — APPROVED** [review]
LGTM

**Review by Convly — APPROVED** [review]

**Comment by Convly** [comment]
Tested on a local project, working fine on my side

**Comment by galago** [comment]
After upgrading I still have the issue. Am I doing something wrong? 

this is my query and variables
```

query SiteInfo($filters: ComponentSharedContentBlocksFiltersInput) {
  siteInfo {
    data {
      attributes {
        name
        contentBlocks(filters: $filters) {
          reference
          content
        }
        locale
      }
    }
  }
}

Variables:
{
  "filters": {
    "reference": {
      "eq": "testimonialsBody"
    }
  }
}

```


I still receive the error and no data after filtering

{
  "data": {
    "siteInfo": {
      "data": {
        "attributes": {
          "name": "My Site",
          "contentBlocks": null,
          "locale": "en"
        }
      }
    }
  },
  "errors": [
    "Invalid parameter reference"
  ]
}

**Comment by innerdvations** [comment]
That error suggests there is not n attribute called "reference" on your contentBlock type. If you do have it there, could you share a partial schema so I can try to reproduce? Thanks!

**Comment by galago** [comment]
yes of course it has a reference field, that's the one I'm trying to filter. It's a string and it's a mandatory field. 


image

**Comment by galago** [comment]
any updates?

**Comment by innerdvations** [comment]
https://github.com/strapi/strapi/pull/18647

**Pull request merged**
