### PR TITLE
fix: listLocales Returning 403 for Authenticated Users

### PR DESCRIPTION
**Pull request by gitstart**
fixes https://github.com/strapi/strapi/issues/13653

### What does it do?
Support getting locales with read-only auth tokens.

### Why is it needed?
Prevent showing 403 when a user with read-only token attempts to query locales.

### How to test it?

-  Add a api token for just read only  
-  make and api request to http://localhost:1337/api/i18n/locales with header authorization with api token 
-  it will response all the locales in the strapi 

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/13653

### Demo

https://user-images.githubusercontent.com/45232708/205666996-450ac6c5-cfd5-450d-9398-e53aa1ea719c.mov

---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
Hi, @Convly @derrickmehaffy could you please take a look at this PR.

**Review by derrickmehaffy — DISMISSED** [review]
LGTM

**Review by Convly — CHANGES_REQUESTED** [review]
Removing the `listLocales` route is a breaking change.

If we want to add the possibility to query `find` & `findOne`, we should add them next to the `listLocales`

**Comment by gitstart** [comment]
Thanks @Convly for pointing out the issue. 
I've made the necessary changes in the PR to address the breaking change. 
What are your thoughts on the current state of the PR?

**Pull request closed without merging**
