### PR TITLE
Introduce reload script execution

### PR DESCRIPTION
**Pull request by valoricDe**
Hi there. I would like to execute a script whenever strapi restarts or reloads.

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi why don't you use the bootstrap.js file to run on startup ? Can you explain your usecase ?

**Comment by valoricDe** [comment]
Hi there. As far as I understand the bootstrap.js file is only called when the strapi instance is started. But I wan't to execute a script (git) everytime the files changed / the server is restarted. I could use nodemon/chokidar to also watch all files but if there is also a chokidar watching all files why not using it :)

**Comment by alexandrebodin** [comment]
the bootstrap.js file is run on every start so on each change the app restarts and it will be executed. does that work for you ?

**Comment by valoricDe** [comment]
Oh great

**Pull request closed without merging**
