### PR TITLE
Fix full text search on postgres uppercased attributes chars

### LINKED ISSUE #4025: The relation autocomplete doesn't work well
**Describe the bug**

The relation autocomplete doesn't work well.

**Steps to reproduce the behavior**

Use any relation autocomplete.

**Screenshots**

Sep-17-2019 09-21-25

**System**
- Node.js version: v10.16.0
- NPM version: v6.11.3
- Strapi version: v3.0.0-beta.16.3
- Database: MongoDB
- Operating system: macOS

### PR DESCRIPTION
**Pull request by JoshTheWanderer**
#### Description of what you did:

A small fix to get full-text search working in PostgreSQL.

PostgreSQL treats single-quoted column names as text values, and unquoted column names get transformed to lower case by default. Strapi capitalises column names (except for relations), and so column names need to be double-quoted in order for full-text searching to work.

This is a similar issue to https://github.com/strapi/strapi/issues/4025 but specific to PostgreSQL databases.

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [x] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [x] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @JoshTheWanderer can you provide an example of a working and not working query to run ? 
I strapi doesn't capitalize the attribute names on the serveur side it uses the attribute name that is in the Model.settings.json file. it only capitalizes in the front end.

**Comment by JoshTheWanderer** [comment]
Hi @alexandrebodin I'll put together an example application tomorrow for you, but we are seeing attribute names being capitalised in the `Model.settings.json` files,  which is translating to capitalised column names in PostgreSQL (and resulting in this issue being seen).

An example from one of our setting files:

```
"attributes": {
    "Title": {
      "required": true,
      "type": "string"
    },
    "Slug": {
      "unique": true,
      "required": true,
      "type": "string"
    },
    "Content": {
      "required": true,
      "type": "richtext"
    }
}
```

And the resulting column definitions:

image

This is on v3.0.0-beta.16.6 if that helps.

**Comment by alexandrebodin** [comment]
Your column name take the name you set in your file. we do not capitalize those names by default. there were created with capitalize names in the interface ;)

In any case thanks for the info I finally see the point of the PR ;) I'm going to test it then merge if it looks alright !

**Comment by JoshTheWanderer** [comment]
Ah, that makes a lot of sense! I didn't create any of the content types, so I missed that entirely. Thanks for taking the time to look into this.

**Pull request merged**
