### PR TITLE
Enable GraphQL Subscriptions

### PR DESCRIPTION
**Pull request by jbeuckm**
#### Description:
Compile 'subscription' resolvers and type definitions into the graphql schema. Add subscription handlers to the http server.

Example `schema.graphql` from an api or plugin:
```javascript
const { PubSub } = require('apollo-server');

let count = 0
const pubsub = new PubSub();

setInterval(() =>
  pubsub.publish('TICK_HAPPENED', {
    tickHappened: { count: count++ }
  }), 1000);

module.exports = {
  definition: `
    type Tick {
      count: Int!
    }
  `,
  subscription: `
    tickHappened: Tick
  `,
  resolver: {
    Subscription: {
      tickHappened: {
        subscribe: async () => pubsub.asyncIterator('TICK_HAPPENED')
      }
    }
  }
};
```
This enables a `subscription` request that can be used from the graphql playground.

#### My PR is a:
- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix #issueNumber
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:
- [ ] Admin
- [ ] Documentation
- [x] Framework
- [ ] Plugin

#### Manual testing done on the following databases:
- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@jbeuckm can you please rebase off the current master and test this? I attempted to test but it seems there is a syntax error somewhere:

```
[2019-04-10T12:27:13.076Z] debug ⛔️ Server wasn't able to start properly.
[2019-04-10T12:27:13.078Z] error Syntax Error: Expected Name, found }
{ GraphQLError: Syntax Error: Expected Name, found }
    at syntaxError (/opt/strapi/packages/strapi-plugin-graphql/node_modules/graphql/error/syntaxError.js:24:10)
    at expectToken (/opt/strapi/packages/strapi-plugin-graphql/node_modules/graphql/language/parser.js:1433:32)
    at parseName (/opt/strapi/packages/strapi-plugin-graphql/node_modules/graphql/language/parser.js:98:15)
    at parseFieldDefinition (/opt/strapi/packages/strapi-plugin-graphql/node_modules/graphql/language/parser.js:870:14)
    at many (/opt/strapi/packages/strapi-plugin-graphql/node_modules/graphql/language/parser.js:1521:16)
    at parseFieldsDefinition (/opt/strapi/packages/strapi-plugin-graphql/node_modules/graphql/language/parser.js:859:50)
    at parseObjectTypeDefinition (/opt/strapi/packages/strapi-plugin-graphql/node_modules/graphql/language/parser.js:813:16)
    at parseTypeSystemDefinition (/opt/strapi/packages/strapi-plugin-graphql/node_modules/graphql/language/parser.js:711:16)
    at parseDefinition (/opt/strapi/packages/strapi-plugin-graphql/node_modules/graphql/language/parser.js:144:16)
    at many (/opt/strapi/packages/strapi-plugin-graphql/node_modules/graphql/language/parser.js:1524:16)
    at parseDocument (/opt/strapi/packages/strapi-plugin-graphql/node_modules/graphql/language/parser.js:115:18)
    at Object.parse (/opt/strapi/packages/strapi-plugin-graphql/node_modules/graphql/language/parser.js:50:10)
    at Object.buildSchemaFromTypeDefinitions (/opt/strapi/packages/strapi-plugin-graphql/node_modules/apollo-server-koa/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:19:33)
    at makeExecutableSchema (/opt/strapi/packages/strapi-plugin-graphql/node_modules/apollo-server-koa/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.generateSchema (/opt/strapi/packages/strapi-plugin-graphql/services/Schema.js:255:20)
    at Function.initialize (/opt/strapi/packages/strapi-plugin-graphql/hooks/graphql/index.js:154:78)
    at /opt/strapi/packages/strapi/lib/hooks/index.js:52:31
    at after (/opt/strapi/packages/strapi/lib/hooks/index.js:153:39)
    at /opt/strapi/packages/strapi/node_modules/lodash/lodash.js:9999:23
    at Strapi.once (/opt/strapi/packages/strapi/lib/hooks/index.js:164:17)
    at Object.onceWrapper (events.js:277:13)
    at Strapi.emit (events.js:189:13)
    at Strapi.EventEmitter.emit (domain.js:441:20)
    at onFinish (/opt/strapi/packages/strapi/lib/hooks/index.js:44:12)
    at Promise.all.then (/opt/strapi/packages/strapi-hook-bookshelf/lib/index.js:1197:55)
  message: 'Syntax Error: Expected Name, found }',
  locations: [ { line: 187, column: 26 } ] }
```

**Comment by derrickmehaffy** [comment]
(Also side note, I believe the goal is to enable subscriptions on all endpoints and define permissions maybe for them)

**Comment by jbeuckm** [comment]
@derrickmehaffy I rebased and tested my example locally again. What did you do to produce the error exactly?

Also, by "the goal" do you mean there is already a roadmap entry to make subscriptions?

**Comment by derrickmehaffy** [comment]
@jbeuckm I merged the PR into the master branch on my fork, Hence why I mentioned you may want to rebase as lots of PRs have been merged over the past few days gearing up for a final release before the Beta stuff starts.

There is no detailed version of the roadmap for GraphQL subs but it is on the plan:
https://portal.productboard.com/strapi/c/45-graphql-subscriptions
https://github.com/strapi/strapi/issues/1877

Typically with feature adds like this the end goal of strapi is to allow users to function at a basic level without writing a single line of code to start. Thus IMO I think subs should be enabled on all endpoints (and the code to do so) and maybe allow them to turned on/off based on a permission setting. I don't know what @Aurelsicoko had in mind when was looking at them a few months ago, maybe he can explain some of his thoughts.

**Comment by derrickmehaffy** [comment]
Side note though it seems I'm not the only one hitting the same issue as the TravisCI testing on all the database types are also failing due to a similar issue: https://travis-ci.org/strapi/strapi/jobs/518463856

**Comment by Aurelsicoko** [comment]
I'm totally okay to natively support subscriptions on all queries. @alexandrebodin what are your thoughts on the implementation made in this PR?

**Comment by jbeuckm** [comment]
Something that confused me about the existing GraphQL plugin implementation:

When I add a new content type with ContentTypeBuilder, a new folder is generated in api/ with the REST interface for the content type. But the GraphQL plugin live-generates some simple CRUD queries and mutations from the Model description. Why doesn't the GraphQL plugin generate a ´schema.graphql´ file with the content type's GraphQL interface in the api/contentType folder ?

**Comment by Aurelsicoko** [comment]
@jbeuckm when we started to develop Strapi, GraphQL wasn't existing at all. Then, we wanted to have the simplest implementation. We called that feature the Shadow CRUD. For the beta, the REST API is going to use the same Shadow CRUD than GraphQL. The Shadow CRUD is going to be an internal API.

It means that the `routes.json`, 'controller.js` and  `service.js` files generated in the `/api` folder are going to be empty. There will have only comments inside these files which will be useful as documentation.

**Comment by fakedob** [comment]
Checkout my PR #3165 with this feature already implemented 👌

**Comment by lauriejim** [comment]
Can you replace your double quote `"` lint by simple quote `'`.
It will let your PR more readable.

**Comment by lauriejim** [comment]
There is no update about this topic.
I close this PR but the topic is really interesting!

**Pull request closed without merging**
