### PR TITLE
Heroku Error: self signed certificate SSL fix

### LINKED ISSUE #5696: Strapi does not work with latest version of the `pg` package
**Describe the bug**
Latest version of the `pg` package (`8.0.0`) is not compatible with strapi.

**Steps to reproduce the behavior**
1. Install the `pg` package like described here https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#_5-install-the-pg-node-module
2. Start the server with the following config.
```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "postgres",
        "host": "${process.env.DATABASE_HOST}",
        "port": "${process.env.DATABASE_PORT}",
        "database": "${process.env.DATABASE_NAME}",
        "username": "${process.env.DATABASE_USERNAME}",
        "password": "${process.env.DATABASE_PASSWORD}",
        "ssl": true
      },
      "options": {}
    }
  }
}
```
3. The server fails to start with the following error.
```
➜  project-folder git:(master) ✗ yarn develop 
yarn run v1.22.0
$ strapi develop
[2020-04-02T22:06:49.564Z] error Impossible to register the 'model-name' model.
[2020-04-02T22:06:49.568Z] error Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket._finishInit (_tls_wrap.js:916:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
When I start the server in production mode, the connection to the DB is made.

**How to fix**
Install the last `7.x.x` version instead.
```bash
yarn add pg@^7.18.2
```

**Note**
The `7.18.2` version of `pg` shows a deprecation warning.
```
(node:3130) DeprecationWarning: Implicit disabling of certificate verification is deprecated and will be removed in pg 8. Specify `rejectUnauthorized: true` to require a valid CA or `rejectUnauthorized: false` to explicitly opt out of MITM protection.
```

**System**
- Node.js version: v12.16.1 LTS
- Strapi version: 3.0.0-beta.19.3
- Database: PGSQL
- Operating system: Ubuntu WSL on windows/heroku dyno

### PR DESCRIPTION
**Pull request by tsoisauce**
Fix Heroku Error: self-signed certificate issue for deploying Strapi to Heroku

#### Description of what you did:
Fix Heroku Error: self-signed certificate issue for deploying Strapi to Heroku
Set `rejectUnauthorized ` to `false` to avoid SSL issues when deploying to Heroku

**Edited by:** @derrickmehaffy 

Fix #5696

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Alex I think will solve future problems relating to new versions of PG but we should document this in the next migration guide.

**Comment by brandonaaskov** [comment]
Please merge this as soon as possible. I lost some dev time to this one, but I'm glad to see there's already a PR to fix it.

**Comment by alexandrebodin** [comment]
@derrickmehaffy Does that break older versions though ? 

@tsoisauce Can you fix the DCO check :)

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Does that break older versions though ? 
> 
> @tsoisauce Can you fix the DCO check :)

It's related to the pg package, so upstream from us. It shouldn't mess with older versions

**Comment by alexandrebodin** [comment]
@tsoisauce Can you make this PR on top of the documentation branch instead of master so we can release it earlier ?

**Comment by tsoisauce** [comment]
closing to update on documentation branch

**Pull request closed without merging**
