### PR TITLE
Add reddit auth provider

### PR DESCRIPTION
**Pull request by Zeranoe**
### What does it do?

Added support for a reddit provider.

### Why is it needed?

There currently is no reddit provider.

### CODE REVIEW

**Review by derrickmehaffy — CHANGES_REQUESTED** [review]
Documentation/example will need to be added into: https://github.com/strapi/strapi-examples/tree/master/login-react before this can be accepted.

**Comment by Zeranoe** [comment]
> Documentation/example will need to be added into: https://github.com/strapi/strapi-examples/tree/master/login-react before this can be accepted.

PR open for the example: https://github.com/strapi/strapi-examples/pull/172

This PR has been updated with documentation.

**Comment by derrickmehaffy** [comment]
> > Documentation/example will need to be added into: https://github.com/strapi/strapi-examples/tree/master/login-react before this can be accepted.
> 
> PR open for the example: [strapi/strapi-examples#172](https://github.com/strapi/strapi-examples/pull/172)
> 
> This PR has been updated with documentation.

I saw, thank you ^_^

**Comment by Zeranoe** [comment]
Is there an ETA on when this will be merged?

**Comment by alexandrebodin** [comment]
@derrickmehaffy not sure some docs are required but if you can add some in our doc repo  @Zeranoe that would be awesome 💯

**Review by alexandrebodin — APPROVED** [review]
Works like a charm. I'll go ahead and merge it.

**Comment by derrickmehaffy** [comment]
Yup np, we will get some docs for it.

**Comment by Zeranoe** [comment]
> @derrickmehaffy not sure some docs are required but if you can add some in our doc repo @Zeranoe that would be awesome 💯

I've already opened a PR for the docs: https://github.com/strapi/documentation/pull/66

**Comment by derrickmehaffy** [comment]
Docs PR merged, I'm not a maintainer for the strapi-examples @petersg83 can you take a look?

**Comment by alexandrebodin** [comment]
We don't really maintain the strapi-examples repo anymore & it is largely outdated. The doc is more than enough :)

**Comment by derrickmehaffy** [comment]
This pull request has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/new-release-strapi-v3-4-5/2446/1

**Pull request merged**
