### PR TITLE
MigrationQA/ Ellipsis in CM LV table

### PR DESCRIPTION
**Pull request by ronronscelestes**
## What

Added ellipsis to text in CM LV

## Demo 

Capture d’écran 2021-09-21 à 16 17 33

### CODE REVIEW

**Comment by gu-stav** [comment]
Apologies for a comment from the sideline: it has been mentioned before that many strapi users struggle with cut-off text in various places.

I believe content is the main thing the table needs to display and it would be nice if the layout can do it's best to show as much as possible. In the case of the screenshot it could be possible that only some cut-off words of that field at the end make a difference and therefore it would be helpful to be able to distinguish them.

In my opinion there would be space to display e.g. a second line and let the text wrap naturally. Of course this doesn't work unlimited but at least showing 255 characters (for short text fields) would be nice.

Really looking forward to the new UI.

**Comment by mfrachet** [comment]
Thanks Gustav for the kind word and you're interest in the project ❤️ . We've shared the information internally and will try to challenge the things with the team 😊

**Comment by maevalienard** [comment]
@gu-stav Hi Gustav, thanks for your message. I have one question for you: Why specifically 255 characters? :)

**Comment by gu-stav** [comment]
@maevalienard I believe the character limit for the short text field is 255 characters (which might be a constraint in some databases), but I might be wrong.

**Review by soupette — APPROVED** [review]
LGTM

**Pull request merged**
