### PR TITLE
Update @koa/router to 12.0.1

### PR DESCRIPTION
**Pull request by smorimoto**
### What does it do?

Update @koa/router to 12.0.1.

### Why is it needed?

See https://github.com/koajs/router/pull/173.

### How to test it?

CI.

### Related issue(s)/PR(s)

None.

### CODE REVIEW

**Comment by smorimoto** [comment]
We have not encountered any regression issues with 11 because we were on 10, but it's not a bad change to reduce the confusion for users caused by the logs that come up during installation. (At least I had to jump around various repositories to confirm this...)

**Comment by derrickmehaffy** [comment]
This will need to be tested heavily for breaking changes, especially for complex community plugins that inject additional logic.

**Comment by smorimoto** [comment]
I think you are right indeed, although 10 to 11 is mainly just dropping some node versions and 11 to 12 doesn't seem to have any major changes that might impact us: https://github.com/koajs/router/releases

**Comment by alexandrebodin** [comment]
Hi, Considering our focus on v5 we will do version upgrades and dependency changes only there to keep our current dependencies stable and avoid risks of Breaking v4 in the upcomings months :)

Thank you for contributing still!

**Pull request closed without merging**
