### PR TITLE
Update Sentry to 7.53.1

### PR DESCRIPTION
**Pull request by garytube**
### What does it do?

Enables new Sentry features!
Like Cronjob Monitoring

### Why is it needed?

Outdated SDK

### How to test it?

Install and Profit

### CODE REVIEW

**Comment by gu-stav** [comment]
@garytube Thanks for this PR. Could you please resolve the conflicts and update the lockfile by running `yarn install` in the monorepo root>?

**Comment by GregorSondermeier** [comment]
Would love for this to go forward. The currently used version 6.19.7 is now more than a year old. Latest at the point of writing this comment is [7.55.2](https://www.npmjs.com/package/@sentry/node/v/7.55.2).

**Review by remidej — CHANGES_REQUESTED** [review]
Hello! There are a few things needed to be able to merge this, as mentioned by others:

- `@sentry/node` should also be updated in `packages/core/admin`
- the lockfile should be updated (`yarn install` at the root of the repo)
- to avoid a breaking change, a small mapping of old to new Sentry options needs to be done (see [my comment](https://github.com/strapi/strapi/pull/16274#pullrequestreview-1391759787) on #16274)

**Comment by remidej** [comment]
Closing this as it's not clear whether the changes are going to be addressed, but I'd be happy to reopen if needed

**Pull request closed without merging**
