### PR TITLE
Add populate option to the fetch user service

### PR DESCRIPTION
**Pull request by abdonrd**
#### Description of what you did:

Add populate option to the fetch user service

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [x] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi, can you give some context on why you need this ?

**Comment by abdonrd** [comment]
While I was testing #4775, I realized that this option was missing.
And that it is in `fetchAll` and in [the other models](https://strapi.io/documentation/3.0.0-beta.x/concepts/services.html#core-services).

**Comment by derrickmehaffy** [comment]
(seems the naming there is wrong also, shouldn't that service just be called find?)

Though you are right @abdonrd it was missing

**Comment by alexandrebodin** [comment]
I'm going to merge it for convenience but this service isn't a core service generated so the functions and options aren't meant to be the same as the ones in the doc. It is more of an internal service for the plugin itself.

We will be refactoring this plugin one day to have documented services etc ;)

**Pull request merged**
