### PR TITLE
Fix #8796 - fix relation typo in fr

### LINKED ISSUE #8796: French wording needs to be checked and clean (extra space) when adding a relational field to a CT in the CTB
### Describe the bug

There is an extra space in the French wording in the modal to add a single unilateral relation in the CTB. But I also wonder if the wording is actually correct: for the 2 first relationship types we use "[CT1] a un [CT2]".

See video: https://www.loom.com/share/95e8b07f2dff4dc3801624dd9d6bafc4

### Steps to reproduce the behavior

1. In dev env, Go to the CTB
2. Put the Admin in French
3. Open a CT
4. Add a field, a relation
5. Click on the 2 first types of relations and see error

### Expected behavior

Regarding the extra space in the first relationship type: No extra space
Regarding the wording: See the comment below (cc @maevalienard )

### System
- Strapi version: 3.3

### PR DESCRIPTION
**Pull request by croatian91**
fix french translation in content type builder plugin

### CODE REVIEW

**Comment by croatian91** [comment]
After:

Screenshot 2020-12-16 at 03 02 47
Screenshot 2020-12-16 at 03 02 55
Screenshot 2020-12-16 at 03 03 05

**Comment by croatian91** [comment]
@soupette up

**Review by maevalienard — COMMENTED** [review]
Looks good to me :) 
Thank you for fixing it!

**Review by soupette — APPROVED** [review]
LGTM

**Pull request merged**
