### PR TITLE
[Fix]: Support avif and heif image formats in upload plugin

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?

Support avif and heif formats in upload plugin. Specially avif is commonly used in web dev because of the compression rate it gives.

### Why is it needed?

Fixes https://github.com/strapi/strapi/issues/14857

### How to test it?

Upload [avif image ](https://libre-software.net/wp-content/uploads/AVIF/AVIF%20test%20file%20-%20Your%20browser%20%28software%29%20supports%20AVIF%20%28Quality%2025%29.avif) . 

And you should see the dimensions of the image.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/14857

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
> I was afraid sharp would not work with Avif & Heif formats in Apple Silicon ([lovell/sharp#2289 (comment)](https://github.com/lovell/sharp/issues/2289#issuecomment-751485477)) But seems to be working alright.
> 
> Also, the image provided by @derrickmehaffy seems to be faulty, I have tried with a windows and mac machines and it seems it can not process it.
> 
> If you have the time derrick, could you test again with this pr? pray

yeah it was provided by a user I have no idea wtf is going on with it

**Comment by jhoward1994** [comment]
@Marc-Roig I can see the dimensions for AVIF images 👍🏻

however uploading a HEIF is giving me an error:
```
POST
http://localhost:1337/upload
{"data":null,"error":{"status":400,"name":"ApplicationError","message":"File is not a valid image","details":{}}}
```
do you get the same?

**Comment by Marc-Roig** [comment]
You are right, for some heif images I am getting the error. I will remove the support for `heif` for now.

I added it, because with sharp there is an "issue" which, for some `avif` images, the metadata returns it's `heif`

**Comment by jhoward1994** [comment]
> I added it, because with sharp there is an "issue" which, for some `avif` images, the metadata returns it's `heif`

I see, does that mean for some AVIF files that have metadata-'HEIF' we will still not see the dimensions? That seems to be the behaviour I'm seeing

**Comment by Marc-Roig** [comment]
> I see, does that mean for some AVIF files that have metadata-'HEIF' we will still not see the dimensions? That seems to be the behaviour I'm seeing

Exactly, don't know if it is related to strapi running in a mac machine or not. But for now , if heif is giving issues, it's the best we can do.

**Review by jhoward1994 — APPROVED** [review]

**Pull request merged**
