### PR TITLE
Fix AWS SES not working in eu-central-1 region

### LINKED ISSUE #5852: strapi-provider-email-amazon-ses does not work in eu-central-1 region
**Describe the bug**
The `strapi-provider-email-amazon-ses` plugin does not work in eu-central-1 region.

**Steps to reproduce the behavior**

1. Configure the plugin to use the SES service in eu-central-1
2. Send email

**Expected behavior**
The email should be sent.

The issue was already recognised and  fixed here: https://github.com/aheckmann/node-ses/pull/60

The PR #5853 updates the `node-ses` dependency to a newer version that includes the fix.

**System**
Not relevant

### PR DESCRIPTION
**Pull request by epegzz**
Fixes #5852

#### Description of what you did:

Just updated the dependency to `node-ses`, as I had to fix the issue there: https://github.com/aheckmann/node-ses/pull/60

### CODE REVIEW

**Comment by alexandrebodin** [comment]
@epegzz  Thank you for the fi x!  Any breaking changes we should be concerned with ?

**Comment by epegzz** [comment]
@alexandrebodin Actually version `3.0.0` does not introduce any API changes at all. 

However, I think that the `3.0.0` version is wrongly tagged and should actually include some more recent commits which would introduce breaking API changes. 

But even if those changes eventually get introduced without doing another major version bump to `4.0.0` then those changes do not have any breaking effect given the way the lib is used by strapi 👍

**Comment by epegzz** [comment]
Tests are failing now, but this is not related to this PR

**Comment by alexandrebodin** [comment]
Thank for the precisions ;)

**Pull request merged**
