### PR TITLE
Improved create-strapi-app's templates

### PR DESCRIPTION
**Pull request by remidej**
### What does it do?

- Enables the use of a `template.js` file instead of `template.json` to return a template's config
- Enables the use of template shorthands to avoid typing the full GitHub URL of a template

Try it out like this:

```sh
# Uses a template.js function to return the latest version of the Strapi GraphQL plugin
yarn create strapi-app my-app --quickstart --template https://github.com/remidej/strapi-template-blog

# Use a <username>/<project> shorthand for the template name
yarn create strapi-app my-app --quickstart --template remidej/blog

# Use a super-shorthand for official templates: blog becomes strapi/strapi-template-blog
yarn create strapi-app my-app --quickstart --template blog
```

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Nice addition ! I think we should support 

```
# Use a <username>/<project> shorthand for the template name
yarn create strapi-app my-app --quickstart --template remidej/blog
```

and if you want to use a fully custom name you will just have to use the github url. This will make it more consistent with the other shorthand.

**Comment by remidej** [comment]
Alright, I'll also update the docs to explain this

**Review by derrickmehaffy — DISMISSED** [review]
LGTM on Docs, pending review from eng for code

**Review by petersg83 — CHANGES_REQUESTED** [review]
LGTM, just noticed that `merge-template.js` is duplicated in `lib` and `lib/utils`. Is it expected?

**Comment by remidej** [comment]
Nice catch @petersg83, there was a duplicate file that shouldn't have been here. I just deleted it

**Review by petersg83 — APPROVED** [review]
LGTM thanks :)

**Review by alexandrebodin — APPROVED** [review]
LGTM 👌

**Pull request merged**
