### PR TITLE
chore: Update jest, jest-circus and jest-cli to 28

### PR DESCRIPTION
**Pull request by gu-stav**
### What does it do?

This PR aims to update jest from version 26 to 28 to make use of new features (such as shards) later on. For now this is only to see, what breaks. It is a successor of https://github.com/strapi/strapi/pull/13343 which got a bit old and clunky.

### Why is it needed?

To keep up-to-date with dependencies.

### How to test it?

Well - it's jest and tests itself.

### CODE REVIEW

**Comment by petersg83** [comment]
Tests pass <3

**Review by alexandrebodin — COMMENTED** [review]
Looks good overal, I'm worries with the strapi.Start the test have slowed down even if I would be surprised could you just a quick look ?

**Comment by petersg83** [comment]
@alexandrebodin I reverted to `load` and `server.listen` because `strapi.start` calls `strapi.listen` and `strapi.listen` logs the "welcome back!" message, which is unwanted for tests.

**Review by alexandrebodin — APPROVED** [review]
LGTM 👍

**Pull request merged**
