### PR TITLE
fix(editor): set proper line height

### PR DESCRIPTION
**Pull request by ovlb**
### What does it do?

Set `line-height` of the editor content to `1.5`.

### Why is it needed?

Currently, the `line-height` inherits from `body` where it is set to `1`. This lead to very tight leading, which makes the text inside of the editor hard to read.

### How to test it?

Open WYSIWYG editor and edit text.

#### Current state

Screenshot 2022-01-16 at 13 50 04

#### Updated 

Screenshot 2022-01-16 at 13 49 11

### CODE REVIEW

**Comment by gu-stav** [comment]
@maevalienard I'm fine with this change and also think the default line height is too narrow. What do you think? Is 1.5 too wide?

**Review by maevalienard — APPROVED** [review]
Thanks for your PR! Looks way better to me, good catch! :D

**Review by gu-stav — APPROVED** [review]
Thanks for your contribution 🚀

**Review by gu-stav — APPROVED** [review]

**Review by MarionLemaire — COMMENTED** [review]
Tested on Getstarted using Chrome, for rich text field in CM entry : OK

**Pull request merged**
