### PR TITLE
Update node version requirements for v10 to v12

### PR DESCRIPTION
**Pull request by derrickmehaffy**
Signed-off-by: Derrick Mehaffy <derrickmehaffy@gmail.com>

#### Description of what you did:

As Strapi does not support Node v13/v14 I've updated all the requirements and made a few notes in the Documentation as well as the README.md and changed all of the packages to reference the node engine based on: https://docs.npmjs.com/files/package.json#engines

@alexandrebodin I am submitting this into the documentation branch but this will also need to be merged into master to update all the package node engine versions (after we test with things like Heroku which do use that engine version)

### CODE REVIEW

**Comment by alexandrebodin** [comment]
I think it supports node v14 now. Need to do a test with travis

**Comment by derrickmehaffy** [comment]
I don't believe sharp has updated their binaries they ship which is where I see most of the issues.

**Review by alexandrebodin — APPROVED** [review]
LGTM

**Comment by derrickmehaffy** [comment]
@alexandrebodin @petersg83 @lauriejim 

Whoever does the next release, make sure this gets pulled into the master as well, as it updates all the packages package.json as well as the main README.md

**Pull request merged**
