### PR TITLE
Drop support for node10

### PR DESCRIPTION
**Pull request by Convly**
### What does it do?

Drop support for Node v10, set the minimum required version to v12.x.x

### CODE REVIEW

**Comment by Convly** [comment]
Don't merge before updating `releases/v4` with `master` (probably right after the `3.6.4` release)

**Comment by petersg83** [comment]
What about allowing node 16 too ?

**Comment by alexandrebodin** [comment]
We should remove node 10 from the tests and add node 16 too

**Comment by Convly** [comment]
> We should remove node 10 from the tests and add node 16 too

Yep, you're right

> What about allowing node 16 too ?

Not sure about that, did you test if everything is working fine with v16?

**Comment by alexandrebodin** [comment]
No but we don't strongly need to verify it now as the goal is to release v4 with node 16 supported so we can define it now

**Comment by derrickmehaffy** [comment]
> What about allowing node 16 too ?

I was just about to ask the same thing :P

**Comment by Convly** [comment]
By the way, should we add a third node version to the Github actions, (12, 14, 16) instead of testing only the two latest ones?

**Review by alexandrebodin — APPROVED** [review]

**Comment by alexandrebodin** [comment]
> By the way, should we add a third node version to the Github actions, (12, 14, 16) instead of testing only the two latest ones?

I thought about it reviewing your PR can you try it and see the time diff in the CI ?

**Comment by Convly** [comment]
> > By the way, should we add a third node version to the Github actions, (12, 14, 16) instead of testing only the two latest ones?
> 
> I thought about it reviewing your PR can you try it and see the time diff in the CI?

Since the suites are run in parallel, it appears that there isn't any significant performance drop.
Moreover, since we'll drop Mongo E2E tests, it'll largely compensate for the slight performance loss.

I would advise we continue with 3 testes node versions.

**Pull request merged**
