### PR TITLE
[RelationInput] move component to CM

### PR DESCRIPTION
**Pull request by ronronscelestes**
## What

Move RelationInput component to `content-manager/components`

### CODE REVIEW

**Comment by gu-stav** [comment]
@ronronscelestes could you merge this please into `feature/relations-main-view`?

**Comment by ronronscelestes** [comment]
> @ronronscelestes could you merge this please into `feature/relations-main-view`?

let's go! 
should I then delete feature/relations-main-view-relationinput-interface + I assume I'll add the tests and missing checkboxes there?

**Comment by gu-stav** [comment]
Ah, nevermind then. Let's merge this one (as soon as the test pass) into [feature/relations-main-view-relationinput-interface](https://github.com/strapi/strapi/tree/feature/relations-main-view-relationinput-interface) and then this one into `feature/relations-main-view`, because it contains more history. Good catch.

Tests + docs can be added in follow-up PRs, if you prefer that.

**Comment by ronronscelestes** [comment]
> Ah, nevermind then. Let's merge this one (as soon as the test pass) into [feature/relations-main-view-relationinput-interface](https://github.com/strapi/strapi/tree/feature/relations-main-view-relationinput-interface) and then this one into `feature/relations-main-view`, because it contains more history. Good catch.
> 
> Tests + docs can be added in follow-up PRs, if you prefer that.

yes sounds good this way!
I had to update lots of snapshots, I checked it's only css class name generated that changed or some css moved a few lines above or below, not sure how moving RelationInput could have provoked that though 🤔

**Review by gu-stav — APPROVED** [review]

**Pull request merged**
