### PR TITLE
Provide @malgamves with some nice elevator music while installing a plugin

### PR DESCRIPTION
**Pull request by MattieBelt**
#### Description of what you did:
Hacking away to provide @malgamves with some nice music while waiting for the graphQL plugin to be installed.

### CODE REVIEW

**Comment by MattieBelt** [comment]
Closing this since the jamstackconf booth has ended. :upside_down_face: :+1:

**Comment by lauriejim** [comment]
Thank you for the joke, you made my evening/night 🤣

**Comment by derrickmehaffy** [comment]
I concur this was hilarious

**Comment by MattieBelt** [comment]
Mission accomplished :sunglasses:

**Comment by malgamves** [comment]
I agree! It made my night! 😆 thoroughly impressed with how quick you got the PR ready 🙌

**Pull request closed without merging**
