### PR TITLE
Remove generic typing form GenericeService

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?

Remove generic typing form GenericeService

### Why is it needed?

Adding generic typing just introduced a typing error

### How to test it?

Create a custom service in a typescript project, there should be no typing errors

### CODE REVIEW

**Comment by stafyniaksacha** [comment]
A better approach would be to rewrite the `factories` typings, so we can use declaration merging 

```ts
// in core strapi/lib/types/factories

export interface ServiceUidMap {
  [key: string]: Service;
}

export function createCoreService<K extends keyof ServiceUidMap, T>(
  uid: K,
  customActions?: T
): T extends undefined
  ? () => ServiceUidMap[K] // only base service
  : T extends (...args: any) => any // custom action is function ? ({ strapi }) => ({})
  ? () => ReturnType<T> & ServiceUidMap[K] // merge custom action return type 
  : () => T & ServiceUidMap[K];
```

Then in user application we can have:

```ts
// file: ./schemas.d.ts (generated with yarn strapi ts:generate-types)

import {
  SingleTypeService,
  CollectionTypeService,
} from '@strapi/strapi/lib/core-api/service';

declare module '@strapi/strapi/lib/types/factories' {
  export interface ServiceUidMap {
    'plugin::foo.bar': CollectionTypeService; 
    'api::homepage.homepage': SingleTypeService;
  }
}
```

**Comment by Punit0405** [comment]
Please Merge this PR ASAP ! so that we can upgrade code from 4.3.2 to 4.3.6
Because it is giving us type errors.
Generic Service type error

**Comment by 3webbg** [comment]
We have the same problem with our projects. 
Please merge or find another solution ASAP :)

**Comment by antokhio** [comment]
Hi, not sure if that's right but here is service implementation for ts:
```
import { factories } from "@strapi/strapi";
import { Service } from "@strapi/strapi/lib/core-api/service";

export type ProjectService = Service & {
  getUsersProjectsIds: (id: number) => Promise<number[]>;
};

export default factories.createCoreService(
  "api::project.project",
  ({ strapi }): ProjectService => ({
    async getUsersProjectsIds(id: number) {
      const projects = await strapi.db.query("api::project.project").findMany({
        where: {
          $or: [
            {
              user: id,
            },
            {
              users: {
                id: id,
              },
            },
          ],
        },
      });

      return projects.map(({ id }) => id);
    },
  })
);```

Controller: 
```
const projectIds = await strapi
        .service<ProjectService>("api::project.project")
        .getUsersProjectsIds(user.id);
 ```

**Comment by antokhio** [comment]
Service in 4.3.5+ (4.3.9)
```ts
/**
 * message service
 */

import { factories } from "@strapi/strapi";
import { GenericService, Service } from "@strapi/strapi/lib/core-api/service";

type MessageService = GenericService & {
  test: () => Promise<any>;
};

export default factories.createCoreService(
  "api::message.message",
  ({ strapi }) =>
    ({
      async test() {
        return await strapi.db.query("api::message.message").count({});
      },
    } as MessageService)
);

```

**Comment by SvenWesterlaken** [comment]
To generalize the solution of  @antokhio:
```ts
import { factories } from '@strapi/strapi';
import { GenericService, Service } from "@strapi/strapi/lib/core-api/service";

type CustomService = GenericService & {
  [key: string]: Service
}

export default factories.createCoreService('api::project.project', ({ strapi }) => ({
  extendedService(...args) {
    let response = { okay: true };
    return response;
  }
}) as CustomService);
```

Also, why is this still not merged in version 4.5.1`!? This is one of many occurrences of the typescript just hindering the development instead of trying to make it easier.

**Comment by eucciferri** [comment]
Hi @SvenWesterlaken! How's it going? I was wondering to know if this will be solved in a general way in the Strapi code in future versions?
Thanks!

**Comment by Convly** [comment]
> Hi SvenWesterlaken! How's it going? I was wondering to know if this will be solved in a general way in the Strapi code in future versions? Thanks!

We're actively monitoring issues & use-cases regarding TS x Strapi. We're going to work on providing strong types for Strapi this year.

**Pull request merged**
