### PR TITLE
[i18n] change locale query params based on locale picker

### PR DESCRIPTION
**Pull request by mfrachet**
### What does it do?

It allows the locale picker in the CM listview to switch locale and refresh the URL query

### CODE REVIEW

**Review by HichamELBSI — APPROVED** [review]
LGTM

**Review by soupette — APPROVED** [review]
LGTM!

I have tested it and it works like a charm!

On a side note I have noticed that the effect in the `ListViewLayout` component is ran twice when changing the locale. Can you remove the `setQuery` from the dependencies array to fix it?

**Comment by soupette** [comment]
In fact, if you remove the `setQuery` from the dependencies array, you can use the `useQueryParams` hook instead:


```
const LocalePicker = () => {
  // ...
 const [query, setQuery] = useQueryParams();

 return (
  <Picker
      position="right"
      renderButtonContent={isOpen => (
        <Flex>
          <EllipsisParagraph width="20ch">{selected.name}</EllipsisParagraph>

          <Padded left size="sm">
            <Carret fill={isOpen ? '#007eff' : '#292b2c'} isUp={isOpen} />
          </Padded>
        </Flex>
      )}
      renderSectionContent={onToggle => {
        const handleClick = locale => {
          setSelected(locale);

          setQuery({ pluginOptions: { ...query.pluginOptions,  locale: locale.code } });
          onToggle();
        };

        return (
          <Padded top left right bottom>
            <List>
              {locales.map(locale => (
                <ListItem key={locale.id}>
                  <button onClick={() => handleClick(locale)} type="button">
                    <EllipsisParagraph width="200px">{locale.name}</EllipsisParagraph>
                  </button>
                </ListItem>
              ))}
            </List>
          </Padded>
        );
      }}
    />
 )
}

**Review by soupette — APPROVED** [review]
LGTM!!!!

**Pull request merged**
