### PR TITLE
Added header actions to bottom of create page

### PR DESCRIPTION
**Pull request by talentedunicorn**
#### Description of what you did:
Added action buttons to the bottom of create/edit views
Screenshot 2019-10-21 at 5 01 00 PM

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [x] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by soupette** [comment]
Hi thanks a lot for your contribution, we are aware that the buttons position should be improved which they will be when we release our next feature. However, I won't merge your PR as it doesn't respect our UI guidelines.

Thanks again for taking the time to solve this kind of issues I hope you will keep contributing on this project!

**Comment by talentedunicorn** [comment]
> Hi thanks a lot for your contribution, we are aware that the buttons position should be improved which they will be when we release our next feature. However, I won't merge your PR as it doesn't respect our UI guidelines.
> 
> Thanks again for taking the time to solve this kind of issues I hope you will keep contributing on this project!

Hey @soupette thanks for looking into my PR. I was curious what the UI guidelines were and how I had not followed them. Perhaps if I have more context i'll be able to make updates to meet those guidelines. 
I'm glad to hear that the button position is already being worked on and will be on the next feature/release?? I'm sure it will address this issue #4273 

Thanks for the patience, I hope I can make a worthwhile contribution in the future 😊

**Comment by Aurelsicoko** [comment]
I posted a screenshot of the new UI. Thanks a lot for your contribution, even if it wasn't accepted 👍

**Comment by talentedunicorn** [comment]
Thanks looking forward to contributing more in the futute :+1:

**Pull request closed without merging**
