### PR TITLE
Fix node inspector in develop

### PR DESCRIPTION
**Pull request by renz45**
This fixes node inspector for the existing develop script. The following usages now work as intended:

- `node --inspect node_modules/strapi/bin/strapi.js develop`
- `strapi develop --inspect`

The issue was that when a cluster was forked, a new port was assigned to the inspector, so the existing window would stay open. This forces the inspector to close and opens it back up on fork for a consistent dev experience. I also added a manual inspector option so it just works without reformatting `npm run develop` command.

The inspector module is experimental, but it's been around for awhile. I checked to make sure the usage conforms to the minimum version of node specified in the package.json

ref https://github.com/strapi/strapi/issues/3743

### CODE REVIEW

**Comment by lauriejim** [comment]
Can you please add this flag into this page of the documentation
https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-develop-dev
Thank you

**Comment by renz45** [comment]
Apologies for the delay! I've had a little trouble getting back to check this. Feel free to adjust the wording in those docs I pushed if needed. 😃

**Comment by renz45** [comment]
@lauriejim @derrickmehaffy I think this is good to go!

**Comment by derrickmehaffy** [comment]
Need to have Alex review/approve the PR before we can merge

**Comment by alexandrebodin** [comment]
Hi, sorry for the late review. I see this PR is quite outdated and has a few conflicts. Let us know @renz45  if you still want to finish the work :)

**Comment by alexandrebodin** [comment]
Closing for inactivity. Feel free to reopen if you can eventually pick it up ;)

**Pull request closed without merging**
