### PR TITLE
always escape RegExp when building query in mongoose connector

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix strapi/strapi#10348

### What does it do?

In a couple places the mongoose connector doesn't escape regexps before passing them to MongoDB

### Why is it needed?

See #10348. In short, making a request to `http://localhost:1337/restaurants?name_contains=lorem\` throws an error because of the trailing backslash.

### How to test it?

Follow the [quickstart](https://strapi.io/documentation/developer-docs/latest/getting-started/quick-start.html#_5-add-content-to-restaurant-content-type) using MongoDB and make a request to `http://localhost:1337/restaurants?name_contains=lorem\`. Without this PR it will throw an error. With this PR, it will return an empty array as expected.

### Related issue(s)/PR(s)

#10348

### CODE REVIEW

**Comment by petersg83** [comment]
Thank you, it looks good to me. Can you please add a test to cover this usecase please?
It's in the file `packages/core/strapi/tests/search.test.e2e.js`

**Comment by vkarpov15** [comment]
@petersg83 sure, I'll take a look at that later this week.

**Comment by vkarpov15** [comment]
@petersg83 added it in bea8313

**Review by petersg83 — APPROVED** [review]
Thank you, works perfectly!

Side node: I first tested with mongo 3.6 and the test wasn't failing. I switched to mongo 4.4 and then it failed correctly.

**Comment by abdonrd** [comment]
@petersg83 @vkarpov15 After this... This query stop working on my side 😕 

```graphql
{
  seasons(where: { slug_contains: "fms-.*-2021-2022" }) {
    slug
  }
}
```

**Pull request merged**
