### PR TITLE
Colors-fix

### LINKED ISSUE #12142: CLI 'develop' on fresh project spams weird text infinitely
## Bug report
I just started a new project and now strap is spamming weird stuff at me :sweat_smile: 

https://user-images.githubusercontent.com/2084639/148699056-16b133cf-0330-43ae-9730-e9fbfaee46b2.mp4

### Describe the bug

~~A clear and concise description of what the bug is.~~
You tell me :see_no_evil: 

### Steps to reproduce the behavior

0. (optional) open fresh environment `docker run --rm -it node:16 bash`
1. `npx create-strapi-app@latest my-project --quickstart`
2. See spam after some time
3. go into my-project folder
4. run `yarn develop`
5. See spam

### Screenshot
Screenshot from 2022-01-09 21-27-46

### System

- Node.js version: 16
- NPM version: 6.14.15
- Strapi version: 4.0.3
- Operating system: Ubuntu

### PR DESCRIPTION
**Pull request by EzraEn1**
### What does it do?

Pinned cli-table3 to 0.6.1 in strapi/core.

### Why is it needed?

cli-table3:0.6.0 is affected by the colors.js attack. cli-table3:0.6.1 fixes this.

### How to test it?

Running strapi should no longer produce zalgo text.

### Related issue(s)/PR(s)

Fixes #12142 from upstream lib `cli-table3`

### CODE REVIEW

**Review by soupette — APPROVED** [review]
LGTM

**Comment by petersg83** [comment]
Thank you @EzraEn1 for the fix! The `yarn.lock` files seems incorrect so we cannot merge your PR as it is. To go faster (since it's a high priority to solve) I took over and proposed a fix there https://github.com/strapi/strapi/pull/12157.
Are you ok if we close this PR in favor of https://github.com/strapi/strapi/pull/12157?

**Comment by EzraEn1** [comment]
Hey @petersg83, do whatever is needed! Just want Strapi back up and running for everyone and happy to have contributed :)

**Comment by petersg83** [comment]
Thank you :)

**Pull request closed without merging**
