### PR TITLE
chore(content-releases): enforce license limits for pending releases

### PR DESCRIPTION
**Pull request by markkaylor**
### What does it do?

- Checks the license has been configured with the maximumReleases option
- Checks if the user has or has not reached the limit per their license
- If the license is missing the config a default of 3 will be set since if you have a license with the feature enabled you should have at least that limit.

This PR only handles the backend validation, another PR will handle the error on the FE 

### Why is it needed?

- To enforce the license entitlements

### How to test it?

- Ping me for a license with a limit of 3
- Then test you can't create more than 3 releases

### CODE REVIEW

**Review by Feranchz — APPROVED** [review]
Tested locally and works great 🚀

**Comment by Feranchz** [comment]
We should add one attribute in the meta object of getReleases to have the maximumReleases number, but I think we should handle that in other PR with the front change 🤔

**Review by Feranchz — APPROVED** [review]

**Comment by joshuaellis** [comment]
Will there be an FE follow up? For example iirc in both seats & workflows we show a modal prompting to upgrade // buy more.

**Comment by markkaylor** [comment]
> Will there be an FE follow up? For example iirc in both seats & workflows we show a modal prompting to upgrade // buy more.

Yes there is another ticket for the FE

**Comment by joshuaellis** [comment]
All good! 😄 good to hear too!

**Pull request merged**
