### PR TITLE
Added norwegian translation.

### PR DESCRIPTION
**Pull request by ksolberg**
### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Review by soupette — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution, can you also update the index.js file so the Norwegian translation is available in the dropdown?

**Review by soupette — APPROVED** [review]
LGTM!

Thank you for your contribution.

**Comment by alexandrebodin** [comment]
Hello @ksolberg  can you please sign the CLA so we can your PR :)

**Comment by ksolberg** [comment]
@alexandrebodin hm, I clicked the sign button and got the confirmation, but here it still says not signed yet? What am I doing wrong?

**Comment by alexandrebodin** [comment]
I thing your commit email address isn't the same as your github account so it doesn't recognize you :/

**Comment by ksolberg** [comment]
@alexandrebodin ah ofc. Got mixed with work email which is not a gh account. Amended the last commit, but need to amend all it seems. Easier to create a new pull request it seems and discard this one. Ok with that?

**Comment by alexandrebodin** [comment]
As you wish :) You can rebase to make one commit with the right author too if your prefer :)

**Pull request merged**
