### PR TITLE
Add Turkmen ISO 639-1 locale code

### PR DESCRIPTION
**Pull request by kerimabdy**
### What does it do?

Adds support for Turkmen ISO 639-1 locale code

### Why is it needed?

Without "tk" locale code support, I have to use a different (Turkish tr) code, which causes other front-end-related issues.

### How to test it?

Has to display Turkmen (tr) in locales list inside the admin panel

### Related issue(s)/PR(s)

There is no issue

### CODE REVIEW

**Review by alexandrebodin — APPROVED** [review]

**Comment by alexandrebodin** [comment]
@kerimabdy You will have to upgrade the test snapshots to fix the test on this PR :)

**Comment by alexandrebodin** [comment]
Hi @kerimabdy FYI your PR is breaking a few tests, Let me know if you can work on it

**Comment by kerimabdy** [comment]
> FYI

I'll try, thanks!

**Comment by kerimabdy** [comment]
updated snapshot

**Review by Convly — APPROVED** [review]
LGTM

**Pull request merged**
