### PR TITLE
Add the option for a different Amazon SES domain

### LINKED ISSUE #3136: Add region for Amazon SES email provider
**Informations**
- **Node.js version**: v11.6
- **NPM version**: v6.5
- **Strapi version**: Alpha 25.2 (the problem is in strapi-provider-email-amazon-ses)
- **Database**: MongoDB 3.6.3
- **Operating system**: Amazon Linux AMI release 2017.09

**What is the current behavior?**
When setting up Amazon SES you haven't the possibility to select AWS region and it defaults to US East. If this is your case it will work, but if not it fails with an error 400 with an incorrect error message "auth.form.error.email.invalid"

**Steps to reproduce the problem**
Just install strapi ses plugin and configure it with an AWS account which doesn't belong to us-east-2

**Suggested solutions**
Adding a line in strapi-provider-email-amazon-ses/lib/index.js fixes the problem.
```   
 var client = nodeSES.createClient({
      key: config.amazon_ses_api_key,
      secret: config.amazon_ses_secret,
      amazon: "https://email.eu-west-1.amazonaws.com"
});
```
The "amazon" field should depend on a variable selectable from the config page of the email plugin

### PR DESCRIPTION
**Pull request by Achder**
> ⚠️ We have stopped merging PRs for now to the Strapi core.<br><br>
> The reason is that we are developing new architecture for the admin panel and for the plugins.<br>
> This new architecture will provide stability of the Strapi core as we approach the release of Beta.<br>
> We appreciate and welcome all your contributions, but until further notice, please do not submit a PR as it will not be merged.<br>
> Furthermore, you will have to rewrite it based on the new architecture.

#### Description:

Allow for configuration of a different Amazon SES domain

#### My PR is a:
- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix #3136 
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin (eMail -> Amazon SES provider)

#### Manual testing done on the following databases:
- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by lauriejim** [comment]
Can you add the description of your PR.
What did you do, why, etc...
Need context to make in understandable to all the community.

**Comment by lauriejim** [comment]
And please update your PR title, as said in the PR template.
The title is used in the change log and the current one is not understandable.

**Comment by derrickmehaffy** [comment]
@Achder I updated it for you, in the future please provide some more detailed descriptions and titles. :wink:

**Comment by alexandrebodin** [comment]
@Achder Hi,

Right now it is missing a default value or allowing to make the field optional in the UI. 

If you fill

**Pull request merged**
