### PR TITLE
Fix mongoose float and decimal problems

### LINKED ISSUE #2251: Cannot create Float or Decimal Fields
**Informations**
- **Node.js version**: 10.12.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: MongoDB
- **Operating system**: Windows 10

**What is the current behavior?**
When creating a number field, if "Float" or "Decimal" are selected from within Number Format, the server throws an error on restart: 

```
(node:21608) UnhandledPromiseRejectionWarning: TypeError: Undefined type `Float` at `total`
  Did you try nesting Schemas? You can only nest using refs or arrays.
...
(node:21608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-11-02T15:40:31.976Z] debug ⛔️ Server wasn't able to start properly.
[2018-11-02T15:40:31.980Z] error (hook:mongoose) takes too long to load
(hook:mongoose) takes too long to load

```

**Steps to reproduce the problem**
I have a content type that I named "order" and at the moment I have the fields "address: String", "city: String", "state: String", "zipcode: String", products: JSON", "total: Decimal."

The problem arises regardless of whether you try setting a default value or not. 

**What is the expected behavior?**

The field should be created without throwing any errors. 

**Suggested solutions**
I did see a similar issue reported in the now closed issue #1859.  Not sure if this is related to that or not, but maybe it's a place to start.

### LINKED ISSUE #2282: Wrong Decimal/Float precision
**Informations**
- **Node.js version**: 10.13.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0 (dev mode)
- **Database**: mongodb 4.0.3
- **Operating system**: Archlinux
- **mongoose version**: 5.3.8
- **mongoose-float**: 1.0.2

**What is the current behavior?**
Decimal: 3.14159265358979
Float: 3.14159265358979

**Steps to reproduce the problem**
Create a content type containing a decimal and a float
Fill both with pi = 3.1415926535897932384626
The result in admin panel is not correct...

**What is the expected behavior?**
Decimal: 3.14 **(Only two digits precision)**
Float: 3.14159265358979

**Suggested solutions**
This issue was discovered when I trying to fix #2251 
Because mongoose-float will set the schema types when loadType() is called, actually there is only one float type exists in the mongoose instance's schema types. Therefore, both Decimal and Float would point to the the last type set by mongoose-float (Currently Float). 

I have no idea how to fix this (submit PR), so I open this issue.

### PR DESCRIPTION
**Pull request by Leo1003**
My PR is a:

🐛 Bug fix

Main update on the:

Plugin

This pull request can resolve #2282 and resolve #2251 before mongoose-float release 1.0.3. 
Assigning mongoose schema types by ourselves can create different types. But if doing this the convertType() should return type name since mongoose tries to resolve objects by their constructor name.

### CODE REVIEW

**Comment by lauriejim** [comment]
Thank you @Leo1003 for this PR it will take a look.

**Comment by lauriejim** [comment]
Hey @Leo1003 `1.0.3` is released and a PR have been open https://github.com/strapi/strapi/pull/2351

**Comment by lauriejim** [comment]
Anyway thank you for the proposal it's appreciate.

**Comment by Leo1003** [comment]
I knew #2351 have fixed for #2251. But it didn't resolve #2282. So that is the main reason that I submitted this PR.

**Pull request merged**
