### PR TITLE
Fix: #17067 Discord Auth not assigning username correctly

### LINKED ISSUE #17067: Discord Auth not assigning username correctly
- Node.js version: 18.15.0
- NPM version: 9.5.0
- Strapi version: 4.11.2
- Database: PostgresSQL
- Operating system: Ubuntu Server
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Discord is removing discriminator soon and Strapi does not update to the new username.  In addition, users that have changed their Discord name have a #0 at the end of their name.  This would not be needed. Another issue that would help is adding the Discord ID of a user to the user table.

### Code snippets

https://github.com/strapi/strapi/blob/553217bd1cd9b63a2c144e1aee7543810a478fc1/packages/plugins/users-permissions/server/services/providers-registry.js#L58

### PR DESCRIPTION
**Pull request by akay41024**
Fix: #17067 

### What does it do?
Combine username and discriminator (if discriminator is exist and not equal to 0)

### Why is it needed?
If username and discriminator is not exist and equal to 0 this will give us error or wrong username details

### How to test it?
You can check the discriminator by giving 0 

### Related issue(s)/PR(s)
This is related to resolved #17067 issue

### CODE REVIEW

**Comment by innerdvations** [comment]
Thanks for your PR! Could you please target the `develop` branch instead of `main`? Thanks!

**Comment by akay41024** [comment]
Sure I will target the develop branch

**Comment by alexandrebodin** [comment]
Hi, Going to close this PR as staled. Feel free to reopen and finish the work when you can.

Thank you for contributing 🙌

**Comment by ricardoboss** [comment]
@akay41024 can you pick this back up?

**Pull request closed without merging**
