### PR TITLE
fix: checking for relation type existence

### PR DESCRIPTION
**Pull request by aleksandrjet**
### What does it do?

I fixed an error, which happened when deleting content-type or collection in usage. Users faced error here - https://github.com/strapi/strapi/issues/19535

Code had error, because checking of existing metadata `db.metadata.get(type)` finishes with error, if metadata is not exist:

```ts
// packages/core/database/src/query/helpers/populate/apply.ts
if (!db.metadata.get(type)) {
    map[type] = {}; // this condition will never be done
    return;
}

// packages/core/database/src/metadata/metadata.ts
export class Metadata extends Map<string, Meta> {
  get(key: string): Meta {
    if (!super.has(key)) {
      throw new Error(`Metadata for "${key}" not found`);
    }

    return super.get(key) as Meta;
  }
}
``` 

### Why is it needed?

Error happens when deleting component or collection in usage 

### How to test it?

I didn't add additional tests, current tests are passed

### Related issue(s)/PR(s)

I faced this problem too - https://github.com/strapi/strapi/issues/19535

### CODE REVIEW

**Comment by aleksandrjet** [comment]
should I do something else to someone checks it?

**Comment by PierreCavalet** [comment]
Can anyone review this PR ? the bug has been there since febrary and everytime you switch branch and a content type is not there it is a nightmare ...

**Comment by stephaned-ev** [comment]
Hello, any news on this topic?
It is a blocking point. Turns out it is impossible to use Strapi Cloud because of this bug, as you dont have the possibility to manipulate the DB.

**Comment by aleksandrjet** [comment]
@oiorain hello! I saw you mark this PR as community, may be you could say, will this pr get approved or not? I am ready to change somethings if it needs

**Comment by alexandrebodin** [comment]
> [!IMPORTANT] 
> With the release of Strapi 5, we have lifted the code freeze. To ensure we can effectively review and assist with contributions, we are now only accepting PRs targeting version 5 (the develop branch).<br/> 
> As your PR is targeting some of the most recent v4 version, We we would greatly appreciate it if you could update your contribution to align with version 5 and resubmit!

**Comment by alexandrebodin** [comment]
Hello 👋  We are going through every PR now that v5 is release and the code freeze has been lifted. 

This should be fixed in v5 but it seems like it would be a nice fix for v4 to be passed. We will be trying to review everything in the next month 🙌

**Review by Marc-Roig — APPROVED** [review]

**Pull request merged**
