### PR TITLE
Enumeration filter support for GraphQL

### LINKED ISSUE #11751: [v4] Can't filter by Enumeration field in GraphQL
Can't filter by enumeration fields in graphql.

query

As per screenshot above, filtering by `state` field is not valid but `state` field can be returned.

I thought maybe `state` is some sort of reserved name, tried another name - the same result.

### System

- Node.js version: 16.13
- Yarn version: 1.22.17
- Strapi version: 4.0.0
- Database: mysql
- Operating system: macOS

### PR DESCRIPTION
**Pull request by iicdii**
Signed-off-by: harimkims <harimkims@gmail.com>

### What does it do?

- Add Enum type attribute field into GraphQL scalar types.
- Add e2e test code for filterting enum field

### Why is it needed?

It's needed to support for filtering by enumeration type field.

### How to test it?

make query request in GraphQL playground

### Related issue(s)/PR(s)

Closes #11751

### CODE REVIEW

**Comment by mruknowme** [comment]
@iicdii thanks for your commit. I may be doing something wrong but I don't think this fixes it entirely. Upon query it produces error: `String cannot represent a non string value: enqueued`.

**Comment by iicdii** [comment]
Can you share your `api/<model>/content-types/<model>/schema.json`?

**Comment by mruknowme** [comment]
> Can you share your `api/<model>/content-types/<model>/schema.json`?

@iicdii sure,

```json
{
  "kind": "collectionType",
  "collectionName": "entries",
  "info": {
    "singularName": "entry",
    "pluralName": "entries",
    "displayName": "Entry",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "title": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string",
      "required": true
    },
    "ytId": {
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      },
      "type": "string",
      "required": true,
      "minLength": 11,
      "maxLength": 11
    },
    "channelName": {
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      },
      "type": "string",
      "required": true
    },
    "channelId": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string",
      "minLength": 24,
      "maxLength": 24,
      "required": true
    },
    "state": {
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      },
      "type": "enumeration",
      "enum": [
        "enqueued",
        "playing",
        "played",
        "cancelled",
        "rejected"
      ],
      "default": "enqueued",
      "required": true
    },
    "guest": {
      "displayName": "guest",
      "type": "component",
      "repeatable": false,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "component": "entry.guest",
      "required": true
    },
    "thumbnail": {
      "displayName": "Thumbnail",
      "type": "component",
      "repeatable": false,
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      },
      "component": "entry.thumbnail",
      "required": true
    },
    "organization": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::organization.organization",
      "inversedBy": "entries"
    },
    "testField": {
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      },
      "type": "enumeration",
      "enum": [
        "opt1",
        "opt2"
      ],
      "enumName": "testField"
    }
  }
}

```

**Comment by iicdii** [comment]
I cannot reproduce your case.
By the way the problem looks like in your data -`String cannot represent a non string value: enqueued` This error is validation error within GraphQL response data.
Can you check your `value` of `state` is saved as string in your data?

**Comment by mruknowme** [comment]
@iicdii not sure what you mean, I can commit and provide access to git if that will help?
All I did was:

1. make identical changes directly in node_modules (just to see if it works)
2. restarted and executed the same query

> Can you check your value of state is saved as string in your data?

How can I check it? (sorry if it's a silly question).

But I created a brand new v4 project, same errors

**Comment by iicdii** [comment]
Can you share you sql dump then? If you use SQLite, you can find it `.tmp/data.db` in your root directory

**Review by Convly — APPROVED** [review]
Hi, thanks for opening this PR and updating the tests!
Works well on my side, tested with @mruknowme example.

**Comment by mruknowme** [comment]
@iicdii here's sql dump, still can't make it work even on new projects
https://gist.github.com/mruknowme/3e40532bc7395a1daf17f1e8dbf8684c

**Comment by Convly** [comment]
@mruknowme do you have a higher quality screenshot of the error thrown?

**Comment by mruknowme** [comment]
@Convly sure https://ibb.co/WHhbkkt

**Comment by Convly** [comment]
I might be wrong, but isn't the error thrown because of something in your `SubmitGuestEntry` mutation (l.40, c.11)

**Comment by mruknowme** [comment]
@iicdii and @Convly apologies, I did something weird before. These fixes from @iicdii are working indeed.

**Comment by Convly** [comment]
No problem, glad you figured it out :rocket:

**Pull request merged**
