### PR TITLE
Fix sanitize polymorphic entities that can be undefined or ids only

### PR DESCRIPTION
**Pull request by alexandrebodin**
Fix https://github.com/strapi/strapi/issues/9438

### CODE REVIEW

**Review by petersg83 — APPROVED** [review]
LGTM, I confirm it fixes the issue

**Comment by cgonzalezsan** [comment]
This won't fix my issue. Here is the link to the [video](https://youtu.be/M_KMl5GZA1o) where I showcase it. I used the changes from this commit

**Comment by alexandrebodin** [comment]
@cgonzalezsan this log is showing a notFound entity. No the same error as this PR has fixed. Can you please open a new issue for this ?

**Comment by cgonzalezsan** [comment]
@alexandrebodin it's the related issue (MongoDB nested component media causes unique validation error) that you closed yesterday as it was related to this PR? I added my comment there as well.

**Comment by alexandrebodin** [comment]
The unique validation error is just a generic error to give a bit of user feedback but it isn't actually your root issue.
If you look closely at the error above you will see the root cause is "notFound" erro & previsouly it was another error. There are not the same

**Comment by cgonzalezsan** [comment]
@alexandrebodin understood, then it might make sense to unlink the issues. I also mentioned you in the other one, would you be able to provide some feedback?

Thanks

**Pull request merged**
