### PR TITLE
Add Czech translations

### PR DESCRIPTION
**Pull request by cebreus**
#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [x] Admin
- [ ] Documentation
- [ ] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello! Thank you for this PR, I really appreciate it.

Can you please do the same as in this PR https://github.com/strapi/strapi/pull/4414
Could you also add the other plugins translation to make sure the CZ translation is complete.

Thank you for your time.

**Comment by profispojka** [comment]
Hi, I have updated this request with the required plugins translations in my new PR - https://github.com/strapi/strapi/pull/4730

**Comment by lauriejim** [comment]
Can you please create just one PR with all your translation. 
Please add the content from #4730 to this one please.

**Comment by MartinN3** [comment]
@profispojka i have checked your PR translations and i think they are fine.

**Comment by lauriejim** [comment]
Hello @cebreus can you please apply [these changes](https://github.com/strapi/strapi/pull/4730) to this PR please. 
I would love to merge this PR.

@MartinN3 Thank you for your review.

**Comment by cebreus** [comment]
Hi @lauriejim, a merge of the work @profispojka is done.

**Comment by lauriejim** [comment]
Shouldn't it be `cz` instead of `cs` 🤔 ?

**Comment by cebreus** [comment]
> Shouldn't it be `cz` instead of `cs` 🤔 ?

No, no according to (ISO)[https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes] or https://www.w3schools.com/tags/ref_language_codes.asp

**Comment by VentyCZ** [comment]
@lauriejim 
> Shouldn't it be `cz` instead of `cs`  ?

Depends on context, cz is 2 letter country code (Czech Republic) and cs is 2 letter language code.
Usually used together to form cs-cz.

**Comment by VentyCZ** [comment]
BTW, @cebreus, great job on the translation!

I'm just sad, that this project does not use Crowdin or similar platform for translation (like OBS Studio for example).

**Comment by cebreus** [comment]
Almost all admiration belongs to @profispojka, who continues on my work. He made approximately 90% of the work. Thanks, @profispojka!

For translation, I used Crowdin, because of theirs automatic suggestions for tranlation and warnings on continuity in translation.

**Comment by lauriejim** [comment]
Hello @VentyCZ ! Thank you for your feedback.
We planned to use Crowdin but not a high priority on our side.

After that is the CS language is used in many other countries? (suppose yes, like the FR)
BUT is this CS is really different in each of these countries? (like PT and TR-BR for the brasil)

**Comment by cebreus** [comment]
> Hello @VentyCZ ! Thank you for your feedback.
> We planned to use Crowdin but not a high priority on our side.
> 
> After that is the CS language is used in many other countries? (suppose yes, like the FR)
> BUT is this CS is really different in each of these countries? (like PT and TR-BR for the brasil)

@lauriejim Czech language is used only in the Czech Republic. We have no colonies, dominions or countries :-)

**Comment by lauriejim** [comment]
OKay so I think if we use CZ withe the CZ flag instead of CS will be more easy to understand nop?

**Comment by cebreus** [comment]
> OKay so I think if we use CZ withe the CZ flag instead of CS will be more easy to understand nop?

No! As I referred above, we must use `cs`. This is official by industrial standards.

**Comment by cebreus** [comment]
> So LGTM 🇨🇿!

**CZ is nonsense.**

Please, see the info on  [ISO](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) or [W3C](https://www.w3schools.com/tags/ref_language_codes.asp).

* `cs` is code for the language
* `cz` i country specification
* `cs-cz` is full specification for webpages 

Info: `cs` is a historical relict of the state Czechoslovakia. After breaking the state into the Czech Republic (aka Czechia) an Slovak Republic (aka Slovakia). Czechia passed down `cs` and Slovakia has new code `sk`.

**Comment by lauriejim** [comment]
So it's good, it's CS 🤔

**Comment by derrickmehaffy** [comment]
Just gonna throw this in here: https://www.w3schools.com/tags/ref_language_codes.asp

IMO we should be using the official standards of language codes no matter how confusing they are. Someone else in the world did the hard work for us.

**Comment by profispojka** [comment]
Hi. I had changed the translation, fixed a few typos and I dont see the latest changes there. @cebreus seems my latest update to your branch has not been merged, could you check it out please? https://github.com/cebreus/strapi/pull/2

**Pull request merged**
