### PR TITLE
Upload: Improve asset cards and upload progress visual design

### PR DESCRIPTION
**Pull request by gu-stav**
### What does it do?

- Fixes the badge alignment once `@strapi/design-system@1.3.0` is released

| Before | After |
|-|-|
| Screenshot 2022-11-14 at 13 11 01 |  Screenshot 2022-11-14 at 13 12 49 |

- Removes the border-radius bottom-left and bottom-right from `UploadProgress`
- Updates `UploadProgress` colors for `@strapi/design-system@1.3.0`

> **Note**
> The attached PR updates the colors of the `ProgressBar` component, so that it will be visible again.

| Before | After |
|-|-|
| Screenshot 2022-11-14 at 13 09 14 | Screenshot 2022-11-14 at 13 14 18 |

### Why is it needed?

Stay up-to-date with the UI Kit.

### Related issue(s)/PR(s)

- https://strapi-inc.atlassian.net/browse/CONTENT-220
- Depends on https://github.com/strapi/design-system/pull/770
- Depends on https://github.com/strapi/design-system/pull/769

### CODE REVIEW

**Comment by gu-stav** [comment]
@maevalienard The "cancel" button during upload doesn't have any hover/ focus effect: do you have an idea what we could use there?

**Review by ronronscelestes — COMMENTED** [review]
nice 💃
only comment, I feel like there is a misalignment between the `cancel` and the `cross` icon now 👀
image

**Comment by maevalienard** [comment]
> The "cancel" button during upload doesn't have any hover/ focus effect: do you have an idea what we could use there?

Good catch. From what I saw, we could use neutral700 as hover color :)

**Comment by joshuaellis** [comment]
I've addressed the feedback from @maevalienard & addressed your comment @ronronscelestes – its now exactly as specified in the figma file 🙇🏼‍♀️

**Review by ronronscelestes — CHANGES_REQUESTED** [review]
thanks for the fixes @joshuaellis 💃
one last UI tweak: 

I think by doing that
```
<Card borderColor={error ? 'danger600' : undefined}>
```
in `UploadingAssetCard` we break the border color when no error

image

from my tests it should be fixed by doing: 
```
<Card borderColor={error ? 'danger600' : 'neutral150'}>
```

**Review by ronronscelestes — APPROVED** [review]
looks goood 💅

**Review by joshuaellis — APPROVED** [review]

**Review by ronronscelestes — APPROVED** [review]

**Pull request merged**
