### PR TITLE
Fix core router not working within plugin context

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Fix core router not working within plugin context

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Fix https://github.com/strapi/strapi/issues/14438

### CODE REVIEW

**Comment by Eggwise** [comment]
@alexandrebodin Can we merge this ? I think this is an important issue to fix as developers cannot create plugins now even though strapi says its possible in their blog
https://strapi.io/blog/how-to-create-a-strapi-v4-plugin-server-customization-4-6

**Comment by Eggwise** [comment]
@Convly Please review

**Comment by Convly** [comment]
Hello and thanks for your comment.

Unfortunately, Alexandre is currently off and this is a draft PR that might be subject to changes. This won't get ready for review before ~2 to 4 weeks.

If this issue is a high priority for you, I suggest you open a new PR with your proposed solution and I'll happily review it.

**Comment by alexandrebodin** [comment]
Ok just updated the PR I think it's ready to review now

**Review by Convly — CHANGES_REQUESTED** [review]
The logic was a bit confusing for me but it seems to work well, 1 small style comment but otherwise lgtm :thinking:

**Review by Convly — APPROVED** [review]
LGTM
Can you update your branch with main to check if the tests are still passing? :slightly_smiling_face:

**Review by Convly — APPROVED** [review]
:magic_wand:

**Pull request merged**
