### PR TITLE
Cloudinary provider plugin secret field now password type

### PR DESCRIPTION
**Pull request by davidkartuzinski**
> ⚠️ We have stopped merging PRs for now to the Strapi core.<br><br>
> The reason is that we are developing new architecture for the admin panel and for the plugins.<br>
> This new architecture will provide stability of the Strapi core as we approach the release of Beta.<br>
> We appreciate and welcome all your contributions, but until further notice, please do not submit a PR as it will not be merged.<br>
> Furthermore, you will have to rewrite it based on the new architecture.

The Cloudinary Provider Plugin had a "text" field but needed a "passsword" field to hide the credentials.

#### Description:

Just changed a field from "text" to "password" type. This is the secret key and should be a "password" type - not "text" type.

#### My PR is a:
- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix #issueNumber
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:
- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by lauriejim** [comment]
Please can you fix you linter to use single quote.

**Comment by davidkartuzinski** [comment]
> Please can you fix you linter to use single quote.

I just saw this.  Yes and I will update.

**Comment by Aurelsicoko** [comment]
LGTM about this change, but @davidkartuzinski you still need to replace the double-quotes by single-quotes instead.

**Comment by davidkartuzinski** [comment]
@Aurelsicoko @lauriejim - I am not sure who will approve this now.  I made the double quotes back to single quotes (also fixed linter rules). This should be okay now.

**Comment by lauriejim** [comment]
Look good, just let me test it.

**Pull request merged**
