### PR TITLE
Fix uploaded file order by size

### PR DESCRIPTION
**Pull request by chriswinch**
#### Description of what you did:
Changes upload file size type to integer so that graphQL can sort the values as expected.
Fixes: #2625 

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by chriswinch** [comment]
@alexandrebodin good catch. have update to decimal :) 
I'm new to graphQL so hope that's the correct type this time!

**Comment by chriswinch** [comment]
Also not 100% on what is causing the e2e tests to fail :[

**Comment by alexandrebodin** [comment]
@chriswinch After trying to migrate, this PR is a big breaking change on existing databases. Change the type breaking the indexing. We need to fix some of the migration behaviour before merging this PR. FOr now you can overide your file upload model locally using the extensions fodler.

**Comment by chriswinch** [comment]
Thanks for the update @alexandrebodin. Is there anything I should update in this PR?

**Comment by alexandrebodin** [comment]
@chriswinch If you feel like making a PR on clearing the column indexes before changing the types then you can surely do it :) You would need to make your PR on top of the develop branch instead and work on the strapi-connector-bookshelf package to handle it. Let me know if you are interested ;)

**Comment by derrickmehaffy** [comment]
Basically the problem that @alexandrebodin was saying is that numerical (decimal) fields can't be included in the general text based full index that happens on SQL databases, these are generated when strapi starts if they don't exist (or a new text based field is added? will need to check)

Basically we need to see if the schema is changed and if a previous text based field is now a numerical one, we wipe the index, update the field, and recreate the index without it.

**Comment by chriswinch** [comment]
@alexandrebodin @derrickmehaffy 
Yeah if you could create an issue for it I'm happy to take a look.
Very new to bookshelf / knex so if someone beats me to it then that's cool 👍

**Pull request merged**
