### PR TITLE
feat: Hungarian admin translations

### PR DESCRIPTION
**Pull request by pataiadam**
### What does it do?

This PR adds Hungarian translations to the project.

### Why is it needed?

Adding Hungarian translations helps users of the project to easily use it in Hungarian as well.

### CODE REVIEW

**Comment by gu-stav** [comment]
@jhoward1994 If you have any questions on how we handle translations, please let me know 🙏🏼

**Review by jhoward1994 — APPROVED** [review]
Köszönöm!

**Comment by gu-stav** [comment]
@jhoward1994 Please do not forget to add the milestone (otherwise the change won't be included in the changeset) 🙏🏼

**Comment by jhoward1994** [comment]
> @jhoward1994 Please do not forget to add the milestone (otherwise the change won't be included in the changeset) 🙏🏼

Woops sorry, thank you!

**Pull request merged**
