### PR TITLE
Fix knex, pg, mysql versions

### LINKED ISSUE #9450: problem installing 3.5.0 by npx
Hi,
after run the command on my server
ubuntu : 20.04
node: v14.15.5
npm: 7.5.4

`npx create-strapi-app my-project --quickstart
`
I get

```
Creating a new Strapi application at /root/my-project.

Creating a quickstart project.
Creating files.
Error while installing dependencies:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-project@0.1.0
npm ERR! Found: knex@0.19.5
npm ERR! node_modules/knex
npm ERR!   knex@"<0.20.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"^0.20.0" from strapi-connector-bookshelf@3.5.0
npm ERR! node_modules/strapi-connector-bookshelf
npm ERR!   strapi-connector-bookshelf@"3.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-18T17_27_16_804Z-debug.log
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your p                                                       roject.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following                                                        command:

cd /root/my-project && npm install

npm ERR! code 1
npm ERR! path /root
npm ERR! command failed
npm ERR! command sh -c create-strapi-app "my-project" "--quickstart"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-18T17_27_17_934Z-debug.log
```

### PR DESCRIPTION
**Pull request by petersg83**
May fix #9450

### CODE REVIEW

**Review by derrickmehaffy — APPROVED** [review]
LGTM but we should run some additional manual tests with these versions on multiple operating systems to ensure there is no bugs

(Was thinking DigitalOcean managed databases and AWS RDS)

**Review by alexandrebodin — APPROVED** [review]
LGTM. Good initiative

**Comment by jorrit** [comment]
Why is sqlite3 pinned to a version older than previously selected?

**Comment by alexandrebodin** [comment]
@jorrit it's not if you look at the diff we hadd a specific case to use v5.0.0 of sqlite :)

**Comment by jorrit** [comment]
What do you mean? What I saw was that previously it was ^5.0.1 and now it is 5.0.0. I could not read an explanation for this in the diff.

**Comment by alexandrebodin** [comment]
the dependency in the getstarted app is not the one used in generated project just our example project. The version used in the generated version is here https://github.com/strapi/strapi/pull/9511/files#diff-c330785d28abd1f2586b6a5afe96f968ac8ac7b69bafad48708729b1818925a3L15-L19

**Comment by derrickmehaffy** [comment]
There was a previous issue with SQLite on windows (v5.0.1) that was throwing an error, I had issued a previous patch (modified in that PR @alexandrebodin linked) to temporarily patch the issue.

You can find that issue here: https://github.com/strapi/strapi/issues/9120

**Comment by derrickmehaffy** [comment]
This pull request has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/new-release-strapi-v3-5-2/3147/1

**Pull request merged**
