### PR TITLE
adjust condition for subdomain when it is an empty string

### PR DESCRIPTION
**Pull request by charlesjohannisen**
### What does it do?

Allow a provider with a subdomain that has a blank/empty value.

### Why is it needed?

The condition does not allow subdomain to be added if subdomain is an empty string.

### Related issue(s)/PR(s)

none

### CODE REVIEW

**Review by soupette — DISMISSED** [review]
LGTM!

Thanks for taking the time to contribute.

**Comment by soupette** [comment]
@charlesjohannisen can you make sure the DCO checks so we can merge your PR?

**Review by HichamELBSI — APPROVED** [review]
LGTM

**Review by HichamELBSI — APPROVED** [review]
LGTM

**Pull request merged**
