### PR TITLE
[Enhancement]: Clone entity relations

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

* Fix: https://github.com/strapi/strapi/issues/15093
* resolves https://github.com/strapi/strapi/issues/10603

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Just adding some meta information, we currently have a customer looking at this feature/PR, internal reference is TID2870

**Comment by Marc-Roig** [comment]
@derrickmehaffy for cloning relations in the Admin UI or using the entityService clone?

**Comment by derrickmehaffy** [comment]
Admin panel

**Comment by Marc-Roig** [comment]
@RomanBON We are workign on it, during the next 2 weeks we will give updates and probably this first iteration will be ready to be merged :)

**Comment by sushmavoleti** [comment]
Any update here, please?

**Comment by joshuaellis** [comment]
> Any update here, please?

We're QA'ing the feature.

**Review by joshuaellis — APPROVED** [review]
do you think we should squash and merge? or merge-commit?

**Comment by Marc-Roig** [comment]
I dont have a preference but I would normally merge commit

**Comment by joshuaellis** [comment]
you do you <3

**Pull request merged**
