### PR TITLE
Update default configuration access in hook

### LINKED ISSUE #3719: Misleading information in hooks documentation
I think it is like a little bug in documentation:

Look at https://strapi.io/documentation/3.0.0-beta.x/advanced/hooks.html
inside initialize, `this` is a Function 

image

if we want to get access to hook config (from defaults) inside initialize function, we can get it:
`this().defaults['myConfig']` or `strapi.config.hook.settings.myhook['myConfig']`

**System**
- Node.js version: 10.15.1
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.13

### PR DESCRIPTION
**Pull request by daksamit**
#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #3719
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [x] Documentation
- [ ] Framework
- [ ] Plugin

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello @daksamit!
Can you precise in your PR body what you tried to do and why.
Because here `this` is not a function.

**Comment by daksamit** [comment]
It's associated with [that issue](https://github.com/strapi/strapi/issues/3719)

**Comment by lauriejim** [comment]
Yes I saw. 
But did you test your update?

**Comment by daksamit** [comment]
Yes, when want to access defaults inside initialize function we need to call this().defaults (or strapi.config.hook.settings.myhook)
Is that what you mean ?

**Comment by lauriejim** [comment]
If I log `this` I got an empty object `{}`

**Comment by daksamit** [comment]
Hmm, My steps to reproduce (3.0.0-beta.14):
1. create project using `strapi new project --quick start`
2. // config/hook.json
```json
...
  "myhook": {
    "enabled": true
  }
```
3. // hooks/myhook/index.js
```js
'use strict';
module.exports = strapi => {
  const hook = {
    defaults: {
      someConfig: {
        test: 123
      }
    },
    async initialize(cb) {
      strapi.log.debug('this', this.defaults);
      strapi.log.debug('this()', this().defaults);
      cb();
    }
  };
  return hook;
};

```
4. run `strapi develop`
my output:

image

**Comment by lauriejim** [comment]
The issue is, in the documentation you updated, `initialize` function is an arrow function, so `this` is an empty object.
And here in the code you sent in you last comment, `initialize` is not an arrow function.
So in your PR you also have to upadte the `initialize` function.

**Comment by daksamit** [comment]
right, thanks! I totally missed it. I will update my PR :)

**Comment by lauriejim** [comment]
Awesome thank you! Waiting for your update.
Your PR will be ready to merge after that.

**Comment by alexandrebodin** [comment]
Hi @daksamit, any update on this ?

**Pull request merged**
