### PR TITLE
Fix no response when get user permission role with internal network

### PR DESCRIPTION
**Pull request by Cow258**
#### Description of what you did:
- Add timeout to fix no response issue
- Fix the function input parameters

> #4625 No response when get user permission role with internal network

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by Cow258** [comment]
@lauriejim @Aurelsicoko

**Comment by derrickmehaffy** [comment]
@Cow258 can you check my response here: https://github.com/strapi/strapi/issues/4625#issuecomment-560267233

I believe @Aurelsicoko already added a fix for this

**Comment by Cow258** [comment]
👌🏻 let's check it

**Comment by Cow258** [comment]
This issue still on 17.8

**Pull request merged**
