### PR TITLE
Allow search Users in the API

### LINKED ISSUE #2639: Allow search Users in the API
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

With https://github.com/strapi/strapi/pull/1520 we add a new query filter for the generated API, but the User model from the `users-permissions` plugin does not have it.

### PR DESCRIPTION
**Pull request by abdonrd**
**Description:**

Allow search Users in the API

Fix #2639

**My PR is a:**
- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix #issueNumber
- [ ] 💅 Enhancement
- [x] 🚀 New feature

**Main update on the:**
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

**Manual testing done on the follow databases:**
- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres

### CODE REVIEW

**Comment by abdonrd** [comment]
@lauriejim I think I'm going to need help! 😅 The `search` is not working.

`strapi.query('user', 'users-permissions').attributes` returns `undefined`.

**Comment by lauriejim** [comment]
Thank you @abdonrd to trying to fix this issue.
I will take to to check your work soon as I can.

**Comment by abdonrd** [comment]
@lauriejim any news about this? 😄

**Comment by derrickmehaffy** [comment]
@abdonrd can you take a look at the conflicts and maybe rebase this on the current master to see if this can merged?

**Comment by abdonrd** [comment]
@derrickmehaffy solved!

**Comment by abdonrd** [comment]
Friendly reminder about this https://github.com/strapi/strapi/pull/2685#issuecomment-457018382! 🙂

**Comment by alexandrebodin** [comment]
@abdonrd I'm closing this PR as you implemented the user search in the beta for both mongo and postgres which was missing in this PR. 

Hope you will like it ;)

**Comment by abdonrd** [comment]
Thanks!

**Pull request closed without merging**
