### PR TITLE
fix: delete process.nexttick

### PR DESCRIPTION
**Pull request by christiancp100**
### What does it do?

It fixes the memory issue on the Data Transfer.

### Why is it needed?

To get data transfer work with big amounts of data

### How to test it?

Do a transfer between to strapi instances with a large amount of data. It should work as expected and the memory shouldn't spike.

### Related issue(s)/PR(s)
https://github.com/strapi/strapi/pull/18557

### CODE REVIEW

**Review by innerdvations — APPROVED** [review]
This will definitely need some thorough QA but code looks fine. Make sense why this was causing a problem! If you discover why the process.nextTick was needed originally, we can do some trickery with Promises to keep the nextTick, but it doesn't seem necessary.

**Review by derrickmehaffy — APPROVED** [review]
Tested locally and against cloud

**Comment by poulato** [comment]
downgraded to v4.14.6 and still get the error [FATAL] Failed to initialize the connection: Unexpected server response 504
Please help !

**Comment by boroco** [comment]
v4.15.1 working fine.

**Pull request merged**
