### PR TITLE
Upgrade - Add support for React codemods

### PR DESCRIPTION
**Pull request by Convly**
### What does it do?

- Added .jsx and .tsx files support for codemods
- Updated the tests

### Why is it needed?

Allow running react migration for the admin

### How to test it?

Put the following snippet into a codemod (`packages/utils/upgrade/resource/<version>/my-codemod.code.ts`) and execute it for the `getstarted` project. It should update the `src/admin/index.jsx` file 

```ts
import type { Transform } from 'jscodeshift';
import { relative } from 'node:path';

const transform: Transform = (file, api) => {
  const j = api.jscodeshift;
  const root = j.withParser('JSX')(file.source);

  const isReactFile = file.path.endsWith('.jsx') || file.path.endsWith('.tsx');

  if (!isReactFile) {
    return root.toSource();
  }

  const fileName = relative(process.cwd(), file.path);

  console.log(`Found React file: ${fileName}`);

  const buttons = root.findJSXElements('Button');

  console.log(`Found ${buttons.length} buttons in ${fileName}`);

  buttons.forEach((button) => {
    const { openingElement } = button.node;
    const isDisabled = openingElement.attributes.some(
      (attribute) => j.JSXAttribute.check(attribute) && attribute.name.name === 'disabled'
    );

    console.log(`Is disabled? ${isDisabled}`);

    if (!isDisabled) {
      openingElement.attributes.push(
        j.jsxAttribute(j.jsxIdentifier('disabled'), j.jsxExpressionContainer(j.literal(true)))
      );

      console.log('Added the disabled attribute');
    }
  });

  return root.toSource();
};

export default transform;

```

`src/admin/index.jsx` should be transformed as follows:

```diff
import React from 'react';
import { Button } from '@strapi/design-system';

const config = {
  locales: ['it', 'es', 'en'],
};
const bootstrap = (app) => {
  console.log('I AM  BOOTSTRAPPED');

  app.injectContentManagerComponent('editView', 'right-links', {
    name: 'PreviewButton',
    Component: () => (
-      <Button onClick={() => window.alert('Not here, The preview is.')}>Preview</Button>
+      <Button onClick={() => window.alert('Not here, The preview is.')} disabled={true}>Preview</Button>
    ),
  });
};

export default {
  config,
  bootstrap,
};

```

### CODE REVIEW

**Comment by joshuaellis** [comment]
🤩

**Review by christiancp100 — APPROVED** [review]
Code LGTM

**Review by innerdvations — COMMENTED** [review]
Code LGTM but I didn't get a chance to try it out

**Review by christiancp100 — COMMENTED** [review]
QAed it and it works perfectly! Maybe it's worth it adding the test codemod to the examples?

**Comment by Convly** [comment]
> QAed it and it works perfectly! Maybe it's worth it adding the test codemod to the examples?

That's a good idea, I'll do it this afternoon

**Review by innerdvations — APPROVED** [review]

**Pull request merged**
