### PR TITLE
Add Traditional Chinese Translation

### PR DESCRIPTION
**Pull request by rockmandash**
Just Add Traditional Chinese Translation !!!
Will add rest plug-in translation in several days !!!
😝😝😝😝😝

### CODE REVIEW

**Comment by lauriejim** [comment]
Hi @rockmandash You want submit others PR for plugins translation or add new commits on this one ?

**Comment by rockmandash** [comment]
@lauriejim I think I will add new commits, thank you!

**Comment by lauriejim** [comment]
Great, I'm gonna wait your GO when you have finish with that to merge this PR.

**Comment by rockmandash** [comment]
I have finished it.

**Comment by rockmandash** [comment]
image
Oh no, this place didn't show TW option, what should I do?

**Comment by rockmandash** [comment]
I fix it! you can merge now.

**Comment by rockmandash** [comment]
changing tw -> zh makes it work.
Should add available country value in the docs !!!!!

**Pull request merged**
