### PR TITLE
fix: Creating a new locale doesn't pre-fill the non-internationalized fields

### LINKED ISSUE #17700: Non-localizable fields don't keep their value after locale switch and no "fill in from another locale" button in collection types
### Required System information

- Node.js version: 18.12.1
- NPM version: 8.19.2
- Strapi version: 4.12.5
- Database: MySQL 5.7
- Operating system: Ubuntu 22.04.3
- Is your project Javascript or Typescript: Typescript

### Describe the bug
I have two locales in my application: fr (default) and en. I have a `team-member` collection type with 3 non-localizable fields and 1 localizable field. When I fill the FR locale data and save it, then switch to English locale, I don't see the "Fill in from another locale" button and all the fields are empty, forcing me to re-type all the non-localizable fields data.

After filling the EN data and saving, the "Fill in from another locale" button appears.

The problem also exist on edit.

### Steps to reproduce the behavior

1. Create an item in a collection type with localizable fields
2. Fill all fields of the default locale
3. Save it
4. Switch to another locale
5. Non-localizable fields are empty and "Fill in from another locale" button is absent

### Expected behavior

The non-localizable fields should keep the value entered for the default locale, and the "Fill in from another locale" button should be visible.

### Screenshots

Default locale (FR) data entered and saved:

image

After switch to other locale (EN):

image

### Code snippets

N/A

### Additional context
N/A

### LINKED ISSUE #17860: Creating a new locale doesn't pre-fill the non-internationalized fields
### Required System information

- Node.js version: v18.17.1
- NPM version: _idk, almost the latest one_
- Strapi version:  4.12.7
- Database: mysql
- Operating system: linux (ubuntu)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Creating a new locale doesn't pre-fill the non-internationalized fields. But when you refresh the page, they get filled. This is a confusing behavior.

#### Setup strapi instance
1. Create a new strapi project with quickstart
1. Install internationalization plugin.
1. Add a second locale in settings.
1. Create a collection-type with the content-type builder with Internationalization enabled.

#### Reproduce the error
1. Click `Create a new entry` on the collection-type just created.
1. Fill the fields and click save (and publish if was enabled)
1. Click the `locale` dropdown and select another locale what doesn't have an entry yet.
1. See error. All fields are empty, including the non-internationalized fields.
   - [ALTERNATIVE PATH]
   1. See another error. Notice that if you open the `locale` dropdown again, the previous locale is marked as if it didn't have an entry, although it does. 
   1. If here you click the previous locale, it takes you to an empty new page with the locale that should be filled but it's not. 
   1. If you reload, fields are also filled now. But the page is still `Create an entry` instead of the normal editing view.
1. Reload the page
1. The non-internationalized fields are magically filled now. And the `locale` dropdown displays the correct state for the translations.

### Expected behavior

The content of the page before and after reloading should be exactly the same. 

Meaning that:
- Non-internationalized fields are pre-filled when creating a new entry.
- The `locales` dropdown should display the correct state for the translations at all time.

### Screenshots

I made a video :)

[screen-capture.webm](https://github.com/strapi/strapi/assets/12821361/a1d4d66b-ad0a-425c-9018-adcc8f207d3d)

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

These are the dependencies I have installed:

```json
"dependencies": {
  "@creazy231/strapi-plugin-apollo-sandbox": "0.0.13",
  "@strapi/plugin-graphql": "4.12.7",
  "@strapi/plugin-i18n": "4.12.7",
  "@strapi/plugin-seo": "1.9.2",
  "@strapi/plugin-users-permissions": "4.12.7",
  "@strapi/provider-upload-local": "4.12.7",
  "@strapi/strapi": "4.12.7",
  "mysql": "2.18.1",
  "strapi-plugin-config-sync": "1.1.3",
  "strapi-plugin-multi-select": "1.2.2"
},
```

### PR DESCRIPTION
**Pull request by derrickmehaffy**
## What does it do

fixes #17860 
fixes #17700
Relates to #12538

## Why is it needed

Creating a new locale doesn't pre-fill the non-internationalized fields. But when you refresh the page, they get filled.

#### Recreation:
1. Add a second locale in `settings -> internationalization`
2. Create a collection type with the content-type builder with Internationalization enabled. (You can enable it in advanced settings)
3. Add some fields
4. Add some non-internationalized filled by  unchecking the `Enable localization for this field` option in advanced settings
5. Click Create a new entry on the collection-type just created.
6. Fill in the fields and click save
7. Click the `locale` dropdown and select another locale that doesn't have an entry yet.
7. See error. All fields are empty, including the non-internationalized fields.
   a. See another error. Notice that if you open the `locale` dropdown again, the previous locale is marked as if it didn't have an entry, although it does. 
   b. If you click the previous locale, it takes you to an empty new page with the locale that should be filled but it's not. 
   c. If you reload, fields are also filled now. But the page is still `Create an entry` instead of the standard editing view.
1. Reload the page
1. The non-internationalized fields are magically filled now. And the `locale` dropdown displays the correct state for the translations.

https://www.loom.com/share/29deb7eca88840f6b829894313f18b18?t=12
 
#### Fix:
1. Checkout to this branch fix/prefill-non-internationalized-fields and run the project
2. try again by adding a new field or editing previous fields, you will see that the issue is resolved.

https://www.loom.com/share/737dede941974c209c4f8679ecc7ae1a?sid=21f65051-246d-4cd9-9af0-f5d03be6626d
#### How the fix works:
The error is happening in the try block of `middlewares/addCommonFieldsToInitialDataMiddleware.js` as the value for currentLayout is `null`,  If we add await in getData() then it will be fixed.

---

This PR is a mirror of: https://github.com/strapi/strapi/pull/18386

### CODE REVIEW

**Comment by alexandrebodin** [comment]
@derrickmehaffy can you move this to target main so we only address the 4.15.x issues in 4.15.5 1st. I'll clear the milestone for now

**Comment by derrickmehaffy** [comment]
Ill need to rebase this so don't merge yet

**Comment by derrickmehaffy** [comment]
Ready for review again, sorry for the delay

**Comment by joshuaellis** [comment]
Now we have TS it's easier to understand this fix and I think i need more time to dig deep. Because `dispatch` calls aren't typed to return Promises which probably means something else is going on we perhaps _should not_ be doing and i'd rather solve this properly.

**Comment by derrickmehaffy** [comment]
Building an experimental to test with: https://github.com/strapi/strapi/actions/runs/7119256371

**Comment by pmknk** [comment]
Hey guys! do you know then it will be released? :)

**Comment by pmknk** [comment]
when when when ? :)

**Comment by TithSambath** [comment]
When will this PR be reviewed and merged. ^^

**Comment by derrickmehaffy** [comment]
@joshuaellis I understand the want/need to fix this properly but as it's impacting users and we know that so far this is working can we merge it and look at this later to figure out a more proper way to address it and in the meantime get it working for users?

If we need to validate if this will cause other problems I can generate an experimental and let users test with it for a bit

**Comment by joshuaellis** [comment]
Yeah sorry, can you sort the conflicts out? The file is now in TS iirc, then we can do an experimental, I can write up a JIRA ticket and add a TODO and get the ball rolling 🎳

**Comment by derrickmehaffy** [comment]
@joshuaellis I rebased this on main instead since we aren't using develop anymore (AFAIK) unless something is changing in 4.17 in which case I'll wait til after that release and rebase it on that instead.

**Comment by derrickmehaffy** [comment]
New experimental being generated based on 4.16.2: https://github.com/strapi/strapi/actions/runs/7402447192

**Comment by joshuaellis** [comment]
> @joshuaellis I rebased this on main instead since we aren't using develop anymore (AFAIK) unless something is changing in 4.17 in which case I'll wait til after that release and rebase it on that instead.

I'm worried this will get lost in the re-merger because of the different file extensions. Lets wait to do 4.17.0 release & then merge 👍🏼

**Comment by derrickmehaffy** [comment]
> > @joshuaellis I rebased this on main instead since we aren't using develop anymore (AFAIK) unless something is changing in 4.17 in which case I'll wait til after that release and rebase it on that instead.
> 
> I'm worried this will get lost in the re-merger because of the different file extensions. Lets wait to do 4.17.0 release & then merge 👍🏼 

Sounds good!

**Comment by CyberSteelX** [comment]
Hi, sorry for bothering. May I ask when this issue will be fixed, because I'm not seeing any 'Milestone' for it (and this other issue that I was keeping track of for a similar problem has been closed 😅 https://github.com/strapi/strapi/issues/17837)? Thanks a lot.

**Comment by joshuaellis** [comment]
@derrickmehaffy when you get a chance can you double check the fix please? Then I can approve and we can merge 😄

thank you for your patience.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy when you get a chance can you double check the fix please? Then I can approve and we can merge 😄
> 
> thank you for your patience.

Yup I'll do it this afternoon. Rebase and rebuild the experimental and confirm it fixes the problem.

**Comment by dabal** [comment]
Hi is there the chance that this will be merged into the master/next release?

**Review by joshuaellis — APPROVED** [review]

**Comment by SalahAdDin** [comment]
@joshuaellis Will this be for the new version?

**Comment by joshuaellis** [comment]
Check the milestone.

**Pull request merged**
