### PR TITLE
Added missing dutch translations

### PR DESCRIPTION
**Pull request by bart-webleads**
### What does it do?
Some dutch translations where missing. They have been added.
Also a few bad translations have been fixed.

### CODE REVIEW

**Comment by ronronscelestes** [comment]
hi @bart-webleads! thank you for this addition 🙂
I'm sorry I'm a bit late to answer back, I'm just coming back from days off - the branch seems to have conflicts with `main` now, could you fix the conflicts before I review your work? 🙏

**Comment by bart-webleads** [comment]
Hi,

Will fix and PR again...

Regards,
Bart Lagerweij



Op ma 14 nov. 2022 om 15:50 schreef Julie Plantey ***@***.***

**Comment by bart-webleads** [comment]
Added a new PR, closing this one...

**Comment by bart-webleads** [comment]
Yes, afterwards I was thinking the same...

Met vriendelijke groet,
Bart Lagerweij | ***@***.***



Op wo 16 nov. 2022 om 16:21 schreef Julie Plantey ***@***.***

**Pull request closed without merging**
