### PR TITLE
Allow to overwrite "from" and "replyTo" fields.

### PR DESCRIPTION
**Pull request by MaheshCasiraghi**

### CODE REVIEW

**Comment by epegzz** [comment]
Cool, LGTM 👍

**Comment by alexandrebodin** [comment]
Hi sorry but we merged this PR recently to do the opposite. https://github.com/strapi/strapi/pull/5584

Can you explain why you want the opposite behavior?

**Comment by MaheshCasiraghi** [comment]
@alexandrebodin @epegzz I believe the code of the PR you are referring to (https://github.com/strapi/strapi/pull/5584/commits/b7fd5f28fdf0afd02efc161910953411f677e675) does in fact the opposite of what it intends to do (https://github.com/strapi/strapi/pull/5584).

It clearly gives precedence to defaults set in provider settings over custom values set on a message-by-message basis. Is there anything evident I am not seeing here?

**Comment by alexandrebodin** [comment]
From the comment in the previous PR I think the options.from and options.replyTo are hard coded somewhere before the call and thus doesn't use the config. If we want to fix this correctly we need to fix the hardcoding. I will let you investigate a bit but it might be coming from the email plugin directly.

**Comment by MaheshCasiraghi** [comment]
@alexandrebodin yes, as you correctly point out, the issue is that the role-permissions plugin hard codes these 2 fields, and does not allow to configure them. PR https://github.com/strapi/strapi/pull/5584 for some reason decided to "solve" this issue by force-overwriting the "from" and "replyTo" fields with default values. It is clearly a weird workaround that breaks the functionality of SES-provider, and this issue shall probably be addressed within the scope of role-permissions plugin instead, and the correct functionality of SES-provider reverted.

**Comment by alexandrebodin** [comment]
Hi @MaheshCasiraghi We just merged a PR that refactor this code out so the issue will not exist anymore when we release it :). I'm closing this PR and referencing the fix https://github.com/strapi/strapi/pull/6210

**Pull request closed without merging**
