### PR TITLE
Add Instagram provider

### PR DESCRIPTION
**Pull request by ntsvetkova-roi**
#### Description of what you did:

I am working on a project where Instagram auth provider is mandatory, and I see no way to extend the users-permissions plugin properly to add it. Overriding the files mentioned in the documentation is not fully working: proper translations are missing even for EN locale (the callback input label shows just the message id users-permissions.PopUpForm.Providers.instagram.providerConfig.redirectURL), and the callback itself is not correct - it is /auth/instagram/callback instead of /connect/instagram/callback though it is specified in strapi-plugin-users-permissions/admin/src/components/PopUpForm/index.js. 
The question about new provider integration is already asked here https://github.com/strapi/strapi/issues/891#issuecomment-517947386 but there is no reply. 
Please either consider this PR as a possible enhancement or extend the beta documentation with the proper way to extend the plugin.

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by alexandrebodin** [comment]
@ntsvetkova-roi Hi, we finally merged the latest release with quite a few changes. If you can update your PR it would be awesome !

**Comment by ntsvetkova-roi** [comment]
Hi @alexandrebodin @lauriejim, 

updated the branch with the latest master, added Instagram to the provider listing and created a [PR](https://github.com/strapi/strapi-examples/pull/134) in the examples repo.

**Comment by lauriejim** [comment]
Thank you! I will check that soon as I can!

**Comment by lauriejim** [comment]
Hello! I tested and it works well, thank you.
I just commented your documentation PR.
Can you please apply the update then we will merge your PR.
Thank you.

**Pull request merged**
