### PR TITLE
add language names for Bosnian, Croatian, Macedonian and Serbian

### PR DESCRIPTION
**Pull request by xmak**
### What does it do?

Adds language names for Bosnian, Croatian, Macedonian and Serbian to packages/core/admin/admin/src/translations/languageNativeNames.js

### Why is it needed?

Allow to extend translations for those languages in config.translation in src/admin/app.js

### How to test it?

Add some translations for the languages ba, hr, mk, rs to config.translation, build the admin and check the translations in the admin.

### CODE REVIEW

**Comment by xmak** [comment]
Is there any progress on this pull request?

**Review by markkaylor — APPROVED** [review]
Sorry for the delay and thanks for the ping :) 

LGTM

**Comment by aposhtol** [comment]
So, where are the actual translations? :)

**Comment by xmak** [comment]
> So, where are the actual translations? :)

I didn't do the translation as I'm currently lacking the resources to do it. I just added the language names so that developer can put their own translations when needed. Once this pull request gets accepted, you will be able to make your own translations in  src/admin/app.js, e.g. like this:

`
const translation_hr = require("/src/admin/translations/hr.json");

const config = {
  locales: [
    'hr',
  ],

  translations: {
    'hr': {
      ...translation_hr,
      Article: 'Članak',
      Category: 'Kategorija',
      "content-manager.containers.ListPage.table-headers.title": 'Naslov',
      "content-manager.containers.ListPage.table-headers.parentPage": 'Nadređena stranica',
      "content-manager.containers.ListPage.table-headers.locales": 'Prijevodi',
    }
  }
};

const bootstrap = (app) => {
  console.log(app);
};

export default {
  config,
  bootstrap,
};
`

Note that in the above code I'm also importing translations from the file gkr-backend/src/admin/translations/hr.json which I copied from the english translation. Here's a sample:

`
{
  "app.utils.filters": "Filteri",
  "content-manager.pages.ListView.header-subtitle": "{number, plural, =0 {pronađeno # zapisa} one {pronađen # zapis} other {pronađeno # zapisa}}",
  "content-manager.HeaderLayout.button.label-add-entry": "Novi zapis",

  

   "Analytics": "Analytics",
   "Auth.components.Oops.text": "Your account has been suspended.",
   "Auth.components.Oops.text.admin": "If this is a mistake, please contact your administrator.",
   "Auth.components.Oops.title": "Oops...",
   "Auth.form.active.label": "Active",
...
`

**Comment by alexandrebodin** [comment]
> [!IMPORTANT] 
> With the release of Strapi 5, we have lifted the code freeze. To ensure we can effectively review and assist with contributions, we are now only accepting PRs targeting version 5 (the develop branch).<br/> 
> As your PR targets version 4, it has been automatically closed. However, we would greatly appreciate it if you could update your contribution to align with version 5 and resubmit!

**Pull request closed without merging**
