### PR TITLE
[WIP] Fixed issues with required, unique, and default on bookshelf hook

### LINKED ISSUE #1189: Strapi does not properly use Unique field type with Bookshelf
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 6.0.0
- **Strapi version**: 3.0.0-alpha.12.1.3
- **Database**: 10.2.14-MariaDB
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**

When setting a field as `unique` and using MySQL, strapi still allows for duplicate values to be written to the database. (Note that strapi does not create and apply a `UNIQUE` key on the specified column in the database)

**Steps to reproduce the problem**

Using MySQL or MariaDB:
Create a field in the content builder and assign the option `unique`, then attempt to save a value multiple times. Strapi will write multiple entries without throwing an error.

**What is the expected behavior?**

Strapi should (for MySQL, unsure about postgres) create and assign a UNIQUE key value to the specified field.

**Suggested solutions**

---

- [x] I'm sure that this feature hasn't already been referenced.

### PR DESCRIPTION
**Pull request by crashlab**
⚠️ This is a "Work In Progress" PR ⚠️

**My PR is a:**
- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #1189 #2888
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

**Main update on the:**
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

**Manual testing done on the following databases:**
- [ ] Not applicable
- [ ] MongoDB
- [x] MySQL
- [ ] Postgres
- [ ] SQLite

**Description:**

The fix address the following issues:

1. When creating a new model with a field "required", the field is not set as "not null"; 
2. When creating a new model with a field "unique", the field is not set as "unique"; 
3. When you add a new field "unique" into a previously created model, the field is not set as "unique"; 
4. When you change the "unique" value of a field in a model that was previously created it 
 will not update the table on the database;
5. When setting a default value, setting the columns default value;
 
⚠️ Postgres queries missing, check the code changes and add it.  ⚠️
⚠️ Default code has not been added ⚠️

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
If anyone wishes to help on this PR, I've spoken with @crashlab on Slack.

ToDo:
* Add Postgres bookshelf/knex queries
* Add SQLite queries
* Add error checking for setting unique with existing data that has duplicate data
* For required, take the `default` and apply that instead of just `not null`

**Comment by derrickmehaffy** [comment]
@lauriejim when talking to @crashlab on slack, he/she doesn't have the time to finish this PR and I don't have the skills but as I have said before, getting these 3 "metadata" options on bookshelf in my opinion is quite important as currently none of these are being used on bookshelf properly.

- Required
- Unique
- Default

(Min/Max don't have constraint options on any of the bookshelf DBs, thus those will need to be handled by strapi validation layer that doesn't exist yet.)

**Comment by lauriejim** [comment]
I'm agree, we have to manage well these points.
We can not finish to work on every PR people start (because there is no end if we start to work like that.)
We will work on this point when this topic will became hot for us. We are actually working on man topic and will do our best to make that work correctly soon as possible.

**Comment by derrickmehaffy** [comment]
> I'm agree, we have to manage well these points.
> We can not finish to work on every PR people start (because there is no end if we start to work like that.)
> We will work on this point when this topic will became hot for us. We are actually working on man topic and will do our best to make that work correctly soon as possible.

Understood @lauriejim I think in this case, these 3 are important.

**Comment by derrickmehaffy** [comment]
Closing this as very likely the Strapi team will start from scratch

**Pull request closed without merging**
