### PR TITLE
Update koa-ip version

### PR DESCRIPTION
**Pull request by derrickmehaffy**
#### Description of what you did:

~~This PR is a WIP as testing needs to be done with `purest` Based on the changelog there are breaking changes (however the documentation related to them is currently offline): https://github.com/simov/purest/blob/master/CHANGELOG.md#v300-20160717~~

Changed to only update koa-ip, purest will come later.

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [x] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
I will need some help testing purest as I can't even get Strapi working properly with 3rd party auth providers locally without the update >.>

**Comment by alexandrebodin** [comment]
@derrickmehaffy I'll try to have a look at the end of the week ;)

**Comment by alexandrebodin** [comment]
@derrickmehaffy Can you make a split PR so we can merge koa-ip alone. 

Purest seems to have a lot of [breaking changes](https://github.com/simov/purest/blob/master/CHANGELOG.md) and it diserves a bit more care to upgrade ;)

**Comment by derrickmehaffy** [comment]
@alexandrebodin done

**Comment by alexandrebodin** [comment]
@derrickmehaffy can you re-run yarn  ? looks like there are a lot of unintended changes ?

**Comment by derrickmehaffy** [comment]
@alexandrebodin that's the last thing I did before I committed was `yarn setup`

**Pull request merged**
