### PR TITLE
[WIP] Make prod and staging database.json files more dynamic

### PR DESCRIPTION
**Pull request by vaskort**
**My PR is a:**
💅 Enhancement

**Main update on the:**
Framework

Hey guys :)

It seems that the `connector` and `client` properties in database.json files for prod and staging were hardcoded. 

I know that its easy to edit them after you initialised your instance but if you want to dockerize your Strapi this becomes a little more difficult. 

So for instance if you initialised your Strapi instance to use MySQL your production and staging  `database.json` were incorrectly set up with `"client": "mongo"` and `"connector": "strapi-hook-mongoose"`.

**What I did:**
I used the settings that were used to create the develop `database.json` to create the staging and production ones.

Let me know your thoughts, if you think this is something valuable and/or want me to change something in my code. Open to suggestions :)

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello @vaskort thank you to submit a PR.
Yes there is an other point, mongoose and bookshelf not need same settings and options.

**Comment by lauriejim** [comment]
You will have to define settings by connectors.
@vaskort Can you make an update about that please. Then I will be able to test it.
Thank you

**Comment by vaskort** [comment]
Hey @lauriejim, sorry for the delay :(
I’m away without a laptop. I will update it in about 2 weeks.

**Comment by lauriejim** [comment]
@vaskort Okay 👍

**Comment by lauriejim** [comment]
Hello @vaskort! Hope your 2 weeks was good ;)

**Comment by vaskort** [comment]
@lauriejim hey mate! Yeah it was great. 

Going to get update this asap.

**Comment by lauriejim** [comment]
Happy to read that!

**Comment by vaskort** [comment]
Sorry for the delay mate - we were releasing something with Strapi at work and didn't have time. 

> Hello @vaskort thank you to submit a PR.
> Yes there is an other point, mongoose and bookshelf not need same settings and options.

Are you sure for the above? I remember that I tested it with a MongoDB and a MySQL database. 

I will test again though.

**Comment by lauriejim** [comment]
Yap, it's an empty object by default with **SQL** databases

**Comment by maturanomx** [comment]
Two commentaries from my side:

1. The history commit is really noise and have garbage. Would be nice a clean commit.
2. Totally agree with this improvement. I had seen a lot of report issues due to the differences of configurations between environments; this sill avoiding some of those... and been all the same, this make evident that in reality **there is not need for different files for environment**. Hope see just one file in a near future :)

**Comment by lauriejim** [comment]
Please check this PR https://github.com/strapi/strapi/pull/2698
We will merge this fix soon as possible.

**Pull request closed without merging**
