### PR TITLE
fix: image URL in README.md

### PR DESCRIPTION
**Pull request by iamdarshshah**
Updated logo image URL

> Screenshot:
Strapi

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Thanks @iamdarshshah, closing as the image is already up to date

**Comment by iamdarshshah** [comment]
Hello @alexandrebodin 

It looks like, the issue still exists. Can you please have a look at it again?
> Screenshot
error

**Comment by lauriejim** [comment]
Hum looks good on my side... The image is hosted on GitHub so that's weird.
Cache issue?

**Comment by iamdarshshah** [comment]
@lauriejim It seems the issue is common across the different browsers. It could not be related to Cache. Maybe something else. Can you please share the screenshot?

Thanks 👍

**Comment by lauriejim** [comment]
image
Just tried on my mobile - looks good.

**Comment by iamdarshshah** [comment]
Okay, cool! No problem... If it works fine then there is no need for updating it. Still don't know why it's not working for me :confused: 

Will try to look for the solution to this issue. Anyways! Thank you :+1:

**Comment by alexandrebodin** [comment]
Let us know if this comes from a specific browser so we can fix it :D

**Comment by iamdarshshah** [comment]
@alexandrebodin 
I have tried with a different system and with different browsers. Here are the results: 

> I don't know what might be the reason behind this.  The issue still exists across different browsers.

**Screenshots:**

**_1. Safari_**
Safari

**_2. Chrome_**
chrome

**_3. Opera_**
Opera

`(P.S - Updated the PR info with a screenshot that includes changes that has been updated through this PR.)`

**Comment by iamdarshshah** [comment]
This might happen due to the fact that Amazon AWS serves content to specific locations or rather I would say, It will work for certain locations only. Due to which I can't access this particular file. Tried visiting URL directly and got this response:

Response


 We can update the URL by `https://strapi.io/assets/strapi-logo.svg`, which will directly point to the static files associated with the `Strapi` website. This will resolve this particular issue.

 would appreciate your thoughts/ideas on this @alexandrebodin

**Comment by alexandrebodin** [comment]
@iamdarshshah You can actually use this one instead so it is the right one :D https://strapi.io/assets/strapi-logo-dark.svg

**Comment by iamdarshshah** [comment]
@alexandrebodin Sure, Updating that! Thanks 👍

**Comment by iamdarshshah** [comment]
@alexandrebodin Should I open new PR for the updating image URL?

**Comment by alexandrebodin** [comment]
@iamdarshshah I'll reopen this one so you can update 👍

**Comment by iamdarshshah** [comment]
Thanks @alexandrebodin 👍 , I have updated the image URL. You can review it now :)

**Pull request merged**
