### PR TITLE
Fixed click event on non-repeatable empty component

### PR DESCRIPTION
**Pull request by akhilmhdh**
### What does it do?

- Fixed the onClick event of a non-repeatable component on its empty state.
- Made the whole area clickable

### Why is it needed?

Admin panel better user experience

### Related issue(s)/PR(s)

#8640 #8608 - one part

### CODE REVIEW

**Review by soupette — DISMISSED** [review]
LGTM

**Comment by soupette** [comment]
@akhilmhdh thanks a lot for your PR can you make sure the DCO checks so we can merge it?

**Comment by akhilmhdh** [comment]
@soupette Done 😄 , sorry from my side.

**Review by soupette — APPROVED** [review]
LGTM

**Pull request merged**
