### PR TITLE
Update Dutch Translation and Typos [NL]

### PR DESCRIPTION
**Pull request by MattieBelt**
After @lexbeelen initiative (#5506), here is a complete update of all dutch translation keys.

There's only one thing I'm not sure about:

Collectie Type / Collectietype / Collectie type
Enkel Type / Enkeltype / Enkel type (Is this even the best translation, any suggestions?)

Please correct me if I'm wrong. (I'm dyslectic)

### CODE REVIEW

**Comment by MattieBelt** [comment]
@JelmerV-WFC & @lexbeelen can you review this?

**Comment by JelmerV-WFC** [comment]
I understand why you are not sure about these ones. If I had to choose between those 3 I would say choose: `Collectie type` and `Enkel type`.

Enkel type sounds a bit weird, but can't think about a better description right now.

**Comment by lexbeelen** [comment]
I prefer for 
> Collectie type

**Comment by MattieBelt** [comment]
Okay will use `Collectie type` and `Enkel Type`


I agree with:
> Enkel type sounds a bit weird, but can't think about a better translation right now.

**Comment by MattieBelt** [comment]
@alexandrebodin ready to be merged

**Pull request merged**
