### PR TITLE
Upgrade bookshelf 1.2.0 and match knex version (~0.21.0)

### LINKED ISSUE #7437: Knex version does not match bookshelf
https://github.com/strapi/strapi/blob/8d0c6848ba421680570e974e5d8606314735de3e/packages/strapi-generate-new/lib/utils/db-client-dependencies.js#L19

https://github.com/strapi/strapi/blob/97922f99ae858e1e3f4f792bb8d6a829adb82649/packages/strapi-connector-bookshelf/package.json#L29

### PR DESCRIPTION
**Pull request by XuluWarrior**
This is an updated/recreated version of #7479

fixes #7437

### CODE REVIEW

**Comment by XuluWarrior** [comment]
Same question as in #7479:

Dwe really wanted the knex peer dependencies to be more narrow than those used by bookshelf itself (>=0.15.0 <0.22.0). Is there a reason not to be more permissive?

**Review by tomsaleeba — COMMENTED** [review]
Is it possible to move `knex` from `peerDependencies` into `dependencies` so users of strapi no longer have to specify knex directly (and manage the version)?

I'm sure there was a reason why this wasn't done, but I can't think what it might be. I'm sure I'm about to learn something new here.

**Comment by derrickmehaffy** [comment]
> Is it possible to move `knex` from `peerDependencies` into `dependencies` so users of strapi no longer have to specify knex directly (and manage the version)?
> 
> I'm sure there was a reason why this wasn't done, but I can't think what it might be. I'm sure I'm about to learn something new here.

@alexandrebodin @Convly @petersg83

**Comment by alexandrebodin** [comment]
> Is it possible to move `knex` from `peerDependencies` into `dependencies` so users of strapi no longer have to specify knex directly (and manage the version)?
> 
> I'm sure there was a reason why this wasn't done, but I can't think what it might be. I'm sure I'm about to learn something new here.

Hi. We actaully can't do that because knex requires to be installed in the same location as the database driver it uses. it is a known issue with knex & hasn't be resolved as far as I know.

**Comment by alexandrebodin** [comment]
I'll be closing this pr which is quite outdated so we can make the update on our side :) Thak you anyway !

**Pull request closed without merging**
