### PR TITLE
Run CLI from a function call

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

Instead of the `strapi` command running the Commander program directly from executing a script, provide a `runStrapiCommand` function and have the `strapi` CLI script pass the args to it.

### Why is it needed?

The existing structure of the CLI is that we run a script directly rather than exporting a module, which makes testing it difficult.

Our existing tests target the underlying actions called by the CLI, but are not testing the setup of the Commander commands themselves, such as which inputs are accepted, how they are parsed, or any writes that Commander itself may do somewhere other than stdout or stderr.

It also gives us the ability to customize the Commander command that will be run if we ever need that (such as to redirect its output)

#### Other ideas

- add cli integration tests that use `exec` to test the CLI through the shell, but they would require more work to set up, and run much slower. Plus `exec` itself may have further issues depending on the environment, interfere with CI, etc. Could be nice for the future but not a reasonable alternative to this
- we should make the command builder more modular, but that's a task for another day :)

### How to test it?

- `strapi` CLI command should work **_exactly_** as before with no changes under any circumstances
- Strapi code should now have access to `runStrapiCommand(argv)` importable from `strapi/lib/commands` to run commands programmatically
- a simple test has been provided to demonstrate we can now test that CLI commands actually exist or not (rather than only testing the underlying code called by those commands)

### CODE REVIEW

**Comment by innerdvations** [comment]
I will add a simple test of the `help` command to test that it works and how it will be used.

**Review by Convly — DISMISSED** [review]
You'll need to update with `main`, but other than that, LGTM. Nice addition :slightly_smiling_face:

**Comment by StrapiShaun** [comment]
@innerdvations should this part be documented: "Strapi code should now have access to runStrapiCommand(argv) importable from strapi/lib/commands to run commands programmatically" ?

**Comment by innerdvations** [comment]
> @innerdvations should this part be documented: "Strapi code should now have access to runStrapiCommand(argv) importable from strapi/lib/commands to run commands programmatically" ?
I'm not sure if it's something we should consider publicly available at this point. Perhaps if it gets the full refactoring next year :)

**Comment by StrapiShaun** [comment]
> > @innerdvations should this part be documented: "Strapi code should now have access to runStrapiCommand(argv) importable from strapi/lib/commands to run commands programmatically" ?
> 
> I'm not sure if it's something we should consider publicly available at this point. Perhaps if it gets the full refactoring next year :)

OK that sounds like a plan!

**Comment by innerdvations** [comment]
I'll need to basically rewrite this once we merge features/deits. After I have time to do that I'll reopen this.

**Comment by alexandrebodin** [comment]
@innerdvations Closing for now as it will be redone

**Pull request closed without merging**
