### PR TITLE
Add: Cloud link in README file

### PR DESCRIPTION
**Pull request by Mcastres**
### What does it do?

Simply adds a cloud link in the README.

### Why is it needed?

Give more visibility for our new upcoming service.

### CODE REVIEW

**Review by gu-stav — APPROVED** [review]
Why not 🤷🏼 I think I'd like to see @derrickmehaffy s approval here too, before this is merged just to be sure.

**Review by nathan-pichon — APPROVED** [review]
Thanks ! LGTM

**Comment by Mcastres** [comment]
When do you think this could be merged @nathan-pichon? :)

**Comment by gu-stav** [comment]
Anytime :p

**Pull request merged**
