### PR TITLE
S3 File Upload larger than 5MB invalid file url

### PR DESCRIPTION
**Pull request by HonzaVrkota**
### What does it do?

When upload file more than 5MB with AWS S3 provider it returns file location without bucket and endpoint, it returns only name of the file starts with slash. `ex: /img_hash456.png`.

Create condition that check if data.location starts with "/", if starts add protocol, bucket and endpoint before file name and return as file url.

 - packages\providers\upload-aws-s3\src\index.ts lines 99 - 101

### Why is it needed?

Invalid url when file is larger than 5MB. 

### How to test it?

check test upload-aws-s3.test.ts - Should add to the url the https protocol, bucket and endpoint if it is missing

### Related issue(s)/PR(s)

issue: https://github.com/strapi/strapi/issues/15144

### CODE REVIEW

**Comment by jhoward1994** [comment]
Hi and thanks for the PR

I'm struggling to replicate this behaviour. I'm using the aws-s3 provider with an upload larger than 5MB (10MB) both in a folder and at the root level. In both cases `data.location` is the correct full s3 URL (see attached video).

Is there something specific about your set up that could be causing this?

https://github.com/strapi/strapi/assets/48524071/3944765e-a864-459c-b8f6-62014c97ccad

**Comment by HonzaVrkota** [comment]
> Hi and thanks for the PR
> 
> I'm struggling to replicate this behaviour. I'm using the aws-s3 provider with an upload larger than 5MB (10MB) both in a folder and at the root level. In both cases `data.location` is the correct full s3 URL (see attached video).
> 
> Is there something specific about your set up that could be causing this?
> 
>  Screen.Recording.2023-08-07.at.11.16.43.mov

Hi,

I'm using aws-s3 provider, but connected to [Backblaze](https://www.backblaze.com/) - Configuration for S3 compatible services.
This is my config:
```
      providerOptions: {
        s3Options: {
          sizeLimit: 250 * 1024 * 1024, // 256mb in bytes
          accessKeyId: env("SCALEWAY_ACCESS_KEY_ID"),
          secretAccessKey: env("SCALEWAY_ACCESS_SECRET"),
          endpoint: env("SCALEWAY_ENDPOINT"), // e.g. "s3.fr-par.scw.cloud"
          params: {
            ACL: env("AWS_ACL", "public-read"),
            signedUrlExpires: env("AWS_SIGNED_URL_EXPIRES", 15 * 60),
            Bucket: env("SCALEWAY_BUCKET"),
          },
        },
      },
```

**Comment by HonzaVrkota** [comment]
@jhoward1994 any update?

**Comment by alexandrebodin** [comment]
> [!IMPORTANT] 
> With the release of Strapi 5, we have lifted the code freeze. To ensure we can effectively review and assist with contributions, we are now only accepting PRs targeting version 5 (the develop branch).<br/> 
> As your PR targets version 4, it has been automatically closed. However, we would greatly appreciate it if you could update your contribution to align with version 5 and resubmit!

**Pull request closed without merging**
