### PR TITLE
Wait for websocket to open only once in transfer pull

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?

- Fixes transfer pull, as it was not working
- We should wait for websocket to open only once

### How to test it?

- Run transfer pull it should work

### Related issue(s)/PR(s)

related to #16473

### CODE REVIEW

**Review by christiancp100 — APPROVED** [review]
LGTM 🍝  + It's QAed

**Review by innerdvations — COMMENTED** [review]
I've tried everything and still can't seem to get it to run a pull transfer, it always just hangs forever. Anyone else having this trouble?

**Comment by marcoautiero** [comment]
I would like to test this one together with the fix provided here https://github.com/strapi/strapi/pull/16634

Is it in some way possible?

**Comment by marcoautiero** [comment]
by the way, it works for me

**Pull request merged**
