### PR TITLE
Fix : Media Library List View navigation

### LINKED ISSUE #17564: Folder Links Not Clickable In List View
## Bug report

- Node.js version: Not applicable
- NPM version: Not applicable
- Strapi version: Latest
- Database:
- Operating system: Linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug
The Folder Links in the Media Library is not clickable in the List View .
 

### Steps to reproduce the behavior

1. Go to Media Library
2. Create a new Folder
3. Switch to List View
4. Click on any of the folder links
5. We are not be navigated to the target folder.

### Expected behavior
We should be able to navigate to the folder

### PR DESCRIPTION
**Pull request by noobCode-69**
### What does it do?

The PR fix the issue of Folder links not working in the Media Library page , in the List view
The issue is related to issue number  #17564

### Why is it needed?

It is needed since we want to navigate to folders in List View also.

### How to test it?
To test the issue do the following things
1. Go to Media Library
2. Create a new Folder
3. Switch to List View
4. Click on any of the folder links

We are not be navigated to the target folder.

Fixes #17564

### CODE REVIEW

**Comment by noobCode-69** [comment]
I would like to discuss the solution here. 
Right now in you codebase you are using this approach to generate a link for the folder (In List View only)

```jsx
onChangeFolder={(folderID) => push(getFolderURL(pathname, query, folderID))}
```
But here `getFolderURL` will never generate the correct URL , to generate correct URL you have to use it like this

```jsx
onChangeFolder={(folderID, folderPath) =>
    push(getFolderURL(pathname, query, { folder: folderID, folderPath }))
}
```
This will generate the correct link. 
After these changes the navigation is working fine.

**Comment by noobCode-69** [comment]
Can someone please review this up?

**Comment by noobCode-69** [comment]
hey @gu-stav can you review and merge this!

**Review by gu-stav — APPROVED** [review]
Thank you! 🌻

**Pull request merged**
