### PR TITLE
fix: relations are not returned in the correct order

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?

When removing or adding a relation in an entity, other entities from the same Content Type were having that same relation reordered.

**Cause**: We were updating the order of the other entities when we should only be updating the inverse order.

**Context**: Given a bidirectional  relation between Author -> Article, the join table:

	| author_id | article_id | article_order | author_order
	
	- `article_order` is the order of articles in author entities
	- `author_order` is the order of authors in article entities

We keep both orders because both sides of the relation. So when updating an author and adding article relations, we update both the `article_order` but also the `author_order` (the inverse side).

Before the SQL query to update the order values was:

```sql
UPDATE
  :joinTable: as a,
  (
    SELECT
      id,
      ROW_NUMBER() OVER ( PARTITION BY :joinColumn: ORDER BY :orderColumn:) AS src_order,
      ROW_NUMBER() OVER ( PARTITION BY :inverseJoinColumn: ORDER BY :inverseOrderColumn:) AS inv_order
    FROM :joinTable:
    WHERE :joinColumn: = :id OR :inverseJoinColumn: IN (:inverseRelIds)
  ) AS b
SET :orderColumn: = b.src_order, :inverseOrderColumn: = b.inv_order
WHERE b.id = a.id;
```

Problem was, all matches with `:inverseJoinColumn: IN (:inverseRelIds)` (other entities using the same relation) were having the src_order updated too.

To fix this the query was splitted in two:
```sql
-- Update order column
  UPDATE :joinTable: as a,
  (
    SELECT
      id,
      ROW_NUMBER() OVER ( PARTITION BY :joinColumn: ORDER BY :orderColumn:) AS src_order,
    FROM :joinTable:
    WHERE :joinColumn: = :id
  ) AS b
  SET :orderColumn: = b.src_order
  WHERE b.id = a.id;

-- Update inverse order column
  UPDATE :joinTable: as a,
  (
    SELECT
      id,
      ROW_NUMBER() OVER ( PARTITION BY :inverseJoinColumn: ORDER BY :inverseOrderColumn:) AS inv_order
    FROM :joinTable:
    WHERE :inverseJoinColumn: IN (:inverseRelIds)
  ) AS b
  SET :inverseOrderColumn: = b.inv_order
  WHERE b.id = a.id;
```

We are introducing yet another db request, but I don't see any other way around this problem.

### How to test it?

See tests.

### Related issues
Fixes https://github.com/strapi/strapi/issues/16961

### CODE REVIEW

**Comment by jhoward1994** [comment]
This looks good and seems to be working for me. I'm just trying to get my head around the failing tests. It looks to me like we might have had broken expectations before as we were expecting relations to be reordered when they shouldn't be. wdyt?

e.g. https://github.com/strapi/strapi/blob/04bedb1b543e9980d29dea3b89e21494e973a2a0/api-tests/core/content-manager/api/relations.test.api.js#L338

**Comment by Marc-Roig** [comment]
@jhoward1994  I think there is another issue with ordering with this implementation, I am refactoring it just now.

**Comment by Marc-Roig** [comment]
@jhoward1994 sorry for the changes, now it should be working ok. And the tests were ok (just that relations are returned in reverse order in the content-manager api)

I will add additional tests so this issue does not happen again :)

**Review by markkaylor — DISMISSED** [review]
I reproduced the bug on main as described in the issue (except I never saw the duplication described over there just the issue with ordering). 

Tested again here on your branch and it looks good to me! 🎈

**Comment by JohnGale87** [comment]
First off, thanks for working on this issue!

> We are introducing yet another db request, but I don't see any other way around this problem.

As you've already split it up and written tests for it, this could be a moot point but IF number of database requests is really a concern here then I think you could have left it as 1 request but with a slightly more complex WHERE clause.


Old (broken):
```sql
WHERE :joinColumn: = :id OR :inverseJoinColumn: IN (:inverseRelIds)
```

New (fixed?):
```sql
WHERE :joinColumn: IN (SELECT DISTINCT :joinColumn: FROM :joinTable: WHERE :inverseJoinColumn: IN (:inverseRelIds))
```

I actually think splitting it up was the right thing from a readability perspective but like I said, if number of  database requests is really a concern then the above SQL should resolve the bug.

**Comment by Marc-Roig** [comment]
Hello!! Love to have DB query conversations here 🚀 

I will explore your solution, it looks like a clean solution 😃  my only concern with it would be having too many row hits. We would be reordering many more rows than strictly necessary.

Thanks a lot for the proposal, I will test and analyze it!!

**Comment by derrickmehaffy** [comment]
I know this is beyond your control Marc but given the constant increases in queries we see, I seriously wish we had the option to disable relational ordering for those that don't need/want it.

**Comment by Marc-Roig** [comment]
I can not but only agree with you on this @derrickmehaffy , backend-wise it wouldn't be a big trouble to do that, @joshuaellis do you think we could disable reordering the whole app in a clean way?

Using a config, or just looking if the loaded relations have the order field.

We have other plans in mind to reduce number of queries you might like also!, like only updating the fields the user updates, not the whole entry.

**Comment by joshuaellis** [comment]
> I can not but only agree with you on this @derrickmehaffy , backend-wise it wouldn't be a big trouble to do that, @joshuaellis do you think we could disable reordering the whole app in a clean way?
> 
> Using a config, or just looking if the loaded relations have the order field.

We have discussed this in FE syncs and we previously didn't want to support this because it felt like a door way to having to handle this with lots of nuanced ui features that end up making the application a lot more complicated to manage in the long run. However, if you're able to create a solid argument as to why we should – user data / interviews as well application data then that would give a stronger argument to do this 😄

**Review by markkaylor — APPROVED** [review]

**Comment by Marc-Roig** [comment]
@joshuaellis was not aware of the technical complexity of it.
The only argument would be performance. Reordering greatly increases the number of database requests we do, and it comes to a price if you have limited resources or you want to scale your app.

I would say it would be very nice to have a toggle for the feature, but if it involves great complexity we could find other ways.

In V5 we will refactor relations and for sure we will improve the performance of reordering. 
Also, we have other big things in mind that will improve performance even more (updating entities based on diffs and not the full entity)

**Comment by joshuaellis** [comment]
> @joshuaellis was not aware of the technical complexity of it. The only argument would be performance. Reordering greatly increases the number of database requests we do, and it comes to a price if you have limited resources or you want to scale your app.
> 
> I would say it would be very nice to have a toggle for the feature, but if it involves great complexity we could find other ways.
> 
> In V5 we will refactor relations and for sure we will improve the performance of reordering. Also, we have other big things in mind that will improve performance even more (updating entities based on diffs and not the full entity)

IMHO lets be reactive on this one unless we have some reliable metrics to be proactive. I'm not opposed to it completely, just trying to walk the line between value and complexity 😄

**Comment by derrickmehaffy** [comment]
Indeed, the largest reason is performance. It was largely unexpected to have a minor release to add a new feature and suddenly performance takes a massive hit to users with no option to turn it off.

I am hopeful the v5 will allow us to fix the performance issues but there is a concern that performance will get worse due to the added complexity of the dimensions.

**Comment by joshuaellis** [comment]
> Indeed, the largest reason is performance. It was largely unexpected to have a minor release to add a new feature and suddenly performance takes a massive hit to users with no option to turn it off.
> 
> I am hopeful the v5 will allow us to fix the performance issues but there is a concern that performance will get worse due to the added complexity of the dimensions.

Ideally we'd have a test-suite of some sort to monitor performance 🤔 it's totally an understandable area of concern.

**Comment by mpuxted** [comment]
> It was largely unexpected to have a minor release to add a new feature and suddenly performance takes a massive hit to users with no option to turn it off.

Having a way to turn relation ordering off for the inverse relation would be more helpful to us than a blanket off or on. In all of the many to many relations we have, the inverse order doesn't matter to us and so just adds extra complexity in the code and UI.

**Comment by Marc-Roig** [comment]
@mpuxted completely, I think that is a valid case and something we will seriously take into consideration now that we plan to refactor relations. I can not give exact dates at the moment but  it's something we will eventually do.

**Pull request merged**
