### PR TITLE
Features/typescript example

### PR DESCRIPTION
**Pull request by ascension**
### What does it do?

Added an example that uses Typescript.

### Why is it needed?

To provide users with an example on how to setup/configure Strapi to use typescript.

### How to test it?

- Clone this branch
- `cd examples/typescript/`
- `yarn && yarn develop`

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/pull/10614

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@alexandrebodin / @petersg83 would this be better to put in https://github.com/strapi/strapi-examples ?

**Comment by soupette** [comment]
> @alexandrebodin / @petersg83 would this be better to put in https://github.com/strapi/strapi-examples ?

I don't think so this repo is not maintained anymore, is it?

**Comment by alexandrebodin** [comment]
Yes that's the good repo, but we won't have anytime to move forward on that for v3 but for v4

**Comment by derrickmehaffy** [comment]
Hi 👋  
We now have released the `v4`. As of now, the `v3` is in maintenance mode for 6 months. We will only be fixing critical and security issues on v3 from now on. 
I will go ahead and close this PR. Thank you for contributing to Strapi 🔥

**Pull request closed without merging**
