### PR TITLE
Add note about docker to deployment documentation

### PR DESCRIPTION
**Pull request by MartinMuzatko**
**My PR is a:**
- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix #issueNumber
- [x] 💅 Enhancement
- [ ] 🚀 New feature

**Main update on the:**
- [ ] Admin
- [X] Documentation
- [ ] Framework
- [ ] Plugin

**Manual testing done on the follow databases:**
- [X] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres

**Description:**

Currently there is no note of docker in the documentation. Maybe this is because the docker image is a bit older. I think this is missing from the docs.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Bad @lucaperret 😛 
```
FROM node:11.1.0-alpine
```

**Comment by MartinMuzatko** [comment]
1. Alpine is not ARM friendly
2. Node 11 is unstable

After this, I'm helping with the docker repo ;)

**Comment by derrickmehaffy** [comment]
@MartinMuzatko Awesome, is this official? If not *cough* @lauriejim get him in there to help. 😆

**Comment by MartinMuzatko** [comment]
NodeJS marks every odd numbered release number as unstable: https://github.com/nodejs/Release#release-plan

That means 6,8,10,12 are considered as stable and 7,9,11 unstable.

That does not actually mean that they are not working or broken, they just use odd numbers as experimental releases.

**Pull request merged**
