### PR TITLE
[WIP] Dependencies upgrade for packages: strapi, admin, utils and generate-api

### PR DESCRIPTION
**Pull request by gustawdaniel**

### CODE REVIEW

**Comment by gustawdaniel** [comment]
In admin there is problem with updates:

```
 sanitize.css   ^4.1.0  →  ^12.0.1   
 style-loader  ^0.23.1  →   ^1.2.1  
```

that provides to fail of test:

```
yarn test:front packages/strapi-admin/admin/src/components/Webhooks/HeadersInput/tests/index.test.js --coverage=0
```

**Comment by gustawdaniel** [comment]
Changes in the mentioned packages require manual review and changes in test because of tests suspect constant structure of generated HTML files, when update in these packages change it a lot, but probably these changes are acceptable if will be assessed by someone from your core team.

**Comment by gustawdaniel** [comment]
It works after `npm install` but fails after `yarn`.

**Comment by gustawdaniel** [comment]
HeadersInput fixed. Now it failing for:

```
packages/strapi-helper-plugin/lib/src/components/PopUpWarning/tests/index.test.js
```

**Comment by alexandrebodin** [comment]
Hi, I'm sorry but this PR is reallly too big to be reviewed as it changes so many dependencies. Any major version bump must be submitted separatly so we can review the specific changelog before accepting them. This would be too long for us to review right now

**Comment by gustawdaniel** [comment]
Ok, so I will close it.

**Pull request closed without merging**
