### PR TITLE
fix: added new eqi operator for case insensitive equal search

### PR DESCRIPTION
**Pull request by meherchandan**
### What does it do?
This PR will add a new operator `$eqi` to perform an case insensitive equal comparison.

Describe the technical changes you did.

### Why is it needed?
Currently in strapi, we have equal(`$eq`) - case sensitive and $constainsi as contains(case insensitive) operator. However in some of the scenarios, we need the equal operator with case insensitive(Specially to compare the url names or parameters). 

Describe the issue you are solving.
To  filter using case insensitive equal operator.

### How to test it?
Add the `$eqi` to any filter query - similar to `$eq`

Provide information about the environment and the path to verify the behavior.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Review by derrickmehaffy — CHANGES_REQUESTED** [review]
Before the engineers review, I know we will need tests and this will also need a documentation PR too.

**Comment by meherchandan** [comment]
> Before the engineers review, I know we will need tests and this will also need a documentation PR too.

I have added the tests as well as documentation - https://github.com/strapi/documentation/pull/961

**Comment by meherchandan** [comment]
@alexandrebodin - I have updated the PR for graphql plugin as well as the operator name(same is updated in documentation pr). I haven't tested the graphql.

**Comment by meherchandan** [comment]
Hi @alexandrebodin , @Convly - may I know if anything else is required for this PR to be approved.

**Comment by alexandrebodin** [comment]
My bad I didn't see the doc PR already merged :)

**Pull request merged**
