### PR TITLE
Improve media upload performance

### PR DESCRIPTION
**Pull request by Marc-Roig**
## 👋🏻  What does it do?
In the upload service, when uploading image, thumbnail, and responsive formats one by one, upload them all together.

As an example, when using cloudinary: 7s before 3s now.

## ❓ Why is it needed?

Especially, when using nonlocal upload providers, uploading images (and not even heavy ones) was slow. 

## 🧪  How to test it?
Upload any image in this branch and master and compare timings.

### CODE REVIEW

**Review by petersg83 — APPROVED** [review]
LGTM :) Well done 🚀

**Review by MarionLemaire — COMMENTED** [review]
Testing on Gestarted using Chrome, with a dataset of : 

MP4 file

GIF file

PDF file

PNG file

PPTX file

For uploading these files in the same order in feature/improve-upload-performance branch then in Master branch : 

With branch feature/improve-upload-performance : 

[2022-08-10 15:07:29.325] http: POST /upload (2179 ms) 200

[2022-08-10 15:07:35.862] http: POST /upload (304 ms) 200

[2022-08-10 15:07:42.415] http: POST /upload (257 ms) 200

[2022-08-10 15:07:48.787] http: POST /upload (1280 ms) 200

[2022-08-10 15:07:53.461] http: POST /upload (367 ms) 200

 

With Master branch : 

[2022-08-10 15:20:01.602] http: POST /upload (2452 ms) 200

[2022-08-10 15:20:52.659] http: POST /upload (608 ms) 200

[2022-08-10 15:21:16.414] http: POST /upload (204 ms) 200

[2022-08-10 15:21:39.994] http: POST /upload (1474 ms) 200

[2022-08-10 15:22:00.907] http: POST /upload (392 ms) 200

 

 >> For MP4, GIF, PNG and PPTX files, upload is faster with feature/improve-upload-performance  than with Master branch. Not for PDF file.

@Marc-Roig  is this the behavior we were expecting ?

**Comment by Marc-Roig** [comment]
@MarionLemaire 
Yes ! that's the expected behavior.

I have to note something that I did not specify clearly. The performance improvement should be only for images.
I am surprised it's faster with things other than images.

**Review by MarionLemaire — APPROVED** [review]
See my previous comment for test proof.
Checked with @Marc-Roig : QA OK.

**Pull request merged**
