### PR TITLE
fix(admin): support windows platform when loading custom app code

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Add windows usecase

### Why is it needed?

To support windows

### CODE REVIEW

**Comment by joshuaellis** [comment]
I'm gonna take a look at this myself tomorrow, we have to do this elsewhere so i think there's probably some similarities that can be drawn up...

**Comment by derrickmehaffy** [comment]
Experimental: `0.0.0-experimental.229cd8b2045b3fbbbdc9d81b42f8298d7ef01582`

**Comment by derrickmehaffy** [comment]
Spoke with two community users on Discord and they both confirmed this fixes it for them on Windows

**Comment by Boegie19** [comment]
Tested the experimental on windows and it fixes the issue.

**Comment by Simnek** [comment]
Just tested experimental on Windows 11 and i can confirm it is fixed.

**Comment by alexandrebodin** [comment]
> I'm gonna take a look at this myself tomorrow, we have to do this elsewhere so i think there's probably some similarities that can be drawn up...

Except from plugins where I reused this change from I don't know what you have in mind ?

**Comment by alexandrebodin** [comment]
Closing in favor of https://github.com/strapi/strapi/pull/18797

**Pull request closed without merging**
