### PR TITLE
Parse environment variables on build configuration

### LINKED ISSUE #1590: Enviroment variables not replaced on `server.json` config file
**Informations**
- **Node.js version**: 9.11.2
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: mongo
- **Operating system**: WSL with Ubuntu 18.04 on Windows 10

**What is the current behavior?**
The `database.json` is using environment variables (👍). Trying to use the same patter on `server.json` file is not working.

**Steps to reproduce the problem**
Edit the `server.json` config file (tried for production env) with this content:
```json
{
  "host": "localhost",
  "port": 1337,
  "autoReload": {
    "enabled": true
  },
  "cron": {
    "enabled": false  
},
  "admin": {
    "path": "/",
    "build": {
      "host": "/",
      "backend": "${process.env.STRAPI_BACKEND}",
      "plugins": {
        "source": "backend"
      }
    }
  }
}
```

**What is the expected behavior?**
The environment variable been replaced with their value. Instead, if is not defines is replaced with `undefined`; if defined is "not replaced" (the requests go to `/$%7Bprocess.env.STRAPI_BACKEND%7D/`)

**Suggested solutions**
🤷‍♂️

### PR DESCRIPTION
**Pull request by maturano**
My PR is a: 🐛 Bug fix

Main update on the: Framework

---

Currently the use of environment variables in the configuration files is allowed, however the values are not replaced building the administration panel. You can clearly see the error if you try to use an environment variable as the value of the `host` parameter in the `server.json` file:

serverconfig_withhttp

As can see, the value was used as an ordinary string; they were not replaced by the value of the environment variable.

This PR moves the code that makes that interpretation to `strapi-utils` trying to make it a shared functionality. In addition to been invoked originally in the same place, with this changes also it's called by `webpack`, getting a consistent result in the build.

You can see here the result of this change:

serverconfig_patch

*Notes*:
- I keep the name of the function. Could have a better name maybe?
- Is `strapi-utils` the correct place? 🤔 
---
close #1590

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@maturano Is this for loading config values from environment variables for use in something like Docker?

**Comment by maturano** [comment]
I was not thinking specifically in Docker, but I think could be also a use case.

I used environment variables on the `server.json` file and there is not been interpreted on the `build` job (as part of a CI pipeline). Not in all parts... this fix that.

On #1590 I documented some cases and their result. I'll put the result of this PR hoping makes clear why should be included.

**Comment by derrickmehaffy** [comment]
@maturano good thinking :wink:

**Comment by maturano** [comment]
@derrickmehaffy I didn't see any new comments on the original issue. I updated the description of this PR hopping having better visibility.

**Comment by maturano** [comment]
Glad to help :)

I just made a rebase with `master` to ensure a clean merge 👍

**Pull request merged**
