### PR TITLE
feat: add missing attributes to Media in typescript generator

### PR DESCRIPTION
**Pull request by benjaminrobinet**
### What does it do?

Adds the missing attributes (allowedTypes, and multiple) of the generated Media type.

### Why is it needed?

Not having the "multiple" attribute, makes the Media type not being repeatable. 

### How to test it?

Generate the types from the `getstarted` exemple, under `ApiHomepageHomepage` you should have 
```
    single: Attribute.Media<'images', 'files', 'videos'>;
    multiple: Attribute.Media<'images', 'videos', true>;
```

### CODE REVIEW

**Comment by benjaminrobinet** [comment]
Just moved to draft as I just figured out that it is not a tupple but an array, will commit a fix.

**Comment by freddieerg** [comment]
Hello @Convly is there any chance of this being approved, our team are desperate to get our hands on this fix and believe it is a critical piece of functionality for accurately generating Media types. Thank you.

**Comment by freddieerg** [comment]
Bumping this. @Convly , please, this is a really vital piece of functionality for TS users.

**Review by Convly — APPROVED** [review]
LGTM, thanks for the tests as well!

**Pull request merged**
