### PR TITLE
Feature - Clone / Duplicate Record for Repeatable Component

### PR DESCRIPTION
**Pull request by RajNandigalla**
### What does it do?

Duplicate Record for Repeatable Component

Screenshot 2020-11-11 at 2 29 14 PM

### Why is it needed?

User convenience
& My Current Employer Requires this feature

### CODE REVIEW

**Comment by RajNandigalla** [comment]
@alexandrebodin Guys can someone look into this PR

**Comment by soupette** [comment]
@RajNandigalla we will have a look into this PR very soon, however we still need to check with our PM @sam-pires if this is a feature we would like to introduce. Also, we will need to merge some other work before as the code of the content manager plugin has been refactored so might want to take a look at the `feature/relational-fields` branch

**Comment by RajNandigalla** [comment]
> [CLA assistant check](https://cla.strapi.io/strapi/strapi?pullRequest=8621)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=8621) before we can accept your contribution.
> 
> **Raj Nandigalla** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=8621) it.

I have signed , it isnt reflecting

**Comment by derrickmehaffy** [comment]
> > [CLA assistant check](https://cla.strapi.io/strapi/strapi?pullRequest=8621)
> > Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=8621) before we can accept your contribution.
> > **Raj Nandigalla** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=8621) it.
> 
> I have signed , it isnt reflecting

Fixed it seems :)

**Comment by sam-pires** [comment]
Hello @RajNandigalla 
Thanks for the PR!

I would like to check the PR and its impacts more in details before approving the merge. We haven't discuss this feature before so I need to work on some specs to keep history of some choices made to be able to maintain it properly.

Right now we are focusing on the next release before the end of the year, 3.4, so we won't be able to merge this PR before Q1 next year. But I'll work on specs and impact before. I'll keep you posted

Thanks

**Comment by sam-pires** [comment]
Actually, your PR code will need to be updated after the next release and the addition of relational fields display in the List Views.
The best to manage your feature suggestion is to create a RFC (request for comments) so we can discuss it there and make sure you have all the info needed and that the specs are written down before pushing the PR :) 

Does that work for you @RajNandigalla ?

The FRC can be submitted in the dedicated repo: https://github.com/strapi/rfcs

**Comment by soupette** [comment]
Thank you @RajNandigalla for your contribution, I am closing this PR due to inactivity, feel free to first open an RFC and then reopen your PR.

**Pull request closed without merging**
