### PR TITLE
fix : Cleaner fallback for files preview (#22100)

### LINKED ISSUE #22100: Cleaner fallback for files preview
### Why should we do it?

In the Media Library, the current fallback for files doesn't look great on the cards and even look buggy in the details modal. We should clean it a bit and let users know that it's normal.

image

image

### Solution

- Update icon style with a 24px size and use `Neutral500` for the color
- Add the text "No preview available" below the icon
- Add the french version of the text ("Aucun aperçu disponible") in the french translation file
- Center the icon and the text vertically and horizontally in their container
- While keeping them centered, offset down the icon and the text from 8px for visual balance

CleanShot 2024-11-07 at 15 28 10@2x

CleanShot 2024-11-07 at 15 28 13@2x

### PR DESCRIPTION
**Pull request by dilshad-knk**
Now :
image
Screenshot 2024-11-14 015601
Screenshot 2024-11-14 015619

Before : 

image
image

### Related issue

fixes #22100

### CODE REVIEW

**Comment by lucasboilly** [comment]
Hi @dilshad-knk, thanks for your contribution :)

Here's my feedback:
- The modal preview should not be different from the card preview (icon size, spacings, margins, etc).
CleanShot 2024-11-15 at 12 23 00@2x
- It's something I forgot to mention, but the text should be smaller. I think you can use `variant="pi"`.
- I noticed it with your screenshots but the colors don't adapt to the dark theme.

**Comment by dilshad-knk** [comment]
1. The modal Preview and card preview is same now
2. Used font font `varient = 'pi'`
3.Now color adapts to the dark theme

Now:

1-Dark theme 

Screenshot 2024-11-17 024351

Screenshot 2024-11-17 024425


2-Light theme 

Screenshot 2024-11-17 024704

Screenshot 2024-11-17 024722

**Comment by lucasboilly** [comment]
Hi @dilshad-knk and thanks a lot! That's very clean 👌

**Review by markkaylor — COMMENTED** [review]
@dilshad-knk The code looks fine to me. Could you please resolve the conflicts 🙏 Then I'll test and we can merge

**Comment by dilshad-knk** [comment]
i have resolved the conflicts

**Review by markkaylor — APPROVED** [review]

**Comment by markkaylor** [comment]
@dilshad-knk The lint / prettier tests are failing. Could you please try:

```
yarn lint:fix && yarn prettier:write 
```

**Comment by markkaylor** [comment]
Looks like you will also need to update the frontend tests in the upload plugin. It looks like snapshots failing. Could you try

`yarn test:front --updateSnapsahot`

**Comment by dilshad-knk** [comment]
Done

**Review by markkaylor — APPROVED** [review]

**Comment by markkaylor** [comment]
@dilshad-knk I'm just a little confused by the git history. Why do you have so many commits that are already on develop?

**Comment by dilshad-knk** [comment]
Can u check PR #22351

It has same changes with clean git history
[
Screenshot 2024-12-06 102141
](url)

**Comment by markkaylor** [comment]
That works we can merge that one. Closing this in favor of https://github.com/strapi/strapi/pull/22351

**Pull request closed without merging**
