### PR TITLE
[WIP] Add different format for `date` content builder

### PR DESCRIPTION
**Pull request by johannpinson**
My PR is a:
🚀 New feature

Main update on the:
Admin
Plugin 

This PR change first the SQL type for `date`, `time` and `datetime` into `DATETIME` instead of `TIMESTAMP`
It will allow to the user very past date, before the classic 1970-01-01.

Because of the timezone management, this PR is linked with #1437 

Then, it add the choose between the different format, like for a number:
capture d ecran 2018-06-20 a 18 58 46

It's also add the possibility to edit the 3 new format and possibly change the type between the four (but it can generate some bug, like switching between number type).

**WARNING:** 
It miss yet the translations, I'm working on it 👍

### CODE REVIEW

**Comment by lauriejim** [comment]
This PR break the Content Manager.
The data input display for `timestamp` type is not correct, the sended data has not the good format.
Have to check if it's related to this PR or not for this data type issue.

**Comment by johannpinson** [comment]
@lauriejim 
It's not related, if you create a new project, add a `timestamp` field and go to the admin, you will already have this "bug".

**Comment by johannpinson** [comment]
@lauriejim:

As talked together, this PR is normally ready to merge.
For the moment, it just allow SQL database to separate `time`, `date` and `datetime` into a `datetime` like SQL format instead of a MySQL `timestamp` (which is too limited with 1970-2038 range for MySQL).
Mongo isn't modified since it's alreay use the `ISODate` for all "date"-like format.

I also rename the main group from `date` to `moment`, since the default choice is `datetime`, I find it more understandable.

**Comment by johannpinson** [comment]
@lauriejim:
BTW, it's ready for the review 😉

**Comment by lauriejim** [comment]
Hello @johannpinson.
I was not able to use your feature.

screen shot 2018-07-05 at 12 56 27

I setup your repo and try to create a content type `Article` with `date` attribute.

About the name `Moment` I don't know if it's better than `Date` @Aurelsicoko need your point of view on this topic.

**Comment by derrickmehaffy** [comment]
@johannpinson What MySQL data types are being used for the other formats? Assuming not the auto-generated ones?

**Comment by lauriejim** [comment]
@johannpinson You look have less time for now and I can't release it the actual state of this issue. It's why I remove it from the next release.

**Comment by johannpinson** [comment]
@lauriejim : ok I see, some bug with the translation keys

@derrickmehaffy : what do you meen by "not the auto-generated types" ?
Because actually, a date field created from the admin is always a `date` but if you modify manually your settings (json file) or you model, you can add one of this four: `date`, `time`, `datetime` and `timestamp` (cf. https://strapi.io/documentation/guides/models.html#define-the-attributes).
So this PR is to allow the user to create one of them directly.

**Comment by derrickmehaffy** [comment]
@johanbaath what data type are you storing them as in MySQL? `String` or something? Not sure what option MySQL has for storing just Date, or just Time, ect

**Comment by derrickmehaffy** [comment]
@johannpinson every time man, every time.

And gotcha, just wanted to check in case I was missing something in the MySQL docs 😛

**Comment by mnlbox** [comment]
@lauriejim any chance to see this PR in next release?

**Comment by soupette** [comment]
@lauriejim @johannpinso where are we on this PR?

Should we try to update it and get it working with the latest release or should we close it?

By the way, I willing to help contributing to make this working if needed.

**Comment by lauriejim** [comment]
@mnlbox Not ready to be in the next release.
I need to do some test and verification after resolving conflicts.

**Comment by Aurelsicoko** [comment]
It cannot be merged without @soupette approval and without a full set of tests.

**Comment by soupette** [comment]
@johannpinson @lauriejim @Aurelsicoko Do I need to undertake some developments to finish this feature?

**Comment by derrickmehaffy** [comment]
@soupette yes I think there are still a few things that need to be worked out, I don't think much is needed but I would really like to see this in the near future as it also fixes the issue I created about the MySQL date. I think most of the things that need fixing are on the frontend, but will have to do some testing with MySQL and postgres once we get those bits worked out.

**Comment by derrickmehaffy** [comment]
Note that this PR: https://github.com/strapi/strapi/pull/1932 is making major modifications to bookshelf so this PR will need to gone through very carefully to ensure none of the changes in https://github.com/strapi/strapi/pull/1932 are reverted.

**Comment by lauriejim** [comment]
I close this PR since there is no activity, will reopen it the it will be necessary.

**Pull request closed without merging**
