### PR TITLE
Update logo

### PR DESCRIPTION
**Pull request by Aurelsicoko**
### What does it do?

I've updated the logos to match the new brand guidelines.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Open the sign-up and sign-in page and appreciate the new logo.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Review by maevalienard — APPROVED** [review]
Thanksssss

**Review by gu-stav — COMMENTED** [review]
Thank you. I've added another commit to compress the PNGs a bit better (saves about 14kB).

One thing I find a bit odd: we currently have two logos with different border radi:

| logo_strapi_auth_v4.png | logo_strapi_menu.png |
|-|-|
| logo_strapi_auth_v4 | logo_strapi_menu |

@maevalienard Do you see a way to unify both, so that we only have to maintain one version?

**Comment by Aurelsicoko** [comment]
Good catch @gu-stav, I'll compress them and update the logo_strapi_menu.png too, the border-radius has been updated a bit.

**Comment by gu-stav** [comment]
@Aurelsicoko I've checked in a compressed version already in 766db8ed9c0bb1d665a8826f8bc50dedb27e7578 :) It would be great, if we could get rid of one logo, because otherwise users need to download both files.

**Comment by Aurelsicoko** [comment]
> @Aurelsicoko I've checked in a compressed version already in [766db8e](https://github.com/strapi/strapi/commit/766db8ed9c0bb1d665a8826f8bc50dedb27e7578) :) It would be great, if we could get rid of one logo, because otherwise users need to download both files.

My bad, I compressed the 3 of them and simply updated the file, we could maybe use only one as you mentioned as they are both the same (not the same size though).

**Comment by gu-stav** [comment]
If you want I can take care of that in a follow-up PR? I've added another one to cleanup the assets a bit and could also cleanup both logos if you tell me which one to use :)

**Review by gu-stav — APPROVED** [review]

**Comment by maevalienard** [comment]
> @maevalienard Do you see a way to unify both, so that we only have to maintain one version?

We should only have the one on the left. Kevin planned a very specific border-radius for the background :)

**Pull request merged**
