### PR TITLE
feat(documentation): add /openapi.json route (strapi/documentation#2143)

### PR DESCRIPTION
**Pull request by faessler**
### What does it do?

Exposes the `full_documentation.json` under the `/documentation/openapi.json` and `/documentation/{version}/openapi.json` routes.

Based on: https://github.com/strapi/strapi/issues/10734#issuecomment-1203774550

### Why is it needed?

This is needed to provide a way to consume the schema generated by the documentation plugin in external code-bases or applications.

This allows for example easy typescript type generation with [openapi-typescript](https://www.npmjs.com/package/openapi-typescript). In an external code-base the types from Strapi can be generated like this:
```
npx openapi-typescript http://localhost:1337/documentation/openapi.json -o ./schema.d.ts
```

### How to test it?

1. Checkout this branch
2. Run `yarn && yarn setup`
3. Run `cd ./examples/getstarted && yarn develop`
4. Open http://localhost:1337/documentation/openapi.json

You now have an `openapi.json` file reflecting the contents of `full_documentation.json`.

### Related issue(s)/PR(s)

- https://github.com/strapi/documentation/issues/2143
- https://github.com/strapi/documentation/issues/590
- https://github.com/strapi/documentation/issues/366
- https://github.com/strapi/strapi/issues/10734
- https://github.com/strapi/documentation/pull/2159

### TODOS:

- [x] update docs
- [ ] ~~add tests?~~

### CODE REVIEW

**Comment by faessler** [comment]
Hey @Marc-Roig can we port this to v5? 🤞

**Comment by Marc-Roig** [comment]
@faessler would you be up to open another pr? 🙏 sounds ok to me port it but I am lacking the time atm

**Comment by tif-calin** [comment]
A port would be much appreciated and very necessary for anyone using REST who wishes to codegen FE types

**Comment by faessler** [comment]
@Marc-Roig I cherry-picked https://github.com/strapi/strapi/commit/6906bea83420e2a8aee898641d473ccf84cee899, resolved some small conflicts, and created PR here https://github.com/strapi/strapi/pull/24550.

@pwizla here also PR for porting docs https://github.com/strapi/documentation/pull/2759.

**Pull request merged**
