### PR TITLE
DOC: Reference the configuration options for SQL databases from the Databases guide

### PR DESCRIPTION
**Pull request by TPXP**
Hello, and thanks for building Strapi, we're using it for our next-gen website and it looks very promising.

I started my project using the quickstart option, but quickly wanted to move on to my PostgreSQL instance to get a setup as close to production as possible (also, I had to use Docker anyway since I have Node v14 on my machine, and well docker-compose just works). So I wen through the configuration to change my database settings, and looked at the documentation to find the relevant parameters. Having two pages with the same title made it difficult for me to find the right options since the guide page does not talk about PostgreSQL or MySQL. This PR aims to add the missing link between the two pages.

#### Description of what you did:
Added a section in the Databases guide referring to the configuration options for SQL databases.

### CODE REVIEW

**Review by derrickmehaffy — CHANGES_REQUESTED** [review]
Can you please make sure you target the `documentation` branch via our Contrib Guide: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#documentation

**Review by derrickmehaffy — APPROVED** [review]
LGTM

**Comment by TPXP** [comment]
Oops, good catch! Thanks for pointing me to the contribution guide. 😓

**Comment by TPXP** [comment]
:wave: Hello, are there any other changes you need ? Seems like the CI fail was not caused by my changes

**Comment by derrickmehaffy** [comment]
@TPXP you are right, the tests are unrelated to your PR

**Pull request merged**
