### PR TITLE
#4192 left menu icons alignment

### LINKED ISSUE #4060: Icons alignment issues in the left menu Firefox
**Describe the bug**
Since updating to version *v3.0.0-beta.16.4* I somehow expirience an issue where the different Icons in front of the Content-Type name are not aligned perfectly centered. This is a totally astethic issue and does not effect functionality in any way, matter of fact it's unpleasant.

**Steps to reproduce the behavior**
1. Update to version v3.0.0-beta.16.4 or higher.
2. Take a look at the side-nav.

**Expected behavior**
The icons should be centered like in previous versions.

**Screenshots**

sidenav-strapi

**Code snippets**
Not applicable.

**System**
- Node.js version: 12.10.0
- NPM version: 6.11.3
- Strapi version: v3.0.0-beta.16.5
- Database: MongoDB
- Operating system: Windows Server 2002 R2

### PR DESCRIPTION
**Pull request by xstable**
This fix #4192 and fix #4060  

**Ready to merge**

#### Description of what you did:
Fix some stylesheets 

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [ ] 💅 Enhancement
- [x] 🚀 New feature

#### Main update on the:

- [x] Admin
- [ ] Documentation
- [ ] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@xstable 

Two things:
1) please update your PR following the PR template (this is required)
2) I've manually restarted the TravisCI build

**Comment by derrickmehaffy** [comment]
@xstable any update to this PR? Just going through and checking in to try and close out stale PRs

**Comment by xstable** [comment]
nothing new here. Stopped working on it atm, because the leak of time

**Comment by derrickmehaffy** [comment]
Alright for now I'm going to go ahead and close this. We can reopen if you get some more time or if someone else wants to pick up on it.

**Pull request closed without merging**
