### PR TITLE
Fix issues with case sensitive email addresses sent by some SSO providers

### PR DESCRIPTION
**Pull request by Convly**
### What does it do?

Use a case-insensitive lookup for admin users in the findOneByEmail method of the user service.

### Why is it needed?

See #16982

### How to test it?

- Manually by executing `yarn strapi console` and then making a manual query to the admin user service.
- Or just by running the unit tests

### Related issue(s)/PR(s)

fix https://github.com/strapi/strapi/issues/16982

### CODE REVIEW

**Comment by innerdvations** [comment]
Was this working in 4.14 and broken in 4.15? If not, let's target main to avoid potentially introducing something new.

**Comment by Convly** [comment]
I figured this could be an easy fix to have in the next release but if we want to be extra cautious I can target another version

**Review by innerdvations — DISMISSED** [review]
LGTM!

Just to be sure, I also confirmed that the unique check on account creation is case insensitive (that is, it shouldn't be possible to have multiple accounts with different casing) so this should be safe.

**Comment by innerdvations** [comment]
> I figured this could be an easy fix to have in the next release but if we want to be extra cautious I can target another version

Yeah, it seems very simple and totally safe to me, but those are always the ones that always seem to end up breaking something unexpected 😆

**Review by innerdvations — APPROVED** [review]

**Comment by derrickmehaffy** [comment]
building experimental: https://github.com/strapi/strapi/actions/runs/7090551315

**Pull request merged**
