### PR TITLE
Translations and text corrections for plugins

### PR DESCRIPTION
**Pull request by hide-me**
### What does it do?

Improvements and additions have been made (the list of changes is presented below) to the localization of the following plugins: [color-picker](https://github.com/strapi/strapi/tree/main/packages/plugins/color-picker), [documentation](https://github.com/strapi/strapi/tree/main/packages/plugins/documentation), [graphql](https://github.com/strapi/strapi/tree/main/packages/plugins/graphql), [sentry](https://github.com/strapi/strapi/tree/main/packages/plugins/sentry)

1. Added strings with names of plugins.
2. Checked translations and terminology style.
3. Created translations into Russian.
4. Fixed few typos.
5. Deleted empty language json files.

### Why is it needed?

All these plugins for now has +1 language, fixed strings with typo, added strings with name of plugin.

### How to test it?

No need to test, this is json files with strings. You may just look into changes to see it all.

### CODE REVIEW

**Review by ronronscelestes — CHANGES_REQUESTED** [review]
hi @hide-me, thanks for this contribution
could you add some changes:
- I think it would be better to squash those 69 commits, it would make it difficult reading the commit history with 1 commit for each small typo changes
- for color picker translation files, I don't think we should add english translations to other languages files (e.g. `"plugin.name": "color picker"`) as we already have english default message when no specific translation key exists

wdyt?

**Comment by hide-me** [comment]
Hello, thank you for your comment!
1. Sorry, but I do not know how to merge group of microcommits, because I used github website editor instead of git. If you can do it - sure, go ahead :)
2. Good, you can **skip or cancel** commits with english translations to other languages files. I thought like this: if someone decides to update the translation of, let's say, German, then the translator will not need to look for missing lines in the file with the English translation - that is my idea: each file is self-sufficient and ready for translation.

**Comment by joshuaellis** [comment]
> Good, you can skip or cancel commits with english translations to other languages files.

As this is your PR, can you please revert those changes and then we will squash the commits.

Thank you 😊

**Comment by hide-me** [comment]
@joshuaellis @ronronscelestes
I made extra commit with deleting strings e.g. "plugin.name": "color picker"
Hope it would help

**Comment by hide-me** [comment]
Any news about my pull reqest?

**Comment by joshuaellis** [comment]
> Any news about my pull reqest?

You've merged main into this branch so now I can't squash it and as we said originally we're not merging a PR with this many commits with the same name – it's bad practice for our GIT history. So I need to look at how to solve this.

**Review by joshuaellis — APPROVED** [review]

**Pull request merged**
