### PR TITLE
Remove model dialog margin-top definition from bootstrap-overrides.scss

### PR DESCRIPTION
**Pull request by kadaan**
Fix for #1062

### CODE REVIEW

**Comment by kadaan** [comment]
@lauriejim Can you review this?  Also, any idea the reasoning behind the margin-top being so large in the first place?

**Comment by kadaan** [comment]
Can you share a screenshot?
		
		

		—Joel Baranickjbaranick@gmail.com
	




On Mon, May 14, 2018 at 5:22 AM -0700, "cyril lopez" <notifications@github.com> wrote:












Hi @kadaan and thanks for your contribution!


However, I don't think that we can merge your PR for the moment since all the popups aren't aligned correctly.


@Aurelsicoko can you confirm?

**Comment by Aurelsicoko** [comment]
@kadaan Thank you for the PR 👍 

Here the screenshot to show you that the text in the modal is not correctly aligned with our baseline.
screen shot 2018-05-15 at 17 37 58

We're taking care of the UI a lot (especially me). Can you try to set the `margin-top` value to `9rem`  instead and tell me if it works well on your side. Otherwise, you can also try `7.2rem` or `5.4rem`. Our baseline is defined to `1.8rem`.

PS: [Here the link to download the Chrome Extension](https://chrome.google.com/webstore/detail/design-grid-overlay/kmaadknbpdklpcommafmcboghdlopmbi)

**Comment by kadaan** [comment]
Cool extension. I’ll give that a shot tonight. One downside about the constant top margin is that it breaks once the client view size gets small enough. That said, a much smaller multiple of 1.8rem will probable fix the issue. Thanks!
		
		

		—Joel Baranickjbaranick@gmail.com
	




On Tue, May 15, 2018 at 8:43 AM -0700, "Aurélien GEORGET" <notifications@github.com> wrote:












@kadaan Thank you for the PR 👍


Here the screenshot to show you that the text in the modal is not correctly aligned with our baseline.




We're taking care of the UI a lot (especially me). Can you try to set the margin-top value to 9rem  instead and tell me if it works well on your side. Otherwise, you can also try 7.2rem or 5.4rem. Our baseline is defined to 1.8rem.


PS: Here the link to download the Chrome Extension

**Comment by lauriejim** [comment]
Hi @kadaan any news about your PR ?

**Comment by johannpinson** [comment]
@lauriejim this PR may be a duplicate of https://github.com/strapi/strapi/pull/1268

**Comment by lauriejim** [comment]
@johannpinson Completely right !!

**Comment by kadaan** [comment]
Thanks for the fix.  I’ve been on vacation, so didn’t have time to work on it.

--
Joel Baranick
jbaranick @gmail.com

**Pull request closed without merging**
