### PR TITLE
set email validator to lowercase

### PR DESCRIPTION
**Pull request by bglidwell**
#### Description of what you did:
Yup .lowercase() converts the string to lowercase which should be done in all instances of email across the application.

Fixes bug where users created inside Strapi admin panel end up with mixed case emails in database.

### CODE REVIEW

**Comment by soupette** [comment]
@bglidwell thanks a lot for your contribution! Before reviewing your PR can you make sure the DCO checks?
Also, do you mind updating the front-end validations so it matches the back-end ones? [Here's the corresponding file](https://github.com/strapi/strapi/blob/64de3a2ea2b4259608b3a1699f5b39530bde7c71/packages/strapi-admin/admin/src/validations/users/profile.js#L7-L10)

**Comment by bglidwell** [comment]
@soupette done!

**Review by soupette — COMMENTED** [review]
LGTM to me for the front-end part.

**Comment by bglidwell** [comment]
Worth noting, this optimization can be used in a lot of different areas. I scoped this particular PR to just the users & permissions plugin for simplicity. I think this route makes schemas easier to test.

**Comment by bglidwell** [comment]
Interesting that the backend doesn't also use yup for validation. Seems a lot of that could be shared between FE/BE, reducing complexity and improving consistency. 

Lastly, it appears the Admin panel does not use the users-permissions plugin's controller for creating user objects. Does the admin use a special controller somewhere? I tried breakpoints in the usual suspect controllers in node_modules/strapi-admin but didn't get anything to stick. Any pointers? I've got a feeling part of the issue is a divergence between the users-permissions plugin (which correctly lowercases on backend before storing/comparing data) and the strapi-admin plugin which does not.

**Review by soupette — APPROVED** [review]
LGTM

**Pull request merged**
