### PR TITLE
[SSO] Accept null value for ssoLockedRoles

### LINKED ISSUE #17172: ssoLockedRoles can't be empty
### Required System information

- Node.js version: 18.9.1
- NPM version: 8.19.1
- Strapi version: 4.11.3
- Database: postgres
- Operating system: Windows
- Is your project Javascript or Typescript: Javascript

### Describe the bug
ssoLockedRoles must be a `array` type, but the final value was: `null`. If "null" is intended as an empty value be sure to mark the schema as `.nullable()`

### Steps to reproduce the behavior

1. Go to SSO in settings full everying in and keep ssoLockedRoles empty

### Expected behavior

For it to allow it

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

Allow the backend validation to accept a null value for ssoLockedRoles.

### Why is it needed?

Fixes a bug where the Settings -> SSO form will not save unless a role is first selected and deselected (allowing the front-end to submit an empty array rather than null)

The frontend receives a null as the initial value and if the field is unchanged it will send it back, which was causing the problem.

### How to test it?

Starting from a new project (or one where where the Strapi option for providers.ssoLockedRoles is null) attempt to save the Settings -> SSO form with an empty SSO locked roles multiselect.

It should now work and accept the null value.

API tests have been added for provider options. Reminder that they only run with EE enabled, that is with `STRAPI_LICENSE=your_license yarn strapi test:api`

### Related issue(s)/PR(s)

Fixes #17172

### CODE REVIEW

**Review by Convly — COMMENTED** [review]
Just trying to understand the issue:
Shouldn't we fix this issue in the frontend instead?
I feel like null doesn't carry the same meaning as an empty array. Why can't we use [] as the default value in the frontend?

**Comment by joshuaellis** [comment]
> Just trying to understand the issue: Shouldn't we fix this issue in the frontend instead? I feel like null doesn't carry the same meaning as an empty array. Why can't we use [] as the default value in the frontend?

I'd disagree, if you send null and the field is not required, why can the FE not send `null` back? 👀 an empty array is a value imo

**Comment by Convly** [comment]
> > Just trying to understand the issue: Shouldn't we fix this issue in the frontend instead? I feel like null doesn't carry the same meaning as an empty array. Why can't we use [] as the default value in the frontend?
> 
> I'd disagree, if you send null and the field is not required, why can the FE not send `null` back? eyes an empty array is a value imo

Yes you're right, I just read `The frontend receives a null as the initial value`, my bad. It indeed makes sense.

**Review by Convly — APPROVED** [review]

**Review by Convly — COMMENTED** [review]
Could we add a test for this?

**Review by derrickmehaffy — DISMISSED** [review]
Lgtm

**Review by christiancp100 — APPROVED** [review]
LGTM 🍝

**Comment by innerdvations** [comment]
Added provider options form API tests

**Review by Convly — APPROVED** [review]
What kind of bug are we talking about (in the test)?

Otherwise, lgtm

**Comment by innerdvations** [comment]
Essentially the same issue as ssoLockedRoles but for defaultRoleId (it won't accept a null value)

I'll create an issue later or directly another PR to fix it as well.

**Review by christiancp100 — DISMISSED** [review]

**Review by Convly — APPROVED** [review]

**Pull request merged**
