### PR TITLE
fix: beforeDelete lifecycle components access

### PR DESCRIPTION
**Pull request by stafyniaksacha**
### What does it do?

Changing the order of deletion allow developers to query the entity being deleted including their components on the `beforeDelete` lifecycle hook

### Why is it needed?

Components can contains useful informations that we may need on this hook (relations to cleanup, etc...)

### How to test it?

Use this as a content type lifecycle which contains a dynamiczone or a component

```js
"use strict";

module.exports = {
  async beforeDelete(event) {
    const { model, params } = event;

    const entity = await strapi.db.query(model.uid).findOne({
      ...params,
      populate: {
        someComponent: true,
      },
    });

    console.log("beforeDelete", entity);
  },
};
```

### CODE REVIEW

**Review by alexandrebodin — APPROVED** [review]
LGTM it makes sense

**Comment by stafyniaksacha** [comment]
> LGTM it makes sense.
> 
> Would you be willing to work on adding some tests for this?

Yes, I will make an e2e test in https://github.com/strapi/strapi/tree/master/packages/core/strapi/tests 
Is it ok if I create a specific `lifecycles` folder, and add my test in a `afterDelete.test.e2e.js` ?

**Comment by alexandrebodin** [comment]
Sure you can create a lifecycles folder for it 👍 

For the error you are getting I think you might be missing a .env file let me ping @petersg83 who worked on that topic

**Comment by petersg83** [comment]
Hi @stafyniaksacha :)
Can you use
```sh
STRAPI_DISABLE_EE=true node test/e2e.js
```
instead please?

**Comment by stafyniaksacha** [comment]
@petersg83 thanks! I'm unlocked ;) Will write the tests

**Review by alexandrebodin — APPROVED** [review]
LGTM 👍

**Pull request merged**
