### PR TITLE
fix: make generate command work

### LINKED ISSUE #22127: Strapi CLI `generate` command saving files in `node_modules/strapi/@generators/dist`
### Required System information

- Node.js version: v18.20.4
- NPM version: 10.7.0
- Strapi version: 5.2.0
- Database: mysql
- Operating system: linux-x64 - Ubuntu 24.04.1 LTS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

While running the strapi cli using yarn (`yarn strapi generate`) the files generated end up being stored under `node_modules/strapi/@generators/dist`

### Steps to reproduce the behavior

1. Create a new strapi project using the cli `yarn create strapi`
2. Try to generate a new API endpoint using the CLI `yarn strapi generate` following all the necessary steps
3. It will succeed but the files won't be in `src/api` folder
4. Try to generate the API endpoint again using the same name
5. It will fail and print the location of the files previously generated

### Expected behavior

The files should be generated at the folder `src`

### Screenshots

image

### Code snippets

_N/A_

### Additional context

Tried the command using `npx`, `npm run` and `yarn`, all yielding the same result

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?

- switch usage of `plop.getDestBasePath()` with `process.cwd`  because it's not giving us the correct path
- adds 'src' directory 

### Why is it needed?

- generate command is not working 

### How to test it?

- test all the generate command choices `middelware`, 'api', content-type'... they should all work

### Related issue(s)/PR(s)

fixes #22127

### CODE REVIEW

**Comment by Bassel17** [comment]
experimental for testing: `0.0.0-experimental.3218535c8b12e654be4191f9c36c07b43861b437`

**Review by innerdvations — COMMENTED** [review]
Code LGTM, testing it now.

Do you know if before it broke (or in strapi v4) if the CLI had to be run from the root of the project or if it worked from any dir in the project?

**Review by Convly — DISMISSED** [review]
LGTM, tested and works well. Everything is generated in the `src` folder

**Comment by Convly** [comment]
> I know there's at least one strapi command (plugin generator?) that traverses up to the root of the project so that you can run it anywhere. But I'm pretty sure the way you've fix this is the same way it's always worked, requiring being in project root, so in that case it's fine.

I believe it assumes you're in the correct folder too.

**Review by jhoward1994 — DISMISSED** [review]

**Comment by Bassel17** [comment]
new experimental: 0.0.0-experimental.15989d13d8be058bf37afc84b7a8377ef1da3263

changed the code a bit and configured `destBasePath`
now all the tests should be passing and the generating is working

**Review by Convly — APPROVED** [review]
Looks much cleaner, nice!
(still works fine)

**Comment by Convly** [comment]
image
image

**Pull request merged**
