### PR TITLE
[WIP] Update Bookshelf to use Knexjs functions

### PR DESCRIPTION
**Pull request by derrickmehaffy**
My PR is a:
- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix 
- [x] 💅 Enhancement #2495 
- [ ] 🚀 New feature

Main update on the:
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

This PR is taking over for the one created by @maturanomx : https://github.com/strapi/strapi/pull/1932

The goal in this PR is the basic support modification of many of the current bookshelf functions and moving them to use knexjs functions where possible.

This is only part 1 of many other PRs to bring bookshelf up to (and hopefully past) mongoose support within strapi.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
**PLACE HOLDER**

What has been tested:

What needs to be tested:

What is still left to work on:

I will update this as I go and pull most of the data off the previous PR

**Comment by derrickmehaffy** [comment]
Closing this for now as most of these changes need to be completely re looked at due to the addition of SQLite

**Comment by wemod123** [comment]
Great PR!
Do you have a estimation of when this "mssql support" feature will be released?

**Comment by justinshea** [comment]
@wemod123 I’ve been tracking this for a while. Sadly, this doesn’t seem like a priority. Missed opportunity...

**Comment by wemod123** [comment]
@justinshea
😺 I see mssql utilization in past two years growth rapid, since MS Azure growth very fast globally,  while  Azure support their mssql in best way, reasonale...
I am one of that user...

Good to see here have a PR, possibly release one day in future.

**Comment by nddipiazza** [comment]
If I resurrect this, can I get it merged this time? I worry I do all the work to resurrect this then it goes stale again. @derrickmehaffy

**Comment by derrickmehaffy** [comment]
> If I resurrect this, can I get it merged this time? I worry I do all the work to resurrect this then it goes stale again. @derrickmehaffy

Strapi v4 pretty much already does most of what this PR was trying to do honestly. Was there something specific you are looking for?

(PS as an update about 3 years after this was closed, we don't plan on adding MSSQL support)

**Pull request closed without merging**
