### PR TITLE
Support many way relation

### PR DESCRIPTION
**Pull request by alexandrebodin**
#### Description of what you did:

Add many way support to Groups and Content Types.

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [X] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [X] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [X] MongoDB
- [ ] MySQL
- [ ] Postgres
- [X] SQLite

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
\o/ I'll be testing this right away :wink:

**Comment by derrickmehaffy** [comment]
It might be good to reference this as the backend part only as I'm not seeing any additions into the content-type builder to support adding manyWay through it (likewise attempting to modify a model with this relation type)

**Comment by alexandrebodin** [comment]
Tjis PR isn't open for review @derrickmehaffy it will be merged in a feature branch not master.

**Comment by derrickmehaffy** [comment]
Gotcha, makes sense :+1:

**Pull request merged**
