### PR TITLE
Enhancement: Move admin permission imports into app provider

### PR DESCRIPTION
**Pull request by gu-stav**
### What does it do?

Instead of importing the `./permissions` file (which contains an import to `ee_else_ce`) everywhere, the permissions are now stored in the `useAppInfo` provider.

🤔 1. I'm not particularly with the location in the `useAppInfo` Provider and have chosen it mainly because it lives at the top-level of the app.

Alternatives:

1. Create a new RBAC hook to retreive them
2. Move them in one of the existing RBAC hooks

One thing to keep in mind is that this PR is not trying to refactor how permissions work. There is plenty of very valuable follow-up work.

🤔 2. Because e.g. menu items can't know anymore about the async imported permissions, their actual permission needs to be built dynamically.

- `useMenu()`: instead of using an actual key from the permissions, the permission-name is now set to a string
- `useSettingsMenu()`: each link already has an id, which is always identical with the namespace in the permissions object, so the permissions can be built dynamically using `settings.<id>.main`

I'm not super happy with that, because it removes a safety-net from the code, but I think we could have a separate discussion about how to represent permissions for menus and refactor these parts.

### Why is it needed?

It is the last step to move all enterprise data-structures to be loaded through the new `useEnterprise()` hook, that will allow us to do runtime switching for the admin app.

#### What are these permissions?

These permissions define the _required_ permission for each plugin / module / namespace. Example: in order to view settings page x, a user needs read permissions for page x. The actual permissions a user has are retrieved from the admin API.

### CODE REVIEW

**Comment by joshuaellis** [comment]
> @joshuaellis I've extended the PR description to give more context. Does that help?

It does, i think this could do with a real dissection on how we handle RBAC because these are the permissions a user has to have to do X and therefore should live within that RBAC ecosystem 🤔

I think a workshop on how to handle this elegantly would be great, if you feel the requirement to move quickly i'd store it in a non-public facing way e.g. `useAppInfos` is a public API and therefore we can't just strip it out in the meantime. using the RBAC provider might have the same problem. We could do an internal provider for now. 

IMHO i'd rather do a small meet to understand the problem space and come up with a solution and figure out the steps to get us there – but happy to follow your lead ✌🏼

**Comment by gu-stav** [comment]
> > @joshuaellis I've extended the PR description to give more context. Does that help?
> 
> It does, i think this could do with a real dissection on how we handle RBAC because these are the permissions a user has to have to do X and therefore should live within that RBAC ecosystem 🤔

Yes, I had the same thought and I think there is a lot of potential to improve the overall situation.

> I think a workshop on how to handle this elegantly would be great, if you feel the requirement to move quickly i'd store it in a non-public facing way e.g. `useAppInfos` is a public API and therefore we can't just strip it out in the meantime. using the RBAC provider might have the same problem. We could do an internal provider for now. 

We are running into the old problem here: right now there is no place to share private utils from in the frontend and there is only the helper-plugin (because this part needs to be shared across every package which is not a plugin - those define their own permissions).

Therefore it doesn't really matter if it lives in appInfo or another hook, because both will be public in the end.

> IMHO i'd rather do a small meet to understand the problem space and come up with a solution and figure out the steps to get us there – but happy to follow your lead ✌🏼 

Let me think about it a bit longer. There is a tradeoff to make between the ideal solution and a good enough solution to move forward, knowing that we need to untangle the whole RBAC situation anyway. 🤔

**Comment by gu-stav** [comment]
Here are some thoughts:

- right now, we are doing cross-package imports of the permissions file, which we should avoid for any future solution because packages should be self-contained somewhat
- because permissions are read in so many locations, the read should be a sync operation (only async for the moment it is added into the store)

## Long-term: Overhaul RBAC APIs

There is a good chance I don't have the complete picture here, but from what I know, I think I'd like to explore if we could make it possible to move everything RBAC related into one hook, that:

- allows registering new requirements (e.g. using injections)
- allows checking, if a user has a certain permission

I think in the long-term _permission requirements_ and actual _user permissions_ should be seen as one thing for a developer using Strapi. Something might have required permission and it should be easily possible to check of the user fulfills that. I can't really say what the actual API could look like and it might make sense to sync on that with the backend-team, because they already have what they call the permission-engine, which addresses a similar need.


## Short-term

### 1️⃣ Move redux to the top-level

We could move the redux-store provider to the top of the application and make the required permissions available.

This would also go well with the long-term idea because a single hook can inject/ know about everything RBAC-related (required permissions/ user permissions) from the store.

With this idea, I'd propose to create a global `app` or `admin` namespace, where we can register these requirements. To keep it simple I'd just move the current permission schema into the store, without questioning its structure.


### 2️⃣ Introduce a new provider/ hook

Similar to the `useAppInfo` provider, we could add a new one + a corresponding hook, e.g. `useRequiredPermissions`, returning the plain permissions object (at least for now).

```js
// App.js
const permissions = useEnterprise(CE_PERMISSIONS, () => EE_PERMISSIONS);
const { register } = useRequiredPermissions();

React.useEffect(() => {
  register(permissions);
}, [permissions]);

// Component.js
const { permissions } = useRequiredPermissions();
```

This hook would need to be shared from the helper-plugin (and, therefore, it would be public) at the moment. For the next major iteration, we could move this into e.g. a plugin-kit, because RBAC might be useful for plugin developers, too (I think it is already possible to create new custom permissions).

We could also go one step further and call the hook `usePermissions`, make the API more strict (not returning the plain data-structure) and try keep it stable for when everything goes into redux:

```js
// Component.js
const { getPermission } = useRequiredPermissions('settings');
const permissions = getPermission('roles.main');
```

This approach would require more up-front research.


### 3️⃣ Keep it in `useAppInfo`

I think we could argue that it makes sense to share app-wide data through that hook, so we don't have to introduce a new and very specialized provider.

I do see the downsides of it, but it would be the least refactoring for now, in case we don't want to move redux to the top, because any hook we have to create would have to be public.

---

Now the big question: what do you think, @joshuaellis? I'm leaning towards 1️⃣, because it is very much aligned with the rest of what we want to do.

**Comment by joshuaellis** [comment]
## Long-term: Overhaul RBAC APIs

I don't actually understand the difference between a permission and user-permission but this can come later – maybe this is something we can work on together post your holiday, I had already identified the code (hooks / methods) all overlapped and were duplicated in places.

## Short-term

Lets move it to redux, it's a data structure and this is perfect for it. There's already RBAC related stuff in redux – `rbacProvider` and `content-manager_rbacManager` whilst we can't remove these, I think we need to understand what they are / what purpose they serve etc. to move this into redux correctly – we should also start some contributor docs on the store in the FE mainly what you're doing now, I don't think we need to back track and fill in the gaps yet. In the future we could remodel to make more sense with a clear migration path 👍🏼

**Comment by gu-stav** [comment]
Closing this PR. The 3 linked PR's will implement it using redux.

**Pull request closed without merging**
