### PR TITLE
v4.14.2

### PR DESCRIPTION
**Pull request by Convly**

### CODE REVIEW

**Comment by joshuaellis** [comment]
You know you can change the latest tag on npm? You don't have to publish a new version... I can show you this tomorrow if you're interested?

**Comment by derrickmehaffy** [comment]
> You know you can change the latest tag on npm? You don't have to publish a new version... I can show you this tomorrow if you're interested?

We know but we don't know how and no internal documentation for it.

**Comment by derrickmehaffy** [comment]
Alex did it last time

**Comment by joshuaellis** [comment]
It's all documented on npms website 🙂 https://docs.npmjs.com/cli/v10/commands/npm-dist-tag

**Pull request closed without merging**
