### PR TITLE
Fix WYSIWYG Reverse text

### PR DESCRIPTION
**Pull request by virgilbugnariu**
### What does it do?

Updated the `addContent` method. Called .focus() every time the editor state is updated.
I have also added some comments regarding another issue that makes the cursor to jump at the end of the formatting block due to the way the editor is initialised in the `componentDidUpdate`.

### Why is it needed?

After adding a MD formatting block (b, i, u, etc.) the text would be reversed. This fixes that issue as well as automatically selecting the placeholder text when no selection is being made.

### Related issue(s)/PR(s)

#7991 (it's closed due to the reporter not filing a proper issue)

### CODE REVIEW

**Comment by soupette** [comment]
Thanks a lot for your contribution!

Your PR fixes the reverse text for some of the markdown block, however, it does not solve the issue for the link, quote and codeblock.

Do you feel like investigating the issue for these blocks?

**Comment by virgilbugnariu** [comment]
Let me take a look :) Don't merge this yet.

**Comment by virgilbugnariu** [comment]
I have pushed a fix for quote/code blocks as well. 
Regarding the link, what I came up with felt a bit hacky so I haven't committed it. 

I'm pretty sure the `sendData` and the `focus` should be all executed in the `setState` callback. Unfortunately this isn't something I can do now, but maybe I can come up with another pull request in the near future.

**Comment by virgilbugnariu** [comment]
Not sure why the codecov checks fail. What does it do? Is there something I can do regarding it?

**Comment by derrickmehaffy** [comment]
@virgilbugnariu you can ignore the codecov, it's for our own use :)

**Review by soupette — APPROVED** [review]
LGTM!

Thanks a lot for your contribution!

**Pull request merged**
