### PR TITLE
Fixes #7974 Add index validation to strapi-plugin-content-type-builder

### LINKED ISSUE #7974: Error 'field cannot have keys not specified in the object shape' when trying to update a Content type
**Describe the bug**
Cannot save a content type if it has an indexed field at *collection.settings.json* file. 

Strapi fields have some validation rules. See https://strapi.io/documentation/v3.x/concepts/models.html#validations. I found that index validation is absent in the code (/node_moduels/strapi-plugin-content-type-builder/validations/types.js). And this throws the error on CT 'Save'. To solve this issue I patched the module and added validation rule for indexes. 

[content-type-builder-index-validation.txt](https://github.com/strapi/strapi/files/5256378/content-type-builder-index-validation.txt)

**Steps to reproduce the behavior**

1. Create a content type
2. Create a field (for example, a Text field)
3. Manually add {"index": true} to the attribute of this field in *collection.settings.json*.

```
{
  "kind": "collectionType",
  "collectionName": "customers",
  "info": {
    "name": "customer"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true,
      "index": true
    }
  }
}
```
4. Add a new field.

**Expected behavior**
The type should be saved and the index should be created in mongodb.

**System**

- Node.js version: v12.18.2
- NPM version: 6.14.5
- Strapi version: 3.1.4
- Database: MongoDB 4.2.3
- Operating system: Win 10

### PR DESCRIPTION
**Pull request by kpirumyan**
#### Description of what you did:

Add yup index validation to content type fields.

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hello, the `index` property is not a valid one outside of mongo database. We should just allow extra properties for now instead of adding this specific one. in the future we will move db options to a specific sub property

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
Hello, the `index` property is not a valid one outside of mongo database. We should just allow extra properties for now instead of adding this specific one. (removing the noUnknown option)

 in the future we will move db options to a specific sub property.

**Comment by kpirumyan** [comment]
> Hello, the `index` property is not a valid one outside of mongo database. We should just allow extra properties for now instead of adding this specific one. (removing the noUnknown option)
> 
> in the future we will move db options to a specific sub property.

Hello,

Got it. Thank you.

**Comment by alexandrebodin** [comment]
Hi @kpirumyan Are you still up to up your PR ?

**Comment by IPWright83** [comment]
> We have someone making a PR for this then but we asked for changes and no responses since then. #8022

@alexandrebodin 

Will this not break being able to add custom indexes like I was advised here https://forum.strapi.io/t/best-approaching-for-adding-custom-indexes/888/6 ? If I'm reading correctly it's restricting `index` to be a Boolean, not a string.

**Comment by alexandrebodin** [comment]
@IPWright83 If you read on of the requested changes I am asking to update this PR to allow sending extra properties (in any format) instead of adding this single index boolean property :)

**Comment by sunnysonx** [comment]
@alexandrebodin could it work with .lazy?

 ```
  index: yup.lazy(value => {
          switch (typeof value) {
            case 'boolean':
              return yup.boolean();
            case 'string':
              return yup.string();
            default: return true;
          }
        }),
```

**Comment by alexandrebodin** [comment]
Hi, @kpirumyan I'm going to close this PR for inactivity. Feel free to ping me if you eventually have time to work on it again :)

**Pull request closed without merging**
