### PR TITLE
fix(upload-aws-s3) - add credentials object to upload-aws-s3 example configuration docs

### PR DESCRIPTION
**Pull request by nolliebigspin**
Updating misleading documentation for upload-aws-s3 plugin

### What does it do?

Update upload-aws-s3 documentation.
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property

### Why is it needed?

Currently there is a warning in the logs that shows the following:
`(node:4986) Warning: Credentials passed directly to s3Options is deprecated and will be removed in a future release. Please wrap them inside a credentials object.`

AWS Docs:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property
> the AWS credentials to sign requests with. You can either specify this object, or specify the accessKeyId and secretAccessKey options directly.

The PR will update the documentation of the plugin.

### How to test it?

Update the plugin config, so the warning will disappear. The plugin should work fine with updated config.

### Related issue(s)/PR(s)

#18951

### CODE REVIEW

**Review by christiancp100 — APPROVED** [review]
You're right, documentation should be updated 👍🏼. Thank you very much for your contribution!

**Comment by christiancp100** [comment]
Hey @nolliebigspin! Thanks for submitting this necessary fix in our docs, you're right and it should be changed. However, in order to get this merged we need your PR to target develop and doing that for you I've encountered several conflicts that need to be fixed. If you can sort it out it would be awesome! Thank you again for taking time to contribute to Strapi

**Comment by Marc-Roig** [comment]
@christiancp100 @nolliebigspin I would recommend basing this branch from develop, and opening the PR again, as it might be easier than fixing all the conflicts.

**Comment by nolliebigspin** [comment]
@Marc-Roig @christiancp100 Thank you for reviewing! I'll reopen a new PR based on `develop` and tag you there.

**Pull request closed without merging**
