### PR TITLE
Settings: Re-fetch users list every time

### PR DESCRIPTION
**Pull request by gu-stav**
### What does it do?

Removes caching from the settings user-list.

### Why is it needed?

Currently, when a user is updated, the list is not re-fetched. We could either invalidate the query after a user has been edited, or re-fetch every time. I find the latter less opinionated and more in-line with the rest of the app.

> **Note**
> The edit view of user is terribly broken (roles are removed when re-saving a user, fields are not updated ...). There is an open issue (https://github.com/strapi/strapi/issues/15673) and we have this in the content-squad backlog.

### How to test it?

1. Navigate to http://localhost:1337/admin/settings/users?pageSize=10&page=1&sort=firstname
2. Edit a user
3. Go  back to list
4. Verify the user has been updated there too

### CODE REVIEW

**Comment by joshuaellis** [comment]
> Currently, when a user is updated, the list is not re-fetched

Can we not invalidate the queries after the mutation has ran? Or is this not something react-query does...

**Review by alexandrebodin — COMMENTED** [review]
Looks good. Probably not realted related but I noticed that when deleting a user the page doesn't refresh (the invite new user button  isn't reenabled when the admin seats are freeed)

**Comment by gu-stav** [comment]
@joshuaellis 

> Can we not invalidate the queries after the mutation has ran? Or is this not something react-query does...

Yes, I think ideally we would do it like that as part of the mutation. The linked issue mentions the poorly designed data-fetching patterns for the user edit-page and I think we could optimize the whole flow when refactoring this to use react-query: https://github.com/strapi/strapi/blob/88faa92af9ac7db59f0f0161d1d44793b476e4cc/packages/core/admin/admin/src/pages/SettingsPage/pages/Users/EditPage/index.js#L78-L114

**Review by joshuaellis — APPROVED** [review]
Great, i've added that ticket to the content-squad so we can look into refactoring this.

**Pull request merged**
