### PR TITLE
Italian language

### PR DESCRIPTION
**Pull request by bitkris-dev**
My PR is a:
💅 Enhancement

Main update on the:
Admin

Italian language added

### CODE REVIEW

**Comment by soupette** [comment]
Hi @bitkris-dev!

Thanks for your contribution, but we won't be able to merge it since you didn't translate the files located in the plugins folder : 
- [content-manager](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-manager/admin/src/translations)
- [content-type-builder](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-type-builder/admin/src/translations)
- [email](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-email/admin/src/translations)
- [settings-manager](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-settings-manager/admin/src/translations)
- [users-permissions](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-users-permissions/admin/src/translations)
- [upload](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-upload/admin/src/translations)

**Comment by lauriejim** [comment]
Hello @bitkris-dev can you please give us an update about this PR?

**Comment by bitkris-dev** [comment]
Sorry, I didn't notice that there were locales to translate in other folders, as I still have to use strapi itself. I will work on it as soon as possible.

**Comment by lauriejim** [comment]
Thank you @bitkris-dev , it will be awesome to have 🇮🇹 translation in Strapi !

**Comment by lauriejim** [comment]
Hi @bitkris-dev have you an update about this PR please ?

**Comment by lauriejim** [comment]
Complete PR that add italian language. https://github.com/strapi/strapi/pull/1426

**Pull request closed without merging**
