### PR TITLE
feature: onCommit , onRollback transaction methods

### PR DESCRIPTION
**Pull request by Marc-Roig**
## What does it do?

This is another iteration to improve transaction handling on async operations like audit logs.
It is a follow up of https://github.com/strapi/strapi/pull/16341.

During the development of RW we have seen two issues regarding how Audit Logs & Transactions interact with each other. And I will try to explain our setup and the problems we have seen.

We were doing something like this:
```js
    await strapi.db.transaction(async (trx) => {
	  const stages = await createWorkflowStages()//  -> Stores in DB new stages & Triggers audit log
      await createWorkflow(stages); // -> Stores in DB new workflow & Triggers audit log
    });
```

### Storing audit log event when data is rollbacked
In some cases, `createWorkflow` can throw an error and so, stages data is rollbacked. But... Even if we rollback the data, the audit log event is stored in DB.

### Saving events on committed transactions
In some cases the execution of the workflow logic and audit logs was like so:
```
RW ====> createsWorkflow ...................commit................................
AL  ====>  .......................savesEvent.................DB Access & commit 
```
With  https://github.com/strapi/strapi/pull/16341 seemed like we had fixed this, but it was just luck and you can see this error happening now, if you go to Settings -> Review Workflows and save some changes.

### Proposed solution
Save audit log events when the transaction is actually commited
```js
      await strapi.db.transaction(({ onCommit }) => {
        onCommit(() => state.provider.saveEvent(processedEvent));
      });
```

This way if data is rollbacked the event will not be stored.

### CODE REVIEW

**Comment by Marc-Roig** [comment]
If @Bassel17 and @remidej  think this is a good idea I can update our internal ADR for transactions :)

**Comment by Marc-Roig** [comment]
🙌 will do that @Bassel17  thank you for the review

**Review by nathan-pichon — APPROVED** [review]
LGTM
Although, I'm not sure that a copy of the arrays is really needed
```javascript
store.commitCallbacks = [...store.commitCallbacks, cb];
```
vs
```javascript
store.commitCallbacks.push(cb);
```
But it's ok

**Comment by Marc-Roig** [comment]
@nathan-pichon you are right, I changed it to push, don't know why I used the spread to begin with 🤔

**Pull request merged**
