### PR TITLE
Fix generate:api causing GraphQL to break

### LINKED ISSUE #3467: Strapi generate:api replaces "_" with " " causing GraphQL to break
**Describe the bug**
`strapi generate:api` prevents Strapi from starting if used with attribute names containing "_".

**Steps to reproduce the behavior**
1. `strapi -- generate:api stuff cms_name:string´
2. `strapi develop` or `strapi start`

Get this error:
```
[2019-06-16T10:13:18.489Z] debug ⛔️ Server wasn't able to start properly.
[2019-06-16T10:13:18.491Z] error GraphQLError: Syntax Error: Expected :, found Name "name"
```

Probable reason: strapi generate:api replaces "_" with " ", which messes up GraphQL syntax.

**Expected behavior**
strapi and plugins should work with all names `generate:api` generates. `generate:api` should either respect "_" or fail if names include underline.

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0@beta.3
- Database: Postgres
- Operating system: MacOS

### PR DESCRIPTION
**Pull request by dev-drprasad**
#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [x] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

closes #3467

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello @dev-drprasad!
Did you test to create a new application using this generator?

Because I'm not sure it will work.
[Here](https://github.com/strapi/strapi/pull/3495/files#diff-be3098adb9349b5b946a63f46bfe55cfL74) is a condition if `attribute` is a **String**. So your code can't work.

**Comment by alexandrebodin** [comment]
Hi  @dev-drprasad.

Are you planning  on updating this PR ?

**Comment by dev-drprasad** [comment]
@alexandrebodin Sorry I didn't have time. Let some one take the issue

**Comment by alexandrebodin** [comment]
@dev-drprasad Thanks for your time I'll closing this PR for now then :)

**Pull request closed without merging**
