### PR TITLE
Fix custom settings override

### PR DESCRIPTION
**Pull request by markkaylor**
### What does it do?

Fixes the settings override in the documentation plugin

Completes the work started on: https://github.com/strapi/strapi/pull/12070 and https://github.com/strapi/strapi/pull/12341

co-authored by: @kayac-chang @roelbeerens 

### Why is it needed?

The settings override doesn't work...

### How to test it?

Create a file at `./extensions/documentation/config/settings.json` copy [this](https://docs.strapi.io/developer-docs/latest/plugins/documentation.html#settings) and edit the fields you want to modify

### Related issue(s)/PR(s)

closes: https://github.com/strapi/strapi/pull/12341
closes: https://github.com/strapi/strapi/pull/12070 
closes: https://github.com/strapi/strapi/issues/12046
closes: https://github.com/strapi/strapi/issues/11840

### CODE REVIEW

**Comment by remidej** [comment]
Would this close #11840 too?

**Comment by ly95** [comment]
still not work after upgrade v4.0.8

**Comment by markkaylor** [comment]
I just tested on v4.0.8 and it is working. @ly95 If you are still having issues could you please provide information about your environment and steps to reproduce.

**Comment by ly95** [comment]
@markkaylor I followed the [doc](https://docs.strapi.io/developer-docs/latest/plugins/documentation.html#settings) exactly. But plugin users-permissions section is not generated.

**Comment by p4bloch** [comment]
Hey there @markkaylor. Tracked down a bug I see which I believe was introduced here. The documentation points out that you can prevent plugins from being generated by sending `plugins: []` but given how `_.merge` works that will never beat the default value of `['email', 'upload']`. And if you remove the key or pass null, which effectively wins, it will render every plugin.

I've been playing a little bit with `mergeWith` which accepts a customizer but I'm not convinced targeting the `plugins` key directly to handle this is the way to go. Thoughts?

**Comment by markkaylor** [comment]
Hi @p4bloch thanks for bringing this up. I was not aware of this particular issue but I have realized that the final merge is far from perfect. 

I am currently working on re-introducing the overrides system which currently doesn't work on v4. Not yet sure exactly the approach we will take for generating the final documentation file but it will probably use `mergeWith` with a customizer as you suggested and should resolve the issue you have brought up.

**Comment by p4bloch** [comment]
Oh, thank you for clarifying that @markkaylor. I wasn't expecting this not to work with v4 based on what I saw in the docs so this makes sense now. The only minor thing I noticed is that the `pluginsForWhichToGenerateDoc` which is documented is not referenced anywhere in this plugin so we may want that removed from the docs when that gets updated.

**Pull request merged**
