### PR TITLE
Fix some many many perf issues in graphQL

### PR DESCRIPTION
**Pull request by alexandrebodin**
Test fix for many many perf issues

### CODE REVIEW

**Comment by abdonrd** [comment]
Yeah! I just tried locally and it seems to solve this problem: https://github.com/strapi/strapi/issues/8552#issuecomment-770388720

**Comment by derrickmehaffy** [comment]
@abdonrd if possible can you run some query speed tests against 3.4.1, 3.4.2, and this fix?

I'm hesitant to suggest it's a fix, but a start in the right direction. (Certainly this helps, but I don't have near the data sample size you do to get numbers)

**Comment by abdonrd** [comment]
Strapi `v3.4.1`:
Screenshot 2021-02-02 at 09 15 08

Strapi `v3.4.2`:
Screenshot 2021-02-02 at 09 13 15

Strapi `v3.4.5` with this fix:
Screenshot 2021-02-02 at 09 06 41

**Comment by derrickmehaffy** [comment]
Wow 47 seconds down to 9ms that is quite the improvement

**Comment by abdonrd** [comment]
> Wow 47 seconds down to 9ms that is quite the improvement

It is! haha

**Review by derrickmehaffy — APPROVED** [review]
LGTM

**Comment by derrickmehaffy** [comment]
This pull request has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/new-release-strapi-v3-4-6/2631/1

**Pull request merged**
