### PR TITLE
Fixed that SSO didn't work in some environment

### PR DESCRIPTION
**Pull request by ryubro**
My PR is a 🐛 Bug fix that SSO didn't work in some environment, though it worked on the React example in the initial phase.

Main update on the Plugin

### The SSO works on initial registration but not on re-login

In the [React SSO example project](https://github.com/strapi/strapi-examples/tree/master/login-react/react-login-front-end-app) I could login with Microsoft account for the first time, but not for the second time.

There were two places that caused this bug

#### No `provider` in the user model

while [the provider service uses `user.provider` to decide if the user already exists or not](https://github.com/strapi/strapi/blob/ebd60f93cc265eb5183f21c495b59acdf6c37e4c/packages/strapi-plugin-users-permissions/services/Providers.js#L71-L73), [the model doesn't have `provider` field anymore](https://github.com/strapi/strapi/blob/ebd60f93cc265eb5183f21c495b59acdf6c37e4c/packages/strapi-plugin-users-permissions/models/User.settings.json) hence, it always think the user exists but it's not registered with the requested provider resulting to respond `Auth.form.error.email.taken` error.

The `provider` was somehow removed in this commit: https://github.com/strapi/strapi/commit/688defca708bfab951e481b5e27005db2b9c377a#diff-18cc44092da248f6a77fa8e1c3840153

I re-added provider field: https://github.com/strapi/strapi/commit/17d5e295b53953a97fb5636ba8f373d7ff60a4fe

#### Bootstrap code of content manager mutates global strapi model

After I added `provider` in the model, somehow the user data which was created by registration via SSO still lacked `provider` field. After adding a few break points, I found [the bootstrap code in content manager mutates the global strapi.models object](https://github.com/strapi/strapi/blob/ebd60f93cc265eb5183f21c495b59acdf6c37e4c/packages/strapi-plugin-content-manager/config/functions/bootstrap.js#L108).

I fixed this particular bug in the following commit:  https://github.com/strapi/strapi/commit/4beab15bc391a999ec08361e45711e51dbba8484

Though the commit fixed the issue that I was experiencing, I worry that we may have similar bugs somewhere in the module as we mutate objects here and there. I think it's good to refactor so that it doesn't mutate objects, but probably in another PR.

~### SSO didn't work when Strapi app is hosted in `https` server~

~I found that the callback URL which Strapi sends to SSO auth server always starts with `http` even when it's hosted on https server. That's because [the protocol was hardcoded to 'http'](https://github.com/strapi/strapi/blob/ebd60f93cc265eb5183f21c495b59acdf6c37e4c/packages/strapi-plugin-users-permissions/controllers/Auth.js#L151-L154). I found a few more places where `http` was hardcoded, but I fixed only the part where SSO matters because that's what I could test.~

~I fixed it in the following commit: 
https://github.com/strapi/strapi/commit/12cc6d6039292116f868caff73a36f551117e2c4~

~I assumed that `process.env.PROTOCOL` would be a good place to set whether the server is 'http' or 'https', but let me know if you prefer different variable.~

~There is another bug that the actual callback URL that Strapi sends to SSO auth server is different from what user can see from the settings screen, but this isn't blocking user to use SSO and can be fixed in another PR, I guess.~

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@ryubro the protocol was removed as strapi itself doesn't allow the server to be run using https, I was the one who added the proxy code, and attempted (and failed many times) to migrate the providers to use the proxy URI instead of the typical localhost one. https://github.com/strapi/strapi/pull/1851

The providers need to be changed to use the proxy URI but the proxy stuff also needs to be modified so that it doesn't construct the two common URIs for ports 443/80

IE `https://api.example.com:443` and `http://example.com:80` all other ports are fine and should be generated this way.

The Proxy bit itself defines this, if the proxy is enabled that information should be used to construct the URI, else it should fallback to the strapi server settings (always http in that case)

**Comment by derrickmehaffy** [comment]
See this PR for my proxy bit: https://github.com/strapi/strapi/pull/1813

**Comment by derrickmehaffy** [comment]
But related to the hard coded http stuff I have talked to @Aurelsicoko about this and all of those references need to be changed over to use the proxy settings if enabled else fall back to usual env settings

**Comment by ryubro** [comment]
Thank you @derrickmehaffy for the explanation. My environment is Azure web app and I could just set the `process.env.port` to 443 to make Strapi to listen to the port in the production environment. If Strapi itself doesn't support https, maybe there is a layer that magically makes all the encrypted packets into decrypted ones in Azure. I'm not really familiar with using SSL with proxy server but, if I may guess roughly, proxy server does the same thing - communicating encrypted packets with client but decrypted packets with app -, doesn't it?

But to the practical point, now I see that the protocol issue is already being handled in another PR, #1851. Do you want me to revert the part regarding protocol from this PR?

**Comment by derrickmehaffy** [comment]
@ryubro yeah it is extremely common with nodejs applications to use an external proxy such as Nginx or Apache for SSL as node doesn't really have a good way to deal with SSL certificates. Typically node will push over http and you use Nginx to proxy public SSL traffic to localhost http (or just internally) this also allows for load balancing/fail over clustering.

I'll be honest in my PR to fix providers, I am a bit stalled at the moment. I don't really have the required skills to fix that. Both @lauriejim did try and trouble shoot it but we kept getting odd redirects.

All the proxy code does is overwrite URIs that are used externally by clients (think of it like giving your street address to the client not your GPS latitude /longitude)

The problem is when used in production many of the oauth² providers don't support non-ssl connections and many plugins like upload were giving localhost address for files (or http addresses).

Honestly if you wanted to dive deeper into the problem with providers and modify them to use the proxy stuff it would be great. My suggestion was to break each provider into it's own plugin and move from grant/purest to passport.js. but that is a major change way above my skill level.

**Comment by derrickmehaffy** [comment]
FYI this might help you understand Nginx (fair warning I haven't proof read this yet)

https://medium.com/@derrickmehaffy/using-strapi-in-production-with-https-717af82d1445

**Comment by ryubro** [comment]
Thank you again for the explanation and transparency, @derrickmehaffy.

> All the proxy code does is overwrite URIs that are used externally by clients (think of it like giving your street address to the client not your GPS latitude /longitude)
>
> The problem is when used in production many of the oauth² providers don't support non-ssl connections and many plugins like upload were giving localhost address for files (or http addresses).

Maybe one more question that is quite similar to https://github.com/strapi/strapi/pull/1851#issuecomment-419486274: why do we need separate settings for server and proxy? Let's say that the node app is running on `http://localhost:1337` and the web server maps the app to `https://example.com:443`, does Strapi need to know the internal URL, `http://localhost:1337`? To me the issues about oauth2 and upload plugin should be resolved if we just set the server address as `https://example.com:443` instead of `http://localhost:1337`, or please enlighten me if I missed something.

**Comment by derrickmehaffy** [comment]
@ryubro the problem is setting it as https:443 is Strapi doesn't have an SSL certificate (required for SSL) and it has no way to manage them. There are options for SSL in nodejs but it is extremely ugly and very difficult to manage.

It is basically an industry standard if you want SSL for nodejs you have to use an external proxy. But yes short answer is, strapi does need to know where it is actually running (passes it to the OS that it is running on localhost) as you shouldn't be running it on a public facing port.

The second issue is, at least on linux, you cannot run services on ports lower than 1024 without being the root user or having root permissions. It is a huge security risk running application as root if you don't have to, thus if you change strapi to run on 443, it will do so locally and thus will need to run as root.

(Just as a side note, I am a System Admin and a Network Engineer as a day job :wink: so security is basically what I do all day :rofl: )

**Comment by derrickmehaffy** [comment]
> The second issue is, at least on linux, you cannot run services on ports lower than 1024 without being the root user or having root permissions. It is a huge security risk running application as root if you don't have to, thus if you change strapi to run on 443, it will do so locally and thus will need to run as root.

For instance if someone managed to inject malicious code into a dependency of strapi which has happened in the past, it would very easy for someone to gain a local shell on your server if Strapi is running as root. IE not a good idea.

**Comment by derrickmehaffy** [comment]
Realistically you should run Strapi locally on the server, firewall off direct access to it and pass all traffic from the web through the proxy (Load balancing, failover, caching, ect) to localhost IE strapi.

**Comment by ryubro** [comment]
@derrickmehaffy 

Oh sorry, it was a silly question.

I understand that node web app should run behind the proxy server, my question was what if we just configure the server setting like it runs on `https://exmpale.com:443` while it actually runs on `http://localhost:1337`. I just realised that we cannot configure the server port 443 and make the app to listen to 1337. Sorry, again, it was a silly question.

Then I think it's best that I'll remove the protocol part of this PR and look into #1851 to see if anything I can do about it.

**Comment by ryubro** [comment]
I removed the protocol part from this PR as it is already being addressed in #1851.

This PR still should fix that the SSO only works when the user first register but not when he re-login.

**Comment by derrickmehaffy** [comment]
Awesome thanks @ryubro If you want to look into that providers PR please let me know if you have any questions.

I've kind of thrown it on the back burner for now until the Strapi team figures out their next steps with the plugin framework. I'll take a look at your changes here though to see if I notice anything else. 

Thanks for letting me ramble on :rofl:

**Comment by Aurelsicoko** [comment]
@soupette Can you test this one?

**Comment by soupette** [comment]
@ryubro If the code mutates the global strapi models wouldn't it be better to do the following  so we're sure that the algorithm doesn't mutate the `strapi` global object?


```
const strapiClone = _.cloneDeep(strapi);
const pluginsLayout = Object.keys(strapiClone.plugins).reduce(...);
const tempLayout = Object.keys(strapiClone.models).filter(...);
const models = _.mapValues(strapiClone.models, pickData);
// ...
```

**Comment by ryubro** [comment]
Hi @soupette,

I believe `_.cloneDeep(strapi)` will guarantee any mutation on global `strapi`, but I'm bit hesitating to do so.

I personally believe that paying more attention not to mutate any object unintentionally - or not to mutate at all - is enough to avoid mutation issues. `_.cloneDeep` is not efficient in terms of resource, especially if we consider that this may need to be applied on every bootstrap code.

But I also understand that writing code with resource optimization in mind is not really worth the effort in modern world, most of the time.

That's why I thought that making this module - or potentially other similar modules - less vulnerable to mutating global object deserves a separate PR.

How do you think?

**Comment by jeremie-olivier** [comment]
Hi @ryubro, I've tested your PR and it doesn't seem to fix the `Auth.form.error.email.taken error.` error yet

I've tried only with google auth provider

**Comment by ryubro** [comment]
Hi @jeremie-olivier,

Thank you for testing this PR. I tested from the scratch again, but it's weird that it still works for me.

If you still have the project that you tested on your machine, could you push the code and share the link for me, please?

**Comment by ryubro** [comment]
@jeremie-olivier,

BTW, was the user that you tested registered before you do the test? This fix only works if the user is also registered with this fixed version.

If you haven't, can you start from the clean database?

**Comment by jeremie-olivier** [comment]
@ryubro Ok by bad, I just tried again and it's working well. Thanks for this !!!

**Pull request merged**
