### PR TITLE
Change implementation for create/remove symlinks

### PR DESCRIPTION
**Pull request by maturanomx**
From JavaScript to BASH significantly reducing LOC making simple understand what is happening.

---
My PR is a: 💅 Enhancement

Main update on the: Framework

## Description
In my process of understanding the operation to publish a new version, I came across with the `createsymlinkdependencies` & `removesymlinkdependencies` scripts. 

Upon understanding its purpose, I realized all that JS logic can be reduced in a line with the command `sed`. So, I create this PR to show how the implementation would be.

## Pros
- The obvious code reduction seeks less mental waste in understanding the purpose. Now includes comments explaining what the script does 😛 
- Although I have not made measurements, it is highly probable that there will be a reduction in execution time.
- With this implementation, create and removing don't produce "false changes" with EOL. Attached screenshot below.

## Risks
~~I know all the core developers are working on MacOS, and I know there are an incompatibility issue for inline replacements with `sed`. Although this could be easily solve installing the GNU version (`brew install gnu-sed --with-default-names`), I decided add a "extra-step" (create and remove backup files) with the intention to have a transparent implementation. However, **I have not tested if works on MacOS** (I don't have one 😋)~~

~~**This will not work under Windows** without BASH; meaning an Windows user should install an Unix environment like Cygwin, WSL a VMs, or similar. (I'm pro-promote this).~~

Changed to use `shelljs` to make it multi-platform.

## How it was tested
I run the task `npm run createsymlinkdependencies` both in the original and this implementation and checked there were no differences in the result. The ones that were there is because of the difference of the EOF in some files. Attached screenshots and the result of the outputs.

## Additional comments
This is a result of what I saw and what I know, but I have the feeling that this can be done using `lerna`.. From what I've seen so far, this is precisely the problem that seeks to solve. I will keep this in mind.

---

### Proofs
* Results of running `createsymlinkdependencies` and then `removesymlinkdependencies`. On the left this PR; on the right the code from this repository (the differences are just on EOLs)
createandremove

* `npm run createsymlinkdependencies`
createsymllink

* ` npm run removesymlinkdependencies`
removesymlink

* Outputs: https://gist.github.com/maturanomx/a74220c694d71f1ddb1476b4ce1dad99

### CODE REVIEW

**Comment by maturanomx** [comment]
Need to solve a linter problem before been merge 😖

**Comment by Aurelsicoko** [comment]
@lauriejim Is this working as expected? I don't have enough skill in bash to completely understand how it works. However, it seems awesome 🎉 

@maturanomx Excellent work! This will certainly speed up the setup time 💪

**Comment by derrickmehaffy** [comment]
@Aurelsicoko `sed` is just a commandline "search and replace" with the rest of it being basically regex to quickly replace everything :stuck_out_tongue_closed_eyes:

**Comment by Aurelsicoko** [comment]
@derrickmehaffy I suspected something like this 🙈

**Comment by lauriejim** [comment]
@Aurelsicoko Have to be tested before the end of the week.

**Comment by maturanomx** [comment]
> As you specify @maturanomx for MacOS users we have to install sed

You mean doesn't work out of the box? :thinking: :cry:. If that's the case, and if GNU's `sed` will be a requirement (not a big deal; it's the common as far as I know), I would like to remove the creation of temporary files; that will improve the performance. What do you think?

**Comment by maturanomx** [comment]
On 2c7311b5d563db4b3d7fcd28841ec5214ee35d8b along with adding the note, I also remove the compatibility workaround. Can you test it and let me know what you think?

**Comment by maturanomx** [comment]
I saw [a travis job fails](https://travis-ci.org/strapi/strapi/jobs/426451446) but apparently was by a Travis issue, not for the commit. On my repository [passes without problem](https://travis-ci.org/maturanomx/strapi/builds/426451432).

I think you can re-run the job, isn't?

**Comment by maturanomx** [comment]
### IMPORTANT

This will not work under Windows without installing an Unix environment. I clarify this because I saw other PRs to promote the Windows compatibility.

If that is a requirement, I think we can use `shelljs`, but that will not be as performant as the "native" solution. IMHO, seeking for Windows support is mostly expend time of development and do the application slower.

Let me know if should modify this to make it work on Windows.

**Comment by Aurelsicoko** [comment]
@maturanomx It's very important to make sure the setup works also on Windows. It's the main reason we are using ShellJS btw...

**Comment by maturanomx** [comment]
Yeah... There was no need to ask, sorry for that. I'll make the changes to support Windows.

I just wanna make a point, but not the place or time

**Comment by maturanomx** [comment]
Done with `shelljs`. Tested with the same results 👍 🎉

**Comment by lauriejim** [comment]
I think you have to update `package.json` script `clean:all` to install dependencies before running `remove symlinks`.

`"clean:all": "npm install && npm run removesymlinkdependencies && rm -rf package-lock.json && rm -rf packages/*/package-lock.json && rm -rf packages/*/node_modules",`

If we don't do that, `shelljs` is not installed and we got this error

```

> @3.0.0-alpha.14.1.1 removesymlinkdependencies /home/ubuntu/strapi
> node ./scripts/removeSymlinkDependencies.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/ubuntu/strapi/scripts/removeSymlinkDependencies.js:7:15)
```

**Comment by maturanomx** [comment]
> I think you have to update package.json script clean:all to install dependencies before running remove symlinks.

I added it as a `preclean:all` hook, to avoid make those lines longer. Also, I took the opportunity to reduce those lines (`{one,two}` means "one or two" in  BASH.

---

However, I have to say it, IMHO this is an example of how we are breaking the KISS principle. This commands is doing too much, that complicates the things instead of make them easy.

I just introduce a `npm install` before `clean:all` ... for then do another `npm install` **after** the `clean:all`, and another one for the packages. Just to "avoid" write it manually? 😕 

This could be a PITA for CI environments (it is for me now; it is doing an automatic `npm install`, another one 😫). And, with this, we are limiting the options of use something like `npm ci` that could reduce a lot the time of the installation of dependencies...

But well... just a reminder that this could be done with one line of BASH.

---

If you want, I could also do a proposal reducing the complexity of the original code with vanilla JS (no `shelljs` dependency, not another `npm install`). Let me know, without a problem 😃

**Comment by maturanomx** [comment]
I'm closing this. The intention was simplify the logic, but with the actual architecture it's complicate do that.

Keep it in mind.

**Comment by maturanomx** [comment]
> Are you sure about the decision to close the PR?

Yeah... for know. This arise --at least to me-- a bigger problem. I'll keep it in mind if I have time.

You are doing an excellent job 👍 Thanks to you for this 😄

**Pull request closed without merging**
