### PR TITLE
Grammar and punctuation

### PR DESCRIPTION
**Pull request by bartduisters**
#### Description of what you did:

Grammar and punctuation

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [x] Documentation
- [ ] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@bartduisters in the future please and push all your typo fixes in one pull request. Also your commits have not been signed off

**Comment by bartduisters** [comment]
@derrickmehaffy I click on 'Improve this page' at the bottom of each page and correct all the mistakes on that specific page as I go through the documentation.

I was going through all the pages available, what you suggest now is to do the full documentation in one PR? Might take a while then.

**Comment by derrickmehaffy** [comment]
Yes please try and include all your fixes in one PR. It's far easier to review and won't spam the PR list with 1,000 tiny fixes.

**Comment by lauriejim** [comment]
Can you please valid the DCO. Thank you.

**Comment by bartduisters** [comment]
I'll first do the rest of the work of translating and then sign the DCO on the final PR. I'll close this PR for now.

**Pull request closed without merging**
