### PR TITLE
[Documentation] Split providers and grant config to a new file

### PR DESCRIPTION
**Pull request by abdonrd**
### What does it do?

Split providers and grant config to a new file in the documentation.

### Why is it needed?

Follow the #8741

### CODE REVIEW

**Review by derrickmehaffy — APPROVED** [review]
LGTM

**Comment by derrickmehaffy** [comment]
Don't merge until https://github.com/strapi/strapi/pull/8741 is merged

**Comment by derrickmehaffy** [comment]
@abdonrd this one needs to be targeted to the master branch as it follows an unreleased code change. Can you please set the branch to master and rebase as needed to remove any extra commits?

**Comment by abdonrd** [comment]
@derrickmehaffy done!

**Comment by derrickmehaffy** [comment]
Sorry @abdonrd for the trouble, can I please have you move this PR over to our new docs repo? We are removing the docs from this one.

https://github.com/strapi/documentation

Ignore the contributing guide over there and set the target as the `main` branch.

**Comment by abdonrd** [comment]
@derrickmehaffy done at https://github.com/strapi/documentation/pull/27

**Pull request closed without merging**
