### PR TITLE
Setup in monorepo bypass build cache

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

Adds --skip-nx-cache to the monorepo setup script

### Why is it needed?

The setup script is the recommended way to set up the monorepo after (for example) switching between branches. However, the cache gets confused quite often right now and results in the need for running 'yarn build --skip-nx-cache' manually

Ideally, we should investigate why ~~the clean is not cleaning (as Marc points out below, clean is actually just cleaning dist folder, so nevermind)~~ / the cache is overzealous and fix that, but this is a quick fix to ensure `yarn setup` is the safest way to build completely.

It shouldn't slow things down unnecessarily because we're already intending to clean everything (hence why we run yarn clean first)

### How to test it?

Run `yarn setup` and it should build now even when the build cache is wonky

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by Marc-Roig** [comment]
I believe yarn clean only removes each package dist folder not the nx cache folder. Normally is located inside a .nx/cache folder. But I can not find it in my local repo 🤔 

There is also another command called nx reset , which just removes the local cache https://nx.dev/core-features/cache-task-results#clear-the-local-cache

But I believe your approach will just be faster and do the same

**Review by Marc-Roig — APPROVED** [review]

**Comment by Marc-Roig** [comment]
Also, do you recall if we have any shared NX cache for our CI? If we do this might increment the CI time

**Comment by innerdvations** [comment]
> Also, do you recall if we have any shared NX cache for our CI? If we do this might increment the CI time

Hmm. You might be right there. I'll do some more investigation when I have some time.

**Review by joshuaellis — APPROVED** [review]
We do really need to fix NX, think we can look at that before merging V5 when circular deps are also fixed 👍🏼

**Review by Convly — APPROVED** [review]
> Also, do you recall if we have any shared NX cache for our CI? If we do this might increment the CI time

Don't have an answer to that, but the changes LGTM

**Comment by innerdvations** [comment]
Looks like the CI is:

- using build and not setup
- the build command being used is already using skip-nx-cache

So I'll go ahead and merge this, but if anyone notices any adverse effects on CI times post here and we can revert.

**Pull request merged**
