### PR TITLE
Fix graphql me query on sql databases

### LINKED ISSUE #2867: Cannot query "me" because of undefined model
**Informations**
- **Node.js version**: v10.9.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.21
- **Database**: MongoDB
- **Operating system**: mac os

**What is the current behavior?**

When I try to query "me" from graphql ui, I get the error "Cannot read property 'associations' of undefined'". The error :

```
{
  "errors": [
    {
      "message": "Cannot read property 'associations' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "me"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'associations' of undefined",
            "    at .../api/plugins/graphql/services/Query.js:270:32",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": {
    "me": null
  }
}
```
**Steps to reproduce the problem**

Query "me" from graphql ui with this query : 

```
{
   me {
      _id
      username
      email
   }
}
```
and the headers : 

```
{
   "Authorization": "mytokenhere"
}
```
**What is the expected behavior?**

Returning the user with selected fields :

```
{
  "data": {
    "me": {
      "_id": "xxxxxxx",
      "username": "username",
      "email": "email"
    }
  }
}
```
**Suggested solutions**

Do not care about population when model is not defined :

```
const _populate = model 
   ? model.associations.filter(a => !a.dominant && _.isEmpty(a.model)).map(a => a.alias)
   : [];
```

### PR DESCRIPTION
**Pull request by derrickmehaffy**
#### Description of what you did:

The schema for GraphQL in the users-permission plugin was forcing the use of `_id` instead of the database agnostic `id`.

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #2867 
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [x] MongoDB
- [x] MySQL
- [x] Postgres
- [x] SQLite

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Test from my own project on beta.13 with the modification applied (MySQL): 
image

**Comment by alexandrebodin** [comment]
That break with mongo

**Comment by derrickmehaffy** [comment]
@alexandrebodin Mongo should be using `id` also no? O_o

**Comment by derrickmehaffy** [comment]
Just tested on a mongo test setup on Vultr:

image

image

**Comment by alexandrebodin** [comment]
It doesn't work on non edit users because the id key is not in the user object you need to add a result for this type that will get _id or id :)

```js
resolver: {
    UsersPermissionsMe: {
      id(obj) {
        return obj.id || obj._id;
      },
    },
}
```

This won't be necessary anymore soon ;) but for now no choice but to have it

**Pull request merged**
