### PR TITLE
test(releases): setup test harness for working with the admin app

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* adds jest setup file for MSW to be used across plugin
* adds render & render hook harness with common things like `NotificationProvider` / `Redux Store (with permissions)` /  `IntlProvider` / `MemoryRouter` – no need to mock things like RBAC etc.

### Why is it needed?

* consistent test harness for the entire app to work with

### CODE REVIEW

**Comment by joshuaellis** [comment]
@simotae14 ask any questions you might have! :)

**Comment by simotae14** [comment]
@joshuaellis thanks a lot for the precious help, I am gonna fix some conflicts I have in content-releases/release-details-redirect-after-creation and if it is ok for you I can try to add some unit test for the submit action here, thanks again

**Comment by joshuaellis** [comment]
> @joshuaellis thanks a lot for the precious help, I am gonna fix some conflicts I have in content-releases/release-details-redirect-after-creation and if it is ok for you I can try to add some unit test for the submit action here, thanks again

Yep, i'm going to leave this PR to you now to solve & merge 👍🏼 feel free to reach out if you run into issues, but i won't be leading this anymore ⭐

**Review by Feranchz — APPROVED** [review]
This is really great, thank you @joshuaellis & @simotae14

I'm approving this because I ran the tests (both front & back) locally and they pass all. But not idea why here they are not passing. The errors here looks like unrelated but we should try to understand what is happening 🤔

**Pull request merged**
