### PR TITLE
fix[documentation] changed id type to integer && updated [ru] translation

### PR DESCRIPTION
**Pull request by oanogin**
### What does it do?

Just changed the id type from 'number' to 'integer'.

### Why is it needed?

Actually, it's wrong to think about id like a `number`, because it has more concrete type - `integer`. 
You should use `number` in openapi spec only in cases when you don't know for sure which format of `number` it could be (ex: float, decimal, integer). 
But in case of Strapi: we completely sure that id field is `integer` and it cannot be anything else.

For example, openapi-codegen generates `*float32` in Golang for id field when it has `number` type.... and it's correct behaviour, so we need to fix this typing issue here.

### How to test it?

Add documentation plugin and trigger openapi spec generation.
Then you will see that all `id` fields have type `integer`

### CODE REVIEW

**Comment by oanogin** [comment]
Hi @joshuaellis, I also have a question related to documentation plugin.
Do you plan to change `POST /api/upload?id=x` to `PUT(PATCH) /api/upload/:id` in future?

Coz this behaviour breaks all the generators, they return an error looks like:
```
error generating code: error creating operation definitions: path '/upload?id={id}' has 1 positional parameters, but spec has 0 declared
```

I'm pretty sure you know about this issue, caused by incorrect REST API `architecture`.
Also I haven't found a way to omit this path ('/upload?id={id}') in openapi generation, so I had to disable `upload` plugin at all by `x-strapi-config` config property.

Thanks a lot :)

**Review by markkaylor — APPROVED** [review]
Looks good to me. Thanks for the PR. In the future please submit separate PRs instead of one PR with several unrelated changes. It can help us review and merge quicker :)

**Comment by markkaylor** [comment]
@oanogin Could you please update the test snapshot for the documentation plugin to fix the failing tests?

**Comment by alexandrebodin** [comment]
Hello @oanogin 

I'm going to close this PR as being staled. Feel free to reopen it against the `develop` branch. 

FYI please make 2 distinct PR between the translations & the documentation plugin code 🙌

**Pull request closed without merging**
