### PR TITLE
Fix issue with duplicate model folder getting created when generating model with api option

### LINKED ISSUE #3694: strapi generate:model creates extra model folder
**Describe the bug**
while running CLI command "strapi generate:model category --api product" it generate model folder inside api/product/model

**Steps to reproduce the behavior**
1. Go to strapi CLI 
2. Run strapi generate:model category --api product to generate new model inside existing product api

**Expected behavior**
ignore creating new model folder if existing already

**System**
- Node.js version: v10.15.3
- NPM version:6.4.1
- Strapi version: 3.0.0-beta.14
- Database: MongoDB
- Operating system: Windows 10

**Additional context**

### PR DESCRIPTION
**Pull request by shabab477**
Refers to Issue fix #3694 

When generating model with strapi cli with the api option flag two model folders are created whereas only one should have been created. Description in the issue link. This PR should fix that issue. 

strapi-without-bug

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [x] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by shabab477** [comment]
Hi @derrickmehaffy, new contributor here. Is there any reason for my code failing to pass the CI build for Postgres? If so what can I do in my code to make it work.

**Comment by derrickmehaffy** [comment]
It's likely unrelated, I'll force the travis to restart and let it try again.

**Comment by shabab477** [comment]
Thanks

**Comment by derrickmehaffy** [comment]
There we go, it passed :P

**Comment by shabab477** [comment]
Yesss it did! Feels really good :P

**Comment by shabab477** [comment]
Welcome @lauriejim!!

**Pull request merged**
