### PR TITLE
Fix auto-reload on file change

### LINKED ISSUE #1782: Server does not restart when a file is updated since the v3.0.0-alpha.13.1 migration
**Informations**
- **Node.js version**: v9.10.0
- **npm version**: v5.6.0
- **Strapi version**: v3.0.0-alpha.13.1
- **Database**: Mongo
- **Operating system**: Mac OS High Sierra 10.13.3

**What is the current behavior?**
Since the migration v3.0.0-alpha.13.1. When I start the local server and I edit a file (a controller for instance) the app detect changes but the the server never restart. 
```
api_1  | [2018-08-21T20:27:55.438Z] info File changed: /usr/src/api/api/bootstrap/controllers/Bootstrap.js
api_1  | [2018-08-21T20:28:00.442Z] info File changed: /usr/src/api/api/bootstrap/controllers/Bootstrap.js
api_1  | [2018-08-21T20:28:05.456Z] info File changed: /usr/src/api/api/bootstrap/controllers/Bootstrap.js
api_1  | [2018-08-21T20:28:10.461Z] info File changed: /usr/src/api/api/bootstrap/controllers/Bootstrap.js
```

**Steps to reproduce the problem**

1. `strapi start`
2. Edit a file from your api

**What is the expected behavior?**

The dev server have to restart when when a file is updated

### PR DESCRIPTION
**Pull request by lauriejim**
My PR is a: 🐛 Bug fix 

Main update on the: Framework

Fix #1782

### CODE REVIEW

**Comment by vokvince** [comment]
Could you please merge?

**Comment by lauriejim** [comment]
I miss to send review request to @Aurelsicoko. Will be merged when the review will be done.

**Comment by Aurelsicoko** [comment]
The code looks good to me, @lauriejim can you make sure it works well with the GraphQL plugin?

**Comment by lauriejim** [comment]
I test with and without during the development.

**Pull request merged**
