### PR TITLE
Refactor Mongoose connection options and add debug

### PR DESCRIPTION
**Pull request by derrickmehaffy**
Signed-off-by: Derrick Mehaffy <derrickmehaffy@gmail.com>

### What does it do?

Refactored the mongoose connection options to allow for custom options in the mongo driver, also added mongoose debug

### Why is it needed?

We only allowed for a very small subset of mongodb options

### Related issue(s)/PR(s)

N/A

### CODE REVIEW

**Review by petersg83 — APPROVED** [review]
LGTM ! Have you planned to update the doc too?

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
the connectivity file is only used for the cli to test the connection it is not the actual connection when the app is started. This one is handled in the index.js file of the connector.

**Comment by derrickmehaffy** [comment]
> LGTM ! Have you planned to update the doc too?

Yeah I'll update the doc also



> the connectivity file is only used for the cli to test the connection it is not the actual connection when the app is started. This one is handled in the index.js file of the connector.

Ah thank you, I'll update that one as well

**Comment by derrickmehaffy** [comment]
Don't have time to finish right now, marking as closed.

**Pull request closed without merging**
