### PR TITLE
Cleanup and normalize package.json files

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Cleaning up package.json files

### CODE REVIEW

**Review by Elhebert — APPROVED** [review]
LGTM. Just a minor ting:

the `author` and `maintainer` fields are not consistent in all the packages. Some are listing "A Strapi developer", "Strapi solution" or "Strapi team". And the email/url are not always filled in.

Might be a good idea to tackle that.

**Review by petersg83 — APPROVED** [review]
LGTM !

**Comment by alexandrebodin** [comment]
> LGTM. Just a minor ting:
> 
> the `author` and `maintainer` fields are not consistent in all the packages. Some are listing "A Strapi developer", "Strapi solution" or "Strapi team". And the email/url are not always filled in.
> 
> Might be a good idea to tackle that.

Agreed I'll merge this one if you are up for it you can update the author / maintainer fields @Elhebert

**Comment by abdonrd** [comment]
Maybe you want to use https://github.com/shellscape/prettier-plugin-package ?

**Pull request merged**
