### PR TITLE
Allow null values on manyToMany and manyWay to set empty array

### PR DESCRIPTION
**Pull request by JelmerV-WFC**
Fixes: #4109 

#### Description of what you did:
Fixes possibility to set null values for manyToMany and manyWay relation types.

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [x] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [X] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by JelmerV-WFC** [comment]
> Can you apply the same logic to bookshelf please :)

Does bookshelf has the same issue? I think the `transformToArrayID` function will return an empty array already if the value is not an array.

**Comment by JelmerV-WFC** [comment]
Maybe we should implement a same kind of function as `transformToArrayID` for mongoose also? Maybe better to handle this the same way as in the bookshelf hook.

**Comment by alexandrebodin** [comment]
@JelmerV-WFC We are rebullding the database as we speak so better not spend to much time on this for now ;)

**Comment by JelmerV-WFC** [comment]
@alexandrebodin haha okay, then we leave it like this. Thanks for the merge :)

**Pull request merged**
