### PR TITLE
Make cron jobs specific for each environment

### PR DESCRIPTION
**Pull request by marcoautiero**
### What does it do?
This PR makes cron jobs configuration specific for each environment and not merged with the default configuration.

### Why is it needed?
Edit the server configuration in `config/server.js` enabling cron jobs and defining some tasks; create a new configuration like `config/env/production/server.js`, enabling cron jobs and defining some tasks. At the moment, the tasks defined in `config/server.js` will be merged with the ones defined in `config/env/production/server.js`. That is not correct, because in production will be included the tasks defined in development, while the tasks should be specific for each environment and not merged.

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @marcoautiero,

The configuration in config/server.js are not development configuration but default ones. If you want to have crons run only in development and some only in production you should split them like so:

```
- config/server.js => common
- config/env/development/server.js => development specific
- config/env/production/server.js => production specific
```

**Comment by marcoautiero** [comment]
@alexandrebodin Aaahh, that makes sense, I didn't understand that the ones in `config/server.js` are the common ones. Maybe the doc needs a revamp on this side.

By the way, I see elements of confusion. The default configs make the app run in development. You hardly think you need to create a configuration in `config/development` to have a dedicated config for development.

**Comment by marcoautiero** [comment]
I closed the PR, but now I'm having second thoughts.

"Default" is not equal to "common". 

If I don't have a specific property in my configuration, then the default applies. And if I define any property in the default configuration, then that one is overridden when I define a new value for that property in an environment configuration. Totally overridden. Nothing "common", just a system of default->override. 

That's not the case for cron jobs. They don't get overridden, they are cumulated. So, the behavior of cron jobs is not coherent to the other cases.

From our doc:
```Everything defined in the production configuration will override the default configuration.```
and I wouldn't like to add the caveat "except for cron jobs". Coherence is synonymous with simplicity :)

**Comment by derrickmehaffy** [comment]
@marcoautiero I think I have the same confusion as Alex which is why I originally closed your old PR. Can you make a loom video showing what you mean?

**Comment by marcoautiero** [comment]
Ok, I discovered my issue.

I had default crons and production crons defined at different timings. 
For instance, if you have a cron job in default defined on `'40 * * * * *'` and one on production defined on `'40 * * * * *'`, then the one on production overrides the one in development. If you have the default one defined on `'40 * * * * *'` and the one defined on production on `'45 * * * * *'`, then you will have both of them in production, because the time of execution is different, and because the keys are different.

Closing, sorry for the loss of time 🙏🏼

**Pull request closed without merging**
