### PR TITLE
Allow login for unconfirmed users

### PR DESCRIPTION
**Pull request by pmrotule**
In some cases, you want to allow your users to log in even if they have not yet confirmed their email address. It is the case in my app where I let the users access their dashboard after signing up but prevent them from creating entries.

#### Description of what you did:

I added an option to the advanced settings of the Users & Permissions plugin.

image

#### Open question

Should I also add a policy? Something like `isAuthenticatedAndConfirmed`. It might be too much of an edge case to make it a default policy.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
I want to get @alexandrebodin's feedback here as I don't think this should be the default, many many services make confirmation a forceful process before you are even allowed to sign in.

Our process was geared around this as well, we make it a hard requirement that users validate their email before they can perform any request, including logging in.

It may be better to handle this at a per-project level, or give that option to users by default (depending on the complexity of that)

**Comment by alexandrebodin** [comment]
Hi, if you disable the confirmation email it will allow user to connect as soon as they register. I'm not sure how does that differ from what you are adding ?

**Comment by pmrotule** [comment]
@derrickmehaffy 
> I want to get @alexandrebodin's feedback here as I don't think this should be the default, many many services make confirmation a forceful process before you are even allowed to sign in.

I totally agree and that's why I didn't make it the default behavior. You will only allow login for unconfirmed users if you explicitly enable it in the advanced settings.

> It may be better to handle this at a per-project level, or give that option to users by default (depending on the complexity of that)

I thought about it, but I would need to override way too much built-in features (like the whole email confirmation workflow).

@alexandrebodin 
> Hi, if you disable the confirmation email it will allow user to connect as soon as they register. I'm not sure how does that differ from what you are adding ?

I don't want to disable the confirmation email since I still want them to receive it and eventually confirm their email address. It is just important in my case to allow them to explore the account section right away. We got better results by doing this since the user can already see how great is the dashboard and gain trust before having to do the extra step of confirming his email. This is not really a behavior that I want to loose by switching to Strapi, that's why I opened the PR.

I hope it makes sense. What do you guys think?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy
> 
> > I want to get @alexandrebodin's feedback here as I don't think this should be the default, many many services make confirmation a forceful process before you are even allowed to sign in.
> 
> I totally agree and that's why I didn't make it the default behavior. You will only allow login for unconfirmed users if you explicitly enable it in the advanced settings.
> 
> > It may be better to handle this at a per-project level, or give that option to users by default (depending on the complexity of that)
> 
> I thought about it, but I would need to override way too much built-in features (like the whole email confirmation workflow).
> 
> @alexandrebodin
> 
> > Hi, if you disable the confirmation email it will allow user to connect as soon as they register. I'm not sure how does that differ from what you are adding ?
> 
> I don't want to disable the confirmation email since I still want them to receive it and eventually confirm their email address. It is just important in my case to allow them to explore the account section right away. We got better results by doing this since the user can already see how great is the dashboard and gain trust before having to do the extra step of confirming his email. This is not really a behavior that I want to loose by switching to Strapi, that's why I opened the PR.
> 
> I hope it makes sense. What do you guys think?

I understand the need but applying it at a core level I think requires some discussion as it opens up a massive can of worms as to what requests we allow without email confirmation and what we don't. I think it's too much of a subjective opinion for us to apply.

Most likely I think this will have to be project based without seriously complicating the users-permissions (which is already complex and needs a refactor)

**Comment by pmrotule** [comment]
> I understand the need but applying it at a core level I think requires some discussion as it opens up a massive can of worms as to what requests we allow without email confirmation and what we don't. I think it's too much of a subjective opinion for us to apply.
> 
> Most likely I think this will have to be project based without seriously complicating the users-permissions (which is already complex and needs a refactor)

Very good point... Even in my project, I think it would be too messy to differentiate confirmed vs unconfirmed access. I could still work around my issue without this feature since the user has basically no rights on his account until he confirmed his email so in theory, he doesn't have to be logged in.

I'll go ahead and close this one. Thanks again for the feedback! Next time, I'll make sure to open an issue before submitting a PR.

**Pull request closed without merging**
