### PR TITLE
Add support for columnType in Mongoose

### PR DESCRIPTION
**Pull request by derrickmehaffy**
Signed-off-by: Derrick Mehaffy <derrickmehaffy@gmail.com>

### What does it do?

Mirrors functionality of Bookshelf for custom types:

https://github.com/strapi/strapi/blob/6b6c1e2f7d5ae969f92b6f9a9b145944df53cda3/packages/strapi-connector-bookshelf/lib/build-database-schema.js#L149-L152

### Why is it needed?

Custom fields and assigning a field a specific type in the database, such as with [this guide](https://www.paulgaumer.com/blog/how-to-create-a-color-picker-plugin-for-strapi-cms?utm_content=144907300&utm_medium=social&utm_source=twitter&hss_channel=tw-3832252517)

### Related issue(s)/PR(s)

N/A reported on slack

### CODE REVIEW

**Comment by alexandrebodin** [comment]
columnType is a string and mongoose don't know what to do with it most of the time it needs a constructor. Unless you use a model in pure js and not json it won't be usable. What is the usecase

**Comment by derrickmehaffy** [comment]
@alexandrebodin it was related to custom fields (the color picker from that guide I linked) I had someone test it out and it worked for them.

**Comment by derrickmehaffy** [comment]
Per our convo Alex, they won't be able to pass in the Mongo constructor without breaking the CTB but it could be done via the model.js with the attributes.

**Review by alexandrebodin — APPROVED** [review]
LGTM thanks for the addition :D

**Comment by derrickmehaffy** [comment]
This pull request has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/add-button-as-custom-field/1410/4

**Pull request merged**
