### PR TITLE
Add utm tags and update link text for careers

### PR DESCRIPTION
**Pull request by Mcastres**
### What does it do?

- Update existing Careers link text to "We are hiring!"
- Also add utm tags to careers & blog links

### CODE REVIEW

**Review by HichamELBSI — APPROVED** [review]
LGTM

**Comment by HichamELBSI** [comment]
Some tests are failing, I think you will need to update the snapshots

**Comment by Mcastres** [comment]
Update the snapshots?

**Comment by HichamELBSI** [comment]
I'll do it, no worries 😄

**Comment by Mcastres** [comment]
Thanks Hicham :)

**Comment by maevalienard** [comment]
The "we are hiring" label doesn't look that good, as it takes 2 lines. Could we try to find something smaller maybe? :)

**Comment by Mcastres** [comment]
I'm afraid "Careers" isn't significant enough. "Join us" maybe?

**Comment by maevalienard** [comment]
That sounds good to me :D @Mcastres

**Pull request merged**
