### PR TITLE
Very small UI improvement for Publish & Unpublish buttons

### PR DESCRIPTION
**Pull request by nitinmadelyn**
### What does it do?

Updated few styles for Publish & Unpublish buttons on Content Manager section.  

### Why is it needed?

- Improved the button design & changed icons to serve it's purpose.
- Previously, Publish & Unpublish buttons had a same Check icon below:
Check
- Trying to improve UI and maintain a consistency.

### How to test it?

- You can login to Admin and navigate to Content Manager.
- Play around it by adding new entries and then Publish or Unpublish them.
- You can also try a bulk action for Publish & Unpublish.

### Related issue(s)/PR(s)

This PR is not related to any open issue.

PS: Please do let me know if I've missed updating Publish & Unpublish buttons anywhere else in the project. I'll be more than happy to update them. 😃

### CODE REVIEW

**Comment by maevalienard** [comment]
Hello! 👋 The checkmark icon is used in several different places in Strapi, not only in the Content Manager. This would require a whole lot more work and an update of the Design System. Also, having icons in a circled background reduce the readability in such small areas :)

That being said, I do agree with the fact that having the same icon for Publish and Unpublish buttons doesn't make much sense. Maybe having an icon on the Unpublish button is not so necessary? :)

**Comment by nitinmadelyn** [comment]
@maevalienard agree with you, as I'm not fully aware of the system at this stage. I would be happy to remove CheckCircle icon from the Unpublish button and restore the Check icon on Publish button.
However we also maintain the consistency for both the buttons so i proposed Publish button as variant="primary" and for Unpublished button variant="secondary".
Does this sounds good to you?

**Comment by nitinmadelyn** [comment]
@maevalienard I've removed the circle icons from both the buttons.
- For Publish button I've restored the previous icon(CheckMark) & added `variant="primary"`
- For Unpublished CheckMark icon has been removed & added `variant="secondary"`

Screenshot 2023-07-07 at 11 20 49 AM
Screenshot 2023-07-07 at 11 21 05 AM
Screenshot 2023-07-07 at 11 21 22 AM
Screenshot 2023-07-07 at 11 21 42 AM
Screenshot 2023-07-07 at 11 21 54 AM

**Is this something you can consider?**

**Comment by joshuaellis** [comment]
@lucasboilly can you review the design changes please? If you're happy with it, I will review the code changes.

**Comment by lucasboilly** [comment]
Hey @nitinmadelyn :)
I agree on the fact that having the same icon for "Publish" and "Unpublish" can be confusing, so let's remove it on the "Unpublish" button. On the other hand, let's keep the colors of the CTA as they are right now to for consistency purposes.

**Review by joshuaellis — CHANGES_REQUESTED** [review]
see above comments

**Comment by alexandrebodin** [comment]
Hi, i'll close this PR as staled. Let us know if/when you ever want to finish the work on it :)

**Pull request closed without merging**
