### PR TITLE
Yarn 4.3.1

### PR DESCRIPTION
**Pull request by smorimoto**
### What does it do?

Update yarn version and run `yarn dedupe`.

### Why is it needed?

The latest yarn includes several bug fixes and performance improvements, and you can streamline the lock file by running dedupe.

### How to test it?

CI.

### Related issue(s)/PR(s)

None.

### CODE REVIEW

**Comment by alexandrebodin** [comment]
hey @smorimoto can you update this ?

**Comment by smorimoto** [comment]
Sure!

**Comment by smorimoto** [comment]
@alexandrebodin Done!

**Review by alexandrebodin — APPROVED** [review]
Works like a charm

**Comment by alexandrebodin** [comment]
Thanks for the update @smorimoto ;)

**Pull request merged**
