### PR TITLE
Add sslCA to mongodb connection options

### PR DESCRIPTION
**Pull request by jean27garbi**
### What does it do?

I added sslCA property to mongodb connectOption in strapi-connector-mongoose

### Why is it needed?

For mongodb replicaset connection with sslca key

### CODE REVIEW

**Comment by jean27garbi** [comment]
Error in CLA signed

**Review by derrickmehaffy — CHANGES_REQUESTED** [review]
Needs to have documentation updated also on how to properly use this. See: https://github.com/strapi/documentation/blob/main/docs/developer-docs/latest/setup-deployment-guides/configurations.md#database

**Comment by chris-makaio** [comment]
Please see #10194 which is an attempt to merge ALL options instead of only the ones specified explicitly

**Comment by derrickmehaffy** [comment]
closing in favor of https://github.com/strapi/strapi/pull/10194

**Pull request closed without merging**
