### PR TITLE
Disable eslint indent rule

### LINKED ISSUE #8282: Disable eslint indent rule in favor of prettier
I just tried to clean up some files, remove `eslint-disable` statements and make them look nice and pretty, but there are several things that tripped me off, one of them is clash between eslint and prettier.

Should we disable eslint "indent" rule in favor of prettier and let prettier decide what to do with indentation?

`eslint/prettier` actually does this automatically but right now there is custom `indent` rule inside `.eslintrc.front.js` which in its turn overrides `eslint/prettier`. 

If that's ok I could make PR.

### PR DESCRIPTION
**Pull request by O4epegb**
Fixes #8282 

### What does it do?

Disable eslint indent rule in favor of prettier

### Why is it needed?

No need to lint indentation if prettier will automatically format them anyway. `eslint-config-prettier` does this but it was overridden in custom config after that.

### CODE REVIEW

**Comment by O4epegb** [comment]
There was one more strange thing, multiple `extends` rule, basically only last one with `airbnb` config was active, I decided to make it first one.

**Comment by soupette** [comment]
@O4epegb thanks for your contribution!
I remember having a hard time configuring the indent rule, and when I run the lint command (`yarn run lint`) with your modifications I am still getting some errors. Can you check? 

Also can you make sure the DCO checks so we can review your PR thanks a lot.

**Comment by O4epegb** [comment]
@soupette No, I don't have any errors locally for some reason

```
~/projects/strapi  fix/disable-indent-eslint-rule ✔                                                                                                      1d  
▶ yarn lint                                 
yarn run v1.22.5
$ npm-run-all -p lint:code lint:css
$ stylelint packages/**/admin/src/**/**/*.js
$ eslint .
✨  Done in 41.37s.
```

**Comment by O4epegb** [comment]
So, can we have it merged? :)

**Review by soupette — APPROVED** [review]
LGTM

**Pull request merged**
