### PR TITLE
Update nl.json

### PR DESCRIPTION
**Pull request by jsprds**
### What does it do?

Fix for grammatical error in the Dutch translation.

### Why is it needed?

Correct translations

### How to test it?

Check the login page: `onthoudt mij` should be `onthoud mij`

### Related issue(s)/PR(s)

N/A

### CODE REVIEW

**Review by MattieBelt — APPROVED** [review]
LGTM

**Comment by derrickmehaffy** [comment]
@jsprds can you please sign the CLA

(Thank you @MattieBelt for reviewing <3)

**Comment by jsprds** [comment]
> @jsprds can you please sign the CLA

Done ;-)

**Review by derrickmehaffy — APPROVED** [review]
LGTM

**Pull request merged**
