### PR TITLE
Fix mongoose autopopulate recursively looping to infinity when cycles…

### LINKED ISSUE #9224: Relationship to self into a component leads to strapi crash, and corrupted database.
## Bug report

Hello,

I've found a case where adding a relationship to self leads to an infinite loop, which makes strapi unable to responds until manually restarted.
The worst thing is that afterwards, the database is "corrupted" in the sense that the relationship his written in base an any attempt to view and edit the faulty content-type instance leads to strapi crashing again.

### Describe the bug

This happens when the relationship is set in a component.

Let say I have a `Project` content-type with a `FeaturedProject` component.
In order to be able to restrict the number of featured project, I can't rely on relationship, so I rely on a repeatable component instead, `FeaturedProjectItem`.

to sum up : 
`Project` can contain a `FeaturedProject` component
`FeaturedProject` contains repeatable `FeaturedProjectItems`
`FeaturedProjectItems` contains a single  relationship to `Project`

### Steps to reproduce the behavior
With the previous Content-Types set up :
1. Create a project, "Project 1". At this point, you can't add a relationship to self as you didn't saved it already
2. Save "Project 1"
3. Edit "Project 1", add a `FeaturedProject` component
4. Inside the `FeaturedProject` component, add a `FeaturedProjectItem`
5. Add a relationship to self
6. Save
7. ----> Strapi will stop responding from here
8. Kill and restart strapi
9. Try to edit "Project 1"
10. ----> Strapi will stop responding again

### Expected behavior
Content-type should be saved without crashing the strapi process.

### Screenshots
insideProject
ProjectRelationship

### Code snippets
`Project` model
```
{
  "kind": "collectionType",
  "collectionName": "projects",
  "info": {
    "name": "Project",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "featured": {
      "type": "component",
      "repeatable": false,
      "component": "block.featured-project"
    }
  }
}

```

`FeaturedProject` component
```
{
  "collectionName": "components_block_featured_project",
  "info": {
    "name": "FeaturedProject",
    "icon": "copy",
    "description": ""
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "string"
    },
    "projects": {
      "type": "component",
      "repeatable": true,
      "component": "struct.project-item",
      "max": 2
    }
  }
}

```

`FeaturedProjectItem` component
```
{
  "collectionName": "components_struct_project_items",
  "info": {
    "name": "projectItem",
    "icon": "file",
    "description": ""
  },
  "options": {},
  "attributes": {
    "project": {
      "model": "project"
    }
  }
}

```

### System
- Node.js version: `12.x` 
- NPM version: `6.14.x`
- Strapi version: `3.4.4`
- Database: `MongoDB, 4.2.3`
- Operating system: `MacOS Catalina`, `Ubuntu 20.04`

### Additional context
1. The need to work with components and repeatable components initially comes from the fact that you can restrict the number of repeatable component instance, but not the number of relationships.
2. Only tried with MongoDB, no SQL database
3. Initially had the bug in Strapi `3.3.4` but the latest version also have this issue.
4. Feel free to ping me on Slack if needed (@Nicolas (Nicolas Ch))

### PR DESCRIPTION
**Pull request by alexandrebodin**
Fix #9224

**Note**
- Will return less data than before & might be a problem for certain users using unintended nesting of component (>2)

### CODE REVIEW

**Comment by cgonzalezsan** [comment]
I can confirm that this fix will solve the issue! :)

**Review by Convly — COMMENTED** [review]
LGTM, some questions though:
- Why setting 2 as a depth limit? (+ do we want to allow the user to modify it?)
- Do we need to add a test to make sure it won't break anymore?

**Comment by alexandrebodin** [comment]
> LGTM, some questions though:
> 
> * Why setting 2 as a depth limit? (+ do we want to allow the user to modify it?)

To have the same depth is in the bookshelf connector

> * Do we need to add a test to make sure it won't break anymore?

We could yes

**Review by petersg83 — APPROVED** [review]
I can confirm the fix works too. LGTM !

**Comment by cgonzalezsan** [comment]
@alexandrebodin any idea when this fix will be released? 
Thanks!

**Comment by alexandrebodin** [comment]
Early next week I think

**Comment by cgonzalezsan** [comment]
@alexandrebodin do you have an ETA for this release? It's a bit urgent as it will solve a blocker issue.

Thanks!

**Comment by alexandrebodin** [comment]
Hi @cgonzalezsan we are making a release tomorrow

**Pull request merged**
