### PR TITLE
[WIP] Add Twitch auth provider

### PR DESCRIPTION
**Pull request by synth3tk**
My PR is a:
🚀 New feature

Main update on the:
Plugin

This will add the Twitch auth provider.

### CODE REVIEW

**Comment by Aurelsicoko** [comment]
@synth3tk Thank you for this PR! Can you please update the documentation as well?

**Comment by lauriejim** [comment]
You can check this PR as an example for the documentation https://github.com/strapi/strapi/pull/1664

**Comment by synth3tk** [comment]
I apologize for the delay, I'll add the documentation on Friday when I'm back at home.

**Comment by lauriejim** [comment]
Hello @synth3tk It works well !

I just have an issue on Twith pop up

screen shot 2018-08-09 at 16 38 08

Did you have the same (can you try new setup:build please)

**Comment by synth3tk** [comment]
I've had that happen before. I thought I fixed it, but switching between branches probably threw me off at some point. I'll take a look at it tonight.

**Comment by lauriejim** [comment]
Maybe @soupette will have time to help you but I don't think so. He is really busy!
We will have to find a solution before merging your PR.

**Comment by synth3tk** [comment]
I added two additional fields to `bootstrap.js` to point the Twitch Grant provider to the new urls. They get added to the database and works perfectly. However, they now show up in the admin provider pop-up when editing. I don't know where I can go to exclude those fields from displaying.

**Comment by soupette** [comment]
@synth3tk I will try to check it out next week.

**Comment by synth3tk** [comment]
I haven't forgotten about this. Had to put this project on pause to get ready for the Extra Life stream. I'll be revisiting it in November.

**Comment by lauriejim** [comment]
I close this PR feel free to reopen it when you are done with this

**Pull request closed without merging**
