### PR TITLE
Added instructions for installing the `pg` node module

### PR DESCRIPTION
**Pull request by spobwoode**
I believe this is necessary to deploy to Google app engine - my deployment didn't work until I did this

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Can you please change the branch from Master to Documentation though?

See the following: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#documentation

**Comment by alexandrebodin** [comment]
Hey @spobwoode you changed your PR base branch but your PR now contains so commits it shouldn't. Do you mind updating it to only contain one commit :)

**Comment by spobwoode** [comment]
@alexandrebodin - Sorry, in trying to clean up this PR I think I might have just made it messier :/ Can you tell me how I can fix this? As you might have guessed, I'm a bit of a n00b

**Comment by alexandrebodin** [comment]
If you are not too familiar with git I would recommend you create a new branch and make a new PR :)

**Comment by alexandrebodin** [comment]
@spobwoode do you mind update your PR ?

**Pull request merged**
