### PR TITLE
Ability to pass OAuth callback dynamically

### PR DESCRIPTION
**Pull request by sajjad-shirazy**
Some times we need to pass callback of Oauth dynamically. suppose we have a multilanguage site and we should have these routes:
https://example.com/en/auth/google/...
and 
https://example.com/fa/auth/google/...
in this case, we should pass `callback` destination when we call Strapi endpoint. some thing like these:
https://strapi.example.com/connect/google/?callback=https://example.com/en/auth/google/
and
https://strapi.example.com/connect/google/?callback=https://example.com/fa/auth/google/

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [x] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@sajjad-shirazy please include documentation updates to support how this should be used (assuming you are passing the callback URL in the request

**Comment by sajjad-shirazy** [comment]
@derrickmehaffy it's there

**Comment by lauriejim** [comment]
I have a question about this PR.
If we allow this update, it allows anyone to add his custom URI. 
So I will be able to use your auth server for my own application.
I think we have to add a callback validation, to be able to allow specific callbacks

**Comment by derrickmehaffy** [comment]
I do agree some kind of whitelist would be required. Maybe hooking into the CORS?

**Comment by lauriejim** [comment]
Will need @alexandrebodin feedback on this topic.

**Comment by sajjad-shirazy** [comment]
@lauriejim, but valid URLs should be inserted on the OAuth service as a callback too and if anybody set a not valid one will be rejected on redirect time. it doesn't have any security issue I think.

**Pull request merged**
