### PR TITLE
Bump jest versions to 29.5 and ts-jest to 29.1

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

Bumped `jest` packages to 29.5.0 and `ts-jest` to 29.1.0

All tests seem to run fine locally, waiting for CI tests

### Why is it needed?

Generally: keeping up-to-date

Specifically: Node 20 breaks `jest.useFakeTimers()` with older versions of jest, so this is kind of holding us back (unless we update our tests)

### How to test it?

All tests should still run as expected

### Related issue(s)/PR(s)

Closes https://github.com/strapi/strapi/pull/16652

### CODE REVIEW

**Review by gu-stav — DISMISSED** [review]

**Comment by joshuaellis** [comment]
> Node 20 breaks jest.useFakeTimers() with older versions of jest

Do you have any instructions on what we should be doing instead? 🤔

**Review by joshuaellis — DISMISSED** [review]
💯

**Comment by innerdvations** [comment]
> > Node 20 breaks jest.useFakeTimers() with older versions of jest
> 
> Do you have any instructions on what we should be doing instead? 🤔

The problem was that Node 20 made some properties readonly that Jest was overwriting to mock the system time. We should be able to continue using useFakeTimers() now.

The workaround I used was mocking `Date.now()` and/or `new Date()` instead, [which you can see an example of here](https://github.com/strapi/strapi/pull/16557/files#diff-b9620d8bc6bb60a0c056c8e5910d5e1a7f65a2b597bc02393dc4d22652525133), but which I'm hoping to revert assuming this Jest update works as expected.

**Comment by innerdvations** [comment]
15 front-end unit test suites were failing due to a change in how resetAllMocks and restoreAllMocks works in later versions of jest. I did a clumsy swap of everything to clearAllMocks and all tests pass now. It looks to me like the tests should have been using clearAllMocks to begin with, but there may be some cases (like where a clear was also being done already) the test logic may be impacted by this.

 @gu-stav @joshuaellis If one of you could make a quick check at those test files to make sure I didn't invalidate any of the tests due to the simple fix, that would be great :)

**Comment by gu-stav** [comment]
> @gu-stav @joshuaellis If one of you could make a quick check at those test files to make sure I didn't invalidate any of the tests due to the simple fix, that would be great :)

Thanks! I think the change is fine and `clearAllMocks` is what we'd want.

**Comment by innerdvations** [comment]
I've noticed there are still front end unit tests failing on Node 18 that are passing on Node 16 (all seem related to React and waitForNextUpdate). I won't have time to investigate for a couple weeks, but if either of you get a bit of time to look that would be awesome.

**Review by joshuaellis — APPROVED** [review]
LGTM – nice to see green in the CI ✨

**Pull request merged**
