### PR TITLE
Add new notification variant to notification component

### PR DESCRIPTION
**Pull request by ivanThePleasant**
### What does it do?

This PR adds a new notification variant to Notification component. Currently we only allow notifications to be info (blue), success (green) and warning (red), however it is quite a standard practice to also have a yellow warning notification. We have yellow warning colors defined in the design system, but no actual yellow warning variant in the CMS. At the same time Notification component does not allow to provide a custom title to the notification, so this functionality has been added as well. Design system has been bumped up to 1.4.2 in order to use the new Alert variant.

### Why is it needed?

Yellow alert is needed for the ee seat checking initiative

### How to test it?

Run the getstarted in --watch-admin, modify any notification in the code base by changing type to `softWarning` and add a title if necessary. Perform an action to receive a notification.

### CODE REVIEW

**Review by joshuaellis — CHANGES_REQUESTED** [review]
Code changes looks fine, think we should be adding some tests around this new feature though 🙏🏼

**Comment by ivanThePleasant** [comment]
Hey @joshuaellis I just checked the test files for the component and looks like we don't really have any tests to check this variant functionality even before my changes. I'm happy to write some more tests to include that, but at the moment it's out of my scope and I can't spend any extra time on it before next sprint. Since changes are minimal, could we merge this and I will add tests to our backlog?

**Comment by ivanThePleasant** [comment]
Also, any reason codecov report acts so weird?

**Review by gu-stav — APPROVED** [review]
> could we merge this and I will add tests to our backlog?

As long as it doesn't disappear in the backlog that would work for me.

> Also, any reason codecov report acts so weird?

No you can ignore that.

**Review by joshuaellis — APPROVED** [review]

**Comment by ivanThePleasant** [comment]
Don't worry, I've already told Nkem we will have to add it to backlog and work on it in next sprint or two 👍

**Pull request merged**
