### PR TITLE
Update RU translations

### PR DESCRIPTION
**Pull request by denisinvader**
My PR is a:
💅 Enhancement

Main update on the:
Admin

Improved texts and fixed typos for Russian locale in admin (including plugins).

Documentation plugin has been translated into Russian.

### CODE REVIEW

**Comment by lauriejim** [comment]
@denisinvader you can push all you RU update in this PR.

**Comment by denisinvader** [comment]
All right, then I will push more changes later

**Comment by lauriejim** [comment]
Okay thank you.

**Comment by lauriejim** [comment]
Tell me when you are done with your translations.

**Comment by denisinvader** [comment]
I think I'm done now

**Comment by lauriejim** [comment]
Okay thank you!
Before merging your PR I would like a review from 🇷🇺 guy/girl of the community.

**Pull request merged**
