### PR TITLE
Adding Cloudfront option to AWS S3 upload provider

### PR DESCRIPTION
**Pull request by rmaroun**
#### Description of what you did:

Related to issue [#3218](https://github.com/strapi/strapi/issues/3218)

Updating provider configuration in order to be able to enable Cloudfront delivery for uploaded assets to s3 bucket. This configuration add a Yes / No dropdown to indicate if we wish to store the Cloudfront URL (which is the other configurable field) of the uploaded asset instead of the S3 bucket URL. This entails that the user has already created a Cloudfront distribution for his/her s3 bucket.

Configuration screen looks like this with the two extra fields for Cloudfront: 

image

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [X] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [X] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [X] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @rmaroun, Thank your for this PR. This needs some testing on our side but we are very shorthanded right now. I hope to be able to get to it soon !

**Comment by rmaroun** [comment]
@alexandrebodin let me know if there is any way to help you on the testing side.

**Comment by alexandrebodin** [comment]
I'm wondering if it wouldn't be better to save a realtive url for flexibility instead of adding a parameter. I'm thinkg in the case someone uses another caching layer or something. the param wouldn't make sense.

**Comment by rmaroun** [comment]
> I'm wondering if it wouldn't be better to save a realtive url for flexibility instead of adding a parameter. I'm thinkg in the case someone uses another caching layer or something. the param wouldn't make sense.

@alexandrebodin What do you mean by relative URL? without the protocol (http/https)? Cloudfront will give you a url on top of your S3 bucket and you need to use it in order to access the cache created by Cloudfront.

**Comment by alexandrebodin** [comment]
Hi, I meant a relative path (/image.png) so you can just prefix with your cache url.

 I'm thinking that adding a specific option on top of the provider for cloudfront isn't really something that will scale. Imagine you implement your own caching layer. You will need to set a custom url. What about if you need to access the file without using the cache. Your PR will completely override the underlying location.

If you just had a relative path you could build your url lazily depending on your usecase :)

Just thinking outload for now.

**Comment by rmaroun** [comment]
@alexandrebodin what the PR is doing is appending your cloudfront URL or your custom domain name to the /image.png and stores it in the db instead of storing the s3 bucket url. You can disable it at anytime and go back to your s3 bucket url the previous urls will still work if you keep your cloudfront distribution up and running. The use case here is to leverage the Cloudfront distribution instead of pointing directly to the s3 bucket url.

**Comment by harrykc** [comment]
This PR is what i needed too, hope will get it soon.

**Comment by rmaroun** [comment]
@harrykc discussed it offline with @alexandrebodin and the core team is starting to work on the media asset manager and he will take into account this feature during his development. Let's wait for now until the media manager is delivered and I will then update this PR.

**Comment by robertpiosik** [comment]
Every media object returns its hash and ext. In my option you should combine it with your cache domain on the application level. File location behind cache domain is abstract and we shouldn't store information about it inside s3 provider configuration as it misses the context of the functionality and leads to a path of dozen unnecessary options.

**Comment by robertpiosik** [comment]
Every media object returns its hash and ext. In my option you should combine it with your cache domain on the application level. File location behind cache domain is abstract and we shouldn't store information about it inside s3 provider configuration as it misses the context of the core functionality.

**Comment by rmaroun** [comment]
> Every media object returns its hash and ext. In my option you should combine it with your cache domain on the application level. File location behind cache domain is abstract and we shouldn't store information about it inside s3 provider configuration as it misses the context of the core functionality.

@robertpiosik Yes indeed that could be a better solution so that you never change the s3 url and just configure a cloudfront distribution and use a custom dns to point to it and add it as an env var to your static website using the hash and ext attributes of the image returned from strapi combined with the custom cloudfront dns to point to the cloudfront cache.

**Comment by rmaroun** [comment]
As indicated by @robertpiosik it is better to manage this at the frontend level instead of storing it in the database. Closing PR.

**Pull request closed without merging**
