### PR TITLE
[Email] Migrate to typescript

### PR DESCRIPTION
**Pull request by jhoward1994**
### What does it do?

Converts the email package to typescript.

### Why is it needed?

More types across strapi

### How to test it?

- Existing test suites in the email package
- Test the email package in the UI

### Related issue(s)/PR(s)

CONTENT-1872

### CODE REVIEW

**Comment by joshuaellis** [comment]
We need #18233 merged before we can finish this.

**Comment by joshuaellis** [comment]
I think this is good for review right? Just needs the PR description writing and then a final review I think...?

**Comment by jhoward1994** [comment]
> I think this is good for review right? Just needs the PR description writing and then a final review I think...?

Yep this is ready for review. I'm still seeing that issue where I can't access the email settings page on port 1337, you said that's not the case for you right?

**Comment by joshuaellis** [comment]
> I'm still seeing that issue where I can't access the email settings page on port 1337, you said that's not the case for you right? @joshuaellis

I can access it, we could ask @Marc-Roig or @gu-stav to check and see which one us is the problem?

**Comment by gu-stav** [comment]
> > I'm still seeing that issue where I can't access the email settings page on port 1337, you said that's not the case for you right? @joshuaellis
> 
> I can access it, we could ask @Marc-Roig or @gu-stav to check and see which one us is the problem?

I can have a look.

**Comment by gu-stav** [comment]
I can't even build the project:

```
 ✖  nx run @strapi/plugin-email:build
       - Verifying package.json 
       
       ✔ Verified package.json
       - Creating build context 
       
       ✔ Created build context
       Building type files:
          entries:
           – @strapi/plugin-email/admin/src/index.ts ./admin/src/index.ts -> ./dist/admin/src/index.d.ts
           – @strapi/plugin-email/server/src/index.ts ./server/src/index.ts -> ./dist/server/src/index.d.ts
       [ERROR]  admin/src/index.ts:8:42 - TS7016: Could not find a declaration file for module '@strapi/helper-plugin'. '/Users/strapi/Development/strapi/packages/core/helper-plugin/build/helper-plugin.esm.js' implicitly has an 'any' type.
         Try `npm i --save-dev @types/strapi__helper-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module '@strapi/helper-plugin';`
       [ERROR]  admin/src/pages/Settings.tsx:26:8 - TS7016: Could not find a declaration file for module '@strapi/helper-plugin'. '/Users/strapi/Development/strapi/packages/core/helper-plugin/build/helper-plugin.esm.js' implicitly has an 'any' type.
         Try `npm i --save-dev @types/strapi__helper-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module '@strapi/helper-plugin';`
       [ERROR]  admin/src/utils/schema.ts:1:34 - TS7016: Could not find a declaration file for module '@strapi/helper-plugin'. '/Users/strapi/Development/strapi/packages/core/helper-plugin/build/helper-plugin.esm.js' implicitly has an 'any' type.
         Try `npm i --save-dev @types/strapi__helper-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module '@strapi/helper-plugin';`
       [ERROR]  admin/src/index.ts:8:42 - TS7016: Could not find a declaration file for module '@strapi/helper-plugin'. '/Users/strapi/Development/strapi/packages/core/helper-plugin/build/helper-plugin.esm.js' implicitly has an 'any' type.
         Try `npm i --save-dev @types/strapi__helper-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module '@strapi/helper-plugin';`
       [ERROR]  admin/src/pages/Settings.tsx:26:8 - TS7016: Could not find a declaration file for module '@strapi/helper-plugin'. '/Users/strapi/Development/strapi/packages/core/helper-plugin/build/helper-plugin.esm.js' implicitly has an 'any' type.
         Try `npm i --save-dev @types/strapi__helper-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module '@strapi/helper-plugin';`
       [ERROR]  admin/src/utils/schema.ts:1:34 - TS7016: Could not find a declaration file for module '@strapi/helper-plugin'. '/Users/strapi/Development/strapi/packages/core/helper-plugin/build/helper-plugin.esm.js' implicitly has an 'any' type.
         Try `npm i --save-dev @types/strapi__helper-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module '@strapi/helper-plugin';`
       Building javascript files:
         format: cjs
          target:
           - esnext
          entries:
           – @strapi/plugin-email/bundle_cjs_0: ./admin/src/index.ts → ./dist/admin/index.js
       Building javascript files:
         format: es
          target:
           - esnext
          entries:
           – @strapi/plugin-email/bundle_esm_0: ./admin/src/index.ts → ./dist/admin/index.mjs
       Building javascript files:
         format: cjs
          target:
           - node16.0
          entries:
           – @strapi/plugin-email/bundle_cjs_1: ./server/src/index.ts → ./dist/server/index.js
       Building javascript files:
         format: es
          target:
           - node16.0
          entries:
           – @strapi/plugin-email/bundle_esm_1: ./server/src/index.ts → ./dist/server/index.mjs
       [ERROR]  Failed to compile TypeScript definitions
```

Does this branch need a rebase?

**Comment by jhoward1994** [comment]
Updated from main, the build should now work for you @gu-stav

**Comment by gu-stav** [comment]
I can't access `http://localhost:1337/admin/settings/users-permissions/email-templates` neither, but it works on port 4000.

The error thrown is: `TypeError: can't access property "nps", window.strapi.flags is undefined` in

```js
Be = t => {
        const {
          enabled: a,
          lastResponseDate: s,
          firstDismissalDate: i,
          lastDismissalDate: d
        }
        = t;
        return window.strapi.flags.nps === !1 ||
        a === !1 ? !1 : s ? Date.now() - new Date(s).getTime() >= w.postResponse : d ? Date.now() - new Date(d).getTime() >= w.postSubsequentDismissal : i ? Date.now() - new Date(i).getTime() >= w.postFirstDismissal : !0
      },
```

**Comment by gu-stav** [comment]
Discussed it on Slack: a rebuild solves the problem and the email settings page works fine for me now ✨

**Comment by jhoward1994** [comment]
I'm still getting redirected from the email settings page even with a full rebuild. I don't see any logs when on port 1337, is there a way to enable that so I can debug?

**Comment by gu-stav** [comment]
> I'm still getting redirected from the email settings page even with a full rebuild. I don't see any logs when on port 1337, is there a way to enable that so I can debug?

Just to make sure: can you share the URL that is a problem for you so we are talking about the same?

**Comment by jhoward1994** [comment]
http://localhost:1337/admin/settings/email


https://github.com/strapi/strapi/assets/48524071/4be08b1d-12f9-4f7f-8766-a5add142d9da

**Comment by gu-stav** [comment]
Oh, I was testing email templates 😮‍💨 I do the same redirect. Could this come from `CheckPagePermissions`? It is definitely a client-side redirect.

**Comment by jhoward1994** [comment]
Woops I think this was something stupid in the end 🤦‍♂️I've updated the helper-plugin dependency in [`1e999bc` (#18136)](https://github.com/strapi/strapi/pull/18136/commits/1e999bcabbcfb017e794ddd1382b113bea2acee9)

@gu-stav could you try again?

**Comment by gu-stav** [comment]
Mmh, I am back at a build error when running `yarn && yarn setup` in root:

```
>  NX   Running target build for 27 projects
    ✖  nx run @strapi/admin:build
       node:internal/modules/cjs/loader:553
             throw e;
             ^
       
       Error: Cannot find module '/Users/strapi/Development/strapi/node_modules/@strapi/helper-plugin/dist/index.js'
           at createEsmNotFoundErr (node:internal/modules/cjs/loader:1070:15)
           at finalizeEsmResolution (node:internal/modules/cjs/loader:1063:15)
           at resolveExports (node:internal/modules/cjs/loader:547:14)
           at Module._findPath (node:internal/modules/cjs/loader:621:31)
           at Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
           at Function.resolve (node:internal/modules/helpers:136:19)
           at /Users/strapi/Development/strapi/packages/core/admin/webpack.alias.js:37:46
           at Array.reduce (<anonymous>)
           at Object.<anonymous> (/Users/strapi/Development/strapi/packages/core/admin/webpack.alias.js:36:22)
           at Module._compile (node:internal/modules/cjs/loader:1241:14) {
         code: 'MODULE_NOT_FOUND',
         path: '/Users/strapi/Development/strapi/node_modules/@strapi/helper-plugin/package.json'
       }
       
       Node.js v20.8.0
       
       

 ————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for 27 projects (2s)
 
    ✔    23/24 succeeded [23 read from cache]
 
    ✖    1/24 targets failed, including the following:
         - nx run @strapi/admin:build
```

**Comment by joshuaellis** [comment]
> Mmh, I am back at a build error when running `yarn && yarn setup` in root:
> 
> ```
> >  NX   Running target build for 27 projects
>     ✖  nx run @strapi/admin:build
>        node:internal/modules/cjs/loader:553
>              throw e;
>              ^
>        
>        Error: Cannot find module '/Users/strapi/Development/strapi/node_modules/@strapi/helper-plugin/dist/index.js'
>            at createEsmNotFoundErr (node:internal/modules/cjs/loader:1070:15)
>            at finalizeEsmResolution (node:internal/modules/cjs/loader:1063:15)
>            at resolveExports (node:internal/modules/cjs/loader:547:14)
>            at Module._findPath (node:internal/modules/cjs/loader:621:31)
>            at Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
>            at Function.resolve (node:internal/modules/helpers:136:19)
>            at /Users/strapi/Development/strapi/packages/core/admin/webpack.alias.js:37:46
>            at Array.reduce (<anonymous>)
>            at Object.<anonymous> (/Users/strapi/Development/strapi/packages/core/admin/webpack.alias.js:36:22)
>            at Module._compile (node:internal/modules/cjs/loader:1241:14) {
>          code: 'MODULE_NOT_FOUND',
>          path: '/Users/strapi/Development/strapi/node_modules/@strapi/helper-plugin/package.json'
>        }
>        
>        Node.js v20.8.0
>        
>        
> 
>  ————————————————————————————————————————————————————————————————————————————————————————
> 
>  >  NX   Ran target build for 27 projects (2s)
>  
>     ✔    23/24 succeeded [23 read from cache]
>  
>     ✖    1/24 targets failed, including the following:
>          - nx run @strapi/admin:build
> ```

Marc had this issue, could be with nx cache....? I've also checked the branch out and can't reproduce the error anymore that jamie shared :)

**Review by joshuaellis — APPROVED** [review]

**Pull request merged**
