### PR TITLE
Updated Models Page Grammar

### PR DESCRIPTION
**Pull request by cwray-tech**
#### Description of what you did:
Quickly went through the models' page in the documentation and updated some grammar as well as added some emphasis and brief clarification in a couple of places.

### CODE REVIEW

**Comment by cwray-tech** [comment]
Hey, Just noticed that I missed removing a word on one of the lines that will look pretty bad:
remove it

**Comment by derrickmehaffy** [comment]
@cwray-tech you can update your local branch and it will reflect here automatically, no need to resubmit a pull request ;)

**Comment by cwray-tech** [comment]
@derrickmehaffy This shows you how unfamiliar I am with this! Will do, I thought later, maybe that is talking about a singular Strapi Model global id?

**Comment by cwray-tech** [comment]
@derrickmehaffy is there anything I need to do to merge this? Thank you!

**Review by derrickmehaffy — APPROVED** [review]
LGTM

**Pull request merged**
