### PR TITLE
Don't parse npm scripts for dynamic config

### PR DESCRIPTION
**Pull request by maturanomx**
Fix the fix merged with #1575

The original patch was done over a block of code moved on #1667 resulting in re-introducing code that now is not invoked and continue with the bug reported on #916.

This patch take the original changes and put them in the current correct place.

Proof:
capture

---
My PR is a:

🐛 Bug fix

Main update on the:

Plugin

### CODE REVIEW

**Comment by maturanomx** [comment]
Travis fails. This is [from the log](https://travis-ci.org/strapi/strapi/jobs/430795596#L522): 
```
📦  Linking strapi-lint
npm ERR! code E503
npm ERR! 503 No backends available: @xtuc/long@4.2.1
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-09-19T23_36_07_284Z-debug.log
npm ERR! code E503
npm ERR! 503 No backends available: @xtuc/long@4.2.1
```

In my local I also have problem with that dependency, just I was getting a 404 error. Temporary problems with the registry? :thinking:

**Comment by lauriejim** [comment]
I have restart tests, looks working well.

**Comment by maturanomx** [comment]
> 
> 
> I have restart tests, looks working well.

Oh!, you mean the Travis tests :)

Just for add information, this is from `master` reproducint #916 :
capture

**Comment by lauriejim** [comment]
Have to check for the issue you screenshot.

**Pull request merged**
