### PR TITLE
[GraphQL] Make plural definition as required

### PR DESCRIPTION
**Pull request by darron1217**
From https://github.com/strapi/strapi/pull/7056

~~This might be breaking change. Because some plural fields are null in mongoose and this will emit error.~~
~~So filling null fields with empty array `[]` is needed after merge this PR.~~
(Edit)
~~Plural with no result returns empty array on version `3.4.1`, but current master returns null.~~
(Edit)
On version `3.4.4` graphql does not returning null on plural. It works well.

### SideEffects?
I couldn't find side-effects. (I've forked this plugin and used it for 1 month)

### What does it do?

Make GraphQL plural definition as required.

### Why is it needed?

To avoid unnecessary if statement on Typescript with CodeGenerator.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/pull/7056

### CODE REVIEW

**Comment by darron1217** [comment]
I'm currently using forked plugin that only plural definition is marked as required.
It works perfectly on version(3.4.4) of Strapi.

This made my frontend code simple (and headache caused by typescript has gone)

**Comment by abdonrd** [comment]
Looks good!

**Comment by alexandrebodin** [comment]
Hi @darron1217 thank you for the contribution :) I'll all for doing this but we sadly can't merge this in v3 as it would be a breaking change in certain conditions. I'll tag it for v4 :)

**Comment by alexandrebodin** [comment]
Hello there, v4 is out and has better management for required attributes. I'll go ahead and close this.  Thank you for contributing!

**Pull request closed without merging**
