### PR TITLE
List view: new cog button icon with the view settings in the list view page

### PR DESCRIPTION
**Pull request by simotae14**
### What does it do?

On the List View page, we would like to free up some space above the table, in the top right corner, to show only a Cog Icon that can open a menu with a link to the List View settings and checkboxes for selecting the columns to display in the List View.
Additionally, we want to add a reset button that selects the default columns of the collection.

### Why is it needed?

In the list view, there are 2 elements in the top right corner of the table:

- The columns that are currently selected
- The cog icon that redirects to the settings of the list view (Configure the view)

We’d like to merge them to free some space in the list view.

### How to test it?

 - Go the content manager and select a collection
 - On the list view you can see a Cog icon on the top right corner of the table
   - click the cog icon
     - you can click on the "Configure the view" button to go to the list view settings page of the collection
     - you can select/deselect the headers to show in the list view
     - you can click on the reset button and immediately have the default selection of the headers for the collectios

### Related issue(s)/PR(s)

The ticket related is CS-42

Reopened version of the merged and reverted PR https://github.com/strapi/strapi/pull/17551

### CODE REVIEW

**Comment by gu-stav** [comment]
@simotae14 Could you please squash the commits, to make sure this PR is ready to merge? :)

**Comment by gu-stav** [comment]
@simotae14 I've tested it today:

- the selected columns are not persisted for me (after a page reload they reset)
- it would probably be good to discuss how the columns should be sorted: I think there is an argument for alphabetically aswell as the same sort order as in the table

Could you take care of that? 🙏🏼

**Comment by simotae14** [comment]
Thanks gustav for your comments, for the squash and merge when it will be ready we have the button enabled in github but if I have to do it manually let me know.

- the selected columns are not persisted for me (after a page reload they reset)
    => as you can see in the comments in the JIRA ticket the persistence is not required
- it would probably be good to discuss how the columns should be sorted: I think there is an argument for alphabetically aswell as the same sort order as in the table

**Comment by yanniskadiri** [comment]
Hey there, it is more of a refacto than an iteration. We are just merging the existing dropdown for column selection and the cog button for list view configuration.

That being said, those are excellent remarks. I'd like to discuss the order of the columns with Lucas because I think it'd be great to have a drag-and-drop system like they do at Hygraph.

So for this PR let's keep it like this if you're okay with it and we'll work on an improvement with Lucas!

**Comment by gu-stav** [comment]
@yanniskadiri Works for me! :)

**Review by gu-stav — APPROVED** [review]

**Comment by markkaylor** [comment]
@Feranchz Could you please review I updated the spacing and padding to match the filter popover.

Before:
Screenshot 2023-08-28 at 10 54 42


After:
Screenshot 2023-08-28 at 10 55 03

**Pull request merged**
