### PR TITLE
Update .npmignore files

### PR DESCRIPTION
**Pull request by jorrit**
### What does it do?

I noticed that the NPM packages contain several development files, like .snyk, jest.config.js and .editorconfig. Also the tests in test directories were excluded, but files in __tests__ were still present.

I've updated all .npmignore files so these files are excluded.

I also found some .npmignore files in admin subdirectories. I am quite certain those files are in fact not needed.

### Why is it needed?

This change cleans up the NPM packages.

### CODE REVIEW

**Review by jakesyl — APPROVED** [review]

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
overall looks good to me :) Can you add 

In most of the packages their is a root `tests` folder can you exclude it too ?

**Comment by jorrit** [comment]
> In most of the packages their is a root `tests` folder can you exclude it too ?

Thanks for reviewing. I did not find any `tests` folders. Some packages have `__tests__`, some have `test`. Both are excluded. Did I overlook something?

**Comment by alexandrebodin** [comment]
> > In most of the packages their is a root `tests` folder can you exclude it too ?
> 
> Thanks for reviewing. I did not find any `tests` folders. Some packages have `__tests__`, some have `test`. Both are excluded. Did I overlook something?

I think we renamed the test folders to tests in a recent refactoring :) you might have missed it

**Comment by jorrit** [comment]
I did, thanks. I have applied the change.

I see all `__tests__` directories got renamed, but copy-monorepo.js and jest.config.js still reference `__tests__`. It is out of scope of this PR, but shouldn't some changes be made in those files?

**Comment by alexandrebodin** [comment]
> I did, thanks. I have applied the change.
> 
> I see all `__tests__` directories got renamed, but copy-monorepo.js and jest.config.js still reference `__tests__`. It is out of scope of this PR, but shouldn't some changes be made in those files?

We actually still have a lot of __tests__ :)

Our ntegration (e2e.js) tests are in tests folders & unit tests for the backend are in __tests__ foder to differentiate them. We need to harmonize all of this at some point. you can ignore all of  test/tests/__tests__ to make sure we don't include any of the test files :)

**Comment by jorrit** [comment]
> We actually still have a lot of **tests** :)
> 
> Our ntegration (e2e.js) tests are in tests folders & unit tests for the backend are in **tests** foder to differentiate them. We need to harmonize all of this at some point. you can ignore all of test/tests/**tests** to make sure we don't include any of the test files :)

Sorry, I made a mistake while searching for files in the project. I've now ignored all three.

**Comment by alexandrebodin** [comment]
Will have to run some "real world" tests with verdaccio to make sure everything still works fine :)

**Review by alexandrebodin — APPROVED** [review]
Everything looks good on our side 👍  thank you for your contribution 🎉

**Pull request merged**
