### PR TITLE
Chore: Bump @strapi/design-system to 1.2.7

### PR DESCRIPTION
**Pull request by gu-stav**
### What does it do?

Bump @strapi/design-system to 1.2.7

➡️ [Changelog](https://github.com/strapi/design-system/releases/tag/v1.2.7)

### Why is it needed?

The release contains a critical fix for https://github.com/strapi/design-system/issues/752.

### CODE REVIEW

**Review by Convly — DISMISSED** [review]
LGTM

**Review by joshuaellis — DISMISSED** [review]
This shouldn't be merged to `main` because `relations` is in `main`.

**Comment by gu-stav** [comment]
I'll leave the merge up to @Convly and let him decide how this will be released.

**Review by joshuaellis — CHANGES_REQUESTED** [review]
I've made a new branch that starts at the 4.4.6 commit, this change should probably branch from there & merge back into there? Or just update that branch and then @Convly  can release off that branch?

**Comment by Convly** [comment]
Let's merge this on `main`. I'll release 4.4.7 with this fix only.

**Review by joshuaellis — APPROVED** [review]

**Pull request merged**
