### PR TITLE
[Database] - Add missing schema attributes to column creation

### LINKED ISSUE #17656: Unique fields validation does not work when saving a cloned entry
### Required System information

- Node.js version: `v18.16.1`
- NPM version: `v9.5.1`
- **Yarn** version: `1.22.19`
- Strapi version: `4.12.0`
- Database: sqlite
- Operating system: Manjaro Linux
- Is your project Javascript or Typescript: JS

### Describe the bug

I have a collection with 3 unique values, [here's the schema](https://github.com/Marje3PSUT/psutarchive-api/blob/dev/src/api/course/content-types/course/schema.json)
```json
"attributes": {
    "name": {
      "pluginOptions": {},
      "type": "string",
      "required": true,
      "unique": true
    },
    "course_id": {
      "pluginOptions": {},
      "type": "string",
      "required": true,
      "unique": true
    },
    "name_ar": {
      "type": "string",
      "required": true,
      "unique": true
    }
}
```

Creating a new item and attempting to save it with any duplicate value for one of these unique attributes works as expected, it returns a validation error and prevents me from saving the item.
The problem appears when I attempt to clone any item, it shows the expected warning
```
Warning:
Entity could not be cloned as it has unique and/or relational fields.
Please edit those fields manually and save to complete the cloning.
```
but still allows me to save it without validation and end up with duplicate values.

### Steps to reproduce the behavior
Here's the repo to reproduce (`dev` branch) https://github.com/itsmohmans/psutarchive-api/tree/dev

1. Run the project with yarn
2. Go to content manager and create a new course, fill in `name` and `course_id` (both are unique)
3. Save, then go back to courses list and click on `duplicate item` button
4. See the expected error 
image
Now ignore this warning, don't edit any field and click on Save, it'll save successfully, and you'll end up with duplicate values that are supposed to be unique.

### Expected behavior

It should validate before saving a cloned item and prevents from saving it if any of the unique fields is still the same as the one we cloned from, the same way it validates when creating and saving a new item.

### Screenshots

Cloned items with the same _unique_ values, either draft or published
image

### Code snippets

If applicable, add code samples to help explain your problem.

### PR DESCRIPTION
**Pull request by dekinderfiets**
### What does it do?

Fixes #17656 and potentially more schema issues related to nullable columns, default column values and unique column constraints.

Describe the technical changes you did.

### Why is it needed?

Because tables columns do not reflect schema attributes.

### How to test it?

Create a new collection field with the following properties: **Required**, **Unique**, and define a **Default Value**.

The created table column in the database should be not-nullable, have the default value and have the unique constraint.

### Related issue(s)/PR(s)

#17656

### CODE REVIEW

**Review by VikasKumarPatel — COMMENTED** [review]
accepted

**Comment by alexandrebodin** [comment]
Hi, thanks for opening this PR.

However, the current behaviour is intedend. `required` and `default` are not and should not be a 1:1 translation to database constraints. These are manage on the application side to support more advance features like Draft & publish / i18N etc. 

If you really want to define those on the DB level you must use the attribute.column options (which is considered as unstable at the moment). 

Beware this could break some features so you need to be very sure of what you are doing. 

THanks again I'll go ahead and close this PR. Feel free to comment if you think it needs to be reopened

**Comment by derrickmehaffy** [comment]
docs related to what Alex mentioned: https://docs.strapi.io/dev-docs/backend-customization/models#database-validations-and-settings

**Comment by VikasKumarPatel** [comment]
Recieved, thanks

**Pull request closed without merging**
