### PR TITLE
fix: hook getter spread make handlers invalid

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Fixes hooks getter being spread thus not allowing changes to handlers (delete is not working correctly).

### Why is it needed?

To allow unregistering a hook for customization purposes.

### How to test it?

try to delete a hook (e.g https://gist.github.com/alexandrebodin/62e5b0b446b9494c81ce672feaf0def3) to replace it with another function.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Patch folder:
[patches.zip](https://github.com/strapi/strapi/files/8654684/patches.zip)

**Comment by derrickmehaffy** [comment]
Can test from my example app which triggered the find of this bug: https://github.com/derrickmehaffy/strapi-test-v4-draft-and-publish-fix

**Review by derrickmehaffy — APPROVED** [review]
Tested via my example repo using patch-package. Works perfectly

**Review by Convly — APPROVED** [review]
LGTM

**Review by derrickmehaffy — APPROVED** [review]
LGTM

**Pull request merged**
