### PR TITLE
3.0.0-alpha.15

### PR DESCRIPTION
**Pull request by lauriejim**
GitHub diff: https://github.com/strapi/strapi/compare/v3.0.0-alpha.14.5...v3.0.0-alpha.15
Migration guide: https://github.com/strapi/strapi/wiki/migration-guide-alpha.14.5-to-alpha.15

### CODE REVIEW

**Comment by abdonrd** [comment]
@lauriejim about the [Migration guide](https://github.com/strapi/strapi/wiki/Migration-guide-alpha.14.5-to-alpha.15)...

We need to keep the `jwtSecret` from `plugins/users-permissions/config/jwt.json`?

**Comment by lauriejim** [comment]
If you follow the migration guide you never touch to the config folder of your application.
So yes you have to keep all your configs.

**Comment by abdonrd** [comment]
@lauriejim following this I will change my `plugins/users-permissions/config/jwt.json`:

> Then, delete your old `plugins` folder and replace it with the new one.

**Comment by lauriejim** [comment]
Ho yes! It was a mistake made since a long time! 
Sorry for the trouble, I will update migrations guides.

**Comment by abdonrd** [comment]
Oops! 😅 

I found it the other day by chance. Right when I commented here.

And what are the implications of having changed it? 😅

**Comment by lauriejim** [comment]
It's used here https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/Jwt.js

**Pull request merged**
