### PR TITLE
Ability to emit errors to Koa

### PR DESCRIPTION
**Pull request by andfk**
My PR is a:
💅 Enhancement

Main update on the:
Framework

Hi! I needed to catch errors from strapi to do some custom error handling logic. I noticed that errors are not propagated to Koa as they are catch in the boom middleware (at least the errors from controllers?) so i would like to propose a way to get these errors propagate if configured. 
I added into `/config/environments/development/server.json`:
```
"emitErrors": true,
```

Then anyone can do in server setup the following:
```
const strapi = require('strapi');
strapi.app.on('error', (err, ctx) => {  'Your logic goes here' });
strapi.start();
```
I would like to propagate any error into this part but for now is a good start. What do you think?

Thanks

### CODE REVIEW

**Comment by lauriejim** [comment]
Thank you for your PR @andfk. Will work on your PR soon as possible.

**Comment by Aurelsicoko** [comment]
LGTM 👍 

It seems the perfect way to do it if we refer to the official Koa wiki (https://github.com/koajs/koa/wiki/Error-Handling). Great job @andfk!

**Comment by andfk** [comment]
Awesome @Aurelsicoko. My only concern is if all errors are catched by Boom middleware? May have to check all the strapi source code but you may know that already :)

Many thanks!

**Comment by Aurelsicoko** [comment]
All the errors generated in the stack of middlewares are caught by the Boom middleware. However, the server's errors aren't caught, but it's perfectly normal because Boom is dedicated to catching HTTP errors only.

**Pull request merged**
