### PR TITLE
fix: the confirmation message of restoring a version was updated

### PR DESCRIPTION
**Pull request by sg1asgard**
### What does it do?
It updates the message for the notification box after an user restores a document version.

### Why is it needed?
The message was reported as incorrect.

### How to test it?
- Edit an entry of a content-type without D&P enabled
- Go to the content history of this entry (you will need a paid license)
- Restore a past version of the entry
- See the notification saying that the version was restored on top of a published one

### Related issue(s)/PR(s)
https://github.com/strapi/strapi/issues/21175

### CODE REVIEW

**Review by simotae14 — APPROVED** [review]
Well done @sg1asgard 🏅

**Comment by sg1asgard** [comment]
@simotae14 @markkaylor 
Well, some tests are failing and I am unsure to what's the problem, if I caused it or it is something else.
If any of you have the time maybe today in the afternoon to assist me? Much appreciated.

**Comment by markkaylor** [comment]
I think the failing test is flaky. Re-running it now to see if it passes. It's not related to your work here. I've see it fail in another PR and it has already been added to a backlog. I plan to take a look today.

**Comment by sg1asgard** [comment]
> I think the failing test is flaky. Re-running it now to see if it passes. It's not related to your work here. I've seen it fail in another PR and it has already been added to a backlog. I plan to take a look today.

Ah, good to know. I've been triple checking my side and pocking around to see what is it all about to no avail : D

**Comment by markkaylor** [comment]
Looks like it could actually be a broken test on develop, I'll take a look in a second

**Pull request merged**
