### PR TITLE
removed text-transform from variable name

### PR DESCRIPTION
**Pull request by shabith**
#### Description of what you did:
Hello There!
I was following the tutorial and realize that variable names are capitalized, which is a bit misleading.
So thought of removing that.

image

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Really think this should be merged :)

**Comment by soupette** [comment]
I completely agree this should be merged it's really confusing to have a different casing than the one the user sets!

**Comment by soupette** [comment]
@Aurelsicoko can you jump in on this?

**Comment by Aurelsicoko** [comment]
Yes, let's do it! We should not modify the way the developer named the fields. We should not lowercase, or camelcase, or anything. Let things as they are ;)

LGTM

**Comment by shabith** [comment]
Thanks guys :)

**Pull request merged**
