### PR TITLE
feat: update react-router to v6

### PR DESCRIPTION
**Pull request by vdhpieter**
### What does it do?

Updates react-router to v6 (not finished)

### Why is it needed?

Strapi has a hard peer dependency on react-router v5. Because we have an integrated monorepo setup and use react-router v6 ourselves in other apps we get peerDependency errors. They are quite some breaking changes between the two (and v7 is on the way with more) so I thought let's try to update.

A second reason for this is that it's always a good idea to keep up to date with dependencies

### Following steps

I underestimated the task quite a bit but had fun in the process doing so. This PR is definitely not mergeable in the current state but while getting deeper and deeper I realised (AFAIK) that (almost?) all the plugins also have a definition for their own routes so they also need to be updated. The good news is that from react-router v6 routes can be defined with an object so the reliance of the plugins on react-router can be minified and updating should be easier in the future because that object could be transformed with code to follow the specs of newer versions.

I see 2 possible outcomes for this PR:

1. You don't have time for this/don't ever want to do it/have it planned way down the line (to long to keep updating this PR)/Want to take another approach for this update... This PR get's closed and I had a fun learning experience (no hard feelings)
2. You do think there is some value for it, but then some help from a more experienced Strapi dev and a concrete plan on how to do this with the plugins is needed. I'm definitely open in helping out with creating PR's on plugins/continuing on this PR... But wanted first to have a discussion before putting more time in

### CODE REVIEW

**Comment by joshuaellis** [comment]
Some things were removed from `react-router@6` correct? This would therefore potentially break a number of third party plugins no?

**Comment by vdhpieter** [comment]
@joshuaellis as described above:
>I realised (AFAIK) that (almost?) all the plugins also have a definition for their own routes so they also need to be updated
...
>a concrete plan on how to do this with the plugins is needed

**Comment by joshuaellis** [comment]
well we don't control third party plugins so i don't see how this is viable unfortunately 😅 we have this on our roadmap for v5 because it would be a breaking change for the plugin environment

**Comment by vdhpieter** [comment]
@joshuaellis What is the planned release schedule for v5?

**Comment by joshuaellis** [comment]
> @joshuaellis What is the planned release schedule for v5?

Q1 2024

**Pull request closed without merging**
