### PR TITLE
Tests: Explicit sorting where we test offset and limit

### PR DESCRIPTION
**Pull request by brettwillis**
### What does it do?

- [x] Change `expect().toMatchObject()` to `expect().toEqual(expect.arrayContaining())` so that, combined with a length check, array equality is tested while ignoring order.
- [x] Update the filtering tests to explicity specify a sort order when testing `_limit` and `_start` parameters.

### Why is it needed?

Currently, these tests are *implicitly* relying on the "natural" ordering returned from the query being the same as the order of creation of the fixtures. While this may be currently working, it is not technically correct as neither SQL or MongoDB (nor many other databases) *guarantee* insertion order (as far as I'm aware) without explicit sorting.

These tests may be flaky, especially for future connectors/databases.

Currently this issue is manifesting while I am developing [strapi-connector-firestore](https://github.com/arrowheadapps/strapi-connector-firestore), where the natural order is almost never the same as the insertion order, causing these tests to incorrectly fail.

### CODE REVIEW

**Review by alexandrebodin — COMMENTED** [review]
LGTM. If you are doing the test without order then I would prefer we don't add a hardcoded sort :)

**Comment by brettwillis** [comment]
@alexandrebodin I can't quite tell from your comment, are you requesting a change or is this good to go?

**Comment by alexandrebodin** [comment]
@brettwillis I was asking to remove the hardcoded _sort since you removed the need for ordering in the tests

**Comment by brettwillis** [comment]
@alexandrebodin hmm, there are two different issues here.

1. The test matchers comparing unsorted responses against sorted criteria. This is solved by comparing in a way that ignores order.

2. As per the title, and the topic of your comment, the specific situation when we are testing the functionality of `_start ` and/or `_limit`.

In the specific situation of item 2, I feel that explicit sorting is required. I think that `_start` and `_limit` only make sense in the context of an implied order in the database. I.e. "return the first item" is only predictable when there is an explicit order to determine what the "first" item is. How can we test what the result should be without explicit order?

Hence I have added explicit sorting for these specific tests of `_start` and `_limit`. Do you agree?

**Comment by alexandrebodin** [comment]
> @alexandrebodin hmm, there are two different issues here.
> 
> 1. The test matchers comparing unsorted responses against sorted criteria. This is solved by comparing in a way that ignores order.
> 2. As per the title, and the topic of your comment, the specific situation when we are testing the functionality of `_start ` and/or `_limit`.
> 
> In the specific situation of item 2, I feel that explicit sorting is required. I think that `_start` and `_limit` only make sense in the context of an implied order in the database. For example, "return the first item" is only predictable when there is an explicit order to determine what the "first" item is. How can we test what the result should be without explicit order? Strictly speaking, the "first" item of an unsorted query could be a different item every time.
> 
> Hence I have added explicit sorting for these specific tests of `_start` and `_limit`. Do you agree?

Makes complete sense I didn't notice in the diff it was on limit tests :)

**Review by alexandrebodin — APPROVED** [review]
Thank you for the improvements 💯

**Pull request merged**
