### PR TITLE
Remove cache key so the url is valid for cors policy

### LINKED ISSUE #10044: Throwing CORS error for downloading attachments on MediaLibrary from AWS S3 bucket
## Bug report
CORS error for downloading attachments on MediaLibrary from AWS S3 bucket though required CORS configuration is added to S3 bucket.

### Describe the bug

We migrated our Strapi app to AWS, we are not able to download attachments from Media Library, from AWS S3 bucket. 
It's throwing CORS error.

### Error:
Access to XMLHttpRequest at '<S3_bucket>.<S3_region>.amazonaws.com/<file_name>.jpeg' from origin '<our_domain>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Steps to reproduce the behavior

1. Run Strapi app connecting to AWS S3 Bucket and Mongo DB.
2. Open Media Library and upload attachments/images
3. Open any attachment and try to Download it
3. Throws CORS error 

### Expected behavior

Attachments from Media Library, S3 bucket can be Downloaded.

### Help needed:

**Note:** We have added required CORS configuration on our S3 Bucket. 

### System

- Node.js version: v14.8.0
- NPM version: 6.14.7
- Strapi version: v3.0.6
- Database: Mongo
- Operating system: MAC

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Fixes #10044

@vinod77 can you test this ?

### CODE REVIEW

**Review by derrickmehaffy — APPROVED** [review]
LGTM, tested under the conditions defined in the parent issue and it works perfect.

Nice fix :)

**Review by soupette — APPROVED** [review]
LGTM

**Comment by abett** [comment]
I think I've occasionally had an error similarly to what you have fixed.
Do I need to reupload or do anything with my files on s3 (using digitalocean) now, or has this been purely a strapi-side problem which is now fixed?

**Comment by derrickmehaffy** [comment]
> I think I've occasionally had an error similarly to what you have fixed.
> Do I need to reupload or do anything with my files on s3 (using digitalocean) now, or has this been purely a strapi-side problem which is now fixed?

It should be Strapi side and there shouldn't be a need to re-upload files as the issue didn't have anything stored in the database, was just how we constructed the headers

**Pull request merged**
