### PR TITLE
fix:: uncaught error: FormModalHeader

### PR DESCRIPTION
**Pull request by rajaadubey**
### What does it do?

added null check

### Why is it needed?

there is null check 

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/20339

### CODE REVIEW

**Comment by joshuaellis** [comment]
Can you fill out the template in detail please, e.g. how do we reproduce the bug, how do we test, how did you come to this solution etc.

**Comment by joshuaellis** [comment]
> > Can you fill out the template in detail please, e.g. how do we reproduce the bug, how do we test, how did you come to this solution etc.
> 
> updated issue #20339

PRs are a form of history, and your current description is lacking how you came to your conclusion, for example at the moment im not convinced on your solution, it just masks the issue, why is the schema null there when it should be defined at this point? etc.

**Comment by alexandrebodin** [comment]
> [!IMPORTANT] 
> With the release of Strapi 5, we have lifted the code freeze. To ensure we can effectively review and assist with contributions, we are now only accepting PRs targeting version 5 (the develop branch).<br/> 
> As your PR is targeting some of the most recent v4 version, We we would greatly appreciate it if you could update your contribution to align with version 5 and resubmit!

**Comment by hanpaine** [comment]
Original Issue ticket has been closed as unable to reproduce and no response on this ticket since May so closing

**Pull request closed without merging**
