### PR TITLE
Sort field

### PR DESCRIPTION
**Pull request by GomatoX**
### What does it do?

Adds new type of field with sort features.

### Whats missing?

- [ ] Icon in buffet js for new type field (help wanted)
- [x] Add restriction to add only one sort field
- [x] Translations
- [ ] Show/hide sorter field in collection edit view

### Video as concept

collection:

https://user-images.githubusercontent.com/2634448/111315496-1bbe2180-866b-11eb-92df-2b5eb136b146.mov

content-builder:

image

### Why is it needed?

To sort collection items.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/3946

### CODE REVIEW

**Comment by ig1na** [comment]
Why is it still a draft ?

**Comment by soupette** [comment]
@GomatoX thank you for your contribution. However such addition should follow the RFC process. 
Do you mind creating a RFC pull request in this [repository](https://github.com/strapi/rfcs) so the Team (we) can provide feedback and maybe guidelines for such addition?

**Comment by GomatoX** [comment]
@soupette I will do!

**Comment by derrickmehaffy** [comment]
Hi 👋  
We now have released the `v4`. As of now, the `v3` is in maintenance mode for 6 months. We will only be fixing critical and security issues on v3 from now on. 
I will go ahead and close this PR. Thank you for contributing to Strapi 🔥

**Comment by creazy231** [comment]
Feature still missing in v4 sadly :(

**Comment by derrickmehaffy** [comment]
> Feature still missing in v4 sadly :(

always welcome to reopen a PR based on the v4, we were just doing a lot of cleanup of older PRs we didn't get a chance to review.

**Pull request closed without merging**
