### PR TITLE
Add ENV to allow hiding startup message

### PR DESCRIPTION
**Pull request by peterbaricic**
Hi,
our devops team wanted me to disable the startup message, but because there is no way to turn it off, I added an ENV `STRAPI_HIDE_STARTUP_MESSAGE` to allow user to hide the startup message.

I would also update the docs, but there is no documentation currently mentioning any existing logging ENVs like STRAPI_LOG_LEVEL, STRAPI_LOG_PRETTY_PRINT, STRAPI_LOG_FORCE_COLOR and STRAPI_LOG_TIMESTAMP.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@alexandrebodin @lauriejim maybe we need to make a place on the documentation to cover any existing environment variables in use? (For example the JWT_SECRET)

**Comment by peterbaricic** [comment]
why is travis always failing on E2E mysql (full pool)?

**Comment by derrickmehaffy** [comment]
> why is travis always failing on E2E mysql (full pool)?

You can ignore this for now, work is being done to try and solve this not only in tests but user projects as well (some default options I believe are set too low)

**Comment by alexandrebodin** [comment]
Hi @peterbaricic would you mind working on adding this var to the documentation ? 

@lauriejim Can you tell us where you would put these docs ?

**Comment by peterbaricic** [comment]
Sure, I can add it, just please point me to the right docs :-)

**Comment by lauriejim** [comment]
Hello and sorry for the delay.
Since we haven't specific documentation for global env variable, I think you can add a paragraph on this page:
https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-start

```
[...]. Certain features are disabled in the `strapi start` mode because they require application restarts.

Allowed environment variables:

| Property | Description | Type | Default |
| --------- | ----------- | ----- | ------- |
| STRAPI_HIDE_STARTUP_MESSAGE | [your description...] values can be `true` or `false` | string | `true` |
```

Having a table like this could be a good option.

**Pull request merged**
