### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tunasakar**
fastandcomfy.io is down!

### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @tunasakar Not sure if it is a temporary downtime or the company who went down :/ any insight on that from your side ?

**Comment by tunasakar** [comment]
Hi Alexandre,
I'm not sure either, but I checked it for you;
I checked the latest snapshots on Wayback Machine and it is displayed as of
May 2020 and their last post on Facebook is November 2020.
They have been offline for at least 2 months.


[image: photo]
Tuna Sakar
SysAdmin | Developer
Codex Uno
+90 530 725 0804
tuna@tunasakar.com
https://www.codexuno.com
<http://us.linkedin.com/in/tunasakar>
<http://zoom.us/j/6102419757?pwd=ZThMTGZ4UjRRT2hwUmxISi9vOWliUT09>
<http://twitter.com/tunasakar> <http://github.com/tunasakar>

IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.
<https://onestream.live?deal=codexuno>

Alexandre BODIN <notifications@github.com>, 12 Şub 2021 Cum, 17:25
tarihinde şunu yazdı:

**Comment by tunasakar** [comment]
> Hi @tunasakar Not sure if it is a temporary downtime or the company who went down :/ any insight on that from your side ?

Hi @alexandrebodin,
I'm not sure either, but I checked it for you;
I checked the latest snapshots on Wayback Machine and it is displayed as of May 2020 and their last post on Facebook is November 2020.
I don’t have more information.

**Comment by alexandrebodin** [comment]
Thanks you for check @tunasakar  💯  Let's remove it then

**Review by alexandrebodin — APPROVED** [review]
LGTM 👍

**Comment by tunasakar** [comment]
> Thanks you for check @tunasakar 💯 Let's remove it then

you're welcome @alexandrebodin

**Pull request merged**
