### PR TITLE
Add display name to display a user friendly name for content types on admin menu

### PR DESCRIPTION
**Pull request by kzhang7**
Add display name to display a business friendly name for content types on admin menu

#### Description:
Currently strapi always automatically rename `My Sample Model`  to `Mysamplemodels` which is not user-friendly.

There are several issues related to this, for example: https://github.com/strapi/strapi/issues/1736

I added an additional field on the new model creation screen called "displayName" to allow admin to define a user-friendly display name for the model. The user-friendly display name will be shown in the admin menu.

#### My PR is a:
- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix #issueNumber
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:
- [x] Admin
- [ ] Documentation
- [ ] Framework
- [ ] Plugin

#### Manual testing done on the following databases:
- [ ] Not applicable
- [x] MongoDB
- [x] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@kzhang7 nice job can you give a screenshot?

**Comment by kzhang7** [comment]
Here is the screenshot:
image

**Comment by soupette** [comment]
@kzhang7 Thanks for the pull request unfortunately the `content-type-builder` has entirely been recoded and the PR #2954 will soon  be merged, so you need to apply the modifications to the new codebase...

**Comment by kzhang7** [comment]
@soupette so we will have a simpler front-end code for `content-type-builder` soon. That's great news! I will re-apply my changes after #2954 is merged.

**Comment by maciejcieslik** [comment]
Can you add such labels to attributes fields too? This is huge problem with localized strapi, where I need to setup names in english and without spaces for fields and then explain client what is what, no mention it's weird that some backend is in one language and fields are in another...

**Comment by Aurelsicoko** [comment]
I'm not okay with the way of handling this issue. The logic should be inverted. We should keep the input "name" at the top of the form. In this input, we should type "Contact Us Page", then another field below should generate a kind of slug "contactUsPage" and this slug should be editable.

With this solution it means that the user has to type twice the same string. I'm not a big fan of this.

**Comment by kzhang7** [comment]
@Aurelsicoko Great idea. I will try implementing that instead once the PR #2954 is merged. But I probably still keep the new input as `display name` or `label`, but move it to the top. So that we can keep the original `name` field as is, to avoid renaming and refactoring hundred of files.

for the auto-generating part, what should be the behavior if the `display name` is not in English? I guess I will just leave the `name` field as empty for the user to define. Do you have any better idea?

@maciejcieslik It is a good idea to add such label to attributes fields too. But to me I can live with it since the attribute field allows underscores to separate English words (we do not have localization requirement).  I will look into it if I have time in a separate PR.

**Comment by Aurelsicoko** [comment]
@kzhang7 If the user tapes "Contact Us", it should generate in the other input "contactUs". If the user tapes "Contactez-nous" (in French), it should generate "contactezNous".

We should not care about the language.

**Comment by maciejcieslik** [comment]
> @kzhang7 If the user tapes "Contact Us", it should generate in the other input "contactUs". If the user tapes "Contactez-nous" (in French), it should generate "contactezNous".
> 
> We should not care about the language.

Exactly and strip the string from all diactric marks that now cause errors - this should be implemented from start or strapi will not be popular worldwide.

**Comment by Aurelsicoko** [comment]
@maciejcieslik we are making mistakes but we try to learn quickly and fix them as soon as possible 👍

**Comment by kzhang7** [comment]
> @kzhang7 If the user tapes "Contact Us", it should generate in the other input "contactUs". If the user tapes "Contactez-nous" (in French), it should generate "contactezNous".
> 
> We should not care about the language.

I meant non-English character languages, such as Chines or Japanese. If the `displayName` is not in English characters, we do not have a way to auto-generate the `name` field.

I just had a chance to work on this. But I could not find a way to update the `name` field with `onChange` or `keyUp` event of the `displayName` field. I could listen to the event and get the value of the `displayName` field, but there is no way to set the value to the `name` field because the form is dynamically built from a JSON schema. Do you have any suggestions?

**Comment by Aurelsicoko** [comment]
@kzhang7 I think @lauriejim or @soupette might be able to help you on this 👍

**Pull request closed without merging**
