### PR TITLE
chore: make document service api more consistent

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

chore: make document service api more consistent

### Why is it needed?

v5

### CODE REVIEW

**Review by Marc-Roig — APPROVED** [review]
nice! 🕺 

this change might affect content history middleware too

**Comment by alexandrebodin** [comment]
@Marc-Roig I'm wondering if we should return entries on update & create too at some point (when/if we allow creating multiple locales at once)

**Comment by Marc-Roig** [comment]
do we plan to allow it? I find the scenario of updating multiple locales with the same values a bit rare. And probably non localized fields might cover many of those use cases.

It's true that it would standarize the response between the other methods, but at the same time it would make the migration a bit more complex. So I don't know either 🤔

**Comment by alexandrebodin** [comment]
> do we plan to allow it? I find the scenario of updating multiple locales with the same values a bit rare. And probably non localized fields might cover many of those use cases.
> 
> It's true that it would standarize the response between the other methods, but at the same time it would make the migration a bit more complex. So I don't know either 🤔

For now I don't see a usecase either, just not a fan of the response differences even if a bit more consistent with this PR

**Pull request merged**
