### PR TITLE
[DS] Typography in API tokens

### PR DESCRIPTION
**Pull request by ronronscelestes**
## What

Replaced Text components with Typography in API tokens views

Fixed snapshots which didn't wait for data to be loaded

### CODE REVIEW

**Review by HichamELBSI — CHANGES_REQUESTED** [review]
You'll need to update the snapshots IMO

**Comment by ronronscelestes** [comment]
> You'll need to update the snapshots IMO

The snapshot didn't need to be updated because it doesn't have any API tokens in it!

Screenshot 2021-11-15 at 18 33 25

**Comment by ronronscelestes** [comment]
> > You'll need to update the snapshots IMO
> 
> The snapshot didn't need to be updated because it doesn't have any API tokens in it! @HichamELBSI
> 
> Screenshot 2021-11-15 at 18 33 25

**Review by HichamELBSI — APPROVED** [review]
LGTM

**Pull request merged**
