### PR TITLE
[Feature]: Clone relation relationships

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by Boegie19** [comment]
Question how are you planning to handle many to one relations
since if you clone that one it will become a many to many

**Comment by Marc-Roig** [comment]
@Boegie19 It needs some testing, but I have pushed some code for cloning many to one relations :) 

Instead of inserting new relations, I am updating the previous one to use the new entity id, instead of the one being cloned.

It needs more testing and thinking, I will be tinkering with this during next week 🔨

**Comment by Boegie19** [comment]
Would work but it willl always leave the copy or the original witout the relation so it is never a perfect clone.

**Comment by Marc-Roig** [comment]
> Would work but it willl always leave the copy or the original witout the relation so it is never a perfect clone.

Agree, but it will have the same behaviour as if some user manually adds those relations. 
It will be a clone, but following the definitions of what a relation is in Strapi.

**Pull request closed without merging**
