### PR TITLE
v5.1.0 into develop

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Review by Convly — APPROVED** [review]

**Review by remidej — COMMENTED** [review]
From the latest convos with Alex I think the new process is merge the release into main (not develop), then `git merge main` into develop directly

**Comment by innerdvations** [comment]
> From the latest convos with Alex I think the new process is merge the release into main (not develop), then `git merge main` into develop directly

do we have permissions to push directly to develop? I thought that was blocked

**Comment by remidej** [comment]
With the releaser role you should be able to do it (it works for me)

**Comment by innerdvations** [comment]
Done via a direct merge main

**Pull request closed without merging**
