### PR TITLE
add media attribute validator

### PR DESCRIPTION
**Pull request by Marc-Roig**
### 👋🏻 What does it do?
You could create an entity via the REST API with an empty media attribute that was required.
Now it will be required and you will receive a 400 Validation error.

### 🧪 How to test it?

Very well explained in https://github.com/strapi/strapi/issues/14648.

<details>
<summary>Example Content Type Schema</summary>

```json

{
  "kind": "collectionType",
  "info": {
    "displayName": "Test",
    "singularName": "test",
    "pluralName": "tests",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "attributes": {
    "name": {
      "type": "string",
    },
    "media": {
      "type": "media",
      "multiple": false,
      "required": true,
      "allowedTypes": ["images", "files", "videos", "audios"]
    },
    "medias": {
      "allowedTypes": ["images", "files", "videos", "audios"],
      "type": "media",
      "multiple": true
    }
  }
}
```

</details>

<details>
<summary>Example Request</summary>
POST http://localhost:1337/api/tests

```json

	{
	    "media": 10,
	    "medias": [{"id": 8}],
	    "name": "test"
	}

```

</details>

### 🔍 Expected behavior

**Scenario 1: Single media attribute**
- Given I have a content type with a required media attribute
- When I use the REST API to create an entity
   And I create it without the media attribute
- I receive a 400 Validation Error

**Scenario 2: Multiple media attribute**
- Given I have a content type with a required multiple media attribute
- When I use the REST API to create an entity
   And I create it without the multiple media attribute
- I receive a 400 Validation Error

### 🔗Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/14648

### CODE REVIEW

**Review by jhoward1994 — APPROVED** [review]
Looks good 🙂

**Comment by petersg83** [comment]
Interesting, I need to take the time to look at it as media are relations and we don't enforce "required" on relations. So I wonder what is currently done with media and what needs to be done.
Example: what happens if I delete the media afterwards?

**Comment by Marc-Roig** [comment]
> Interesting, I need to take the time to look at it as media are relations and we don't enforce "required" on relations. So I wonder what is currently done with media and what needs to be done. Example: what happens if I delete the media afterwards?

That is a good point, and I think this is more of a product decision that was taken when we let users select media as required.
RN you can have required media field and delete the media afterwards. That leaves you with an invalid entity I guess. I can test this a little bit more to see what implications it has.

**Comment by Marc-Roig** [comment]
After further discussions, we have agreed to push this forward in order to be consistent with how the CM works.

**Comment by jhoward1994** [comment]
I think we should rename the test file now to a `test.api.js` file

**Comment by Marc-Roig** [comment]
@jhoward1994 good catch

**Review by jhoward1994 — APPROVED** [review]
Looks good 👍🏻

**Review by jhoward1994 — APPROVED** [review]

**Pull request merged**
