### PR TITLE
Use explicit path

### PR DESCRIPTION
**Pull request by jimmywarting**
It dose not look like you are going to switch to ESM any time soon.
But preparing for it can be good without breaking things.

ESM requires explicit path

> Mandatory file extensions[#](https://nodejs.org/dist/latest-v19.x/docs/api/esm.html#mandatory-file-extensions)
A file extension must be provided when using the import keyword to resolve relative or absolute specifiers. Directory indexes (e.g. './startup/index.js') must also be fully specified.
> 
>  This behavior matches how import behaves in browser environments, assuming a typically configured server.

this is also better for commonjs as it dose not have to 2nd guess what file it needs to import so it is less stat-ing directories and looking for matches. so things loads faster

it should be made a best practices

### CODE REVIEW

**Comment by joshuaellis** [comment]
I don't agree with this, with the correct setup you can omit the file extension.

**Comment by jimmywarting** [comment]
Even if your are using cjs dose mean that you should.
guess you haven't seen https://youtu.be/M3BM9TB-8yA?t=838

**Comment by joshuaellis** [comment]
> Even if your are using cjs dose mean that you should. guess you haven't seen [youtu.be/M3BM9TB-8yA?t=838](https://youtu.be/M3BM9TB-8yA?t=838)

No i haven't, it's also from four years ago. Most bundlers can differentiate between `esm` / `cjs` etc. without the need for a file path – vite for example. With webpack, we applied a setting on the rule:

```js
resolve: {
	fullySpecified: false,
},
```

So the bundler can differentiate on it's own.

**Comment by joshuaellis** [comment]
closing due to inactivity, we can revisit this again if needs be.

**Pull request closed without merging**
