### PR TITLE
Updating email instructions to update shipper email on template to avoid sender email error

### PR DESCRIPTION
**Pull request by juancarlosjr97**
Avoid the error if the user has not changed the shipper email on the template, and provide a quick guidance

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello! it looks like there is a conflict on the file, can you please have a look @juancarlosjr97 
Thank you :)

**Comment by MattieBelt** [comment]
@juancarlosjr97 any update? I still think this is a good tip to add to the docs.

**Comment by juancarlosjr97** [comment]
@MattieBelt it was added to a new PR #7413 :) 

Thank you!

**Comment by MattieBelt** [comment]
Did not see that :), thanks. (problem on my side)

**Pull request closed without merging**
