### PR TITLE
Add --template option to create-strapi-app

### PR DESCRIPTION
**Pull request by remidej**
### Description of what I did

I added a `--template` option to the `create-strapi-app` CLI.

Right now, every project created with `create-strapi-app` is an empty Strapi project. This will remain the default, but we also want to help users bootstrap projects that are preconfigured for specific use cases. After discussions with @alexandrebodin and @Convly , we designed a specification for this that relies on a **new template system**.

It looks like this:

```bash
# Using yarn
yarn create strapi-app my-strapi-app --template <template-github-url>

# Using npm
npx create-strapi-app my-strapi-app --template <template-github-url>
```

A template's only concern should be to adapt Strapi to a use case. It should not deal with environment-specific configs, like databases, upload or email providers. This is to make sure they are maintainable, and to avoid conflicts with other CLI options like `--quickstart`.

These templates are meant to be an important piece of our upcoming starters system. To clarify:

- A *template* is a pre-made Strapi configuration
- A *starter* is a pre-made frontend application that consumes a Strapi API

### How it works

A template is a GitHub repository. This way, it's fully open. Any community member can create a template, not just the Strapi team.

Inspired by [create-react-app](https://create-react-app.dev/docs/custom-templates/), here is the structure a template should follow:

```txt
.
├── README.md
├── .gitignore
├── template.json
├── template
│   ├── README.md
│   ├── .env.example
│   ├── api/*
│   ├── components/*
│   ├── config
│   │   └── functions/*
│   ├── data/*
│   ├── plugins/*
│   ├── public/*
│   └── scripts/*
```

- `README.md` and `.gitignore` are meta files: They only affect the template itself, not the projects made with it.
- `template.json` is used to extend the default `package.json` of a Strapi project. We can use it to add scripts and dependencies.
- `template/` is the folder where you can extend the file contents of a Strapi project. It can contain any of the following:
  - `README.md`: the readme of app made with this template
  - `.env.example`: to specify required environment variables
  - `api/`: for collections and single types
  - `components/` for components
  - `config/` can only include the `functions` directory (things like `bootstrap.js` or `404.js`). That's because other config files are environment-specific.
  - `data/` to store the data imported by a seed script
  - `plugins/` for custom Strapi plugins
  - `public/` to serve files
  - `scripts/` for custom scripts

If a template doesn't follow this structure, the installation will crash.

### Try it out

You can try it by calling the node script locally:

```bash
# Template that adds an Article collection
node ./path-to-this-strapi-fork/packages/create-strapi-app/index.js my-strapi-app --template https://github.com/remi2j/strapi-template-dummy-article

# Template that will crash because it doesn't follow the structure
node ./path-to-this-strapi-fork/packages/create-strapi-app/index.js my-strapi-app --template https://github.com/remi2j/strapi-template-dummy-illegal
```

### Things to figure out

- There are already some things called "templates" in the CLI for database configs. We should find a new name for these to avoid confusion.
- Should seed data be imported automatically? Or should it be left as an additional command?

### CODE REVIEW

**Comment by remi2j** [comment]
See more discussion about this PR at #7626

**Review by alexandrebodin — APPROVED** [review]
LGTM. Good job 💯

**Comment by bernardro** [comment]
hey @remidej @alexandrebodin - thanks for this 
I noticed the documentation says this:

`A template is only useful once applied on top of a default Strapi app via the CLI`

When I look at the CLI documentation I only see this
```
strapi new <name> --dbclient=<dbclient> --dbhost=<dbhost> --dbport=<dbport> --dbname=<dbname> --dbusername=<dbusername> --dbpassword=<dbpassword> --dbssl=<dbssl> --dbauth=<dbauth> --dbforce
```

is `create-strapi-app --template` the only way to apply a template for now?

**Comment by alexandrebodin** [comment]
Hi @bernardro indeed create-strapi-app is the one you need to be using for this.

**Comment by bernardro** [comment]
thank you @alexandrebodin

**Pull request merged**
