### PR TITLE
anchor leading to 404 page

### PR DESCRIPTION
**Pull request by aretw0**
#### Description of what you did:
The old anchor is leading to a 404 page, and I just set it right.

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @aretw0 your PR contains unwanted commits (you must have started it from master instead of the documentation branch) :) Can you please update it so there is only your commit ?

**Comment by aretw0** [comment]
Oh, sorry. I'm not used to doing this. I think I have changed now, can you confirm? Is still worth it?

**Comment by alexandrebodin** [comment]
Hi @aretw0 sadly your PR still contains a lot of commits you didn't make :/ If you are really struggling you might want to create a new PR. sometimes it is the easier approach

**Comment by aretw0** [comment]
I might do it

**Pull request closed without merging**
