### PR TITLE
Update strapi-admin & plugins Brazilian Portuguese (pt-BR) language translations

### PR DESCRIPTION
**Pull request by natanaelsimoes**
### What does it do?

Adds missing translations and corrects existing on strapi-admin and every plugin.

### Why is it needed?

To prevent mixed language content while using admin interface in Brazilian Portuguese language.

### CODE REVIEW

**Comment by kazzkiq** [comment]
This looks like a pretty simple PR to merge, since all changes were made on JSON translation files (no JS/TS code changes). Is there any ETA on this?

Also, good work @natanaelsimoes.

**Review by HichamELBSI — APPROVED** [review]
Hi @natanaelsimoes, Thank you for the contribution. Looks pretty good to me.

**Comment by HichamELBSI** [comment]
Can you update the branch please 😅

**Comment by natanaelsimoes** [comment]
@HichamELBSI branch updated!

**Review by HichamELBSI — APPROVED** [review]
LGTM can you fix the branch please

**Comment by natanaelsimoes** [comment]
@HichamELBSI PR ready to merge!

**Review by DerOrangeBaron — APPROVED** [review]

**Comment by derrickmehaffy** [comment]
Hi 👋  
We now have released the `v4`. As of now, the `v3` is in maintenance mode for 6 months. We will only be fixing critical and security issues on v3 from now on. 
I will go ahead and close this PR. Thank you for contributing to Strapi 🔥

**Pull request closed without merging**
