### PR TITLE
translate en to zh-Hans by using claude.ai

### PR DESCRIPTION
**Pull request by smoothdvd**
### What does it do?

Translate en to zh-Hans by using claude.ai

### Why is it needed?

More relevant Chinese translation

### How to test it?

Change language to zh-Hans in user's profile

### CODE REVIEW

**Review by gu-stav — COMMENTED** [review]
Hello 👋🏼 

Did you take some time to review these (automated) translations already?

**Comment by smoothdvd** [comment]
Yes. I already reviewed them before pull request.

**Comment by gu-stav** [comment]
@smoothdvd Could you please address the merge conflict? After this is is ready to go :)

**Comment by smoothdvd** [comment]
Resolved!

**Review by gu-stav — APPROVED** [review]

**Review by gu-stav — APPROVED** [review]

**Pull request merged**
