### PR TITLE
Enhance blocks link validation

### PR DESCRIPTION
**Pull request by Ben-Zahler**
### What does it do?

Enable users to create mailto, tel and relative links in the blocks editor.
https://github.com/strapi/strapi/issues/18562

### Why is it needed?

Describe the issue you are solving.

### How to test it?

1. Create a new strapi entry for a type that contains a "blocks" field
2. Create a text link
3. enter one of the following values for the link
    - mailto:strapi@strapi.io
    - tel:+123456789
    - /strapi
5. Save the link and then save the entry
6. The link should be saved successfully.

### Related issue(s)/PR(s)
https://github.com/strapi/strapi/issues/18562

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by Ben-Zahler** [comment]
sorry for the failed prettier check, locally I get:
> Checking formatting...
> All matched files use Prettier code style!
I will investigate what needs to be tweaked.

**Comment by remidej** [comment]
Hey and thanks for the PR!

I like what you're doing here, but I unfortunately can't merge it. Mainly because we've recently changed the way links are validated on the frontend, [as seen in this PR](https://github.com/strapi/strapi/pull/19052/files). The changes just haven't propagated to the develop branch yet, but that should happen next week.

What will be left to do is to update the link validation on the backend to match what the frontend is doing: just rely on `new URL()`, if it doesn't throw then the link is allowed. That should enable mailto links, as well as any other protocol, like ftp, tel, magnet etc. So no more need to keep a whitelist.

Let us know if you'd like to open the PR to do that, otherwise we'll do it ourselves soon.

**Comment by Ben-Zahler** [comment]
thanks for checking my PR, @remidej !
I only now found time to look into this and I found that on the 4.17.0 branch, relative links are still getting blocked in the editor, but they're passing validation in the backend (I did not check why).

Editor validation fails because `new URL('/relative')` throws an exception.

There is an easy fix I created on a branch from the 4.17.0 branch that can be applied to develop after it's merged back:
https://github.com/strapi/strapi/compare/releases/4.17.0...Ben-Zahler:strapi:18562-blocks-enable-relative-links
What do you think? for me, nopt having relative links available is a blocker and I really want to migrate to blocks editor because my authors don't can't handle markdown.

**Comment by CodeDruid13** [comment]
Closely following as this has been an issue for a while now. @remidej please look into and merge this issue.

**Comment by djoohl** [comment]
Second this. I need to have mailto: + relative links. Please review and merge this.

**Pull request closed without merging**
