### PR TITLE
[Relations] Move connect/disconnect

### PR DESCRIPTION
**Pull request by ronronscelestes**
## What

Move connect and disconnect creation in `EditViewDataManagerProvider` reducer from `LOAD_RELATION` to `CONNECT_RELATION`/`DISCONNECT_RELATION`

### CODE REVIEW

**Review by gu-stav — APPROVED** [review]
Code looks good to me, thanks. I think the tests will break, but they are easy to fix.

**Comment by gu-stav** [comment]
@ronronscelestes Did you test it? It looks like as if I'm not able to add new relations ...

**Comment by ronronscelestes** [comment]
> @ronronscelestes Did you test it? It looks like as if I'm not able to add new relations ... If the tests are not broken and it works we can merge it. I need to add new ones anyways ...

mmh weird, I tested it again, I'm able to add and remove them 🤔

**Comment by ronronscelestes** [comment]
@gu-stav 

https://user-images.githubusercontent.com/71838159/189086860-a698c758-dba6-4fb2-a533-905ea2ef4637.mov

we have other issues (once a relation is removed it won't appear in search because we omit them - I'll have a look into it) but I can add and remove

**Pull request merged**
