### PR TITLE
Validation lifespan during the creation of a token

### PR DESCRIPTION
**Pull request by simotae14**
### What does it do?

Describe the bug
As an admin user, when I enter the page to create a new token, the frontend validation is not applied on the “Token duration” field.

Steps to reproduce the bug
access the API tokens settings

create a new token

save without editing the token duration field

the validation messages are not displayed for the token duration selector

☑️ Acceptance criteria
Expected behavior
Frontend validation is also applied on the token duration field; as an admin user, I can’t proceed to save the token if I don’t select a token duration.

### CODE REVIEW

**Review by Convly — APPROVED** [review]
LGTM

**Comment by simotae14** [comment]
I agree but after the release I want to refactor the code and add some more tests so maybe I can add this one to the list of what I have to do

**Review by ronronscelestes — APPROVED** [review]
LGTM

**Review by Convly — CHANGES_REQUESTED** [review]
It works well overall, however I noticed that setting the value using the keyboard only works for "unlimited" and not for numerical values, do you have an idea on what's going on?

lifespan-validation

**Comment by simotae14** [comment]
unfortunately it doesn't work even in the main branch, I can try to take a look and understand the problem or we can open a bug after the release (I am not sure is just related to this field and also Unlimited has the null value)

**Review by Convly — APPROVED** [review]
LGTM

**Pull request merged**
