### PR TITLE
Add the FAQ in the documentation

### PR DESCRIPTION
**Pull request by lauriejim**
**My PR is a:**
- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix #issueNumber
- [x] 💅 Enhancement
- [ ] 🚀 New feature

**Main update on the:**
- [ ] Admin
- [x] Documentation
- [ ] Framework
- [ ] Plugin

**Manual testing done on the following databases:**
- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres

**Description:**

I would like to move the wiki stuff in the documentation. That is why this PR exist.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Mmmmmm We could move the FAQ there also, but It is nice to have it on the github as well (easier to update)

**Comment by lauriejim** [comment]
It's the FAQ 🤔

Duplicate information is not a good thing I think.
And I prefer centralize information in one place, the documentation.

**Comment by derrickmehaffy** [comment]
The downside @lauriejim is in order to add new information to the FAQ a PR has to be made, merged, and the docs have to be redeployed. And if other changes are made to the docs during that time, there might be a case where the docs are updated on something that isn't in a release yet.

**Comment by derrickmehaffy** [comment]
That is making the assumption that the docs are not automatically deployed from the master branch and are redeployed manually, but in either case my above statement is still valid.

In my opinion it would be better to hard code into the docs a link to the FAQ on the wiki, or split the FAQ into two parts:

Developer FAQ (Github)
User FAQ (Docs) 

However the FAQ is typically a good place to put common issues (such as ones that come up in a release) and ways to work around them which will be subject to change quite often.

**Comment by lauriejim** [comment]
This documentation make my brain 🤯

**Comment by derrickmehaffy** [comment]
@lauriejim I see FAQ as different than normal docs. FAQ is something that is very volatile. Stuff that subject to change often and quickly. So I think they should remain in a place that allows for that quick change.

Typically if I see a common issues I will update the FAQ with a fast work around.

**Pull request closed without merging**
