### PR TITLE
[WIP] Update knex and bookshelf versions to latest

### PR DESCRIPTION
**Pull request by derrickmehaffy**
#### Description of what you did:

Update both knex and bookshelf plugins to latest versions

- Knex changelog: https://github.com/knex/knex/blob/master/CHANGELOG.md
- Bookshelf changelog: https://github.com/bookshelf/bookshelf/blob/master/CHANGELOG.md

Key Knex changes:
- orderBy accepts QueryBuilder
- Fix bugs in replacement logic used when dropping columns in SQLite
- Fix concurrent child transactions failing
- Add SSL/TLS support for Postgres connection string
- Allow to extend knex query builder
- Add .isCompleted() to transaction
- Pooling: tarn.js connection pool was updated to version 2.0.0. This fixes issue with destroying connections and introduces support for connection pool event handlers. Please see tarn.js documentation for more details

**Knex breaking changes:**
- Pooling: `beforeDestroy` configuration option was removed (Need to note to Strapi users to remove this from their config)

Key Bookshelf changes:
- Fix JSON.stringify causing TypeError in some cases
- Depends updates (should help clean up any depreciate warnings)
- Promote some useful plugins to core (Pagination plugin added by default)

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Letting TravisCI run it's tests then I'll do some manual testing but so far I don't believe there should be any breaking changes. Marked as WIP until I get the chance to test with the 3 core DBs

**Comment by derrickmehaffy** [comment]
May need some additional work for migration on bookshelf: https://github.com/bookshelf/bookshelf/wiki/Migrating-from-0.15.1-to-1.0.0

**Comment by derrickmehaffy** [comment]
Issues with travis:

```
[2019-11-04T21:35:26.663Z] error Impossible to register the 'permission' model.
[2019-11-04T21:35:26.663Z] error CustomError: EmptyResponse
```

Appear to come from the new requiredFetch stuff that was added, will try to track this down.
https://github.com/bookshelf/bookshelf/wiki/Migrating-from-0.15.1-to-1.0.0#default-to-require-true-on-modelfetch-and-collectionfetchone

**Comment by alexandrebodin** [comment]
@derrickmehaffy this is already updated in develop :) will be released with the upcoming beta.18

**Comment by derrickmehaffy** [comment]
Well crap lol, alright I'll close this out. :man_facepalming: forgot to even look at develop.

**Pull request closed without merging**
