### PR TITLE
chore: only use node 18 for lint

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* only uses node 18 for lint

### Why is it needed?

* Eslint doesn't behave differently on different node versions
* reduce load on GH actions

### CODE REVIEW

**Comment by joshuaellis** [comment]
We would need to remove the required checks for lint 14 & 16 before merging.

**Review by Marc-Roig — APPROVED** [review]

**Comment by alexandrebodin** [comment]
I think that in the past this wasn't true and we had lint errors in node 14 and not in other versions 🤔 which made use avoid some js features

**Comment by gu-stav** [comment]
@alexandrebodin Why do you think this happened? The eslint rules are the same across node versions ...

**Comment by alexandrebodin** [comment]
I think it might be that it allowed us to catch usage of features that weren't available in node 14 when we ran eslint but wasn't specific to eslint itself I can't remember much more than that.

But if we are sure no eslint rules is dependent on detecting the node version I'm fine running only on one node versions. Might be worth doing a quick check on the eslint plugins we use like the node and import ones 🤔

**Comment by joshuaellis** [comment]
import doesn't seem to have an issue, it looks like `eslint-plugin-node` is quite out of date (hasn't been updated since 2020) and doesn't work as you'd expect e.g `String.replaceAll` was added in node 15 but using node 14 there are no issues reported :(

It also seems to have issues with workspaces as well – https://github.com/mysticatea/eslint-plugin-node/issues/253

Considering it's not working as expected, how you would you proceed @alexandrebodin?

**Comment by alexandrebodin** [comment]
We will get ride of it during v5 upgrades I think. It needs ot be dealt with in our share eslint config. You can go ahead with node 18 only linting for now I think

**Comment by joshuaellis** [comment]
> We will get ride of it during v5 upgrades I think. It needs to be dealt with in our shared eslint config. You can go ahead with node 18 only linting for now I think

Would you be able to remove the required checks for 14 & 16 please? :)

**Review by alexandrebodin — APPROVED** [review]

**Pull request merged**
