### PR TITLE
upload-aws-s3 plugin add baseUrl config

### PR DESCRIPTION
**Pull request by limichange**
### What does it do?

The rich text content contains the full image address. Migration has become a hassle, so I would like to set up a custom domain directly.

### Why is it needed?

Add a base URL to the file path.

### How to test it?

Upload a file.

### Related issue(s)/PR(s)

Nope.

### CODE REVIEW

**Comment by limichange** [comment]
If the user sets the base URL, the file upload result will use the base URL or use the default URL.

**Comment by limichange** [comment]
If someone want to use it, can look at https://github.com/limichange/dine-strapi-provider-upload-aws-s3

**Comment by limichange** [comment]
🤔 if `strapi` members think this is unnecessary, can directly close this PR.

**Review by soupette — APPROVED** [review]
I have tested it and it's working well! 


LGTM

**Comment by limichange** [comment]
@alexandrebodin @Convly Need me to resolve conflicts?

**Comment by alexandrebodin** [comment]
Hello, 

I'm concerned that using the `providerOptions` to mix in custom options could create unintended `bugs` and conflicts with the AWS options in the future. wdyt ?

**Comment by v-dimitroff** [comment]
Obviously it is a needed feature as lots of us have came up with similar solutions. 

@alexandrebodin I had the same gut feeling that it might get messy as locally I've introduced also a `rootPath` option and list could easily go on with time.

Maybe one idea to make things slightly better could be to nest all custom options inside a single field key so we know all the rest of the params are only AWS config props?

``` 
config: {
    provider: 'aws-s3',
    providerOptions: {
      customOptions: {
         baseUrl: env('BASE_URL')
      }
      accessKeyId: env('AWS_ACCESS_KEY_ID'),
      secretAccessKey: env('AWS_ACCESS_SECRET'),
      ...
    }
}
```

There is most probably a better name for this field but you get the idea.

**Comment by alexandrebodin** [comment]
Thank you for the reactivity 👍 

Yes the conflict is something that I'm worried about considering it's a philosophy issue for other providers too :)

Something I would rather do is to go with a subkey for s3 instead and use a retro compatibility + deprecation

To move from 

```
{
    providerOptions: { 
      //.... 
    },
}
```

to

```
{
  providerOptions: {
       // all our custom options,
       s3Options: {}
  }
}
```
we could make this retro compatible for the time being and add a log to use the new format so we can remove it eventually

**Comment by v-dimitroff** [comment]
> 

I'll be happy to contribute if @limichange is not available.

**Comment by alexandrebodin** [comment]
I don't recall what the root path proposal was about can you remind me?

**Comment by v-dimitroff** [comment]
I have added it locally on my cloned copy of the provider but I can guess lots of people would have similar scenarios. 

Currently it is not possible to specify folders for your assets inside Strapi. Our CDN hosts other files besides the ones uploaded from Strapi and because of this I have dedicated a folder where all the Strapi files should go so we don't just flood the root level of the bucket with files. 

So a `rootPath` variable which could be empty by default and added as a prefix of the file's `Key` if holding any value did the job very well.

```
const fileKey = `${rootPath}${path}${file.hash}${file.ext}`

S3.upload(
{
  Key: fileKey,
  ...
 })
```

**Comment by lack-of-gravitas** [comment]
Is this ever going to be checked and merged?

**Comment by v-dimitroff** [comment]
> Is this ever going to be checked and merged?

Thank you for pinging the thread  @lack-of-gravitas .
I've opened a new PR with almost the same changes and including the details discussed above with @alexandrebodin - could you please review it and I'll be happy to address all comments so that we can start using this obviously needed functionality.

**Comment by alexandrebodin** [comment]
Awesome @v-dimitroff I'll close this PR in favor of yours and review it :) 

Closing for inactivity in favor of https://github.com/strapi/strapi/pull/13040

**Pull request closed without merging**
