### PR TITLE
Fix/mongoose ca

### PR DESCRIPTION
**Pull request by chris-makaio**
### What does it do?

allow to set mongoose's CA cert option

### Why is it needed?

some DBaaS won't accept connections without root CA

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @chris-makaio thank you for contributing to strapi ! 
Your PR contains commits already on the repo :) Can you update your branch so it only contains your commit ;)

**Comment by alexandrebodin** [comment]
Hi @chris-makaio any success update your PR ?

**Comment by chris-makaio** [comment]
sorry @alexandrebodin , which upstream branch should I use for the branch? It seems I took the wrong one (develop as far as I remember)

**Comment by alexandrebodin** [comment]
You can use master @chris-makaio :)

**Comment by chris-makaio** [comment]
@alexandrebodin looks pretty naked now :D

**Review by alexandrebodin — APPROVED** [review]
Will wait for the tests but LGTM 💯  
Would you be willing to also make a PR on our doc repo to add the option in this doc https://strapi.io/documentation/developer-docs/latest/concepts/configurations.html#database ?

**Comment by chris-makaio** [comment]
sure, is this fine?
https://github.com/strapi/documentation/pull/122

**Pull request merged**
