### PR TITLE
Stop populating component when populating relation to avoid infinitie…

### PR DESCRIPTION
**Pull request by alexandrebodin**
This pr reverts using a depth param to prevent over fetching data to just stopping component loading inside of components relations. This way we prevent infinite loops like in the issue https://github.com/strapi/strapi/issues/9224

Fix https://github.com/strapi/strapi/issues/9462

### CODE REVIEW

**Review by petersg83 — APPROVED** [review]
Works like a charm :)

**Comment by tbanys** [comment]
After this commit api started return this kind of data in relation fields:

```
         {
                  "__component": "links.link",
                  "_bsontype": "ObjectID",
                  "id": {
                      "type": "Buffer",
                      "data": [
                          95,
                          75,
                          105,
                          78,
                          64,
                          156,
                          240,
                          45,
                          206,
                          133,
                          68,
                          253
                      ]
                  }
              },
```

I'm using mongoDB

**Comment by alexandrebodin** [comment]
@tbanys can you share your model structure to reproduce & fix this asap ?

**Comment by shtelzerartem** [comment]
@alexandrebodin Here is what happening because of this bugfix #9451 . Population of relation field in components is must-have.

**Comment by tbanys** [comment]
@alexandrebodin 
```
{
  "kind": "singleType",
  "collectionName": "globals",
  "info": {
    "name": "Global",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "navbar": {
      "type": "component",
      "repeatable": false,
      "component": "layout.navbar"
    },
    "footer": {
      "type": "component",
      "repeatable": false,
      "component": "layout.footer"
    }
  }
}
```

```
{
  "collectionName": "components_layout_navbars",
  "info": {
    "name": "Navbar",
    "icon": "map-signs"
  },
  "options": {},
  "attributes": {
    "logo": {
      "model": "file",
      "via": "related",
      "allowedTypes": [
        "images"
      ],
      "plugin": "upload",
      "required": true
    },
    "menu": {
      "model": "menu"
    },
    "button": {
      "type": "component",
      "repeatable": false,
      "component": "links.button"
    }
  }
}
```

```
{
  "kind": "collectionType",
  "collectionName": "menus",
  "info": {
    "name": "menu"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "title": {
      "type": "string"
    },
    "links": {
      "type": "dynamiczone",
      "components": [
        "links.link",
        "menu.menu-dropdown"
      ]
    }
  }
}
```

```
{
  "collectionName": "components_links_links",
  "info": {
    "name": "Link",
    "icon": "link"
  },
  "options": {},
  "attributes": {
    "url": {
      "type": "string"
    },
    "newTab": {
      "type": "boolean",
      "default": false
    },
    "label": {
      "type": "string"
    }
  }
}
```

**Comment by alexandrebodin** [comment]
thanks @tbanys I'm investigating right now

**Comment by tbanys** [comment]
@alexandrebodin Hi, any news about this bug fix?

**Pull request merged**
