### PR TITLE
[v5] Run initialization on each new db pool connection; set postgres search_path for schemas

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

- moves the call to database dialect.initialize() into the knex pool.afterCreate
- Sets the postgres search_path used for schemas

### Why is it needed?

- our dialect.initialize() was called synchronously in the Database constructor but was running async code, so we were making our connection available without it necessarily being initialized
- our dialect.initialize() was only being called once on startup and not on each new connection in the pool
  - knex may open new pool connections, especially for raw queries, so in many cases the initalize was not happening before queries were run
- We keep accidentally writing queries that do not target the right schema. Setting search_path will keep us from having to remember anything anywhere, it will just work.

### How to test it?

Waiting for validation on these things:
- [ ] db packages should all still work properly despite the changes to every dialect
  - [x] Mysql
  - [ ] mysql2
  - [ ] sqlite3
  - [x] better-sqlite3
  - [x] postgres
- [ ] reproduce mysql/mysql2 opening a new connection in the pool and validate that `set session sql_require_primary_key = 0` has happened in the new connection
- [x] reproduce same as above with sqlite3/better-sqlite3 and `pragma foreign_keys = on`
- [x] postgres with a custom schema and deleted 'public' schema should still work
  - [x] DTS import/export should now work with it

TODO:

Add tests:
- [ ] test that user-supplied afterCreate still works correctly (esp. given that I want to [add it to the documentation](https://github.com/strapi/strapi/pull/17694#issuecomment-1750323869))
- [ ] test that it's called on each new connection that is opened

### Related issue(s)/PR(s)

Would have prevented https://github.com/strapi/strapi/issues/16836
Better alternative to https://github.com/strapi/strapi/pull/18042 (very localized fix)
Better alternative to https://github.com/strapi/strapi/pull/18029 (similar change at a higher level than this)

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
building experimental: https://github.com/strapi/strapi/actions/runs/6187265618

**Comment by derrickmehaffy** [comment]
Experimental Version: `0.0.0-experimental.98723a112314341c30a5f2b1fb46125eae3a6503`

**Comment by derrickmehaffy** [comment]
Testing with Better-SQLite3, MariaDB, and PostgreSQL (including transfer/import/export) still need to test MySQL/MySQL2 clients with normal MySQL and the legacy sqlite3 package.

**Comment by innerdvations** [comment]
Switching back to draft because I woke up this morning and realized saving the nativeConnection is actually a big mistake. I'll need to rework how that is done.

**Comment by derrickmehaffy** [comment]
> Switching back to draft because I woke up this morning and realized saving the nativeConnection is actually a big mistake. I'll need to rework how that is done.

Poke me on Slack or whatever when you are ready for more testing. We can do some peer testing too if you want.

**Comment by innerdvations** [comment]
Waiting for the TS DB migration to be finished, then I'll update this.

**Comment by innerdvations** [comment]
Back to draft while updating from the typescript conversion

**Comment by innerdvations** [comment]
This is hopefully out of sync with v5, closing and reopening a cleaner version.

**Pull request closed without merging**
