### PR TITLE
Replace babel-jest with @swc-node/jest to speedup frontend testing

### PR DESCRIPTION
**Pull request by Brooooooklyn**
## `babel-jest`

```
Test Suites: 168 passed, 168 total
Tests:       719 passed, 719 total
Snapshots:   8 passed, 8 total
Time:        65.408 s
Ran all test suites.
```

## `@swc-node/jest`

```
Test Suites: 168 passed, 168 total
Tests:       719 passed, 719 total
Snapshots:   8 passed, 8 total
Time:        37.314 s
Ran all test suites.
```

### CODE REVIEW

**Review by soupette — APPROVED** [review]
Wow it seems way faster!

Thanks a lot for your contribution/

LGTM

**Review by soupette — CHANGES_REQUESTED** [review]
However it prints some errors in the terminal about the coverage.
Can you check?

**Comment by Brooooooklyn** [comment]
> However it prints some errors in the terminal about the coverage.
> 
> Can you check?


Seems like I forgot to enable **dynamicImport** in config, I will fix it soon

**Comment by Brooooooklyn** [comment]
@soupette fixed

**Comment by Brooooooklyn** [comment]
@soupette

**Review by soupette — APPROVED** [review]
LGTM! Thanks for your contribution!

**Pull request merged**
