### PR TITLE
fix: hide doc status when no d&p

### PR DESCRIPTION
**Pull request by markkaylor**
### What does it do?

- [Backend] Return undefined locale if the CT doesn't have D&P
- [Backend] Update API tests 
- [Frontend] Hide the status for documents undefined locale
- [e2e] TODO: Looking into it in the related PR, but there is already a published product in the DB that isn't present in the CMS in the e2e test instance.

### Why is it needed?

Only d&p documents should have a status

### How to test it?

Make changes to documents with and without draft and publish
Check the statuses are correct for draft and published (draft, published, modified)
Check there is no status for no draft and published (empty grid cell)

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/pull/22407

### CODE REVIEW

**Comment by remidej** [comment]
Haven't test tested since it's a draft but LGTM so far :)

**Comment by markkaylor** [comment]
@remidej I'm close to fixing the issues with the e2e test, but if you agree I think we could review and merge this and wrap up the e2e test in a follow up to be sure this gets in before the release branch lock on Monday. We still get good coverage from the api test.

**Comment by remidej** [comment]
@markkaylor we're not affected by the release branch lock since this is a feature branch and will be a separate exp release. Happy to get it merged now if you want though, your call!

**Review by remidej — APPROVED** [review]
I just checked with @lucasboilly and we agree it would look nicer with a dash instead of the empty space. But we can merge like this first too!

**Comment by remidej** [comment]
I added the dash thingy
screenshot 2024-12-18 at 11 33 22@2x

**Review by Marc-Roig — APPROVED** [review]

**Review by simotae14 — APPROVED** [review]
lgtm

**Pull request merged**
