### PR TITLE
[DEITS] Misc - Cleanup / Fixes

### PR DESCRIPTION
**Pull request by Convly**
### Why is it needed?

- Fix light issues regarding streaming (file source provider)
- Remove console log from the engine
- Added decryption capabilities

### How to test it?

- yarn strapi export (with encryption & compression)
- Create a transfer engine with the local file source provider as a source & see the content being streamed (decompressed & decrypted)

### CODE REVIEW

**Review by innerdvations — APPROVED** [review]
LGTM

**Comment by Convly** [comment]
image
Oops, forgot to update the unit tests, will fix that quickly

**Comment by Convly** [comment]
Done :heavy_check_mark:

**Comment by innerdvations** [comment]
Oops, my bad too, I didn't run tests on this one. Checked now and it's all good except for the TS151001 warning in tests that I think we always get.

**Review by innerdvations — APPROVED** [review]

**Pull request merged**
