### PR TITLE
fix: typescript autogeneration on develop command

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

Adds the missing typescript build process with errors ignored to generate types before generating again with errors on.

### Why is it needed?

[ts autogeneration is broken ](https://github.com/strapi/strapi/issues/18738)

### How to test it?

In a typescript project, create a new content type in the content type builder -> it should now properly generate types and restart the server, unless there are legitimate typescript errors

### Related issue(s)/PR(s)

Fixes https://github.com/strapi/strapi/issues/18738

### CODE REVIEW

**Comment by innerdvations** [comment]
@joshuaellis  I'm not sure this is the "correct" way to fix this because I couldn't completely follow the flow of the worker process and when each step happens. If you can take a look and suggest a better place to put this, let me know and I'll update. Essentially, when a new content type is added we have to run a build with errors disabled because to generate the types we need a running Strapi... but Strapi won't build with incorrect types. So we ignore it, build, generate the types, then build again with errors on to catch legitimate errors.

**Review by Convly — COMMENTED** [review]
Instead of building twice at the same place, we could instead add back
- A build (`ignoreDiagnostics: true`) in the primary process
- A build (`ignoreDiagnostics: true`) on every process reload

This would permit creating the initial build to allow worker processes to generate the types without errors.

**Comment by joshuaellis** [comment]
> Instead of building twice at the same place, we could instead add back
> 
> * A build (`ignoreDiagnostics: true`) in the primary process
> * A build (`ignoreDiagnostics: true`) on every process reload
> 
> This would permit creating the initial build to allow worker processes to generate the types without errors.

I think this suggestion makes more sense yes :)

**Comment by innerdvations** [comment]
Closing this to add a very different solution targeted at the 4.15 fix branch

**Pull request closed without merging**
