### PR TITLE
Upgrade to latest alpha-12.x in migration guide

### PR DESCRIPTION
**Pull request by Duske**
My PR is a:

💅 Enhancement

Main update on the:

Documentation

Since there are some issues with the release alpha.12 concerning the webpack build process, we should advise the user to upgrade to the latest alpha.12.x

### CODE REVIEW

**Comment by lauriejim** [comment]
Can you update to `3.0.0-alpha.12.1.3` can it's more stable than `3.0.0-alpha.12.1` please.

**Comment by Duske** [comment]
Is it still correct that  `strapi-mongoose` has version `3.0.0-alpha.12` in `package.json`?

**Comment by lauriejim** [comment]
@Duske I think you make a mistake by replacing by `3.0.0-alpha.12.3` instead of `3.0.0-alpha.12.1.3`.

**Comment by Duske** [comment]
You're absolutely right, sorry!

**Pull request merged**
