### PR TITLE
Default datetime to null

### LINKED ISSUE #2300: Bookshelf Date field autofills with current date
**Informations**
- **Node.js version**: v10
- **npm version**: v6
- **Strapi version**: 14.5
- **Database**: MySQL (MariaDB 10.2)
- **Operating system**: Linux Mint 19 (Ubuntu 18.04)

**What is the current behavior?**

When using bookshelf with MySQL if you leave a date field empty it will auto-fill with the current date.

**Steps to reproduce the problem**

Create a model with a date field, create an entry and leave the date field empty. The database will auto-fill the date field with the current date/time

**What is the expected behavior?**

Date should remain empty until provided a value

**Suggested solutions**

Modify the creation script to default to null, only created_at and updated_at should auto-fill and updated_at should update when a PUT request is made.

### PR DESCRIPTION
**Pull request by websocket98765**
## Description of what you did:

Fixes #2300 

Updates bookshelf to default datetime related fields to NULL, not to current time.

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [x] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by websocket98765** [comment]
@alexandrebodin How would you suggest implementing that? 

I see: https://github.com/strapi/strapi/blob/0f1141c47795eb7317295c8d8db88a9ed1ad3221/packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js#L283-L291 We could update this to `timestampUpdate`, because it only sets a dafault value currently. But that may be messy long term because my understanding is that `timestampUpdate` is supposed to have an autoupdated value (although it's not possible in Postgres without a trigger).

Is `updated_at` set somewhere from the client? If so, could we do the same with `created_at` on creation?

**Comment by derrickmehaffy** [comment]
Probably best not to modify those default timestamps, using just a datetime field would be best.

@websocket98765 those timestamp fields are used for the automated created_at / updated_at fields

**Comment by alexandrebodin** [comment]
@websocket98765 Are you willing to update your ? 
If you could just leave the timestamp case as is and put your new logic like:

```js
    case 'date':
    case 'time':
    case 'datetime': {
      if (client === 'pg') {
        return 'timestamp with time zone DEFAULT NULL';
      } else if (client === 'sqlite3' && tableExists) {
        return 'timestamp DEFAULT NULL';
      }
      return 'timestamp DEFAULT NULL';
   }
    case 'timestamp':
      if (client === 'pg') {
        return 'timestamp with time zone';
      } else if (client === 'sqlite3' && tableExists) {
        return 'timestamp DEFAULT NULL';
      }
      return 'timestamp DEFAULT CURRENT_TIMESTAMP';
```

**Comment by websocket98765** [comment]
@alexandrebodin I think it's better if someone else finishes this out. The PR is open and any Strapi committers can commit to the `default-datetime-null` branch to update this PR. I don't understand off hand how to implement what you're suggesting and unfortunately don't have time to fully dig into Strapi for more complex changes at this time.

**Comment by alexandrebodin** [comment]
Closing this PR then and will open a new one

**Pull request closed without merging**
