### PR TITLE
refactor(helper-plugin): migrated `awaitToJs.js` to typescript

### PR DESCRIPTION
**Pull request by fletch-r**
Migrated the `awaitToJs` utils file to TypeScript

Relates to #17690

### CODE REVIEW

**Comment by yurimutti** [comment]
Pull requests must be based off of and target https://github.com/strapi/strapi/tree/chore/ts-migrate-helper-plugin

**Comment by gu-stav** [comment]
I just checked and it seems this util is unused. Should we delete it instead? :)

**Comment by joshuaellis** [comment]
> I just checked and it seems this util is unused. Should we delete it instead? :)

No it's a public API, however it should be marked as `deprecated` with a clear guide what to replace it with – @markkaylor could advise here 👍🏼

**Comment by markkaylor** [comment]
Yes agree I don't think we can delete anything right now in the helper-plugin since we expose it to plugin developers.  

We can deprecate with JSDoc @deprecated. For this case I think try / catch and async await could be used directly and we can warn this will eventually be removed. I'm actually wondering now though should we migrating function we want to deprecate to TypeScript or just marking them as such? What do you think @joshuaellis ?

**Comment by joshuaellis** [comment]
> Yes agree I don't think we can delete anything right now in the helper-plugin since we expose it to plugin developers.
> 
> We can deprecate with JSDoc @deprecated. For this case I think try / catch and async await could be used directly and we can warn this will eventually be removed. I'm actually wondering now though should we be migrating functions we want to deprecate to TypeScript or just marking them as such? What do you think @joshuaellis ?

I'd migrate them still because you'll get weird TS issues when we migrate other sections of the monorepo if the types are not complete :)

**Pull request closed without merging**
