### PR TITLE
Add Strapi edition to the admin footer

### PR DESCRIPTION
**Pull request by remi2j**
Signed-off-by: Rémi de Juvigny <remi@hey.com>

#### Description of what you did:

I changed the text on the bottom of the admin sidebar. The goal was to let the user know whether he's using community edition or enteprise edition.

It looks like this:

Screenshot 2020-09-02 at 17 01 08

### CODE REVIEW

**Comment by soupette** [comment]
@maevalienard can you check that the design is ok?

**Comment by maevalienard** [comment]
@remi2j @soupette Would you mind adding a "—" between the version and the name of the plan please? :)

**Comment by remi2j** [comment]
@maevalienard after all this talk I managed to forget something 🙃

Here is an updated screenshot:

Screenshot 2020-09-02 at 18 00 31

I made the dash symbol part of the link. Otherwise it was the only white character of the line, which made it stand out in a weird way. Let me know if that's okay

**Comment by maevalienard** [comment]
LGTM thank you Rémi!

**Review by soupette — APPROVED** [review]
LGTM

**Pull request merged**
