### PR TITLE
Load storage providers before server start

### PR DESCRIPTION
**Pull request by vincentbpro**
### What does it do?

Makes changes in the upload plugin to load storage providers before server start (moves the loading from `bootstrap.js` to `register.js`) allowing the providers to edit some server configutation before they are applied.

### Why is it needed?

It will allow configuring the security middleware prograamatically when loading a provider instead of having to manually edit the `middlewares.js` config file.

Example of manual middleware configuration:

image

### CODE REVIEW

**Review by alexandrebodin — COMMENTED** [review]
Except for the conflicts that looks alright 👍 . 

Have you been able to valide that allows adding a domain to the CSP "cleanly"? 
Also it would be great to add some tests in the PR too

**Comment by vincentbpro** [comment]
@alexandrebodin yes it works fine! I was surprised how easy it was in the end

Working on the tests :)

**Comment by derrickmehaffy** [comment]
> Except for the conflicts that looks alright +1 .
> 
> Have you been able to valide that allows adding a domain to the CSP "cleanly"? Also it would be great to add some tests in the PR too

hold up, we will be able to dynamically update the csp config for providers now :thinking:

**Comment by vincentbpro** [comment]
Exactly @derrickmehaffy, it allows apply config with `global.strapi.config.set()` in the providers `init()` functions.

**Review by alexandrebodin — APPROVED** [review]
LGTM. This will enable a much simpler user xp with providers soon. 

We should document it somewhere and update the providers to use this method. @derrickmehaffy @pwizla can we still merge this now?

**Comment by vincentbpro** [comment]
FIY for the moment it doesn't change anything for the users, first the providers packages need to be updated to benefit from this.

**Pull request merged**
