### PR TITLE
Register logger middleware before errors middleware

### PR DESCRIPTION
**Pull request by goodhoko**
In the examples and project templates the "errors" middleware which turn thrown errors into HTTP responses is registered before the "logger" middleware. This causes any errors thrown in controllers to pierce through the logger middleware resulting in these requests not being logged.

Eg. when a controller throws a ValidationError the resulting HTTP 400 request is not logged at all.

Change the order of middleware registration so that the logger is 'above' the errors middleware and has a chance to log *all* requests.

The caveat to consider is that with this new order, when the "logger" middleware itself throws, the error won't be handled by the `errors` middleware so the resulting HTTP response may not adhere to the standard otherwise expected.

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hi @goodhoko good idea to change the order. We migrate the code to typescript recently so there is a conflict would you be willing to update your PR ?

**Comment by goodhoko** [comment]
@alexandrebodin GitHub wasn't reporting any conflicts but I rebased on `main` anyway. Is it good to go?

**Comment by goodhoko** [comment]
Hmmm it seems the failed CI is just some flaky test. Can we rerun it?

**Comment by derrickmehaffy** [comment]
FYI we will need a small migration guide for this in the docs

**Comment by derrickmehaffy** [comment]
> Hmmm it seems the failed CI is just some flaky test. Can we rerun it?

I don't think that one is you

**Comment by goodhoko** [comment]
ok, is any of this actionable from my side?

**Comment by derrickmehaffy** [comment]
@Boegie19 here is the PR I was talking about

**Review by derrickmehaffy — APPROVED** [review]
Tested and LGTM

**Comment by Boegie19** [comment]
This pr will also fix https://github.com/strapi/strapi/issues/13327

**Pull request merged**
