### PR TITLE
Admin: Allow reducers to be injected async into the store

### PR DESCRIPTION
**Pull request by gu-stav**
### What does it do?

Registers a new method `injectReducer()` on the redux-store which allows us to dynamically inject reducers.

### Why is it needed?

Review Workflows will use redux as state management. Currently it is impossible to extend the core-store without writing our own strapi-plugin and [extending reducers in the bootstrap phase](https://docs.strapi.io/developer-docs/latest/developer-resources/plugin-api-reference/admin-panel.html#reducers-api).

This allows us to extend the store for individual views (such as any EE view) and follows a recommended pattern for code splitting from the redux documentation: https://redux.js.org/usage/code-splitting

```js
import { useEffect } from 'react';
import reducer from './reducer';

export function Component() {
  useEffect(() => {
    store.injectReducer('NS', reducer);
  }, [])

  return null;
}
```

### CODE REVIEW

**Comment by joshuaellis** [comment]
I think this raises an important – this isn't really how Redux suggests we code-split and it could be a good chance to deprecate the current way we do it `app.addReducer` and instead expose a hook for people to use (be more react-y). This would then drive plugin developers to the new direction 😄

**Comment by gu-stav** [comment]
@joshuaellis I like the idea of the hook a lot. We could start by making this a local hook in strapi/admin and start using it internally. I'll add this to the tech tasks for review workflows as soon as this PR is approved.

**Review by joshuaellis — APPROVED** [review]
Worth opening a new ticket to address our own stuff?

**Comment by gu-stav** [comment]
@joshuaellis Do you refer to the new hook?

**Review by ronronscelestes — APPROVED** [review]
works for me!

**Comment by joshuaellis** [comment]
> @joshuaellis Do you refer to the new hook? 

That but more are we adding reducers in plugins elsewhere? For example.

**Comment by gu-stav** [comment]
@joshuaellis I see. I'll add a follow-up in Jira 👍🏼

**Pull request merged**
