### PR TITLE
[V4]Add the hover pointer in all necessary tables

### PR DESCRIPTION
**Pull request by matteo6b**
Hello ,

I have fixed the problem that the pointer had in this [issue](https://github.com/strapi/strapi/issues/11167) in the tables with what I have uploaded in this PR and in the Strapi/parts [repository](https://github.com/strapi/parts/pull/382) I have fixed ToggleCheckbox  

I have created a styleComponent with the function that it has the Hover Pointer and called it <TrHover
in all the views that the old version had

example Code 

`  const TrHover = styled(Tr)`
    &:hover {
      cursor: pointer;
    }
  `;`

### Related issue(s)/PR(s)
https://github.com/strapi/strapi/issues/11167

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@mbistuer can you please sign the CLA so I can ask the frontend team for a review?

**Comment by mfrachet** [comment]
Hello 👋🏻 . I'm not very sure this should take place in strapi core, but more in https://github.com/strapi/parts. Also, this is still in alpha and we're working hard on improving and iterating on this 😊 . We'll try to make something reasonable for the stable with the code you provided 🙏🏻 

Have a good one 👋🏻

**Comment by derrickmehaffy** [comment]
> Hello 👋🏻 . I'm not very sure this should take place in strapi core, but more in https://github.com/strapi/parts. Also, this is still in alpha and we're working hard on improving and iterating on this blush . We'll try to make something reasonable for the stable with the code you provided 🙏🏻
> 
> Have a good one 👋🏻

@mfrachet Do you want to keep this PR open or is the team gonna handle it elsewhere?

**Comment by mfrachet** [comment]
@derrickmehaffy We'll tackle this in the UI lib :)

**Pull request closed without merging**
