### PR TITLE
Update migration guide for beta 17.5

### PR DESCRIPTION
**Pull request by websocket98765**
#### Description of what you did:

The existing guide wasn't up to date enough to successfully install beta 17.5.

- Adds`strapi-helper-plugin` which is required
- Removes the graphql plugin, which causes an error (like "expected number received M") when trying to run `npm run develop` if otherwise not using graphql in the project.
- Adds `npm run develop` command.

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [x] Documentation
- [ ] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [x] SQLite

### CODE REVIEW

**Comment by websocket98765** [comment]
@alexandrebodin Updated to remove helper plugin.

**Comment by websocket98765** [comment]
@alexandrebodin it's correct to exclude `strapi-plugin-graphql` too right?

**Comment by derrickmehaffy** [comment]
It's an optional plugin maybe a special note for it? (The same applies for documentation and any providers)

**Comment by websocket98765** [comment]
@alexandrebodin Turns out `strapi-helper-plugin` does not need to be listed in package.json if running `strapi develop`, but _does_ need to be in package.json when using `strapi develop --watch-admin`, otherwise this error occurs (wait for it, it'll look like it started successfully, but will throw this error after a short wait):
strapi helper error

When testing both, I ran:
```
rm -rf .cache build
npm run build
<the start command>
```

For now I think it's better to list `strapi-helper-plugin` in package.json so `--watch-admin` works.

**Comment by alexandrebodin** [comment]
@websocket98765 That's an issue to fix not sth to be added to the package.json file. It shouldn't be required or at least we should document it if it is. Need @soupette insight on this.

**Comment by soupette** [comment]
@websocket98765 I have tried to reproduce your issue and I am unable, I am pretty sure that the `strapi-helper-plugin` doesn't need to appear in your project's dependencies. Maybe you should try to remove your `package-lock.json` or your `yarn.lock` to get it working.

**Comment by websocket98765** [comment]
I've removed strapi-helper-plugin from PR. Should be ready to merge.

**Comment by alexandrebodin** [comment]
I'm closing this PR as it doesn't add new steps to the previous migration guide.

Feel free to open a new PR if necessary.

**Comment by websocket98765** [comment]
I'm confused why it's closed, it would seem valuable to have a migration guide for the current 17.5 version of Strapi (instead of 17.4). But, I spent enough time on it. You guys can update it if desired.

**Comment by derrickmehaffy** [comment]
Because it's not worth updating that single migration guide every time there is a new patch, migration guides are only tweaked and added when something needs to be done, after that the user can update to the latest. It would just be a pain to have to keep changing version numbers in all the "places"

**Comment by websocket98765** [comment]
@derrickmehaffy Intentionally leaving docs outdated helps nobody, especially when a PR already exists. If they don't want to merge it to say 17.5, that's fine, but they should consider creating a commit to remove the graphQL plugin so it doesn't cause an error and add the npm run develop command for NPM users.

**Comment by derrickmehaffy** [comment]
It's not intentionally not updating @websocket98765 it is explained how to update: https://strapi.io/documentation/3.0.0-beta.x/guides/update-version.html#upgrading-your-dependencies

going through every single time a version changes and updating an older migration guide is just busy work. The major change happened in beta.17.4 so that is why it was used in the migration guide.

**Pull request closed without merging**
