### PR TITLE
Fix graphql nested groups returning null

### LINKED ISSUE #4326: Graphql: Nested objects returns null
**Describe the bug**
Fetching for nested objects returns null in response

**Expected behavior**
Should return the respective data in the response

**Screenshots**
Screenshot 2019-10-22 at 9 52 43 PM

**System**
- Node.js version: v10.16.3
- NPM version:
- Strapi version: 3.17.3
- Database: Postgres
- Operating system: MacOS

### PR DESCRIPTION
**Pull request by alexandrebodin**
#### Description of what you did:
Fix #4326

#### My PR is a:

- [ ] 💥 Breaking change
- [X] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [X] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by anmolmahatpurkar** [comment]
Is this released? Can we follow a nightly release cycle for such important fixes? This is a real blocker for me, and it's already a week since its fixed.

**Comment by derrickmehaffy** [comment]
@anmolmahatpurkar 
image

**Comment by anmolmahatpurkar** [comment]
@derrickmehaffy I think a release is not out yet though.

**Comment by derrickmehaffy** [comment]
Nope not yet, you can see that on the releases tab :wink: https://github.com/strapi/strapi/releases/latest

**Comment by anmolmahatpurkar** [comment]
When is this expected to release?

**Comment by derrickmehaffy** [comment]
No ETA yet, I suspect probably sometime this week but that is just a guess.

**Comment by sprashivaesh** [comment]
Doesn’t work if the nesting is more than one element.

**Comment by sprashivaesh** [comment]
In file 
_packages/strapi-hook-bookshelf/lib/mount-models.js_
` else if (_.isEmpty(options.withRelated)) {
            options.withRelated = createGroupsPopulate();}`
change
`else if (_.isEmpty(options.withRelated)) {
            options.withRelated = []
              .concat(createGroupsPopulate())
              .concat(createAssociationPopulate());
          }`

**Comment by mdacosta** [comment]
I confirm that it still doesn't work.
And it doesn't seem to work with the fix suggested by @sprashivaesh either... 🤷‍♂

**Comment by alexandrebodin** [comment]
@mdacosta Can you please open a detailed issue with your models and queries so we can check that out. Thanks !

**Pull request merged**
