### PR TITLE
Fix strapi new for Windows

### LINKED ISSUE #1939: Mongoose Hook connectivity fails on project creation on Windows
**Informations**
- **Node.js version**: 8.12.0/9.11.2
- **npm version**: 6.4.1/5.6.0
- **Strapi version**: alpha14
- **Database**: Mongo
- **Operating system**: Windows 10

**What is the current behavior?**

`Strapi new` connection test fails when creating a mongodb project. The CLI also reports it as a success.

**Steps to reproduce the problem**

Since `strapi new` is currently broken in node 9 on windows, use the CLI to init a project
```
PS C:\newsync\Projects\RestaurantApp\app> strapi new server --dbclient=mongo --dbhost=lcalhost --dbport=27017 --dbname="mydb" --dbusername="" --dbpassword=""
🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️

Lets configurate the connection to your database:
Database determined by CLI args: mongo

⏳ Testing database connection...
{ <strong>Error: Cannot find module 'C:\Users\Nick\AppData\Local\Temp\strapifd3e9ff2ccd8\node_modules\mongoose'</strong>
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\Users\Nick\AppData\Local\Temp\strapifd3e9ff2ccd8\node_modules\strapi-hook-mongoose\lib\utils\connectivity.js:8:20)
    at Promise.all.then (C:\Users\Nick\AppData\Roaming\npm\node_modules\strapi\node_modules\strapi-generate-new\lib\before.js:259:126)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7) code: 'MODULE_NOT_FOUND' }
<strong>The app has been connected to the database successfully!</strong>

🏗  Application generation:
√ Copy dashboard
√ Install plugin settings-manager.
√ Install plugin content-type-builder.
√ Install plugin content-manager.
√ Install plugin users-permissions.
√ Install plugin email.
√ Install plugin upload.
√ Link strapi dependency to the project.

👌 Your new application server is ready at C:\newsync\Projects\RestaurantApp\app\server.

⚡️ Change directory:
$ cd server

⚡️ Start application:
$ strapi start
```

First we have the path that is executed
image

In connectivity.js
image

But the structure is
<pre>
${tempPath}/node_modules/
    strapi-hook-mongoose/
       lib/
       package.json
       ...some other stuff
       node_modules/
           ...a bunch of modules... including
           <strong>mongoose/</strong>
</pre>

**What is the expected behavior?**

1. Mongoose is imported correctly and the project is created correctly.
2. When something errors, the success callback shouldn't be called...

**Suggested solutions**

Why do we even need to do some hacky path building to require mongoose? part of the whole point of require is that it's relative to the module. Just `require('mongoose')` should be fine right?

### LINKED ISSUE #1940: Build scripts fail on windows
**Informations**
- **Node.js version**: 9.11.2
- **npm version**: 5.6.0
- **Strapi version**: Master branch
- **Database**: n/a
- **Operating system**: Windows 10

**What is the current behavior?**

any commands that run the clean or clean:all scripts fail on windows because they run "rm"

**Steps to reproduce the problem**

run `npm clean` on windows

**What is the expected behavior?**

clean script completes correctly

**Suggested solutions**

Switch to a cross-platform npm module like rimraf.

### PR DESCRIPTION
**Pull request by NickBolles**
My PR is a:

🐛 Bug fix

Main update on the:

Plugin

Fixes `Strapi new` database connection check.
Also make multiple platform dependent `rm` commands use rimraf instead

Fix #1939  and fix #1940

### CODE REVIEW

**Comment by lauriejim** [comment]
Thank you for this PR, will review it soon as possible.

**Comment by danielehrhardt** [comment]
rimraf is a nice tool. It is working fine on my Windows and Mac Machine.

**Comment by lauriejim** [comment]
Got this error when I try to clone the repo and run `npm run setup:build`.
I'm on linux machine to test it.

```
> @3.0.0-alpha.14.1.1 setup:build /home/ubuntu/strapi
> npm run setup --build


> @3.0.0-alpha.14.1.1 setup /home/ubuntu/strapi
> npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean


> @3.0.0-alpha.14.1.1 clean:all /home/ubuntu/strapi
> npm run removesymlinkdependencies && rimraf package-lock.json && rimraf packages/*/package-lock.json && rimraf packages/*/node_modules


> @3.0.0-alpha.14.1.1 removesymlinkdependencies /home/ubuntu/strapi
> node ./scripts/removeSymlinkDependencies.js

sh: 1: rimraf: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @3.0.0-alpha.14.1.1 clean:all: `npm run removesymlinkdependencies && rimraf package-lock.json && rimraf packages/*/package-lock.json && rimraf packages/*/node_modules`
npm ERR! spawn ENOENT
```

**Comment by danielehrhardt** [comment]
I think we should change rimraf to npx rimraf

**Comment by NickBolles** [comment]
@lauriejim why in the world does the script run npm clean before the initial npm install?

Well yes that can be fixed by using npx rimraf in the scripts. I'll update later today

**Comment by NickBolles** [comment]
@lauriejim I think that last commit should fix that issue. Let me know if you come across any others, especially on non-windows platforms.

**Comment by NickBolles** [comment]
Actually I get errors way down the line in setup:build in strapi-admin build,
image

https://github.com/strapi/strapi/blob/master/packages/strapi-admin/package.json

I'm trying to figure out why these scripts reference the binaries directly. And why `APP_PATH=$APP_PATH` is used several times. Is this because this can be copied to the generated strapi server? Doesn't it do an npm install of the dependencies (react-ga, remove-markdown etc.) when it does this?

I guess I don't see any problem with requiring those packages and using them directly, especially if we fix the env vars used in these scripts.

**Comment by lauriejim** [comment]
It works on linux 👍 I will try tomorrow on my Mac.
So the dep in package.json is no longer require, you can remove it.

**Pull request merged**
