### PR TITLE
Added oneWay relation option on frontend

### PR DESCRIPTION
**Pull request by okaris**
### 💅 Enhancement
Main update on the: Plugin

This PR provides frontend support for #379 fixed in #426

### CODE REVIEW

**Comment by lauriejim** [comment]
Hi @okaris, we add `WIP` status label, so let us know when we can review your PR.

**Comment by derrickmehaffy** [comment]
@lauriejim correct me if I'm wrong but bookshelf in the backend doesn't have the oneway relationship right?

**Comment by Aurelsicoko** [comment]
@okaris Can you make a screenshot of the front-end?

**Comment by okaris** [comment]
image
This is what it looks like in the end @Aurelsicoko

**Comment by okaris** [comment]
Although I faced a problem. Creating a oneWay relations appends to the target models settings.json. The relationship I created in the above screenshot caused this: 
image

**Comment by okaris** [comment]
I am also on Slack as @okaris btw

**Comment by okaris** [comment]
@lauriejim My work here seems to be done. The PR is ready to be reviewed. Thanks

**Comment by Aurelsicoko** [comment]
@okaris Can you add 2px padding between boxes? I really like the icon, well done 👍

**Comment by okaris** [comment]
@Aurelsicoko thanks and done. 
image

**Comment by lauriejim** [comment]
@okaris Thank you ! That is awesome. We have to make some test on it before merging, just to be sure it's all OK. 
Will try to test it soon as we can. Lot of work actually.

> I'm so exiting to see one-way in content-type-builder !

**Pull request merged**
