### PR TITLE
Average and sum aggregators for Query Engine API

### PR DESCRIPTION
**Pull request by WalkingPizza**
### What does it do?

Adds the `avg` and `sum` functions to the Query Engine API.

### Why is it needed?

Just like the `count` aggregator, it is sometimes useful to retrieve sums and/or averages from the database directly instead of fetching entries and executing operations over them manually.

### How to test it?

1. Create a `Test` content type, with a numeric field called `value`;
2. Create a random amount of entries of type `Test`;
3. Run `strapi.db.query('api::data.data').sum("value");` and notice how it returns the sum of those values;
4. Run `strapi.db.query('api::data.data').avg("value");` and notice how it returns the average of those values.

### CODE REVIEW

**Comment by WalkingPizza** [comment]
More than happy to write some documentation and submit a PR if this gets accepted.

**Comment by WalkingPizza** [comment]
@alexandrebodin did you have a chance to look at this? 👀

**Comment by alexandrebodin** [comment]
Hey @WalkingPizza Thank you for adding those. 

We implemented the count as a root-level function because it's so common but the idea for more general aggregations would be to expose sth similar to the below example so we can support a custom mix of filters / groupBy etc and make multiple aggregates at once.

```js

strapi.db.query.aggregate(
  aggs: {
    avg: {
      'field': true
    },
    sum: {
      'otherField': true
    }
  }
)
```

This is far from a final version that would go through RFC but that's a snippet of the idea.

**Comment by alexandrebodin** [comment]
As mentioned previously, we don't intend to expose aggregations one by one for now and we are not planning on working on this for the time being. I'll close the PR for now and hopefully we can use some of it's logic for future plans.

Thank you for contributing so much @WalkingPizza 🎉

**Comment by jerodfritz** [comment]
Thank you for taking a first step towards this @WalkingPizza.   I have a similar use-case now that desperately needs this functionality.  Iterating over the result sets to perfom these calculations is just not feasible as the dataset grows.  I'd be willing to sponsor your contribution.  Do you think you could adapt the aggregates to how @alexandrebodin sees this fitting into the bigger picture?

**Pull request closed without merging**
