### PR TITLE
Fix decimal on content manager's inputs

### PR DESCRIPTION
**Pull request by HichamELBSI**
Signed-off-by: HichamELBSI <elabbassih@gmail.com>

#### Description of what you did:
fixes https://github.com/strapi/strapi/issues/7401

### CODE REVIEW

**Comment by psycoder17** [comment]
I actually tried that solution late last night when I was having my issue, and that did not solve it for me. If I'm not mistaken, that var only controls the up and down arrows on the text field. So it was incrementing the number correctly, but I could not save the record due to some sort of validation telling me I needed to round to the nearest .1 still.

**Comment by HichamELBSI** [comment]
Hello @psycoder17, I just try this one on Firefox and it works well for me. What version of Firefox do you have?

**Review by soupette — APPROVED** [review]
LGTM

**Review by soupette — APPROVED** [review]
LGTM

**Pull request merged**
