### PR TITLE
improve russian translations

### PR DESCRIPTION
**Pull request by Ashot-KR**
Improves some russian translations for admin UI:
fix some wrong translations
make some translations more "native"
add absent translations

### CODE REVIEW

**Review by reslear — DISMISSED** [review]

**Comment by alexandrebodin** [comment]
Hi @Ashot-KR Would you mind fixing the conflicts ;)

**Comment by Ashot-KR** [comment]
@alexandrebodin sure, i'll do it later today

**Comment by reslear** [comment]
@Ashot-KR @alexandrebodin also look please another Russian language problem #7098 (Russian cyrillic ERROR on save - Content Type) Russian users really need. thx!

**Comment by Ashot-KR** [comment]
@reslear i got this error once 😄  actually pluralization in Russian not very easy thing. I will take a look and probably suggest some potential solutions

**Comment by Ashot-KR** [comment]
@alexandrebodin conflict resolved

**Review by reslear — APPROVED** [review]

**Review by soupette — APPROVED** [review]
LGTM

**Pull request merged**
