### PR TITLE
Add Vietnamese translation

### PR DESCRIPTION
**Pull request by olragon**
#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [x] Admin
- [ ] Documentation
- [ ] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello! Thank you for this pull request!
Can you also add plugins translations, please.
To be completed on the Vietnamese language.
Thank you for your time!

**Comment by olragon** [comment]
@lauriejim can you review?

**Comment by lauriejim** [comment]
Hello @olragon , how did you test your translations in the Admin UI?

**Comment by olragon** [comment]
Hi @lauriejim , I includes commit used to adjust language switcher to test translations in the Admin UI.

**Comment by olragon** [comment]
@lauriejim any tasks remain?

**Comment by lauriejim** [comment]
Thank you for adding this new language to Strapi!

**Pull request merged**
