### PR TITLE
Init tech docs

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Init a doc project in the repo for technical doc for contributors

### Why is it needed?

We have a lot of doc lying around and most are not public at the moment. Making this more open and put it in one place will improve onboarding and hopefully help contributors 🎉 

### How to test it?

checkout the branch and go to the docs folder and follow the README instructions

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by gu-stav** [comment]
Thank you for starting the work on that 🚀 

In my experience documentation stays more up-to-date if the files are co-located to the code (similar to tests), so that when a developer edits something somewhere, it is easier to understand: 1) there is documentation for that part of the code they are working on 2) this documentation might need an update.

What I'd propose instead therefore would be to sprinkle these doch files all over the repository and to collect / watch them once somebody works on the documentation. What do you think about that?

**Comment by alexandrebodin** [comment]
> Thank you for starting the work on that 🚀
> 
> In my experience documentation stays more up-to-date if the files are co-located to the code (similar to tests), so that when a developer edits something somewhere, it is easier to understand: 1) there is documentation for that part of the code they are working on 2) this documentation might need an update.
> 
> What I'd propose instead therefore would be to sprinkle these doch files all over the repository and to collect / watch them once somebody works on the documentation. What do you think about that?

Good thoughts thanks for sharing. I'm genuinely curious if you have some examples in mind of projects doing that? 

Right now I'm worried it would make the repo harder to navigate and make contributions to the doc/understanding the structure a lot harder. I feel like it would actually make the doc less maintainable over time as the risk of duplicating Information and having structural problems would be higher, even more with the team growing.  Would be interesting to get @pwizla's input on that? :) 

For now, we will start with high-level docs that will fit better at the root. If we need to document more low-level parts of the code as you say I would probably put that as part of the codebase and not a global doc 🤔 It will probably be a case by case basis. Some other options also could be to add links in the jsdoc in the code to the corresponding doc file so dev will see those in the code itself for example. 

Let's explore when we face this situation in real life to see what makes more sense 👍

**Comment by pwizla** [comment]
Thanks for bringing this to my attention. I'm curious about the context and the need behind this 👀 
* Who's the target? Is it mostly in-house contributors (a.k.a. Strapiers)? Is it also for external contributors?
* What kind of content would be hosted here?
   > a lot of doc lying around and most are not public at the moment. 
  Could this content be included in Strapi developer docs?

**Comment by alexandrebodin** [comment]
> Thanks for bringing this to my attention. I'm curious about the context and the need behind this 👀
> 
> * Who's the target? Is it mostly in-house contributors (a.k.a. Strapiers)? Is it also for external contributors?
> This is targeted at code contributors internal or external
> * What kind of content would be hosted here?
> Very technical docs (architecture diagram, sequence diagrams, db schemas, low level API specs...)
>   > a lot of doc lying around and most are not public at the moment.
>   
>   
>   Could this content be included in Strapi developer docs?
> I don't think we should mix those as it's not targeted as Strapi users and could create confusion. However some docs might be interesting to reuse to explain some concept (thinking about some diagrams mostly) :)

**Comment by derrickmehaffy** [comment]
FYI, nice part of Docusaurus is they have things like this which let you directly imbed files/lines/gists straight into the doc: https://github.com/saucelabs/docusaurus-theme-github-codeblock

**Review by Convly — COMMENTED** [review]
Hey, thanks for creating this PR. I don't have much to say that hasn't been already shared. I think it's a good idea to have this kind of documentation living next to the code for contributors.

**Review by gu-stav — APPROVED** [review]
Let's give it a try :)

**Pull request merged**
