### PR TITLE
Don't parse npm scripts for dynamic config

### LINKED ISSUE #916: Server fails to start when package.json contains shell parameter expansions
**Information**

- **Node.js version**: 9.6.1
- **npm version**: 5.8.0
- **Strapi version**: 3.0.0-alpha.11.3
- **Database**: MongoDB
- **Operating system**: MacOS

**What is the current behavior?**

Strapi server fails to start when package.json contains shell parameter syntax, e.g. a script containing `FOO=${BAZ:-foo}`.

Shell parameters could normally be used with npm but Strapi interprets them as JS and throws a syntax error.

```shell
[2018-04-09T05:42:07.122Z] debug Server wasn't able to start properly.
SyntaxError: Missing } in template expression
    at Object.keys.reduce (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:379:38)
    at Array.reduce (<anonymous>)
    at templateConfigurations (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:375:27)
    at Object.keys.reduce (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:377:18)
    at Array.reduce (<anonymous>)
    at templateConfigurations (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:375:27)
    at Object.keys.reduce (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:377:18)
    at Array.reduce (<anonymous>)
    at templateConfigurations (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:375:27)
    at Strapi.module.exports.app (/private/tmp/test/node_modules/strapi/lib/core/configurations.js:94:19)
    at Strapi.load (/private/tmp/test/node_modules/strapi/lib/Strapi.js:197:29)
    at <anonymous>
```

**Steps to reproduce the problem**

1. `> strapi new test` (accept defaults)
1. add the conflicting code to `scripts` in package.json:
`"test": "FOO=${BAZ:-foo} sh -c 'echo $FOO'"`
1. NPM runs the script normally
`> export BAZ=bar`
`> npm test`
`bar`
1. Start Strapi
`> npm start`
`SyntaxError: Missing } in template expression`

**What is the expected behavior?**

Server starts normally.

**Suggested solutions**

Template literals in configuration are ignored if they contain `()` characters indicating a function call.

https://github.com/strapi/strapi/blob/648bf52a3c69b50df14fe69e1625029ab31f093e/packages/strapi/lib/core/configurations.js#L371-L374

They could also be ignored if they contain shell parameter expansion characters: `: = - ` etc. [(Bash docs)](http://wiki.bash-hackers.org/syntax/pe#overview).

I don't think these shell characters would appear when using dynamic configuration as intended.

**Workaround**

Insert an inline comment containg a bracket `` `#(` `` so that Strapi ignores the expression.

e.g.
```js
"scripts": {
    "test": "FOO=${BAZ:-foo`#(`} sh -c 'echo $FOO'"
}
```

---

- [x] I'm sure that this issue hasn't already been referenced

### PR DESCRIPTION
**Pull request by ackro**
My PR is a:

💅 Enhancement

Main update on the:

Framework

Fixes #916. Prevent NPM scripts config in project's package.json from being used by dynamic config as it may contain shell script syntax that breaks parsing.

### CODE REVIEW

**Comment by lauriejim** [comment]
Thank you @ackro for you first contribution to Strapi. Appreciate your work, will test it in fews days 👍

**Comment by Aurelsicoko** [comment]
@ackro Thank you for this PR! It seems to work as expected however this method is a recursive one and you added a condition inside this recursive which is executed a lot of times. 

I think we could do something better and exclude the `info.script` object for being templated. Here how we could proceed:
```js
// Current
this.config = templateConfigurations(this.config);

// New
this.config = Object.assign({}, this.config, templateConfigurations(_.omit(this.config, 'info.script')));
```

What do you think about this solution?

**Comment by ackro** [comment]
@Aurelsicoko, good idea, that's a better approach. I can test this if you like but sounds good to go.

**Comment by lauriejim** [comment]
@ackro I release today, we will merge it for next release.

**Comment by lauriejim** [comment]
Hello @ackro, have you any update about @Aurelsicoko feedback ?

**Comment by ackro** [comment]
sorry guys, I misunderstood that comment as @Aurelsicoko working on it. I will submit a new PR for this.

**Comment by lauriejim** [comment]
@ackro You don't need to open a new PR, you just have to add new commit on this one.

And thank you for your contribution 👍

**Comment by lauriejim** [comment]
@ackro have you any update please ?

**Comment by Aurelsicoko** [comment]
It seems to work even if it's not optimized as we could except, we should merge it. @lauriejim let's go 👍

**Pull request merged**
