### PR TITLE
chore: remove step from time configure view modal

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* Removes the ability to set step with time fields in admin UI
* Removes checking for metadata.step because it was only used for time, instead we set defaults based on attribute.type
* Removes step check from metadatas schema

### Why is it needed?

* Since we released the ability to type a time in the TimePicker theres no need for a step & performance degrades when there are 1000s of items in the dropdown

### Related issue(s)/PR(s)

* resolves CONTENT-1530

### CODE REVIEW

**Comment by joshuaellis** [comment]
I need to update the User documentation, do you think this needs a migration to remove the step metadata from the attributes? Is there any BE bits I might have missed @Marc-Roig // @alexandrebodin

**Comment by alexandrebodin** [comment]
> I need to update the User documentation, do you think this needs a migration to remove the step metadata from the attributes? Is there any BE bits I might have missed @Marc-Roig // @alexandrebodin

I don't think that's worth it they should (to be verified during review) be removed after the next edition of the field. Added to my review list ✅

**Review by gu-stav — APPROVED** [review]
Works well for me. Nice cleanup!

**Comment by Marc-Roig** [comment]
Changes looks good to me, and I don't think we need a migration either.

Did we consider plugins using the DatePicker when doing the refactor? There are some plugins using it
https://github.com/ComfortablyCoding/strapi-plugin-publisher/blob/963d516b5aed0c724529ab1ba79b4ba9b6875955/server/config/index.js#L18
https://github.com/webbio/strapi-plugin-scheduler/blob/4d162483fd30ee1ffdeee631fd31e0e45aa0abfd/admin/src/components/Scheduler/index.tsx#L188

**Review by Marc-Roig — APPROVED** [review]

**Comment by joshuaellis** [comment]
> Change look good to me, and I don't think we need a migration either.
> 
> Did we consider plugins using the DatePicker when doing the refactor? There are some plugins using it [ComfortablyCoding/strapi-plugin-publisher@`963d516`/server/config/index.js#L18](https://github.com/ComfortablyCoding/strapi-plugin-publisher/blob/963d516b5aed0c724529ab1ba79b4ba9b6875955/server/config/index.js#L18) [webbio/strapi-plugin-scheduler@`4d16248`/admin/src/components/Scheduler/index.tsx#L188](https://github.com/webbio/strapi-plugin-scheduler/blob/4d162483fd30ee1ffdeee631fd31e0e45aa0abfd/admin/src/components/Scheduler/index.tsx#L188)

Their values will still be valid 👍🏼

**Comment by Cerlancism** [comment]
`step` is still stored in `strapi_core_store_settings` for the "Configure the view" data if configured the time step previously.

Now all "Configure the view" for the content type will error upon save.

The response in the inspector:
```json
{
	"data": null,
	"error": {
		"status": 400,
		"name": "BadRequestError",
		"message": "Bad Request",
		"details": {
			"name": "validationError",
			"errors": [
				"metadatas.post_date.edit field has unspecified keys: step"
			]
		}
	}
}
```

**Comment by SvenWesterlaken** [comment]
Unfortunately, I also still have the same errors on my end & start date field in strapi version `4.16.2`

**Comment by bendixcrse** [comment]
I also waited for an update by strapi, but they don't fix it. They removed the step option for their date picker (selecting the time in 5 / 10 / 15 etc. minutes steps).

I finally fixed that manually, by going into the Postgres database and searching for the general settings strapi table and removing the step attribute in the json.

**Comment by grant-nadine** [comment]
> I also waited for an update by strapi, but they don't fix it. They removed the step option for their date picker (selecting the time in 5 / 10 / 15 etc. minutes steps) and this is why the view isn't editable anymore if you had the steps defined before.
> 
> I finally fixed that manually, by going into the Postgres database and searching for the general settings strapi table and removing the step attribute in the json.

Thank you so much for responding. I've been looking all day for some direction to take to fix this. I didn't know where to start looking in postgres so this is a big help already. I will give these steps a try.

**Comment by SvenWesterlaken** [comment]
I also fixed it by entering the database and manually removing the keys from the settings table. @grant-nadine.

A general direction on how to fix this would be a database migration, I think?

**Comment by bendixcrse** [comment]
> > I also waited for an update by strapi, but they don't fix it. They removed the step option for their date picker (selecting the time in 5 / 10 / 15 etc. minutes steps) and this is why the view isn't editable anymore if you had the steps defined before.
> > I finally fixed that manually, by going into the Postgres database and searching for the general settings strapi table and removing the step attribute in the json.
> 
> Thank you so much for responding. I've been looking all day for some direction to take to fix this. I didn't know where to start looking in postgres so this is a big help already. I will give these steps a try.

Sure, you need to find the table 'strapi_core_store_settings' and then search for the key 'plugin_content_manager_configuration_content_types::api::{{YOUR_DOCUMENT_TYPE}}' (look at the placeholder at the end) and edit the JSON by removing the "step" attribute from the datepickers. After that it should work.

**Comment by grant-nadine** [comment]
Thank you @bendixcrse and @SvenWesterlaken! Really appreciate you providing this info, huge help :)

**Pull request merged**
