### PR TITLE
Fix issue #14312. Target field not nullified when selecting None

### LINKED ISSUE #14312: UID fields can not be created without an attached field
## Bug report

@kasonde [reported internally](https://strapihq.slack.com/archives/CEN0F9WF6/p1662274230026039) that it is impossible to create uid fields, which are not attached to another field.

Shared loom video: https://www.loom.com/share/59e284d5a90b4ffd9cf7943f7e120eff

Backend error thrown:

```json
{
  "error":{
    "name":"ValidationError",
    "message":"contentType.attributes.test.targetField must be one of the following values: name",
    "details":{
      "errors":[
        {
          "path":["contentType","attributes","test","targetField"],
          "message":"contentType.attributes.test.targetField must be one of the following values: name","name":"ValidationError"
        }
      ]
    }
  }
}
```

It looks like as if this is a regression.

### Required System information

- Node.js version: not relevant
- NPM version: not relevant
- Strapi version: 4.3.6
- Database: not relevant
- Operating system: not relevant

### Steps to reproduce the behavior

See attached loom video.

### Expected behavior

It was validated with @yanniskadiri that we do want to support uid fields, which are not attached to another field.

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Fixes #14312 

### Why is it needed?

Fix

### How to test it?

Following the issue reproduction steps it should not throw any errors anymore

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Comment by gu-stav** [comment]
Thank you @alexandrebodin. During refinement we've decided yesterday to discuss this case with product because it is unclear if it makes sense to have a UID field without an attached field. If a user would want to create e.g. a slug field, they can do that using a textfield and making it unique and we couldn't come up with another usecase so far. Let me know if you have anything in mind :)

**Comment by alexandrebodin** [comment]
From what I remeber, this was intended to address more technical usecases where the users would just generate a uid programatically based on multiple fields or a random id using lifecycles on the server. So basically not wanting our default behavior of generating something based on another attribute when not necessary. 

I don't recall anything else but we can probably find the histry in Notion somewhere :)

**Comment by gu-stav** [comment]
> 

Correct my if I am wrong, but they could do that using another field type too? The reason why I am hesitant to move on with this without product involvement is that we have a feeling that attaching a field to another field is actually the only thing which makes the UID field unique, because everything else can be achieved on other ways and if we'd make this optional, it might be very unclear what the field is actually about.

Will keep you posted.

**Comment by alexandrebodin** [comment]
Another field would not enforce uniquness. So if a user wants to use programatically generated UID but then make sure someone using the admin cannot create a duplicate they would have to implement the unique check themselves. Thats the only reason I can think of right now 🤔 

I would mostly be careful not to break apps that already have this targetField set to null via file or when it was working 👍

**Comment by gu-stav** [comment]
> Another field would not enforce uniqueness.

But you could set the other field to be unique and would achieve the same, no? Especially with the discussed improvements on making uniqueness configurable for different dimensions (i18n, content-type, component-type) I think this is very powerful way to achieve that.

**Comment by alexandrebodin** [comment]
That would probably be equivalent. In any case I don't think you can just remove that behavior as it would become a breaking change most likely. I would just fix the regression for now and consider dropping it for v5.

**Comment by alexandrebodin** [comment]
Do you have some updates on this ?

**Comment by gu-stav** [comment]
> Do you have some updates on this ?

The issue is being tracked here and currently in "Needs product": https://strapi-inc.atlassian.net/browse/CONTENT-1011

**Comment by alexandrebodin** [comment]
Ok I will have to put it in the next release if I don't get some news but then. No reason to leave a bug in the product because we want to change a feature in the future.

**Comment by derrickmehaffy** [comment]
Iirc UID fields apply global uniqueness where as a normal text field with unique set applies it only to that content-type.

**Pull request closed without merging**
