### PR TITLE
Fix relation description UI in CM EditView

### LINKED ISSUE #3998: In Repeatable groups with relation field the description of the field is not aligned with non relation fields
**Describe the bug**
In Repeatable groups with relation field the description of the field is not aligned with non relation fields.

see below image

**Steps to reproduce the behavior**
1. Create Group with a number field and a relation field
2. Go to Content type manage and add a description to the number field and to the relation field
3. Add the group to a content type
4. Go to content type page
5. Click on create new content type
6. Go to the section of the repeatable group

**Expected behavior**
Description texts should be aligned either above the input field or below it

**Screenshots**
image

**System**
- Node.js version: v12
- Strapi version: beta.16.3

### PR DESCRIPTION
**Pull request by virginieky**
#### Description of what you did:
Fixes #3998

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [X] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [X] Plugin

#### Manual testing done on the following databases:

- [X] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by soupette** [comment]
@Aurelsicoko it's a design update can you check it out?

My opinion is that description should be under the label for the relation displayed on the right side, but what should we do for the the relation inside a group? Since we have a the dnd reorder I am not sure where to put them.

**Comment by Aurelsicoko** [comment]
Currently, the description is not displayed for manyWay references. The UI doesn't really support a description text for this specific case.

Screenshot 2019-09-27 at 16 55 34

If we want to be consistent we should put it under the list, even if it'll look ugly.

**Comment by soupette** [comment]
@virginieky I tried your modifications, now the description is placed under the input which is great however the baseline is not respected anymore.

Screenshot 2019-10-03 at 10 59 34
Screenshot 2019-10-03 at 11 01 06

**Comment by soupette** [comment]
@virginieky  what is the status of this PR? I think that changes have been applied in the content manager update

**Comment by soupette** [comment]
I'm closing this PR as the modifications have been applied with the dynamic zone support.

**Pull request closed without merging**
