### PR TITLE
upload folder parameterized for more custom deploys

### PR DESCRIPTION
**Pull request by jmchza**
#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [x] Admin
- [x] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [x] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by jmchza** [comment]
Hey guys, I have added a way to customised the upload folder, so in that way you could have different alternatives when deploying the admin console separated of the api which is the main use case for most people out there.
So this is related to enabling the /api prefix for the api and breaking the admin console.
Well now with this option you can get away by separating the admin console of the api.
For an example think of playing with NGINX deploy and configurations, this open more path to play with.

**Comment by alexandrebodin** [comment]
Closing this PR for inactivity. Feel free to reopen if you want to finish it ;)

**Comment by jmchza** [comment]
Sorry guys, I've been hammered changing job so let me resubmit this one tonight.
Thanks.

**Comment by jmchza** [comment]
Hi guys,

I am now looking at this again and after a deeper look I see that this change won't be as straight forward as only customising the upload path for the admin console.
It would be enough for the cases where the api does not prepend a prefix i.e: /api
If that is the case, the admin console also would need to have few routes customised within some plugins such as user-permission plugin as well as strapi-admin plugin.
So i went and took the time to give this a go and i bumped into the problem that no matter what i defined into the overridden routes the controllers that ends up responding the /init request is still the originals. So I have overridden the /init to become /api/init into both plugins and for some reason it does not take any relevance.

So I will attach a screenshot into this ticket with a debugger stoped where you can see the routes are overridden but again for some reason it is still expecting a /init instead of /api/init

So steps that you need to do to reproduce this would be:

generate a new admin with the next admin config:
```
"admin": {
    "autoOpen": false,
    "path": "/",
    "build": {
      "backend": "http://localhost:1337/api"
    }
  }
```

copy routes.json and controller into the /extensions directory for the user-permission plugin as well as for the strapi-admin plugin, (not sure if the overridden of the strapi-admin actually works cause I am trying only to figure thins out don't thing this is into the official documentation )
and then generate the new admin to be deployed into a NGINX

```
npm run build
```

Deploy the console into an nginx server and attempt to login
you will see that the next request do not get a proper response:
```
http://localhost:1337/api/users-permissions/init
http://localhost:1337/admin/init
```

So before I could proceed with the customisation of the uploadPath for the upload plugin with /api as prefix for the REST api side , I need to understand where would this misbehaviour would be so I can contribute with this fix as well.

I hope all that makes sense.
Thanks.

**Comment by jmchza** [comment]
Hi Alex, would you mind to reopen this one and see if we can get it going this time? @alexandrebodin Thanks.

**Comment by alexandrebodin** [comment]
Hi @jmchza We are refactoring the upload plugin right now. I would recommend you wait just a bit before adding this feature :)

**Pull request closed without merging**
