### PR TITLE
Added core-js dependency

### LINKED ISSUE #2735: GraphQL plugin installation issue
**Informations**
- **Node.js version**: node v10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.21 
- **Database**: Mongo 4.0.2
- **Operating system**: Windows x64
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When clicked from Plugin in Admin UI - Admin didnt respond, so i manually restarted strapi - there was error after restart:
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\Projects\strapi\my-project\plugins\graphql\node_modules\apollo-env\lib\polyfills\array.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

So i removed the folder from plugins and reinstalled it from CLI:

strapi install graphql
Graph QL installed successfully from CLI but still same issue on starting strapi.

**Steps to reproduce the problem**

1. Go to admin panel and click install for GraphQL - wait for restart
OR
1. Go to CLI and execute "strapi install graphql"
2. Run strapi start

**What is the expected behavior?**

It should load the application

**Suggested solutions**

### PR DESCRIPTION
**Pull request by parikhdhruv24791**
Links to issue #2735 
(https://github.com/strapi/strapi/issues/2735)

**My PR is a:**
- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #2735 
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

**Main update on the:**
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

**Manual testing done on the following databases:**
- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres

**Description:**
Issue with core-js dependency - always got an error while adding graphql plugin
Check issue #2735  for details.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@parikhdhruv24791 More than likely this package needs to be moved to the `Strapi-Helper` plugin. Due to how NodeJS works there could be conflicts if one or more plugins share the same depends as each other. 

The helper plugin is what deals with these depends, more than likely in this case core-js is a dependency for another module and in your particular case it was not installed properly. Either way this should be looked closer into and moved over here: https://github.com/strapi/strapi/blob/master/packages/strapi-helper-plugin/package.json

**Comment by derrickmehaffy** [comment]
@lauriejim @Aurelsicoko thoughts? I'm not entirely sure if this depends is required or not, or if it was an issue with the user environment and resolving dependencies.

**Comment by derrickmehaffy** [comment]
Just as a footnote @parikhdhruv24791 this module is not graphQL related itself (it does other functions), typically if a module is directly related to the plugin is when it is stored in that plugins `package.json` such as the case with the apollo module

**Comment by soupette** [comment]
@derrickmehaffy 
> More than likely this package needs to be moved to the Strapi-Helper plugin. 

It needs to be moved to the strapi-helper-plugin if it's going to be used by the UI of others plugins or it causes a `babel-polyfill` error. A lot of dependencies are being put in this packages and  we would like to reduce the amount of its dependencies..

**Comment by lauriejim** [comment]
This issue come from Apollo Graphql.
I think we have to update this deps.
Since this PR was merged https://github.com/apollographql/apollo-tooling/pull/961

**Pull request closed without merging**
