### PR TITLE
Falky tests experimentation

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Experimenting with the flaky test this one was a straight forward change to avoi ddepending on timers. 

### Why is it needed?

Fix & experiment flaky test issues

### How to test it?

Run the tests on the inputUID 

### Related issue(s)/PR(s)

/

### CODE REVIEW

**Comment by remidej** [comment]
It looks like the github action still failed for `admin/src/pages/Roles/pages/tests/CreatePage.test.js`

**Comment by alexandrebodin** [comment]
> It looks like the github action still failed for `admin/src/pages/Roles/pages/tests/CreatePage.test.js`

Yes looks like it is just a very slight improvement but this just shows we haven't found the root case yet... 

I'm leaning towards issues with setTimeouts and notifications at the moment 🤔

**Review by innerdvations — APPROVED** [review]
Runinband seems like a good idea to me, should at least help with the consistency in passing until we clean up the tests themselves

Updated tests look fine.

**Review by remidej — APPROVED** [review]
LGTM too, that's a surprising speed boost 🚀

**Pull request merged**
