### PR TITLE
Add authSource & ssl options to MongoDB connector

### LINKED ISSUE #694: Add authSource & ssl options to MongoDB connector
**Node.js version**: v8.9.1
**npm version**: v5.6.0
**Strapi version**: v3.0.0-alpha.10.2
**Operating system**: macOS

**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

I can't connect to MongoDB.

**If the current behavior is a bug, please provide the steps to reproduce the problem**

I need to send some params to the MongoDB connection, if not it fails in the `strapi new project`.

* In the MongoDB URL: `?authSource=admin&ssl=true`
* In the MongoDB CLI: `--ssl --sslAllowInvalidCertificates --authenticationDatabase admin`

**What is the expected behavior?**

I should able to connect to MongoDB.

Thanks in advance!

### PR DESCRIPTION
**Pull request by abdonrd**
Based on #738.
Fixes #694.

I have not tried it yet.

### CODE REVIEW

**Comment by lauriejim** [comment]
Can you test it please and tell me if it fix your issue ?

**Comment by abdonrd** [comment]
I'll try it as soon as I can! (a couple of days I guess)

**Comment by lauriejim** [comment]
Perfect ! Thank you

**Comment by abdonrd** [comment]
@lauriejim it works for me with using the `config/environments/development/database.json`! 🎉 

But it doesn't work with the interactive CLI from `strapi new myDevelopmentProject --dev`.

**Comment by abdonrd** [comment]
@lauriejim remember that it doesn't work with the interactive CLI from `strapi new myDevelopmentProject --dev`, only with the config files.

**Comment by abdonrd** [comment]
@lauriejim remember that it doesn't work with the interactive CLI from `strapi new myDevelopmentProject --dev`, only with the config files.

screen shot 2018-03-14 at 09 32 16

**Comment by lauriejim** [comment]
It's normal. Strapi try a `npm install strapi-mongoose@alpha` and your update is not publish to npm.
If you update the line where the test connection folder is created by `npm link strapi-mongoose` it should work.

**Pull request merged**
