### PR TITLE
Convert 1/0 to true/false for mysql

### PR DESCRIPTION
**Pull request by lauriejim**
My PR is a:
🐛 Bug fix

Main update on the:
Framework

Related issue: #1203

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Awesome! Thanks @lauriejim ! I'll merge this locally and do some testing. \o/

**Comment by derrickmehaffy** [comment]
@lauriejim AdminUI works fine.

Get requests properly return the specified values of `true` and `false` however POST and PUT requests do not work. If you attempt to send a `true` or `false` instead of the 1/0 you get this:

```
[2018-05-30T16:44:48.341Z] debug POST /testboolean (96 ms)
[2018-05-30T16:44:52.931Z] debug GET /testboolean (14 ms)
{ Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'true' for column 'testboolean1' at row 1
    at Query.Sequence._packetToError (/root/strapitest/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/root/strapitest/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/root/strapitest/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/root/strapitest/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/root/strapitest/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/strapitest/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
    at Protocol._enqueue (/root/strapitest/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/root/strapitest/node_modules/mysql/lib/Connection.js:208:25)
    at /root/strapitest/node_modules/knex/lib/dialects/mysql/index.js:161:18
From previous event:
    at Client_MySQL._query (/root/strapitest/node_modules/knex/lib/dialects/mysql/index.js:155:12)
    at Client_MySQL.query (/root/strapitest/node_modules/knex/lib/client.js:206:17)
    at Runner.<anonymous> (/root/strapitest/node_modules/knex/lib/runner.js:155:36)
From previous event:
    at /root/strapitest/node_modules/knex/lib/runner.js:61:21
From previous event:
    at Runner.run (/root/strapitest/node_modules/knex/lib/runner.js:47:31)
    at Builder.Target.then (/root/strapitest/node_modules/knex/lib/interface.js:39:43)
    at Child.<anonymous> (/root/strapi/packages/strapi-bookshelf/node_modules/bookshelf/lib/model.js:1118:36)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlMessage:
   'Incorrect integer value: \'true\' for column \'testboolean1\' at row 1',
  sqlState: '22007',
  index: 0,
  sql:
   'insert into `testbooleans` (`created_at`, `testboolean1`, `testboolean2`, `teststring`, `updated_at`) values (\'2018-05-30 09:45:11.025\', \'true\', \'false\', \'test5\', \'2018-05-30 09:45:11.025\')' }
```

The alias works fine on GET requests but it doesn't convert between them for POST/PUT.

**Comment by derrickmehaffy** [comment]
Response from a GET Request:

```json
[
    {
        "id": 4,
        "teststring": "test1",
        "testboolean1": true,
        "testboolean2": false,
        "created_at": "2018-05-30T16:41:43.000Z",
        "updated_at": "2018-05-30T16:41:43.000Z"
    },
    {
        "id": 7,
        "teststring": "test2",
        "testboolean1": false,
        "testboolean2": true,
        "created_at": "2018-05-30T16:41:49.000Z",
        "updated_at": "2018-05-30T16:41:49.000Z"
    },
    {
        "id": 10,
        "teststring": "test3",
        "testboolean1": true,
        "testboolean2": true,
        "created_at": "2018-05-30T16:41:56.000Z",
        "updated_at": "2018-05-30T16:41:56.000Z"
    },
    {
        "id": 13,
        "teststring": "test4",
        "testboolean1": false,
        "testboolean2": false,
        "created_at": "2018-05-30T16:42:02.000Z",
        "updated_at": "2018-05-30T16:42:02.000Z"
    }
]
```

**Comment by lauriejim** [comment]
@derrickmehaffy Can you give me steps to reproduce your issue. It look works fine on my side.

**Comment by derrickmehaffy** [comment]
@lauriejim I just created a test model and used postman to try and do a post request, I also tried to do a put request on entries I made from the adminUI.

I merged this PR into the current master when I tested.

**Comment by lauriejim** [comment]
@derrickmehaffy I tried again and I haven't errors.
Test create data from UI and update from Postman, Create and update from Postman, Create and update from UI. Create from Postman and update from UI. All work fine.

**Comment by derrickmehaffy** [comment]
Running some additional checks on the fix-boolean-mysql branch.

**Comment by derrickmehaffy** [comment]
Steps to reproduce:

Node Version: v10.3.0
NPM Version: v6.1.0
Database: MariaDB 10.2

Model:
```
{
  "connection": "default",
  "collectionName": "testbooleans",
  "info": {
    "name": "testboolean",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "teststring": {
      "type": "string"
    },
    "testbool1": {
      "type": "boolean"
    },
    "testbool2": {
      "type": "boolean"
    },
    "testbool3": {
      "type": "boolean"
    }
  }
}
```

PUT Request on id 4 (Updating the value `testbool1` from `true` to `false`:

```
[2018-05-31T13:57:20.601Z] debug PUT /testboolean/4 (24 ms)
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 4, 1 ],
  __knexQueryUid: '8f405d71-1402-4269-a68b-bbe3aa4d3564',
  sql:
   'select `users-permissions_user`.* from `users-permissions_user` where `users-permissions_user`.`id` = ? limit ?' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 4 ],
  __knexQueryUid: 'e1467bc9-8e9f-422a-a2a5-8508fbf191c1',
  sql:
   'select `users-permissions_role`.* from `users-permissions_role` where `users-permissions_role`.`id` in (?)' }
{ method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '4', 'false', 2018-05-31T13:57:54.865Z, '4' ],
  __knexQueryUid: '9709d7d3-55eb-4c6b-a720-319ef421e3f2',
  sql:
   'update `testbooleans` set `id` = ?, `testbool1` = ?, `updated_at` = ? where `id` = ?' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '4', 1 ],
  __knexQueryUid: '3acbfcd7-dd5b-45ff-a922-49d6d86f6dda',
  sql:
   'select `testbooleans`.* from `testbooleans` where `testbooleans`.`id` = ? limit ?' }
Unhandled rejection Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'false' for column 'testbool1' at row 1
    at Query.Sequence._packetToError (/root/strapitest/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/root/strapitest/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/root/strapitest/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/root/strapitest/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/root/strapitest/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/strapitest/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
    at Protocol._enqueue (/root/strapitest/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/root/strapitest/node_modules/mysql/lib/Connection.js:208:25)
    at /root/strapitest/node_modules/knex/lib/dialects/mysql/index.js:161:18
From previous event:
    at Client_MySQL._query (/root/strapitest/node_modules/knex/lib/dialects/mysql/index.js:155:12)
    at Client_MySQL.query (/root/strapitest/node_modules/knex/lib/client.js:206:17)
    at Runner.<anonymous> (/root/strapitest/node_modules/knex/lib/runner.js:155:36)
From previous event:
    at /root/strapitest/node_modules/knex/lib/runner.js:61:21
From previous event:
    at Runner.run (/root/strapitest/node_modules/knex/lib/runner.js:47:31)
    at Builder.Target.then (/root/strapitest/node_modules/knex/lib/interface.js:39:43)
    at Child.<anonymous> (/root/strapi/packages/strapi-bookshelf/node_modules/bookshelf/lib/model.js:1118:36)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)

{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '4', 1 ],
  __knexQueryUid: '746acb99-d759-4143-8393-14bb3f714c74',
  sql:
   'select `testbooleans`.* from `testbooleans` where `testbooleans`.`id` = ? limit ?' }
[2018-05-31T13:57:54.876Z] debug PUT /testboolean/4 (20 ms)
```

POST Request to create a new entry:

```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 4, 1 ],
  __knexQueryUid: '28e4acf5-50ba-465d-a39c-7a314d9160e3',
  sql:
   'select `users-permissions_user`.* from `users-permissions_user` where `users-permissions_user`.`id` = ? limit ?' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 4 ],
  __knexQueryUid: '90abbba5-9dba-483d-9b2f-9795a09ab390',
  sql:
   'select `users-permissions_role`.* from `users-permissions_role` where `users-permissions_role`.`id` in (?)' }
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings:
   [ 2018-05-31T14:01:40.362Z,
     'false',
     'false',
     'true',
     'test10',
     2018-05-31T14:01:40.362Z ],
  __knexQueryUid: '1d15a129-48f1-4267-8382-828517b90cb1',
  sql:
   'insert into `testbooleans` (`created_at`, `testbool1`, `testbool2`, `testbool3`, `teststring`, `updated_at`) values (?, ?, ?, ?, ?, ?)' }
{ Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'false' for column 'testbool1' at row 1
    at Query.Sequence._packetToError (/root/strapitest/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/root/strapitest/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/root/strapitest/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/root/strapitest/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/root/strapitest/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/strapitest/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
    at Protocol._enqueue (/root/strapitest/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/root/strapitest/node_modules/mysql/lib/Connection.js:208:25)
    at /root/strapitest/node_modules/knex/lib/dialects/mysql/index.js:161:18
From previous event:
    at Client_MySQL._query (/root/strapitest/node_modules/knex/lib/dialects/mysql/index.js:155:12)
    at Client_MySQL.query (/root/strapitest/node_modules/knex/lib/client.js:206:17)
    at Runner.<anonymous> (/root/strapitest/node_modules/knex/lib/runner.js:155:36)
From previous event:
    at /root/strapitest/node_modules/knex/lib/runner.js:61:21
From previous event:
    at Runner.run (/root/strapitest/node_modules/knex/lib/runner.js:47:31)
    at Builder.Target.then (/root/strapitest/node_modules/knex/lib/interface.js:39:43)
    at Child.<anonymous> (/root/strapi/packages/strapi-bookshelf/node_modules/bookshelf/lib/model.js:1118:36)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlMessage:
   'Incorrect integer value: \'false\' for column \'testbool1\' at row 1',
  sqlState: '22007',
  index: 0,
  sql:
   'insert into `testbooleans` (`created_at`, `testbool1`, `testbool2`, `testbool3`, `teststring`, `updated_at`) values (\'2018-05-31 07:01:40.362\', \'false\', \'false\', \'true\', \'test10\', \'2018-05-31 07:01:40.362\')' }
[2018-05-31T14:01:40.368Z] debug POST /testboolean (15 ms)
```

**Comment by derrickmehaffy** [comment]
Using 0/1 instead of false/true works fine:

image

**Comment by lauriejim** [comment]
@derrickmehaffy please can you try to use raw format with Postman.

**Comment by derrickmehaffy** [comment]
@lauriejim yeah I can once I get a bit more free time, busy day. If both you and @Aurelsicoko are both able to use it, its likely and issue with pbcak ("Problem Between Chair and Keyboard") aka me :stuck_out_tongue:

**Comment by derrickmehaffy** [comment]
@lauriejim Yup it was pbcak, using raw set to `application/json` worked just fine in postman. Not sure why `x-www-form-urlencoded` wasn't working properly but :man_shrugging: 

Looks good to me.

**Pull request merged**
