### PR TITLE
Fixed media library item checkbox selection

### PR DESCRIPTION
**Pull request by ritiksharmarj**
### What does it do?

- Modify the 'onSelectOne' function to take only the selected item as its parameter, rather than the entire element object.
- Modify the 'isSelected' line to check if the selected array contains the 'id' and 'type' of the current item.

### Why is it needed?

Only the selected item should be checked (checkbox). Now if the user checks any item then it checks the checkbox of the current item only.

### How to test it?

- packages/core/upload/admin/src/components/TableList/TableRows.js

### Related issue(s)/PR(s)

#16377

https://user-images.githubusercontent.com/54701022/231890465-734a7c3f-4c7c-4d15-a94c-e79e36be0950.mp4

### CODE REVIEW

**Comment by ritiksharmarj** [comment]
@joshuaellis what should I do next?

**Comment by joshuaellis** [comment]
> @joshuaellis what should I do next?

You'll want to look at fixing the tests that are broken :)

**Comment by ritiksharmarj** [comment]
> > @joshuaellis what should I do next?
> 
> You'll want to look at fixing the tests that are broken :)

I think there is 1 failed test case and the rest 8 are skipped.
Could you provide me with documentation or any guidance to fix these test cases?

**Comment by joshuaellis** [comment]
> @joshuaellis
> 
> I think there is 1 failed test case and the rest 8 are skipped. Could you provide me with documentation or any guidance to fix these test cases?

Identify the test that's failing, run it locally and look at why it's breaking, then decide if you're code had unintended side effects or the test needs to be modified because it was behaving incorrectly. 

Documentation – look at react-testing-library & jest to understand how the tests are written / work

If you need more guidance then you'll need to be patient and wait till i have time to do a full review of this PR – sometime next week I imagine 🙂

**Comment by ritiksharmarj** [comment]
@joshuaellis I tried to understand test cases and also removed my code and tested it there for `test:front` but it still failed. I want to understand my mistake so that I'll take care of it next time.

**Comment by joshuaellis** [comment]
Now the branch is up to date, i would try again.

**Comment by joshuaellis** [comment]
Closing due to inactivity.

**Pull request closed without merging**
