### PR TITLE
Add primary keys to relational table

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Add Primary Keys to link tables

### Why is it needed?

Some cloud service require them

### How to test it?

- TO BE Tested on multiple DBs
- Start with all code and create data (relations)
- Stop server
- Switch to this PR
- Restart
- No errors should happen and Ids should be created in join tables 

### Related issue(s)/PR(s)

- fix https://github.com/strapi/strapi/issues/13455

### TODO

- [x] It breaks migrations on existing Sqlite databases we still need a solution

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
FYI for @marcoautiero / @alexandrebodin we have an EE customer mentioning this also, feel free to ask the support team for more info or see internal TID1774

**Comment by alanko0202** [comment]
Hi all, I have the same issue with the MySQL HA cluster requirement.
Do you have the target date for this release? or any workaround I could do? Thanks in advance.

**Comment by alanko0202** [comment]
Hi all, I have the same issue with the MySQL HA cluster requirement.
Do you have the target date for this release? or any workaround I could do? Thanks in advance.

**Comment by alexandrebodin** [comment]
@alanko0202 You can apply this PR changes to your project if you need to using patch-package. @derrickmehaffy  can help you with that.

**Comment by alexandrebodin** [comment]
For the time being we need a new feature to be built into a lib we use and we do not have the bandwidth to do it.

**Comment by alexandrebodin** [comment]
Here is the Knex PR we need to finish this work https://github.com/knex/knex/issues/5299

**Comment by alanko0202** [comment]
@alexandrebodin Thanks. It works after I apply this changes.

**Review by Marc-Roig — APPROVED** [review]

**Review by innerdvations — APPROVED** [review]
Tested on sqlite and postgres 14 and worked as expected

What is the reason for adding an new autoincrement column for the pk instead of using a primary key constraint on both columns in the link tables?

**Comment by alexandrebodin** [comment]
> Tested on sqlite and postgres 14 and worked as expected
> 
> What is the reason for adding a new autoincrement column for the pk instead of using a primary key constraint on both the existing columns in the link tables?

-> Mostly to make sure this can't break users apps if they have duplicated link rows for some reason. I went for the less risky approach here
-> I also I'm concerned with the compatibility issue with composite PKs in the 1st place I'm not confident they are behaving and supporting in the same way in the DBs & hosted DBs that already have this issue

**Comment by alexandrebodin** [comment]
@derrickmehaffy can you do this test on a maria db project ?

**Comment by innerdvations** [comment]
For some reason my mind keeps coming back to this, sorry 😆

Although it seems totally safe, it feels like a big change (adding a column to every relational table) for something that is only necessary in rare situations. I don't know much about the way the internal migrations work, but would it make things complicated to add a flag (like in env or project config) to create this PK only when specified?

**Review by derrickmehaffy — APPROVED** [review]
LGTM tested on SQLite3, MariaDB, and MySQL (didn't test PG)

**Pull request merged**
