### PR TITLE
feat: Add keycloak native users-permissions provider

### PR DESCRIPTION
**Pull request by derrickmehaffy**
### What does it do?

Adds Grant's Keycloak provider natively to the users-permissions plugin

### Why is it needed?

Internal TID6072

### How to test it?

You'll need a local keycloak instance, for setup of keycloak you can follow the beginning part of this guide: https://medium.com/@achiumenti/strapi-keycloak-now-its-security-time-049d178473f8

### Related issue(s)/PR(s)

https://github.com/strapi/documentation/pull/2048

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Running experimental to test with and provide to customer to test with before merging

**Comment by derrickmehaffy** [comment]
Tested against Keycloak Server version: 24.0.1

**Comment by derrickmehaffy** [comment]
Example repo I used for testing (included some customization to users-permissions as well unrelated to keycloak): https://github.com/strapi-support-demo-apps/strapi-example-v4-customize-users-permissions

**Comment by derrickmehaffy** [comment]
When merged/released this needs to be updated: https://feedback.strapi.io/feature-requests/p/keycloak-provider

**Review by alexandrebodin — APPROVED** [review]

**Pull request merged**
