### PR TITLE
Improve & add missing Slovak (SK) translations

### PR DESCRIPTION
**Pull request by sebqq**
#### Description of what you did:

Just refined Slovak translations and added missing ones.

**Update**: Also added translation file for `strapi-plugin-upload` plugin package.

**Update 2**: Also refined and added missing translations for `strapi-plugin-content-type-builder` plugin package

**Update 3**: Also refined and added missing translations for `strapi-plugin-content-manager` plugin package

**Update 4**: Also refined and added missing translations for `strapi-plugin-users-permission` plugin package

### CODE REVIEW

**Comment by sebqq** [comment]
Could translation strings be reason why the tests failed?

**Comment by soupette** [comment]
@sebqq thanks a lot for your contribution can you resolve the conflict so we can review your PR?

**Comment by sebqq** [comment]
> @sebqq thanks a lot for your contribution can you resolve the conflict so we can review your PR?

Conflicts should be resolved.

**Review by soupette — APPROVED** [review]
LGTM thanks for your contribution!

**Pull request merged**
