### PR TITLE
fix: Removed the unexpected capital letters

### PR DESCRIPTION
**Pull request by lucasboilly**
### What does it do?

I removed the capital letters that were at the beginning of the words "Multiple" and "Locales".

### Why is it needed?

Publish and unpublish multiple locales were the only items in the popover with a capital letters for each word.

### How to test it?

Open an entry that has i18n and click the "More" button next to the "Publish" button.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/20808

### CODE REVIEW

**Review by simotae14 — CHANGES_REQUESTED** [review]
you have a commitlint issue because of the format of your commit, you need to follow this convention https://github.com/conventional-changelog/commitlint/#what-is-commitlint

**Review by remidej — COMMENTED** [review]
We can bypass the commitlink check this time, but you need to fix some end to end tests. Look for `getByRole('menuitem', { name: 'Publish Multiple Locales', exact: true })` in your repo. It no longer finds it, you need to update the casing there

**Comment by lucasboilly** [comment]
@simotae14 @remidej should be good now (except the commitlint issue).

**Review by simotae14 — APPROVED** [review]
Well done @lucasboilly 👏🏽

**Pull request merged**
