### PR TITLE
kara-kalpak locale

### PR DESCRIPTION
**Pull request by kiri-rin**
### What does it do?

Adding Kara-Kalpak locale to plugin-i18n (according to https://iso639-3.sil.org/code/kaa) 

### Why is it needed?
Support Kara-Kalpak locale

### How to test it?

- Open internationalization settings page
- Add new locale
- Check that Kara-Kalpak locale appears in locales select field

### Related issue(s)/PR(s)

none

### CODE REVIEW

**Comment by ronronscelestes** [comment]
Hi @kiri-rin, thank you for this contribution 😊
It seems that snapshots are failing, could you please try updating them with `yarn test:unit -u`?

**Comment by kiri-rin** [comment]
> Hi @kiri-rin, thank you for this contribution blush It seems that snapshots are failing, could you please try updating them with `yarn test:unit -u`?
Done

**Comment by ronronscelestes** [comment]
> @ronronscelestes Hello! Any news on this pull request?

Hi! I'm sorry we went on a company retreat for a few days - I will approve the run tests flow now 😊

**Review by ronronscelestes — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
