### PR TITLE
Chore: Remove unique identifier

### PR DESCRIPTION
**Pull request by Mcastres**
### What does it do?

Removes unique identifiers from the codebase. 
I'm not sure if there are additional things to do in order to completely get rid of it.

### Why is it needed?

It was being used to match the uid created when someone browsed the website in order to estimate the conversion between Website <> Strapi. We'll no longer track this conversion this is why I made this PR.

### CODE REVIEW

**Comment by joshuaellis** [comment]
Can you fill in the template pls? So we know why it was done mainly in case we're looking for historical context in the future.

**Comment by Mcastres** [comment]
> Can you fill in the template pls? So we know why it was done mainly in case we're looking for historical context in the future.

I added the reason why :)

**Review by alexandrebodin — DISMISSED** [review]
LGTM to remove it @joshuaellis I'll let you confirm everything is still working :)

**Comment by joshuaellis** [comment]
@Mcastres looks like you've not ran `yarn` after removing a dep & there are lint issues too 👍🏼

**Comment by Mcastres** [comment]
Yes I did and I don't have any errors :/

**Comment by gu-stav** [comment]
@Mcastres I've updated the lockfile and rebased the branch on `main` because there were merge conflicts. Looks good to me now - I am very happy to see this dependency go away :)

**Review by gu-stav — APPROVED** [review]

**Review by joshuaellis — APPROVED** [review]

**Pull request merged**
