### PR TITLE
Losing OneToOne relation in the content manager

### LINKED ISSUE #825: User model lose his relations (one to one) when saved from the admin panel
**Node.js version**: nvm with node v9.2.0

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.11.1

**Operating system**: macos

Simple use / case from a fresh start strapi project

Step 1: Create a model **license** from the content type builder with a filed **name** (which is a string)
Step 2: On the User model create a relation one to one with the license model (license 1--1 user)
Step 3: Go to content type Licenses, create a license
Step 4: Go to content type Users, select the admin user and associate the license, save

Step 5: This is where the bug happen -> Again click on your admin user
On the associated model there is your license visible on the right side, just save and again click on your admin user 

Result : license is empty
Expected: license should be still associated to your admin user

--------

I spent some time doing some log on strapi core code and right here https://github.com/strapi/strapi/blob/v3.0.0-alpha.11.1/packages/strapi-plugin-content-manager/config/queries/mongoose.js#L92-L98

the value of 
```
{
  id: record[details.via][this.primaryKey] || record[details.via].id,
  values: {
    [current]: null
  },
  parseRelationships: false
}
```
is equal to 
```
{
  id: 5ab25c59bd3ce82f93cedb1c,
  values: {
    license: null
  },
  parseRelationships: false
}
```

I can reproduce this bug with other model name (not the fact the name is license).
I cannot reproduce this bug if i try with another model relation (license N--1 user).

### PR DESCRIPTION
**Pull request by TheWebsDoor**
The problem was that the relation was recreated on only one side and sometimes, the removal of the previous relationship was executed before updating with the new one (because of the asynchronous function) and if the relation remained the same, that's why sometimes the relation disappears.
So there are the steps : 

- Delete relation on the old first side (if exists)
- Delete relation on the old second side
- Recreate relation on the new first side (only when deletion complete)
- Recreate relation on the new second side (only when deletion complete and if value not null)

### CODE REVIEW

**Comment by lauriejim** [comment]
@TheWebsDoor Can you give us an update about @Aurelsicoko feedback please.
Will be a pleasure to merge this PR !

**Comment by TheWebsDoor** [comment]
Sorry @lauriejim I was quite busy during last days but I'll check this tonight :)

**Comment by lauriejim** [comment]
Super good news ! We really want to pass this point in the next release :)

**Comment by TheWebsDoor** [comment]
I've made a little clean according to what you said. Tell me if it's better for you :)

**Comment by Aurelsicoko** [comment]
LGTM

**Comment by sbastias** [comment]
Hello, I think I've fixed this - at least with my installation.

I needed a oneToOne relationship with self for a bilingual CMS. So i needed MyObject <-> MyObject.

The code below updated in **strapi-hook-mongoose/lib/relations.js** finally worked!



       // In the 'update' block switch statement
        case 'oneToOne':
            if (response[current] !== params.values[current]) {
              const value = _.isNull(params.values[current]) ? response[current] : params.values;
              const recordId = _.isNull(params.values[current]) ? value[this.primaryKey] || value.id || value._id : value[current];

              const model = module.exports.getModel(details.model || details.collection, details.plugin);


              /***********************************

              If the record to update already has a relation set with key [current], and it's not the same as the submitted value,
              then retrieve the associated record, and clear it's association by setting [details.via] to null

              ********************************/
              if (response[current] && _.isObject(response[current]) && response[current][this.primaryKey] != value[current]) {

                console.log(value[current])

                console.log('Unsetting reciprocal relation: ' + response[current][this.primaryKey] + '[' + details.via + ']')
                virtualFields.push(
                  module.exports.update.call(this, {
                    id: response[current][this.primaryKey],
                    values: {
                      [details.via]: null
                    },
                    parseRelationships: false
                  })
                );
              }

              // Remove previous relationship asynchronously if it exists.
              virtualFields.push(
                model
                  .findOne({ [model.primaryKey]: recordId })
                  .populate(details.via)
                  .then(record => {

                    console.log("\n\n" + details.via)

                    if (record && _.isObject(record[details.via])) {

                      let firstQuery = {
                        id: getValuePrimaryKey(record[details.via], model.primaryKey),
                        values: {
                          [details.via]: null
                        },
                        parseRelationships: false
                      }

                      // console.log("\n\nFIRST\n\n")
                      // console.log(firstQuery)

                      module.exports.update.call(this, firstQuery)
                      debugger

                    }

                  return Promise.resolve();

                })
                .then(() => {

                  // set new relation on target

                  let secondQuery = {
                    id: getValuePrimaryKey(response || {}, this.primaryKey),
                    values: {
                      [current]: value[current]
                    },
                    parseRelationships: false
                  }

                  // console.log("\n\nSECOND\n\n")
                  // console.log(secondQuery)

                  virtualFields.push( module.exports.update.call(model, secondQuery) )
                  


                  if (!_.isNull(params.values[current])) {
                    let thirdQuery = {
                      id: recordId,
                      values: {
                        //[current]: null,
                        [details.via]: getValuePrimaryKey(params.values, this.primaryKey) || null
                      },
                      parseRelationships: false
                    }

                    // console.log("\n\nTHIRD\n\n")
                    // console.log(thirdQuery)

                    virtualFields.push( module.exports.update.call(model, thirdQuery) )

                    debugger
                  }

                  

                  return Promise.resolve();
                })

              )

              acc[current] = _.isNull(params.values[current]) ? null : value[current];
              
            }

            break;

**Pull request merged**
