### PR TITLE
package.json name property must be in lowercase

### PR DESCRIPTION
**Pull request by kuldipem**
#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [x] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@kuldipem I don't think the devs want to add more depends why not just use `toLowerCase()`

**Comment by kuldipem** [comment]
`toLowerCase()` can be used, but will not generate a proper name, e.g.
`TestApp` become `testapp`, if we use `toLowerCase()`, but using the
depends, the name will be `test-app`, that is a proper name for a project.

- I'm agree with you, but slugify is a simple solution rather than mantain
string function to slugify the name.

**Comment by derrickmehaffy** [comment]
Poking @alexandrebodin to get his thoughts but I can almost promise they are trying to avoid adding depends and are in the process of trying to remove them.

**Comment by kuldipem** [comment]
if @alexandrebodin  think, there is no more third-party deps , then I could write a simple string function to make it similar to it.

**Comment by alexandrebodin** [comment]
@kuldipem You can try using the `kebabCase` function from lodash which already is in the dependencies.  I think it should do the job fine

**Comment by kuldipem** [comment]
Thanks, I'll check it out. That's great idea. I would do it.

**Comment by derrickmehaffy** [comment]
@kuldipem I believe Alex's solution would be pretty easy based on the lodash docs: https://lodash.com/docs/#kebabCase

Just swapping out your `toSlugCase(scope.name)` to `_.kebabCase(scope.name)` (it looks like you'll need to require lodash as I don't think there is any other lodash functions being used in that file)

**Comment by kuldipem** [comment]
I'm closing this PR and creating a new one with lodash kebab case function

**Pull request closed without merging**
