### PR TITLE
Fix the issue templates

### PR DESCRIPTION
**Pull request by abdonrd**
My PR is a:
🐛 Bug fix

Main update on the:
GitHub

Fix the issue templates with the right names.

### CODE REVIEW

**Comment by lauriejim** [comment]
Thanks @abdonrd , little mistake !

**Comment by abdonrd** [comment]
By the way... I don't like very much the checkbox the because:

screen shot 2018-05-04 at 16 10 43

In the issues view:

screen shot 2018-05-04 at 16 10 23

**Comment by lauriejim** [comment]
I'm agree with you. Do you have an idea to `force` user to check open and closed issue ?
Just let the message and remove the checkbox ?

**Comment by abdonrd** [comment]
I guess so...

I really don't know if gain some effectiveness by forcing people to check the checkbox.
People who do not follow the template, possibly delete it entirely haha

**Comment by abdonrd** [comment]
Also, maybe you want to remove/update the [.github/ISSUE_TEMPLATE.md](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE.md).

**Pull request merged**
