### PR TITLE
Adds missing Twitter provider redirect URI configuration

### LINKED ISSUE #2346: Missing URI redirection configuration in Twitter provider
**Informations**
- **Node.js version**: 10.9.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: MongoDB v4.0.4
- **Operating system**: Fedora 29

**What is the current behavior?**
The UI shows a bad value for this parameter that the user has to add to the provider app setup: `.../auth/twitter/callback`. If the user add this one the process fails.
bad

**Steps to reproduce the problem**
Follow the documentation to setup Twitter provider.

**What is the expected behavior?**
The UI should should the correct value for this parameter: `.../connect/twitter/callback`
good

Moreover, this would be consistent with the URI provided by the rest of the providers.
google
fb
discord

**Suggested solutions**
To add a new case to cover Twitter in this switch statement: https://github.com/strapi/strapi/blob/17e2063943f5410fc014f6a95dfba30ec3ae8a93/packages/strapi-plugin-users-permissions/admin/src/components/PopUpForm/index.js#L45

I'm sending a PR.

### PR DESCRIPTION
**Pull request by jesusprubio**
My PR is a: 🐛 Bug fix #2346

Main update on the: Plugin

This PR fixes this issue: https://github.com/strapi/strapi/issues/2346

### CODE REVIEW

**Comment by maturanomx** [comment]
Can you do a `git rebase` instead the merges?; In order to have a clean history log

**Comment by jesusprubio** [comment]
@maturanomx I can't see that requirement in the CONTRIBUTING file. So, for convenience, I prefer to use the GitHub button. :smile_cat:

**Comment by derrickmehaffy** [comment]
@jesusprubio please do not manually merge the master into PR's, @lauriejim will do so when he merges the PR.

It is just common courtesy so you don't make a mess of the commit history.

**Comment by jesusprubio** [comment]
Done, then should I rebase or not?

**Comment by derrickmehaffy** [comment]
It's fine to leave it "out of date" for now

**Pull request merged**
