### PR TITLE
fix: Added a gap between the 2 icon buttons

### PR DESCRIPTION
**Pull request by lucasboilly**
### What does it do?

I added a gap between the 2 icon buttons of the media library modal (add new assets).

### Why is it needed?

It's only a UI issue but it makes it look less "buggy".

### How to test it?

Go to the edit view, find an empty media input and click on it.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/20772

### CODE REVIEW

**Review by simotae14 — CHANGES_REQUESTED** [review]
The code looks good but you need to run the unit test to update the failing snapshoot, and you also have a commitlint issue because of the format of your commit, you need to follow this convention https://github.com/conventional-changelog/commitlint/#what-is-commitlint

**Comment by remidej** [comment]
We can merge despite the commitlint error, but as Simone said the snapshot fix is mandatory. You can run this command in your Strapi repo then commit the changes it made for you: `yarn test:front:update`

**Comment by lucasboilly** [comment]
Hey @simotae14 and and @remidej  it seems the issue is fixed (only the commitlint issue remains).

**Review by simotae14 — APPROVED** [review]
well done @lucasboilly

**Pull request merged**
