### PR TITLE
Validate boolean is not null when required

### PR DESCRIPTION
**Pull request by ThewBear**
### What does it do?

Validate the boolean form value against `null` instead of `undefined`

### Why is it needed?

Since the boolean is nullable. The `is required` validation error never show up because it will be initialize with `null` instead of `undefined`.  For more information, see https://github.com/strapi/strapi/issues/9013#issuecomment-757755285

### Screenshots

Validation error

The off state will be fixed in strapi/buffet#175

### Related issue(s)/PR(s)

#4059
#9013

### CODE REVIEW

**Comment by petersg83** [comment]
Hi,

Thanks for you contribution!

I don't really understand, what problem does your PR solve? Do you have some steps to reproduce the problem?

**Comment by ThewBear** [comment]
@petersg83 
1. Create a collection type that has two fields.
  - string
  - boolean with default value as `null` and **required**
2. Create a new entry, type value only in string field and save.
3. Click Publish and there will be a validation error but no error message at the boolean field.

**Comment by petersg83** [comment]
Thank you! I could reproduce, thanks :)
I let @HichamELBSI and @soupette review it :)

**Review by soupette — APPROVED** [review]
LGTM

**Review by HichamELBSI — APPROVED** [review]
LGTM

**Pull request merged**
