### PR TITLE
add koa-range to support range headers for media streaming

### LINKED ISSUE #2246: Adding Range header to video/audio file
**Informations**
- **Node.js version**: 10.6.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: mongo
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**

Video/Audio files not working in Safari 9+

**Steps to reproduce the problem**

This could fall under a feature request, though I assume users would expect video/audio files to work in Safari out-the-box.

On a clean installation upload an MP4 file from the Strapi dashboard.
Click record to copy file location to clipboard and then paste in Safari.
Video does not stream.

**What is the expected behavior?**

It should stream the video as it does in Chrome and IE

**Tested**

Tested opening video in Safari from desktop to ensure it's not an encoding/corrupt file issue.

**Suggested solutions**

After some research it seems the solution would be to add `Range` to request headers for these file types as this is now seems mandatory in Safari.

Thanks

### PR DESCRIPTION
**Pull request by birdm4n**
#### Description of what you did:

Included koa-range (https://github.com/koajs/koa-range) into core strapi package to strapi provides range headers for media uploaded to strapi and requested for streaming (e.G. videos). 

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #2246
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [X] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [X] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

**Comment by alexandrebodin** [comment]
I'm closing this PR as we are not accepting new default middlewares in Strapi for now to avoid adding too much overhead by default

**Comment by birdm4n** [comment]
I understand. But then please implement adequate range headers. The middle ware would not be necessary in the first place, if it was implemented on your side!

**Comment by alexandrebodin** [comment]
I understand your point. 
I think we only need to change the upload-plugin to serve the files with the right headers. If you are willing to take a look at the strapi-plugin-upload go ahead. I'll also do some testing later this week.

Right now your best bet is simply to add the middleware in your app.
I would recommend you use a CDN to host your videos if you want proper perf and robustness for video streaming.

**Comment by FrancisVarga** [comment]
The easiest and most performant way is upload to s3 and stream it over CF or CFM.

**Pull request closed without merging**
