### PR TITLE
Resizing fields in edit view

### PR DESCRIPTION
**Pull request by web-mi**
strapi_resize

### What does it do?

- Cleanup content-manager (DraggedField to flex without absolute positioning, duplicated css, Tooltip.js not used/working anymore)
- Added resize function to edit view fields except dynamiczones and components (minSize: 2, maxSize: 12)

### Why is it needed?

Using 50% of the remaining space for a single dropdown or radio button makes editing complicated because much space is wasted.

### How to test it?

Edit view of any component. A new button is shown at the end of the fields. By dragging the element the field could be resized to any size between 2/12 and 12/12. 2/12 instead of 1/12 because 1/12 is to small for description and buttons. Maybe someone has an idea how to handle too small elements.

### Related issue(s)/PR(s)

Issues: #8094, #8950
Strapi Community Discussion: 
https://forum.strapi.io/t/change-width-of-fields-on-edit-page/181
https://forum.strapi.io/t/columns-in-content-manager-detail-view/1011/2

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
This pull request has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/columns-in-content-manager-detail-view/1011/12

**Comment by derrickmehaffy** [comment]
This pull request has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/change-width-of-fields-on-edit-page/181/4

**Comment by sirdavidoflee** [comment]
Any movement on this? This would be a great feature to have in the CMS and would be especially helpful for Content Managers in my organization.

**Comment by timosnel** [comment]
We would also be helped greatly if this feature gets released.

**Comment by web-mi** [comment]
I'm currently using it with /extensions but one single file is not overrideable and that is the one which will reset all resized fields on "yarn build".
So don't resize all fields because its only unitl your next release / build! ;-) 
[PR_9898.zip](https://github.com/strapi/strapi/files/6397830/PR_9898.zip)

**Comment by web-mi** [comment]
Yes. Thats because its better to get the review done. Then the reset problem should be gone. ;-)

**Comment by jhammond2012** [comment]
+1

**Comment by Messa1** [comment]
What is status of this pr? Would be a awesome feature for strapi.

**Comment by aminta** [comment]
+ 1

**Comment by sam-pires** [comment]
Hello,

Thanks @web-mi for the PR and everyone else for the interest 🙂 

We really like this feature and the possibilities it introduces to customize the view. Though, for the moment we have to wait a bit before fully evaluating the possibility to merge it. And we probably won't be able to merge it as it is. And that for 2 main reasons:
- We are currently working on the v4 and the new Design System implementation. As part of this work, we are working on the Content Manager on both the List and Edit views and making some technical and layout changes. So first we'll need to finish that to see how the PR works with it and how we (you and us) can adapt it.
- Before being able to accept a feature such as this one, we'll have to work a bit on the specs in order to make sure we manage well all the edge cases and that the way it is implemented in the PR in fully compatible with the User Experience we want to offer 🙂  

We totally want to add more flexibility and customization possibilities in the Edit view, it's in our plans and this PR is a good starting point, but we'll have to work on it together. So let's wait until the end of the Quarter, once the v4 and the Design System are released, and see how to make it work 🙂

**Comment by sam-pires** [comment]
And I feel questions on the v4 coming haha 😄  so here's some info:

- There will be an Alpha release in August, followed by a Beta.
- Until then, what I can tell regarding the Edit view is that we'll change the layout a little bit to make it easier to manage and display the Relations and at the same time to start making more room for plugins...

**Comment by derrickmehaffy** [comment]
Hi 👋  
We now have released the `v4`. As of now, the `v3` is in maintenance mode for 6 months. We will only be fixing critical and security issues on v3 from now on. 
I will go ahead and close this PR. Thank you for contributing to Strapi 🔥 

---

PS I would really love to see this refactored for the v4. This PR is awesome if we could add it.

**Comment by marianhlavac** [comment]
I was actually kind of hoping that v4 will have this functionality already included.

At this point, is the author (@web-mi) willing to refactor this for v4, or should someone else take over?

**Comment by derrickmehaffy** [comment]
> I was actually kind of hoping that v4 will have this functionality already included.
> 
> At this point, is the author (@web-mi) willing to refactor this for v4, or should someone else take over?

If anyone else wants to take over there is no reason to hold out for the original author unless they speak up.

**Comment by web-mi** [comment]
Hi together,
i made this pr and another (#9865) for a client where i need these features because editing was a mess on huge pages.
And because its open source i made the changes on my own bill and published everything.
Long time i didn't get any reply or a reply that v4 will be released. 
Then both pr get closed after 9 months and as i read these features are still missing.
Currently i got no time to build and test everything again and currently no need for it anymore.
If someone will take over the idea and code is still here but unfortunately i'm out sorry. ;-)

**Comment by derrickmehaffy** [comment]
> Hi together, i made this pr and another (#9865) for a client where i need these features because editing was a mess on huge pages. And because its open source i made the changes on my own bill and published everything. Long time i didn't get any reply or a reply that v4 will be released. Then both pr get closed after 9 months and as i read these features are still missing. Currently i got no time to build and test everything again and currently no need for it anymore. If someone will take over the idea and code is still here but unfortunately i'm out sorry. ;-)

I'm sorry to hear that and I know we certainly did not do the best we could on getting this and #9865 looked at in a reasonable amount of time and I'll be sharing that feedback with the team to hopefully not let this happen again in the future.

**Comment by urbandale** [comment]
#9865 solved a  major pain point for our customers. Long pages are normal in websites. When the editors (our customers) cannot do their job, then they are not wanting to wait. This reflects then bad on Strapi and puts us in a hard position to defend the Strapi framework since the customer uses most of all the editing features.  #9865 was really an "easy" fix (thanks @web-mi) – it calmed our customer and made them feel we were not dragging them through some Open Source Hell for the benefit of the programmer's enthusiasm. Now we are torn between not upgrading to v4 and upgrading and losing their patience... 
BTW – Another feature they would REALLY like to see and cannot understand why it does not exist is being able to drag elements up and down on the page to change their position... but that is another topic...

**Pull request closed without merging**
