### PR TITLE
Remove `request` dependency

### PR DESCRIPTION
**Pull request by gu-stav**
### What does it do?

Removes `request` and replace it with `node-fetch`.

### Why is it needed?

Users are seeing deprecation messages for a long time already:

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```

We are only installing the dependency, because `request-promise-native` needs it and it only ever used to wait for the strapi server to restart in a API utility that is actually *never used*.

### Related issue(s)/PR(s)

- https://github.com/strapi/strapi/issues/14420

### CODE REVIEW

**Comment by joshuaellis** [comment]
in the `helper-plugin` theres `whatwg-fetch` could that be replaced? or would that need to be replaced with `axios`? 🤔

**Comment by gu-stav** [comment]
@joshuaellis I believe with our current browser support matrix we could even get rid of `whatwg-fetch` entirely? 🤔

**Comment by joshuaellis** [comment]
> @joshuaellis I believe with our current browser support matrix we could even get rid of `whatwg-fetch` entirely? 🤔

I think you're probably right to be honest.

**Review by Marc-Roig — DISMISSED** [review]

**Comment by gu-stav** [comment]
@Marc-Roig I had dreams about this and they turned out to be true: the utility is actually never used, which allows us to remove these dependencies all-together.

**Review by innerdvations — APPROVED** [review]
Seems fine to me, tested and works fine. But I'm not front-end so I can't speak for if it's needed there for some reason.

**Comment by gu-stav** [comment]
@innerdvations This is actually a BE dependency :)

**Comment by innerdvations** [comment]
Ahahaha, ok, in that case I approve, we don't seem to be using it

**Pull request merged**
