### PR TITLE
feat: :sparkles: add authing provider

### PR DESCRIPTION
**Pull request by willin**
### What does it do?

Add a Provider of [Authing](https://authing.cn)

### Why is it needed?

A well-known IDaaS platform in China mainland.

### How to test it?

image

### CODE REVIEW

**Comment by willin** [comment]
needs to update grant after this pr merged. https://github.com/simov/grant/pull/271

**Comment by willin** [comment]
done with `grant` https://github.com/simov/grant/commit/e172564886f10adf6e1de07d94fd86e5e501d4ae

**Comment by alexandrebodin** [comment]
Hello 👋 ,

Thank you fro contributing to Strapi!
Can you share some instructions on how to test your PR please ?

**Comment by mylesrankin** [comment]
Don't you need to define the provider in `packages/plugins/users-permissions/server/services/providers-list.js`?

**Comment by derrickmehaffy** [comment]
Closing this one for inactivity, @willin if you can provide instructions to test your PR we can reopen.

Thanks!

**Pull request closed without merging**
