### PR TITLE
Fix #17875 - Missing schema in validateQuery after upgrading to v4.13.1

### LINKED ISSUE #17875: Missing `schema` in `validateQuery` after upgrading to `v4.13.1`
### Required System information

- Node.js version: `v20.5.1`
- NPM version: `v9.8.1`
- Strapi version: `v4.13.1`
- Database: `PostgreSQL`
- Operating system: `macOS`
- Is your project JavaScript or TypeScript: `TypeScript`

### Describe the bug

Missing `schema` in `validateQuery` after upgrading to `v4.13.1` when trying to `findOne` and `find` a content type that has media attribute. When trying to get data from REST API, I know I need to use `?populate=*`, but when I try to query using GraphQL plugin, I get this error.

### Steps to reproduce the behavior

1. Go to GraphQL sandbox.
2. Make a query that contains the media attribute.
3. Execute the query.
4. See error.

### Expected behavior

Before upgrading to `v4.13.1`, I was using `v4.12.7`.

### Screenshots

Screenshot 2023-08-31 at 10 30 32 AM

Screenshot 2023-08-31 at 10 30 50 AM

### Code snippets

I only upgraded Strapi and its related dependencies to `v4.13.1`

### Additional context

Not applicable.

### PR DESCRIPTION
**Pull request by diacu**
### What does it do?

There's a typo, causing validateQuery to fail for queries containing media file references.

### Why is it needed?

Fix the error `Missing schema in validateQuery`.

### How to test it?

Query for any entity that has a media file relation field and include the file in the attributes.

### Related issue(s)/PR(s)

fixes #17875

### CODE REVIEW

**Review by marcoautiero — COMMENTED** [review]
Impressed.

**Review by marcoautiero — APPROVED** [review]

**Review by Bassel17 — APPROVED** [review]
LGTM,
A silly mistake from our side

**Comment by derrickmehaffy** [comment]
I am generating an experimental version so users can test with it: https://github.com/strapi/strapi/actions/runs/6051019399

**Comment by derrickmehaffy** [comment]
Experimental Version: `0.0.0-experimental.f0f8d365a96bb312d6f9e8f40d6cdd061b9a2892`

**Review by derrickmehaffy — APPROVED** [review]
I have tested the experimental and it works properly.

**Comment by mauriciabad** [comment]
This issue should have been prevented with proper TypeScript setup...

**Comment by LucaNerlich** [comment]
you are a live saver, thanks a lot!

**Pull request merged**
