### PR TITLE
Fix package 'strapi-generate-new' on Windows

### PR DESCRIPTION
**Pull request by Nsbx**
I maked a condition to launch the correct command on windows.

fix to this issue : https://github.com/strapi/strapi/issues/468

### CODE REVIEW

**Comment by ArkhipovK** [comment]
May be its better to use more unitized variant like this one.
https://github.com/shelljs/shx

I suppose, that similar functionality will become necessary again in future.

**Comment by lauriejim** [comment]
Hi @Nsbx thank you for this PR.

To remove files, we will prefere use `shelljs` node modules which is already used in `setup.js` script.
https://github.com/strapi/strapi/blob/master/scripts/setup.js#L30

Can you update your PR with this node modules and confirm me it works ?

**Comment by Nsbx** [comment]
Hello @lauriejim 
The change is done and is work on my Windows :)

**Comment by lauriejim** [comment]
Well done @Nsbx  !

**Comment by Nsbx** [comment]
image

From a French dev, Please find somewhere else to exist

**Pull request merged**
