### PR TITLE
Manage tokens having the same name

### PR DESCRIPTION
**Pull request by simotae14**
User Story description

💬 User story 
As an admin user managing API tokens, I want the alert message “Name already assigned to another token” to be shown when I’m trying to assign to a token a name already assigned to another token, so that I can have a better understanding of the reason why a token is not saved. 

📍 Context 
At the moment, when the admin user try to save a token with a name already assigned to another token a general message of error is displayed. 

☑️ Acceptance criteria 
 - As an admin user 
   - when I save a token with a name already assigned to another token 
     - then I want the alert box to be displayed with the message “Name already assigned to another token”

### CODE REVIEW

**Review by ronronscelestes — COMMENTED** [review]
alert message properly showing with the right error!
I'm wondering if it would be better to show the message as field error instead of an alert, I think `setErrors` from `Formik` could help for that, wdyt?

**Comment by simotae14** [comment]
Thanks julie, to be honest we are good with the alert type...it is something that already we used for other fields

**Review by ronronscelestes — APPROVED** [review]
LGTM

**Review by Convly — APPROVED** [review]
QA: LGTM, works well functionally

**Comment by Convly** [comment]
You might want to have a look at the failing E2E tests though :eyes:

**Pull request merged**
