### PR TITLE
[Data Transfer] Select http/https module based on protocol in local provider

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

Switches protocol based on url

### Why is it needed?

Currently export is broken in some cases (can't reproduce when) because the `https` module is throwing an error on urls that start with "http:"

### How to test it?

Run an export with files and it should work.

Note: I couldn't reproduce the original error, but the [reported issue](https://github.com/strapi/strapi/issues/17481) makes sense. So if someone can reproduce and then test that this PR fixes it, that would be great :)

### Related issue(s)/PR(s)

Fixes https://github.com/strapi/strapi/issues/17481

### CODE REVIEW

**Comment by innerdvations** [comment]
> The code LGTM. Will need to reproduce & QA though. Let's not merge it until we've successfully QAed it.

Yeah, it makes sense to me given the description of what failed and what works, but I can't reproduce. I imagine it's a specific combination of versions that I didn't have time to test myself.

**Review by christiancp100 — APPROVED** [review]
LGTM

**Comment by innerdvations** [comment]
On second thought, why are we using http/https directly instead of using our request wrapper? 🤔

**Comment by innerdvations** [comment]
Has anyone who has been able to reproduce the original bug tested this PR? I don't want to merge it if it doesn't actually do anything.

**Pull request merged**
