### PR TITLE
Added support in email plugin for Mailgun and Sendgrid

### PR DESCRIPTION
**Pull request by AustinBratcher**
My PR is a:

💅 Enhancement

Main update on the:

Plugin (Email)

Added basic support for using Mailgun and Sendgrid (as opposed to the Sendmail) package in the email plugin. Configuration is done in plugins/email/config/settings.json.

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello @AustinBratcher ! Awesome PR 💪 !
Just some suggestion I would like to share with you to make this feature better.

To make the email plugin more extendable (like the upload plugin) it's could be nice to transform the `strapi-plugin-email` like an hub that receive functions of email providers you want.

Can you check how the plugin email work.
We load all upload providers on server start https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/config/functions/bootstrap.js depending of some configs.

And then on upload action we use the provider function to upload the file https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/services/Upload.js#L56

Like this way everyone is able to use any provider he want without updating the core email plugin.

Issue related: https://github.com/strapi/strapi/issues/911

Feel free to join [Slack](https://slack.strapi.io) to chat of this update.

**Comment by AustinBratcher** [comment]
Thanks for the feedback @lauriejim ! 

I briefly looked into following the bootstrap pattern in the upload plugin. I'm relatively new to the react/redux world, so I saw the settings.json method as a quicker way to get some feedback on the modifications. I'll keep working on it and try to make it a bit more like the upload plugin!

**Comment by indiecore-fm** [comment]
Thanks for you amazing addition!

**Comment by lauriejim** [comment]
@AustinBratcher Can you add a paragraph in the documentation about configurations and usage.

Make a duplicate of this file for the example [Upload](https://github.com/strapi/strapi/blob/master/docs/3.x.x/en/guides/upload.md) and don't forget to add the page in the menu here [Menu](https://github.com/strapi/strapi/blob/master/docs/3.x.x/en/SUMMARY.md)

I will rewrite this plugin to make it more flexible like the upload file plugin.

**Comment by lauriejim** [comment]
Just to let you know.
We are talking with @AustinBratcher on Slack about making this feature more extensible. So the code will be updated.

**Comment by AustinBratcher** [comment]
PR updated, but looks likes like the Travis build is failing because of a new dependency I added to the email plugin --- strapi-email-sendmail. It's intended to be an npm package much like strapi-upload-local. What's the best way to role that in to avoid the travis build fail?

**Comment by lauriejim** [comment]
@AustinBratcher Thank you for this update. Let me take a look this week end. I will give you some feedback !

**Comment by lauriejim** [comment]
@AustinBratcher I fixe the setup issue.

**Comment by AustinBratcher** [comment]
Excellent. Anything else I need to do to clean up the PR?

**Comment by lauriejim** [comment]
I'm actually not able to display the config page. And I can't start admin in dev mode.

**Comment by lauriejim** [comment]
I remove some useless code.

**Comment by lauriejim** [comment]
@AustinBratcher please check points that @soupette highlight. And then it's ready to merge.

I tested it and it works really well. Nice job !

**Comment by AustinBratcher** [comment]
@lauriejim , sorry for the slow response. Looks like you beat me to fixing the issues. Anything else need to be done?

**Comment by lauriejim** [comment]
Hey @AustinBratcher. Yes I did it. It take just few minutes.
Waiting for @soupette approval this morning and then merge.

**Comment by mnlbox** [comment]
@AustinBratcher Guys I can't find Mailgun on plugin setting in dashboard. Is it only support Sendgrid?

**/CC:** @soupette

**Comment by AustinBratcher** [comment]
@mnlbox Did you install in the strapi-email-mailgun package?

**Comment by mnlbox** [comment]
@AustinBratcher No. Where is it? Is it any documentation available for this plugin? (strapi mail)

**Comment by AustinBratcher** [comment]
@mnlbox The email plugin works just like the upload plugin. You can add configurations by installing packages prefixed with "strapi-email-*". 

`npm install --save strapi-email-mailgun`

After installing the package, the configuration option will show up in the admin panel.

**Comment by mnlbox** [comment]
Thanks man :wink:

**Comment by lauriejim** [comment]
You can check here for the documentation https://strapi.io/documentation/guides/email.html

**Pull request merged**
