### PR TITLE
Refactoring API tokens v2 frontend code

### PR DESCRIPTION
**Pull request by simotae14**
### What does it do?

Refactor and split the code of the Edit and Create pages in the Api Token Settings.

### Why is it needed?

Because the code was huge in just one component, we need to split it and have a more readable code.

### How to test it?

We need to test all the possible combinations and possibilities with Api token to check some regression errors.

### CODE REVIEW

**Review by ronronscelestes — COMMENTED** [review]
Nice improvement 💃
I see one difference in behaviour between `features/api-token-v2` and `api-token-v2/refactor-api-token-v2` branches:

in `features/api-token-v2` if I choose full access or read only token type, I can still easily customize permissions and it will update token type automatically:
image
image

in `api-token-v2/refactor-api-token-v2` though everything is disabled if I choose full access or read only token types:
image

was it really wanted? I feel like the dynamic one (updating token type automatically if any change) was nice 👀

**Comment by simotae14** [comment]
Thanks @ronronscelestes we have decided to let the user choose the permissions only when the Custom type option is selected otherwise the permissions need to be disabled because for Read only and Full access we mean all the current categories and even the future added categories will be Full access or Read only.
If you want we can have a call or discuss about it in slack

Thanks again

**Review by Bassel17 — APPROVED** [review]
LGTM,
Tested the features on my side they seem to be working as expected

**Review by ronronscelestes — APPROVED** [review]
LGTM 💃

**Pull request merged**
