### PR TITLE
Enables TypeScript Support (instantly)

### PR DESCRIPTION
**Pull request by ashbrener**
#### Description of what you did:

TypeScript support for Strapi has long been a critical success factor for many in this community. 

It is clear why there have been heated discussions about this across several forums, and understood why the idea of retrofitting TypeScript support through the Strapi core make a lot of us nervous, especially those who are not familiar or do not have an appreciation of TypeScript.

With that being said, we do not have to overthink a solution to this and hopefully the approval of this PR will solve 90% of the TypeScript use cases out there.

Personally, I do not need any of the generated code (controllers, models etc) to be ported in TypeScript. 
I steer clear of making any manual edits to these files.

## Approach

I have endeavored to touch the Core as little as possible. 

I do not yet have clarity on how best to approach testing, and will obviously leave documentation until the PR is approved as time is precious.

## Issues this PR addresses:

1. #630
2. #6141

## TypeScript Compilation Options

There are 2 ways to enable TypeScript in a project:

1. Appending a `--typescript` flag to the strapi CLI command eg 
```
strapi develop --typescript
``` 
This method registers [ts-node](https://www.npmjs.com/package/ts-node) support under the hood and is usually preferably suited for running in development mode.

2. Compiling using the TypeScript compiler by running a command such as:
```
tsc -p ./tsconfig.json  --listEmittedFiles --extendedDiagnostics
```
This method outputs the transpiled Javascript and source maps alongside their TypeScript parent source file.

Conceptually it is not best practise to use `ts-node` in production as there is a concern of a slight performance impact.
However in my experience if there is, it is unnoticeable.
Further, I prefer not retaining the transpiled files in my project.

## TypeScript Example Project

I have been careful to limit injection of TypeScript specific code in the overall project, and so for now have not made changes to the get started example project.
I have created a new [example project](https://github.com/ashbrener/strapi/tree/master/examples/typescript-example) to show example usage.

Namely:

[API Controller](https://raw.githubusercontent.com/ashbrener/strapi/master/examples/typescript-example/api/typescript/controllers/typescript.ts)

[Bootstrap](https://github.com/ashbrener/strapi/blob/master/examples/typescript-example/config/functions/bootstrap.ts)

[Plugin Extension](https://github.com/ashbrener/strapi/blob/master/examples/typescript-example/extensions/users-permissions/controllers/TypeScriptExample.ts)

[Hook](https://github.com/ashbrener/strapi/blob/master/examples/typescript-example/hooks/test-hook/index.ts)

[Middleware](https://raw.githubusercontent.com/ashbrener/strapi/master/examples/typescript-example/middlewares/testM/index.ts)

### New Dependencies

I am curious why the Strapi project has no `devDependencies` in `package.json` which would be the preferred reference for the TypeScript dependencies.
However I have followed protocol by adding the following to `dependencies`:
[typescript, ts-node and tsconfig-paths](https://github.com/ashbrener/strapi/blob/master/packages/strapi/package.json#L66)

### TypeScript file support

I have added support for requiring .ts file extensions (for ts-node) which provides support for the following:

1. Controllers
2. Services
3. Hooks
4. Middleware
5. Bootstrap
6. Plugins and Plugin Extension

### CLI

Addition of a new typescript flag

```
strapi start --typescript
```
[packages/strapi/bin/strapi.js](https://github.com/ashbrener/strapi/blob/master/packages/strapi/bin/strapi.js#L121)
[packages/strapi/lib/commands/start.js](https://github.com/ashbrener/strapi/blob/master/packages/strapi/lib/commands/start.js#L9)

```
strapi develop --typescript
```
[packages/strapi/bin/strapi.js](https://github.com/ashbrener/strapi/blob/master/packages/strapi/bin/strapi.js#L131)
[packages/strapi/lib/commands/develop.js](https://github.com/ashbrener/strapi/blob/master/packages/strapi/lib/commands/develop.js#L18)

### Type Declarations

It may not be necessary (or practical) to describe the entire shape of the Strapi object instance. 
The previous version left a ton of room for improvement, and I have had good shot at it though it may need expansion, and possibly some reduction as well.

[index.d.ts](https://github.com/ashbrener/strapi/blob/master/packages/strapi/index.d.ts)

## New Project Generator

Addition of 2 new files to a new base project:

[tsconfig.json](https://github.com/ashbrener/strapi/blob/master/packages/strapi-generate-new/lib/resources/files/tsconfig.json)

[Strapi object instance global namespace support](https://github.com/ashbrener/strapi/blob/master/packages/strapi-generate-new/lib/resources/files/types/global.d.ts)

## Conclusion

I have implemented a marvelously simple solution here and hoping I get support here.

All comments and contributions welcome, I look forward to helping the community accelerate this process and have it included in the core as quickly as possible.

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Hello thank you for your PR.

Here are a few comments:

- I really don't think strapi should be loading any typescript file at runtime.
 `ts-node/register` is not to be used for production usage. typescript should be compiled and then run by strapi.

- Typescript should not be added as a dependency of Strapi but to the generated projects instead.

- We just need to support loading files from a specific directory so a user can have a src and a dist dir and tell strapi to run the dist dir.

We would just need to update the generators to add a typecript option and add the npm scripts to run strapi develop / start etc.

**Comment by ashbrener** [comment]
@alexandrebodin thank you for your comments.

As stated in my description above I agree with you that it is not best practise to register `ts-node` in production. However in my experience this decision varies between developers. Accordingly in my PR `ts-node` will only be registered `--typescript` flag is present in the CLI command. Arguably if this is a concern, it may be worth only allowing the `--typescript` flag on the `strapi develop` command. Personally I do not wish to manually compile with `tsc` everytime I run the server in development mode. Equally the watcher will then need to trigger `tsc` every time a .ts file changes.

I agree it would be better to require typescript and associated dependencies in the generated projects.

Compiling typescript to a dist dir separates (alienates) it from all other code scripts where it could happily coexist. As per my description above if one runs `tsc` the source is compile in place and sits next to the original TyperScript source file.

**Comment by alexandrebodin** [comment]
> @alexandrebodin thank you for your comments.
> 
> As stated in my description above I agree with you that it is not best practise to register `ts-node` in production. However in my experience this decision varies between developers. Accordingly in my PR `ts-node` will only be registered IF the`--typescript` flag is present in the CLI command. Arguably if this is a concern, it may be worth only allowing the `--typescript` flag on the `strapi develop` command.

- adding --typescript option in the commands is not a good solution. You should generate it once with a ts option and that's it. adding those option on other commands couples Strapi with typescript too strongly.

> Personally I do not like to manually compile with `tsc` everytime I run the server in development mode. Equally the watcher will then need to trigger `tsc` every time a .ts file changes.

- The only way to address that issue would be to allow loading ts files dynamically. I would be willing to allow this if we upgrade strapi bootstraping to customize the file loading system like you would do with the webpack config . But loading ts files and requiring ts dependencies in strapi core is not an option.

> I agree it would be better to require typescript and associated dependencies in the generated projects.

> Compiling typescript to a dist dir separates (alienates) it from all other code scripts where it could happily coexist. As per my description above if one runs `tsc` the source is compile in place and sits next to the original TyperScript source file. This is actually similar to making changes to entities in Strapi admin which regenerates .js code files in the project.

- This is a matter of configuration, if strapi is told to load form for example `./app` and you compile the `app` folder in place it will work juste fine it will just load the compiled js files if you prefer

**Comment by ashbrener** [comment]
> adding --typescript option in the commands is not a good solution. You should generate it once with a ts option and that's it. adding those option on other commands couples Strapi with typescript too strongly.
> 

* This makes sense.

> The only way to address that issue would be to allow loading ts files dynamically. I would be willing to allow this if we upgrade strapi bootstraping to customize the file loading system like you would do with the webpack config . But loading ts files and requiring ts dependencies in strapi core is not an option.

* Yes you could do it like webpack. In fact it maybe sizable task but you could also structure the entire project in a `src` / `dist` model that merges the admin build process. That is `strapi build` would webpack build the entire project into a `dist` folder including admin where production can be run from.

Another simple way to abstract typescript is with a new `strapi-typescript` package that when included in the command line enables typescript. Example:

```NODE_OPTIONS="--require strapi-typescript/register" strapi develop```

**Comment by ashbrener** [comment]
@alexandrebodin latest commit has the following changes:

1. Removed all Typescript references from Strapi core:

- `ts-node` and `tsconfig-paths` registration 
- CLI `--typescript` flag

2. Moved `typescript`, `ts-node` and `tsconfig-paths` dependencies from Strapi core to the `strapi-generate-new` package.

3. In typescript-example project added `ts-node` registration to NPM develop script, eg:

```NODE_OPTIONS="--require ts-node/register" strapi develop```

**Comment by alexandrebodin** [comment]
Hello @ashbrener can you cleanup the example app so it only contains one api and one model ? it would be easier to review and we won't have to maintain two duplicates of the same app

**Comment by ashbrener** [comment]
Hi @alexandrebodin are you happy with a separate example app or do you want me to simply include a TypeScript API controller in the getstarted project ?

**Comment by alexandrebodin** [comment]
Separate examples are fine and easier to read for the community :) If you can just make it a bit simpler so we don't have to maintain it as we update the main one it would be great

**Comment by ashbrener** [comment]
👍  will do @alexandrebodin

**Comment by ashbrener** [comment]
@alexandrebodin [this is now the only API controller](https://raw.githubusercontent.com/ashbrener/strapi/master/examples/typescript-example/api/typescript/controllers/typescript.ts)

**Comment by alexandrebodin** [comment]
Hey @ashbrener sorry I don't know what happened but your branch has a lot of commits that should be here. did you pull develop or sth ?

**Comment by ashbrener** [comment]
Pulled from master. Revert ?

**Comment by ashbrener** [comment]
@alexandrebodin I have reset and reapplied some of the mods.

**Comment by santoshyadav198613** [comment]
Hi team any update here, any timeline when this will be released?

**Comment by ejferg** [comment]
So ready for this!

**Comment by ashbrener** [comment]
> loading files with ts extensions should be only enabled when we run with a specific TS option (can be an env var for ex) to avoid loading ts files when running a compiled app. 

We could detect if ts-node is running and augment file extension options if applicable.

> I would also like to see a way to no use ts-node and build in two different folders as some users to that instead.

You would then be further abstracting the Strapi file system for api controllers, middleware, hooks, plugins, extensions and so on. I would strongly recommend against.
A more popular approach would be to (webpack) compile the entire application and merge it with the admin site build into a single dist output folder.

**Comment by ashbrener** [comment]
@alexandrebodin what do we still need to do to get this across the line.

**Comment by Busin-Riccardo** [comment]
Hi team, 
I know you guys have a lot to do but please give this pull request some time since Typescript support is a deal breaker for a lot of people.

**Comment by alexandrebodin** [comment]
Hi @ashbrener 

I'm not sure I understood your comment on different folders as you are mentionning at the end that you do build your code into a `dist` folder ?
Compiling with webpack or using tsc to compile files independently doesn't change the result of having a dist folder 🤔  I must have missed sth in your explanation.

Right now I'm still not happy with seeing .ts everywhere in the loading. system... I think we should change this somehow so it is cleaner. A ts user could add the 'ts' extension to the config and update the yarn develop command to load the extension.

Maybe sth like

`./config/server.js`
```js
module.exports = () => ({
  loader: {
    extensions: ['js', 'json', 'ts']
  }
})
```

Then you can enable it in dev or prod or whatever and just add the ts-register to the bootstrap file or in the npm scripts 🤔 
this would give flexibility to only load js files in prod if the ts files are compiled in place.

**Comment by ashbrener** [comment]
Hi @alexandrebodin, to clarify I have incorporated our Strapi project as 1 of many apps inside a broader [Monorepo](https://en.wikipedia.org/wiki/Monorepo) project constructed using [Nx](https://nx.dev) by [@Nrwl](https://nrwl.io/). The Nx framework uses a series of "builders" to compile all monorepo apps to a single ```dist``` directory. 
In fact a group of us are working on an awesome custom Strapi builder for Nx which should prove very useful for many.

As you so astutely mentioned earlier in the the thread, one ideally needs to compile the Typescript to an output folder. So we achieve this in our build workflow by compiling (transpile all ```.ts``` files, and copy the remainder) to the monorepo ```dist``` directory.
With this being said, I still believe that the ```strapi build``` command should not only produce the admin client, but should rollup a compiled version of the entire Strapi server as well. Obviously this is challenging with Webpack given that the internal nature of Strapi core uses the file system to persist the data models.

Great idea being able to configure allowable file extensions, that would work well.

**Comment by ashbrener** [comment]
@alexandrebodin where to from here ?

**Comment by ashbrener** [comment]
> @alexandrebodin where to from here ?

Guys we would really like to help you and the community get this over the line.

Kindly guide us.

**Comment by derrickmehaffy** [comment]
@ashbrener Alex is currently out on vacation and we have been quite busy at the moment. We will let you know if we need anything else.

Thank you.

**Comment by alexandrebodin** [comment]
Hi @ashbrener,

 I think that implementing that `extensions` option would be the way to move forward. If we had that you will be able to load stuff however you want and based on the env too so making it possible to implement the scenarios we mentionned. 

With that we could have a good enough support for now. And start thinking at what is next for the next major versions

**Comment by Erim32** [comment]
Hi @ashbrener any update about this feature ?

**Comment by ashbrener** [comment]
I will have a look at extensions in due course when  we have some s p a c e.

In the interim, anyone who wants to have a crack at it ... feel free :)

**Comment by alexandrebodin** [comment]
Hey @ashbrener Nice to see you back here :D FYI @ascension did try some of this implementation but has be inactivte :) You can check this PR here https://github.com/strapi/strapi/pull/7803.

**Comment by derrickmehaffy** [comment]
This pull request has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/strapi-integration-with-other-typescript-aplications-in-a-monorepo/1104/2

**Comment by alexandrebodin** [comment]
Closing in favor of https://github.com/strapi/strapi/pull/9076.

**Pull request closed without merging**
