### PR TITLE
Add Arabic language ar_SA - إضافة اللغة العربية

### PR DESCRIPTION
**Pull request by runbb**
My PR is a:
+ 💅 Enhancement
+ 🚀 New feature
+ 🇸🇦 Language

Main update on the:
+ Admin
+ Plugin

Add Arabic language support to strapi
Under the name `ar_SA`

### CODE REVIEW

**Comment by lauriejim** [comment]
@runbb Thank you for this awesome PR ! 

Let me just some time to review your PR and then Strapi will have Arabic language support 🎉

**Comment by runbb** [comment]
no no, arabic flag is one of Arab world
https://en.wikipedia.org/wiki/Arab_world

you can use Saudi Arabia flag (ar_SA) for arabic

**Comment by lauriejim** [comment]
Can you rename all `ar` files to `sa` please. To get the correct 🇸🇦 flag.

**Comment by runbb** [comment]
Saudi Arabic isn't language

**Comment by runbb** [comment]
I will replace files from ar to ar_SA

**Comment by lauriejim** [comment]
@runbb You can use `ar` and update https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/containers/LocaleToggle/index.js
Add a case for `ar` to display https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/flags/4x3/sa.svg flag

**Comment by lauriejim** [comment]
The most important is to have a correct flag and somewhere we can contribute to Arabic language.

**Pull request merged**
