### PR TITLE
Respect relation items order

### PR DESCRIPTION
**Pull request by GomatoX**
### What does it do?

Solves issue mentioned here: https://github.com/strapi/strapi/issues/2166
It's simple solution to just recreate releation by given order.

### Related issue(s)/PR(s)

fixes: https://github.com/strapi/strapi/issues/2166

### CODE REVIEW

**Review by derrickmehaffy — CHANGES_REQUESTED** [review]
We will also need a solution for mongoDB.

Have you tested this on all SQL databases?

**Comment by GomatoX** [comment]
@derrickmehaffy Yes.

Example in video with MariaDB (10.5)

https://user-images.githubusercontent.com/2634448/110959429-5ae03000-8356-11eb-8401-9fbd9a2d6e0d.mov

**Comment by GomatoX** [comment]
@derrickmehaffy tested on Mongo (4.4.4), works as well.

**Comment by GomatoX** [comment]
@derrickmehaffy any updates?

**Comment by derrickmehaffy** [comment]
@GomatoX This will need a review from our engineering team once they have some free time. At the moment we have all engineers focused on I18N. Once that is finished they should have some time to review PRs

**Comment by GomatoX** [comment]
@derrickmehaffy any news? or I should close this PR?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy any news? or I should close this PR?

I'm not sure what the status is with regards to our work on the v4. Someone from @strapi/maintainers will need to confirm.

**Comment by alexandrebodin** [comment]
Hello, this is only fixing one behaviour but isn't fixing all of them. We won't be merging this as is for now. We are currently focusing on v4 we will probably need to remove it as it is a broken feature to figure out new way to implement it as we will change part of the relation management

**Comment by GomatoX** [comment]
@alexandrebodin so if it's still broken feature so it wont do it less bad, so from my perspective having working feature (even if it's out of desing, especialy if it's not breaking enything) is better than having feature whitch is not working at all.

**Comment by derrickmehaffy** [comment]
Hi 👋  
We now have released the `v4`. As of now, the `v3` is in maintenance mode for 6 months. We will only be fixing critical and security issues on v3 from now on. 
I will go ahead and close this PR. Thank you for contributing to Strapi 🔥

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy Is there a ticket / branch to implement this feature in v4?
> It would really help me in some use cases in my project. But the issue of not respected reference order is there in v4, too. 🤔 

No not at this time, no one (us or the community) have started work on it.

**Comment by NicoHof** [comment]
> > Hi @derrickmehaffy Is there a ticket / branch to implement this feature in v4?
> > It would really help me in some use cases in my project. But the issue of not respected reference order is there in v4, too. 🤔
> 
> No not at this time, no one (us or the community) have started work on it.

@derrickmehaffy Thank you for your fast feedback!

In the end I think it isnt a bug and neighter critical.

Probably its a valid workaround to create a repeatable component with a single reference field in it?
This way you can create an ordered list of references. Only downside I guess: The referenced Item does not "know" it is referenced in there. Its a one way relationship within this component.

**Pull request closed without merging**
