### PR TITLE
feat: New command 'components:list'

### PR DESCRIPTION
**Pull request by boazpoolman**
### What does it do?

It introduces a new CLI command:

```
strapi components:list
```

### Why is it needed?

Similar to the `content-types:list` command it can be handy to quickly get a list of all the available components in your Strapi installation.

### How to test it?

1. Install the PR
2. Setup your Strapi app
3. Add some components
4. Run the command and see a list of the components

### CODE REVIEW

**Comment by Boegie19** [comment]
I love it

**Comment by christiancp100** [comment]
I like this approach, but, would it make sense to create a container for this so that it fits with the other approach: https://github.com/strapi/strapi/blob/b8264edcb35f6b430b83793e548c1458e9638730/packages/core/strapi/lib/commands/actions/content-types/list/action.js ?

**Comment by boazpoolman** [comment]
I'll leave that up to you to decide. I don't know much about the container paradigm in Strapi as a whole.

I did notice while putting up this PR that `strapi.container.get('components')` doesn't return anything.

**Comment by Boegie19** [comment]
putting components into a container would be a major change

**Review by christiancp100 — APPROVED** [review]
LGTM

**Pull request merged**
