### PR TITLE
Remove node 16 tests and update all static tests to node 20

### PR DESCRIPTION
**Pull request by derrickmehaffy**
### What does it do?

Removes node 16 from matrix tests and upgrades all of our other tests to use node 20 instead of 16

### Why is it needed?

Node 16 is EOL: https://nodejs.org/en/blog/announcements/nodejs16-eol

### How to test it?

Let the tests run

### Related issue(s)/PR(s)

N/A

### CODE REVIEW

**Comment by joshuaellis** [comment]
All our engines are currently `"node": ">=16.0.0 <=20.x.x",` i'm wondering if we should edit these too, what do we think? :)

**Comment by innerdvations** [comment]
Yeah, I think we should block it at the same time, because as soon as someone adds code that is node18+ only, it will break node16 anyway. But there's no rush here, we could add a release note in 4.14 saying "we will remove node 16 support in strapi 4.15" to give people some warning, and then remove it.

**Comment by derrickmehaffy** [comment]
> Yeah, I think we should block it at the same time, because as soon as someone adds code that is node18+ only, it will break node16 anyway. But there's no rush here, we could add a release note in 4.14 saying "we will remove node 16 support in strapi 4.15" to give people some warning, and then remove it.

Good idea, I'll adjust this PR to do that on Monday and I'll update the release notes.

We could probably give people a bit more lead time and delay this to 4.16 instead.

**Comment by innerdvations** [comment]
Note: we added the deprecation warning to today's release (4.14.4) and will release this in 4.14.5

Given that, I've updated the recommended versions in the README.

**Review by innerdvations — DISMISSED** [review]
LGTM!

**Comment by joshuaellis** [comment]
@innerdvations let me know if those FE tests fail again and i'll take a look.

**Comment by innerdvations** [comment]
Doing final QA on this today and then merging

**Review by joshuaellis — APPROVED** [review]

**Comment by joshuaellis** [comment]
@alexandrebodin can you remove `unit_back (node:16)` as a required test? we can then merge this :)

**Pull request merged**
