### PR TITLE
Update grant-koa version

### LINKED ISSUE #2338: Update the grant-koa version
- ❌ **I have created my request on the Product Board before I submitted this issue**
- ✅ **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Update the `grant-koa` (`users-permissions` plugin) to `v4.0`: [Grant changelog](https://github.com/simov/grant/blob/master/CHANGELOG.md).

https://github.com/strapi/strapi/blob/b16fd8c452d7d7f7a16ba6ae5b204a27855a0041/packages/strapi-plugin-users-permissions/package.json#L26

### PR DESCRIPTION
**Pull request by abdonrd**
My PR is a:

🐛 Bug fix

Main update on the:

Plugin

Fixes #2338

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@abdonrd any reason this was closed?

**Comment by abdonrd** [comment]
@derrickmehaffy thanks for the ping! I guess I accidentally deleted the branch.

**Comment by derrickmehaffy** [comment]
No problem 😄

**Comment by maturanomx** [comment]
Just to ask if this is tested. Been a mayor release could/should break some things.

In a quick view on the changelog, I just able to see one change in the API:

```javascript
  if (req.query.error) {} // v3.x
  if (req.session.grant.response.error) {} // v4.x
```

In the absent of testing, at least a direct confirmation that the change was tested and validated 😄

**Comment by abdonrd** [comment]
@maturanomx I have tested with Google, Twitter & one custom provider.

**Pull request merged**
