### PR TITLE
Update media thumbnails on replace

### PR DESCRIPTION
**Pull request by jhoward1994**
### What does it do?

- Provides the `updatedAt` prop to ImageAssetCard
- This ensures that the FE gets the latest image when media is replaced using https://github.com/strapi/strapi/blob/0c20c6cea2c856b7725787549e1ba887d9a06afc/packages/core/upload/admin/src/components/AssetCard/ImageAssetCard.js#L11

### Related issue(s)/PR(s)

Fixes https://github.com/strapi/strapi/issues/17283

### CODE REVIEW

**Comment by jhoward1994** [comment]
@joshuaellis @gu-stav 

Oops, I've just seen https://github.com/strapi/strapi/pull/17408 already exists

This was closed because of the failing snapshot, do you think it's okay to update it as I have here?

**Review by joshuaellis — APPROVED** [review]
Noice Thats Nice GIF

**Comment by joshuaellis** [comment]
yeah lets just do this one

**Comment by rahulc-globant** [comment]
Hi Team,
Will this fix work if S3 bucket to which we are uploading is **Private**
Because in that case we will be using signed urls and adding any parameter to already signed urls will cause signature mismatch.
@jhoward1994 @joshuaellis

**Pull request merged**
