### PR TITLE
Generic localhost address for Dockerized Strapi apps

### PR DESCRIPTION
**Pull request by sboutet06**
My PR is a:

💅 Enhancement

Main update on the:

Framework

This changes allows to run Strapi into a Docker container and expose the app to host via 0.0.0.0:1337 address. We can then access Strapi on host by using http://localhost:1337.

### CODE REVIEW

**Comment by kamalbennani** [comment]
:+1:

**Comment by sboutet06** [comment]
@lauriejim of course I can just customize the config file to my needs but, as the 0.0.0.0 basically listens to any available interface, it also works for localhost. So I thought it could be good to get Docker compatibility nearly for free.

**Comment by Aurelsicoko** [comment]
I would love to have the thoughts of @lucaperret on this one! Btw, thank you @sboutet06 for this PR 👍

**Comment by lucaperret** [comment]
You could set an environment variable `HOST` to be able for changing localhost to 0.0.0.0

**Comment by sboutet06** [comment]
@lucaperret : to me, using an env. variable would make sense if we plan to change the value or customize it but, if I'm not wrong, this address is only used when serving Strapi locally right?

**Comment by lucaperret** [comment]
It's used also in production environment:
https://github.com/strapi/strapi/blob/eeaba813e0c9120ffd7481d973ded2d86f7c1d13/packages/strapi/lib/Strapi.js#L60

**Comment by lucaperret** [comment]
hi @sboutet06, have you tried with the env variable `HOST` or `HOSTNAME` ?

**Comment by sboutet06** [comment]
Hi, not yet.
I'll give it a try by using the exact same fallback line: `host: process.env.HOST || process.env.HOSTNAME || 'localhost'` and let you know (maybe with a new pull request)

**Comment by sboutet06** [comment]
Hi,
It works using this 1 line fallback solution. I added a commit in that direction.
Pls let me know.

**Comment by lucaperret** [comment]
IMO it's not relevant to have this configuration. You can override the host configuration with these environment variable.

**Pull request closed without merging**
