### PR TITLE
Update services.md

### PR DESCRIPTION
**Pull request by derappelt**
Added entityValidator to create and update service, so it act like the default service and doesn't throw a 500 Error on invalid data.

### CODE REVIEW

**Review by alexandrebodin — APPROVED** [review]
Thanks for this update. I actually think we should link to the reference implementation in the code directly @derrickmehaffy  @lauriejim  what do you think ?

**Comment by derrickmehaffy** [comment]
I agree @alexandrebodin (as I wasn't even aware that function existed :P I thought it was handled at the query level)

**Comment by derappelt** [comment]
I've updated the code so it's more in line with the actual implementation
[entity-service.js](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/services/entity-service.js#L65)

**Comment by derrickmehaffy** [comment]
We should be sure to add this to the migration guide as well for 3.2.0 to make it easier to find and let people know to update their services.

**Comment by alexandrebodin** [comment]
@derrickmehaffy this was introduced a while back so I don't think that should go in the next migration guide :)

**Comment by derrickmehaffy** [comment]
Aye but no one was aware and we are changing the docs to add it in for overriding the core controllers > hence the migration guide.

I've helped a lot of people write their their own overrides and none are using that function ;p

**Comment by alexandrebodin** [comment]
I think the only thing we should do is use a tool to embed the code directly from github or something. this would always be up to date this way

**Pull request merged**
