### PR TITLE
[fix]: use explicit imports for fontawesome in order to decrease bundle size.

### LINKED ISSUE #14572: [RFC] Consider removing font-awesome
## Discussion report

I've been doing some investigations around bundle size (namely the design system and it's integration with the admin application) and noticed how large the `fortawesome` package is (see image below)

CleanShot 2022-10-07 at 11 09 10@2x

It accounts for ~40% of the bundle size, I appreciate it's been chunked but i'm wondering if it's _really_ necessary to use an external library? (side note) are we lazy loading its usage? Could we find either a leaner library or one that's significantly smaller etc, or perhaps enhance the `@strapi/icons` and use that.

If we want to tackle the bundle size that we pass to the client really then this topic needs to be approached.

### Steps to reproduce the behavior

1. run `yarn analyze:bundle` in `packages/core/admin`
2. see report and investigate yourself.

cc @gu-stav / @ronronscelestes / @maevalienard

### PR DESCRIPTION
**Pull request by CleberRossi**
### What does it do?

Found this discuttion about the size of the bundle. 

https://github.com/FortAwesome/react-fontawesome/issues/70

We need to import expliciting the component want in order of the webback be able to  only import what you need. 

Following issue recomendation from FortAwesome github, issue 70. https://github.com/FortAwesome/react-fontawesome/issues/70

Just changed the way the components are imported: 
from
`
import { faQuestion,faTimes } from '@fortawesome/free-solid-svg-icons/'`

to 

```
import { faQuestion } from '@fortawesome/free-solid-svg-icons/faQuestion';
import { faTimes } from '@fortawesome/free-solid-svg-icons/faTimes';
```

Look at the icons that were "changed"
image

### Why is it needed?

Make bundlesize smaller. 

### How to test it?

run yarn analyze:bundle in packages/core/admin
see report and investigate yourself.

before:
image

after:
image

result: 

4.34 MB to  642.77 KB  -> 93% do decrese of this package
### Related issue(s)/PR(s)

Fixes #14572

### CODE REVIEW

**Comment by joshuaellis** [comment]
The biggest issue so far is this:
 
CleanShot 2022-10-10 at 14 53 02@2x

You can no longer see / pick icons when making a component.

**Comment by gu-stav** [comment]
Thank you for picking this up @CleberRossi . Currently, I don't think there is a way to get rid of the dependency or make it more tree-shakeable because content editors can pick one icon for components in the CTB from all icons the library supports. The name of that icon is persisted in the database and will be used to display an icon in the CM.

That means: without design changes, there is no way to remove FA from the CTB and CM bundle. I think a good first step would be to isolate the dependency to be only used there so that it doesn't need to be loaded e.g., in the onboarding.

Would you like to work on that?

Internally we need first to discuss and come up with a solution: 1) to make components visually distinct from each other so that content editors can distinguish them 2) create a migration path for the existing icon names in the DB.

**Review by gu-stav — CHANGES_REQUESTED** [review]
Thank you for picking this up @CleberRossi . Currently, I don't think there is a way to get rid of the dependency or make it more tree-shakeable because content editors can pick one icon for components in the CTB from all icons the library supports. The name of that icon is persisted in the database and will be used to display an icon in the CM.

That means: without design changes, there is no way to remove FA from the CTB and CM bundle. I think a good first step would be to isolate the dependency to be only used there so that it doesn't need to be loaded e.g., in the onboarding.

Would you like to work on that?

Internally we need first to discuss and come up with a solution: 1) to make components visually distinct from each other so that content editors can distinguish them 2) create a migration path for the existing icon names in the DB.

**Comment by CleberRossi** [comment]
@gu-stav and @joshuaellis If it is possible, I can work. 

I am still looking how to do it dynamically because I saw somenone imported the all.js inside globalstyles, however there is no documentation in fortawesome. So I think, MAYBE,  it is possible to do it using webpack.config which would reduce the bundle. 

I am trying to do it. Will let you know soon.

**Comment by joshuaellis** [comment]
I think we should close this PR for now, we need to solve the issue internally with design help and a separate PR can be made for Gustav's comments :)

**Pull request closed without merging**
