### PR TITLE
[Docs] Set build onbrokenlinks to throw

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

Throws errors when broken links are found rather than warning

### Why is it needed?

To prevent broken links from making it into the docs

### How to test it?

Try adding a broken link and then `yarn build` in /docs and it should throw an error.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/pull/17114

### CODE REVIEW

**Review by joshuaellis — DISMISSED** [review]
CleanShot 2023-06-27 at 16 28 48@2x

definitely works

**Comment by innerdvations** [comment]
@joshuaellis vercel deployment automatically failed, maybe that's why this wasn't set to throw? I don't have time to look into this but I'll leave it open to investigate later

**Comment by innerdvations** [comment]
> it failed cause it has broken links 😄 I can try take a look & build on this PR too.

Ah, ok, I don't think I can see the actual error just that it failed. Locally I don't seem to have any broken links, but if I can get into vercel and check it should be easy to fix.

**Comment by innerdvations** [comment]
The issue is that vercel only deploys the /docs folder but the /docs folder is attempting to load CODE_OF_CONDUCT and CONTRIBUTING from the root of the monorepo.

**Comment by alexandrebodin** [comment]
Going to close this as staled. feel free to reopen if needed

**Pull request closed without merging**
